### ISSUE TITLE
a few issues i encounter in V. endevour

### ISSUE THREAD

**Issue by Fullbustr** [skyarkhangel/Hardcore-SK#1001]
![image](https://user-images.githubusercontent.com/29687378/27515004-0a07c6b4-599a-11e7-8289-5b42e45c5490.png)

As shown in the image for some reason simple clothing requires chitin instead of components. geussing its just a bug in the recipe ( several clothing recipes got this issue) also wondering if its only me that has this since its rather annoying bug.

![image](https://user-images.githubusercontent.com/29687378/27515018-53841fb8-599a-11e7-84f7-469a796ab9d0.png)
Colonist cant repair or do maintance on dubs hygiene toilet bath probable showers. tech fixable by rebuilding it everytime it breaks down or staying low tech for hygiene waste need.

Wondering if its normal that there is no number tab in hardcore-SK V.endevour and make until certain treshold were the lower breaket went.

thanks in advance if ya could fix these.
btw Great modpack really puts the thumb screw on the early game.

**Comment by Fullbustr** [comment]
kk seem the bug is a bit more complex then i first thought
1 the recipes are wrong like you see in the above screenshot
2 the pawns dont seem to notice it and make the stuff/ repair it when they feel like make it.
3 can't manual order them to make the clothing cause then they try to use the bugged recipe that I can see.

**Comment by sidfu** [comment]
the issue with the hygine is probaly cause the minefiable being on it. it was removed from them in a 16 due to issues try this o see if it helps.
[Buildings_Hygiene.zip](https://github.com/skyarkhangel/Hardcore-SK/files/1100509/Buildings_Hygiene.zip)

it goes in Mods\Dubs Bad Hygiene\Defs\ThingDefs_Buildings

**Comment by Fullbustr** [comment]
Seems to have fixed them ignoring the repairing on it.
thx for the help.
