### ISSUE TITLE
lag with override haul priority

### ISSUE THREAD

**Issue by reaper0022** [skyarkhangel/Hardcore-SK#1006]
[output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/1103872/output_log.txt)

not 100% sure if the lag is directly from "override haul priority" but when i stop using it no lag

found at end of the log file 
or
line 3732 

Jessa started 10 jobs in one tick. newJob=HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73) jobGiver=RimWorld.JobGiver_Work jobList=(HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73)) (HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73)) (HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73)) (HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73)) (HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(127, 0, 77)) (HaulToCell A=Thing_ChunkGranite234561 B=(124, 0, 73))  lastJobGiver=RimWorld.JobGiver_Work

**Comment by skyarkhangel** [comment]
Fixed
