### ISSUE TITLE
Ammo Crafting Table & Heavy Arms Lathe - works without power

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#104]
[Ammo Crafting Table](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L4678)
[Heavy Arms Lathe](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L4745)
Забыли прописать потребление енергии.
Описание у обоих одинаковое

**Comment by kaptain-kavern** [comment]
Right, they bock lack the `<li Class="CompProperties_Power">` tag. If I had know what they're supposed to consume I had done the changes myself , but I think it's better @skyarkhangel done it himself

**Comment by skyarkhangel** [comment]
Both table has function to work without power with 50% workspeed debuff.
