### ISSUE TITLE
Most bakery products cannot be produced

### ISSUE THREAD

**Issue by VorChar** [skyarkhangel/Hardcore-SK#1040]
Most of the bakery products are nutrition based recipes and require flours or sugar. Flour nor sugar has nutrition so all of these recipes are uncraftable

Uncraftable recipes are (based on nutrition count):
- Taffy candies
- Blueberry pie
- Pumpkin pie
- Sweer rolls
- Pizza
- Chocolate cookies

Craftable recipes are (based on item count):
- Bread
- Caramel snacks

**Comment by pongvin** [comment]
fixed
