### ISSUE TITLE
Several groups spawning with only L-15 LMG as weapons

### ISSUE THREAD

**Issue by Discobubba** [skyarkhangel/Hardcore-SK#1045]
Title says it. Several groups of both visitors and raiders from different factions have been spawning with only L-15 LMGs as weapons. Save with issue provided in zip file.
[L-15 LMG issue.zip](https://github.com/skyarkhangel/Hardcore-SK/files/1133893/L-15.LMG.issue.zip)

**Comment by skyarkhangel** [comment]
should be fixed today
