### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mora145** [skyarkhangel/Hardcore-SK#1047]
Hey man! Do you know how to translate the wounds inflicted on the settlers?  @FaHT1k @sidfu 

![screenshot_4](https://user-images.githubusercontent.com/25883820/27999755-4c3ed586-64ee-11e7-9fec-0e1f37c639ea.jpg)

**Comment by mora145** [comment]
Bite scar, for example

**Comment by FaHT1k** [comment]
I don't know, problem with CombatExtended\Patches\Core\HediffDefs. Need help Sky or NotFood.

**Comment by skyarkhangel** [comment]
CE added to some hediffs new comp. So the number of comps increased.

From spanish:
  <Bite.label>mordida</Bite.label>
  <Bite.comps.0.labelTendedWell>vendado</Bite.comps.0.labelTendedWell>
  <Bite.comps.0.labelTendedWellInner>suturado</Bite.comps.0.labelTendedWellInner>
  <Bite.comps.0.labelSolidTendedWell>enyesado</Bite.comps.0.labelSolidTendedWell>
  <Bite.comps.2.oldLabel>cicatriz</Bite.comps.2.oldLabel>
  <Bite.injuryProps.destroyedLabel>destrozado</Bite.injuryProps.destroyedLabel>
  <Bite.injuryProps.destroyedOutLabel>perdido</Bite.injuryProps.destroyedOutLabel>

try like this:

  <Bite.label>mordida</Bite.label>
  <Bite.comps.1.labelTendedWell>vendado</Bite.comps.1.labelTendedWell>
  <Bite.comps.1.labelTendedWellInner>suturado</Bite.comps.1.labelTendedWellInner>
  <Bite.comps.1.labelSolidTendedWell>enyesado</Bite.comps.1.labelSolidTendedWell>
  <Bite.comps.3.oldLabel>cicatriz</Bite.comps.3.oldLabel>
  <Bite.injuryProps.destroyedLabel>destrozado</Bite.injuryProps.destroyedLabel>
  <Bite.injuryProps.destroyedOutLabel>perdido</Bite.injuryProps.destroyedOutLabel>

**Comment by skyarkhangel** [comment]
need to find comp number for translation.

**Comment by mora145** [comment]
yes, it is.

**Comment by mora145** [comment]
and this? 

![screenshot_7](https://user-images.githubusercontent.com/25883820/28023706-9dd86588-655c-11e7-9036-98f0883bcf7f.jpg)

**Comment by FaHT1k** [comment]
Add in Mods\MedicalTab\Languages\Spanish-SK\DefInjected\PawnColumnDef\PawnColumns_Medical.xml

	<PawnColumnDef_Consciousness.label>consciousness</PawnColumnDef_Consciousness.label>
	<PawnColumnDef_Moving.label>moving</PawnColumnDef_Moving.label>
	<PawnColumnDef_Manipulation.label>manipulation</PawnColumnDef_Manipulation.label>
	<PawnColumnDef_Talking.label>talking</PawnColumnDef_Talking.label>
	<PawnColumnDef_Eating.label>eating</PawnColumnDef_Eating.label>
	<PawnColumnDef_Sight.label>sight</PawnColumnDef_Sight.label>
	<PawnColumnDef_Hearing.label>hearing</PawnColumnDef_Hearing.label>
	<PawnColumnDef_Breathing.label>breathing</PawnColumnDef_Breathing.label>
	<PawnColumnDef_BloodFiltration.label>blood filtration</PawnColumnDef_BloodFiltration.label>
	<PawnColumnDef_BloodPumping.label>blood pumping</PawnColumnDef_BloodPumping.label>
	<PawnColumnDef_Metabolism.label>metabolism</PawnColumnDef_Metabolism.label>

**Comment by mora145** [comment]
Thx!
