### ISSUE TITLE
Blurry text & FPS drop on main menu

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#107]
размытый текст кнопок
![1](https://cloud.githubusercontent.com/assets/20729235/17785932/fb97f15a-6582-11e6-865b-50674ba708cd.png)
ванила справа для сравнения.
![2](https://cloud.githubusercontent.com/assets/20729235/17785949/089b00fe-6583-11e6-91bb-516b04a040f0.png)
томозит анимация и по ощущениям довольно сильная просадка фпс. влюбом другом меню все ок.
началось с 4.0, на 3.0 было все ок. ванила тоже ок. 
_____
1366х768, 4Gb, HD3000

**Comment by skyarkhangel** [comment]
размытость - так и задумано.
тормозит анимация. Придется сделать опцию отключения анимации, для слабых пк.

**Comment by skyarkhangel** [comment]
В последнем моем апдейте сделано, проверяйте.

**Comment by jnkyacc** [comment]
> размытость - так и задумано.
на 11 дюймах просто читать не возможно - слезятся глаза от такого :)

> В последнем моем апдейте сделано, проверяйте.
Да стало по лучше.  В целом стало на 100-200 метров меньше хавать.
