### ISSUE TITLE
Bug: Cannot butcher due to "Need materials"

### ISSUE THREAD

**Issue by PhenotypeX** [skyarkhangel/Hardcore-SK#1086]
I'm not sure of the exact steps to reproduce, but it happens every Lost Cannibal start. In the attached save I was able to get it to happen within minutes by butchering the start corpses.

I've attached the save file renamed as a .txt file to allow it to be uploaded to github.

In the save, there is a bill to butcher humanlike at the table, but it says "Need materials" when you try to force a colonist to butcher.

[Butcher Bug.txt](https://github.com/skyarkhangel/Hardcore-SK/files/1173460/Butcher.Bug.txt)

**Comment by obsidiac** [comment]
In my game, I have seen the Need Materials problem with animal corpses come and go randomly.

I have tried bills on small butcher table, and regular butcher table.  Both types of tables seem to be able to process the same corpses, and seem to be unable to process the bugged corpses.
Bills with filters set to only that type of corpse, and bills set to allow-all do not seem to make a difference.  Valid ranges also seem to not matter.

Other corpses brought in by the hauler are usually processed right away, even while the bugged corpses are stuck as "Needs Materials".

Waiting an unknown number of hours sometimes frees those corpses for butchering.

It feels to me like something has somehow claimed those corpses, even though a hauler can pick up and move these bugged corpses.

**Comment by Freshpage** [comment]
I've been watching this some more, and it seems that one way to 'unstick' the corpses is to make sure all other meat in storage is used up. I'm going to keep looking to try to work out exactly what the issue is.

**Comment by obsidiac** [comment]
I think I know what this may be:  the bill does not see enough available stockpile space for the output.  This is especially noticeable with large animals that produce more than one stack of meat.

Strangely, this happens even with Drop on Floor specified in the bill.  This part is definitely a bug.


I noticed with cooking meals that the cooks would only put 1 stack of food in a barrel then stop cooking, even though the barrel could hold 4 stacks.  When I created another stockpile that would accept more food, they started cooking more, and was willing to fill the barrel up with more than one stack of food.

So I tried this with butchering, and the same thing happened:  would say Needs Materials until a vanilla stockpile large enough to take all of the meat from a single butchering action was created.

I was able to toggle the stockpile settings and the recipe would show "Needs Materials" when not enough stockpile space was available.  Flipping fresh on and off did not reliably produce "Needs Materials" but flipping the meat type on and off did.


For storage options like skips and barrels, a workaround is to have a vanilla stockpile large enough for the output of this butchering bill.  It can be lower priority than the storage skip or barrel.

**Comment by pongvin** [comment]
this is a feature that is part of the QOL tweaks. butchering corpses is disabled is there is no storage room to store the meat, with the "need materials" error.

you can disable this in the mod options tab.

**Comment by Freshpage** [comment]
It seems the bug is possibly related to that mod. However, it is definitely a bug because even with empty storage it still happens sporadically. I have disabled "consider storage when butchering" in the mod options but this doesn't seem to have helped.
