### ISSUE TITLE
Bed pricing needs rework

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#109]
# Summary:

Stylish bed costs too little, Sleeping Pod needs evaluation for what it is supposed to do well

# . 

The 'Sleeping Pod' and 'Stylish Bed' feel like they need a rework on their pricing.

For reference of some beds below

```
Stylish bed stats: 
cost - 30 fabric or leather , 5 component
requires bedroom furniture IV
100% rest effectiveness
110% immunity gain speed
0.70 comfort

Simple bed stats:
cost - 60 fabric or leather, 5 component
requires bedroom furniture I
85% rest effectiveness
105% immunity gain speed
0.50 comfort

Luxury bed (single) stats:
cost - 10 rubber, 15 plastic, 5 component, 70 fabric
requires bedroom furniture III
100% rest effectiveness
110% immunity gain speed
0.80 comfort
```

To me it feels wrong that the stylish bed is better both in effectiveness and in cost to the simple bed, and that it is almost the same as the bed before it, losing 0.1 comfort for a significant cost reduction.

I don't know what the stylish bed should cost but it feels like it should be made more expensive.

As for the sleeping pod,

```
sleeping pod stats:
cost - 6 component, 5 medicine, 70 fabric
requires bedroom furniture IV
100% rest effectiveness
110% immunity gain speed
0.75 comfort


Pod Bed Stats:
cost - 60 cloth, 25 rubber, 25 plastic, 1 mechanism, 3 component, 70 (metal or wood or plastic)
requires bedroom furniture IV
115% rest effectiveness
110% immunity gain speed
0.80 comfort
```

The sleeping pod feels like it's costs should be adjusted to use more hi-tech resources for what it is, improve its stats so its better than the stylish bed, or just remove it since it feels really similar to the Pod Bed which unlocks at the same tech level.

I have no idea what exactly changes should be but these two beds feel like they need a tweak in cost or stats.

**Comment by skyarkhangel** [comment]
ok.

**Comment by skyarkhangel** [comment]
Done, in next commit.
