### ISSUE TITLE
Mod Real fog war

### ISSUE THREAD

**Issue by mora145** [skyarkhangel/Hardcore-SK#1096]
Hi guys.

What do you think about adding the mod Real Fog War to the pack? 
I've been using it for 2 weeks, and it's going great.

[https://ludeon.com/forums/index.php?topic=28938.0](url)

![836245605_preview_20170107005713_1](https://user-images.githubusercontent.com/25883820/28736161-976c4814-73b6-11e7-909d-0d79541fbfae.jpg)

**Comment by notfood** [comment]
I tried it as well, it doesn't need any changes and it works fine. Leave it to the users to install it. HcSK is compatible.
