### ISSUE TITLE
Terminators

### ISSUE THREAD

**Issue by mora145** [skyarkhangel/Hardcore-SK#1100]
¿Hay alguna manera de "limitar" el tiempo en el que los terminator's están a nuestro servicio? 

Creo que tener a uno a nuestro servicio, por mucho tiempo, nos hace invencibles y aburre la dinámica del juego.

**Comment by shoter** [comment]
Translated to english:

"Is there a way to "limit" the time that the terminator's are at our service?

I think that having one at our service, for a long time, makes us invincible and bores the dynamics of the game."

**Comment by Wazowski1** [comment]
Nooo por favor dejar el **Terminator** como esta es el puto dios, **mora145** aumenta la dificulta a **extrema** para que veas que el **Terminator** se queda pequeño, por cierto, saludos desde Venezuela también hermanazo

**Comment by mora145** [comment]
Si, ya vi, enfrentandome contra unos Mecanoides, le dieron palo. Pero en otras cosas como investigaciones, transporte y demas, sigue siendo mucha ventaja. Al igual que se buguea y aprende todas las habilidades al 10/10

**Comment by Wazowski1** [comment]
Si en eso si tienes razón ayuda muchísimo en transporte y todas esas cosas, pero digamos que sería darle un uso consiente para no aburrirnos, yo por lo menos lo tengo a una sola tarea que es minar como un loco, u otra que cause menos impacto sería que limpiara todo el tiempo, desventaja siempre la tendremos nosotros con esa dificultades demenciales.
