### ISSUE TITLE
#Wildrose seeds

### ISSUE THREAD

**Issue by JimmyKoole** [skyarkhangel/Hardcore-SK#1104]
GetInspectString exception on SeedWildRose2264835:
System.NullReferenceException
at SeedsPlease.Seed.GetInspectString() [0x00000] in filename,unknown blablabla
in short cant plant them, cant find wild rose in sowing options
have all flowers + farming research

**Comment by missflora** [comment]
if you are are using wild cultivation, sidmaster made a compatibility patch

**Comment by JimmyKoole** [comment]
I am using wild cultivation but i cant find the patch you are talking about
Im also having trouble with brewery, making wine mash in the electric brewery gives me tequila mash, and tequila mash also gives me tequila mash.

my load order: 
http://imgur.com/jE9bau6

**Comment by missflora** [comment]
[Patches.zip](https://github.com/skyarkhangel/Hardcore-SK/files/1201924/Patches.zip)

**Comment by missflora** [comment]
Use this and put it into wild Cultivation folder
