### ISSUE TITLE
Dryed fruit recipie has dryed fruit as ingredient, creating a loop

### ISSUE THREAD

**Issue by martov1** [skyarkhangel/Hardcore-SK#1114]
The recipie has it's end product as an ingredient, creating a never ending loop.

![imagen](https://user-images.githubusercontent.com/7854453/29489839-62898944-8500-11e7-8270-c44df6085b98.png)

**Comment by AnalTweet** [comment]
Same thing with Salt meat recipe and Salted meat respectively.
![ss 2017-09-08 at 12 48 06](https://user-images.githubusercontent.com/31756139/30197810-5b358a64-9494-11e7-9b45-c96aa0c024c6.jpg)

**Comment by skyarkhangel** [comment]
Fixed
