### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#1115]
1. solarflare bugged. when solarflare event happens, game get lagged. see pic.1
2. small graphic bug. see pic.2, vent and tree. vent is overlapping the tree. 
![1](https://user-images.githubusercontent.com/23387664/29492057-6ef1a9f0-85aa-11e7-9609-571bedbbd553.JPG)
![2](https://user-images.githubusercontent.com/23387664/29492058-70ceed78-85aa-11e7-97bf-ad1a31a52e4e.JPG)

**Comment by skyarkhangel** [comment]
Were fixed
