### ISSUE TITLE
So few raid happen.. I dont have any ancient things!

### ISSUE THREAD

**Issue by totobrother** [skyarkhangel/Hardcore-SK#1119]
I played  kara fateful.
But only 1 raid was happend. even i picked very hard
Everybody said it because of ancient things.
So i edit my save file and delete all of ancient.
but after 60 days, still didnt happen raid...
What should I do? my colony has name. so i sure i delete all acient.
also i restarted game and set regular raid every 12 day.
but didnt work!! other event such as trade, is work well.
Plz help me.

**Comment by Freshpage** [comment]
It isn't the ancient things exactly - it is the mechs within them which are in "attack colony" mode. Did you delete these?  Easy way to tell if you have this problem: have you had the event to set your colony name? If not, then you have the problem.

**Comment by Inei** [comment]
I am playing tribe scenario with Kara too, and had like three or four raids already till day 54.

**Comment by totobrother** [comment]
I said i have colony name, it is not that problem...
I think too many event block raid.
