### ISSUE TITLE
Black sleeping spot no graphic

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#112]
I'm using github version with the last commit being  "Merge pull request #111 from jnkyacc/patch-1  …"

http://imgur.com/a/QYYQl

Edit* New issues, Stone furnace/klin can't be rotated, Brewery is available from the start but butcher's table isn't?

**Comment by kaptain-kavern** [comment]
I think it's because the sleeping spot should not still be here, judging by the changes brought with RA assets

**Comment by kaptain-kavern** [comment]
https://github.com/skyarkhangel/Hardcore-SK/commit/365269f897638311af61c9ddcbd22d241fdf87e9

resolved

**Comment by skyarkhangel** [comment]
Fixed
