### ISSUE TITLE
Spacecraft chunks and cargo pods that fall have build roof areas around them.

### ISSUE THREAD

**Issue by MrSamsa** [skyarkhangel/Hardcore-SK#1123]
Every time a chunk of spacecraft or cargo pod falls it creates a build roof area around it. These areas seem to cause lag/stuttering in my game if they arnt removed eventually and doesnt seem practical anyways.

I noticed a problem with my pawns going on the other side of the map to build a roof around a crashed spaceship chunk that was next to a wall of mountain. When I saw them build a roof over it I checked the build roof areas and every single piece that had ever fallen during the game had a build roof area over it but most were out in the open and couldnt have roofs, which is why I never noticed :P

**Comment by Freshpage** [comment]
I've noticed this too
