### ISSUE TITLE
Chemical Laboratory referred to but removed

### ISSUE THREAD

**Issue by Dunkhan** [skyarkhangel/Hardcore-SK#1130]
The chemical laboratory workbench appears to have been removed from the game. The petrochemical laboratory makes carbon fiber alloy, and the synthetic organ bench makes artificial bones so the jobs of theis building are covered. But the research tree still says"

"This allows your colonists to build the Chemical Laboratory, which can be used to create medkits and advanced prosthetic body parts."

In the biochemistry tech, which is not true. This is very confusing to the user. There are also other texts which mention the chemical laboratory that should be fixed at the same time. see:
https://github.com/skyarkhangel/Hardcore-SK/search?utf8=%E2%9C%93&q=%22chemical+laboratory%22&type=

**Comment by Inei** [comment]
There are lots of descriptions in english version that needs to be updated in the research tree, as for now they are for old/vanilla techs versions and totally misleading in most cases.
