### ISSUE TITLE
Limb lost to frostbite glitch.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1132]
I had a trader got hit by angry Kirin, I saved him, but he lost his hand due to frostbite, though, for some reason his hand was not considered damaged, as I harvested new hand from prisoner, and had no options to install new hand to him then I harvested whole arm, but there was still no option to install it to him (though I was doing such operations before with other patients). Then I  tried to harvest his own damaged arm (with hand lost to frostbite) and for some reason I harvested healthy arm from him, though, for some reason I have no option to install it back to him, and now he has cut off arm, and no ways to sew normal arm back, even though I can install bionic arm that I got from another prisoner.

**Comment by Inei** [comment]
After installing bionic arm, I've been able to replace it with normal arm from storage. Though, still a bug.

**Comment by zakhad** [comment]
Yeah I've noticed that with legs as well, But at least with arm you can install a shoulder and it'll replace the arm. :s

**Comment by caesius90** [comment]
It also happens to other causes of damages, not only frostbite.

**Comment by caesius90** [comment]
my rim lost his both hands and both legs. i have new leg and arm but cant implant them (no pickable sugery option in th tab).

**Comment by Rhyssia** [comment]
Looks like destroyed parts are removed from surgery options. (Had this happen with kidney)

**Comment by sidfu** [comment]
some parts need certain research to install. make sure u have the research to install it. u can test it by saveing, enable dev and finish all reserach and see if u have option to install. if u can then its fine and just reload your save
