### ISSUE TITLE
Sapping tunnel bug.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1135]
Just had a droppod raid, and enemies decided to sapper a tunnel, though, for some reason, they started glitching instead, standing on place, and trying to do something with embrasures, which causes spam of this error in the log for almost all of the enemies. 

`Missy started 10 jobs in one tick. newJob=UseVerbOnThing A=Thing_Embrasure3552913 jobGiver=RimWorld.JobGiver_AISapper jobList=(UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913) (UseVerbOnThing A=Thing_Embrasure3552913)  lastJobGiver=RimWorld.JobGiver_AISapper
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.<GotoCastPosition>c__AnonStorey4DC:<>m__7C3()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef, Nullable`1)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
`

**Comment by sidfu** [comment]
not a bug per say. its cause the sapper has to much to do and overloads they pawn. same can happen to your colonist if u have to many jobs happaning at same time for them

**Comment by Riro12** [comment]
I also had the same bug
The sap has never been successful X(

**Comment by sidfu** [comment]
we know about it and are in process of trying to fix

**Comment by Freshpage** [comment]
In my game with the latest build I had 3 raids, and all 3 were sapper raids. Not sure if having 3 sapper raids in a row is coincidence or part of the same problem. (In all 3 they didn't attack).

**Comment by Inei** [comment]
I found out that if they can't find proper place to sap, or  target place for sapping appears to be guarded with pawns turrets or whatever else. They just stand in the distance doing nothing. Though, if you move your pawns from guarding, they'll eventually move to attack, but will stop and return to their initial position as soon as you'll return your pawns back to guard.  It can be used to bomb them from distance with artillery though. As they don't react much to that, until enough of them dead to take what they can to leave, or just to flee.

**Comment by sidfu** [comment]
we  just recenly updated sappers are u useing the newest version?

**Comment by Freshpage** [comment]
I just downloaded the latest version and loaded a save game with an ongoing broken sapper raid. It is fixed for me.

**Comment by sidfu** [comment]
all it was for sappers is that the grenades wher emissing some settings and had a bad setting. fyi grenades can be used with sheilds now so expect sappers with sheilds. on flip side u can do same
