### ISSUE TITLE
Nonbutcherable spider corpses.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1136]
Well, not sure what is bugged in there, as they occasionally butcher them, though, I don't know what triggers it, as for the most time spider corpses stay in storage and when you try to force pawn to butcher it with table, it says it lacks materials for it.

**Comment by nemesis688** [comment]
So I think I had the same issue. For me it was because I didn't have any stockpiles that could store "Arachnid Meat" and with one of the QoL mods in the pack it makes it so the butcher table will not butcher if there is no room in a stockpile for the meat

**Comment by Inei** [comment]
You are right. I had space for arachnid meat though, but not for arachnid chitin. Thankies alot.

**Comment by Rhyssia** [comment]
resolved
