### ISSUE TITLE
Terminator wooed by enemy prisoner :P

### ISSUE THREAD

**Issue by MrSamsa** [skyarkhangel/Hardcore-SK#1137]
One of my prisoners from the Orion Corp I have been keeping around to harvest the cybernetic body part from has successfully managed to woo my Terminator. Im sure it is some fiendish plot by this Orion Corp prisoner to escape somehow...

Is this supposed to be possible? This prisoner is scheduled for body part removals and euthanasia but I dont want my terminator getting depressed (lol) or going on a killing spree after we dispose of his new lover :-/

Got a good laugh out of this. Perhaps I should let this freakish love affair continue and put a double bed in the prison?

**Comment by skyarkhangel** [comment]
I hope were fixed, about week-2 week ago.
