### ISSUE TITLE
kiln not working

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#114]
the kiln to make charcoal and bricks for tribals not working. u can add bills,refuel it but beyond that no one will work on the bills and when u right click u only have option to refuel nothing for bills.

**Comment by kaptain-kavern** [comment]
This looks like it lack the workgiverDef then. I can try to locate this one @skyarkhangel

**Comment by kaptain-kavern** [comment]
Indeed the kiln is not listed in workGiverDef neither under DoCremateJob + I don't know if there is still recipe attached to it (since you remove the charcoal prod from tablefurnace

**Comment by sidfu** [comment]
on newest update kiln seems to be working they making charcoal altest gonna spawn in clay to see if they make the bricks

**Comment by skyarkhangel** [comment]
Fixed, yes soon add woody stuff for fuel too.

**Comment by zakhad** [comment]
is it intentional that it can't be rotated or it doesn't yet have the side view graphic?

**Comment by sidfu** [comment]
didnt try to rotate it when i put iit down this time but it is 2 wide so the spot to craft is off to side simlar to the concrte mixer

**Comment by skyarkhangel** [comment]
can't be rotated while we haven't textures for back, side position
