### ISSUE TITLE
Dead people in drop pods.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1140]
Not sure if it's a bug, but they always dead, and always naked with only hats of different kinds on them. That's looks very odd. Aren't they supposed to have other gear too? Or not be dead at least sometimes?

**Comment by Rhyssia** [comment]
Certain pods will drop dead colonists. Some will drop injured.

**Comment by Inei** [comment]
It's not them being dead that concerns me. Rather them being naked wearing only hats.

**Comment by Rhyssia** [comment]
Fair enough, will ask around about it.

**Comment by skyarkhangel** [comment]
its intended that they are dead. Okay i'll add some more equip.
