### ISSUE TITLE
Skynet Cloak weight.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1145]
Not sure if it's a bug, but if we put some logic in it and compare resources needed to craft it with resources needed to craft full power armor, it's hard to believe it should have 15 kg weight, while heaviest of power armors weights only 9. Unless it was made this way for some kind of balance reasons.

**Comment by Rhyssia** [comment]
I'm going with balance. Initially the cloak weighed 30kg. Will kick the idea around a bit.
