### ISSUE TITLE
Poor pathfinding.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1151]
Not quite a bug, but rather annoying thing. It's about pawns quite often tend to move over tables, barrels, storage piles or whatever else that slows them down, instead of using free tiles left for moving nearby. I tried restricting parts of those working tables with area restrictions, but it's quite poor workaround, as if they have more than one mat to craft on table, they can't start working, as they put things in restricted area, and then move to move to get access to it, and just stuck with repeating it. And without restrictions, they continue climbing over tables instead of using free paths to move that won't slow them down.

**Comment by sidfu** [comment]
base game issue. short distance has better ai logic for frinding path than long distance. smartly organizing bbase and leaving plenty of room helps

**Comment by skyarkhangel** [comment]
Ah yep, i hope it would better on a18
