### ISSUE TITLE
8 hardcoreSK bug reports.

### ISSUE THREAD

**Issue by eastaress** [skyarkhangel/Hardcore-SK#1161]
1. Binoculars do not function properly. And it displays a huge error message.

2. The error message continues when you put the enriched Uranium Alloy in the plant.

3.There are two 'cook roasted meat' bill on electric stove.

4.If the tent is deconstructed wall-> pack Tent-> deploy tent, you can get a cloth or leather at infinity.

5.EMP grenade is not thrown. Continue to generate the error.

6. When a Terminater event (Salvation) is created at the end of a map, it walks out of the map before the join message arrives, and if so, the acceptance does not join.

7.Fuse mod does not operate normally. When I tested it, the original Steam workshop fuse mod seems to work. In other words, the hard core SK fuse mod seems to be a problem.

8.Cloth lockers-locker. If the item is drafted during the equipment change or is forced by the policy, the item becomes inaccessible in the box as the box becomes unavailable. In this case, the Forcegear command is not executed either. It is a serious problem that an item disappears although it is not a frequent bug. At least when you deconstruct, you should return the item in box.

**Comment by GhostGum** [comment]
> When a Terminater event (Salvation) is created at the end of a map, it walks out of the map before the join message arrives, and if so, the acceptance does not join.

I just had this happen twice in a row. :/
