### ISSUE TITLE
To make bronze alloy, we must

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1167]
mix copper ORE and other ALLOYS.

Is this a mistake or an intended thing?
mixing ORE and ALLOY seems a bit irrational.

**Comment by Slipshodian** [comment]
It isn't irrational, it's just nitpicking the fact that it doesn't use both ores or both alloys in the process.

**Comment by Freshpage** [comment]
It's not irrational, but it does make things a bit more fiddly. Once you've smelted the copper you can no longer make any bronze so you have to remember to keep some copper ore unsmelted. Not sure if there is a good reason to add this micro management into the game.
