### ISSUE TITLE
bionic leg attached rims cant wear shoes

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#1168]
i dont think this is intended.

**Comment by pectus-solentis** [comment]
Are you korean? English speakers don't call pawns as 'rims'. That's korean own slang.

**Comment by skyarkhangel** [comment]
this bug on vanilla too?

**Comment by henryho96** [comment]
As far as I known this is a problem in Vanilla as well. Can't remember if it has been fixed through mods yet.
