### ISSUE TITLE
Achtung! last PR

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#117]
is it bugged or it just me?
https://github.com/skyarkhangel/Hardcore-SK/pull/113

![Log](https://cloud.githubusercontent.com/assets/20729235/17831289/fd9f909e-66e4-11e6-8ac4-02aa05063758.png)
ковырял ресерч
___
upd: looks like shit happens [here](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Agro.xml#L637)
and im not sure that we need to change SK_FungiI to Fungiponic...
upd1: откатился на Powered by RA, все работет

**Comment by jnkyacc** [comment]
looks like shit happens [here](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ResearchProjectDefs/ResearchProjects_Agro.xml#L637)
and im not sure that we need to change SK_FungiI to Fungiponic...

**Comment by jnkyacc** [comment]
еще один http://hardcore-sk.ru/threads/probuem-testovuju-versiju.164/page-126#post-9802

**Comment by kaptain-kavern** [comment]
Oh it's from my changes. Sorry 
Looks like line 637 and 638 must be erased.

**Comment by kaptain-kavern** [comment]
This should do it : https://github.com/skyarkhangel/Hardcore-SK/pull/119

**Comment by jnkyacc** [comment]
> The changes from SK_FungiI to Fungiponic is for the mushrooms to appear in Colony Manager (See here )

hm. so only 2 ways...
1) make custom CM build
2) change other SK_FungiI-II-III to Fungiponic-2-3 to make it less confusing

**Comment by kaptain-kavern** [comment]
Make custom CM was the best option I think, but i don't know C#

**Comment by jnkyacc** [comment]
1021598c213ddb7373cdbb010923c5da90cbce16
