### ISSUE TITLE
Raw food eaten instead of cooked food.  "Items_Meals.xml"?

### ISSUE THREAD

**Issue by GhostGum** [skyarkhangel/Hardcore-SK#1193]
2017-10-10

Certain cooked foods (like "Roasted Meat", among others, for example) seem to have very low eat priority. My pawns will eat all my raw meat and veg itself before they eat the actual cooked meals.
Kinda bugs out food supply badly at the start of game.

I think changing the following worked as a workaround for me:

> /Core_SK/Defs/ThingDefs_Meals/Items_Meals.xml

```
	<ThingDef ParentName="MealBase">
		<defName>RoastedMeat</defName>
```
To:
```
	<ThingDef ParentName="MealRottable">
		<defName>RoastedMeat</defName>
```

Cheers

**Comment by ynemo** [comment]
added this in pull request 
https://github.com/skyarkhangel/Hardcore-SK/pull/1229/commits/2f6460bbb8c9851bb03a6a1ce02bc773ecbbc884
