### ISSUE TITLE
В моде миникарты не выключен дебаг

### ISSUE THREAD

**Issue by thghca** [skyarkhangel/Hardcore-SK#1204]
Это немного замедляет загрузку.
`namespace MiniMap.Extra
{
	// Token: 0x0200001E RID: 30
	internal class ControllerSettings : Mod
	{
		// Token: 0x06000083 RID: 131 RVA: 0x00002342 File Offset: 0x00000542
		public ControllerSettings(ModContentPack content) : base(content)
		{
			HarmonyInstance.DEBUG = true;`

**Comment by thghca** [comment]
Лучше заменить на  [BetterMiniMap](https://steamcommunity.com/linkfilter/?url=https://github.com/AaronCRobinson/BetterMiniMap)

**Comment by skyarkhangel** [comment]
У нас нет сурсов на MiniMap. Скоро заменим :)
