### ISSUE TITLE
Hardcore-SK-master RIMWORLD World Generating

### ISSUE THREAD

**Issue by Lesh86** [skyarkhangel/Hardcore-SK#1208]
Hi,

I already set up Hardcore-SK-master Nod Pack. Works all fine no errors etc.
Until I start a new Colony. Generating a new world brings me back to  generating new world.

Nothing happens, no errors occurs, so i cant use the modpack pls need some advice / help.

Update found that Errors but dont have any plan what that means. :(

https://gist.github.com/HugsLibRecordKeeper/509cacacaeb67595b4851a499a3558bf

Thx Lesh

**Comment by thghca** [comment]
Try to disable minimap mod,

**Comment by Lesh86** [comment]
Solved

-Deleted every Data from Rimworld
-downloaded & installed Rimworld new
-started the game
-deactivate Norton (seems to be Norton killed some .dll data
-downloaded Hardcore-SK-master RIMWORLD Modpack
-used the updater tool
-start rimworld and finally everthing works fine :)
