### ISSUE TITLE
I have Tier 2 Research Bench but game message says otherwise

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1227]
Tier 1 : Primitive Research Bench
Tier 2 : Research Bench
Tier 3 : Hi-tech Research Bench

![2017-10-28 1](https://user-images.githubusercontent.com/11158226/32133287-d467f668-bc0f-11e7-95bf-bc747446e32c.png)
Tier 2 Research Bench is normally installed.

![2017-10-28](https://user-images.githubusercontent.com/11158226/32133293-ea5647f4-bc0f-11e7-8e11-0174dd18d721.png)
And my research pawn is just researching Tier 2 (Production I) research items...
But Why there is a lock icon on my Production I research items.?
Even when I click that game message says Requirements Missing.

**Comment by thghca** [comment]
Try deconstruct primitive research bench.

**Comment by pectus-solentis** [comment]
I haven't ever built that on my entire games.

**Comment by thghca** [comment]
Try replace ResearchPal.dll with this https://github.com/thghca/RimWorld-ResearchPal/blob/master/Assemblies/ResearchPal.dll

**Comment by notfood** [comment]
Updated it to thghca's version.
