### ISSUE TITLE
Various Weapon Problems

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#1232]
(Okay I'm done for now, there's more though that I'll come back for) 

**1. FN SCAR-H has the model of the FN SCAR-L**

https://image.prntscr.com/image/kQr0cW6VTfe8ET4-vAmFoQ.png

https://i.pinimg.com/736x/ba/3a/54/ba3a54c7fd27e6048d7fdaaab19aa12c--fn-scar-tactical-firearms.jpg

https://i.ytimg.com/vi/mCf5tpaymr4/hqdefault.jpg

The 7.62 x 51mm version of the gun has a slightly wider straight magazine and a longer barrel thingy. 

Either editing the model to look like the SCAR-H or changing it into a 5.56 assault rifle are options here. Because there are not many battle rifles (for example the FN FAL, G3, M14 etc.) it might make more sense to get rid of the only one we  have.

**2. The Spectre M4 Luger is not a Spectre M4 Luger**

https://image.prntscr.com/image/bwyqhkVqSN_fJR2x3pE1Yg.png

https://i.pinimg.com/736x/2a/80/00/2a800010d6610dcb3bc43269286e4975--internet-movies-submachine-gun.jpg

I don't know what gun it is but I'm trying to find out, I'll update when  I do. 

I think changing the name and the stats to match the model would be the easy solution. 

**3.  Sledgehammer has the wrong description**

It says "Specific type of long straight, double-edged sword." 

**4. RPK-74 is not an RPK-74**

https://image.prntscr.com/image/W5TnbUf2QGGwrBaeflADqA.png

https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Soviet_RPK-74.JPEG/300px-Soviet_RPK-74.JPEG

http://www.imfdb.org/images/thumb/f/fa/GalilARM-2.jpg/450px-GalilARM-2.jpg

The RPK-74 is chambered in 5.45 x 39mm not 7.62 x 39mm and the in game model is of a different weapon, possibly the Galil a 5.56 x 45mm assault rifle.  

Find or make the right model and/or change the name and stats to the IMI Galil I guess

**5. The HK USC should be an SMG not an AR**

In game it is in the Assault Rifle family for crafting and stuff, but it shoots a pistol cartridge and is a Submachine Gun. 

**6. L-15 LMG is not a real gun**

I have no idea what an "L-15" is supposed to be, if it's a real gun I've never heard of it and can't find anything about it. 

https://image.prntscr.com/image/ZaAxb8xvRIqaaDyfLQHpbg.png

I think the model might supposed to be an M-249 SAW in the Paratrooper configuration with a shorter barrel and light stock, scene below. 

http://www.colinsun.com/Colin/nfblog/wp-content/uploads/2009/03/m249_2.jpg

Not really sure what to do about this one honestly, I guess make it an M-249 Para? 

**7. The Mass Effect Guns are all Weird** 

-The A-6 Cerberus Harrier has the almost the right name (there is no A-6 I think) and description, but it talks about the Mattock another gun  that isn't in the game in its description. 

http://masseffect.wikia.com/wiki/Cerberus_Harrier

-The M-6 Mantis has the wrong designation and model. I don't know what the in game picture is. 

The Mass Effect gun is called the M-92 Mantis, the gun in game has almost the same name and the same description as the mass effect gun but looks completely different. 

https://image.prntscr.com/image/xezrAZXmRJybjWPDjZbjfQ.png

http://vignette3.wikia.nocookie.net/masseffect/images/b/bf/ME2_SR_-_Mantis.png/revision/latest?cb=20140825071501

-  The M-8 Revenant has the right name and model (at this point I think you just renumbered them which is fine not a big deal nobody knows the mass effect numbers anyways) but the wrong stats and description. 

http://masseffect.wikia.com/wiki/M-76_Revenant

It should be closer to an LMG like what the big mechanoid centipedes have. with 60 or 80 or ammo in the magazine and maybe a different cheaper ammo type. 

 It also has the description of the Avenger for some reason. 

- The A-10 Avenger has the wrong model and wrong description. It actually has what might be the model for the Halo MA5. Maybe it's not supposed to be the gun from Mass Effect but it sure is confusing. 

**9. The M56 Smart Gun is strange**

http://avp.wikia.com/wiki/M56_Smartgun

That's the gun from Aliens, and it's a big hip fired minigun type weapon. 

The gun in game is nothing like it, I think you should just change the name because they have nothing in common.

**Comment by Vulpes-Inculta** [comment]
1) Getting rid of SCAR-H 7.62mm assault rifle? Why getting rid of a little variety?
2) Sledgehammer description is probably a joke.
3) Smart Gun used to have a proper model in the old combat realism, but the stats don't match kind of. Cause smart gun from Aliens seems to be a fast firing low-calibre platform. The gun in the game is a kind of a portable HMG chambered in 50 bmg. I don't mind the concept but well I agree it may use another name.
4) L-15 MG is not a real gun? It's sci-fi, man! Having ancient real world guns in this game is what I personally find weird. Like Lee-enfield or Mosin-Nagant on a distant planet in the year of 5502. That's funny.

**Comment by zachary-foster** [comment]
I dont mind having the old guns, but I too find it a little strange that they are in a SciFi setting. However, if they are named for an existing gun, then the relative stats/appearance should match the real gun. Otherwise, a new name would be best in my opinion.

**Comment by Vulpes-Inculta** [comment]
I just imagine it's a paralell universe or something. I also make little changes in the files myself when I meet something rly strange like M4A1 being more bulky than AK-47. It's easy to do, simple textfile edit.

Like for example I just changed SVU blahblah Dragunov to just SVD Dragunov cause the model is that of a regular SVD.

Another funny thing, this so called RPK-74 is called Galil in the files! That's what it looks like too. Idk how it ended up being called RPK, meh. Just changed it to "Galil heavy" and it's fine for me.

Just do the same, my dudes, it's rly easy :)

**Comment by zachary-foster** [comment]
>I just imagine it's a paralell universe or something.

Thats a good way of thinking about it. It would be nice if the descriptions of the guns were based on some unified fictional "history", rather than being clearly from one universe or another. They could still be based on and appear like real guns, but would not necessarily be the same ones that are on Earth today or from mass effect, etc. 

> simple textfile edit. 

Good idea! It would be nice if we could make things consistent in the source though.
