### ISSUE TITLE
Real Fog

### ISSUE THREAD

**Issue by mora145** [skyarkhangel/Hardcore-SK#1236]
Since the last modifications were made, I can no longer start games using the Real Fog mod.

Does anyone know that mod is being incompatible?

This mod override:

**EnvironmentInspectDrawer.ShouldShow:** to hide environment attribute for unrevealed areas.

**GenMapUI.DrawThingLabel:** to prevent showing labels of not visibile objects.

**HaulAIUtility.HaulToStorageJob:** to prevent hauling of not discovered objects.

**InstallationDesignatorDatabase.NewDesignatorFor:** to use a patched Designator_Install, which prevents the installations of things in non discovered areas.

**LetterStack.ReceiveLetter and Messages.Message:** To pin the arrow of the messages source to the initial location, in order to not follow raiders or pawns when moving in non discovered areas.

**MouseoverReadout.MouseoverReadoutOnGUI:** to prevent showing info of non discovered or seen objects.

**Pawn.DrawPawnGUIOverlay:** to hide the name of not seen pawns.

**SectionLayer_ThingsGeneral.TakePrintFrom and SectionLayer_ThingsPowerGrid.TakePrintFrom:** to hide not visible objects.

**Selector.Select**: to prevent the selection of not visible objects.

**Verb.CanHitCellFromCellIgnoringRange:** to apply the Fog of War in the targeting system.

**WorkGiver_DoBill.TryFindBestBillIngredients:** to prevent the using of non visible objects for bills.

**Comment by Vulpes-Inculta** [comment]
This is a very bad idea to use ANY external mods with such a complex and fragile modpack.

**Comment by notfood** [comment]
I use a ton of external mods.

By the way, Real Fog is working for me. 

My modlist: https://gist.github.com/notfood/a55a1588cc850c917f0dcca953a8f0e4
prefix X_ and Z_ come from the steam workshop instead of the pack.

**Comment by notfood** [comment]
The mod causing the issue is MorePlanning, disable it and Real Fog should work again.

**Comment by mora145** [comment]
Thx @notfood problem solved :+1: You have many mods ... I'll try some that I liked.
