### ISSUE TITLE
About not using  a "Core" folder anymore

### ISSUE THREAD

**Issue by kaptain-kavern** [skyarkhangel/Hardcore-SK#124]
I run a comparison between the _Core_ folder from Vanilla and the _Core_ folder from the pack. 
- The only differences I found in the _Defs_ folder was a typo about a capitalized character for one  label in _Faction_ (insects/Insects) and a difference about fuel consumption for wood torches (but iirc Tynan just changed that)
- The Russian folder for translation 
- A bunch of added textures

So as far as I understand all we have to do is not packaging it anymore, move the textures folder to _SK_Core_ folder (the path should be the same, if not the changes would be simple to implement). And I'm not sure about the translation files as I have only played in English and never fiddled with translation files, but I'm pretty confident they can also be moved as the official translation pack are distributed without all the _Core/Defs_ structures.

@skyarkhangel : I could try to make this up and do a PR but I'm waiting for your reply in case I missed something about the way you want your pack to be.

**Comment by skyarkhangel** [comment]
Its made for convenience. Players could delete mods folder and copy from project.
And ONE big difference: Removed TONS of unsuported translations. In vanilla language folder more then 10k files. For example, all project with mods less then 9k files.

**Comment by skyarkhangel** [comment]
I think in the next versions take a note this offer.
