### ISSUE TITLE
Why can't we store Ibuprofen, Mortacain, etc... in Medicine Cabinet?

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1245]
I know they are categorized in not Medicine but Drug, but these DRUGs has an apparent healing (not addictive effects) effects at its prime effects, so I think we can't store Ibuprofen, Antibiotics, etc... is irrational.

**Comment by sidfu** [comment]
drug filter added

**Comment by pectus-solentis** [comment]
And please make Medicine Cabinets store Raw Healroot. Healroots are necessary to make medicines, and it itself is a (crude) medicine too.
