### ISSUE TITLE
Large Tool Cabinet doesn't be applied to most worktables

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1248]
and even Small Tool Cabinet doesn't be applied to Hand Machining Table.
It seems that it is undoubtly a bug...

**Comment by sidfu** [comment]
not bug oversite and changed

**Comment by pectus-solentis** [comment]
Then how will you explain that **the tables that only large tool cabinets are applied**?

**Comment by pectus-solentis** [comment]
I think that the tables applies large tool cabinets are also apply small tool cabinet is rational.
