### ISSUE TITLE
Weapon Crafting does not use intermediate object, all done in one sitting 

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#1251]
http://prntscr.com/h8tzi5

Crafting ammunition or a sculpture or sword makes an unfinished object which is then worked on, allowing the colonist to leave and come back, for some reason crafting a rifle for example does not work like this, the colonist must stay there crafting until completion or you have to start over again.

**Comment by sidfu** [comment]
we triede it and it caused issues. it should be back in the future if the errors and bugs we had get sorted out

**Comment by sma342** [comment]
Any chances to fix that asap? Crafting guns is kinda impossible without this.
