### ISSUE TITLE
Cabbage's Fertility Sensitivity is 8% (0.08)

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1253]
It seems that 80% (0.8) is mistyped. Isn't it?

**Comment by sidfu** [comment]
no the scale goes from 0 to 1.0+
so a 1.0 fertlity is 100% a 1.2 is 120%

**Comment by pectus-solentis** [comment]
Are yoi kidding me?
In the Def file Cabbage's FS is scribed as 0.08

**Comment by sidfu** [comment]
fixed
