### ISSUE TITLE
Serving Table doesn't store sweets and other foodstuffs

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1257]
Why? It seems irrational.

**Comment by sidfu** [comment]
its meant to be meals. if we allowed everything then people would use just it and ignore the fridge and such. consider it a balance thing

**Comment by pectus-solentis** [comment]
No. Why can't we store sweets and drugs on Serving Table? Sweets aren't be
spoiled by temperature so being not able to store sweets on Serving Tables
seems irrational.

2017. 11. 12. 오전 9:10에 "sidfu" <notifications@github.com>님이 작성:

**Comment by ynemo** [comment]
added to pull request 
https://github.com/skyarkhangel/Hardcore-SK/pull/1264/commits/3f3dd9b18b7e20a8a84ef5926ac92a0ba67a401d

**Comment by pectus-solentis** [comment]
Then how about drugs be stored in ST?
