### ISSUE TITLE
Storage accessories - items truncating after load

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#129]
1) Pallet
Вся суть в том что можно запихнуть на него 1200+600 дерева при емкости самого палета в 500. Подозрения у меня что оно не знает как ему считать т.к емкость палета 500 а один стак дерева 600. Skip при этом работает как задумано на 800. Баг или фитча смотрите сами... тут фикс #130 

2) All storage accessories - items truncating after load
После забивки под завязку и сохранения-загрузки скидывает на один стак.

![screenshot31](https://cloud.githubusercontent.com/assets/20729235/17860578/1cdc283c-688e-11e6-8c98-f9202bf55174.png)

**Comment by skyarkhangel** [comment]
ok. Merged changes. Also, storages could update soon.

**Comment by jnkyacc** [comment]
@skyarkhangel оно обрезает не только стороджи, а вообще все айтемы выше их мах стака. https://github.com/skyarkhangel/Hardcore-SK/issues/132 и я так предполагаю что остальные екстракторы которые все складывают в один стак тоже подвержены этому.
