### ISSUE TITLE
Double Beds broken or not showing

### ISSUE THREAD

**Issue by GATEElemental** [skyarkhangel/Hardcore-SK#1305]
Hello.

I've started a new game in B18 with Dev Branch a few weeks ago, since then I've cleaned up my mod folders and re downloaded everything at each update.
Now in Master Branch I've encountered a problem in which I could reproduce in a new steam installation and new download:

1- Start a new game (doesn't matter which map or tech level)
2- Enable Dev
3- Enable God
4- Attempt to create a Double Bed, upon selecting the bed, the game warns about an error and no Beds are available to place instead a Double Bed.
5- Without God powers and if you have the research, it seems to pick only Leathers and no Wools even if I have loads of wools to build double beds with.

**Comment by skyarkhangel** [comment]
Fixed in last update
