### ISSUE TITLE
Mine extractor creates too large stacks, causes truncating

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#132]
Mine extractors put what is mined in a single tile. It allows for stack sizes to go over their normal limits, causing anything over the stack limit to be deleted on loading.

**Comment by skyarkhangel** [comment]
We wait for the next version. Mine extractors would removed with A15 update. I'am stopped works with it.

**Comment by Jalordon** [comment]
Seems to not occur now so closing this issue for now.
