### ISSUE TITLE
current git version errors

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#133]
4 c ould not resolve cross-referecne: no verse.thingdef named componets found to give to
verse.thingcount(2x null)

basiccaly all 4 errors are same

cannot call itemfromxmlfile with resolvecrossref=true while loading is already in progress
verse.log.error(sstring)
verse.xmlloader:itemfromxmlfile(string,boolean)
verse.conceptdatabase:reloadandrebind
verse.playdataloader:doplayload
versse.playdataloader:loadallplaydata(boolean)
verse.root<start>m__5a2
verse.longeventhandler:runeventfromanotherthread(action)
verse.longeventhandler:<updatecurrentasynchroonouseven>m___5a0

**Comment by skyarkhangel** [comment]
After my update can't find this error.
