### ISSUE TITLE
Getting error on try to Hunt/Tame Feenix

### ISSUE THREAD

**Issue by ghihihihihi** [skyarkhangel/Hardcore-SK#134]
Hi,

i got errors during trying to Hunt or tame the Feenix.

![image](https://cloud.githubusercontent.com/assets/3660629/17890467/7f6e80fa-6936-11e6-8623-b2329b858019.png)

I'm using your Modpack-Version from 19.08.2016.

**Comment by skyarkhangel** [comment]
Fixed in next update
