### ISSUE TITLE
Frame Rate Drop from Fuel Buildings

### ISSUE THREAD

**Issue by firedoom13** [skyarkhangel/Hardcore-SK#1364]
As soon as I let my pawns finish build any buildings that need fuels to run, My game just slowly losing FPS every 5 mins in the game. I have to Reload the map multiple times because of it. And it happens at the beginning of the game. I have 5 Pawns with nothing expected their clothes. And as soon as place down a furnace and let them build it. My FPS just drop every time I let my camera even look at it. Then when I removed the furnace or look away from it. My FPS become normal again. Same goes for my 6-7 steam engines. As I look at them my FPS just drop. Oh and I check my error log, there were no error happening in the log.

**Comment by skyarkhangel** [comment]
Please check fps drop with simple storage, while opening storage settings

**Comment by firedoom13** [comment]
I did notice that every time I open up the storage with settings up, it did drop a split sec.
