### ISSUE TITLE
Pawns don't automatically pick up meals unless part of inventory assignment

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#137]
In vanilla pawns would normally take food into their inventory to eat so they would waste less time getting food.

 Pawns with out a loadout that includes meals in it won't take meals on their own, making them inefficient.

The issue is that it becomes tedious to have to make load outs, possible one for every type of gun, and assign them to the pawn.

Would it be possible to make it so that either pawns will still take a meal without a loadout, or allow for non-exclusive load outs that don't force the pawn to drop stuff not included in the loadout?

**Comment by skyarkhangel** [comment]
So its combat realism bug :/

**Comment by jnkyacc** [comment]
@skyarkhangel  оно закоменчено в СР коде. Если раскоментить оно будет подбирать, но т.к. лоадут исключает любые вещи кроме разрешеных, то будет выкидывать и подбирать бесконечно.
