### ISSUE TITLE
Ship chunk automatically kills colonist in lone survivor

### ISSUE THREAD

**Issue by johncabz** [skyarkhangel/Hardcore-SK#138]
When you start the lone survivor scenario, all of the ship chunks fall from the sky, your pawn spawns, then a much larger ship chunk falls directly in the area your pawn is and automatically kills/maims him

**Comment by jnkyacc** [comment]
@johncabz Do not use Crash Landing &  Prepare Carefully together until it will be fixed.

**Comment by skyarkhangel** [comment]
This scenario, i return to default mode without crashlading soon.

**Comment by skyarkhangel** [comment]
Rewroked Lone Survivor scenario to classic variant.
