### ISSUE TITLE
How about making the minimap need technology/items?

### ISSUE THREAD

**Issue by zachary-foster** [skyarkhangel/Hardcore-SK#1393]
The minimap is super useful. Almost too useful. If I am in the middle of the wilderness at night in the fog, part of the danger is not knowing if there is a bear 10 feet behind me. But the minimap will tell me with a useful and unrealistic red dot. So here are my suggestions: 

With no research: Only terrain is shown on minimap. 
For early modern: add "radio" research, which reveals the position of colonists on minimap.  If we really wanted to be realistic, colonists would need to carry a cheap and light "radio" to show up, perhaps made out of some 20 metal/plastic and 1 electronic component. The idea is that they could talk to each other and tell eachother where they are.
For modern: add "radio collars" or "radio chip", which reveals the position of tamed animals. If we really wanted to be realistic, a collar could need to be installed as a cheap animal prosthetic, again something like  20 metal/plastic and 1 electronic component.
For late modern / spacer: add "satellite surveillance" which would show everything, as it is currently set up. A new building could be required ("satellite comms station"?) and must be powered to work.

This would make it harder during raids, but more fun and unpredictable overall. This is HARDCORE SK after all, right?  ; )

However, I have no idea how hard this would be to make happen, so its just an idea.

**Comment by skyarkhangel** [comment]
A thought about it to make in future.
