### ISSUE TITLE
1 salt being left by metorite instead of salt "stone"?

### ISSUE THREAD

**Issue by zachary-foster** [skyarkhangel/Hardcore-SK#1394]
I assume this is a bug? Also, salt would be an odd thing to find in a meteorite. Salt is the result of long-term rock weathering in the presence of water, followed by evaporation and compaction as a sedimentary rock. That would not typically happen in space. The meteorite would have to be a fragment of a destroyed planet large enough to have had long-term liquid water (liquid water evaporates into space without enough gravity, e.g. Mars and Mercury). Not too likely. Most meteorites would be iron, nickel or silicate rocks (closest rock is granite in this game). see https://geology.com/meteorites/meteorite-types-and-classification.shtml.

![pic](https://user-images.githubusercontent.com/6090555/35466183-67e19ea2-02b6-11e8-8141-61f74f29e072.png)

**Comment by skyarkhangel** [comment]
this should be fixed in last update. Salt has the "Chunk" def, which lead to this problem

**Comment by zachary-foster** [comment]
Cool, thanks!
