### ISSUE TITLE
[Suggestion] Field Surgery 

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#140]
Думаю такие операции как удаление пальцев тут лишние. Достаточно оставить ступня-нога\кисть-рука\глаза-ухо-нос. Пальцы очень сильно "загрязняют" сам список и найти в нем что то становится тяжело. Как самый лучший вариант - убрать все операции без наркоза, вместе с пальцами, в отдельную вкладку.

**Comment by skyarkhangel** [comment]
Согласен, нужно как-нибудь переделать этот момент.

**Comment by skyarkhangel** [comment]
Field surgert removed
