### ISSUE TITLE
My colonist wont fish?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#141]
Hi, here's story:
I waited for spring and now its summer, my fisherman colonist wont fish. I have disabled all jobs, leave only fishing.
He just cloudwatching and similar stuff, wont go on fishing spot to fish. I made rod (excelend piece) egiped him with it.
Any ideas?

**Comment by jnkyacc** [comment]
@zoranjoza did you research fishing?

**Comment by zoranjoza** [comment]
Yes i did research Fishing I. Now i can do Fishing II, but i dont need aquaculture basin for now.
I have build fishing pier and fishing rog(exc). I ordered my colonist to pick up a rod. Disabled all work and leave only fishing. Still he dont want to go fishing, just chilling around....

**Comment by jnkyacc** [comment]
If you using last mod version from github (not from mega and ect.) upload you save here.

**Comment by zoranjoza** [comment]
I dont know why but i cant upload zip or rar.
I have uploaded it on google drive. Here is link to download:
[](https://doc-04-1c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/485vlhjcfesdm8ieq94cdqapljaitvjk/1472040000000/10922195088471663546/*/0B5eRdr0dEGLgV3YtUm52U2ZHbWs?e=download)

**Comment by zoranjoza** [comment]
[https://doc-04-1c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/485vlhjcfesdm8ieq94cdqapljaitvjk/1472040000000/10922195088471663546/*/0B5eRdr0dEGLgV3YtUm52U2ZHbWs?e=download](url)

**Comment by jnkyacc** [comment]
Fluffy Breakdowns is not compatible with hardcore. Remove Fluffy Breakdowns and start new game(not sure that you can salvage your save).

**Comment by Jalordon** [comment]
It may be worth its own issue report but what issues does Fluffy Breakdowns cause?

It is included with the mod pack as a mod that's not enabled by default, so I would assume that it should work, though I don't know if it works without issue.

**Comment by jnkyacc** [comment]
@Jalordon Ok. You make me completely curios about this issue. His save wont load on my version anyway so my first suggestion was that FB is our bad guy. But after you came, i just copy-paste his pawn to my save and found that @zoranjoza just put his fishing rod to inventory instead of wear it. Seems Fluffy's name now clear :)

There is you guy safe and sound.
![screenshot36](https://cloud.githubusercontent.com/assets/20729235/17935790/d6bb9348-6a1c-11e6-99f0-8a68dda8a50b.png)

**Comment by zoranjoza** [comment]
Thank you so much. 
I didnt try it with "force".
Tought that picking it up and having it in inventori is enough for him to think that he can fish with rod in inventory.
Btw how to open my "big  colony" inventory?There was a tab at botom of screen, now its removed?
