### ISSUE TITLE
I just fixed Medicine Cabinet xml tags which is in Building_Accessories.xml

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1411]
<ThingDef ParentName="ContainerBase">
		<defName>Storage_MedicineCabinet</defName>
		<label>medicine cabinet</label>
		<graphicData>
			<texPath>Things/Building/Furniture/Containers/MedicKitTable</texPath>
			<graphicClass>Graphic_Single</graphicClass>
			<shaderType>CutoutComplex</shaderType>
			<drawSize>(1,1)</drawSize>
			<drawRotated>false</drawRotated>
		</graphicData>
		<pathCost>40</pathCost>
		<statBases>
			<MaxHitPoints>100</MaxHitPoints>
			<WorkToBuild>1800</WorkToBuild>
			<Beauty>11</Beauty>
			<Bulk>24</Bulk>
			<Mass>9</Mass>
		</statBases>
		<description>Stores medicine and raw medical ingridients; prevents deterioration. Up to 5 items. Decrease rotting process.</description>
		<stuffCategories>
			<li>Metallic</li>
			<li>Woody</li>
			<li>Plastic</li>
			<li>Precious</li>
			<li>Glass</li>
		</stuffCategories>
		<costStuffCount>35</costStuffCount>
		<costList>
			<Plastic>15</Plastic>
			<Rubber>10</Rubber>
			<Component>5</Component>
		</costList>
		<tickerType>Normal</tickerType>
		<comps>
			<li Class="SK.CompContainer_Properties">
				<itemsCap>5</itemsCap>
				<texfull>false</texfull>
			</li>
		</comps>
		<building>
			<preventDeteriorationOnTop>false</preventDeteriorationOnTop>
			<fixedStorageSettings>
				<filter>
					<categories>
						<li>Medicine</li>
						<li>Drugs</li>
					</categories>
					<thingDefs>
						<li>Biomatter</li>
						<li>Paraffins</li>
						<li>SyntheticAmmonia</li>
						<li>BioDiesel</li>
						<li>Chemfuel</li>
						<li>MintLeaves</li>
						<li>Hypericum</li>
						<li>WildRose</li>
						<li>aloe</li>
						_<li>HerbalMedicine</li>_
						_<li>NeutroPetals</li>_
						_<li>PsychoidLeaves</li>_
						_<li>RawHops</li>_
						_<li>Neutroamine</li>_
					</thingDefs>
				</filter>
			</fixedStorageSettings>
		</building>
		<researchPrerequisites>
			<li>SK_StorageI</li>
			<li>VitalsMonitor</li>
		</researchPrerequisites>
	</ThingDef>

**Comment by pectus-solentis** [comment]
to store various kinds of medicine _ingredients_.

**Comment by sidfu** [comment]
u didnt fix is as it wasnt broken. the reason the ingredients are not listed for it is that its meant to hold medincine. since it doesnt most med ingredients can spoil.

just cause something isnt designed to way u  want or like doesnt make it a bug.

**Comment by skyarkhangel** [comment]
added some of them.

**Comment by pectus-solentis** [comment]
@skyarkhangel Still it doesn't store Raw Healroots.

**Comment by pectus-solentis** [comment]
![to sidfu](https://user-images.githubusercontent.com/11158226/36068327-c0129322-0eca-11e8-8519-10203e3afc95.png)
@sidfu What is it?
