### ISSUE TITLE
Plant Processing Bench is a 'crafting table' but runs off 'cooking'

### ISSUE THREAD

**Issue by timegrinder** [skyarkhangel/Hardcore-SK#1413]
Found the Plant Processing Bench appears to run off of cooking skill but is considered a 'crafting' table, so only crafters can use it which also may amplify the work time if a crafter with low cooking skill attempts to use it.

If it's meant to represent a cross-skill requirement that would make sense, but is that otherwise able to be added or are all benches restricted to a single skill requirement?

**Comment by skyarkhangel** [comment]
Okay. Changed to crafting

**Comment by timegrinder** [comment]
I probably should've said this in the original comment but is the table itself restricted to being based off crafting to start with? Because if it could be set to another skill 'Growing' might be the more appropriate skill for extracting seeds (knowing what parts of a plant to cut up/etc to replant)
