### ISSUE TITLE
Killing / butchering a Feenix does not provide the heart

### ISSUE THREAD

**Issue by timegrinder** [skyarkhangel/Hardcore-SK#1422]
After trapping and downing a Feenix I was not able to get its heart either through killing, butchering or medical operation.

Has this been disabled or is it a skill check on butchery quality to see if you can salvage it? Or does it have to be an adult? (Mine was juvenile)

I wasn't able to find a reason for it in previous GitHub issues, commits or the game files.

Any help appreciated, even if it's 'you don't know what you're doing lol' :3

**Comment by sidfu** [comment]
far as i know the fire heart doesnt drop anymore but the cold one does. think the fire one was causeing null temp errors

**Comment by timegrinder** [comment]
Ohh, cool. maybe I overlooked it in the changes.

Is there a more detailed change log stored somewhere? (Even if it's on the HardcoreSK website and I have to translate it.

Thanks!

**Comment by skyarkhangel** [comment]
i suggest to add to drop.
