### ISSUE TITLE
Potential bug with combat / work / tick controller

### ISSUE THREAD

**Issue by timegrinder** [skyarkhangel/Hardcore-SK#1427]
Hello,

I've got a current game where two things broke at the same time

1) Combat is broken in that applying a hit to a pawn / animal (whether someone attacking me or me attacking them) applies multiple hits at once, (can confirm it is an unlimited number of hits until the animal / pawn is killed, ranging from 50 to several hundred sometimes) from what I can see it is replaying the last attack constantly and applying it's damage to random body parts etc, if the enemy dodges / parries etc it will replay the parry constantly until the next attack. It also causes the hit sound to glitch and play on loop really fast indefinitely until the body hit is disposed of (butchery / burial for example) or the game client is closed / save loaded. When combat is finished the pawn is also stuck facing the direction it was facing when it made its last attack, not facing another direction until new combat or a reload.

2) The work controller breaks regularly and pawns are found standing around doing nothing, not having their needs altered by their surroundings or time and remain frozen until drafted / undrafted.

The bugs remain through reloads and restarting the game client so I'm assuming my save game is now corrupted.

Are these known potential bugs encountered in Hardcore-SK? Unfortunately I'm using the version from 31/01/2018 and have added several quality of life mods over the top so wondered if it was something that could occur in the base Hardcore-SK mod, or if someone was interested in looking at the save game if it's a bug that someone has encountered previously.

Image for example:
![rimworldwin_2018-02-22_15-54-11](https://user-images.githubusercontent.com/12099413/36521824-e5fb3fea-17e8-11e8-925c-f8e3fd67273e.png)

**Comment by fsemprini** [comment]
I have the same problem. It seems like a bug in the last update of the Simple Sidearms mod.

The mod author is already aware of the problem: https://ludeon.com/forums/index.php?topic=32497.msg399076#msg399076

**Comment by timegrinder** [comment]
Thanks for that

When I searched around I found some old and supposedly fixed reports of the bug (or something similar), and when checking the debug logs / testing and removing the SimpleSidearms mod the bug showed up again anyway and this time the debug log blamed the CombatExtended mod instead (unless the two are rolled together in HardcoreSK?)
