### ISSUE TITLE
painkiller rib & drugged rib

### ISSUE THREAD

**Issue by reaper0022** [skyarkhangel/Hardcore-SK#1428]
Can't seem to install painkiller rib & drugged rib. Thought is was a tech problem. So used dev tools research all tech. Still no option to install painkiller rib & drugged rib. Can install adrenaline rib & medical rib. I was trying to make a better soldier.

**Comment by sidfu** [comment]
ill fix in a bit when i finish what im doing. its just they not added to the race xml. someone probaly updated iwth a old copy of it

**Comment by reaper0022** [comment]
much appreciated. stared out as a tribe now have bionics (took a long time 3 tries). now just need soldier that can survive some of the big wave in coming.

**Comment by sidfu** [comment]
u can look at the changes and know where to change if u dont want to wait on the  fix to go thru.
