### ISSUE TITLE
beehive

### ISSUE THREAD

**Issue by reaper0022** [skyarkhangel/Hardcore-SK#1432]
Beehive don't search for flowers unless you make them. I still build them all the time free food, slower than molasses in January. After discovering with god-mode on I can make them search for flowers manually helps out. Without that they don't do much. I've seen other pics with hardcore sk and they had a pile of honey, so maybe it's just me.

1st pic just built 0 flowers, 2nd after flower god-mode search 27

![bee01](https://user-images.githubusercontent.com/25542352/36953016-e1172d32-1fe4-11e8-8701-2aa24f4f7510.png)

![bee02](https://user-images.githubusercontent.com/25542352/36953086-a5380aba-1fe5-11e8-9a15-2c4ab63dcbf9.png)

**Comment by timegrinder** [comment]
Unless this is a new issue I found that they do the search every x number of ticks to update the flower count, so they'll always be built with 0 flowers recognised and then within a couple of in game hours they'll pick up the flowers in range.

Are yours stuck permanently on 0 no matter how long you wait unless you manually intervene?
