### ISSUE TITLE
Frozen deep water turns to shallow on thawing

### ISSUE THREAD

**Issue by PhenotypeX** [skyarkhangel/Hardcore-SK#1437]
When deep water is frozen and then defrosts it is turned into shallow water.  Somewhat ruined my archipelago game!

This is quite an old bug I think. It was there the last time I played, about 6 months ago.

**Comment by sidfu** [comment]
this has long been fixed make sure your game is 100% updated
probaly best to do a comptely clean install that means clelaring out everything in app data then run game so it refreshes it

**Comment by Freshpage** [comment]
OK, I deleted everything in appdata apart from the save folder, and it now seems to be working for new games. 

The old save still has the problem though - presumably there is something in the original map generation which is causing it.

No problem though, at least new games are fine.

Thanks for your help!
