### ISSUE TITLE
Ammunition marked as "Any drugs" when creating loadout.

### ISSUE THREAD

**Issue by PhenotypeX** [skyarkhangel/Hardcore-SK#1438]
Steps to recreate:

1) I created a completely clean install, including deleting the entire appdata folder.
2) I started a map and used dev mode to add 25 Rimfire cartridges 
3) I got the pawn to pick them up, then clicked "create loadout"
4) In the loadout, the ammo displays as "Any Drugs".

I've tested this with 0.45 ACP and NATO ammo and get the same problem.

**Comment by Monocer** [comment]
Same here. And after correcting it, the loadout changes itself again after a while. Lots of stuff is being displayed/tagged incorrectly. For me the loadouts are currently completely unusable.
