### ISSUE TITLE
Can't install and body part?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#144]
Guys how can i perform-do operations? I go on health and add bill. There is harvest, amputating and eutanize. I dont have "install" leg, arm or w/e. I have in storage ARM and Advenced bionic arm. And i cant install it to anyone of my 9 colonists.
Any help?

**Comment by Jalordon** [comment]
Research is required to unlock installation surgeries for both bionic and natural body parts.

The in game 'Help' button on the menu bar has a search box that you can search for some information, as that's how I found out for myself that research is needed. Hope this helps if you find more questions.
