### ISSUE TITLE
Darkness event

### ISSUE THREAD

**Issue by lordmatiz** [skyarkhangel/Hardcore-SK#1448]
I've just got wiped out by Darkness, because my campfire didn't give light... and yep - it was fueled.
Campfire was fueled a moment before.
Photo of event https://prnt.sc/ivxp1j

**Comment by sidfu** [comment]
campfires sometimes bug. take and eject the fuel then once it goes out then reput fuel in. for darkness its better to use torches

**Comment by skyarkhangel** [comment]
how many fuel was in campfire?

**Comment by lordmatiz** [comment]
@skyarkhangel it was full (check link). I've refuelled it with coal right before blackout - that might be the cause. Maybe blackout overlaped delayed "light event" from the campfire?
