### ISSUE TITLE
Скорость обработки камней

### ISSUE THREAD

**Issue by alex256z** [skyarkhangel/Hardcore-SK#1449]
1) В камнерезных станках в задании по переработке осколков камней в блоки не работает модификатор пешки "скорость обработки камней".
(Нет строки "workSpeedStat>StonecuttingSpeed</workSpeedStat" в файле \Core_SK\Defs\RecipeDefs
в рецепте "MakeStoneBlocksAny")
2) За обработку камней не дают опыт

**Comment by skyarkhangel** [comment]
Так было сделано в b18, но я считаю тоже что нужно вернуть. ок.
