### ISSUE TITLE
Using the Machining bench can cause elements of the UI to disappear

### ISSUE THREAD

**Issue by Ratione** [skyarkhangel/Hardcore-SK#1450]
When using the machining table, click cut any stone blocks, then try to switch it from "Do X" mode to anything else, boom, elements of the UI disappear and dont reappear after load, only restart, and never if you saved after.

**Comment by Ratione** [comment]
Its not exactly game breaking, but it is annoying.

**Comment by skyarkhangel** [comment]
Can't reproduce. what a hardcore sk update date? i remember this bug on old a17
