### ISSUE TITLE
Food pots being overfilled

### ISSUE THREAD

**Issue by PhenotypeX** [skyarkhangel/Hardcore-SK#1451]
Food pots are getting overfilled way beyond their 4 items capacity.

I tested this will a fresh start, spawned in lots of pemmican and a pot, and this is the result:
https://imgur.com/a/EGE8g

I tested using today's build (17th March), with default mods.

Edit: after some more testing, it looks like this bug is being caused by the Pick Up and Haul mod.

**Comment by skyarkhangel** [comment]
Fixed today.
