### ISSUE TITLE
Pawn mood effects dissapear and appear all the time.

### ISSUE THREAD

**Issue by Traper** [skyarkhangel/Hardcore-SK#146]
Escape pod recruited pawn mood effects constantly flicker like in those screenshots.
http://i.imgur.com/orHEjlp.png
http://i.imgur.com/dtrBICu.png
Debug log.
http://i.imgur.com/0YhgAcV.png

**Comment by jnkyacc** [comment]
https://github.com/skyarkhangel/Hardcore-SK/issues/139

**Comment by Traper** [comment]
Duplicate issue then, closing.
