### ISSUE TITLE
IceMapComponent при каждой загрузке создает новый класс

### ISSUE THREAD

**Issue by bananasss00** [skyarkhangel/Hardcore-SK#1462]
с функцией SK_Utility.EnsureIsActive(MapComponent mapComponent) что-то не так

-------
Нашел серьезный баг влияющий на производительность.
При каждом цикле загрузка/сохранение создается новый экземпляр класса SK.IceMapComponent (game/maps/li/components). За что они отвечают?

За 3 дня игры уже создалось 100500 таких классов с множеством циферок) Убил весь день на поиск виновника. Вычищал все что можно из сейва, оставалась пустая карта, но фпс все равно уходил кудато.

И мои замеры влияния на игру:
3х дневная карта - 7фпс на х4 скорости
3х дневная карта (с удаленными IceMapComponent) - 12фпс на х4 скорости

3х дневная карта (без всех things) - 22фпс на х4 скорости
3х дневная карта (без всех things, с удаленными IceMapComponent) - 60фпс на х4 скорости!

**Comment by skyarkhangel** [comment]
Скорее всего так и есть. ок
