### ISSUE TITLE
Bug about space spice?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#147]
Hello, i had one colonist who was sad... I tought lets give him some space spice it cant harm...
So he eat it about year ago and he still have its effect, all time he is HIGH - Buzzed.(not so bad :yum:)
![untitled](https://cloud.githubusercontent.com/assets/21177680/17946425/8e9fad84-6a48-11e6-9ca8-69be92f08285.jpg)
Here is my save if it helps. Look for guy named  Tail.(junky)
https://drive.google.com/file/d/0B5eRdr0dEGLgV3YtUm52U2ZHbWs/view?usp=sharing
Bug or lucky guy?

**Comment by jnkyacc** [comment]
Drugs are bad, mmmkay?  Its bugged - permanent effect.

**Comment by zoranjoza** [comment]
Can i fix it somehow?

**Comment by jnkyacc** [comment]
@zoranjoza 
replace HediffDefs_SK.xml in Mods/Core_SK/Defs/HediffDefs/
https://raw.githubusercontent.com/jnkyacc/Hardcore-SK/patch-5/Mods/Core_SK/Defs/HediffDefs/HediffDefs_SK.xml
