### ISSUE TITLE
Странности в исследованиях гигиены

### ISSUE THREAD

**Issue by thghca** [skyarkhangel/Hardcore-SK#1474]
В гигиене II только коврики.
Гигиена III присутствует в 2 экземплярах и в обоих есть элекроунитазы и электродуш.

Обычные душ и унитаз почему-то открываются в гигиене III (первой), которая требует электричество и металлургию.

**Comment by alex256z** [comment]
Та-же проблема и у меня.  Два исследования с названием Гигиена III.
Порылся в файлах. У первой гигиены III в коде - название **ElectricCremation** (поэтому там электро крематорий). У Гигиены II в коде - название **SK_HygleneI**

Временное решение - в файле
`Mods\Dubs Bad Hygiene\Defs\ThingDefs_BuildingsBuildingsA_Hygiene.xml`
в строке 421 и 599 изменить  **`<li>ElectricCremation</li>`**  на   **`<li>SK_HygleneI</li>`**
тогда в гигиене II появляются все (электронные в том числе) унитазы и души, но электронные невозможно построить до исследования гигиены III (которая вторая (OMG!!)), что нам и надо.
