### ISSUE TITLE
Пешка внезапно перестала есть еду.

### ISSUE THREAD

**Issue by insidio118** [skyarkhangel/Hardcore-SK#1475]
На 3й год игры одна из пешек принципиально отказывалась хавать любую еду. Все утром (или по надобности) жрали, и шли по делам, а этот индивидуум игнорил позывы голода и уходил клепать компоненты. Боролся с этим кормя его вручную через приказы, но со временем этот баг крайне надоел. Есть какой-то способ решения проблемы?

P.S. Никаких оторванных челюстей и проблем со здоровьем не было. Жаль было терять одну из прокачанных пешек.

**Comment by skyarkhangel** [comment]
перезагрузку сейва делали?

**Comment by insidio118** [comment]
Что подразумевает собой перезагрузка сейва? 
Если банальный запуск/перезапуск игры, или выход в меню и загрузка последнего сейва - то да, делал. Проблема не решилась. Дело в том, что такой "болезнью" заболела 1 пешка из 10. 

Чисто в теории я мог бы убить пешку и рекрутом создать себе похожую, но это все равно не панацея.

**Comment by skyarkhangel** [comment]
Отправь сейв.

**Comment by insidio118** [comment]
Жрать не хочет челик с ником Lisolet



[wqdqd.zip](https://github.com/skyarkhangel/Hardcore-SK/files/1910419/default.zip)

**Comment by skyarkhangel** [comment]
После обновления AlienRace исчезла проблема.

**Comment by insidio118** [comment]
Спасибо, проверил по сейву всё ок
