### ISSUE TITLE
Надевается только один предмет на слот головы

### ISSUE THREAD

**Issue by bananasss00** [skyarkhangel/Hardcore-SK#1480]
![Image alt](https://image.prntscr.com/image/mXPm1b1uRUiOPw4-vpY6oA.png)
Например такой сет

**Comment by bananasss00** [comment]
Аа, это в самом римворлде косяк вроде как

**Comment by bananasss00** [comment]
https://www.upload.ee/files/8344799/CanWearTogetherFix.zip.html

добавил опцию чтобы можно было одевать перчатки, ботинки на протезы. По умолчанию отключено

**Comment by skyarkhangel** [comment]
Включил в последний апдейт: https://github.com/skyarkhangel/Hardcore-SK/commit/8ac57ff121efaa7c6486a2e6dcc3d430d6f07c0c

**Comment by bananasss00** [comment]
ок
