### ISSUE TITLE
Muffalo statue turned upside down

### ISSUE THREAD

**Issue by bubal93** [skyarkhangel/Hardcore-SK#1483]
Статуя муффало из нефрита сделана на столе скульптора.
Если поворачивать, то вращается неправильно. Повернуть лицевой стороной - будет статуя вверх ногами.
![muff](https://user-images.githubusercontent.com/17985872/38962083-e70bf8f8-436b-11e8-8500-858b0d77d8f0.jpg)

**Comment by skyarkhangel** [comment]
this already fixed 3-4 days ago.
