### ISSUE TITLE
Error's in game?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#149]
![untitled](https://cloud.githubusercontent.com/assets/21177680/17952202/8000e2e6-6a68-11e6-9f18-387a0f842342.jpg)

**Comment by zoranjoza** [comment]
Another bug about 
![untitled](https://cloud.githubusercontent.com/assets/21177680/17952966/4907780c-6a6f-11e6-96a8-8a95da0dcf01.jpg)

**Comment by zoranjoza** [comment]
Another error.
![untitled](https://cloud.githubusercontent.com/assets/21177680/17964495/b8a93520-6ab9-11e6-8aa7-4c977b5d872a.jpg)

**Comment by zoranjoza** [comment]
And another one, visitors came, and leave right away.
![untitled](https://cloud.githubusercontent.com/assets/21177680/17964518/e4bf9b36-6ab9-11e6-8341-2f15f5357c19.jpg)

**Comment by zoranjoza** [comment]
Getting those "PAWNGROUPMAKERS" errors every few min....

**Comment by jnkyacc** [comment]
Its harmless. Will be fixed later.

**Comment by skyarkhangel** [comment]
its not a "bug". As i found, storyteller with random type block itself raids until satisfy other rules.
