### ISSUE TITLE
Разделочные столы

### ISSUE THREAD

**Issue by alex256z** [skyarkhangel/Hardcore-SK#1490]
В исследованиях разделочный стол(в "Технологии") и кухонный стол(в "Земледелии") перепутаны местами и при старте игры за племя сразу доступен современный кухонный стол, а древний разделочный открывается только через исследования

Core_SK\Defs\ThingDefs_Buildings\Buildings_Production.xml
строка 249 и 327

**Comment by alex256z** [comment]
Я имел ввиду переставить разделочный стол(TableButcher) в SK_Technology, а кухонный стол(TableKitchen) в  SK_Agriculture   )))

**Comment by lavrovas** [comment]
По-моему теперь к разделочному столу нужно снижать требования по производству - зачем 6 компонентов и 2 механизма для чисто каменного стола из эпохи неолита?
