### ISSUE TITLE
Колонист из каравана предложил присоединиться к поселению

### ISSUE THREAD

**Issue by xVampiRx** [skyarkhangel/Hardcore-SK#1491]
Если нажать принять, то колонист телепортируется в колонию.
![20180420032158_1](https://user-images.githubusercontent.com/8029399/39539393-281c2340-4e48-11e8-9af7-f7582637dacf.jpg)

**Comment by Inei** [comment]
Аналогичный баг, причём при отказе, он вообще пропал из каравана. А отношения (он был помолвлен с одной из колонисток) были разорваны.
