### ISSUE TITLE
Пешки не стреляют с лука и стоят тупят . А в лог спамится ошибка .

### ISSUE THREAD

**Issue by holyinkvizitor** [skyarkhangel/Hardcore-SK#1494]
Вот скрин лога .
![image](https://user-images.githubusercontent.com/39035869/39677957-84987c08-518c-11e8-86d1-15604880b8a8.png)

**Comment by bananasss00** [comment]
в последних обновлениях убрали мод TickMultiThread, изза него скорее всего

**Comment by CEHA** [comment]
TickMultiThread не то пальто............
Там что-то напарили с коордиатами - написано веть ))

**Comment by CEHA** [comment]
WaitMaintainPosere (Job_2082560 ,,  РАЗНЫЕ

**Comment by CEHA** [comment]
СТАПЕ - я понял - 10 работ за 10 тиков - вот на что )))

**Comment by holyinkvizitor** [comment]
все оказалось проще они экипировали сами щит  а я не заметил этого .

**Comment by holyinkvizitor** [comment]
кстате они постоянно пытаются экипировать к луку щит

**Comment by CEHA** [comment]
Они дибилы - к ввинтовкам тож щиты ищут. С права ток и вижу что экипирован двуручным и щитом ((

**Comment by skyarkhangel** [comment]
Попробуйте с обновлением
