### ISSUE TITLE
Мод Pick Up and Haul не работает без корректно

### ISSUE THREAD

**Issue by bubal93** [skyarkhangel/Hardcore-SK#1501]
В последней версии пешки не подбирают много предметов к себе в инвентарь при обычной и срочной переноске, а берут только один предмет в руки (как в ванили).
Необходимо вручную указывать им команду "подобрать и перенести", иначе не работает.

В более ранних версиях (около 2 недель назад) все работало корректно.

**Comment by bananasss00** [comment]
Работает если не ставить приоритеты на предметы
![Image alt](https://image.prntscr.com/image/MuLwKgUQRGmLHikOJcLE1g.png)
и срочную переноску.

вроде и раньше  так тоже было?
