### ISSUE TITLE
Cannot throw EMP grenade

### ISSUE THREAD

**Issue by dantebelmondo** [skyarkhangel/Hardcore-SK#1504]
Pawn cannot throw EMP grenade. 
And the error log shows:
![empgrenadeerro](https://user-images.githubusercontent.com/39038359/40097480-f625d486-589b-11e8-9ac2-0f8c005d9d38.PNG)

**Comment by notfood** [comment]
This happens to Extinguisher as well. I get the feeling it's on CE side. It's trying to handle weapons that aren't CE and the cast fails.
