### ISSUE TITLE
Проблемы с выпечкой хлеба.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1510]
Тут проблема с доступностью. Дело в том, что делать муку вы можете практически с самого начала, построив мельничные жернова, но для того, чтобы из этой муки что-либо испечь, вам нужна духовка, которая доступна становится только после изобретения технологии "Production I", для которой сначала требуется изобрести электричество, что как бы не совсем логично получается - вы можете делать муку без технологий, но пока не сделаете духовку, пользоваться ей вообще никак не сможете, поскольку единственный рецепт для неё - это выпечка хлеба. Раньше, вроде бы, была доступна каменная духовка, которая появлялась намного раньше, но теперь её нет, и единственный способ использовать муку - изучать технологии. Что для игры за племя, довольно непростая задача сама по себе.

**Comment by skyarkhangel** [comment]
ok
