### ISSUE TITLE
Лаунчер не запускается

### ISSUE THREAD

**Issue by RPgK** [skyarkhangel/Hardcore-SK#1517]
Лаунчер просто не запускается. В логах файл приведенный ниже. Вопрос - что делать?
[Report HSKL.zip](https://github.com/skyarkhangel/Hardcore-SK/files/2046987/Report.HSKL.zip)

**Comment by TBXin** [comment]
1. .NET Framework 4.5 установлен?
2. Диск M это физический раздел или сетевая шара?

**Comment by RPgK** [comment]
1) Да, ведь в 10 версии Windows он установлен по дефолту, Стим установил и 3 версию. Через Программы и компоненты, убедился что оба используют. Через средство диагностики прогнал, изменений нет. Обновил диретикс, внес изменения в реестр. Иначе говоря - Сделал все, что советует интернет при данной ошибки (Да, я думал что мне не ответят и начал сам разбираться). 2) Диск м - изначально был внешним диском. Думал беда в нем, по-этому удалил игру, и переустановил на внутренний диск. И, не сильно это помогло, от слова соовсем

**Comment by TBXin** [comment]
> M:\st\steamapps\common\RimWorld\HSKLauncher.exe

А зачем вы закинули ланчер в корневую директорию игры? Другие файлы, которые шли вместе с ланчером вы тоже закинули сюда же?

Для работы ланчера нужны все файлы, которые поставляются вместе с ним, а именно:

- Languages (папка)
- HSKLauncher.exe
- Caliburn.Micro.dll
- Caliburn.Micro.Platform.Core.dll
- Caliburn.Micro.Platform.dll
- NLog.dll
- Octokit.dll
- System.Windows.Interactivity.dll
- HSKLauncher.exe.config

Все перечисленные файлы и папка должна лежать на одном уровне.

**Comment by RPgK** [comment]
Аааа, я использовал только сам Exe. Пользовался инструкцией с hardcore-sk, и на 5 странице написано - "Автоматический установщик обновлён. Информация готовится и скоро всё станет понятно. Пока же можно с уверенностью сказать, что файла HardcoreSK_Updater.exe на гитхабе больше нет, вместо него нужно скачать файл HSKLauncher.exe. Остальное должно быть интуипонятно. Ждём новости"
Так вот, я и считал что остальное - для внутреннего пользования. Вон, написано же - нужно скачать файл (не файлы). Ну хорошо, сейчас проверю

**Comment by RPgK** [comment]
Да, теперь все работает, большое спасибо. Кейс закрыт
