### ISSUE TITLE
Crashlanding - New Classic

### ISSUE THREAD

**Issue by Tyroki** [skyarkhangel/Hardcore-SK#152]
Is there any chance we can have a version of Crashlanding like the version of Hell Effect you can download from Mega?

With all of the various ship chunks, like mechanic and beam?
I'd like to make some custom scenarios, but the only ones that have all of these are the crashlanding based ones with the full crash site. Awesome as that crash site is, it DOES kinda screw over Prepare Carefully (as you already know).

Crashlanding Classic only has the 3 ship chunks, and as we still can't seem to ADD ship debris ourselves, we can't remove them if we want them. But if we want all of these different types of ship debris to be scattered, we have to make scenarios from the versions of crashlanding with the full crash event... which then makes ALL scenarios have the full crash event.

Also the craters are a pain in the ass :\

**Comment by jnkyacc** [comment]
I believe Crashlanding will be reworked soon or later. Craters will be removable(fillable).
Classic scenario is a temporary remedy. I think it pointless at this point to add other ship chunk(or any resources) as people adding what they wand through PC.
You can edit any scenario by editing scenario.xml in Mods\Core_SK\Defs\ScenarioDefs

**Comment by skyarkhangel** [comment]
Reworked scenarios, now we have "Classic" scenario without crashlanding.
