### ISSUE TITLE
Exception ticking MechanoidShipIncoming

### ISSUE THREAD

**Issue by XaocDIO** [skyarkhangel/Hardcore-SK#1520]
Здравствуйте! 
Проблема с отрисовкой корабля механоидов. Иногда отдалив камеру, можно увидеть, как он ползет вниз.
![image](https://user-images.githubusercontent.com/10487765/40746077-099a6d66-6462-11e8-81e8-a5f9469f902b.png)
[рапторы.zip](https://github.com/skyarkhangel/Hardcore-SK/files/2055589/default.zip)

Это проблемы моего компа или мода? Переустановил игру с нуля. Проблема не исчезла.

**Comment by skyarkhangel** [comment]
Должно быть поправлено в последних обновлениях.
