### ISSUE TITLE
Доработка Launcher для медленного интернета.

### ISSUE THREAD

**Issue by XaocDIO** [skyarkhangel/Hardcore-SK#1521]
Здравствуйте!
У меня 3G интернет и при скачивании обновлений через лаунчер происходит зависание на определенном проценте.
Но я могу скачать архив с гитхаба.
Можно ли доработать лаунчер, чтобы он мог устанавливать мод в том числе с заранее скаченного архива. 

Было бы очень здорово.

Заранее спасибо.

**Comment by TBXin** [comment]
Добрый день,

Будет в следующей обнове ;)

![](https://i.imgur.com/WHNzJEX.png)

**Comment by XaocDIO** [comment]
Очень здорово!
А то каждый раз при сбое обновления качать 200мб при ограниченном интернете накладно :)
