### ISSUE TITLE
Psychic Soothe Affecting Less?

### ISSUE THREAD

**Issue by Tyroki** [skyarkhangel/Hardcore-SK#153]
Just got a Psychic Soothe global effect for females, and only one of my three females is being affected.

**Comment by Tyroki** [comment]
Actually, the cleaning thing is a pretty big deal.
All of my pawns are freaking out about how disgusting the place with all of the blood everywhere from defending their home, yet none of them will clean it up. The mood debuff from that is intense.

Does it require research, or is it flat out broken for me?

The only thing I've added is Phi Client for the sake of a little multiplayer with my friends.

**Comment by Tyroki** [comment]
Shouldn't it be affecting all females not just one?

**Comment by jnkyacc** [comment]
I cannot reproduce it. Just to confirm that all females same race? If so you can close issue and reopen if you encounter same way again.
Not sure but also possible some trait effect countered PS

**Comment by Tyroki** [comment]
I'll see what happens if Soothe ever comes up again (my luck with it tends to be awful.)
All females were standard humans.

The game this happened in didn't go so well. I was counting on the Soothe to chill the other two girls as they were close to the deep end. They went over, and it ended the colony.
I did check over their traits at the time, and none were immune to psychic phenomena hence the confusion.

I'll keep this open and see if it happens again.

**Comment by skyarkhangel** [comment]
Closed. old version
