### ISSUE TITLE
Ice Stalagmites and pathfinding.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1533]
Тут проблемка в том, что колонисты не считают их препятствием при прокладке пути движения к цели. То есть если подобный кристал вырастает на проходе, они в него упираются, и стоят, не могут пройти, даже если рядом есть свободный проход.

**Comment by LuckyAss** [comment]
Разве это не пофиксили вчерашним обновлением?

**Comment by Inei** [comment]
У меня последняя версия вроде. Сейчас переустановлю ещё раз проверю. Или нужно новую игру просто начинать?

**Comment by skyarkhangel** [comment]
Проверьте на последних обновлениях.
