### ISSUE TITLE
Cleaning problems

### ISSUE THREAD

**Issue by Tyroki** [skyarkhangel/Hardcore-SK#154]
Actually, the cleaning thing is a pretty big deal.
All of my pawns are freaking out about how disgusting the place is, what with all of the blood everywhere from defending their home. However, not one of them will clean it up. The mood debuff from that is intense. I've even tried turning everything else off in the work tab, and I can't even force them to clean. It's pretty bad.

Does it require research, or is it flat out broken for me?

The only thing I've added is Phi Client for the sake of a little multiplayer with my friends.

**Comment by jnkyacc** [comment]
You should designate cleaning zone same way as home\stockpile\ect. Area\zone tab.

**Comment by Tyroki** [comment]
Ah. Thank you very much. 
I'm new to the pack, so I was used to just expanding the home zone to clean.
Having a cleaning zone is bloody nice. Cheers!

Feel free to kill this thread with fire then :D

**Comment by jnkyacc** [comment]
Just press "close issue" some where in the bottom.
