### ISSUE TITLE
Азари и болезни.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1542]
Тут проблема в том, что они долгожители, конечно, но генератор из-за этого у них очень много болезней генерирует, в том числе старческих. До такое степени, что в последнем рейде из 40 азари не было ни одной здоровой, у всех начиная с доброкачественных опухолей и астмы, до некрозиса и вирусов со страшными названиями в честь немецких учёных. Такое ощущение было, что они не воевать пришли, а помереть, чтобы не мучаться. Трое, кстати, умерли от перетонита ещё до начала атаки...

**Comment by alex256z** [comment]
Вот-вот, и у меня то-же самое)). из 14-ти азари две без ноги, ещё 3 без руки и у всех куча болезней. Прям как в каждой моей команде из World of Tanks))

**Comment by ynemo** [comment]
Генератор при создании болезни должен ориентировать не просто на возраст, а на отношение текущего возраста к "максимальному" возрасту особи.

**Comment by Inei** [comment]
Ну там явно что-то не так. Потому что приходит толпа полумёртвых инвалидов.

**Comment by ynemo** [comment]
Да, генератор похоже думает, что после 70-80 лет пора умирать ,независимо от вида особи.
А надо бы сделать, чтобы на отношение текущего к максимальному ориентировался.

**Comment by skyarkhangel** [comment]
Понятно все, это из-за PrepareCarefully, который не учитывает изменения в AlienRace.

**Comment by ynemo** [comment]
Я его отключил нафиг - бесполезный мод, никогда им не пользовался.
