### ISSUE TITLE
Ice stalagmites melt very slow comparing to growing.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1546]
Ледяные сталагмиты тают очень очень медленно. Проверяла в комнате с антиматериальным реактором, по сравнению с тем как они растут, скорость таяния примерно 1-2% за игровой час при температуре 2000 градусов. В то время как при минус 10, они растут по 10-20 процентов за тот же час. В первом случае скорость таяния -20000%+, во втором скорость роста около 100%.

**Comment by zachary-foster** [comment]
Thanks for the report. I will look into this. They should melt faster. In my tests, they melted at -300% at about 25C.

**Comment by zachary-foster** [comment]
I checked it on my current version and full size ice stalagmites melt in about 2 days at 20C. Maybe its a bug in an older version?
