### ISSUE TITLE
Различные баги

### ISSUE THREAD

**Issue by Sushnostb** [skyarkhangel/Hardcore-SK#1555]
1.За разделку терминаторов вешается дебафф -6 всему поселению как при разделке человека. 
2. Фелин страдает от болей, которые появляются вместе с сообщениями о развитии карциномы. Первое время пешка просто страдала от боли, затем проскочили и сами карциномы.
![default](https://user-images.githubusercontent.com/40970862/42452692-756eb240-8393-11e8-99ab-13af5045848a.png) К примеру, здесь игра ограничилась сообщением, но новую болячку так и не завезла. Пешка периодически теряет сознание от боли, когда появляются сообщения о новой карциноме. ![2](https://user-images.githubusercontent.com/40970862/42452955-1e297abe-8394-11e8-890b-652736eddcb4.png) За один игровой день бывало по 2 сообщения.

**Comment by ynemo** [comment]
Карциома находится в скрытой стадии. Она себя ещё не проявила, и поэтому не отображается в панели здоровья.
