### ISSUE TITLE
To Desktop, If attack another village

### ISSUE THREAD

**Issue by Feeudeel** [skyarkhangel/Hardcore-SK#1556]
When my man and Terminator try to Attack another Village, the map loads and I can see it, but after 1 - 3 seconds the Game quits and i go Back to Desktop.
In Error Log it says: "KERNELBASE.dll caused a breakdown"

Could it be that I ran out of Ram?

**Comment by skyarkhangel** [comment]
Seems yep, start to use our x64 Rimworld version for b18.
You can find it in our discord server or ask some in chat.
