### ISSUE TITLE
Tents and Sleeping Bags

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1560]
While Tents are made on the Tailor's Workbench, Sleeping Bags being made on the ground (where it will be setted up) seems a lot unrealistic and bizzare.

How about fixing Sleeping Bags to be made on the Tailor's Workbench just like Tents?

**Comment by FennexFox** [comment]
Why don't you just fix all your suggestion yourself, commit, do a pull request and let them decide to accept or not?

What's the point of shoving all of your thoughts to others?

**Comment by pectus-solentis** [comment]
@fennexfox I have no access to RimWorld because I'm hospitalized now and I don't know how to use Pull Request.

**Comment by FennexFox** [comment]
IF that's the case, you can stop nagging until you can do a legit contribution.

**Comment by zachary-foster** [comment]
Hi @pectus-solentis, 

If you have a computer, you can contribute to HDSK using github and git. Here is a summary of what you do:

1. Install git. How you do this will depend on you OS.
1. Fork the HDSK repo on Github to your own account. This will make a copy you can edit. See https://help.github.com/articles/fork-a-repo/
1. "clone" **your fork** of the HDSK repository onto your computer. Using git from the terminal/command line, this would be: `git clone git@github.com:pectus-solentis/Hardcore-SK.git`. This will make a new folder called "Hardcore-SK" with all of HDSK and its history. If you are not using the command line, then how you do this will depend on what program you are using to interact with git.
1. Make changes and commit them. If you don't know how to use git, there are many good tutorials online.
1. Push the new commits to **your fork** on github.
1. submit a pull request to ask Sky to accept your changes. See https://help.github.com/articles/about-pull-requests/

Just repeat the last three steps to add more changes after that.
