### ISSUE TITLE
Пищевые контейнеры

### ISSUE THREAD

**Issue by alex256z** [skyarkhangel/Hardcore-SK#1563]
Все пищевые контейнеры перестали правильно работать после добавления в сборку мода **Rimworld Search Agency** - колонисты заполняют всего один стак в горшке/сервировочном столе а всё остальное носят на склад. (FixSaveStorageSettings убран)

**Comment by alex256z** [comment]
p.s.     В бочки еда тоже не складывается (всякие блюда не складываются, а с мясом всё ОК)

**Comment by Azrael1980** [comment]
Оружие в сундуки тоже 1-2 ложится +гранаты, больше не складывают.

**Comment by Kiriharas** [comment]
Есть вариант откатиться до версии перед установкой RSA, многим помогло

**Comment by skyarkhangel** [comment]
Ок. проверю
