### ISSUE TITLE
A minor addition to Basalt cutting.

### ISSUE THREAD

**Issue by CJoker3221** [skyarkhangel/Hardcore-SK#1564]
As most would have noticed, working Basalt (From NPS) on a Stonecutting Bench doesn't produce Sand and Rubble as a by-product, I would do it myself..but I have little to no idea on how to do that myself.
Edit: It also only produces 10 blocks, instead of 20 like the others!

**Comment by FennexFox** [comment]
Made a pull request about it, hope it's gonna be merged

**Comment by skyarkhangel** [comment]
Added
