### ISSUE TITLE
Storage structures with a beauty value don't have beauty

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [skyarkhangel/Hardcore-SK#1569]
For example, a Commode, Shelf, Armory, none of them have an impact on the beauty of a room.
Example with golden commode-
https://i.gyazo.com/508dc62b8880a2e0a10ce9a9a7b76bdd.png

**Comment by skyarkhangel** [comment]
Seems its a vanilla bug, this buildings have ignoreStoredThingsBeauty setting, which should apply only on things in container, not itself.
