### ISSUE TITLE
Баг после фикса RSA

### ISSUE THREAD

**Issue by bananasss00** [skyarkhangel/Hardcore-SK#1572]
Вот видео, что происходит
https://streamable.com/bcovd

1) сыпятся ошибки в консоль
2) и заполненность бочки периодически скачет 6/6 <-> 7/6
Как я понял, такое возникает когда в бочке есть неполный стак каких то предметов

В других тестах бывало что пешки налетают на бочку и бесконечно пытаются в нее чтото закинуть(с ошибкой в консоль) )))

**Comment by skyarkhangel** [comment]
Привет. Да, так и есть. Разбираюсь.

**Comment by bananasss00** [comment]
Привет. Спасибо за фикс. Сейчас вроде все ок
