### ISSUE TITLE
Фелины и люди

### ISSUE THREAD

**Issue by alex256z** [skyarkhangel/Hardcore-SK#1573]
Возможно, это нормально и это предусмотрено модом, но выглядит странновато )))
![cat1](https://user-images.githubusercontent.com/13462761/43205832-eb6723d8-902c-11e8-9e2e-636a957acfc0.png)
![cat2](https://user-images.githubusercontent.com/13462761/43205833-eb8b5582-902c-11e8-9561-e83d7c866028.png)
![cat3](https://user-images.githubusercontent.com/13462761/43205834-ebad31fc-902c-11e8-951a-6a428af28888.png)

**Comment by skyarkhangel** [comment]
Уберем, оставим?

**Comment by alex256z** [comment]
Оставим!)) Будет небольшой бонус при рекруте фелинов в колонию, да и моя больная фантазия будет иногда рисовать мне ЭТО



![46f23020efc344705cb18763393577a3](https://user-images.githubusercontent.com/13462761/43330449-eba16412-91cb-11e8-92f1-da6fd240d78e.jpg)
