### ISSUE TITLE
PickUpAndHaul и Haul Priority [Fix]

### ISSUE THREAD

**Issue by bananasss00** [skyarkhangel/Hardcore-SK#1575]
https://www.upload.ee/files/8752022/PickUpAndHaul_SKFix.zip.html

**zPickUpAndHaul_SKFix.dll** нужно закинуть в **Mods\PickUpAndHaul\Assemblies**
Исходник прилагается.

PS:
Сам мод особо не изучал, просто взял фикс совместимости для AllowTool в самом PickUpAndHaul и перенес его для HaulPriority :)

В принципе получилось неплохо, сначала берут то что в приоритете и по пути забирают что нибудь еще.

Видео:
https://streamable.com/i6e30

**Comment by skyarkhangel** [comment]
Привет, у нас в группе дискорда сидит автор PickUpAndHaul. Можно было бы ему показать.

**Comment by bananasss00** [comment]
Привет, понял)
