### ISSUE TITLE
Pawns don't storage items after containers reach 6/6

### ISSUE THREAD

**Issue by Xplendit** [skyarkhangel/Hardcore-SK#1576]
Example given:
In container: 

1. item 1 x 75
2.  item 2 x 75
3.  item 3 x 75
4.  item 4 x 75
5.  item 5 x 75
6.  item 6 x 25

And you have item 6 x 25 in another stockpile, your pawns won't haul it to the container. As soon as you remove 1 item. your pawns haul it to the container.

video:
[https://streamable.com/7szlz](https://streamable.com/7szlz)

**Comment by bananasss00** [comment]
bug https://github.com/skyarkhangel/Hardcore-SK/issues/1572 comeback :)

https://streamable.com/beom1
