### ISSUE TITLE
Лаунчер не обновляет ModsConfig.xml

### ISSUE THREAD

**Issue by definitelynotalex1** [skyarkhangel/Hardcore-SK#1580]
Вообще обновляет, но если даже указать "только для чтения", после запуска игры все сбрасывается и в модах пустота, запускается ванила

**Comment by definitelynotalex1** [comment]
Извиняюсь, при "рид онли" игра вообще не запускается, но при запуске все обнуляется 
![default](https://user-images.githubusercontent.com/36571362/43950940-35a38e3e-9cab-11e8-867c-1176421862f0.png)
![default](https://user-images.githubusercontent.com/36571362/43950963-4725c212-9cab-11e8-9354-6c3b8bc13c96.png)

**Comment by definitelynotalex1** [comment]
проблема исчерпана, не знал, что мод все еще под А17

**Comment by definitelynotalex1** [comment]
Тема все еще открыта

**Comment by skyarkhangel** [comment]
не надо ставить маркер "только для чтения". Римворлд сбрасывает модконфиг при серьезных ошибках. Приложи лог, после того как игра сбросит его. В папке игры RimWorldWin_Data, файл output_log.txt

**Comment by definitelynotalex1** [comment]
Проблема решилась сама собой, я удалил какую-то папку update из корня, и установил все вручную, попробовал для перепроверки удалить и установить через лаунчер, все встало как надо
