### ISSUE TITLE
Surgeries Not Showing Up

### ISSUE THREAD

**Issue by ghshell** [skyarkhangel/Hardcore-SK#1582]
The only way I see implant options is if I go to the medical tab and left or right click on a stat for a colonist. The operations tab under health does not show implants at all, even if I have it in my stockpile ready to use. I cannot find a way to install joy wire or cybernetic tail. I have installed cybernetic spine, exo, brain stimulator, and cybernetic limbs successfully through the medical tab.

**Comment by crowman69** [comment]
You can't cure scars either so it looks like the medical mod is broken.
