### ISSUE TITLE
Pawns won't avoid lava tiles

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#1583]
Maybe just make it unpassable like deep water tiles, idk

**Comment by sidfu** [comment]
its not a issue with the tile it a issue with how the game does pathing.
short range pathing is accurate but longer the pathing is the more inaccurate it gets to the point where it hardly even cares what the tile is. for lava zones at start make a zone covering all the lava areas then invert it and sset that as a zone for all pawns should prevent them going over it

**Comment by LEEROU** [comment]
@sidfu yeah with rimworld mechanics I can understand how hard it is to fix it but instead of fixing it or messing with areas why not just make it unpassable for now?
I bet this isn't hard and can be done in xml (but really can't say for sure)

**Comment by sidfu** [comment]
its passable as it can be used as part of natural defenses. with the ablity in b19 of putting buildings on water we probaly be able to have specal buildings to put on lava and such.

look in patches channel for a quick patch u can use for now to make both deep and lava inpassable

**Comment by LEEROU** [comment]
Appreciated tnx
