### ISSUE TITLE
Combat Realism - Ammoless Mod Option

### ISSUE THREAD

**Issue by Tyroki** [skyarkhangel/Hardcore-SK#159]
Now, don't get me wrong. I LOVE ammo myself, and am going to constantly use it.
I do think the mod itself could use a Mod Option to turn ammo off though (purely optional, not something forced), if possible.
I'm asking on behalf of my buddies, as the extra micromanaging of needing ammo is putting them off, and the sole thing putting them off of the pack.

**Comment by skyarkhangel** [comment]
at the moment this is not possible, i havent time to work with combat realism
