### ISSUE TITLE
Fungiponics requires Compost, not Raw Compost or Fertilizer

### ISSUE THREAD

**Issue by LoliScout** [skyarkhangel/Hardcore-SK#1598]
The Fungiponics Basin requires Compost, which appears to have been removed, instead of Raw Compost or Fertilizer. Version 2018.10.28
![bugs](https://user-images.githubusercontent.com/24879707/48324771-7610c880-e600-11e8-95aa-ac67950f3464.png)

**Comment by LoliScout** [comment]
Only Raw Compost can be made. Help Tab has no information on regular Compost. Unsure if the Kitchen Table is supposed to be able to make Raw Compost, but it can't while the lower tier Butcher Tables can.
![bug bug](https://user-images.githubusercontent.com/24879707/48324929-2ed70780-e601-11e8-80d4-2e080b71805b.png)

**Comment by sidfu** [comment]
if u can move to discord im in there now. it might be a install issue as im ingame now on 1.0 and i only have compost now raw version

**Comment by LoliScout** [comment]
Was a problem with the b18 version. Closing this now.
