### ISSUE TITLE
Growing zone behavior: minimum 100% fertility

### ISSUE THREAD

**Issue by Masquerine** [skyarkhangel/Hardcore-SK#16]
The way that the growing zone currently works is that you can only place it on soil that has a minimum of 100% fertility. This renders poor soil, dusty soil and marginal soil unable to be in a growing zone (30%, 40% and 70% fertility). Some crops that can go in growing zones can be planted in soil as low as 5% fertility, which is why the 100% fertility requirement to be a growing zone is conflicting.

I'm not sure how to fix the minimum behavior on growing zone, and the other alternative fix would be to adjust all of the values on plants/soils so that 5%/30%=100% as the new minimum, so that these soils can be used for simple things like flowers. The maximum fertility on tilled soil could then go from 200% to 300% to compensate for the change, possibly.

I'm not sure how you want to handle this.

**Comment by skyarkhangel** [comment]
Yep, need to fix and some growing factor rebalance for some plants

**Comment by skyarkhangel** [comment]
Updated.
