### ISSUE TITLE
Game crash after reducing the game view

### ISSUE THREAD

**Issue by Bloodman93** [skyarkhangel/Hardcore-SK#1603]
[2018-11-17_130030.zip](https://github.com/skyarkhangel/Hardcore-SK/files/2591748/2018-11-17_130030.zip)

**Comment by sidfu** [comment]
not a bug u ran out of memroy

0 MB physical memory [2685 MB free].
0 MB paging file [2883 MB free].
0 MB user address space [104 MB free].


b18 versin is 32bit only. on discorfd look for the pins and the b18 64x patch

**Comment by Bloodman93** [comment]
Thanks a lot.
