### ISSUE TITLE
Korean Language disappear bug

### ISSUE THREAD

**Issue by J1STAR** [skyarkhangel/Hardcore-SK#1604]
Error Process
1. Option - Choose Language - Select English - Restart
2. Main - Click Flag Image - Select English - Restart
3. Can not choose Korean anymore (Korean option disappeared)

**Comment by skyarkhangel** [comment]
May be bad updated? Try to check for errors. Or reupdate

**Comment by J1STAR** [comment]
OK. i will try updated version. #1605
