### ISSUE TITLE
Infinite Honey Generate

### ISSUE THREAD

**Issue by J1STAR** [skyarkhangel/Hardcore-SK#1610]
Queen BeeHouse in Food Storage = Infinite Honey Generator
![2018-12-08 3 39 15](https://user-images.githubusercontent.com/8870540/49666277-e8a78380-fa9a-11e8-9843-057642400bdc.png)

**Comment by sergii-okhotnyi** [comment]
Here is log if helps: https://git.io/fhiTZ
