### ISSUE TITLE
Не все ванильные текстуры заменены

### ISSUE THREAD

**Issue by JohnySilver** [skyarkhangel/Hardcore-SK#1613]
Обнаружил, что текстуры компонентов взяты из ванильной версии. Продвинутый механизм тоже стилизован под ваниль.
Как выяснилось, это новая концепция HSK: смешать ваниль и HSK.
Данная концепция является спорной, поэтому отписываю о ней, как о баге.

Поклонники ванили и HSK - это две разные аудитории.
Поклонникам ванили не нужен HSK с его продвинутыми механиками, усложненными производственными цепочками, разнообразием экипировки, одежды и проч. Они ищут другой геймплей, более PVEшный и ненапряжный. Например, мой знакомый играет в ваниль и смотреть не может в сторону HSK, потому что он развлекается тем, что дает колонистам имена своих знакомых и смотрит за социалкой, или добавляет через режим разработчика на карту трумбо с терминальной стадией зависимости от люцеферция и натравливает его на врагов. Зачем ему HSK? Одними текстурками ванильцев не завлечь, для этого надо оболванивать весь HSK.

HSK'шники в свою очередь смотреть на могут на ваниль без чувства тошноты из-за ее примитивизма, в том числе в графическом оформлении.

Попытка сделать полуваниль, полуHSK, которая будет нравиться всем, приведет к тому, что получится недованиль и недоHSK, которая не будет нравится никому.
У HSK уже есть своя аудитория, зачем ее отпугивать, пытаясь привлечь тех, кому HSK не был и не будет интересен?
Поэтому предлагаю оставить все визуальное оформление в исконном стиле HSK.

**Comment by IngriTapper** [comment]
Не мне судить, я всё же не из разрабов, но может быть текстурки были взяты как временная мера? Не все умеют рисовать, я например точно не умею, а придумывать и реализовывать текстурьё - и подавно. Но как то отображать вещи необходимо. И тут приходит на помощь ваниль.

**Comment by JohnySilver** [comment]
Увы, нет.
Текстуры компонентов и продвинутых механизмов уже были в b18, их не надо было рисовать, только перенести.

**Comment by LEEROU** [comment]
Текстуры компонентов не выглядят **слишком** мультяшно для хск. Есть необходимость менять только те, которые не вписываются в сеттинг. 

Такую драму развёл, будто текстура компонентов абсолютно полностью совсем разрушит погружение.

И тем более я уверен, что скоро её заменят.

**Comment by JohnySilver** [comment]
> Текстуры компонентов не выглядят **слишком** мультяшно для хск.

Поэтому в предыдущих версиях HSK они были заменены *facepalm*

> Такую драму развёл

Спасибо за твое ценное, аргументированное мнение о том, что не относится к проекту. Ты выбрал самое подходящее место для его озвучивания. Только сильно не отвлекайся, а то некому будет в Одноклассниках оценки фоткам с пляжа ставить.

> будто текстура компонентов абсолютно полностью совсем разрушит погружение
Разрушит. 
Аргументы будут или просто поскандалить пришел на Гитхаб?
И откуда эти выводы про "абсолютно полностью совсем"? Не надо приписывать людям слов, которых они не говорили.

**Comment by skyarkhangel** [comment]
Мы не меняли текстур, это изменения в 1.0 как бы "пробивают" текстуры хск. Переодически нахожу и меняем пути текстур, чтобы такого не происходило. Так что, все будет ок.

**Comment by skyarkhangel** [comment]
Текстурки компонентов были уже сделаны сегодня.

**Comment by JohnySilver** [comment]
Я на форуме вопрос задавал можно ли где-нибудь ознакомиться с концепцией нового HSK и описанием того, что планируется сделать, потому что сейчас непонятно - что баг, что новый вектор развития, а что вообще фича)
Хотя бы краткое описание основных моментов упростило бы очень тестирование.
