### ISSUE TITLE
New colony has 300 000 building wealth

### ISSUE THREAD

**Issue by Stevey34** [skyarkhangel/Hardcore-SK#1617]
In the 1.0 developer branch, new colonies may have very high building wealth for no apparent reason. This results in mood penalties and very difficult raids. The colony died to centipedes before I could get any weapon capable of damaging them. ~~I think the reason for the wealth is that due to some of the mods, ancient danger rooms may contain high value floors, which are erroneously counted as colony wealth. (Another possible cause could be the ancient asphalt road that was on the map, I do not know how much wealth broken asphalt adds).~~

**Comment by Stevey34** [comment]
I was wrong about the reason above. I found out this bug is actually caused by sand tiles having a high value. Because sand tiles have a high value, desert colonies have a very high initial wealth.

**Comment by Voker57** [comment]
> I was wrong about the reason above. I found out this bug is actually caused by sand tiles having a high value. Because sand tiles have a high value, desert colonies have a very high initial wealth.

Do you know where's the problem in the code?

**Comment by Antirrhinum-ru** [comment]
> > I was wrong about the reason above. I found out this bug is actually caused by sand tiles having a high value. Because sand tiles have a high value, desert colonies have a very high initial wealth.
> 
> Do you know where's the problem in the code?
@Voker57 
The problem with high values of sand and rich soil tiles was solved in commit on Dec 21, 2018
