### ISSUE TITLE
Can't Tame Buffalo/Muffalo

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#162]
I have the option to select them and click tame but they are not tamable.  If I click on a pawn that has handling and the right click the buffalo to force taming as a priority it won't work.  

I tested this a few times and if the buffalo is the only animal for taming and the handling priority is highest the buffalo still doesn't get tamed.

I am not sure if the script for them is complete.

I have no other mods except this one.

**Comment by jnkyacc** [comment]
Any messages/errors?

**Comment by Vigilence** [comment]
None, the pawn just doesn't tame them.  They are not clickable when forcing a pawn to tame them.  

I can still click the tame button, but nothing more.

**Comment by K0t0fay** [comment]
да приручить маффало не получается. Не доступна принудительная команда

**Comment by Vigilence** [comment]
I meet the tame level, as I am level 9 and they require level 4 handling.

**Comment by Vigilence** [comment]
Here is the window that popups when right clicking the muffalo or buffalo when your handler is selected.

![screenshot 27](https://cloud.githubusercontent.com/assets/16742086/18012637/737d040c-6b88-11e6-944f-8eab902bd6d3.png)

![screenshot 26](https://cloud.githubusercontent.com/assets/16742086/18012638/73825150-6b88-11e6-8f6a-e63cea7b6052.png)

![screenshot 25](https://cloud.githubusercontent.com/assets/16742086/18012639/738363b0-6b88-11e6-8d5f-92db6c8952d1.png)

**Comment by jnkyacc** [comment]
Looks like taming broken

**Comment by Vigilence** [comment]
I can tame rabbits and such.  Just not these guys.  Since I have only had the mod for 2 days, I am not sure if effects the other animals that are not vanilla, or that have new art.

**Comment by K0t0fay** [comment]
Из всех животных на карте я могу приручить только римволка и серого волка (появляется опция принудительного приручения при нажатии правой кнопкой мыши)

**Comment by jnkyacc** [comment]
1) Equip backpack. 
2) Have proper food type(meat for predator and ect.)

You cannot tame it because you pawn unable to take needed amount of food into his inventory. Big animals require more food that you pawn can haul.

**Comment by Vigilence** [comment]
I see. My base is only a day old so that might be why, since I have no crops.   I wasn't thinking about that.  I don't have a backpack, is that craftable in this mod pack?

**Comment by jnkyacc** [comment]
Craftable\tradeable\removablefromdeadbodies

**Comment by Vigilence** [comment]
Nice, ty.

**Comment by skyarkhangel** [comment]
Added ability to tame rough animals with hay.

**Comment by skyarkhangel** [comment]
Solved andc closed.
