### ISSUE TITLE
Balance: Ammo cooking off does too much damage

### ISSUE THREAD

**Issue by stevehv** [skyarkhangel/Hardcore-SK#1621]
One hit from an inferno cannon will down a colonist, which causes him to drop all the ammo in his inventory, which will make the ammo cook off instantly due to fire. Hundreds of bullets will kill the downed colonist and all other colonists nearby, because each bullet does as much damage as a gunshot wound.

I think cooking off handgun ammo should not do more than few points of damage. A cartridge exploding outside a gun barrel would give the bullet very little velocity. Handgun ammo cooking off dealing as much damage as gunshots is unbalanced and unrealistic. Can this be rebalanced?

**Comment by Szara-ManOfHonor** [comment]
In mod options go to combat extended, there you can turn on realistic ammo cookoff, which does not spawn damaging projectiles. Though I agree a middle ground would be better. The mod team is still waiting on the official CE update to 1.0.

**Comment by stevehv** [comment]
@Szara-ManOfHonor Thanks, I did not know that was possible. I will turn that on for now.
