### ISSUE TITLE
Не указывается время когда испортится продукт.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1626]
Установил ваш мод H-SK и запустил игру. Заметил баг. Ни у каких продуктов не отображается время когда он испортится. Написано "(испортится через )". Время не указано. Сохранился, вышел, опять запустил игру и загрузился. Проблема сохранилась но стала проявлять себя иначе. Теперь кликая например по одной клетке с кокосами время указано. А кликая по другой клетке с другими кокосами оно как и раньше не указывается. Возможно время показывается к продуктам которые должны скоро испортится. Но я в этом не уверен.

**Comment by Andry2017** [comment]
Так же и в других местах наблюдал подобную проблему. Например в событии спасти человека. Так же не показывалось до какого числа это нужно успеть сделать.

**Comment by masakitenchi** [comment]
Closed as too old
