### ISSUE TITLE
Movement circles most of the time do not render

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#163]
Normally when giving one or more drafted pawns a move order the game briefly shows a circle for where pawns are going to go.

Most of the time these circles are not rendering when giving move orders, making it harder to tell where pawns are going to move.

Observations: On loading a game paused the circles are working normally. After 2-5 seconds of the game unpaused the circles stop rendering.

edit: Nothing substantial is logged that looks like it would be an issue, only white text.

Can anyone else confirm if this issue is occurring?

**Comment by jnkyacc** [comment]
Confirm. Disappearing - appearing in ~30-60 sec interval.

**Comment by Jalordon** [comment]
If you mean path lines as the line from the pawn to their destination, yes.

On another note I tried syncing my fork that i have been using to obtain updates. May have been me just being bad. 

I seem to have the issue less severely now, so I don't know if that was the cause of it.
