### ISSUE TITLE
Lots of ammo is not craftable due to bad filters

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#1631]
For example, HEAT SPG-9 grenades have HeavyBar as ingredient, but it is not possible to allow any bars of type because there is no corresponding filter.

**Comment by NoManColonies** [comment]
just add <li>HeavyBar</li> to <filter> in it xml file.

**Comment by Voker57** [comment]
yeah that's what i did

**Comment by masakitenchi** [comment]
Closed as too old
