### ISSUE TITLE
there are online MOD!

### ISSUE THREAD

**Issue by yejudora** [skyarkhangel/Hardcore-SK#1637]
I play with my friends in the original version.So Im think theres nothing better than Hardcore-SK online
[https://github.com/Zetrith/Multiplayer]    Its great one thanks author

**Comment by skyarkhangel** [comment]
Multiplayer support is currently not available in HSK! We are waiting for the author of the mod to improve its compatibility with the main HSK base, especially with Combat Extended. If something changes, we will inform.

Поддержки Мультиплеера на данный момент в HSK нет! Мы ждём, когда автор мода доработает его совместимость с основной базой HSK, особенно с Combat Extended. Если что-то изменится - об этом будет сообщено отдельно.

**Comment by masakitenchi** [comment]
Closed as too old
