### ISSUE TITLE
RPG7 - OP damage

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1639]
Урон от РПГ7 (по крайней мере с термобарическими снарядами) просто чудовищный. Один выстрел разнёс все гранитные амбразуры (у них хп 815, а у РПГ урон базовый написан 150 - а тут после единственного выстрела от них даже камней не осталось) причём даже не прямым попаданием, а взрывной волной - и убил троих людей в полной силовой броне, которые за ними прятались. Это так и должно быть? Просто в прошлой версии такого точно не было.

**Comment by Szara-ManOfHonor** [comment]
I've had this problem as well, the RPG rounds obliterate anything with one shot, easily taking out an entire wall 8+ tiles long when they miss. It seems a bit excessive.

**Comment by zakhad** [comment]
I also want to know if anyone else runs into the same issue i did, in that if they can't be sold to vendors.

**Comment by masakitenchi** [comment]
Closed as too old
