### ISSUE TITLE
Beds need a rebalance

### ISSUE THREAD

**Issue by justarandomusername** [skyarkhangel/Hardcore-SK#164]
Hide beds have better stats (pretty much everything except for beauty) than the basic and simple beds and cost significantly less.

**Comment by zakhad** [comment]
Hide beds are more limited in what they can be made from. But honestly i would prefer if they got nerfed the whole point of getting them is so that you're not sleeping on the ground debuff, I outright skip hay beds because by the time you have research set up / grown hay you have hide beds already :S

**Comment by harchschoolboy** [comment]
I think that amount of leather needed for beds can stay on the same level, but probable we need a possibility to gather hay from the grass on the map, and plant it without any researches. So it will allow to feed tamed animal herbivorous from the start, and construct hay beds.

**Comment by harchschoolboy** [comment]
For example:
![image](https://cloud.githubusercontent.com/assets/3436744/18026295/67522776-6c4a-11e6-91d0-c2c16b6669ac.png)

i created a patch for this - https://github.com/harchschoolboy/Hardcore-SK/tree/WildGrass2Hay
but i didn't find how to create addition order button to collect hay only, so it works through harvest
2 hay for usual grass, 4 hay for tall grass

**Comment by justarandomusername** [comment]
Thats a very nice solution for the hay beds, since I skipped them always too. I just think that Hide Beds are specially powerful because you can choose the leather, so Hare or Hedgehog leather for example will outright be better than anything you can make for pretty much years (even medic beds).

I would suggest to create them using some assorted leathers and turned into a general "Hide Leather" and get fixed stats.

**Comment by skyarkhangel** [comment]
Rebalanced.
