### ISSUE TITLE
Robes and coats overlap cloaks textures.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1640]
Новые текстуры плащей очень классные, но, к сожалению если одевать их вместе с верхней одеждой (такой как робы или пальто, например), то она перекрывает текстуры плаща, что смотрится довольно странно, особенно если смотреть со спины. По сути всё, что нужно сделать, это поменять слои отображения одежды так, чтобы плащи отображались поверх одежды остальной (если такое возможно конечно).

**Comment by Inei** [comment]
Идея перенести плащи в слот для роб была не такой плохо. :) Но, к сожалению, ещё небольшая проблемка осталась - Loadbearing kits со спины тоже просвечивают через плащи, хотя по логике их должны носить вокруг пояса под плащом - с этим можно что-нибудь сделать тоже?

**Comment by masakitenchi** [comment]
Closed as too old
