### ISSUE TITLE
items deteriorate even under roof

### ISSUE THREAD

**Issue by golgepapaz** [skyarkhangel/Hardcore-SK#1641]
Items deteriorate event there is a roof tile above. the behaviour was different at b18. Don't know if it is from the core game or from hardcore_sk
![image](https://user-images.githubusercontent.com/174083/51193201-56946580-18f9-11e9-8783-a40e4f9ad1f3.png)

**Comment by Kiriharas** [comment]
they alse deteriorate if not indoors

**Comment by golgepapaz** [comment]
> 
> 
> they alse deteriorate if not indoors

Well that was not the case before. I clearly remember just building a roof over things prevented them from deteriorating even if the tile is counted as outdoors.

**Comment by SampsaxD** [comment]
It's a change from 1.0, so nothing to do with HCSK

**Comment by golgepapaz** [comment]
> 
> 
> It's a change from 1.0, so nothing to do with HCSK

yeah that explains it .thanks
