### ISSUE TITLE
"C" key is set to both cancel tool and build window

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#1645]
Fix this please, search tab isnt' as frequently used as the bild tool and the first one overrides the hotkey.
Thanks

**Comment by kanade1278** [comment]
Just turn off the 'Dubs Mint Menus' mod, and use 'Recipe icons' mod. this is better

**Comment by LEEROU** [comment]
Thanks! Mint menus really should be disabled by start, it's menus are just so big it's hard to read

**Comment by sidfu** [comment]
mins menus are adjustable. just hit the cog and u can adjust everything from icon size to even window size

**Comment by Wishbringer** [comment]
Set the key to something else in Mods\Dubs Mint Menus\Defs\MainButtons.xml:
<defaultHotKey>?</defaultHotKey>

**Comment by skyarkhangel** [comment]
Removed a hot C key for Mint Menus.

**Comment by masakitenchi** [comment]
Closed as too old
