### ISSUE TITLE
Light and consiousness little issue.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1646]
У меня колонистка есть, у неё одно лёгкое отсутствует - потеряно было в следствие ранения. Из-за этого у неё сознание постоянно слегка ослаблено (видимо из-за нехватки кислорода). Проблема в том, что иногда она есть не совсем здоровую пищу и травится. Так вот, так как свет влияет на сознание, и пока уровень сознания выше 40% - она может двигаться. Но, как только она выходит из палаты в тёмный коридор, тут же падает на землю и снова надо "спасать". Заставить её отдыхать в кровати невозможно - поскольку отравление болезнью не считается, а госпиталь у меня хорошо освещается. То есть как только она оказывается в кровати, тут же уровень сознание из-за света повышается, и она снова приходит в себя - и снова выходит в тёмный коридор где снова падает в отключку - и этот цикл продолжает повторяться пока отравление не заканчивается. 

Проще говоря - проблема в том, что свет сознание повышает. Можно ли бонусы и штраф к сознанию за освещённость переделать в другие бонусы, чтобы такие ситуации не возникали?

**Comment by skyarkhangel** [comment]
Изменил в следующем обновлении.

**Comment by masakitenchi** [comment]
Closed as too old
