### ISSUE TITLE
Вождь в бешенстве.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1648]
Когда ко мне приходят гости и с ними что то случается. Например у гостя случилась ломка и он упал и потерял сознание. Выходит сообщение что вождь в ярости от того что я стал вербовать гостя. Но я этого не делал. Было раньше как то ещё ситуация что на гостя напало животное и убило его. Тоже было сообщение что вождь в ярости от моей вербовки. И один раз я вроде поставил просто улучшить отношение. Но гость решил присоединится к поселению и вождь был в ярости от моей вербовки. Хотя я вроде ставил улучшить отношение. Но насчёт этого последнего случая я не уверен. Может действительно не то выбрал. Хотя вроде нет.

**Comment by Inei** [comment]
Там вождь не от вербовки должен быть в ярости, а от того, что того, кто в гости пришёл ранили. Если вы его успеете спасти - отношение можно будет частично восстановить, или даже улучшить. Возможно баг русской локализации просто.

**Comment by skyarkhangel** [comment]
В последних обновлениях снижен уровень с 8 до 5 для оказания первой помощи и возможно проводить на любых пешках.

**Comment by Andry2017** [comment]
Inei, если с колонистом что то случается то я получаю сообщение что вождь разозлится от моей вербовки и  минус 10 репутации. Может дело просто в том что какой то косяк в русском переводе. Но он есть. И его надо исправить.

skyarkhangel, было бы ещё хорошо что бы сильно раненого гостя или члена дружеской фракции хороший медик мог лечить сразу в том месте где он лежит без медикаментов как и поселенцев. А то сейчас(ну в моей версии) надо обязательно тащить с собой медикаменты, а поселенца хороший медик может вылечить и без них. Шансы гостя выжить были бы выше. Можно было бы так же добавить возможность разрешать гостям пользоваться Регенератором кожи за репутацию. Или вообще добавить в игру возможность продавать и покупать медицинские услуги.

**Comment by Inei** [comment]
Там вроде есть такая опция, в английской версии называется "Patch up" - медик начинает лечить прямо на месте, правда качество перевязки при этом страдает, естественно.

**Comment by Aquaril** [comment]
Andry2017, ты меня не так понял) "А так, поставь в дефолтных настройках медикаментов Нейтральную фракцию на "Уход врача без медикаментов"" - и был ответ на твой вопрос "Как заставить врача лечить нейтралов без медикаментов".

**Comment by masakitenchi** [comment]
Closed as too old
