### ISSUE TITLE
Бесконечно повторяющийся эвент

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1649]
Играл за котов,у них при старте начинается нападение и несколько раненых пешек,так вот при входе в любую локацию караваном начинается тоже самое,то есть нападение и несколько упавших пешек

**Comment by skyarkhangel** [comment]
Ок, скоро будет исправлено.

**Comment by masakitenchi** [comment]
Closed as too old
