### ISSUE TITLE
На горне не работает "Сжечь предметы" (recipe BurnThings)

### ISSUE THREAD

**Issue by siteonfly** [skyarkhangel/Hardcore-SK#1650]
Задача добавляется, но ее не выполняют. Аналогичная задача на костре (recipe BurnThingsCampfire) работает нормально.

**Comment by skyarkhangel** [comment]
ок

**Comment by siteonfly** [comment]
Не помогло, во всяком случае на текущем сейве, на новом не пробовал. Задачу удалил, добавил снова - при клике правой кнопкой меню не появляется. Трупы и фекальный ил сжигают нормально. Скрины для наглядности:
![default](https://user-images.githubusercontent.com/12813448/52054866-dfa0d300-256e-11e9-8748-c3710019ed4a.png)

**Comment by igrovan** [comment]
Та же самая проблема с задачей "Сжечь одежду"

**Comment by masakitenchi** [comment]
Closed as too old
