### ISSUE TITLE
баг с дройдами

### ISSUE THREAD

**Issue by DoctorEpic** [skyarkhangel/Hardcore-SK#1651]
Скачал сборку неделю назад. Смысл бага в следущем:
1) строим стол сборки дройдов
2) заказываем боевого дройда //начинается сбор ресурсов на постройку
3) сразу, пока пешки еще не закинули ресурсы, переставляем сам станок
4) изготовление дройда началось сразу после установки
5) профит! теперь вы можете построить армию дроидов не тратя на их производство ресурсы!

также работает с рабочими дройдами и андройдами 

как радикальная мера - запретить таскать станки, но это не желательно (я люблю перемещать мастерские)

**Comment by Pepelnica1488** [comment]
запретить перемещать что либо из за какого то долбаёба который захотел испортить игру абузом?

**Comment by masakitenchi** [comment]
Closed as too old
