### ISSUE TITLE
На 8-9 году жизни колонии игра иногда стала вылетать.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1652]
Я так и не понял почему. Но подозреваю что при загрузке какого то события, а может и нет. Могу скинуть сохранку после которой такое произошло 2 раза подряд. Только на 3 раз вылет не повторился.

**Comment by skyarkhangel** [comment]
Почисти игру в опциях RuntimeGC.

**Comment by Andry2017** [comment]
Templorum, ну я сообщил что проблема есть. Предложил сохранку скинуть если это будет полезно. Это уведомление сделано с расчётом что мне подскажут что я могу сделать что бы помочь найти и выявить источник этой проблемы. Ну или хотя бы просто дадут рекомендации по её решению.

skyarkhangel, буду знать.

**Comment by masakitenchi** [comment]
Closed as too old
