### ISSUE TITLE
Проблема с ремонтом бота

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1653]
У меня есть сломанный бот носильщик лежащий на складе. Когда я выбираю своего строителя и кликаю правой кнопкой мыши по сломанному боту. То выпадает меню где есть пункт "Починить бота". Но он не работает. То есть при попытке выбрать этот пункт ничего не происходит. Вообще ничего! Даже меню не закрывается как будто щелчок левой кнопки мыши не был совершен вообще. По видимому этому пункту меню не назначено какое либо действие.

**Comment by Zim777** [comment]
Исследуешь технологию ботов, строишь платформу для  этого бота. И только тогда ты сможешь его отремонтировать. Приятной игры

**Comment by Andry2017** [comment]
Я понял в чём была проблема. Я поставил станцию бота в угол. А для ремонта необходимо чето бы ресурсы располагались в строго определённых местах которые были в моём случае заняты стенами. В случае если эти места заняты другими ресурсами так же не получалось произвести ремонт бота. Приходится ставит станцию бота на открытое место где ничего не мешает ремонту и тогда его возможно осуществить.

**Comment by masakitenchi** [comment]
Closed as too old
