### ISSUE TITLE
Проблема с бермудским треугольником на карте!

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1654]
Есть участок земли немного затенённый. Когда на него наводишь курсор мыши в описании пишется "Enemy ship(incoming)" вот только вражеского корабля там никакого нет. Всякий поселенец или бот что туда заходят исчезают навсегда и бесследно. Так же при каждой загрузке игры в этом месте появляется анимация садящегося корабля. Но посадки так и не происходит. Началось это всё недели 2 назад. Я периодически обновляю игру до последней версии продолжая играть в одной и той же колонии.

**Comment by masakitenchi** [comment]
Closed as too old
