### ISSUE TITLE
A bunch of minor issues

### ISSUE THREAD

**Issue by Aquaril** [skyarkhangel/Hardcore-SK#1655]
- Aquaculture Hopper can't be contructed. There is no button in Production/Fishing Tab.
- And you can place Aquaculture basin without research if you not open Fishing tab, just clicking on it.
- Bug with Pot and Honeycomb w. Queen (If Honeycomb was placed in Pot, when Queen die, Pot produces Honey with dramatic speed). Schrödinger's Honey. Pawns take it from Pot, but Pot spawn new one.
- For cooking Lavish and Luxury meals only Prime Meat can be used. As I know, Shelled Mashgon and Blueblade filet could be used instead.
- Holographic Cell doesn't working(Yes, I know that that's chair). - Update: Seems like properties of Pod Chair and Holographic Cell were mixed up. 
- Battery and Fission Battery can be made only from Lead.(I know, that Lead only for simple Battery is fine, but not for Fission one).
- Many pieces of apparel lost their recipes on Tailoring Benches and Smithy.
- File cabinet doesn't working with Hi-tech Research Bench.
- "Brew medical drink" on Antibiotic recipe in Medical Table. Seems like description for Healroot or Mushroom tincture.
- Fridge can accept only Aloe Leaves from Plant Matter tab (Should also be Mint, Herbal medicine (Herbal Medicine and Herbal medicine =_=, maybe you will rename one to Herbal Medicine Kit? or Herbal medicine to Raw Healroot), Neutro Flower Petals and soo...). Also, why we can storage all type of Medicine here? None of them rotting from temperature.
![herbal](https://user-images.githubusercontent.com/13365248/52171377-75a64a80-2775-11e9-9027-cef920f8eae4.png)
- Chemical Protection Set not working against Radiation(Yep, not working at all. Only androids(race) and terminators can survive it, even without suit).
- Shooting target seems to be broken, pawns can't reload their guns, even if they have ammo.
- Holosuite not working too.
- Beta Poly working speed is 80%, (Should be 180%).
- Pawns can't study Stargate structure(Not research, study like terraformer).
- Antibiotics and tincture have nutrition 0.01. I had 3 Polar Bears with Antibiotics overdose on my base constatly.
- Caravans with Drones only constantly filling with foraged food.
- Hauling and Cleaner Bots (disabled) can't be disassembled on Electric  Machining table. (Bill ask Bot's corpse).
- Wild predators not hunting Boomalopes (Maybe its normal).
- ~~Hospitality not giving goodwill.~~ Giving, but not writing about it.
- Coolers and vents can't be placed on Panel Reinforced Wall. If you try to do that, they deconstruct wall and do this =_=.
![panel](https://user-images.githubusercontent.com/13365248/52172205-2ddaef80-2784-11e9-9721-273a7bc00ec1.png)

- Needed way to upgrade existing androids with unlockable androids upgrade. Maybe adding unlockable operation on Android pawns.
- And "Android Runner" scenario... Steel android printer is a bad joke? "... but you start with the means  to produce more."... For 1 Android you need 75 Biomatter, 25 Robot parts and Synthetic fibers... And needed Robotics Research at the end of Research tree.... 4 Research projects away from "Android Printer" Research.

Development branch. Modpack version: Jan 31, 2019 .

**Comment by masakitenchi** [comment]
Closed as too old
