### ISSUE TITLE
Tanned leather is not leather

### ISSUE THREAD

**Issue by harchschoolboy** [skyarkhangel/Hardcore-SK#166]
Такой момент возник.
Tanned leather принадлежит к категории BTextile
Из-за чего из нее нельзя крафтить все то, что крафтится только из кожи.
Можно присвоить дополнительную категорию - Leathers
```
	<thingCategories>
			<li>BTextiles</li>
			<li>Leathers</li>
		</thingCategories>
```
Но возникает другая проблема, они будут делать Tanned Leather из Tanned Leather, если не отключить Tanned Leather в ингридиентах таски, по кругу.
Есть ли возможность настраивать список из разрешенных\запрещенных позиций?
![image](https://cloud.githubusercontent.com/assets/3436744/18019382/79ead024-6be4-11e6-8675-0d9dc3bc182d.png)
Если да, то имеет смысл присвоить этой дубленой коже категорию кожи, выключить ее из ингридиентов, и крафтить на здоровье, ибо в данный  момент выглядит нелепо, что можно скрафтить из кожи футболку, но нельзя ботинки.

Алсо, было бы неплохо разрешить миксовать разную кожу для получения дубленой, с едой такое прокатывает на гриле, когда пару разных мяс плюс рыба дают жареное мясо.

Алсо, в процессе дубления кожа не уменьшается в объеме аж вдвое) поэтому 20 из 40 это ну как аще нечестно

**Comment by jnkyacc** [comment]
1) ласт апдейт она в кожной категории и больше никаких маек
2) согласен насчет таннед из таннед
3) ласт апдейт можно миксовать
4) считайте платой за микс :)
