### ISSUE TITLE
Бесконечный мед

### ISSUE THREAD

**Issue by Nyaster** [skyarkhangel/Hardcore-SK#1660]
Стоит поставить пчелиную соту с маткой в сундук(Лично я делал из досок), то по истечению времени(Когда матка должна умереть) сота начнет генерировать мед. Где то 1 в секунду.

**Comment by Azumgi** [comment]
Год назад было то же самое, если сота была в инвентаре у павна: http://hardcore-sk.ru/threads/a17-bagi-i-oshibki-testovoj-versii-s-github.527/page-22#post-17952
Скорее всего тоже не пофикшено ещё.

**Comment by masakitenchi** [comment]
Closed as too old
