### ISSUE TITLE
Нерабочая пешка.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1666]
В какой-то момент, на "ровном месте", одна из пешек перестала работать. Просто "стоит". Спать, жрать, в туалет бегает сам. Принудительно работы выполняет. В свободном режиме просто стоит. Не перегружен, шмотки не мешают - я его полностью раздевал. Отрицательных перков нет. Лог: https://git.io/fhd5K . Поэкспериментировал. Баг как-то связан с областями. Если выбираю в назначениях этой пешки зону Уборка - начинает в её пределах работать как положено (он животновод/фермер). Перевожу в режим без ограничений - всё, стоит. Создал отдельную зону, размером с карту - и на ней "стоит".
P.S. Похоже я в первый раз не там запрос сделал, сорри. Тут весьма непривычная структура "форума", и англоязычная. :(

**Comment by SetAriman** [comment]
Добавлю. Поставил новое обновление, поэкспериментировал. Это касается и остальных пешек, если приоритет у них на фермерство и рубку деревьев. Т.е. если самое приоритетное фермерство - пешка стоит на месте и не работает. Только принудительно. Если приоритет сместить на другие виды работ, пешка без проблем начнёт их делать. Баг возник на "ровном месте."

**Comment by skyarkhangel** [comment]
Было еще у кого-то подобное? Не могу такое воспроизвести. Распиши как воспроизвести эту ошибку.  Стоят ли какие-то дополнительные модификации?

**Comment by SetAriman** [comment]
Сохранение http://www.mediafire.com/file/xg1ors98l3wcz5e/1.rws/file

Я проверил на другой пешке, как и писал, то же самое. Если увеличиваю приоритет на фермерство и рубку деревьев выше всех остальных, пешка один раз начинает это делать, а потом останавливается и "стоит". Если сменить пешке назначенную зону с "неограниченно" на зону, предназначенную для уборки - пешка будет заниматься фермерством, как обычно. Но если выставить другую зону, помимо уборки, пешка опять "стоит". Как воспроизвести - хз, Баг вылез на ровном месте. (У меня вечно вылазят редкие баги. :( ) Модификации только оригинальные, плюс включен мод на изгороди из отключенных.

**Comment by SetAriman** [comment]
Снова столкнулся с этим багом. Дважды. (Или с похожим.) Но тут оказалось проще и интереснее. Один раз пешка застыла на месте - как и в первом посте. Но начала работать, когда я дал доступ к переноске предмета, находившегося за пределами разрешённой зоны. Она его перенесла и всё пошло нормально. Хотя эта работа и не была у неё в приоритете. Вторая пешка так же отказалась двигаться. Ей, как оказалось, приспичило что-то крафтить на станке, который я отключил несколько дней назад. Скрафтила и дальше работала без проблем.

**Comment by masakitenchi** [comment]
Closed as too old
