### ISSUE TITLE
Three simple problems

### ISSUE THREAD

**Issue by liu11900** [skyarkhangel/Hardcore-SK#1669]
1.   The base damage of SPG-9 grenade (Frag) should be 170.
In“SPG9.xml”, the base damage of SPG-9 grenade (Frag) is 70, while for SPG-9 grenade (HEAT), the base damage is 170.  I think they both should be 170.
2.  The natural armor of Droids and Mutants seems not work.
 A Mutant has an armor-blunt of 0.24, but it still can be hurt by human fists. My workerbot  has an armor-sharp of 0.3, but he was knocked down by a group of man-hunting Mosquito. ：(
The same problem happened in Android‘s upgrade. All the armor upgrades did not apply any practical effect.
3.  Melee Shocker and Electric Baton are too powerful.  
The state of Electroshocked will reduce the victim's mobility by 60 percent on each hit and no one can escape from it.  That means, if you want to knock down a Centipede, just grab your Melee Shocker and hit it twice. Lancer? Twice. Terminator ? Twice ! The only way to protect yourself is to wear a power armor, it's sheild works.

**Comment by masakitenchi** [comment]
Closed as too old
