### ISSUE TITLE
Кирилица в названии файлов

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1670]
Конкретно:
сomfortablechair_east
сomfortablechair_eastm
сomfortablechair_north
сomfortablechair_northm
сomfortablechair_south
сomfortablechair_southm
AdvСhest
AdvСhest_m
AdvСhest_full
AdvСhest_full_m
СaravanPlace
coffeeМaker
coffeeМaker_m

**Comment by skyarkhangel** [comment]
Благодарю!
