### ISSUE TITLE
Дикие тормоза при сейсмической активности

### ISSUE THREAD

**Issue by AnFox** [skyarkhangel/Hardcore-SK#1671]
При сейсмической активности игра превратилась в пошаговую стратегию, машина совсем не слабая.

**Comment by Andry2017** [comment]
У меня один раз такое тоже было. Сохранился загрузился и прошло.

**Comment by skyarkhangel** [comment]
Обновление какое? Исправляли подобное, но возможно проблема осталась?

**Comment by Andry2017** [comment]
У меня по моему такое произошло когда наложились землетрясения. Шло одно за другим. Началось землетрясение и в это время упал метеорит и спровоцировал ещё одно. Возможно в этот момент случилось ещё какое то событие и тормоза вызвало оно. Но в любом случае у  меня за 12 лет игры такое было только один раз.

**Comment by skybsky** [comment]
Возможно ещё что-то фоном было. На свежей версии лагов у меня не было.

**Comment by masakitenchi** [comment]
Closed as too old
