### ISSUE TITLE
Жарка мяса.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1672]
Не раз замечал, что пешка, у которой полно работы, вдруг начинает жарить мясо. При том, что у неё кулинария в приоритетах вообще отключена. Два раза начинал игру и оба раза одна и та же пешка этим занимается.

**Comment by Zim777** [comment]
Работа за костром, к примеру, не относится к кулинарии, это в категории ремесла. Вы можете указать в настройках жарки мяса ограничение на навык кулинарии для жарящего мясо. к примеру, от 3 и выше.

**Comment by SetAriman** [comment]
Спасибо. (Лучше бы сделали два типа костров: для готовки и для ремёсел - это выглядело бы логичнее.)
