### ISSUE TITLE
Проблема с тренажерами.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1673]
У тренажера по стрельбе возникает проблема с перезарядкой оружия. Иногда пешки перезаряжаются нормально, а иногда у них начинается бесконечная перезарядка. Они по кругу циклически начинают перезаряжаться и так без остановки долгое время. Если самому заставить его перезарядится то проблема проходит и он продолжает выполнять упражнение. Так же ни разу не видел что бы кто то подходил к голограмме для тренировки по улучшению навыка общения.

**Comment by masakitenchi** [comment]
Closed as too old
