### ISSUE TITLE
Караваны сбегают от меня при холодной температуре даже если им выделено тёплое место.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#1675]
У меня ядерная зима после взрыва бомбы. Караваны заходя ко мне либо гибнут от радиации(но это я понимаю) либо так и немного не дойдя до поселения разворачиваются и убегают потому что слишком холодно. И это несмотря на то что я место для приёма чужих корованов сделал в тёплом помещении. Было бы хорошо что бы караваны знали об этом и не сбегали на пол пути.

**Comment by skyarkhangel** [comment]
готово.

**Comment by masakitenchi** [comment]
Closed as too old
