### ISSUE TITLE
Чёткий психолог.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1677]
Странный случай. Пешка впала в апатию. Но так как у неё дипломатия в высшем приоритете, стала успокаивать сама себя. (В итоге расстроилась и пошла страдать дальше.)

**Comment by skyarkhangel** [comment]
В B18 мы исправляли самоуспокоение. В 1.0 автор это снова оставил, можем убрать.

**Comment by SetAriman** [comment]
Сложный вопрос. Но больше выглядит, как баг. Если у человека истерика, он вряд ли себя успокоит - душевное состояние абсолютно неподходящее. Да и у игроков будет вызывать вопросы, которые привыкли, что пешек успокаивают другие пешки.

**Comment by masakitenchi** [comment]
Closed as too old
