### ISSUE TITLE
[dev] Вопрос. По опыту пешек. Баг или фича баланса?

### ISSUE THREAD

**Issue by shikulja** [skyarkhangel/Hardcore-SK#1679]
Исследования уже почти полностью изучил, кроме корабля.
Застроился улучшенными ветряками, солнечными панелями.. андроиды и боты уже бегают.
Но вот проблема, выше 15-16 уровня строительства не могу поднять (чтобы коллайдеры, тесла и пр. строить), из 16 колонистов,  ТОЛЬКО у одного строительство назначено, и он не может даже один опыт поднять.

Чтобы поднять надо застраивать высоко-уровневые строения, типа аэс, центрифуг и пр. хай-тек, но даже 16 человек не хватает, чтобы так быстро готовить ресурсы для строительства.

Подскажите что за беда, и как с ней справится.
Проблема даже не столько в повышении опыта, сколько в том - что они на ходу все забывают.

**Comment by skyarkhangel** [comment]
Кто-нибудь сталкивался с этим?

**Comment by SetAriman** [comment]
Я пока нет. Пешка качается и вроде уже перешла за 16. Но я медленно играю. А вообще в будущем буду ставить мод, который позволяет убрать уменьшение опыта (Талант не пропьёшь!). Мне не нравится игровая идея - как сейчас - что опыт медленно падает.
P.S. В горах и холмах хорошо стройку качать, на сглаживании стен и полов. Правда в ХСК с этим похоже что-то намудрили. Я играл в Минимализм, и после сглаживания стены были такие же, как и сделанные. А тут получается визуально мешанина. Зачастую часть стен сглаженые, часть построенные и выглядит это как цыганское одеяло.
P.P.S. Если человек играет на равнинах, строят пара пешек, без огонька и он быстро развивается, вполне возможно, что упрётся в искусственный лимит. Сейчас смотрю серию свежих видосов по ХСК, ютуберу приходится строить и ломать столы и стены, чтобы качнуться.

**Comment by shikulja** [comment]
Одна качаеться, медленно, но если следить то держу уровень. Но не успевает заниматься строительством, разбором лома. Если вторую назначить тоже, то опыта тогда вообще не хватает.

**Comment by SetAriman** [comment]
Кстати: будет "весело", если эту пешку убьют. Или сама помрёт, благодаря местной медицине. Всё, песец колонии, будет три года разбирать и мостить полы. Если не помрёт.
P.S. Как по мне, я поставил бы максимальные требования к строительству не выше 12. Остальное чисто бонус скорости и качества строительства.

**Comment by shikulja** [comment]
> Кстати: будет "весело", если эту пешку убьют. Или сама помрёт, благодаря местной медицине. Всё, песец колонии, будет три года разбирать и мостить полы. Если не помрёт.
> P.S. Как по мне, я поставил бы максимальные требования к строительству не выше 12. Остальное чисто бонус скорости и качества строительства.

отчасти согласен, медицину можно на верстаках раскачивать, но топовые биосинтетические органы как правило требуют, и уровень, и навык ремесла а не медицины, из-за этого надо держать на всякий случай и предыдущие верстаки для прокачки, а чтобы прокачивать надо изготавливать с большим запасом и затратами ресурсов.. в основном на продажу.. но естественно для колонии столько не нужно, тем более все можно андроидами заменять.

**Comment by shikulja** [comment]
Очередной репорт разрабам.
Медицина.
качал на передовых и прочих медикаментах за станком. единственная пешка назначеная
максимум 17.5lvl с парой бионических операций набирает 18lvl чего достаточно для кибернетических имплантов. Но такой подход совсем не комильфо, тем более ей надо нонстоп за станком стоять. В результате посмотрел на статистику опыта после операции 21к опыта из 4к суточных. оверхед дичайший.. но толку 0, еще и забывает  на ходу опыт.
Строительство. 
максимум чего я смог добиться 18,2lvl но нужен 19 т.к. необходим конвертер материи, для дальнейшего развития. Как не странно то адронный коллайдер и прочий хайтек требует 18lvl строительства.
то есть чтобы построить надо нонстоп набирать опыт, чтобы построить необходимое оборудование, причем пешка почти сразу сбросит опыт, поэтому если нужно будет перестроиться, нужно будет заново набирать опыт.
Игру дропаю т.к. превращается тупо в "дрочево"
