### ISSUE TITLE
`Human` string  is hardcoded in Infusion.StatPart_InfusionWorker

### ISSUE THREAD

**Issue by evgeny-k** [skyarkhangel/Hardcore-SK#168]
чтобы заработали Infusion суффиксы/префиксы надо убрать проверку на "Human" в `Infusion.StatPart_InfusionWorker`.
как вариант, перенести мой фикс из https://github.com/urty5656/RimWorld-Infusion/pull/2/commits/1e5657bf7b0682b55224b8c874485ad49acf76ec в сорцы `Core_SK.dll`

**Comment by skyarkhangel** [comment]
Интересно, смотрю

**Comment by skyarkhangel** [comment]
Added to SK. Thank you :)
