### ISSUE TITLE
Проблема с Кирином.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1680]
Второй раз сталкиваюсь. Ставишь пешке охоту на Кирина, и если она подходит близко, игра начинает жутко тормозить, а потом и вообще вылетает. Вот лог. https://git.io/fhhMh

Кстати. Раньше Кирин если впадал в ярость, когда его бьёшь, то он мстил (и мстя его была страшна). В прошлый раз охотился на него, Кирин впал в ярость и ... убежал с карты. Как-то нелогично.

P.S. Сейчас обратил внимание. Мало того, что проблема при охоте. На этот раз, когда дал команду охотиться на Кирина, упавшего без сознания на базе, - другая пешка сама по себе одновременно отправилась его стабилизировать. Прибежала и стояла рядом.

**Comment by masakitenchi** [comment]
Closed as too old
