### ISSUE TITLE
Проблемы с отображением плаща. 

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1683]
Не раз замечал на разных пешках - плохо отображается плащ. Сейчас специально наблюдал за двумя. На одной плащ на голое тело, на другой плащ поверх футболки. В результате первая пешка отображается то голой, то в плаще. Вторая - то в футболке, то в плаще. В других видах одежды та же картина.

**Comment by masakitenchi** [comment]
Closed as too old
