### ISSUE TITLE
Можно понерфить малый шкаф с инструментами?

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1684]
Мои пешки очень переживают. Уже более трёх лет колонии, даже научились делать патроны, но нет простого шкафчика для инструментов. Тупо простого маленького шкафчика. Он, зараза, требует резину - как будто там не простой шкафчик, а кресло с вибромассажем и флюгегехайменом. :(

**Comment by masakitenchi** [comment]
Closed as too old
