### ISSUE TITLE
О крафте простых вещей.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1685]
Вопрос: можно ли убрать из крафта простых вещей компоненты? Та же набедренная повязка требует аж три штуки, даже больше, чем туника. Хотя и то и то всего-навсего куски ткани, по сути. Хорошо хоть брюки не требуют, хоть шить их по идее куда сложнее, чем повязку. Может стоит убрать компоненты из рецептов простых вещей? Это же не бронежилет или что-то сложное. 
P.S. Кстати: набедренная повязка почему-то не делается из ткани, только из шкур.

**Comment by masakitenchi** [comment]
Closed as too old
