### ISSUE TITLE
Неправильный расчёт протезов.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1687]
У моего кошака нет почки и отстрелили крюк, который я поставил вместо отдавленной лапы. Решил поставить новый крюк. В результате показатель его работы: до операции - 87%, после операции - 62%. Т.е. с протезом он стал работать куда хуже, чем вообще без него, с голой культёй.

**Comment by SetAriman** [comment]
То же самое и с повязкой на ухо. После установки, взамен отсутствующего уха, слух с 75% упал до 41%. При этом в факторах, влияющих на слух, кохлеарный имплант указан дважды.

**Comment by masakitenchi** [comment]
Closed as too old
