### ISSUE TITLE
Камнерезный станок не учитывает кирпичи

### ISSUE THREAD

**Issue by Igoryahaha** [skyarkhangel/Hardcore-SK#1691]
Нет отдельного рецепта для производства кирпичей(при этом они делаются при производстве "любых блоков" и не учитываются в общем количестве блоков, т.е. если сделать установку -  "Сделать до Х любых блоков", то производство будет бесконечно, пока не появятся другие блоки, кроме кирпичей).

**Comment by masakitenchi** [comment]
Closed as too old
