### ISSUE TITLE
Update Hospitality  1.0.13 - 10.03.2019

### ISSUE THREAD

**Issue by Sonsalt** [skyarkhangel/Hardcore-SK#1692]
1.0.13 - 10.03.2019
- New: Highlight for "Make Default" to clarify what is set
- New: Added "..." button in guests tab that opens the personal guest tab
- Fix: "Guests drop food" bug
- Fix: Shopping area saying "unrestricted" instead of "no shopping"
- Fix: Target version
- Tweak: "Area of accommodation" renamed to "Allowed area"
- New: Included Maeyanie's code for configuring selling price factor (create a file "Hospitality.cfg" in RimWorld's config folder, add the line PriceFactor=0.85 and tweak is as desired)

https://ludeon.com/forums/index.php?topic=11444.0

**Comment by masakitenchi** [comment]
Closed as too old
