### ISSUE TITLE
Щит с двуручным оружием

### ISSUE THREAD

**Issue by AnFox** [skyarkhangel/Hardcore-SK#1693]
Пешки постоянно надевают любой имеющийся щит, даже если у них двуручное оружие, после чего, естественно, не могут стрелять.

**Comment by skybsky** [comment]
Кстати, как вариант можешь пока им в настройках сделать кастомный Outfit без щитов

**Comment by Aldentr** [comment]
Та же проблема, у каждого колониста кастомный аутфит без щитов, все равно рвутся их поднимать.

**Comment by masakitenchi** [comment]
Closed as too old
