### ISSUE TITLE
Colonists pick a bunch of fruits and eat only 1 and 1 and 1... repeating

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1695]
And when I see his Needs, **he isn't hungry at all.** But he is eating a fruit and eating a fruit and eating...
Is it a bug? Then which mod makes this bug?

**Comment by zachary-foster** [comment]
He is eating for joy. Can make it impossible to tame with fruit or any other joy food. Its a bug in my opinion. Keep them happy to avoid it.

**Comment by masakitenchi** [comment]
Closed as too old
