### ISSUE TITLE
Poison arrows have no effect

### ISSUE THREAD

**Issue by Leslac** [skyarkhangel/Hardcore-SK#1697]
On the latest commit poisoned arrows have no effect on any animals or enemies. The arrows cause no damage and no poisoning effect is accrued.

 Animals still behave like they're being attacked and flee or go aggressive on your pawns.

 I haven't tried it with other ammo types.

**Comment by Leslac** [comment]
Note that other weapons word as normal. Uzis, melee weapons and ordinary arrow types. Just the poison arrows have no effect.

**Comment by masakitenchi** [comment]
Closed as too old
