### ISSUE TITLE
Xenon Ion Turbine not working

### ISSUE THREAD

**Issue by Masquerine** [skyarkhangel/Hardcore-SK#17]
The Xenon Ion Turbine doesn't seem to do anything. It gets placed on a steam geyser, the display box says that the Xenon Ion Turbine is working but it does not produce power.

I'm not sure how to fix it.
![xenonionturbine](https://cloud.githubusercontent.com/assets/16396520/12363191/70b576da-bb95-11e5-8570-9e3c3590ccd9.png)

**Comment by skyarkhangel** [comment]
try to use it in room with temp  >100 and you'll be surprised.
Ohh please, correct the description :)

**Comment by Masquerine** [comment]
I see, haha. Yeah the original description was from the original mod, but I see now that it doesn't match with your modifications. Updating description.
![xenon](https://cloud.githubusercontent.com/assets/16396520/12370495/fd47d340-bbe0-11e5-9b1d-e818434175d1.png)
