### ISSUE TITLE
Trader arrived during lord of darkness event

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#170]
A trader visited in the middle of the darkness event, resulting in a lot of free stuff.

**Comment by zakhad** [comment]
Feature not a bug lol, I had a aks 74u donated within the first 5 minutes T_T I'd be happy but the colony wealth goes higher than im able to deal with higher scaling harder threats that early on. Atm I have a Massive hive spawned on the edge of one of my maps whenever i get attacked on that side they just end up as hive food lol.

**Comment by skyarkhangel** [comment]
at a wrong time... it was a big mistake xD

**Comment by skyarkhangel** [comment]
So its random event.
