### ISSUE TITLE
2 things about electronics table

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1701]
![2019-03-20](https://user-images.githubusercontent.com/11158226/54659490-5b51e180-4b15-11e9-9ad0-ff97aacc99ca.png)
1. Why are there 2 mineral sonar moduels?
2. Being able to make **psychic** devices only needs Electronics Basic research seems a bit weird. Isn't it an archotech device? And isn't it a very powerful devices in game?

**Comment by masakitenchi** [comment]
Closed as too old
