### ISSUE TITLE
Still I think these 2 things are irrational.

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1702]
1. Why doesn't Large Tool Cabinet have the tools that Small Tools Cabinet have?
2. And why is it not able to do with Electric Tailoring Bench that is able to do with non-electric Tailir's Bench? (equivalent to Weapon Crafting Bench too.)
Electric Machining table is able to do the ALL things that Hand Machining table can do.
Why Electric Tailor's Bench and Advanced Weapon Crafting Table should be different?

**Comment by masakitenchi** [comment]
Closed as too old
