### ISSUE TITLE
Баг охоты с арбалетом

### ISSUE THREAD

**Issue by Aldentr** [skyarkhangel/Hardcore-SK#1704]
Версия пака от 20.03.2019, дополнительно включены моды из пака (A Dog said...; Fences And Floors; Haul to Stack; Psychology; SeedsPlease) и из мастерской Steam (Roads of the Rim; Infused; FrameRateControl; Not Mine- Unclaim Structures).
Пешке назначен арбалет и небольшое количество арбалетных болтов. Охота происходит следующим образом: пешка подбегает к жертве, стреляет, мажет, бежит на склад за арбалетным болтом, возвращается к жертве и все по-новой (возможно, на склад бежит после перезарядки, если понадобится - уточню).

**Comment by masakitenchi** [comment]
Closed as too old
