### ISSUE TITLE
What about making tables to be able to set owners?

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1705]
![2019-03-22 (2)](https://user-images.githubusercontent.com/11158226/54808173-c68ce680-4cc2-11e9-9bed-2db28f4c4752.png)
When I make tables in my pawn's private bedroom, often the non-owners of this room use its table. I think making tables to be able to set owners will go well.

**Comment by Leslac** [comment]
Or just give us the option to "attach to bed".

**Comment by pectus-solentis** [comment]
@Leslac Just like bathroom gadgets?

**Comment by Leslac** [comment]
Yeah, I think it's the water trough or something like that.

 But I've no idea what's easier to program.

**Comment by zakhad** [comment]
Could just use the locks mod and restrict who can access the room via locking the door.

**Comment by pectus-solentis** [comment]
> Could just use the locks mod and restrict who can access the room via locking the door.

@zakhad I tried that, but if I use Locks the other pawns couldn't get his room when even emergency. That was not I wanted.

**Comment by zakhad** [comment]
Just unlock the door?

**Comment by pectus-solentis** [comment]
@zakhad I did and rescued that pawn, but I think just that situation was absurd.

**Comment by masakitenchi** [comment]
Closed as too old
