### ISSUE TITLE
Texture of washing machine when it is seen away is strange.

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1706]
![2019-03-23 (6)](https://user-images.githubusercontent.com/11158226/54865056-ccf28f80-4da2-11e9-8052-e762cc08b5e9.png)
![2019-03-23 (10)](https://user-images.githubusercontent.com/11158226/54867139-4187f700-4dc0-11e9-8ede-04d9e1ca79dc.png)

**Comment by masakitenchi** [comment]
Closed as too old
