### ISSUE TITLE
I think that making components with Hand Assembling Workbench and Electric Assembling Workbench has the same recipe is a bug.

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1707]
Isn't EAW a faster version of HAW?

When I saw xmls HAW is using **the same recipe** as EAW when making components.

> <recipes>
>     <li>Make_ComponentIndustrial</li>
>     <li>MakeWires_Hand</li>
>     <li>MakeSimpleMechanism_Hand</li>
>     <li>MakeAdvMechanism_Hand</li>
> </recipes>

It is the code of HAW
and

>  <recipes>
>     <li>Make_ComponentIndustrial</li>
>     <li>Make_ComponentSpacer</li>
>     <li>MakeWires_Electric</li>
>     <li>MakeSimpleMechanism_Electric</li>
>     <li>MakeAdvMechanism_Electric</li>
> </recipes>

It is the code of EAW.

**Comment by masakitenchi** [comment]
Closed as too old
