### ISSUE TITLE
Enemies' equipped items disappear

### ISSUE THREAD

**Issue by Leslac** [skyarkhangel/Hardcore-SK#1712]
An issue I've seen since having used the beta of this mod, is disappearing items.

 Raiders come equipped with a plethora of stuff, weapons and apparel, but when you down them and strip them, a lot of the stuff doesn't appear on the ground. It just disappears.
 It also seems to be happening with equipped weapons that won't be dropped on the ground next to the downed raider.

 There's no rule as to what stuff won't appear, it seems to be random (working as intended?)

 I'm pretty sure this can be repeated easily. I've seen it happen for the past month, so I don't know what version the problem could originate from.

**Comment by zakhad** [comment]
It's on the FAQ section of the hardcoreSK discord.

"Due to the recent change sky added there is now chance for loot failure you can adjust this amount in the RimWorld\mods\Core_SK\Defs\Config.xml"

if you want to remove the chance of loot fail then change all the values to 0 

        
        
        <ChanceToInstantDestroyAmmo>0.2</ChanceToInstantDestroyAmmo>
        
        <ChanceToInstantDestroyEnemyItem>0.05</ChanceToInstantDestroyEnemyItem>
        
        <ChanceToDamageEnemyItem>0.25</ChanceToDamageEnemyItem>
        
        <MinAmountDeterioration>10</MinAmountDeterioration>
        
        <MaxAmountDeterioration>50</MaxAmountDeterioration>

**Comment by Leslac** [comment]
Thanks, that's fine - I was just wondering whether it was a bug or wad.

**Comment by masakitenchi** [comment]
Closed as too old
