### ISSUE TITLE
Plant is called heal plant, product is called herbal medicine, crafted product also herbal medicine...

### ISSUE THREAD

**Issue by Leslac** [skyarkhangel/Hardcore-SK#1715]
Very minor issue, but one that underlines the importance of names.

 There's a plant called heal plant (or something along those lines) - if you harvest it you get herbal medicine and you can use this as a 30% efficiency medicine. So far so good...

 But there's also a crafted product called Herbal medicine of 60% efficiency.

 Maybe change the name of the harvested product? Healroot f.ex. - it took me quite a while before I discovered there was a difference between the two, because that's the magic of names :)

 Thanks for an awesome mod!

**Comment by pectus-solentis** [comment]
Original name of that plant was Healroot. I think that the harvested product's name should be changed to Healroot too.

**Comment by Leslac** [comment]
Yeah, that's the name exactly :)

**Comment by masakitenchi** [comment]
Closed as too old
