### ISSUE TITLE
Why Deep Space Mining Ships don't sell rubbles?

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1717]
When thinking Bulk Resource Trader sell rubble so much amounts, I think Deep Space Mining ship not  selling Rubbles and selling sands so few is a bug.
I just readed TraderKind folder's xmls but I got no idea how to fix its xml.

**Comment by pectus-solentis** [comment]
https://github.com/skyarkhangel/Hardcore-SK/pull/1703/commits/8e472bc87d10cd3cbcdeb0d80a34e0b28196aad3
solved.

**Comment by masakitenchi** [comment]
Closed as too old
