### ISSUE TITLE
Why I "brew Medical Drinks" to make Antibiotics?

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1719]
It seems that "brew Medical Drinks" is an old description that doesn't make sense now.

Now I "brew Medical Drinks" to make Antibiotics, but its ingredients still need Hops. It seems irrational that not Medical Drinks but Antibiotics need Hops.
How will it be fixed?

============================================================

As I wrote here at 11 Feb 2018 and "brew Medical Drinks" changed to "make Antibiotics" then, but now that is reverted to "brew Medical Drinks". WHY?

**Comment by shikulja** [comment]
> It seems that "brew Medical Drinks" is an old description that doesn't make sense now.
> 
> Now I "brew Medical Drinks" to make Antibiotics, but its ingredients still need Hops. It seems irrational that not Medical Drinks but Antibiotics need Hops.
> How will it be fixed?
> 
> ============================================================
> 
> As I wrote here at 11 Feb 2018 and "brew Medical Drinks" changed to "make Antibiotics" then, but now that is reverted to "brew Medical Drinks". WHY?

I think this is fixed in the dev version.

**Comment by masakitenchi** [comment]
Closed as too old
