### ISSUE TITLE
And Ibuprofen is Painstopper. Right?

### ISSUE THREAD

**Issue by pectus-solentis** [skyarkhangel/Hardcore-SK#1720]
But when I make 1 then recipe's name is "Making Painstopper", and when I make 4 then recipe's name is "Making 4 Ibuprofen". I think it is a kind of typo.

**Comment by Kurrar** [comment]
the same situation is with antibiotics "Making Medical drink" produces "Antibiotics"

**Comment by masakitenchi** [comment]
Closed as too old
