### ISSUE TITLE
Рандомные краши, вылеты, краш при попытке зайти в эквип пешки

### ISSUE THREAD

**Issue by Tsuned-MX** [skyarkhangel/Hardcore-SK#1723]
Debian 9

[rim.log](https://github.com/skyarkhangel/Hardcore-SK/files/3050113/rim.log)
[Player.log](https://github.com/skyarkhangel/Hardcore-SK/files/3050123/Player.log)

**Comment by Tsuned-MX** [comment]
Если играете на Linux то отключите Rimthemeslite

**Comment by Tsuned-MX** [comment]
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.0.2150 rev802</version>
  <activeMods>
    <li>Core</li>
 #mod from steam workshop   <li>1668983184</li>
    <li>HugsLib</li>
    <li>RIMMSLoadUp</li>
    <li>AlienRace</li>
    <li>CombatExtended</li>
    <li>Core_SK</li>
    <li>EdBPrepareCarefully</li>
    <li>Architect Icons</li>
    <li>FacialStuff_SK</li>
    <li>FacialStuff_DianneDefaults</li>
    <li>AlienFaces</li>
    <li>Androids</li>
    <li>Androids_FacialStuffPatch</li>
    <li>Skynet_SK</li>
    <li>Bubbles</li>
    <li>MoreTraitSlots</li>
    <li>AreaUnlocker</li>
    <li>AllowTool</li>
    <li>CameraPlus</li>
    <li>CleaningArea</li>
    <li>Miscellaneous_Core</li>
    <li>Miscellaneous_Robots</li>
    <li>Miscellaneous_TrainingFacility</li>
    <li>Miscellaneous_BeeAndHoney</li>
    <li>ExpandedRoofing</li>
    <li>MyLittlePlanet</li>
    <li>Dubs Bad Hygiene</li>
    <li>HolyWasher</li>
    <li>RT_Fuse</li>
    <li>RT_SolarFlareShield</li>
    <li>SetUpCamp</li>
    <li>Real Ruins</li>
    <li>SnapOut</li>
    <li>PickUpAndHaul</li>
    <li>HuntForMe</li>
    <li>CrazyCatLady</li>
    <li>TechAdvancing</li>
    <li>Hospitality</li>
    <li>TraderDismissal</li>
    <li>Locks</li>
    <li>Statue of Colonist</li>
    <li>MassGraves</li>
    <li>MorePlanning</li>
    <li>BetterMiniMap</li>
    <li>Arachnophobia_SK</li>
    <li>NPS_SK</li>
    <li>Minerals</li>
    <li>RealisticPlanets_SK</li>
    <li>SeasonalWeather_SK</li>
    <li>Darkness_SK</li>
    <li>DarkestNight_SK</li>
    <li>ZiTools</li>
    <li>ZiTools BetterMiniMap Addon</li>
    <li>Mod Medicine Patch</li>
    <li>ImprovedWorkbenches</li>
    <li>SaveStorageSettings</li>
    <li>kNumbers</li>
    <li>RelationsTab</li>
    <li>ColonyLeadership_SK</li>
    <li>Religion</li>
    <li>WorkTab</li>
    <li>ColonistBarKF</li>
    <li>Sidearms</li>
    <li>Recipe icons</li>
    <li>MintMenus</li>
    <li>MoreInfoBox</li>
    <li>DaysMatter</li>
    <li>RimworldSearchAgency</li>
    <li>RSA_HSKCompPatch</li>
    <li>RuntimeGC</li>
    <li>ResearchTree</li>
    <li>HelpTab</li>
    <li>TGC_Patches</li>
  </activeMods>
</ModsConfigData>

**Comment by Zim777** [comment]
Вам же сказали - на Linux отключайте Rimthemes
А у вас при запуске включено 1668983184 (https://steamcommunity.com/sharedfiles/filedetails/?id=1668983184) RimThemes.
