### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by lordmatiz** [skyarkhangel/Hardcore-SK#1727]
Regarding lastest (Apr 8, 2019 development branch) modpack.

1. Harvested healroot plant is named Herbal medicine (tier 2) - which is almost the same as Herbal Medicine (tier 5). The only difference is 'm' and 'M'.
2. One of my colonists is 'hanging out' with my T-Hybrid terminator..... and they can't finish even after colonist fainted from exhaustion, starvation, etc... 
3. Burn apparel doesn't work at basalt kiln (havent tried in any other). You can make bill, bu then noone can do it.
4. Not a bug, but a thought. It's kinda unfair how smoothed rock gives bonus to beauty and walls do not. You should add some option to engrave constructed walls for some bonuses.
5. Not sure if bug or my fault - after ~5years on planet not even once was my colony visited by merchants.

**Comment by masakitenchi** [comment]
Closed as too old
