### ISSUE TITLE
Торговые караваны не приходят

### ISSUE THREAD

**Issue by Tony2371** [skyarkhangel/Hardcore-SK#1731]
Сборка последняя на 23.04.2019 (development branch). Торговые караваны не приходят. Уже третью колонию стартую, но ни одного каравана так и не пришло, хотя гости время от времени заглядывают. 

p.s. В Development mode в меню принудительной активации событий напротив Trader Caravan Arrival стоит [NO], как и у еще нескольких событий. Если я правильно понимаю, определенные условия должны быть выполнены, чтобы событие попало в игровой цикл. Но какие?

**Comment by masakitenchi** [comment]
Closed as too old
