### ISSUE TITLE
Всячина (mnogo russian language)

### ISSUE THREAD

**Issue by ImTheMass** [skyarkhangel/Hardcore-SK#1732]
Версия HSK последняя на 25.04.19. Версия Rimworld 1.0.2150
Замеченные баги:
1. Иногда некорректно отображаются имена Азари (пишет - Errorname).
2. Пулемет ГШ-30 нельзя построить, хотя его детали есть в продаже и в ветке исследований.
3. Часто при появлении новой черты характера она не сохраняется в характеристиках пешки.
4. Нова и Азари не могут пользоваться комодом (изменение внешности). Подходят к комоду и сразу уходят.
5. Картотечный шкаф, который должен увеличивать скорость исследований, не работает. Даже при размещении рядом с научным столом пишет "осключен".
6. Дроиды выходят из гибернации когда им вздумается.
7. Миномет нельзя собрать на верстаке, в то время как остальные турели собираются, даже без соответствующих исследований. Это нормально?

Спорные моменты
1. Рассказчик (Кассандра, Рей) какой-то вялый для "вызова". В b18 он мне сжигал седалище, а тут даже скучно. За 5 лет из опасного лишь один геошторм и один психокорабль. Справедливости ради хочется отметить, что качество налетов растет постепенно от простого к сложному (от луков к огнестрелу), как и должно быть. Беда в том, что обогнать этот рост сложности - слишком просто, даже для "вызова".
2. Большую часть силовой брони нельзя произвести. Если это такой баланс, то он достаточно плохо реализован. Можно уж тогда различные типы брони привязать различным же фракциям, чтобы только у них эту броню можно было приобрести (Азари - у Азари; Синдикат, скажем, у братства кровавой луны; Межзвездная, допустим у корпорации и т.д.) Тогда появится возможность выбора союзника и связанных с этим бонусов (сейчас это не так, я специально прошел караваном через несколько разных поселений и проверил).
3. Растениеводство крайне несбалансировано. У меня пятый год пешки в десятом поту сажают растеница и не могут раскачаться дальше 13 уровня. Не критично, но странно. То же исследование или строительство вылетает в 20 буквально за год.
4. Smartgun настолько сломан, что достоин быть квестовым оружием. Или, хотя бы,, - дорогим по ресурсам.
5. Совсем непонятно, как работает высокотехнологичное оружие. По характеристикам - оно хуже кинетических винтовок(точность, урон боеприпасов, дальность, скорость и др.), а по эффективности - я бы так не сказал. Сложнаа.
6. Беда с той же силовой броней: тяжелая броня - это внешний и промежуточный слой. Легкая и средняя - только внешний. Так вот, тяжелая броня защищает пешку втрое хуже, чем легкая(внешний слой)+бронежилет(промежуточный). Да и к тому же дополняется кучей дебафов. Бессмыслица какая-то.

Глупости.
1. Глупость, но мне показалось интересным добавить функцию окраски одежды. Что-то вроде - сделать набор красок, после чего на станке выбрать настройки перекраски одежды. Вон, пешки корпорации, у меня, все в сером ходят независимо от материала одежды.. Круто же.
2. Было бы интересно ограничить количество союзников. Скажем, добавить требования разорвать отношения с фракцией (здравствуй, Spore).
3. Верните броню "Валькирия"! Хоть она и имбалансная, но крутая же!

Спасибо, что дочитали до конца мою писанину. Мне безумно нравится HSK и сам RimWorld и я желаю им становится  только лучше и лучше =D. Если я где-то ошибся, буду признателен за разъяснения.

**Comment by masakitenchi** [comment]
Closed as too old
