### ISSUE TITLE
Статус версии, road map...

### ISSUE THREAD

**Issue by OpacareAngelus** [skyarkhangel/Hardcore-SK#1739]
Очень жду релиза вашей сборки, но нигде не могу найти информации о её статусе. Когда можно будет ждать рабочей версии? 
Очень не хотелось бы начинать колонию, а потом пересоздавать её снова >_>

**Comment by semareset** [comment]
Сборка полностью рабочая, мелкие огрехи есть и будут всегда. На данный момент нет ни критических багов, ни серьезных недочетов. В будущем исправится немного баланс крафта, баланс системы стрельбы и визуальная составляющая. Так что смело начинайте колонию, или попробуйте себя в долгом походе к точке с кораблем (от ИИ). Все новые патчи ставьте при помощи лаунчера от команды СК и при загрузке просто подтверждайте что сэйв должен работать с новыми модами. Если что-то изменится, Скай сразу же сообщит об этом в группе в ВК.

П.С. Добро пожаловать!!

**Comment by OpacareAngelus** [comment]
Спасибо за информацию.
Я так-то на сайте HSK следил, но там что-то глухо D:

**Comment by masakitenchi** [comment]
Closed as too old
