### ISSUE TITLE
Icicat triggers cold snap on arrival

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#174]
Not sure if this is intended, as feenix arrival doesn't cause a heatwave.

**Comment by zakhad** [comment]
Yup right in the middle of summer there goes all my crops really hate this, it used to be only on death.

**Comment by jnkyacc** [comment]
> as feenix arrival doesn't cause a heatwave.

Ignition of all shit around seems not enough? :)

**Comment by Jalordon** [comment]
Usually feenix and icicats beeline toward my colony and I have everyone just unload bullets to get their valuable hearts.

**Comment by skyarkhangel** [comment]
Do you want heatwav incident?

**Comment by skyarkhangel** [comment]
So close issue for now.
