### ISSUE TITLE
Проблемы с лечением (давние проблемы).

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1742]
Три пешки заболели пневмонией. 
1. Сообщение получено, но болезнь скрытая, в койку уложить нельзя - несколько часов. Дал всем троим лечебную настойку из трав. В дальнейшем давал настойку ежедневно.
2. Как только заболели, тут же уложил на койки, со скоростью иммунизации **139%**. 
3. В палате установлены и работают три начальных медицинских прибора. Лечил по кд полевыми медикаментами.
Т.е. вроде всё отлично, очень хорошее медобслуживание. НО:
1. Одна пешка еле выздоровела. Разница между болезнью и уровнем иммунитета около 5%.
2. Вторая пешка выздоровела чудом. Разница менее 1%.
3. Третью - только спасать через консоль. Стартовая разница между болезнью и иммунитетом около 25%, итоговая, перед гибелью, 9%.
Как по мне, это совершенно неправильная ситуация. 
Помимо этого, осталась старая недоработка. Выздоровев, пешка пытается уйти из больницы. Но, так как ходить она практически не может, то через несколько шагов падает на землю. И класть её в постель бесполезно. Ибо она так и будет долго и упорно, часами, вставать и падать. 
Думаю, стоит немного доработать болезни, убрать настолько тяжёлый вариант развития, который почти не лечится - ну если только какими супер-медикаментами, которые будут лет через 5 игры. И добавить функцию "профилактическое лечение", позволяющее принудительно уложить пешку в койку - до отмены.

**Comment by ImTheMass** [comment]
Нуу... Первое - это не сказать чтобы проблемы сборки. За то мы и любим римку, что она сложная. Пневмония в принципе лечится тяжко, а если у Вашей пешки еще и слабый иммунитет, отсутствует почка или болеет печень (беда с кровообращением) то вылечить ее вообще становится героической задачей. И, да, часто спасают только передовые медикаменты. Заначку на черный день никто не отменял, как и пересадку органов. 

А по поводу "падает пешка в проходе", это из-за "темного окружения". Почему-то дверные проемы считаются недосягаемыми для света. кроме случая когда освещение встроено в стены. Это, конечно, беда.

**Comment by SetAriman** [comment]
В том и вопрос. Пешка была здоровой. Так что героическая задача это просто вылечить пешку. И это вполне возможно уже в первые годы игры племенем, когда передовые медикаменты даже купить не всегда возможно. И хорошо если просто смог построить кровати с высокой иммунизацией. А уж о пересадке органов вообще речь не идёт. Т.е. игрок получает нерешаемую проблему. Хотя вся игра построена на их преодолении.

Я знаю про проход. Но я и предлагаю решение. Оно же поможет в борьбе со скрытыми болезнями. Только желательно сделать индикатор скрытого заболевания у пешек. Тогда тех же пневмонийщиков можно будет тут же загнать в кровати и дать антибиотик. А потом придержать, пока не смогут нормально ходить. А то пешка ходить не может, а тут: работайте, негры, солнце ещё высоко!

**Comment by masakitenchi** [comment]
Closed as too old
