### ISSUE TITLE
Что насчёт мода QualityBuilder?

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1748]
В сборке Минимализм сталкивался с этим модом - крайне удобен и необходим, когда в отряде больше одного строителя. Тут его почему-то не включили. Можно уточнить: его посчитали ненужным или он конфликтует со сборкой? Хочу его поставить, потому и интересуюсь.

**Comment by TlepshSmither** [comment]
мужик, здесь ошибки по Римке пишут, а не просьбы/вопросы...

**Comment by SetAriman** [comment]
Чувак, тогда это ошибка, что в ХСК до сих пор надо на стройку каждого долбанного стула отправлять строителя вручную, дабы не порол херни.

**Comment by masakitenchi** [comment]
Closed as too old
