### ISSUE TITLE
Ogres trivialize food and leather

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#175]
Someone pointed it out in the forum thread and I agree with it that ogres give way too much meat and leather.

Is it intended for them to give so much resource?

**Comment by zakhad** [comment]
Concidering if you don't have ranged weapons they're lethal 20-40 weapon damage. I think its okay honestly but maybe like a 10-20% nerf if anything

**Comment by Jalordon** [comment]
The issue isn't so much their deadliness, they are understandably very strong in melee. Ogres don't flee and I usually get 6-10 ogres in one attack while at 100,000 around wealth. 

Each ogre has a base of 150 leather and meat and it gets multiplied further (1.8) by their body size, so each ogre is 270 meat and leather, saying no body parts get shot off. 

In other words I get up to 2700 of each in a single attack, which makes for a lot of meals and ogre skin to the point that i have to make a separate outdoor stockpile for all the leather i get.

**Comment by Vigilence** [comment]
What I thought was weird was that they are eatable without any negative buffs.  Are they considered animals in the game?  I thought they were humanoid since they carry armor/gear and melee weapons.

I thought initially I would get the cannibalism debuff but nothing.

**Comment by Inei** [comment]
What's worse, they seems to be dying not from injuries, with their health pool, but rather from pain shock, from those "injuries", as it seems they have same pain threshold as humans, which means when they get certain amount of damage, they simply either fall unconscious, or simply die, having only few "scratches" comparing to their health level.

**Comment by Jalordon** [comment]
Mildly on topic, the change in commit 2e880cda5b16fd27b0864134199e7a13cb9ec5a2 made ogres have a lot more health but they generally died from either dying instantly when incapacitated or after a few days of starving (the commit made them starve faster too but still takes a bit of time).

It's practically impossible for them to lose even an insignificant body part (example of 650 health nose) before being incapacitated by pain. Does pain factor work for pawns so that could be applied to ogres for more durable ogres without needing really high health?

The 2.5x modifier before the commit made ogres practically never lose any body parts, so health modifier could go down to 1 - 1.5x without making ogres lose body parts short of extreme luck. Lower health also makes it easier to finish off incapacitated ogres.

**Comment by zakhad** [comment]
Did they get a speed buff as well? Because I'm noticing I'm not quite able to kite them as well as before, which is fine its not too drastic but it caught me off guard. But i agree nose/lesser parts. should only be like 50 tops pawns have like what 9? and thats 5x as much at that let alone 650 at 72x

**Comment by trevize23** [comment]
Ogres need a rebalance once again. I feel they got way overbuffed.
I think the recent updates made them faster (?) and you can't incapacitate them anymore. So the only downside they still have is being melee.  

If you want to go the route of Ogres being melee monsters then give some fitting downsides. Imo they should even get a speed nerf instead of the buff.

**Comment by skyarkhangel** [comment]
Closed. Rebalanced several times.
