### ISSUE TITLE
Режимы работы сантехники.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1750]
У сантехники - унитазы, душ и т.д. есть режимы работы: мужской, женский, унисекс. Это понятно - делать раздельные комнаты, дабы пешки не смущались. Но какой смысл в этом режиме, если при смене его на одном душе или унитазе, тут же изменяются все остальные? Сделал душ мужским - ВЖУХ! - все души чисто мужские.

**Comment by OpacareAngelus** [comment]
А я отдельные делаю, чтобы не парить мозги :)

**Comment by SetAriman** [comment]
Это, разумеется, можно. Но это использование костылей вместо имеющейся механики. Которую надо либо чинить, либо отключать.

**Comment by Zim777** [comment]
Меняется не на конкретную вещь, на на комнату. Ставь унисекс и разные аппараты разделяй дверьками из гигиены, тогда они не будут смущаться. Или отдельные комнаты для мужчин или женщин.

**Comment by SetAriman** [comment]
Тоже неплохо. Было бы. У меня унитазы каждый в отдельной кабинке, с дверями из гигиены. Меняешь один - меняются все. Души по 2 в отдельных кабинках, с дверями из гигиены. То же самое.

**Comment by masakitenchi** [comment]
Closed as too old
