### ISSUE TITLE
Multiplayer (by Zetrith) Mod Issue

### ISSUE THREAD

**Issue by Szaman1** [skyarkhangel/Hardcore-SK#1751]
Hardcore_sk runs with mod fine and there is no error in game log(except little problem with RimThemesLite, because it's not showing extra multiplayer button, but when this mod is off everything is ok)) but when we Host the game in multiplayer, problem is with Time control- doesn't work. Clicking the buttons doesn't affect the time speed and keyboard shortcuts doesn't work either. 

In my opinion problem is with part of the core_sk mod because it seems that he has a integrated mod (Easy speedup maybe?)  with extra speed button maybe the core sk and multiplayer using two different library or something?

Anyway i think that that issue should be resolve somehow, maybe by separated time speed control mod to allow peoples turn it off? 

or maybe there is some possibilities to do something with that?

Multiplayer mod is very awesome thing. I tested it on vanilla version with friends and i think that with hardcore mod it will be Super Awesome combination! 

links:
https://github.com/Zetrith/Multiplayer

**Comment by skyarkhangel** [comment]
No adaptation to multiplayer yet.

**Comment by Szaman1** [comment]
But there is some way to run Hardcore mod without extra speed button mod? maybe it's just that? or you tested this already?  i'm ready to test game but i'm not sure how to turn off this mod. there is some access to core_sk source code ? 

I'll glad to help with this matter.

**Comment by vperpl** [comment]
use dnspy to steal the mod content & modify so it works fine for multiplayer

**Comment by masakitenchi** [comment]
Closed as too old
