### ISSUE TITLE
Хитрые зомби.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1752]
Отстреливаю зомби из-за мешков с песком и амбразур (двойная линия). Пешки активно стреляют по ним до тех пор, пока зомби не начнут ползать. По ползунам пешки стреляют очень редко и не могут вести огонь принудительно - только если вывести их на позицию прямой стрельбы. При этом прямая стрельба происходит почти исключительно в принудительном режиме. НО: если ползун укусит дверь, пешки тут же открывают по нему огонь. Даже из-за защитной линии.

**Comment by masakitenchi** [comment]
Closed as too old
