### ISSUE TITLE
Возможная ошибка в работе подкреплений.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1753]
На мою карту прибыло враждебное племя. Не атакой, а просто проходило мимо. Взаимных атак не было. Но тем не менее, прибыл десант союзников и выпилил их под корень. По мне, это ошибка - меня ведь не атаковали и не собирались. Помимо этого, возможно стоит уменьшить дроп на месте высадки союзников. 3000+ дерева и куча металлолома это, как по мне, перебор.

**Comment by skyarkhangel** [comment]
Похоже на ошибку в текущей версии самой игры. Т.к. HSK, в том числе дополнительные модификации в составе, не затрагивают эвента с помощью союзников.

**Comment by masakitenchi** [comment]
Closed as too old
