### ISSUE TITLE
Сильно лагает

### ISSUE THREAD

**Issue by Pfertsegentakl** [skyarkhangel/Hardcore-SK#1754]
Загрузка игры идет очень долго, в главном меню появляется окно с такими логами https://gist.github.com/HugsLibRecordKeeper/e249cd60e8adaca03c01963c47142325

В процессе игры все очень сильно лагает, даже когда я ставлю на паузу.
Процессор: FX 6300
Оперативной памяти 7 гб, (может мало?)
Игра на ssd
Windows 10

Версия игры 1.0.2231, 64 bit

**Comment by skyarkhangel** [comment]
Лог хороший, сейв приложите.

**Comment by Pfertsegentakl** [comment]
При запуске новой игры уже начинает лагать.

[Поселение1.zip](https://github.com/skyarkhangel/Hardcore-SK/files/3207798/1.zip)

**Comment by skyarkhangel** [comment]
Проверь загрузку памяти, процессора. Объем виртуальной памяти.

**Comment by SetAriman** [comment]
Возможно это стартовая загрузка. У меня игра тоже лагает, и здорово - первую минуту после первого запуска. Потом нормально.

**Comment by masakitenchi** [comment]
Closed as too old
