### ISSUE TITLE
Вылетает игра

### ISSUE THREAD

**Issue by abaskakau** [skyarkhangel/Hardcore-SK#1755]
Вылетает при попытке открыть вкладку "Здоровье" и при клике на местность при открытом меню строительства

Воспроизводится в ветке master и в ветке development
Rimworld latest Steam (>1.0).

macOS Mojave 10.14.4

**Comment by rogoznikoviv** [comment]
На linux и версии 1, тоже вылетает если нажать кнопку "Био".

И на бете и на стабле вылетает.

**Comment by rogoznikoviv** [comment]
Отключил мод RimThemesLite и заработал выбор демократии/диктатуры и вроде всё стало открываться.

**Comment by abaskakau** [comment]
> Отключил мод RimThemesLite и заработал выбор демократии/диктатуры и вроде всё стало открываться.

Позволю уточнить, а при появлении окна выбора типа правления тоже отсутствует кнопка "Ок/Подтвердить", но при нажатии enter тип правления все-таки выбирается?

**Comment by Zim777** [comment]
Позволю уточнить, кнопка выбора появляется. если в настройках данного мода выключить полностью анимацию окон.

**Comment by rogoznikoviv** [comment]
> Позволю уточнить, а при появлении окна выбора типа правления тоже отсутствует кнопка "Ок/Подтвердить", но при нажатии enter тип правления все-таки выбирается?

Да, кнопка отсутствует, но ентер я не пробовал, просто нажал ескейп и вошел в карту.

**Comment by skyarkhangel** [comment]
> Отключил мод RimThemesLite и заработал выбор демократии/диктатуры и вроде всё стало открываться.

Проверьте с последним сегодняшним обновлением. Осталась ли проблема?

**Comment by rogoznikoviv** [comment]
> > Отключил мод RimThemesLite и заработал выбор демократии/диктатуры и вроде всё стало открываться.
> 
> Проверьте с последним сегодняшним обновлением. Осталась ли проблема?

Обновился, кнопка "ок" в выборе демократия/диктатура - не появилась, но если просто нажать ентер, то уже игра не вылетает из "персоны" и других пунктов детализирующих персонажа.

**Comment by skyarkhangel** [comment]
Закрывайте через Esc, с кнопкой разберемся.

**Comment by abaskakau** [comment]
> Закрывайте через Esc, с кнопкой разберемся.

Спасибо, теперь работает
