### ISSUE TITLE
баг в переработке шмота/оружия

### ISSUE THREAD

**Issue by MlTHRlL** [skyarkhangel/Hardcore-SK#1756]
на верстаке кожевника/рабочем месте/столе оружейника/(любом другом столе с возможностью разбирать предметы на составляющие) колонисты периодически, когда идут выполнять разборку предмета, начинают его перекладывать по столу туда-сюда пока не отвлекутся на другую работу

**Comment by SetAriman** [comment]
Они это иногда и с крафтом делают. Обычно если освободилась позиция выше той, которую пешка начала крафтить. В таком случае помогает смена позиции в списке крафта.

**Comment by MlTHRlL** [comment]
> Они это иногда и с крафтом делают. Обычно если освободилась позиция выше той, которую пешка начала крафтить. В таком случае помогает смена позиции в списке крафта.

с другими верстаками таких проблем не наблюдал
мне обычно помогает принудительный перенос этого предмета

**Comment by ronekarleone** [comment]
Это проблема связана с тем, что перед крафтом нужно очистить верстак.
Такое бывает, если на верстаке валяются вещи, выкинутые вручную/принудительно, либо сменилось задание и надо убрать заготовку. 
В обоих случаях пешка не может убрать предмет на склад, а переставляет его туда сюда на верстаке.

**Comment by SetAriman** [comment]
Лично у меня эта проблема была (и много раз) только из-за смены приоритета в крафте. Т.е. даже при чистом верстаке. Пока несла расходники, освободилась более высшая позиция в крафте. В результате вроде надо делать одно, а начато второе. И пешка гоняет заготовку по станку. В результате или разбирать заготовку или менять приоритет в крафте. Когда заготовка обретает максимальный приоритет, пешка тут же успокаивается и начинает крафт. А другие вещи ей не мешают, даже если их там 2-3 заготовки. Скидывает на пол и крафтит.

**Comment by masakitenchi** [comment]
Closed as too old
