### ISSUE TITLE
"нужны аккумуляторы"

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1757]
Такое сообщение у меня висит постоянно, хотя давно установлены и работают 10 аккумуляторов. 2 найденных и 8 крафтовых.

**Comment by OpacareAngelus** [comment]
Возможно, что у тебя где-то есть источник питания, не подключенный к общей сети (или к аккумуляторам в принципе). У меня такое бывало. Ткнул солнечную панель и считай забыл. А потом, в какой-то момент, провод вообще обломился, а панель осталась торчать в стороне и генерировать электричество в никуда.
Проверь целостность цепочек от генераторов электричества к аккумуляторам.

**Comment by SetAriman** [comment]
Возможно, спасибо. У меня ветрогенератор из гигиены изначально не подключен (да и не должен, по идее). Правда на него игра не ругалась с аккумуляторами, пока нормальный ветряк не поставил.

**Comment by SetAriman** [comment]
Проверил - не он. Всё подключено. Так что проблема осталась.

**Comment by SetAriman** [comment]
Проблема пропала когда ... построил и подключил геотермалку. Странно сие.

**Comment by masakitenchi** [comment]
Closed as too old
