### ISSUE TITLE
Электрическая бетономешалка.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1758]
Построил электробетономешалку. Ибо сказано, что она быстрее обычной. Но по факту, обе, оловянные, работают со скоростью 120%. Или я что-то упустил, или ... на этом мысли останавливаются.

**Comment by OpacareAngelus** [comment]
Возможно имеется ввиду, что 120% от базовой скорости. Возможно электрическая имеет базовый модификатор выше.

**Comment by SetAriman** [comment]
120% это финальная производительность. Производная от материала, базового модификатора и всякой чистоты пола и прочего.

**Comment by masakitenchi** [comment]
Closed as too old
