### ISSUE TITLE
Sad mood cutting wrists disease infection nerf

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#176]
The wandering duration for cutting wrists needs to be reduced I had someone get to major infection before I'm able to get to give them their first treatment and in the early game when you don't even have you're first bed and/or medicine is just bad design.

Sure i could shoot them down or punch them down but then theirs a chance I'd start losing fingers/toes/blindness because theirs no way to recover from that in the early game it just encourages save scumming.

I could force arrest and imprison but that's which normally was fine because you could just immediately release them but now you have to re recruit someone for being "stupid" which depends on your social could take days/weeks

**Comment by skyarkhangel** [comment]
A14 bug. Closed.
