### ISSUE TITLE
Проблема с руинами.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1760]
Пришёл. Зачистил противников. Убил появившихся зомби, включая ползающих. Открыл все возможные комнаты. На миникарте ни одной красной точки. Прождал больше полудня. Но уйти не могу, якобы потому, что остались противники. Пришлось загружаться и отменять поход.

**Comment by TlepshSmither** [comment]
Та же самая проблема. А знаете почему? Потому-что игра зарезервировала сразу 3 нападения на руины и пишет, что уйти нельзя. Баг короче.

**Comment by ronekarleone** [comment]
Из руин (возможно не из всех) можно уйти через край карты: подойти к краю и щелкнуть на/за край. Нужно подходить всей группой, иначе выйдут раздельно.
Но в таком случае нужно вручную загрузить все вещи в караван, т.к. нельзя выбрать вещи для выноса с карты.

**Comment by Pepelnica1488** [comment]
ДОСИХПОР не исправили такой дебильный и важный баг

**Comment by gleb031212** [comment]
> ДО СИХ ПОР не исправили такой дебильный и важный баг
это не баг. после зачитски руин надо там "продержатся " 2-3 дня отюивая атаки и осады рейдеров которые тоже хотят поживится хабаром. не сил? не беда беги всеми пешками на край карты (останутся только вещи в инвентаре)

**Comment by Pepelnica1488** [comment]
> > ДО СИХ ПОР не исправили такой дебильный и важный баг
> > это не баг. после зачитски руин надо там "продержатся " 2-3 дня отбивая атаки и осады рейдеров которые тоже хотят поживится хабаром. нет сил? не беда беги всеми пешками на край карты (останутся только вещи в инвентаре)

мдя об этом никто не писал но ладно,самое важное что это ТУПО ибо зачем я должен кого то ждать? это же МЕГАТУПО тупее чем стадо комаров нападающих каждый день на тебя в саванне

**Comment by SetAriman** [comment]
Ага: просто ожидая, когда баг спадёт.

**Comment by hadaev8** [comment]
Руины скопипасчены в сборку без изменений, так что про все проблемы надо писать автору мода в стиме.
Не говоря уж о том, что это не баг, а фича.

**Comment by SetAriman** [comment]
Как победить баг? Объявить его фичей! Изи же. На самом же деле фичи логичны и интуитивно понятны. А здесь этим и не пахнет - ты не поверишь. 
P.S. Враньё а-ля Близзард: это не баги, это фичи и вообще вершина баланса!

**Comment by TlepshSmither** [comment]
Проблема решается тем, что нужно залезть в настройки мода на руины и разрешить уходить из них. Всё.
Бага нет.

**Comment by Pepelnica1488** [comment]
неплохо бы добавляя его в сборку тыкнуть это по дефолту

**Comment by masakitenchi** [comment]
Closed as too old
