### ISSUE TITLE
Проблема с электрическим крематорием.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1761]
Если я даю пешке задачу сжигать трупы - она сжигает, одного за другим. Но: если на карте где-то активна задача "собирать песок" и я даю пешке команду сжигать трупы, то пешка сжигает один труп и тут же, не сходя с места, начинает собирать песок на месте установки крематория. Несколько раз потестил - баг стабильный.
P.S. Обычный крематорий не проверял.

P.P.S. Тоже самое произошло, когда дал команду поставить в комнаты пару тумбочек. Пешка их поставила и начала собирать в этом месте песок.

**Comment by masakitenchi** [comment]
Closed as too old
