### ISSUE TITLE
Нет прерывателей.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1763]
Изобрёл прерыватели, но возможность их строить не появилась. Только предохранители.

**Comment by Zim777** [comment]
Изучайте все, что необходимо для строительства той или иной постройки\вещи.
В вашем случае исследовать только "прерыватели" недостаточно, необходимо также и "робототехника"

**Comment by SetAriman** [comment]
Ок, понятно. 

Как по мне, это извращение. У меня для вас прерыватели, которые вы изобрели, только вы их не получите - потому что нужно другое изобретение из другой эпохи. Как и с винтовками. Изобрести - изобрёл, а крафтить своими силами нельзя, запчасти в другой эпохе. Это как изобрести транзисторный приёмник не изобретя транзисторы. :(

**Comment by ynemo** [comment]
Ну это нормально, это как российский смартфон. Собран в России, но все запчасти из Китая. Всё логично.

**Comment by SetAriman** [comment]
Это разные вещи. Составные части смартфона были изобретены до его появления, а не после. Не путай изобретение чего-то с нуля от простого к сложному и крафт чего-то.

**Comment by masakitenchi** [comment]
Closed as too old
