### ISSUE TITLE
Проблемы с тераморфингом.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1764]
Судя по всему, тераморфингу не поддаётся claystone. Он даже за каменный пол не считается, если его сгладить. Так что набросать чернозёма тоже не выйдет.

**Comment by murmax** [comment]
Поддерживаю, аналогичная ситуация с базальтом. Все усугубляется тем, что эти штуки находятся не в Core_SK, А в своих модах. Для себя исправил, но стоит все же глобально этим заняться.

**Comment by masakitenchi** [comment]
Closed as too old
