### ISSUE TITLE
Всё пропало, шеф!

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1767]
Обновил сегодня игру до текущей версии, и ...
1. Меню по Ескейп вызвать нельзя.
2. Различные всплывающие подсказки - в меню игры и настройках модов - теперь не пропадают с экрана, заслоняя собой всё изображение.

**Comment by skyarkhangel** [comment]
переустанови, у тебя какая-то ошибка.

**Comment by SetAriman** [comment]
Полностью всё удалил (как сказано на форуме, с удалением папок) и установил заново - не помогло. 

Помимо этого в журнале появилось много новых ошибок. https://git.io/fjRAe

**Comment by SetAriman** [comment]
Поэкспериментировал - новая игра создаётся без проблем. Старой пришёл песец. ОЧЕНЬ крутое обновление. (Надеюсь это не часто.)

**Comment by skyarkhangel** [comment]
С последним обновлением проверь совместимость со старым сейвом

**Comment by SetAriman** [comment]
Обновил сейчас - ничего не изменилось. С сейвов играть невозможно, только новую игру начинать.

**Comment by SetAriman** [comment]
Кстати: при появлении игрового меню после запуска игры, выскакивает лог. https://git.io/fj0kp

**Comment by masakitenchi** [comment]
Closed as too old
