### ISSUE TITLE
Backstories

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#177]
@skyarkhangel ССЛ"овские бакстори только добавляют новые, а заменить ванильные можно? xml заинжектить вместо ванильного можно как то?

**Comment by skyarkhangel** [comment]
вместо.. скорее всего врядли

**Comment by jnkyacc** [comment]
@skyarkhangel затереть ванильные у меня получилось, но оно трет и ССЛовкие. т.к шарп я знаю в общей сложности часов 48, то я не могу допереть как сделать что бы или оно терло до того как ССЛовские подгружает или второй раз только ССЛовкие грузить. ССЛовкие на русском работают.
я пытался поменять путь и скормить его же хмл"ки которые в ассетах, но видимо оно припаяно только к ассетам... спросил равкода с лудеона мож чо и ответит.

**Comment by jnkyacc** [comment]
:laughing: ну короче он ответил в своем стиле "все возможно" и ничо такого что бы помогло...

`foreach (Backstory bs in XmlLoader.LoadXmlDataInResourcesFolder<Backstory>("Backstories/Shuffle"))`

Путь можно переписать этот? "Backstories/Shuffle" на папку мода?

**Comment by jnkyacc** [comment]
Пошел по другому пути, без замен чего либо...
![screenshot69](https://cloud.githubusercontent.com/assets/20729235/18724301/45a59a8a-803c-11e6-8f38-9215531b86dd.png)
надо только заставить брать значение из хмл"ки, сравнивать и заменять на переведенную... Х_х
