### ISSUE TITLE
Не меняют инструменты

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1770]
У поселенца в руках серп в инвенторе мотыга и топор, идет рубить дерево, но не меняет инструмент.
К смене предметов в целом:
Было бы не плохо, чтобы поселенцы убирали оружие из рук, когда работают.
Охотник взял в руки молоток и больше не может охотиться, хотя пистолет в инвентаре.

**Comment by hadaev8** [comment]
Мотыги нет в назначениях инструментов

**Comment by SetAriman** [comment]
У меня мотыга есть в назначениях, но толку - она глючная, отписывался в других репортах.

О смене инструментов. Бывает такое, что пешка подбирает два однотипных инструмента - например два топора - и стоит около дерева, потому что не может его срубить: переключает топоры взад-вперёд.

**Comment by hadaev8** [comment]
Таже история с инструментами разного типа, но одного класса, например: молоток и гаечный ключ.

**Comment by SetAriman** [comment]
Кстати: эта система инструментов дала ещё один баг. Теперь пешки не берут нормально в руки оружие при переходе в боевой режим. Т.е. если бойца ближнего боя переводишь в боевой режим, он не берёт в руки оружие, а зачастую стоит с инструментом. А если убегающую пешку с дробовиком, которую пнул зомби, перевести в боевой режим, обычно и она не возьмёт дробаш в руки. Если не ошибаюсь, при использовании гранат иногда тоже было подобное.
