### ISSUE TITLE
Religion

### ISSUE THREAD

**Issue by PigQuark** [skyarkhangel/Hardcore-SK#1771]
При отказе от мода Религия - ошибки. Чистая установка с нуля. 
![Image 663](https://user-images.githubusercontent.com/51176723/58589405-1909f680-8262-11e9-9dbe-b85bcf368cf2.jpg)

**Comment by Zim777** [comment]
1. ставьте начисто HSK, не запускаете
2. открываете ModsConfig.xml и удаляете оттуда строчку <li>Religion</li>, сохраняете изменение
3. запускаете HSK, профит

**Comment by masakitenchi** [comment]
Closed as too old
