### ISSUE TITLE
Проблема со складами в новом патче.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1773]
Начал новую игру, ибо патч запорол старое прохождение. Возникла странная проблема. Начал игру - сделал склад. Пешки таскают ресурсы, всё норм. НО. Если я создаю ещё один склад - с повышенным приоритетом для хранения обломков камня, досок, дров и т.п. - он не работает. Игра не воспринимает его как склад для выделенных ресурсов. И, в качестве второго и последующих складов, приходится использовать свалки.

**Comment by masakitenchi** [comment]
Closed as too old
