### ISSUE TITLE
Переборщили с инструментами.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1776]
Ввели новую систему инструментов. Мол реализм, все дела. НО. Сейчас смотрю - пешка из племени стала крафтить кирку - нужное дело в горах, а то за пол-года обои две кирки в пыль стесались. Объём работ: "осталось 525". 525, Карл! На всего 1 (один) инструмент. Интересно, сколько недель пешка будет крафтить один инструмент на рабочем месте из гранита? Один из кучи необходимых?

**Comment by ronekarleone** [comment]
Это глобальная проблема экономики. Вещи более высокого уровня стоят дешевле, чем их исходники. Крафтишь ты какое нибудь пиво, в итоге оно стоит дешевле, чем на него затрачено ресурсов. Поэтому сейчас нет смысла ничего крафтить. Только разбирать до базовых ресурсов и продавать их.

**Comment by masakitenchi** [comment]
Closed as too old
