### ISSUE TITLE
Продвинутый компонент дешевле обычного компонента

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1777]
Продвинутый механизм только слегка дороже обычного.
Еще мне кажется странным, что можно переплавить молот тора и получить компонент за 40 ценности, хотя ценность самого тора 5.
Мне кажется, цена вещей должна быть как минимум не меньше, чем цена затраченных ресурсов.

**Comment by ronekarleone** [comment]
Это глобальная проблема экономики. Вещи более высокого уровня стоят дешевле, чем их исходники. Крафтишь ты какое нибудь пиво, в итоге оно стоит дешевле, чем на него затрачено ресурсов. Поэтому сейчас нет смысла ничего крафтить. Только разбирать до базовых ресурсов и продавать их.

**Comment by hadaev8** [comment]
"Enemy ship" from core sk, event enemy landing or something, not sure what is it in english.
So they spawn on bottom side and cant go around instead attacking ship, probably because of shallow water path cost?

**Comment by TheLoneTec** [comment]
You shouldnt be getting a regular component from a thor hammer. The smelt components are medieval components

    <smeltProducts>
      <Bronze>3</Bronze>
      <ComponentMedieval>2</ComponentMedieval>
      <FSX>1</FSX>
    </smeltProducts>
    
    If you are getting industrial components, something is messing with your xml

**Comment by TheLoneTec** [comment]
also an advanced components market value is 100 vs the 40 of the industrial component

**Comment by TheLoneTec** [comment]
wait ignore, for some reason discord linked to this old issue lol, closing
