### ISSUE TITLE
Электрокузню нельзя переместить

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1778]

**Comment by SetAriman** [comment]
Почти всё нельзя переместить. Учитывай на будущее. ;)

**Comment by hadaev8** [comment]
Почти все как раз таки и перемещается.

**Comment by SetAriman** [comment]
Это в начале. А потом - нет.

**Comment by Rrs0** [comment]
Офк должна переставляться.

**Comment by masakitenchi** [comment]
Closed as too old
