### ISSUE TITLE
Баг с подбором инструментов.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1779]
В новой версии игры пешки начали взад-вперёд брать инструменты, которые им не назначены. То есть, к примеру, у меня уборщик периодически бегает на склад за молотком, подбирает его, а через какое-то время несёт обратно. Строитель часто тырит кирку, хотя он даже не назначен на шахтёрство. В итоге это ещё и провоцирует старый баг очерёдности крафта, из-за которого пешка начинает крафтить новый инструмент, а потом тупо перемещает заготовку взад-вперёд по столу.

**Comment by desolaris** [comment]
Да, при работе происходит переключение между инструментами раз в секунду. Баг с разделкой туши был, полдня простояла возле рабочего места ежесекундно меняя инструменты(мультитул, кирку и разводной ключ), полоса прогресса работы каждый раз начиналась заново. Замочек не помогал, принудительно выкинул из инвентаря всё кроме мультитула, тогда она смогла закончить работу.

**Comment by SetAriman** [comment]
К счастью это отключаемо в настройках мода, есть там "оптимизация". Что не отменяет её багнутости.

**Comment by masakitenchi** [comment]
Closed as too old
