### ISSUE TITLE
Two bugs that I've found

### ISSUE THREAD

**Issue by tim0901** [skyarkhangel/Hardcore-SK#178]
1. Battery efficiency does not change with infrastructure research
2. Production tables (e.g. electric smelting furnace) are not changing their power consumption when in use/idle causing them to get stuck on max power when not in use

**Comment by Jalordon** [comment]
For the second issue I was told it is a CCL issue. 

I managed to get it fixed for myself by  adding <tickerType>Normal</tickerType> to every production facility that needs power. 

It works to get it to have idle costs as expected though I don't know if it significantly costs processing power.

**Comment by skyarkhangel** [comment]
1. Battery effciency upgrade temp. removed with A14 update.
2. Yep, sometimes bugs, cause of CCL.
