### ISSUE TITLE
UI Windows Not Disappearing

### ISSUE THREAD

**Issue by Sindusk** [skyarkhangel/Hardcore-SK#1781]
https://i.imgur.com/p8W5Zuw.jpg

Ever since installing the latest version (after the recent Rimworld update), I have been getting this issue sporadically. When hovering an object, the UI window will appear but then never disappear. This makes multiple windows "stick" to the screen and are unable to be removed.

Log File:
[output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/3243703/output_log.txt)

**Comment by sidfu** [comment]
the error is from survial tools. for now if it happens try to take and destory any tools under the cross hairs as the might have bugged

**Comment by masakitenchi** [comment]
Closed as too old
