### ISSUE TITLE
Неправильная колонна.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1784]
Вместо стены можно ставить колонны, для поддержки потолка и украшения. Но, в отличии от стены, можно становиться прямо на неё.

**Comment by semareset** [comment]
так и задумано

**Comment by SetAriman** [comment]
А, так это волшебная колонна. Так надо было и писать в описании. :( А то игра вроде про реализм.

**Comment by semareset** [comment]
Реализм....хм.... погоди, сейчас механоида своего домашнего выпущу погулять и мы обсудим детали.

**Comment by SetAriman** [comment]
Механоид это реализм. "Злые роботы объявили войну. Сухопутные жители встревожены." А волшебные колонны и магические животные - нет.

**Comment by PigQuark** [comment]
реализм, не реализм, а колонну надо бы уже давно исправить.. проходная колонна - это не "задумано", это дичь просто ), далёкая от волшебства.

**Comment by ronekarleone** [comment]
Если колонна будет не проходной, то это будет стена.
В реальности колонна может быть сильно узкой, и можно будет пройти, обогнув ее. Также она может быть какой угодно формы, хоть в форме арки, тогда можно пройти под ней. Так что все вполне корректно.

**Comment by SetAriman** [comment]
Некорректно. Это не арка. (Колонны и арки это вообще две большие разницы.) Это не декоративный прутик. (Хотя даже он будет мешать движению и замедлять его.) Это **несущая** колонна. Мощная и объёмная. Держащая любой потолок на большой площади. Де-факто это декоративный аналог несущей стены.

**Comment by masakitenchi** [comment]
Closed as too old
