### ISSUE TITLE
Избыток текста.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1786]
С новой системой инструментов, в правой информационной панели на экране возник избыток текста. Периодически оповещения не вмещаются и просто накладываются друг на друга. Предлагаю оповещение "Поселенцы нуждаются в инструменте" заменить хотя бы на "Нужен инструмент" - это сэкономит целую строчку. В идеале в моде была бы полезна опция не выдавать оповещения о скорой поломке инструмента и о его необходимости - они тупо без необходимости занимают нужное место. Ни кто же не напоминает, что у пешки скоро окончательно испортится презерватив или что ей нужна пушка получше.

**Comment by skyarkhangel** [comment]
В настройках мода, добавлена возможность отключить оповещения.

**Comment by masakitenchi** [comment]
Closed as too old
