### ISSUE TITLE
Плащ Интерактор

### ISSUE THREAD

**Issue by Arjuna75** [skyarkhangel/Hardcore-SK#1789]
Плащ Интерактор теперь только покупать? 
А вообще, много вещей пропало из Гипер-портняжного стола.
Это ошибка или так задумано?

У меня стоит майская сборка, но и в версии 2019.06.08 тоже самое.

**Comment by TlepshSmither** [comment]
Нет, не ошибка, Их выпилили по просьбе какого-то стримера. Мол, барахла меньше будет. По факту - испортили самую идею Римки.
Надеюсь, вернут через полгода.

**Comment by Arjuna75** [comment]
Эх... Лучше бы выпилили что-то другое. Какую-нибудь средневековую одежду (плащи, пуховики и т.п.). А то развился по технологиям до Гипер-портняжного стола, а выяснилось, что и крафтить то нечего.

**Comment by TlepshSmither** [comment]
Лучше ничего не выпиливать, т.к. всё это барахло в разное время нужно, ради отыгрыша или ради плюшек. Ту же Пустынную Мантию убрали из крафта и теперь нельзя норм играть в пустыне. Нафига? Стример так сказал. 
А барахло выпилили только из крафта и теперь можно вообще им не заниматься, зачем? Есть же ремонтный станок и стирка.
Римка = разнообразие.

**Comment by SetAriman** [comment]
Разнообразие разнообразию рознь. Нужен баланс. А не, к примеру, 10 видов одних только трусов, ибо это типа "разнообразие" и "отыгрыш".

**Comment by Skippeer12** [comment]
В дискорде, в канале #Patches
Есть файлик, который включает обратно весь крафт одежки, его надо закинуть в соответствующую папку с модом и можно крафтить сколько влезет. Файлик за 15 февраля, 2019 года
![image](https://user-images.githubusercontent.com/18488106/59561423-bc138c00-9028-11e9-841b-24150385245b.png)

**Comment by Arjuna75** [comment]
Спасибо! Вот только архив не открывается. Ни WinRAR ни 7-Zip его не могут открыть

**Comment by Zim777** [comment]
У вас устаревшие версии программ. Ставьте WinRar v5.5

**Comment by TlepshSmither** [comment]
А вы случайно не знаете точно такого же файла, который возвращал бы оружие, которое выпилили из крафта?

**Comment by Steklowata** [comment]
Нет новостей, пилит ли кто-нибудь оружие и броню, имевшиеся в В18 обратно в 1.0?

**Comment by Zim777** [comment]
Многое есть, но оно просто не доступно для крафта - квесты, торговцы, рейдеры, руины - хватит быть хикикомори. 
Часть оружия в ребалансе,  возможно что-то новое завезут, что то уберут, что-то подправят и тд.

**Comment by masakitenchi** [comment]
Closed as too old
