### ISSUE TITLE
Иногда ломается вода в гигиене

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1791]
https://steamuserimages-a.akamaihd.net/ugc/796489360408120754/EF900B9308B5CC58BE60053408581785FF09699C/

Было бы еще не плохо постройки гигиены сгруппировать, а то там ппц спам в панеле строительства.

**Comment by murmax** [comment]
Это из-за Prison Labor. После установки римфеллера, он начинает предупреждать, что Prison Labor похерил сейв, перезагрузитесь. После перезагрузки (того же сейва) как правило все норм.
