### ISSUE TITLE
Стабильность версии\вайпы.

### ISSUE THREAD

**Issue by OpacareAngelus** [skyarkhangel/Hardcore-SK#1792]
Насколько стабильна версия?
Планируются ли какие-либо критические изменение в дальнейшем, из-за которых сохранения могут слететь?

**Comment by TlepshSmither** [comment]
А более умного вопроса не нашлось? Здесь пишут об ошибках или багах. С такими вопросами лучше в группу вк)

**Comment by OpacareAngelus** [comment]
Иногда здесь просто пишут свои размышления или задают вопросы. Группа ВК и офф сайт чуть меньше чем мертвые. Вот мы и тут.

**Comment by TlepshSmither** [comment]
ага, и тебе на эти вопросы отвечают. как я заметил по ветке.

**Comment by Skippeer12** [comment]
Если почитать анонсы в дискорде, то можно считать это концом, возможно будут какие либо минимальные изменения баланса/механик/т.п.
Но сам римачь уже не в бете, так что и сборку наверняка перестанут серьезно обновлять, я не разработчик конечно и знать наверняка не могу.

**Comment by OpacareAngelus** [comment]
И на том спасибо. Уже хоть какая-то информация для меня :)

**Comment by skyarkhangel** [comment]
Работы и обновления конечно же будут.

**Comment by OpacareAngelus** [comment]
Спасибо за ответ :)
Насколько критичными они могут быть? Я имею ввиду, может ли возникнуть ситуация, в которой придется начинать новую колонию, потому что старое сохранение перестанет быть совместимым?

**Comment by masakitenchi** [comment]
Closed as too old
