### ISSUE TITLE
Медицинское оборудование

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1793]
Мед лампа и плазменный шар (полагаю, лампа лекаря тоже) дают сто света, что позволяет дешево гидропонить.
Древние и обычные инструменты хирургии не исключают друг друга. Лампы тоже.
При этом мойка и монитор жизненных показателей исключают друг друга, хотя логики я в этом не вижу.

**Comment by skyarkhangel** [comment]
Предлагаю перебалансировать затраты по энергии.

**Comment by TlepshSmither** [comment]
Чтобы нормально освещать ферму нужно 1000 энергии. Если повысить цены на медлампы - станет тупо не выгодно их ставить, т.к. затраты не покроют расходы и придётся ставить неудобную в некоторых местах лампу для фермы. 
С  медлампами можно хоть продольные фермы, хоть треугольные ставить. Не гробьте этот способ.

**Comment by hadaev8** [comment]
Может поставить лампам 90 света? Тогда это будет как стеклянная крыша.

**Comment by Skippeer12** [comment]
На мед.лампы нужны немножко продвинутей детали, чем на лампу для фермы, всё это сводится к тому что ферму на мед.лампах можно построить только после момента как ты исследовал нефтеперегонку (или очень удачного рейда в руинах). Что как бы не выгодно со стороны получение овощей/фруктов, так как лампа для фермы тупо дешевле в несколько раз.

Не уверен что 90% света дает баф на манипуляцию и передвижение как это делает 100%. Но точно сказать не могу, давненько не играл.

**Comment by hadaev8** [comment]
Да, баф только на 100%.
Что странно.
Мне что, ставить в мастерские светолампы?

**Comment by Skippeer12** [comment]
> Да, баф только на 100%.
> Что странно.
> Мне что, ставить в мастерские светолампы?

Вообще ведь голографичкеские ячейки, очень советую.

**Comment by masakitenchi** [comment]
Closed as too old
