### ISSUE TITLE
Herbal Medicine is Useless

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#180]
Herbal Medicine is useless when starting out due to crafting imbalances.  It requires paraffin (extracted from crude oil), which is fairly high in the tech tree.  This needs a major fix as medicine can't be used by anyone that is starting as a tribe.

Herbal medicine is the base medicine and the only medicine neolithic tribes have access to.   This form of medicine should have a co-ingredient & alternative ingredients that are easy to get and does not rely on growing or purchasing it.  I would recommend using clay as a secondary ingredient as it can be used to create a healing potices that are used in real life for its healing properties.

Potices can also be made from teas, potato's, certain herbs, minerals, salts and fruits. 

I would also recommend adding potices as it's own type of medicine for the very reasons above.  If you don't start out with medicine or herbs, and don't have the abilty to extract crude oil (beyond neolithic technology) then you are shit out of luck.  The poltice would solve this issue. 

http://www.healing-from-home-remedies.com/make-a-poultice.html
http://www.eytonsearth.org/clay-poultice-infection.html
https://en.wikipedia.org/wiki/Poultice
http://shimfarm.blogspot.com/2011/06/benefits-of-green-clay.html

![screenshot 30](https://cloud.githubusercontent.com/assets/16742086/18030785/ee9e882a-6c93-11e6-8be6-45572dc98bd5.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/16742086/18030786/eea5a16e-6c93-11e6-879e-9329e11886c9.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/16742086/18030787/eea7c16a-6c93-11e6-9c0e-3f5fa4db2b86.png)
![green clay poultice](https://cloud.githubusercontent.com/assets/16742086/18030839/85506aa8-6c95-11e6-93e7-0ae30d76c1de.JPG)

**Comment by Jalordon** [comment]
There's medicinal mushrooms (glowshrooms) that work as early game medicine, though I will agree that they feel too sparse in amount to use without micromanagement for diseases and surgeries.

**Comment by Tyroki** [comment]
Gonna have to agree.

**Comment by zakhad** [comment]
Yup also agree, some kind of alternative would be nice than paraffin, Glemcaps are okay but far too sparse considering how generally speaking easy they are to cultivate early game they should be a lot lower down in the tech tree, and all you'd need is the raw mushroom turned into spores or seeds to grow which are growing anywhere you've dug out.

**Comment by justarandomusername** [comment]
Agreed aswell, usually I just try to micro manage the 25 starting medicine as much as possible but they run out every single time before I can get into any proper medicine crafting.

**Comment by harchschoolboy** [comment]
I think it can be solved if someone add beehives where you can gather wax as natural component of herbal medicine.
I don't say about all of this beekeeping stuff like like honey, bees, and crops pollination right now.
Just wild beehives.

**Comment by jnkyacc** [comment]
Replace paraffin to ash for herbal meds.

**Comment by skyarkhangel** [comment]
Ok. reworked.
