### ISSUE TITLE
Пешка не может заниматься "ремеслом" если в инвенторе есть кирка

### ISSUE THREAD

**Issue by surabujin** [skyarkhangel/Hardcore-SK#1803]
Сегодня переключился с ветки develop на master, загрузил сохранение уже имевшееся - настроил инструменты в назначениях... Вскоре выяснилось что все задачи по "ремеслу", "портному" и "кузнецу" не выполняются. Выбрав пешку и попытавшись послать ее заниматься указанными действиями - при правом клике по верстаку не появляется менюшка выбора действия.

Проблема проявилась только для части пешек. После серии экспериментов удалось выяснить что проблема проявляется если в инвентаре(не важно в руках или нет) присутвует кирка.

Версия сборки в которой было сделано сохранение: d1c85e2c38a9efbcbfbc96876ab4ccf43397fe43
Версия на которую обновился: 5f77d0b7b4c1e15ce6ba3c633cdf75e7789b9c0d

**Comment by skyarkhangel** [comment]
Убедитесь что у вас новая игра, с апдейтом на инструменты. Могут быть баги со старыми сейвами.

**Comment by masakitenchi** [comment]
Closed as too old
