### ISSUE TITLE
Пешка берёт миллиард молотков и переключает их при работе

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1805]
Пешка берёт миллиард молотков и переключает их при работе тем самым ничего не могя сделать ( да да могя )...
![image](https://user-images.githubusercontent.com/47127651/60053576-dca2ac80-96e0-11e9-874a-e2db856a4e0f.png)

**Comment by skyarkhangel** [comment]
Как воспроизвести? У меня не получается, более того, если инструмент подходит по типу для работы, переключения не должно происходить в принципе.

**Comment by Pepelnica1488** [comment]
Не знаю мб потому что они с разными эффектами infused?

**Comment by arznaar** [comment]
У меня воспроизводится то же самое без сторонних модов - только rimworld из стима + hardcore SK поставленный инсталлером.

Происходит не часто. Замечал с киркой (очень редко) и с молотком на станках.
Воркэраунд - заставить пешку выкинуть лишние инструменты и все становится хорошо - пешка не стремится набрать их обратно.

(через пару часиков добавлю сюда конкретные версии и сейв)

**Comment by surabujin** [comment]
У меня похожая проблема - у пешки в инвенторе есть "ручной топор" и "боевой топор" она пытается срубить дерево и в процессе постоянно переключается между этими двумя топорами и прогресс рубки сбрасывается.

**Comment by Pepelnica1488** [comment]
@surabujin и это тоже...вчера увидел когда играл норбалами

**Comment by masakitenchi** [comment]
Closed as too old
