### ISSUE TITLE
Набор инструментов "конфликтует" с набором оружия

### ISSUE THREAD

**Issue by surabujin** [skyarkhangel/Hardcore-SK#1806]
Новая колония, сборка 33cd82dc863cc7fe00865c14dbaba1de7ba0dc2e

У пешки в наборе инструментов назначен молоток, но в наборе вооружения молотка нет (есть короткий лук, стрелы и дубина) - пешка не берет молоток со склада, при принудительном "назначении" молотка она его перет и сразу кладет назад. Если запретить молоток на всех складах - она его выбросит не сразу а после "первого применения".

Если назначить "ничего не выбрано" в наборе оружия - пешка подбирает молоток и работает с его помощью.

ЗЫ На сколько я понимаю набор инструментов не задумывался как дублирующий для набора оружия... или я не правильно понимаю и инструмент должен быть назначен и в наборе инструментов и в наборе оружия?

**Comment by Pepelnica1488** [comment]
двачую,этот бар реально бесит приходится вручную все наборы составлять

**Comment by masakitenchi** [comment]
Closed as too old
