### ISSUE TITLE
Настенная лампа вс настенный фонарь

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#1807]
Фонарь требует меньше энергии и светит не так далеко, как лампа.
Но он стоит дополнительно 2 пластика и вроде как является более продвинутой вещью.

Оба предмета открываются технологией аккумуляторы, которая открывает кучу всего, например, продвинутый стол исследований.
Считаю, технологию надо переименовать или добавить новые, а эту оставить только под аккумуляторы.

**Comment by Pepelnica1488** [comment]
"важнейшая" проблема васяна на данный момент

**Comment by Kiriharas** [comment]
к чему такие грубости, вполне себе тянет на рабланс (другое дело, что сейчас, возможно, другие проблемы важнее)
