### ISSUE TITLE
Очень частое отравление пеммиканом

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1808]
Не понятно зачем он нужен если травишься им почти так же как какими нибудь ЯБЛОКАМИ
(вы ведь часто травились яблоками правда?)

**Comment by Skippeer12** [comment]
Мне кажется это зависит из каких ингредиентов он был приготовлен.
Если из яблок, то какого качества были яблоки, если у них уже истек срок годности и на них написано что они гниют, то лучше их просто выбросить, а не пихать в еду. Я так же наступал на эти грабли, пока не понял в чем проблема.

**Comment by Kiriharas** [comment]
у пеммикана шанс отравления (2%, кажется), как и у другой сырой еды (в т.ч. яблоки, ага) ради баланса, т.к. скрафтить просто и лежит долго

**Comment by Pepelnica1488** [comment]
@Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт

**Comment by Kiriharas** [comment]
> @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт

ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?

**Comment by Pepelnica1488** [comment]
> > @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт
> 
> ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?

только опасная еда и всё,у меня мастер повар в перчатках с ножом и на кухне всегда чисто это не влияет на то что еда травит

**Comment by Kiriharas** [comment]
> > > @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт
> > 
> > 
> > ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?
> 
> только опасная еда и всё,у меня мастер повар в перчатках с ножом и на кухне всегда чисто это не влияет на то что еда травит

ну, значит пеммикан не очень подходит для регулярного питания, скорее как несгораемый запас на чёрный день, или для путешествий (для чего он и нужен)
а так - 2-4 дня это немного, у меня обычно 20-30% колонии нонстоп всё блевотиной заливают, пока нормальную кухню не построю

**Comment by Pepelnica1488** [comment]
@Kiriharas если он для путешествия тогда это будет худшее путешествие с постоянно блюющими замедляющими караван пешками

**Comment by Zim777** [comment]
А вы не пробовали заготавливать для путешественников нормальную пищу?
Что-то типа сухофруктов, разной медленно портящейся еды типа жареного картофеля, кокосов и тд, на худой конец комбикорм, солонина?

**Comment by Skippeer12** [comment]
> > > @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт
> > 
> > 
> > ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?
> 
> только опасная еда и всё,у меня мастер повар в перчатках с ножом и на кухне всегда чисто это не влияет на то что еда травит

Если пишет опасная пища, то оно было приготовлено из испорченных продуктов.

**Comment by Pepelnica1488** [comment]
> > > > @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт
> > > 
> > > 
> > > ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?
> > 
> > 
> > только опасная еда и всё,у меня мастер повар в перчатках с ножом и на кухне всегда чисто это не влияет на то что еда травит
> 
> Если пишет опасная пища, то оно было приготовлено из испорченных продуктов.

вот зачем ты пишешь то чего не знаешь? пеммикан из prepare carefuly был между прочим и так же травятся

**Comment by ynemo** [comment]
Всегда считал, что у пеммикана по дефолту 2% на отравление. И эти 2% никак не уменьшить

**Comment by Pepelnica1488** [comment]
начал колонию в итоге СРАЗУ отравились 2 бомжа ТААААК клааааассноооо

**Comment by Skippeer12** [comment]
> > > > > @Kiriharas играл за норбалов 2 катки и каждые 2 - 4 дня кто то постоянно травится и блюёт
> > > > 
> > > > 
> > > > ну тащем то ещё многое зависит от повара, на начальном этапе колонисты обычно направо и налево из за плохих условий готовки блюют. При отравлении обычно пишется причина (опасный тип еды/ плохой повар), у тебя что показывало?
> > > 
> > > 
> > > только опасная еда и всё,у меня мастер повар в перчатках с ножом и на кухне всегда чисто это не влияет на то что еда травит
> > 
> > 
> > Если пишет опасная пища, то оно было приготовлено из испорченных продуктов.
> 
> вот зачем ты пишешь то чего не знаешь? пеммикан из prepare carefuly был между прочим и так же травятся

А вот это уже интересно. Но давал бы ты эту информацию сначала, а не в конце дискусси, было бы замечательно.
Без определенного мода, пешки любят складывать всю еду в одно место, в котором оно стакается и получает все те дебаффы которые были у блюда которое лежало там изначально.
Например, у тебя  есть обычное блюдо из мяса животного и овощей, а на складе лежит блюдо из человеченки или мяса инсектоидов, то не важно было ли изначально приготовленное блюдо хорошим, оно получит дебаф к настроению потому что в ингредиентах будет писать что там есть мясо инсектоитов или плоть человека. Наверное довольно складно описал это, но надеюсь ты поймешь.

**Comment by masakitenchi** [comment]
Closed as too old
