### ISSUE TITLE
sentry heavy turret don't shoot 

### ISSUE THREAD

**Issue by WAPPAP** [skyarkhangel/Hardcore-SK#1809]
they are just aiming target endlessly. and dont shoot

**Comment by Schaf-Unschaf** [comment]
Are they set to Aimed Shot? Try if it works with Snapshot. Noticed the same behaviour with other turrets behind embrasures only aiming when on Aimed Shot.

**Comment by Szara-ManOfHonor** [comment]
This can also happen when the turret doesn't actually have a line of fire on the target. Such as if there are objects covering the target, if there are trees in the way; or if it is a small target behind chunks, or close to the embrasure.

**Comment by WAPPAP** [comment]
no, i was playing tundra terrain, so there is no obstacle to cover enemy, and i can't switch aim mode. i clicked aim shot, but it doesn't work. and i destroyed parapet that cover heavy sentry turret, but it's same.

**Comment by masakitenchi** [comment]
Closed as too old
