### ISSUE TITLE
Unless you start with seeds you aren't growing anything but potatos.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#181]
In the wild you would be able to find fruits, vegetables and herbs.  With these findings you have the ability to eat, create medicine and grow more with the seeds you now have.

With this mod, unless you start with seeds or you get lucky with a seed carrying trader you can only grow potato
s.  

Add wild variations of fruits, fruit trees, herbs and other greens adds a small balances to the game.  This would allow the player to gather these items and start to rely on the world for seeds instead of a random trader.  

![edible_and_useful_wild_plants-l](https://cloud.githubusercontent.com/assets/16742086/18030881/82d97f98-6c96-11e6-87db-3740bbfa3c20.jpg)

**Comment by justarandomusername** [comment]
If im not mistaken you can get seeds from stuff via Composter. But I do agree that you should be able to find more plants in the wild and/or an easier way to get some seeds.

**Comment by Tyroki** [comment]
I wasn't able to set up potatoes until a few traders in. I had to survive a crashlanded run (with actual crash) through hunting alone.

It's a bloody tough experience.
Not that I don't want the pack to the hard (It's great being hard), but this is a little ridiculous.

**Comment by tim0901** [comment]
I believe there are types of berry that grow on the bushes around the map, but I agree possibly having some other way of getting seeds - or alternatively increasing the likelihood of seeds turning up with traders - could be a nice change

**Comment by Tyroki** [comment]
Those have been giving you seeds?

Lucky. Haven't found a single seed :\

**Comment by tim0901** [comment]
No they haven't, but they're an alternative food source that can probably go through the composter to get seeds from

**Comment by zakhad** [comment]
Maybe like for some to spawn on the map albeit rarely and there's a small chance like 1-5% you'll get a seed? I'd like to see something like that so you don't depend on traders nervelessly

**Comment by skyarkhangel** [comment]
Now we use NotFood's seedplease, which allows wild plants seeds.
