### ISSUE TITLE
Rimworld Cities Implementation request

### ISSUE THREAD

**Issue by Sonsalt** [skyarkhangel/Hardcore-SK#1810]
A procedural city generator mod for RimWorld.
https://github.com/rvanasa/rimworld-cities

This mod adds a serious amount of new world map events based on large cities to the game.

**Comment by skyarkhangel** [comment]
Cities mod in active development now, I think later.

**Comment by Sonsalt** [comment]
@skyarkhangel The development has now stabilized. 

Regarding the compatibility, the main issue is related to is madeFromStuff but stuff=null. Assigning default.

I have been trying to compare the implementation to Ruins, but it appears to be different. 

If you can provide me with an example of how to make all the benches etc compatible, patching the GenStepDef then I can do the rest.

**Comment by skyarkhangel** [comment]
its not a serious bug, like notification that spawned building require stuff, but missed and then game usually sets steel as default.

**Comment by masakitenchi** [comment]
Closed as too old
