### ISSUE TITLE
now i realize all turret is broken

### ISSUE THREAD

**Issue by WAPPAP** [skyarkhangel/Hardcore-SK#1812]
all turret don't shoot

**Comment by NoManColonies** [comment]
same here

**Comment by Schaf-Unschaf** [comment]
That's strange. I'm sitting on the pre-survivaltools version and my turrets (manned and sentry) are working just fine.

**Comment by skyarkhangel** [comment]
Seems all fine for me on latest update. Checked some manned and unmanned turrets and artillery.

**Comment by masakitenchi** [comment]
Closed as too old
