### ISSUE TITLE
Очередь задач у пешки сбрасывается при автопереключении инструмента

### ISSUE THREAD

**Issue by surabujin** [skyarkhangel/Hardcore-SK#1818]
Задачи для пешки добавленные вручную (с зажатой кнопкой shift) сбрасывается когда пешка сама переключает инструмент нужный для выполнения задачи.

Порядок действий
- у пешки в руках нож
- у пешки есть в инвентраре ручной топор
- включаем паузу
- выдаем пешка 3 задачи по рубке деревьев
- выключаем паузу
- пешка начинает движение к первому дереву
- "берет" в руки топор
- очередь задач сбрасывается - пешка отправляется "работать" по своим приоритетам.

Опция "оптимизировать инструменты" в surviving tools отключена.

Версия bdc22069dcd038db92d77419b250e9e78d43b5ac

**Comment by Pepelnica1488** [comment]
да такое есть и без шифта тоже самое если переключает то идёт заниматься своими делами приходится силой затаскивать иногда

**Comment by skyarkhangel** [comment]
Исправлено в след. апдейте.

**Comment by Pepelnica1488** [comment]
не исправлено,дал пешке задачу на разбор капсулы она взяла молоток и пошла по своим делам

**Comment by masakitenchi** [comment]
Closed as too old
