### ISSUE TITLE
Меняются названия предметов после обновления от Steam

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1819]
После каждого обновления игры стимом часть ингредиентов меняют названия.
Например, при разделке волка я недавно получил мясо и кожу слона.
В предыдущих обновлениях при разделке оленей и маралов получал мясо муффало. Это лечиться переустановкой модов Hardcore SK на новую версию, но можно это как-то исправить?

**Comment by skyarkhangel** [comment]
скорее это проблема с переводом. В папке Core обновляйте папку с русским языком
