### ISSUE TITLE
You should'nt have to rely on a composter or Biorefinery to get seeds.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#182]
If I were to pick up an apple from a tree I wouldn't need to take the apple to a composter or Biorefinery to get seeds.  

Rimworld is a game, but with this modpack getting seed packs is extremely difficult unless you actually edit the game and start with them.  Instead of needing these machines, researching agriculture should allow the ability to not only grow these vegetables/herbs/fruits , but be able to extract seeds from them too.

But how can we grow things unless we get them from seed packs?  So far the only way it to get them from traders or edit the game so we have them from the start.

There is a simple way to fix this,  simply add vegetables, fruit trees and herbs to the game world.  We already have strawberry bushes but why is that the only thing that is growing in the world?  If we have so many random abandoned buildings then there should be overgrown vegetable and herb patches.  There should be random fruit trees and bushes along with herbs and vegetables adding to the map to add a bit more balance and realism to the game.  Animals don't just rely on grass to eat and neither should the pawns in rimworld.

![apple-021](https://cloud.githubusercontent.com/assets/16742086/18030894/2d0799f0-6c97-11e6-97c6-82dcf7653296.jpg)
![dscc_0366](https://cloud.githubusercontent.com/assets/16742086/18030898/39cdf512-6c97-11e6-955d-8c873fb0cb5f.JPG)
![download 1](https://cloud.githubusercontent.com/assets/16742086/18030913/112d03f4-6c98-11e6-929c-c5262716c5f1.jpg)
![download 2](https://cloud.githubusercontent.com/assets/16742086/18030914/130eacae-6c98-11e6-97d4-2c4646476f1a.jpg)
![download 3](https://cloud.githubusercontent.com/assets/16742086/18030915/14599006-6c98-11e6-8077-9b05918ab761.jpg)
![download 4](https://cloud.githubusercontent.com/assets/16742086/18030916/15dfd692-6c98-11e6-8a8e-9733b6230836.jpg)
![download 5](https://cloud.githubusercontent.com/assets/16742086/18030918/1780a238-6c98-11e6-9cc0-04b0a9d613f7.jpg)
![100_6373](https://cloud.githubusercontent.com/assets/16742086/18030920/190f15e4-6c98-11e6-80a1-2c876b189210.jpg)

**Comment by jaynus** [comment]
@skyarkhangel Is this a feature you would accept? I have added this in my local game, I can create a pull request if its something that would be included. I have added a very small chance of some plants to spawn via the Biome configs based on the climate.

**Comment by skyarkhangel** [comment]
Closed. Old version
