### ISSUE TITLE
Ближний бой не работает.

### ISSUE THREAD

**Issue by TlepshSmither** [skyarkhangel/Hardcore-SK#1822]
Обнова сегоднешняя (06.07.19) 
Стартанул за норбаллов - пантера захотела сожрать одного - атаковал всеми сразу - в итоге атаковал только ОДИН норбалл. 
при попытке атаковать сразу 4 норбаллами 1 пантеру - они просто ходят за ней.

**Comment by Pepelnica1488** [comment]
ля только захотел стартануть

**Comment by skyarkhangel** [comment]
Должно так-то работать, проверь еще.

**Comment by Pepelnica1488** [comment]
боевой топор с мелким баклером почему то больше не дерется,хотя раньше дрались,как только выкинул баклер начался бой стандартно

**Comment by skyarkhangel** [comment]
ах ясно, не доделанная механика двуручного оружия.

**Comment by masakitenchi** [comment]
Closed as too old
