### ISSUE TITLE
Религия дает -20 настроения

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1824]
После возведения алтаря религия дает -20, если долго не проводить богослужения.
До возведения такого дебафа нет, что уже не последовательно.
Также возникает проблема, что пешки в походе не могут делать богослужения и постоянно под дебафом -20. К слову у крестоносцев не было такой проблемы в крестовом походе :)
Надо либо добавить переносной алтарь, либо, что звучит логичнее, заменить дебаф от отсутствия на баф от наличия богослужения.

**Comment by TlepshSmither** [comment]
На данный момент легче просто не ставить этот мод. 
Верующий человек УЖЕ ИМЕЕТ БАФ от того, что он верует! Так у нас в жизни тысячи лет было!
Мои предложения : 
1) Баф от НАЛИЧИЯ РЕЛИГИИ (+7) к настроению и возможность тихой молитвы у себя в спальне. 
2) Дебаф в отношениях между людьми, если разные религии. 
3) Дебаф убирается, если у пешки есть перк "веротерпимость" (описание: "Какая разница, какой человек веры? Главное - его поступки!") (это позволит сохранить семью, если религии разные)
4) При наличии богослужения баф выше (+ 15), но он не долгий, 12 часов.
5) При наличии Алтаря и Храма вообще, тоже идёт баф (+3) от наличия.
6) Дебаф от отсутствия храма или алтаря (- 3). 
 
Пока-что от такой важной штуки толку - 0. Поэтому стримеры (которых знаю) выключают этот мод, да и я тоже.

**Comment by ak72ti** [comment]
Лучшим вариантом будет исключить мод из списка тех что включен по умолчанию, как это сделано с заборами, зомби, а так же некоторыми другими опциями. Мод на религию просто отвратительно реализован.

**Comment by Pepelnica1488** [comment]
та норм мод просто почему бы не добавить опцию что бы верун сам у себя под шконкой молился а не требовал алтарь + книгу + реликвию

**Comment by ronekarleone** [comment]
Я бы еще понизил вероятность обращения в религию. А то она щас как чума расходится. За год заразились все колонисты. При этом, чем больше больных, тем быстрее распространяется.

**Comment by masakitenchi** [comment]
Closed as too old
