### ISSUE TITLE
Замедление времени при путешествиях

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1825]
Если есть пешки, путешествующие по карте, то в редких случаях происходит сильное замедление игры. Пока не понял, чем это вызвано, просадкой FPS или сбросом игры до скорости х1 (при этом внизу написано, что х4).
Если путешествующую пешку посадить в лагерь, то скорость тут же восстанавливается.
Если снова отправить на карту, то замедление может повторно и не появиться.

**Comment by ak72ti** [comment]
Замедление игры происходит когда у пешки нет подходящей еды, или в качестве еды используется приправа, либо еда что пешке не назначена, так же замедление усиливается на колличество пешек. Важно отметить что оно проходит когда у пешки есть что поесть либо если она не требует еды. По крайней мере так у меня.

**Comment by masakitenchi** [comment]
Closed as too old
