### ISSUE TITLE
у хищников случается непонятная потеря крови

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1829]
![image](https://user-images.githubusercontent.com/47127651/60978036-2920f580-a339-11e9-9720-780de83ec428.png)

пока что заметил 2 случая у тигра и терраморфа

**Comment by ronekarleone** [comment]
Хищники быть ранены в процессе охоты на животных, но самостоятельно залечивают раны. 
Так как раны неглубокие, но их много, происходит большая потеря крови, но быстрое залечивание ран. В итоге выглядит ка потеря крови без ранений.

**Comment by masakitenchi** [comment]
Closed as too old
