### ISSUE TITLE
Mining buildings collapse due to 'no support'

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#183]
Mining rigs tend to collapse instantly saying that support was removed, Noticed for both mining rig and advanced mining rig. 

I never noticed this behavior before so I don't know if it was always there and I got lucky that it never collapsed on me or if this was an unintended change, since briefly reading the commit notes I saw no mention of extractors collapse.

edit: Figured it out more, It allows placing the mine extractor off center of the mineral deposit but the mine instantly collapses into a few slag chunks (huge resource loss) when it completes. Unsure if this will be resolved because of A15 drilling as mentioned in a previous mining rig issue.

**Comment by skyarkhangel** [comment]
Fixed on a16.
