### ISSUE TITLE
Сбор песка/торфа/етк не в разделе шахтерство.

### ISSUE THREAD

**Issue by A1EE** [skyarkhangel/Hardcore-SK#1838]
На скорость сбора песка/торфа/етк уже давно влияет навык шахтерства, тем не менее эти работы до сих пор остаются в категории "носильщик", что абсолютно не логично и мешает(буквально каждой пешке приходится настраивать эти пункты отдельно, чтобы она или не занималась этим, тк навык шахтерства низкий, или наоборот, занималась в более приоритетную очередь, чем переноска).

Хорошо бы перенести эти работы хотя бы в раздел шахтерство, а лучше даже выделить отдельной группой.

**Comment by thghca** [comment]
Всякие задачи по обслуживанию техники типа перезаправки и перезарядки тоже стоит в отдельную категорию переместить.

**Comment by masakitenchi** [comment]
Closed as too old
