### ISSUE TITLE
Colonist wont plant carrot or peach?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#184]
Hi, 
I bought carrot seeds from traders, and i got peach seed from drop pods.
My colonist plant potato, cecropia tree but wont carrot and peach.
When i use developer mode they do harvest them when they are ready. And take seeds and harvest to stockpile.
Any help?

**Comment by tim0901** [comment]
Have you go the technologies required to plant these crops?

**Comment by zoranjoza** [comment]
Yes ofc.

**Comment by Mongoon** [comment]
Check soil fertility (in help) - both carrot and peach require 140% so i guess that's the case.
