### ISSUE TITLE
Стартовые очки можно генерить

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1840]
Есть очень приятный баг, но все же баг.
При старте можно перегенерируя рандомного персонажа выбрать такого, обмундирование и характеристики которого будут стоить намного больше в очках.
Затем перейдя в детальную проработку можно дать ему дешевую по очкам одежду и использовать эти очки для более тщательной проработки персонажа.
По опыту, разброс в очках бывает от 2000 до 4000. Бывало я мог сгенерить персонажа в 4500 очков, что позволяло в тщательной проработке дать ему все скилы на большие огоньки и значения 10-15.

**Comment by A1EE** [comment]
Ну такое. Ты либо используешь те очки, на сколько сгенерировало в первый раз, либо сам себе определяешь потолок(например как при твоих крутых пешках), либо не заморачиваешься и делаешь анлимит.
Собственно, вместо того, чтобы париться перегенарицией - можешь просто убрать галку.

**Comment by masakitenchi** [comment]
Closed as too old
