### ISSUE TITLE
Баг с расчетом стоимости материалов при старте

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1842]
При старте во время тщательной проработки стоимость одежды меняется рандомно при смене материала. Например, если штаны из кожи стояли 200 очков, то пощелкав по исходным материалам и вернувшись обратно на кожу, можно обнаружить что они стоят 2000 или наоборот 50 очков. Подозреваю, что зависит от предыдущего материала.

**Comment by A1EE** [comment]
Думаю не баг, просто при каждой смене материала(или круга?) меняется качество вещи и его эксклюзивность.

**Comment by skyarkhangel** [comment]
Its PrepareCarefully, need to contact its author. We just using this mod for hcsk.

**Comment by ronekarleone** [comment]
> Думаю не баг, просто при каждой смене материала(или круга?) меняется качество вещи и его эксклюзивность.

Хм... Похоже на правду.
