### ISSUE TITLE
не локализуется исследование

### ISSUE THREAD

**Issue by Kramolnikk** [skyarkhangel/Hardcore-SK#1846]
не локализуется исследование:
<defName>ComponentAssembly</defName>
<label>3D Printing</label>
<description>Unlocks the Electric Assembling Bench - an electric table for the assembling of components, wires, mechanisms, and advanced mechanisms and basic hand tools.</description>

**Comment by skyarkhangel** [comment]
Fixed with changed defname "ComponentAssembly" to another.
