### ISSUE TITLE
BodyPart health duplication.

### ISSUE THREAD

**Issue by NoManColonies** [skyarkhangel/Hardcore-SK#1847]
When install any body part(s) that have it more than 1 of it alternative part on pawn body i.e. hand ,arm ,leg ,eye ,ear ,etc. if the new prothetic increase that body part hit points it will increase on all body part of it alternative. For example installing simple bionic arm on right arm will set hit point of right arm to 90 at the same time will increase hit point on left arm to 90 too even the left arm has nothing installed(Can be observed using dev mode since default body part are hidden without Hediff) although I have not tested for the case when each side of installed body part that both set different max hit point.

**Comment by NoManColonies** [comment]
<img width="1280" alt="Screen Shot 0001-07-17 at 12 11 27 PM" src="https://user-images.githubusercontent.com/38200442/61348806-2a4ba880-a88c-11e9-974e-0cc39d39d26e.png">
<img width="1280" alt="Screen Shot 0001-07-17 at 12 11 31 PM" src="https://user-images.githubusercontent.com/38200442/61348811-2cae0280-a88c-11e9-924e-3ae37c27230b.png">

**Comment by NoManColonies** [comment]
<img width="1280" alt="Screen Shot 0001-07-17 at 12 14 16 PM" src="https://user-images.githubusercontent.com/38200442/61348907-726acb00-a88c-11e9-9ef4-dac34e12f972.png">
Default

**Comment by NoManColonies** [comment]
<img width="1280" alt="Screen Shot 0001-07-17 at 12 17 46 PM" src="https://user-images.githubusercontent.com/38200442/61349060-fb820200-a88c-11e9-863d-d86690722104.png">
<img width="1280" alt="Screen Shot 0001-07-17 at 12 17 49 PM" src="https://user-images.githubusercontent.com/38200442/61349063-fcb32f00-a88c-11e9-8408-0b1b5457f2b5.png">
Default
<img width="1280" alt="Screen Shot 0001-07-17 at 12 17 49 PM" src="https://user-images.githubusercontent.com/38200442/61349068-0341a680-a88d-11e9-8111-3952572d2c57.png">

**Comment by skyarkhangel** [comment]
Yep, I confirmed. So far I do not see solution to solve this bug for now.

**Comment by masakitenchi** [comment]
Closed as too old
