### ISSUE TITLE
Correct tailors loom description to remove "requires power"

### ISSUE THREAD

**Issue by martov1** [skyarkhangel/Hardcore-SK#185]
the tailors loom says it requires power in the description but it does not (and thats awesome, no need for power to sew)

**Comment by jnkyacc** [comment]
Tailors loom - require power. 300w to be precise.
875 commit.

**Comment by martov1** [comment]
oh, it did not have the power UI to turn off and to show power consumption, i have 4.0 (not the lastest github version.)

**Comment by skyarkhangel** [comment]
Fixed.
