### ISSUE TITLE
Неправильный расчет цены продажи

### ISSUE THREAD

**Issue by RHode007** [skyarkhangel/Hardcore-SK#1850]
Если бонус переговорщика больше множителя цена товара уменьшается 

![image](https://user-images.githubusercontent.com/19503512/61394678-54bd5600-a8cc-11e9-9405-12309d9e8bbb.png)
![image](https://user-images.githubusercontent.com/19503512/61394719-70c0f780-a8cc-11e9-9590-8729ce34a1c8.png)
![image](https://user-images.githubusercontent.com/19503512/61395275-b3cf9a80-a8cd-11e9-829b-a56aee0b934f.png)
![image](https://user-images.githubusercontent.com/19503512/61395226-94d10880-a8cd-11e9-9a48-f9158e8ce0b7.png)

**Comment by masakitenchi** [comment]
Closed as too old
