### ISSUE TITLE
Feature request or idea discussion - non violent colonists going berserk

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#1853]
Hey, is it possible to program/code so that  it makes a non violent colonists go berserk when attacked by a animal that's hunting them? Like how mosquitoes go manhunting when they suck blood from a member of the colony. I just it a bit odd how a colonist is quite happy to be eaten alive. 

If you fail to arrest a non violent colonist they will go berserk so it stands to reason being eaten alive would have the same effect lol.

As I don't think it's possible to change a colonists backstory that has incapable of violence to suddenly be capable of such as to find an alternative method such as trait changer mod.

**Comment by Kramolnikk** [comment]
Или убрать впадение в бешенство, на то он и пацифист.

**Comment by masakitenchi** [comment]
Closed as too old
