### ISSUE TITLE
Странный печёный картофель.

### ISSUE THREAD

**Issue by Kramolnikk** [skyarkhangel/Hardcore-SK#1856]
Печёный картофель имеет такую же питательность как и сырой(!) картофель.
Например солёное мясо (солонина) имеет 0.05 -> вяленое 0.15.

P.S. С привлекательностью так и должно быть? Сырой картофель нейтрально, печёный  -4.

**Comment by Pepelnica1488** [comment]
а хлеб с его нереальными полями пшеницы и мизерным урожаем + длительность производства питает ещё слабее чем картопля

**Comment by TlepshSmither** [comment]
К хлебу сыр нужно добавлять, чтобы блюда были имбовыми по питательности. Овцы, лошади, муффало подойдут. Если повезёт - будут коровы по ивенту)

**Comment by Pepelnica1488** [comment]
хлеб сам по себе мегапитательный 1 буханки в день хватит среднему жиробасу 95 кг

**Comment by masakitenchi** [comment]
Closed as too old
