### ISSUE TITLE
mining helmet/ шахтерская каска

### ISSUE THREAD

**Issue by JesusREAI** [skyarkhangel/Hardcore-SK#1857]
шахтерская каска не производит свет, при нажатии правой кнопкой мыши на каске, выбивает красная ошибка (версия 1.0.2282, версия HSK последняя, установил лаунчером)
could not resolve symbol "1_labelshort" for string "Надеть (1_labelshort)"

**Comment by hadaev8** [comment]
Убрали им свет, читай упдейты
