### ISSUE TITLE
Прелдагаю взрывстрелы для баллисты

### ISSUE THREAD

**Issue by PodliKirill** [skyarkhangel/Hardcore-SK#1864]
https://www.dropbox.com/s/2y8x45di5w71gbn/Ballista.xml?dl=0
Файлик в \Mods\Core_SK\Defs\CombatExtended\Ammo\Neolithic
Запилил и протестировал - работает.

**Comment by ronekarleone** [comment]
Предлагаю ЭМИ стрелы для балисты и ЭМИ ядра для катапульты!

**Comment by masakitenchi** [comment]
Closed as too old
