### ISSUE TITLE
Несколько хоперов не работают

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1865]
Если к одному дозатору пасту подключить несколько хоперов (тестировалось на 2), то пешки перестают брать еду из дозатора, хотя хоперы загружены.

PS может можно сделать что-то с тем, что если в хопере осталось меньше минимально необходимого для генерации пасты количества продукта, то пешки меняли продукт на другой?

**Comment by masakitenchi** [comment]
Closed as too old
