### ISSUE TITLE
Major armor bug

### ISSUE THREAD

**Issue by corex1** [skyarkhangel/Hardcore-SK#1866]
The "natural armor" of mutants, (an)droids, etc. don't work, making the android armor upgrades at the android printer useless.
For example battle droids have 200% heat armor, which should make them invulnerable to laser weapons. But when I shot him with a laser gun he received full damage (same for sharp and blunt damage)
![Screenshot (23)](https://user-images.githubusercontent.com/51675665/62568977-51473a00-b88e-11e9-8aa7-b21579468c8c.png)

**Comment by corex1** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/51675665/62569361-c7e43780-b88e-11e9-918d-a202a3d7cbde.png)

**Comment by skyarkhangel** [comment]
ah, yep. Natural armor disabled currently. Need to enable and rebalance some pawns, Mechanoids mostly.

**Comment by masakitenchi** [comment]
Closed as too old
