### ISSUE TITLE
Anyone else noticing manual priorities keeps defaulting to check's instead of numbered priorities.

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#187]
Pretty much what the title says. This is somewhat frustrating because every time I load a save game for any reason and I've not noticed that the priorities have been set back to check's instead of numbers (Why is it no longer remembering? It used to remember regardless of what type of priority setting you choose and it'd stick with it) 

Now Every level 1 medic thinks there the bee's knee's giving that 10-20% medical treatment, over my 14 skilled medic with actual medial gear on that  gives him around +40 medical treatment resulting in over 135% quality treatments without medicine its really frustrating to have people die without you knowing, I'm like why are you getting to extreme at 50%? when you didn't even get to extreme before., he was being treated as i checked, I didn't check who was doing it because I assumed It was still my number 1 priority medic.

**Comment by Vigilence** [comment]
I noticed it for certain things like cooking on the grill.  I think these items don't have the same coding as the campfire which does allow prioritizing.

**Comment by Vigilence** [comment]
Yeah I noticed that too, also the "Home Area" option defaults to on, and the toggle room stats defaults to off every time you load a game.

**Comment by Jalordon** [comment]
Saw on the forums that it may be another CCL bug: https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/issues/171

**Comment by Vigilence** [comment]
Hopefully it gets fixed soon, cause it's really annoying.

**Comment by skyarkhangel** [comment]
Closed. Old version
