### ISSUE TITLE
Баг. Поселенцы подбирают одинаковые инструменты.

### ISSUE THREAD

**Issue by OpacareAngelus** [skyarkhangel/Hardcore-SK#1872]
Собсна, по сабжу. Самое в этом плохое то, что они начинают автоматически переключаться между ними, как между наиболее подходящими. Из-за этого, в итоге, слетает процесс работы (сборки, копки и т.д.). В основном замечал такое за молотком и киркой.

**Comment by Pepelnica1488** [comment]
забей они никогда не пофиксят это

**Comment by Zim777** [comment]
Этот момент, когда это было пофикшено, но кто-то заявляет, что это никогда не пофиксят

**Comment by masakitenchi** [comment]
Closed as too old
