### ISSUE TITLE
Животные и люди жрут соль.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#1873]
Так как это пищевой ингридиент, то считается едой, и даже питательность имеет как у мяса - 0.05. Только вот если логически подумать, даже если просто килограмм соли съесть - это чистое самоубийство. Можно её как нибудь не совсем съедобной сделать?

**Comment by skyarkhangel** [comment]
В конце июля для соли был добавлен статус "не для употребления".

**Comment by masakitenchi** [comment]
Closed as too old
