### ISSUE TITLE
Проблема с рубкой деревьев.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1877]
Сейчас наблюдал. Две пешки рубят деревья, указанные для вырубки при созревании. Обе имеют топоры (инструменты). Но одна пешка рубит киркой, хотя и не против рубить топором, если сменить инструмент вручную. Вторая категорически отказывается рубить топором, потому что уверена, что рубить серпом - лучше.

**Comment by skyarkhangel** [comment]
Переключение на серп вместо топора должно быть исправлено в последнем обновлении.

**Comment by Pepelnica1488** [comment]
не исправлено,они серпом рубят деревья

**Comment by Zim777** [comment]
Если у вас stable(master) ветка, то там исправления нет. Оно в  development ветке
