### ISSUE TITLE
Wierd sounds around base?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#188]
Hi i hear some sounds in my base, like raptors attacking or raptor afk sound. And i even dont have any raptor on map. When i zoom in to some part of my base i hear sound, but nothing is there that  can make that sound.

**Comment by skyarkhangel** [comment]
Reload game?

**Comment by zoranjoza** [comment]
Not helping. I used developer mode and remove whole sector 25x25 i think.
And i notice when i remove everything from one sector then sound stop

**Comment by skyarkhangel** [comment]
Closed. Obscure bug-report.
