### ISSUE TITLE
О возрасте рейдеров.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1880]
Можно как-то подкорректировать минимальный возраст? Как-то странно, когда полноценному рейдеру - в броне и с оружием - 6 лет. Ещё и наёмник, видать бывалый боец. ;)
P.S. Рекрутировал его, "за печеньки", выдал метлу и кирку и через пару часов он огрёб люлей от второго пацана, 17 лет: наверное не так копал. Тяжко быть ребёнком. (

**Comment by OpacareAngelus** [comment]
У меня, например, два дроида-киборга есть. Одному 1 год, второму 2 года, хотя это лишь формальная цифра для них.
Ко мне приходили дроиды возраста 1-6 лет, нападали на базу.
Если у тебя всё же 6 лет было человеку - тогда да, не помешал бы маркер по возрасту для определенных рас. Но я никогда такого не встречал с людьми, азари или котиками. Все старше 16.

**Comment by SetAriman** [comment]
Как повезёт. У меня только за эту партию минимум двое пацанов. Этот, и второй, восьмилетка - просто шёл через карту.

**Comment by Zim777** [comment]
В дев версии изменили минимальный возраст приходящих рейдеров, ниже 14 не будет приходить.
В мастер ветке все же можно словить рейдеров от 6 лет и выше

**Comment by SetAriman** [comment]
6 лет... А девочку нудистку, наёмницу-снайпера 5 лет не хочешь? ))

**Comment by masakitenchi** [comment]
Closed as too old
