### ISSUE TITLE
Гигантские улитки

### ISSUE THREAD

**Issue by ossram** [skyarkhangel/Hardcore-SK#1882]
С гигантских улиток не уходит статус "сражен" после болезней или соответствующих травм и они не могут подняться.

**Comment by Arlaise** [comment]
Races_Animals.xml

	<PawnKindDef ParentName="SK_AnimalKindBase">
		<defName>GiantSnail</defName>
		<label>Giant Snail</label>
		<race>GiantSnail</race>
		<combatPower>30</combatPower>
		<ecoSystemWeight>0.20</ecoSystemWeight>
		<lifeStages>
			<li>
				[DELETE?] <label>Giant Snail</label> [/DELETE?] 
				<bodyGraphicData>
					<texPath>NPS/Animals/Snail/Snail</texPath>
					<drawSize>0.45</drawSize>
					<color>(223,219,108)</color>

**Comment by masakitenchi** [comment]
Closed as too old
