### ISSUE TITLE
Гости-зависимые

### ISSUE THREAD

**Issue by ossram** [skyarkhangel/Hardcore-SK#1888]
Гости-зависимые никак не могут уйти с поселения. При дебаффе к скорости передвижения от последствий зависимости, гости успевают получить все дебаффы от недоедания, низкой гигиены, обезвоживания и получить диарею. Начинают уходить недолеченными, сонными и голодными, от чего, не доходя до края карты, падают в обморок от изнеможения или голодания.

**Comment by masakitenchi** [comment]
Closed as too old
