### ISSUE TITLE
Баланс поздних этапов игры и гусеницы механоидов

### ISSUE THREAD

**Issue by ossram** [skyarkhangel/Hardcore-SK#1892]
На поздних этапах игры (±20 лет), Зеон не проблема, а вот из обломков кораблей механоидов вылезают по ±30 гусениц + ±25 жнецов + ±25 лансеров. Такой рейд контрить практически невозможно без абузов. Каждая турель успевает уничтожить максимум по 3-4 гусеницы, до того как ее снесут, а когда в атаке много гусениц с инферно-пушками, это число еще меньше.

**Comment by ronekarleone** [comment]
Лабиринт и минометы с ЭМИ?

**Comment by ossram** [comment]
> Лабиринт и минометы с ЭМИ?

Не надежно.
На последнем трае отбивал 55 гусениц и 45 жнецов вместе, без андроидов и протезированных колонистов. Никаких снарядов для такого вторжения не хватит, да и меткость минометов желает лучшего. В общем, весело провел 28 игровых часов отбиваясь в боевом режиме, истратил все патроны под автоматы и снайперки, паралельно шло непрерывное производство и поднос боеприпасов. И это еще предпекло. 
Но, если так посмотреть, за все время игры в HSK, это было единственное действительно напряжное событие на уровне развития, когда Зеон - это уже только ресурсы на продажу.

**Comment by ossram** [comment]
Дополню, чтобы не быть голословным. Кто-то отбивался от "такого" без абузов?
![1](https://user-images.githubusercontent.com/55915620/71072563-770f1480-2187-11ea-8a56-0a9cc809118b.png)

**Comment by ronekarleone** [comment]
Я тут потестил работу дубинки-шокера. Она имба: два удара в любое место и гусеница валится.
Тактика: в узком коридоре за углом ставишь милишника с дубинкой-шокером и отовариваешь гусениц по одной. Теоретически можно законтрить любой рейд.

**Comment by ossram** [comment]
> Я тут потестил работу дубинки-шокера. Она имба: два удара в любое место и гусеница валится.
> Тактика: в узком коридоре за углом ставишь милишника с дубинкой-шокером и отовариваешь гусениц по одной. Теоретически можно законтрить любой рейд.

Вот-вот, и я о том. Базовые механики игры и сборки в целом не позволяют нормально играть без использования абузов. Дубина-шокер, так совсем, если из правильных материалов и качества, имеет бронепробитие равному которому просто нет, а, в свое время, трубка с ядовитыми дротиками после нерфа плохо пробивает даже простую одежду, а в случае пробития, почти никогда не срабатывает эффект снотворного.

**Comment by masakitenchi** [comment]
Closed as too old
