### ISSUE TITLE
Oil drillers can not be placed outside of god mode, Oil extractor does not produce oil

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#190]
Errors Since merging https://github.com/skyarkhangel/Hardcore-SK/commit/0edf22c11b150197c1ffa6051f6fc587656f11e9

The removal of the below code in Mods/Core_SK/Defs/ThingDefs/Minerable_SK.xml from deposit of oil made it so it was impossible to place drilling rigs, failure message given 'Space already occupied.' Adding it on my own made it work again. Unsure if it was intended to have a work around that was not implemented yet.
```
line 115
-    <building>
-      <isEdifice>false</isEdifice>
-      <claimable>false</claimable>
-      <deconstructible>false</deconstructible>
-    </building>
```

Extractor I'm not sure how to fix the issue that I'm getting, every tick it is giving the error

```
Exception ticking OilExtractor8360: System.DivideByZeroException: Division by zero
  at SK.Building_OilExtractor.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
```
And no oil is produced.

edit: when spawning a fissure and placing the oil extractor on it, it doesn't produce oil but no errors are thrown, probably not important.

**Comment by Jalordon** [comment]
I tried looking in the assembly with a de-compiler to try to see if anything was visible from there.

Oil extractor does  `Find.get_TickManager().get_TicksGame() % 0 == 0` in SK.Building_OilExtractor's Tick() probably causing the divide by 0 error. @skyarkhangel 

It was `Find.get_TickManager().get_TicksGame() % 90 == 0` in mineral extractor's code for reference. 

Not sure how it looks on your end since the de-compiler may have changed appearance of the original code.
```
		public override void Tick()
		{
			base.Tick();
			bool flag = this.gusher == null;
			if (flag)
			{
				this.gusher = (OilGusher)Find.get_ThingGrid().ThingAt(base.get_Position(), ThingDef.Named("Oilfield"));
			}
			bool flag2 = this.gusher != null;
			if (flag2)
			{
				this.gusher.harvester = this;
				this.oilSprayer.OilSprayerTick();
			}
			bool flag3 = !this.HasPower || !this.HasFissure;
			if (!flag3)
			{
				bool flag4 = Find.get_TickManager().get_TicksGame() % 200 == 0;
				if (flag4)
				{
					GenTemperature.PushHeat(this, 1f);
				}
				bool flag5 = Find.get_TickManager().get_TicksGame() % 0 == 0; //This line is the issue
				if (flag5)
				{
					MoteThrower.ThrowDustPuff(Gen.TrueCenter(this), 0.3f);
				}
				int num = this.tickCount;
				this.tickCount = num - 1;
				bool flag6 = num <= 0;
				if (flag6)
				{
					this.tickCount = this.availableList[this.resourceIndex].ticksToProduce;
					this.Dig();
				}
			}
		}
```

**Comment by skyarkhangel** [comment]
Ok. i soon look at problem. Yes, oil extractor had an update.. so with bug :)

**Comment by skyarkhangel** [comment]
Fixed
