### ISSUE TITLE
Редкие залежи в недоступных местах

### ISSUE THREAD

**Issue by ossram** [skyarkhangel/Hardcore-SK#1900]
[Edited:] [Новые залежи ресурсов, которые являются маловероятными и малоколичественными для спавна], спавнятся под глубокой водой или на краях карты за грядой гор на пол карты.

**Comment by Zim777** [comment]
Уважаемый, мы рады, что вы пишите про огромное кол-во "багов". Но большая часть из них уже решена и применена к dev-ветке.
В частности данный "баг" уже не актуален, так как система добычи была переделана и "залежей" в таком виде уже не будет в будущем.

**Comment by ossram** [comment]
> Уважаемый, мы рады, что вы пишите про огромное кол-во "багов". Но большая часть из них уже решена и применена к dev-ветке.
> В частности данный "баг" уже не актуален, так как система добычи была переделана и "залежей" в таком виде уже не будет в будущем.

Спасибо за ответ, если угодно, я могу больше не писать о них. Под "редкими" я имею в виду залежи тех видов ресурсов, которых на карте максимум 1-2, таких как, к примеру, урановая, золотая руда и других, и касаются они именно последнего обновления. Без урановой руды еще куда не шло, но вся электроника без золотой руды это уже проблема.

**Comment by ossram** [comment]
Залежи золота же вовсе после генерации новой карты не было найдено даже с помощью режима разработчика.

**Comment by Zim777** [comment]
Терраформинг ->  "Мелководье" из "Глубокая вода " и так далее -> профит

Все типы ресурсов не обязаны спавнится на карте.
Хватить сидеть на месте и изображать из себя хикикомори.
Создавайте лагеря, вторые поселения, торгуйте своими караванами.

**Comment by ossram** [comment]
> Терраформинг -> "Мелководье" из "Глубокая вода " и так далее -> профит
> 
> Все типы ресурсов не обязаны спавнится на карте.
> Хватить сидеть на месте и изображать из себя хикикомори.
> Создавайте лагеря, вторые поселения, торгуйте своими караванами.

Тундровый архипелаг, поселение в мире - на острове в несколько клеток окруженных океаном, вокруг никого и ничего, на самом гексе до ближайших нужных ресурсов 100-150 клеток глубокой воды, самое меньшее в 50 клеток, прокопать по 100 клеток глубокой воды в 5-6 сторон, где 2-3 клетки с залежами не проблема, но они кончаются через один, максимум, полтора игровых года с несколькими майнерами. Соседние гексы практически идентичны. Добавлю, что вода не замерзает.
В HSK выход есть всегда, и новая система добычи отличная, но сейчас добывать ресурсы стало невыгодно, а в не "комнатных" биомах, где нет возможности поставить даже карьер, предусмотреть бы хоть базовые ресурсы в доступности, или по всем залежам (клеткам с ресурсами) увеличить количество добываемой породы раза так в 3. Я к тому и веду.

К слову, sky, твою идею с подземными пещерами можна реализовать, как для восстановления месторождений. По окончании добычи на месте, где были залежи, можна спустится в так называемую пещеру-локацию, которая завалена обрушенной породой, а на другом конце локации за большими завалами что-то похожее на обычный артефакт, но в виде породы, по активации которого на основной локации залежи восстанавливаются полностью, что позволяло бы восстановить добычу буровых до следующей разведки залежи. Усложнить все жуками и землетрясениями с завалами. Небольшая локация не будет сильно грузить движок игры, а при покидании ее, она будет выгружена с памяти.

**Comment by masakitenchi** [comment]
Closed as too old
