### ISSUE TITLE
Цвет залежей ресурсов и альфа-канал

### ISSUE THREAD

**Issue by ossram** [skyarkhangel/Hardcore-SK#1901]
Некоторые виды залежей практически невозможно заметить на соответствующих биомах днем. К примеру, нефрит и урановую руду в умеренных лесах, а янтарь, медь в пустынях. Уголь же днем заметить сложно практически везде, недавно случайно нашел залежи угля в центре базы во время солнечной вспышки, так как до этого там постоянно горел свет. Также, при низком количестве ресурсов, альфа-канал делает цвет почти невидимым для любых залежей.

**Comment by Zim777** [comment]
Пользуйтесь поиском - правый нижний угол - иконка увеличительного стекла - поиск объектов

**Comment by ossram** [comment]
> Пользуйтесь поиском - правый нижний угол - иконка увеличительного стекла - поиск объектов

Да верно, а что с глубинными как?

**Comment by masakitenchi** [comment]
Closed as too old
