### ISSUE TITLE
Спасите котиков!

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1908]
Можно как-то "прокачать" кошек? Эти заразы усиленно охотятся на всё живое. В результате у меня кошка обычно в двух состояниях: бежит охотиться / лежит в постели с чумой, заражением и ранами. Может бонус какой против грызунов дать?

**Comment by skyarkhangel** [comment]
Кошкам снижено значение размера жертвы при поиске добычи. Было выше их самого уровня, т.е. могли охотится на таких же как они.

**Comment by masakitenchi** [comment]
Closed as too old
