### ISSUE TITLE
Неправильные грибы.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1910]
У салата с грибами питательность 0.70, тогда как у простого блюда 0.85. И масса 1.70 кг против 1 кг. Это при том, что салат делается из двух ингредиентов, а не одного, требует больших затрат и изучения наук. У других блюд из грибов питательность как и у простого блюда, хотя они тоже сложнее. Выходит тупо жрать стартовую картоху куда выгоднее, чем заморачиваться с грибами.
P.S. У чизбургера питательность 0.90, а заморочек куда больше, чем у простого блюда.

**Comment by ronekarleone** [comment]
Не только у салата с грибами. В сборке есть системная проблема с приростом питательности и ценности при обработке. Нужна перебалансировка (я когда-то предлагал это на форуме), но это никому не нужно

**Comment by masakitenchi** [comment]
Closed as too old
