### ISSUE TITLE
Readme.md dead links

### ISSUE THREAD

**Issue by thisischrys** [skyarkhangel/Hardcore-SK#1914]
>  RimWorld ReShade Guide:
> When a lot of people hear of ReShade, first thought often comes to games in 3D space, such as PUBG and Skyrim. However, ReShade is versatile enough to work with games even like Rimworld and have stunning results.
> Learn more: https://imgur.com/a/DrYqGaY

Actual presets linked in the imgur.com are a dead link.

**Comment by skyarkhangel** [comment]
All fine with link for me.

**Comment by thisischrys** [comment]
Sorry, I realise I wasn't being clear.

I mean the link to download the actual shaders:
https://drive.google.com/open?id=1CvXlGEPOlvTok0aRmhsTHd3n4DlQzyoM

**Comment by wooley2000** [comment]
https://discordapp.com/channels/272340793174392832/272340793174392832/473850500677369857

**Comment by wooley2000** [comment]
for the future

**Comment by masakitenchi** [comment]
Closed as too old
