### ISSUE TITLE
Для чего нужен разводной ключ?

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1915]
Это более технологичное устройство, чем молоток. При этом ускоряет те же действия - ковку и строительство - но в разы хуже. 40% и 50% против 120% и 100%. Это при том, что в данном случае у ключа отличное качество, а у молотка только нормальное.

**Comment by skyarkhangel** [comment]
Сделан из другого материала?

**Comment by SetAriman** [comment]
Нет. И два ключа, которые я смотрел, и два молотка - стальные.

**Comment by Kiriharas** [comment]
Ключ судя по всему не адаптирован под мод на инструменты - у него циферки +30%, тогда как у молотка х130%

**Comment by skyarkhangel** [comment]
Да, все причина найдена. Исправлено в следующем апдейте.
