### ISSUE TITLE
Производство снарядов для миномёта.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1920]
Снаряды для 80-мм миномёта (другие не проверял) в производстве по принципу "повторять до" заказываются партиями минимум по 80 шт. Можно сделать заказ малыми партиями, хотя бы по 10? Чтобы было удобно поддерживать нужное количество на складе.

**Comment by skyarkhangel** [comment]
Сделано в следующем апдейте.
