### ISSUE TITLE
Третья концовка.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1921]
Может я неправ, но насколько я помню, когда проходишь игру в конце идут титры под музыку или что-то такое. Знаменуя окончание игры. Но в случае третьей концовки, когда колонию эвакуирует спасательный корабль, ничего нет. Тупо выкидывает в меню.

**Comment by Zim777** [comment]
Да, так и есть - в случае улетания на корабле "дружественного" ИИ - просто выход в меню. так  происходит в оригинальном RimWorld.
Это не баг сборки ХСК и не баг игры в целом. Сам Тунан загадочно отмолчался на такой же вопрос.
Можете считать, что ваши колонисты просто стали объектами для эксперимента "дружественного" ИИ.

**Comment by SetAriman** [comment]
Тутан загадочно отмолчался, что ему лень было пилить баг, и вообще он про него забыл? ;) Ну так сборка для того и предназначена, чтобы доработать и улучшить то, что не сделал Тунан.

**Comment by Pepelnica1488** [comment]
> Тутан загадочно отмолчался, что ему лень было пилить баг, и вообще он про него забыл? ;) Ну так сборка для того и предназначена, чтобы доработать и улучшить то, что не сделал Тунан.

1 000 000+ проданных копий и зажравшийся разраб ас ис

**Comment by SetAriman** [comment]
Кому зажравшийся, а кому - ленивый. "И так сойдёт" В Кенши не ходи. Или легендарного качества ВоВ от легендарной Близзард из легендарной серии игр, в котором баги до сих пор косяками с ванилы тянутся.

**Comment by Pepelnica1488** [comment]
У кенши таких продаж и рядом небыло + разраб римворлда всегда при бабле был и не один

**Comment by SetAriman** [comment]
Вопрос не в продажах, а в тенденции. И я привёл примеры. Кстати: во втором примере продажи и популярность куда выше, чем в Римке. Не путай продажи и нежелание продолжать **полноценную** работу над релизом после официального окончания. Большинство контор после релиза слегка допиливает продукт и бросает его. К примеру та же Беседка с её жутко забагованной серией Свитков. Это распространённая практика. 

А также не путай тёплое с мягким и член с пальцем. Не надо. Даже если они, в отличие от твоего примера, и похожи друг на друга.

**Comment by masakitenchi** [comment]
Closed as too old
