### ISSUE TITLE
Сумасшедший феникс.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1924]
Приручил молодого феникса, всё было хорошо. Но в какой-то момент он отказался выходить из хлева гулять и начал раз за разом поджигать всё, что видит: кровати животных, других животных, пешек. Причём он не буянил, просто поджигал что попало. Возможно это исправить? Иначе, выходит, нет смысла приручать эту ходячую катастрофу.

**Comment by ronekarleone** [comment]
С какого-то релиза животные стали дичать. Теперь их надо регулярно тренировать, чтобы компенсировать одичание. Чем больше параметр "дикость", тем быстрее они дичают. Твой скорее всего стал полностью диким. Можешь попробовать его заново приручить.

**Comment by masakitenchi** [comment]
Closed as too old
