### ISSUE TITLE
How can i make carbon? (for ammo crafting)

### ISSUE THREAD

**Issue by kvort** [skyarkhangel/Hardcore-SK#1926]
I can't make 'hp" ammo, because the ammo crafting requires "carbon" that I haven't found yet where to craft, the "Chemical Laboratory" has been removed, only the description remained

**Comment by sidfu** [comment]
just something that got overlooked in the move to new systems. we probaly replace it with charcoal or something

**Comment by Zim777** [comment]
If it is about dev-branch then there is Rimefeller_SK
new laboratory in it can produce carbon.

**Comment by kvort** [comment]
Thx!

**Comment by masakitenchi** [comment]
Closed as too old
