### ISSUE TITLE
Возможная проблема с ядерной зимой.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1927]
У меня после падения ядерной ракеты наступила ядерная зима. Или, как это называет игра, "радиоактивное заражение." По данным, которые я нашёл в сети, зима должна длиться год или два. Но у меня пошёл уже третий год холодов и окончания не видно.

**Comment by kismatvei** [comment]
Данные были не корректные, событие ядерная зима длиться более 5 лет, сам проверял и вроде как - на 10 год не было ни одного радиоактивного осколка
> Но потом через год ещё одна бахнула 😂

**Comment by Zim777** [comment]
На текущий момент в дев ветке зима длится ровно 100 дней.
В стабильной версии  даже меньше - всего 50 дней

**Comment by SetAriman** [comment]
Да ладно? Я закончил с месяц назад партию, и у меня "радиоактивные осадки" и связанное с ними похолодание висели свыше 7 лет. До самого конца игры. В стабильной последней версии. Не закончил бы партию - и дальше бы так было.

**Comment by Zim777** [comment]
В дев ветку зашло 100 дней всего лишь 13 марта
В стабильной чуть-чуть раньше.
внезапнА?

**Comment by insidio118** [comment]
У меня ядерная зима продлилась 2 года. Я отключил её через консоль, больше ждать не стал. Играю на дев ветке.

**Comment by masakitenchi** [comment]
Closed as too old
