### ISSUE TITLE
Leatherworking update.

### ISSUE THREAD

**Issue by harchschoolboy** [skyarkhangel/Hardcore-SK#193]
I suggest to update leatherworking process.
Like raw leather + drying frame +time => leather.
Leather + tanning barrel + time => tanned leather.

Both of those jobs aren't require alot of addtitional manipulations. Tanning require bark, which can be gained additionaly when you saw logs to planks.

It can be realized as a compost bin atm. 
You put drying frame outside, put some raw leather on it, 2-3 days later you get ready for craft leather.
Same with tanning barrel, except it can be placed inside.

Any additional suggestions?

**Comment by Vigilence** [comment]
That would be cool to see.

**Comment by jnkyacc** [comment]
> It can be realized as a compost bin atm. 

wait A15 with fermentation barrels 

> Tanning require bark

What about ice sheet biome? I think better start without any additional items for leather working.

**Comment by harchschoolboy** [comment]
> What about ice sheet biome? I think better start without any additional items for leather working.
buy wood, or bark from traders, hydroponically grow trees no one says it will be easy
i don't say that only tanned leather would be crafting ingredient, not tanned leather will be too
but i think there should be unusable raw leather which should be dried to become crafting material

> wait A15 with fermentation barrels 
is it HCSK stuff or Tynant?

I've started experiments with tanning barrel 
![image](https://cloud.githubusercontent.com/assets/3436744/18164968/68a0f6e8-704b-11e6-8f7f-29585e37a1e7.png)

Also, as i understand, Compost Bin way of work (convert stuff to compost) is hardcoded to dll?

**Comment by jnkyacc** [comment]
> is it HCSK stuff or Tynant?

Vanilla stuff for beer fermentation. It also have a nice progress bar.

> Also, as i understand, Compost Bin way of work (convert stuff to compost) is hardcoded to dll?

yes

**Comment by harchschoolboy** [comment]
> Vanilla stuff for beer fermentation. It also have a nice progress bar.

got it
ok, then i postpone this idea until a15 will be stable for HCSK
