### ISSUE TITLE
Impossible to load the saved game after a couple of hours of gameplay

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#1930]
And the log contains quite a lot of System.NullReferenceException's: http://pstbin.ru/t/30842/

Got it on all the two games i've tried to play after installing Hardcore-SK master.

**Comment by sidfu** [comment]
make sure u using the hcsk ones and not steam version of some of the mods. before u go adding mods liek vampires and such make sure your base hcsk is workign fine first.

**Comment by l29ah** [comment]
I've only installed the HCSK mods to the vanilla game.

**Comment by sidfu** [comment]
your log has refercneces to vampires and werewolves at the top of it

**Comment by l29ah** [comment]
```
‰ grep -i vamp rimworld.log               
The class Vampire.VampireUtility could not be loaded, used in Vampire, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
The class Vampire.CompVampire could not be loaded, used in Vampire, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
```

```
Hardcore-SK $ grep -ri VampireUtility .
Binary file ./Mods/FacialStuff_SK/Assemblies/FacialStuff.dll matches
Hardcore-SK $ grep -ri CompVampire .
Binary file ./Mods/FacialStuff_SK/Assemblies/FacialStuff.dll matches
```
I don't see anything about werevolves.

**Comment by Zim777** [comment]
The class EdB.PrepareCarefully.PrepareCarefully could not be loaded, used in EdBPrepareCarefully, Version=1.0.10.0, Culture=neutral, PublicKeyToken=null
The class Vampire.VampireUtility could not be loaded, used in Vampire, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
The class Werewolf.WerewolfUtility could not be loaded, used in Werewolf, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
Missing field Instance in class Androids.Integration.AndroidsModSettings (type token 16777242)
The class Androids.Integration.AndroidsModSettings could not be loaded, used in AndroidsFacialStuff
The class Vampire.CompVampire could not be loaded, used in Vampire, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
The class Werewolf.CompWerewolf could not be loaded, used in Werewolf, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null
The class Werewolf.CompWerewolf could not be loaded, used in Werewolf, Version=1.18.0.0, Culture=neutral, PublicKeyToken=null

**Comment by l29ah** [comment]
I've disabled the Androids mod since i've heard it's insane, but haven't disabled AndroidsFacialStuff. Does this result in working gameplay but broken saves? Can i fix them somehow?

**Comment by l29ah** [comment]
No idea about the rest. I've only disabled DarkestNight, Arachnophobia, Androids, and Skynet.

**Comment by Zim777** [comment]
> I've disabled the Androids mod since i've heard it's insane, but haven't disabled AndroidsFacialStuff. 

But you have to. they are linked

**Comment by sidfu** [comment]
your save is probably corrupted so u cant use that save. not all mods can be removed and a save still used.
this is what i recommend
1. to  a complete clean install. this means also removing the app data.
2. once that's done run game once so u regen the app data and also then make a backup of core
3. now install the dev version.
4. bootup and see what errors u have.
5. if no errors take then add any extra mods.

if u disable androids which u dont need to  u will need to disable the facial patch for them. not the alien faces mod the one specifically named androids.

androids will allow u to build some later but u dont have to.

**Comment by l29ah** [comment]
Yeah, force-loading the saves with the facial stuff disabled works, thank you!
