### ISSUE TITLE
Light from Power Armor always turn off

### ISSUE THREAD

**Issue by Glucocorticoid** [skyarkhangel/Hardcore-SK#1931]
Light mode of power armor switch to ForcedOff when pawn wear it.

If i try on paused game to switch light mode to ForcedOn and drop armor, it has <lightMode>ForcedOn</lightMode>

But if i equip it again, light mode again switch to ForcedOff and can`t be toggled on ever.

 Seems like class ApparelWithMiningLight is broken or smth.

**Comment by Glucocorticoid** [comment]
For Appare_PowerArmorShield class in core_sk.dll binary you set private property disablelight = true.

Every tick() in TickFunctions():
		if (this.disablelight)
		{
				this.lightMode = Apparel_PowerArmorShield.LightMode.ForcedOff;
		} 
		...

Same for basic ApparelWithMiningLight class.

Every second each apparel with mining light set light mode to ForcedOff and paws don`t use light for mining and dig very slow in darkness.

Can we have some options here? In early June 2019 versions light works correct.

**Comment by masakitenchi** [comment]
Closed as too old
