### ISSUE TITLE
Tribals can build steel grill without technology research

### ISSUE THREAD

**Issue by thisischrys** [skyarkhangel/Hardcore-SK#1934]
Steel grill can be built by clicking Production > Prepare food.
It is not visible if you right click it, but if you left click it you can place it without needing the technology research.
Using dev version.

**Comment by zakhad** [comment]
It's a limitation of the architect menu known bug, Grill is the first alphabetically out of all eventual options from that menu list, so it will always show first until you select something that you're no longer able to select it. Same with happens with the fishing pier and fishing hopper showing first H > P.

**Comment by thisischrys** [comment]
Gotcha, thanks for the info!
I'll just have to restrain myself :p
