### ISSUE TITLE
Суперскучно

### ISSUE THREAD

**Issue by ImTheMass** [skyarkhangel/Hardcore-SK#1935]
Версия HSK от конца лета 19 года.
Лейтгейм HSK - невероятно скучное время. После 7-8 лет колонии противники физически ничего не могут ей сделать. Даже особо с обороной заморачиваться не надо - 14,5 мм пулеметы справляются с любой проблемой на раз-два. И это на режиме "пекло"... Слишком разительная разница между зубодробительным началом и чиллаутной концовочкой. И это на фоне бесконечного гринда ресурсов на постройку корабля стоимостью со квартиру в центре Москвы. Нет никакого вызова. Даже ядерная зима у меня не вызывает ничего кроме зевоты. Добавьте хотя бы вторжение мехов, чтобы они дня два бесконечным потоком перли на колонию и взрывались при выходе из строя... Или атаку андроидов-смертников с системой самоуничтожения и кибернетическими протезами, которые со скоростью 20 кл/сек прилетят к твоим оборонительным рубежам и с веселыми криками "Аллах акбар!" снесут тебе половину колонии... или гостя-саботера, который почиллит немного в гостях, а потом, такой: "все ваши оборонительные сооружения выведены из строя, а боеприпасы взорваны! Отбивайся чем можешь!". Ну серьезно, можно же что-нибудь придумать интересное... 

И еще, скорее всего есть проблема с изменением рассказчика во время игры. Так, пока я не поменял его, на меня хотя бы изредка нападали мехи и термосы. Сменил Кару на Рей, и сложность событий упала на порядки. Печаль =(.

**Comment by amasonchic** [comment]
Я не эксперт, но смена расказсчика ломает игру, даже ванильку - все события ломаются.

**Comment by Pepelnica1488** [comment]
Для меня начало наоборот суперлёгкое а в лейте начинается ад из рейдов в 200 пешек

**Comment by TlepshSmither** [comment]
Кару на Рей менял? 
Сначала ставишь ЗЕРО, сложность на максимум, железную волю, чтоб без перезагрузок в случае неудачи. 
На Рей любой дурень отобьётся.

**Comment by ImTheMass** [comment]
Зеро я тоже ставил, через месяцок (игровой) игры с Рей. Ну да, стало чуть больше событий на природку, а-ля геошторм и прочая ерунда. Единственное, что было там неприятно - пожар на гидропонике (без которой я и так прекрасно обхожусь) и взрыв аккумуляторов от постоянных землетрясений. Ну, такое-себе.. 
Сейчас вернул Кару. Запустил реактор и стало слегка повеселее. Хоть огры с огнестрелом стали приходить.

> Сначала ставишь ЗЕРО, сложность на максимум, железную волю, чтоб без перезагрузок в случае неудачи.
Я и так без перезагрузок играю. Кара, пекло. От племени + с выставленным максимальным штрафом к исследованиям. Было весело первые пять лет трястись над каждым пистолетиком и каждым патроном =D. Но, повторюсь, когда я максимально развил колонию, все веселье пропало. А Зеро как ИЗНАЧАЛЬНОГО рассказчика я еще не тестил... Ну, поразмянется у меня жопа с ним в начале, да вот опять же боюсь, что к лейту он сдуется, как и остальные рассказчики (и я буду рад, если ошибаюсь).

**Comment by furlapan** [comment]
Вся соль то как раз выжить. Выжить до определенного момента. Для кого-то это запуск шатла а для кого-то момент полного развития - когда становится скучно. И, как поется - "наша песня хороша - начинай сначала...!"

**Comment by ImTheMass** [comment]
А как же эстетическое удовольствие от эскалации масштабов противостояния, от событий, после которых тебе нужно задействовать всю свою производственную мощь чтобы восстановиться или отбиться? Что делать с желанием пободаться с игрой на высоких ставках? Когда в каждую пешку вбухано под 100к серебра? Когда ты защищен от всех очевидных угроз тебе остается лишь почивать на лаврах - игра физически ничего не может тебе противопоставить. Это неправильно. Игра должна завершаться не скукой, а триумфом или палатой жопного хирурга. 
Ванилка, к слову, всегда имела бэкдоры, от которых было очень сложно защититься на любом этапе игры при любой возможной стратегии обороны. Но ванилка до безобразия скудная на контент - материалов, технологий и объектов там с котью слезку, а максимальный тех уровень набивается за несколько часов игры. Плюс ко всему, в HSK исчезла даже такая вещь как кульминация игры в виде 15 дневного прогрева реактора корабля, ну разве что чуть-чуть больше налетов, принципиально таких же как всегда. 
Мне все равно кажется, что лейтгем HSK очень плохо сбалансирован, в частности - баланс смещен в пользу игрока. Даже поселенцы перестают сраться между собой, а уж если дело дошло до драки (вау) они едва царапают друг друга. Все такие взаимолюбящие что аж противно.

И, сделаю акцент, я не предлагаю делать всю HSK воплощением страдания. Но для "пекла"-то можно постараться?

Я, честно, безумно люблю проект HSK и от всей души хотел бы сделать его лучше, хотя бы даже фидбэком и идейками.

**Comment by Pepelnica1488** [comment]
как вариант при определённой ценности колонии ( хз лямов 5 или 10 у меня больше 2 все равно никогда не было ) врубать овержёсткий режим с каким нибудь новыми врагами которые реально будут вас карать,придумать то можно но надо ли оно?

**Comment by ImTheMass** [comment]
> как вариант при определённой ценности колонии ( хз лямов 5 или 10 у меня больше 2 все равно никогда не было ) врубать овержёсткий режим с каким нибудь новыми врагами которые реально будут вас карать,придумать то можно но надо ли оно?

Надо =D.

**Comment by masakitenchi** [comment]
Closed as too old
