### ISSUE TITLE
Вечновсплывающие уведомления

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1937]
Андроид "стал каннибалом" но как бы не стал поэтому бесконечно вылезают уведомления и никак не исправить
![image](https://user-images.githubusercontent.com/47127651/69143421-fef6f580-0ad9-11ea-8e34-3228f1b7d3c4.png)

вот сейв https://anonfiles.com/d4xeibB5n9/Saves_7z

**Comment by Pepelnica1488** [comment]
ps напишите если кто нибудь знает как фиксануть ибо играть невозможно жи

**Comment by Zim777** [comment]
Выдай черту канибализма вручную этой пешке через РР

**Comment by masakitenchi** [comment]
Closed as too old
