### ISSUE TITLE
Лед практически не тает в помещениях

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1939]
Выживаю на льдах.
Построил комнату вокруг небольшого озера (мелководье плюс прибрежная земля).
После замерзания комнаты все тайлы превратились в лед.
Теперь же в комнате стабильно +30 - +50, но тает максимум 3 тайла из 20 бывших озером и берегом.

**Comment by masakitenchi** [comment]
Closed as too old
