### ISSUE TITLE
Колонисты прерывают задания

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1941]
Пешки довольно часто прерывают вручную назначенные таски и идут делать то, что стоит в приоритете в работах. Это похоже на прерывание на еду или сон, но только они идут работать куда хотят.

**Comment by ImTheMass** [comment]
Такое бывает, если для назначенной работы им нужно поменять инструмент. Они его меняют и забывают задание.

**Comment by masakitenchi** [comment]
Closed as too old
