### ISSUE TITLE
Рекурсивный лук без техи

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1943]
Рекурсивный лук можно крафтить без технологии "Рекурсивный лук"

**Comment by PodliKirill** [comment]
Это ошибка описания техи. Теха "рекурсивный лук" открывает мешки с песком и в английской версии называется Security l. Аналогично - техи "аккумуляторы" не открывающие аккумуляторы, "Высокоточное производство" для кухни и некоторые другие имеют очевидные несоответствия названий.

**Comment by masakitenchi** [comment]
Closed as too old
