### ISSUE TITLE
Количество патронов

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1948]
Пешка набивает стрелами весь инвентарь (300+ стрел).
Если оттюнить это количество в наборе снаряжения, то тогда нельзя будет просто управлять ее вооружением: она будет выкидывать все оружие, что не прописано в снаряжении. Можно поправить дефолтный уровень патронов и проблему с выкидыванием вручную назначенного оружия?

**Comment by Kiriharas** [comment]
Нет, либо прописывай всё в снаряжении (что не сложно, имхо), либо отключай мод.
Кстати, если пешка находится в режиме призыва, то она не выкинет поднятое оружие, пока не выйдет из него.

**Comment by Pepelnica1488** [comment]
100 стрел максимум надо а она напихивает по 300..

**Comment by ImTheMass** [comment]
> Нет, либо прописывай всё в снаряжении (что не сложно, имхо), либо отключай мод.


Я уже настолько привык прописывать каждой пешке снаряжение, что забыл как меня это бесило вначале.

**Comment by ronekarleone** [comment]
> Я уже настолько привык прописывать каждой пешке снаряжение, что забыл как меня это бесило вначале.
Это не отменяет того, что это недоработка, и было бы неплохо исправить.

**Comment by Leslov** [comment]
Если хочешь вручную назначать вооружение, то оставь в настройках снаряжения "Не назначено", тогда пешка ничего скидывать не будет.

**Comment by ronekarleone** [comment]
Если поставить "Не назначено", то пешка набивает весь инвентарь стрелами, см. тему тикета.

Короче. Очевидно, что это недоработка. Пешка должна **определять дефолтное количество боеприпасов динамично,** в зависимости от оружия:
- для лука хватит 50 стрел,
- для пистолета 50 патронов,
- для ПП и автоматов нужно 100-300,
- для снайперок нужно 50-100, 
- для гранотометов хватит 40, 
- для пулемета нужно под 300-500.

**А еще лучше добавить это в виде параметров мода.**
Потому что назначить списки снаряжения для всех пешек и вручную их контролировать - это раздражающий микроменеджмент. Решил ты выдать пешке пилу и отправить учиться на хирурга: вместо того, чтобы приказать пешке взять пилу, ты должен зайти в профиль ее снаряжения, там прописать пилу и затем выдать задание пешке взять нужную пилу. Все еще хуже, если ты решил сменить вооружение с луков на автоматы: для каждой пешки прописать нужное оружие и патроны, вместо одного щелчка по нужному оружию.Или смена оружия, если кончились нужные типы патронов. Или в случае износа оружия. Или замена легкого оружия на гранотометы при тяжелом рейде. И всегда нужно микроменеджментить в снаряжении вместо одного щелчка по нужному оружию.

**Comment by Leslov** [comment]
А как ей понять, какое оружие брать и нужно ли вообще брать? По моему, то, что пешке нужно назначать, что надевать не является недоработкой. Можно сделать общие наборы, например для мирных ремесленников, поваров и т.п. выдавать соответствующий набор инструментов и пистолет/ПП для самообороны, для боевых - инструменты и определенный тип штурмовой винтовки, чтобы при внезапном нападении они были наготове.

**Comment by ronekarleone** [comment]
В том то и дело, что пешка при использовании списка снаряжения пешка надевает лучшее из заданного класса, что вообще говоря не плохо. Но при этом, кстати, не учитывает модификаторы мода infused, типа сгибателя и пр., что плохо (зачем чистому стрелку кирка с модификатором сгибатель?)
А при ручном задании, ты говоришь взять нужное оружие и все. Проблема  в том, что пешка потом это оружие выкинет в рандомное время. Я так трай слил, когда пешка выбросила единственный дробовик для ЕМП дроби,и он сгнил, а стрелами механоидов не убьешь.

По сути в снаряжении ты наборы и задаешь. Это хорошо, когда поздний лейт, оружия всех видов, патронов 1000+ каждого типа итд. Тогда не важно в принципе что пешка берет оружием, тупо делаешь всем один набор снаряжения и все.
А когда у тебя на всю колонию, один узи, пистолет (.45), снайперка, пара луков и гранотомет с 3 единицами прочности и патронов до 100 каждого типа (реальная ситуация в текущем трае), то тут появляется постоянный менеджмент вооружения: передать снайперку другому колонисту, т.к. он одел шапку с бонусом на скорость прицеливания, выстрелить из гранотомета по скоплению норбалов один раз и положить его обязательно в помещении, чтоб не сгнил, Передать узи другому колонисту, т.к. этот отравился и с трудом ходит. И вот в таких случаях наборы снаряжения все очень усложняют. Забудешь потом все вернуть, он выкинет гранатомет на улице, и он сгниет. А если не использовать наборы снаряжения, то (см. тему кейса) они забивают весь инвентарь стрелами, и потом гранатомет туда не лезет, и вот ты начинаешь выкидывать стрелы, брать гранатомет, потом пешка опять берет стрелы по максимуму, ты выкидываешь стрелы, берешь гранаты итд. Бесит. 
И еще бежит за выпавшими из норбалов стрелами, даже если ей срочно нужно полечиться или вылечить умирающего колониста. Парочку колонистов из-за этого потерял. (Знаю про зоны и запрет стрел, но в горячке боя за всем не уследишь: дал задание лечить, отвлекся, вернулся, а пешка уже радостно бежит за !!!каменными!!! стрелами под огнем норбалов, отменив приказ лечить колониста).
В итоге я пришел к решению, что делаю по 50 стрел и вручную их раздаю, но в таком случае часто бывает ситуация, что забыл обновить боезапас и пешка без стрел. И крафтишь стрелы, пока враги идут к стенам.

В общем, если подытожить.
**Есть два предложения для доработки:
1. Запретить пешке выбрасывать вручную назначенное оружие, если в наборе снаряжения оно не назначено (я же не просто так его выдал);
2. Сделать динамическое определение необходимого числа патронов, как я описал выше.**

**Comment by masakitenchi** [comment]
Closed as too old
