### ISSUE TITLE
Кувалда не является инструментом

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1949]
Дает +55%, но режет до 30% от общей скорости строительства

**Comment by ronekarleone** [comment]
![Безымянный](https://user-images.githubusercontent.com/25797150/70273555-5c1dc700-17bb-11ea-993b-24fa4df6814d.png)

**Comment by masakitenchi** [comment]
Closed as too old

**Comment by masakitenchi** [comment]
Closed as too old
