### ISSUE TITLE
Books show up as pink squares.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#195]
The books in the game show up as pink squares as pictured below.

![screenshot 32](https://cloud.githubusercontent.com/assets/16742086/18107779/5d04f872-6ed7-11e6-9018-767ebc065e92.png)

**Comment by jnkyacc** [comment]
Unable to reproduce.
875 commit

**Comment by skyarkhangel** [comment]
Fixed a long time ago
