### ISSUE TITLE
Дебилизм при переноске

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1951]
Приказываешь пешке перенести что нибудь - она бегает по всей карте пихая себе ВСЁ ЧТО БЛЯТЬ ПЛОХО ЛЕЖИТ и тащит это на разные склады то на один забежит высрет там кучку то на другой и так 20 раз туда сюда ну что за идиотизм

**Comment by Azumgi** [comment]
Проблема в моде [Pick Up and Haul](https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058). Он стал работать гораздо хуже то ли в 0.19, то ли в 1.0. Там есть и другие неприятные баги. По-хорошему, его надо переписывать, но автор, похоже, его забросил.

**Comment by ossram** [comment]
> Приказываешь пешке перенести что нибудь - она бегает по всей карте пихая себе ВСЁ ЧТО БЛЯТЬ ПЛОХО ЛЕЖИТ и тащит это на разные склады то на один забежит высрет там кучку то на другой и так 20 раз туда сюда ну что за идиотизм

Ну, так, в чем проблема? Ты вручную дал пешке задание по переносу вещей, чем она и занимается. Если нужно перенести конкретный предмет или предметы, - прерви задание переноса после подбора их пешкой, и она перенесет на склады только нужные предметы.

На худой конец, используй перенос вручную, или приоритеты высокой, максимальной или срочного переносов. В игре больше шести различных вариантов переноски, и, по памяти, как минимум четыре из них прописаны в приоритетах работ.

**Comment by ossram** [comment]
Специально перепроверил... Отмечаешь нужный предмет максимальным приоритетом переноски и пешка переносит только его. Так в чем проблема?

**Comment by Leslov** [comment]
Бывает такое, что ремесленник, выполнив задание несет свою поделку на какой-нибудь дальний склад (это нормально) и по пути начинает таскать все подряд, что плохо лежит (это ненормально), несмотря на то, что приоритет переноски у него ниже, чем приоритет ремесленных работ.

**Comment by masakitenchi** [comment]
Closed as too old
