### ISSUE TITLE
Сильный пролаг после операции "Копировать - вставить" в окне Работа

### ISSUE THREAD

**Issue by Leslov** [skyarkhangel/Hardcore-SK#1952]
В окне "Работа" если создать набор (избранное), а затем копировать его и вставить его в ту же строчку, то игра дает очень сильный пролаг, у меня только через 30 секунд отвисло. Если у пешки не задан набор из избранного, то лага не будет.
![image](https://user-images.githubusercontent.com/15822720/71279922-c5850480-237b-11ea-9164-1e87072baff1.png)

**Comment by masakitenchi** [comment]
Closed as too old
