### ISSUE TITLE
Абуз отсутствия сна

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1954]
В текущем релизе можно абузить ситуацию, что пешки вообще не спят.
Работают нон-стоп, срываются, тут же засыпают во время срыва и он проходит, получают +40 настроения из-за срыва, что перекрывает отсутствие развлечений (-18) и сна (-20). Пару дней бонус держится и заново.
Раньше хотя бы пешка могла впасть в ступор на дня два, что довольно долго (в одиночестве означало смерть от голода). Теперь же ступор длится сутки или еще меньше. 
В итоге у меня уже 3ий год колонисты не спят. У всех конечно стрессовые травмы, но они по сути ничего не делают, зато качают медицину каждые 5 дней. 
Варианты и предложения:
1. Срыв не прерывается от сна;
2. Бонус к настроению от срыва сделать меньше (+20 или +30), плюс динамически определять в зависимости от тяжести срыва. Сейчас выгоднее дать пешке сорваться, прервать срыв каким либо способом и несколько дней наслаждаться +40 к настроению;
3. Стрессовую травму сделать серьезнее (+0.5% к вероятности срыва и очень редкие панические атаки - это ни о чем). Например, снизить скорость работы и/или постоянный дебаф к настроению.
4. Сделать так, чтобы при долгом отсутствии сна (2-3 дня) пешка приобретала состояние "Нужно отоспаться" при котором пешка падает в ближайшем месте и спит до упора без возможности разбудить (что довольно реалистично).

**Comment by masakitenchi** [comment]
Closed as too old
