### ISSUE TITLE
Молоток нельзя починить на ремонтном станке

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1955]
См. темы. Все можно, а молоток нельзя.

**Comment by ronekarleone** [comment]
На самом деле нельзя починить вообще никакие инструменты, кроме тех, для которых стоят дополнительные категории. Например разводной ключ также относится и к WeaponMelee, поэтому его можно чинить, а метлу или молоток нет.

**Comment by ronekarleone** [comment]
Этот  пул реквест #1956 решает проблему и позволяет чинить Инструменты в задании "Починить простое оружие".

**Comment by skyarkhangel** [comment]
Добавлено. спасибо
