### ISSUE TITLE
Пешки не работают

### ISSUE THREAD

**Issue by Nikovit** [skyarkhangel/Hardcore-SK#1957]
Пешки не работают как будто работа для них не назначена. Также вручную нельзя отправить пешку на работу, при клики правой кнопкой мыши по станку, предмету и т.д. не появляется контекстное меню.

Пробывал начать новую игру, но поселенцы по прежнему не хотят работать.

**Comment by ronekarleone** [comment]
На выбор:
- не установлено задание или оно в suspend, или выполнено;
- нет ингредиентов или они запрещены;
- нет нужного скила;
- запрещено зоной;
- пешке не установлено разрешение на данные работы;
- и пр.

Нужно больше информации.

**Comment by Nikovit** [comment]
Я удалил все папки и настройки модов вручную, заново установил Hardcore-SK и пешки заработали. Но все равно спасибо за ответ)))))
