### ISSUE TITLE
Стеганку нельзя переработать

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1958]
Стеганку нельзя переработать на верстаке кожевника

**Comment by ronekarleone** [comment]
Темпер тоже нельзя переработать

**Comment by Pepelnica1488** [comment]
чел забей там РИМАТОМИКС УУУУУУУУ

**Comment by Zim777** [comment]
![2](https://user-images.githubusercontent.com/46481732/71550009-b29faf00-29cf-11ea-85c5-e9819177c0c1.png)
Отлично Стёганка перерабатывается

**Comment by Zim777** [comment]
Вы не можете найти эти два предмета в фильтрах?
А все просто - "стЁганка" и "тЭмпер"
Протирайте глазки

**Comment by ronekarleone** [comment]
Оу! Спасибо
