### ISSUE TITLE
Частое срабатывание события изменения черты характера

### ISSUE THREAD

**Issue by ronekarleone** [skyarkhangel/Hardcore-SK#1959]
Семь срабатываний события за 3 дня. При этом 4 раза подряд в течение часа. И все на подавленность.
Теперь половина колонистов имеет -12 к настроению,  хотя  них вроде все нормально было.
Это вообще легально?) Может поправить какой-нибудь коэффициент?

![image](https://user-images.githubusercontent.com/25797150/71551219-ff48b180-29f2-11ea-99c9-3c39f423397d.png)

**Comment by ronekarleone** [comment]
При этом половина событий не отработало. Сообщение есть, а трейт не появился.

**Comment by skyarkhangel** [comment]
Для разных персонажей срабатывало, не помнишь? Если для одного персонажа несколько раз это баг, для разных это нормально.

**Comment by ronekarleone** [comment]
Две вроде повторно сработали: у пешек было -6, стало -12. Остальные на новых прокнулись. Довольно странное событие. Условие срабатывание непонятное. Вроде бы пешки более менее довольны. В итоге у большинства оно превратилось в "Закаленный". Не уверен, что это баг, просто странное событие.

**Comment by Proha5** [comment]
А как отключить эти события? Искал не нашел.

**Comment by masakitenchi** [comment]
Closed as too old
