### ISSUE TITLE
Кровь снаружи

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#1960]
![image](https://user-images.githubusercontent.com/47127651/71643637-20e4ba00-2ccd-11ea-82dc-0b39ed32d44c.png)
ps не знаю влияет ли это на скорость игры но может все таки сделать что бы она исчезала снаружи хотя бы за сезон?

**Comment by Leslov** [comment]
Дождик все смоет. Если хочешь по читерски сразу убрать ее, то отметь домашней зоной и в разделе RuntimeGC нажми "Убрать грязь в домашней зоне"

**Comment by Pepelnica1488** [comment]
дождик ничего не смоет,был ливень несколько дней толку ноль
ps может тебе ещё игру в 1 кнопку выиграть клоун?

**Comment by Pepelnica1488** [comment]
![image](https://user-images.githubusercontent.com/47127651/71773866-e18cc680-2f75-11ea-85ae-703abc5ff05a.png)

ух уж этот дождик год прошел а срач остался
