### ISSUE TITLE
Странная переноска

### ISSUE THREAD

**Issue by SkydarIndependent** [skyarkhangel/Hardcore-SK#1961]
Поселенцы раскладывают некоторые объекты (песок, гравий и т.д.) по 5-10 штук на одной клетке, из-за чего склады постоянно приходиться расширять

**Comment by Leslov** [comment]
Подозреваю, что это происходит из-за того, что в момент начала переноски стак, в который было бы логично положить предмет был занят кем-то другим

**Comment by Zim777** [comment]
![2](https://user-images.githubusercontent.com/46481732/71684616-aab08800-2d9e-11ea-9547-c086352903a6.png)
Просто поставьте чуток повыше приоритет. Или вручную отдайте команду сложить в стак.
