### ISSUE TITLE
MISSING RECIPES AND BUGS FIX Your Game

### ISSUE THREAD

**Issue by janglejuice** [skyarkhangel/Hardcore-SK#1962]
-NO Make Silage recipe exist even after research after building steel bio-refinery
 bio refinery description says: A machine for making biodiesel and silage.
  NO Make Silage recipe exist
-TAILORING/CRAFTING BENCHES MISSING BUNCH OF RECIPES AFTER RESEARCH
Doctor's cutters & pincers X Com overalls armor just to name a few
-NanoReplication Research does nothing
  no nano printer to replicate items

you expect donation without fixing the basics of the game is this a joke?

**Comment by SampsaxD** [comment]
Descriptions are not up to date on most of the things. Silage can be made using the butcher table.

A lot of tailoring recipes are disabled intentionally. There's a patch to enable all of them in the #patches in Discord.

Nanoreplication is the only valid issue here. Probably was removed at some point without removing the research.

Why are you so hostile? You paid nothing for this modpack, nobody is "expecting" a donation, and with the modpack still under development things are expected to not be 100% perfect.

**Comment by janglejuice** [comment]
fine I am sorry for being hostile but maybe you should have that information availble here also? I am considering donating but its very frustrating when I am playing and there is no information about it. also compatible mod list on github (https://goo.gl/yvjYDV
) is some application list not a compatible modlist on this page just seems careless

Thx

**Comment by janglejuice** [comment]
"even just saying in github for the latest bug update/ information, visit discord" would be helpful

**Comment by SampsaxD** [comment]
Try [this one](https://docs.google.com/spreadsheets/d/1i5eWzeJCNSgWl-q8cnTRsiOXZOcvtZAWdtRA1BNn0HY/edit?usp=sharing) for compatible mods.

I agree a lot of the things about this modpack are very obscure, and it could use an updated guide. For now best you can do is ask for help in the discord if you find something that seems odd.
(In general the [Discord](https://discord.gg/eRXjeA) has the most information about this pack)
