### ISSUE TITLE
Отсутствие тактического бронежилета в списке крафта

### ISSUE THREAD

**Issue by CountRendor** [skyarkhangel/Hardcore-SK#1964]
После изучения технологии "бронезащита" тактический жилет не появляется в списке крафта швейной машинки. В разделе "помощь" крафта тоже нет

**Comment by Zim777** [comment]
Часть вещей и оружия не доступна к крафту - ваши караваны, торговые караваны, торговцы. лут с рейдеров, квестовые объекты на карте, квесты на обмен и так далее к вашим услугам.
Впрочем, если вас это не устраивает - идете в дискорд в канал patch и вытягиваете патчик на весь крафт вещей.
Приятной игры, уважаемый хики
