### ISSUE TITLE
Неправильный расчёт крафта.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1975]
Изобрёл длинные луки. Дал команду крафтить до двух штук. Рабочее место выдало, что крафт невозможен, ибо они уже есть. Засчитались луки, лежащие вдалеке от лагеря на земле возле трупов.

**Comment by kismatvei** [comment]
В настройки задачи есть пункт, делать до n до *кол-во на складе"склад n"*
