### ISSUE TITLE
Средневековый пластик

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1979]
Изучил пару технологий средневековья на напольное покрытие. Теперь у меня масса вариантов деревянного и прочих мраморных полов, изготавливаемых из пластика - линолеум. Оно, конечно, интересно, только что пластик делает в средневековых технологиях? И что плохого было в старом варианте?

**Comment by Zim777** [comment]
Пластиковые покрытия - это имитации покрытий из риматомикса

**Comment by SetAriman** [comment]
Хз что за риматомикс, но в игре это имитация покрытия из дерева и камня. И сделана она из пластика, о котором в средневековье даже и не мечтали. Не тот уровень технологий. С таким же успехом можно вместе с длинными луками изучить плазменное оружие - а почему нет? Стреляет плазменными "стрелами", имитирует луки, все дела...
