### ISSUE TITLE
Request for Misc inct to be updated

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#198]
As the title suggests, it fixes problems with pawns returning from going off the map. I figured it would have been incorporated by now after the forum posts about it. For the moment I manually replace it and it works fine I haven't had any issues S: been using it for 4 or so days no problems.

**Comment by Vigilence** [comment]
So if they leave they won't come back if I use the version included in this mod?

**Comment by Vigilence** [comment]
There is a new version of misc incidents as well as a patch if you are using prepare with map generator.  

https://ludeon.com/forums/index.php?topic=3612.0

**Comment by zakhad** [comment]
Depending on their equipment the Misc Incs couldn't calculate their firepower on the weapons some of the stats were missing so it'd reset or something, Haplo the mod author did a hotfix as a workaround so 

To quote Haplo in the forum after I asked him what he did to fix it. 

"The new error is the log I've added to maybe figure out what goes wrong in there..
The problem seems to happen in my function CalcVerbValue. In there I look for various stats to calculate a value for the firepower the pawns have with them. And with the Great Bow you have it looks like one of these stats isn't available. For now I just threw a try-catch around it all that gives me some information about the error but doesn't cause a full crash that prevents the respawning."

I've just been doing it manually and wondered why It haven't been updated as part of the pack considering people were having problems with it.

**Comment by Vigilence** [comment]
After I updated it and added the patch my guys came back fine, and with loot too :D

**Comment by skyarkhangel** [comment]
Updated
