### ISSUE TITLE
Привлекательность полов.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1980]
Как-то странно выходит, что из одного и того же количества блоков камня - например мрамора - строятся полы как с привлекательностью 4, так и 0. Ну и в промежутке. По идее на более простую, неказистую кладку, и расход должен быть ниже. Может качественный пол кладётся чуть дольше, не написано, но как по мне это всё равно неправильно.
P.S. А если потратить 3 блока вместо 4, то пол станет ещё и уродливым, -1. Какой смысл от уродливого пола, на который к тому же уйдёт почти столько же ресурсов, как на великолепный?

**Comment by shikulja** [comment]
количество блоков одинаково, расчет идет из простоты добычи ресурсов.
У блоков с -1 (бетонные) (и кафельные) идут в склад и мед. кабинет соответственно.
бетон с -1 вроде бы безопаснее, и возможно температура не так быстро подымается.

Сам не уверен, так как описание не содержит важных примечаний, хоть смысл данных блоков соблюден.

**Comment by SetAriman** [comment]
В смысле? Так указано сколько блоков камня тратится на один квадрат. И потратив 4 мрамора, ты можешь получить как 0 привлекательности, так и +4. Всё равно, как в магазине за 10 баксов купить как пачку лапши, так и полную корзинку её же.

Бетонный пол изначально плюсовой. Потом появляются варианты похуже и получше.
