### ISSUE TITLE
Обновлённый карьер.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1981]
Карьер перестал иногда давать светокамень. Что очень расстраивает. На карте его далеко не всегда сыщешь. Тем более в первой половине игры.

**Comment by Kiriharas** [comment]
У меня всё работает, можешь зайти в настройки мода Quarry и посмотреть точные шансы добычи ресурсов

**Comment by SetAriman** [comment]
Cпасибо, значит не везёт. 60% выкопано. (
