### ISSUE TITLE
Plant pot bug?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#199]
Hi,
My colonist when plant dandelion flower it look like they planted it on flor  below pot.
![untitled](https://cloud.githubusercontent.com/assets/21177680/18129622/d0b37eba-6f8b-11e6-80eb-53b09b99ae57.jpg)

**Comment by jnkyacc** [comment]
Astralagus, Dandelion, Crocus - bugged

**Comment by skyarkhangel** [comment]
Reworked yesterday :) plz test
