### ISSUE TITLE
Привлекательность еды.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1990]
У некоторых видов еды есть параметр привлекательности, и он аж -4. Причём это нормальная еда. Зачем делать её уродливой?

**Comment by kismatvei** [comment]
Показатель привлекательности относиться к характеристике комнаты, никто не говорит что она уродливая, просто ее место в холодильнике, а не рядом со скульптурной из нефрита

**Comment by SetAriman** [comment]
А кто мешает еде лежать на столе в столовой рядом со статуей из нефрита? И о том, что она уродливая и портит вид окружения, говорит сама игра. Включи фильтр красоты и убедись. И зайди в свойства еды и убедись.

**Comment by Zim777** [comment]
Кто мешает положить еду в поднос, холодильник или горшок возле стола?

**Comment by SetAriman** [comment]
А кто мешает сделать еду НЕ-уродливой? У тебя дома еда уродливая? Жена ставит борщ на стол, и ты, морщась и отворачиваясь от этого мерзкого непотребства, его ешь? У меня не так. И у других не так. Даже простой бутерброд на скорую руку и то хорошо выглядит. Как и должно быть.  С чего вообще у готовой еды - да хоть у аккуратного разделанного мяса - негативный параметр внешнего вида? Непривлекательной она станет, когда испортится.
