### ISSUE TITLE
Странные гости.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1996]
Не раз замечал. Шли беженцы. Зомби их погрызли. Недогрызенный очухался и заявляет, что я его якобы спас и он мой гость. (А потом бегаешь за ним с мечом и ждёшь, когда он станет зомби.)

**Comment by kismatvei** [comment]
Мод на гостеприимство и мод на зомбиленд, продукт от разных мододелов с разными взглядами на мир Rimworld

**Comment by SetAriman** [comment]
Зомби-мод тут не причём. Думай головой. А то куча ответов от тебя и сплошные выдумки. Беженцев мог и суслик покусать. После чего, очнувшись, они вдруг посчитают тебя спасителем и навяжутся в гости. Не задействована механика спасения. Если бы я его действительно спас, другое дело.

**Comment by Zim777** [comment]
Такая уж механика,что спасенный или очухавшийся мимокрокодил становится гостем временно.
Можешь его конечно арестовать, с последствиями.
Пишите в баги самому автору мода гостей.
