### ISSUE TITLE
Польза пеноксициллина.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#1998]
По механике игры подразумевается, что его надо производить - вместе с предыдущими продуктами - в конских дозах и жрать всей базой каждые 5 дней: а вдруг болезнь? Не лучше было бы изменить механику, чтобы он помогал лечению болезни? А сами эти болезни сделать более долгодействующими. Т.е. чтобы их можно было вылечить и без пеноксициллина, но раза в полтора дольше. Тогда будет иметь смысл исследовать это производство и делать запас на базе. А сейчас проще забить на него и лечиться по простому.

**Comment by Pepelnica1488** [comment]
Самый бесполезный препарат автоматом идет на продажу ни разу не помогал

**Comment by kismatvei** [comment]
Механикой игры подразумевается, чтоб пешка врач, когда пойдет лечить пациента который болеет малярией, не смог заразиться от него

**Comment by SetAriman** [comment]
В механике игры пешки не заражаются друг от друга.
