### ISSUE TITLE
Can't repair broken down hand sawmill

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#200]
It used to work a few days ago.  My pawn has the repair skill selected and at 10 but he can't repair the sawmill.  Is it because a lack of repair ingredients?  I have over 20 components and around 300 wood planks, and around 300 wood logs.

![screenshot 34](https://cloud.githubusercontent.com/assets/16742086/18141151/6225320e-6f86-11e6-83c2-db46425ec570.png)

**Comment by Vigilence** [comment]
Also can't repair even if it's not broken down like in the picture above.

**Comment by Vigilence** [comment]
To fix issue I have to deconstruct and reconstruct.

**Comment by skyarkhangel** [comment]
Old version
