### ISSUE TITLE
Перенос мебели.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2000]
Когда пешкам нечего делать, переносом мебели начинают заниматься те, кто не назначен на строительство. Соответственно с нулевым уровнем строительства и без инструментов. В результате, один стул могут переставлять часами.

**Comment by AndreiAvinov** [comment]
Раскрой приоритеты переноски - там должна быть перестановка мебели, отключи её для не строителей

**Comment by SetAriman** [comment]
о_О Спасибо. Не подумал бы, что могут быть приоритеты для тех, у кого нет приоритетов. Такие вещи надо вырубать по-умолчанию.
