### ISSUE TITLE
Ненужный табак.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2003]
На складе завалялись листья табака. Похоже это единственный предмет, который я за долгие годы так и не смог никому продать.

**Comment by kismatvei** [comment]
Листья табака - сырье необходимое для производства сигарет, которыми можно торговать, удовлетворять потребности пешек или развлекать их

**Comment by SetAriman** [comment]
Для чего они и так ясно. Вопрос в том, что их очень редко кто покупает. Как и бивни слона, кстати. Тоже могут годами пылиться при том, что почти ежедневно вызываешь торговцев.
