### ISSUE TITLE
Тупые дроиды.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2004]
У рабочего дроида ремесло всего 4 единицы. То есть он вроде и ремесленный, но почти ничего не умеет. А на том, что умеет, качается ТАК медленно. Можно поднять ему ремесло до 7 по-умолчанию? Чтобы он мог плавить базовые металлы толком.

**Comment by kismatvei** [comment]
Разработчиком мода было задумано - дройды способны выполнять только действия связанные с крупной крупной моторикой:
Распилить бревно на станке ✓
Собрать компоненты или выковать слиток металла ×

**Comment by SetAriman** [comment]
Ну так металлы он и не плавит. Навык никакой. По факту это не рабочий дроид, а дроид-уборщик. Чуть лучше бота-уборщика. Это таки две большие разницы. Для баланса более сложную работу ему можно было бы отключить. А насчёт 3к - ну так и раба можно выкупить за малые деньги, одноразово, только работать он будет куда лучше.

**Comment by kismatvei** [comment]
Работать он будет лучше, есть он будет, спать он будет, а дройды не спят и способны весь день в карьере проработать

**Comment by SetAriman** [comment]
Тогда зачем он вообще нужен по такой логике, если уборку лучше поручить боту?
