### ISSUE TITLE
Вредители обнаглели.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2006]
Получаю сообщение о вредителях посевов. Ну, думаю, опять жуки завелись в теплицах. Оказалось - куропатки. о_О Это игровой юмор или ... ?

**Comment by AndreiAvinov** [comment]
Вредители = любые мелкие животные жрущие посевы

**Comment by SetAriman** [comment]
С чего вдруг? Вредители это те, кто вредят. О размерах при этом ни где не сказано. Например - механоиды. Вылезут, например, тоже посреди теплицы и потопчут всю кулубнику, выращенную собственными руками.

**Comment by dodther** [comment]
В дев версии пишет "Пожиратели посевов"

**Comment by SetAriman** [comment]
Вопрос не в тексте, а в логике происходящего. Когда у тебя появляются жуки, это понятно. Они где хочешь могут появиться, хоть в горшке. Это жежуки. Но когда у тебя закрытая база, в ней закрытая теплица, и внутри вдруг материализуется стая куропаток, выглядит малость дико. Да и не только куропатки, ещё какие-то животные раз были.
