### ISSUE TITLE
Склады автоматически объединяются

### ISSUE THREAD

**Issue by SkydarIndependent** [skyarkhangel/Hardcore-SK#2007]
Если создать новый склад другого цвета рядом с старым складом, то новый склад автоматически будет присоединен к старому.

**Comment by SetAriman** [comment]
Смотря как создавать. Если создать один склад, а потом **заново** начать создавать рядом новый, заново открыв панель, всё без проблем создаётся, сколько угодно.

**Comment by Zim777** [comment]
Тут какая штука.
Если мы создали склад и не убрав выделение, создаем склад рядом впритык второй - они объединятся. А если мы создали один склад, тыкнули рядом на пустое место так, чтоб выделение с первого снялось и создаем следующий - они не объединятся.
