### ISSUE TITLE
Не разбираются сломаные боты. 

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2008]
Задача "разобрать механоида" есть, боты туда входят, но сломанный бот ни кто не разбирает.

**Comment by kismatvei** [comment]
Сломанный бот(пылесос/грузчик) не является механойдом, его можно починить за
> 20 стали и 1 компонент (пешка строитель лвл 5) *старая инфа*

**Comment by SetAriman** [comment]
Вопрос не в починке, а в разборке. На складе могут пылиться несколько штук, которые пешки подобрали с погибшего каравана. Или которые погибли вместе с дрон-станцией. И с ними ничего нельзя сделать. Ведь чинится он только тогда, когда у него есть дрон-станция.

**Comment by kismatvei** [comment]
Боты это не механойды, я хотел тебе это объяснить

**Comment by SetAriman** [comment]
Да мне без разницы кто его папа. Есть задача на станке: разобрать механоида. В настройках ЭТОЙ задачи есть пункты: разборка бота-носильщика и разборка бота-уборщика. И эта часть задачи не работает.
