### ISSUE TITLE
Map generation. "Wood Log Stone Wall"

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#201]
Just reporting a typo. I'm using the first github version that includes [A14] Psychology

Edit apparently I didn't include the imgur http://imgur.com/3l0mzMl

**Comment by jnkyacc** [comment]
I'm afraid that it not a typo this is real "Wood Log Stone Wall". All walls were reworked in SKmod but not Map generator.

**Comment by skyarkhangel** [comment]
Fixed? pls check this with latest update.

**Comment by skyarkhangel** [comment]
Fixed a long time ago
