### ISSUE TITLE
Не правильно считает количество песка.

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2020]
Задание "Раскрошить щебень/камень в песок не правильно определяет количество имеющегося песка. Ставишь создавать до 200. А он определяет что уже есть 300. Хотя его 15 штук. Ладно. Ставлю создавать до 500. Потом смотрю, опять не хватает песка. В заданиях смотрю, говорит что уже есть 600, хотя на самом деле 5 штук. И именно столько определяется в других крафтах, когда например, создаешь кремний. А вот при песка видит почему то не 5 а 600.

**Comment by Zim777** [comment]
Внимательно посмотрите по карте и на складах, сундуках  и тд. Вероятно у вас где-то завалялась кучка песка.
![1](https://user-images.githubusercontent.com/46481732/77224211-fe479c00-6b6b-11ea-9d18-aa66e0886b23.jpg)
![2](https://user-images.githubusercontent.com/46481732/77224213-00115f80-6b6c-11ea-955a-0494c851b4e0.jpg)
![3](https://user-images.githubusercontent.com/46481732/77224214-00115f80-6b6c-11ea-80c4-12e70acc35dd.jpg)

**Comment by Zim777** [comment]
Также вы можете определить только один склад для песка, и указать - учитывать только именно этот склад. Например вот так.
![4](https://user-images.githubusercontent.com/46481732/77224383-ce999380-6b6d-11ea-8d10-70b63f41a86b.jpg)
![5](https://user-images.githubusercontent.com/46481732/77224385-cfcac080-6b6d-11ea-8538-c6be78794e34.jpg)

**Comment by Proha5** [comment]
Zim777, Точно. Спасибо. Все так и есть. Просто с толку сбил поиск. Он подсветил еще и почву из песка. И не заметил, что кое где кучи песка валялись. Можно было бы им дать разное название, что бы в поиске не смешивались эти 2 вида песка.
