### ISSUE TITLE
Мелководье под пирсом

### ISSUE THREAD

**Issue by Selengiks** [skyarkhangel/Hardcore-SK#2030]
Невозможно никаким способом, кроме инструментов разработчика, терраформировать мелководье под пирсом. Думал, нужны помпы, а не, они так же ничего не делают.
![image](https://user-images.githubusercontent.com/38987970/77475849-19dbcc80-6e22-11ea-813b-b0c8fca0f90d.png)

**Comment by AndreiAvinov** [comment]
eeeeh, а как эта поверхность вообще появляется?

**Comment by Selengiks** [comment]
Появилась, под пирсом, ну или когда я сломал пирс для рыбалки. Сразу ли, или нет (появилось это мелководье под пирсом) я не знаю, не следил.

**Comment by Proha5** [comment]
Selengiks, а как инструментами разработчика удалить? Это ведь режим разработчика? И что именно там нужно выбрать?

Лучше бы удалили этот пирс вовсе. Знал бы, что он такую свинью подложит, никогда не построил бы.
