### ISSUE TITLE
Приоритет веселья. И выгрузка вещей по расстоянию.

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2031]
1. Поселенцы отдают предпочтение веселью, даже если приоритет у какого то занятия выставляешь в 1. Удовлетворенность 97%, а он бежит в другую часть базы телик смотреть. Хотя рядом куча станков с работой.

2. Может можно улучшить мод, который позволяет переносить нескольких предметов? Чтоб выгружал вещи не в случайном порядке, а отсортировано по расстоянию до склада? Вначале те, что ближе.

**Comment by Zim777** [comment]
По второму пункту - это надо обращаться к авторам модов, которые использует сборка.
