### ISSUE TITLE
Зачарование на броню утратило полезность.

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2035]
Раньше могли выпасть чары +0.33 брони. Что означало +33%. Но теперь, когда броня измеряется в MPA RHA, эта прибавка стала мизерной. Была защита 11 мм, стала 11.33мм. А раньше  было 0.5 стало 0.83. Только по огнезащите осталось как раньше.

**Comment by Zim777** [comment]
Они раньше были слишком полезными. Но в любом случае  они пройдут балансировку, когда сам баланс с оружием, материалами и вещами устаканится
