### ISSUE TITLE
Зациклилось событие

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2036]
Каждые день по 1-3 события на заражение чумой животных.
Так же, уже дней 20 никто не нападает.
Менял рассказчика и сложность.
Случилось это после обновления на последнюю версию. До этого мод был обновлен от 22 февраля.

**Comment by Zim777** [comment]
Ничего не зациклилось, ввели новую механику - заразные пешки и животные "сорят" заразой - надо вовремя убирать, иначе от них будут заражаться другие.
Плюс юзайте для пешек и животных пеноксицилин - очень помогает

**Comment by Zim777** [comment]
При смене рассказчика и сложности - рассказчику порой до 60 дней приходится адаптироваться под новые условия

**Comment by Proha5** [comment]
Пеноксицилин на здоровых применять?

**Comment by Leslov** [comment]
Здоровым и выздоравливающим тоже можно, чтобы повторно не заразились

**Comment by Zim777** [comment]
Да, до того как они словят малярию или чуму.
Кроме того, если вас сильно напрягает грипп и другое - можете добавить в файл Mods\Core_SK\Patches\Drugs.xml  пару строчек на выбор

<li>Animal_Plague</li> - защищает животных от чумы
<li>FoodPoisoning</li> - защищает пешек от отравления едой
<li>WoundInfection</li> - защищает пешек от заражения ран
<li>Fever</li> - защищает пешек от лихорадки
<li>Flu</li> - защищает пешек от гриппа
<li>Ebola</li> - защищает пешек от эболы
<li>Measles</li> - защищает пешек от кори
<li>Pneumonia</li> - защищает пешек от пневмонии  


Добавлять только `<li>Flu</li>` в  блок <value> </value>
например так
```
<value>
<li>Animal_Plague</li>
<li>Flu</li>
</value>
```

**Comment by Proha5** [comment]
Zim777, есть какая либо возможность обнулить/перегрузить события? Спец. команда, или в сейве что то изменить? Ждать 60 дней не хочется, и нет гарантии, что починится.

Может нападения прекратились из за постройки устройства из rimatomics, которое обнаруживает вторжения? Оно еще ни разу не предупредило ни о чем. Апгрейдил его, тоже тишина.
