### ISSUE TITLE
Exception ticking Gas_BlackSmokeХХХХХХ

### ISSUE THREAD

**Issue by Selengiks** [skyarkhangel/Hardcore-SK#2038]
Собственно, консоль постоянно забита под завязку сообщениями, на подобии теми как на скриншоте ниже. И как только пошли эти сообщения, начались дикие лаги. Было и так плохо, порядком 20 кадров, сейчас не подымается выше 10-15.
Сообщений мало, ибо как раз почистил через Runtime
![image](https://user-images.githubusercontent.com/38987970/77805234-13e82480-708a-11ea-8e00-9e1ce900fbf6.png)

**Comment by Zim777** [comment]
У вас самая последняя версия сборки?
Насколько я помню - данная проблема уже была исправлена

**Comment by Selengiks** [comment]
Значит сейчас обновлюсь. У меня сборка за 20 марта.
Кстати. Такой вопрос, пока тема читается. Перестали адекватно работать гранатомёты и пулемёты, стационарные. Как только ставишь колонистов, вроде стреляют. Но спустя какое-то время, просто перестают реагировать. Вертятся себе да и всё. Если вручную цель указать, начинают бесконечно целится, или дальше себе вертеться.

**Comment by Zim777** [comment]
У многих пулеметов и гранатометов есть мертвая область, может все враги в этой области? или нет патронов

**Comment by Selengiks** [comment]
Это я знаю. Но фишка в том, что враги в радиусе поражения, и не в мёртвой зоне

**Comment by Selengiks** [comment]
Как столкнусь с этим опять, так и сделаю пожалуй

**Comment by Zim777** [comment]
И учтите, что многих стационаркам нужно свободное место справа и слева, чтобы поворачивать ствол

**Comment by Selengiks** [comment]
Это с недавних пор так? Спрашиваю, ибо немного раньше они прекрасно работали. Проблемы начались лишь недавно

**Comment by Zim777** [comment]
уже больше чем год многим турелям нужно место

**Comment by Selengiks** [comment]
Тогда не знаю. Как я их поставил, в одну клетку пространства, всё было ок, стреляли как положено. А пару дней назад стали вот так вот своевольничать. И да, вдруг о разном, я сейчас пишу за: агс-17, кпв и м249 стационарки

**Comment by Zim777** [comment]
Создавайте отдельный тикет, с подробностями и скриншотами, иначе это все просто вода

**Comment by Selengiks** [comment]
Ошибка дыма пропала, но, что печально, фпс просел ещё больше, с последней версией. В любом случае, спасибо
