### ISSUE TITLE
Забыли поправить огнезащиту у синтетической кожи.

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2039]
У нее осталось старое значение 150%. У всех остальных материалов не больше 17%.

**Comment by ArpoMo6** [comment]
Её исправили, на самом деле, просто у кожи андроида вообще не прописаны какие-либо статы и она тупо берет ванильный шаблон, где значение по умолчанию равно 150%.
Добавил коже статы. Отправил Скаю патч.
https://i.ibb.co/xDqZYmt/image.png
https://github.com/skyarkhangel/Hardcore-SK/pull/2103
