### ISSUE TITLE
Пешки с иммунитетом от болезни продолжают заражать других

### ISSUE THREAD

**Issue by Leslov** [skyarkhangel/Hardcore-SK#2040]
![image](https://user-images.githubusercontent.com/15822720/77834386-410a0500-7166-11ea-8e97-769746e860e9.png)
Скорее всего, в этом методе нужно добавить проверку на наличие иммунитета при попытке оставить след болезни

**Comment by Leslov** [comment]
![image](https://user-images.githubusercontent.com/15822720/77836129-46bb1700-7175-11ea-837f-215fb712a7a3.png)
Поправил, доработав метод вот так.

**Comment by Proha5** [comment]
Leslov, Это не баг.. Если у носителя чумы выработался иммунитет, он еще не избавился от инфекции и может заразить окружающих.

**Comment by Leslov** [comment]
Кому как, но по-моему игре это явно вредит

**Comment by Proha5** [comment]
Да нормально. Просто дольше в инфекционном отделении держать, до полного излечения.
Интересно, на каком расстоянии идет заражение, и влияют ли стены?

**Comment by Zim777** [comment]
Достаточно
- ввести параметры сопротивления болезни и стерильности всем вещам (уменьшится шанс заболевания и разбрасывания "грязи" на порядок)
- ввести хедиф на защиту от болезни на 15-20 после набора 100% иммунитета (уберется заболевание по второму и третьему кругу)
Плюс добавить препараты, которые дают временный иммунитет не только к чуме, но и грипу, эболе и тд, как тот же пенокс
