### ISSUE TITLE
GrammarResolver failed to resolve a text

### ISSUE THREAD

**Issue by Selengiks** [skyarkhangel/Hardcore-SK#2046]
Периодически проскакивает вот такая пачка ошибок
![image](https://user-images.githubusercontent.com/38987970/77957746-a08a2100-72dc-11ea-8cb7-dcc955090931.png)

**Comment by Zim777** [comment]
Нужен лог, а не просто скриншот ошибки

**Comment by Selengiks** [comment]
output_log файл?

**Comment by Zim777** [comment]
![image](https://user-images.githubusercontent.com/46481732/77961409-7176ae00-72e2-11ea-8379-0c1b3547fe69.png)
вверху - весь лог скопировать
внизу - конкретную выделенную ошибку

**Comment by Selengiks** [comment]
После вылета по неизвестной причине, снёс римку, сейчас ставлю *чистую*. Если ошибка снова будет, скину лог.
