### ISSUE TITLE
Нет способов получать обедненный уран.

### ISSUE THREAD

**Issue by d1ssolvedz** [skyarkhangel/Hardcore-SK#2047]
На последних ветках, или с момента внедрения Rimatomics убрали возможность получения обедненного урана путём крафта. Можно ли временно вернуть старую центрифугу с вырезанным рецептом на обогащенный уран? Иначе как минимум невозможно производить альфа поли.

**Comment by Zim777** [comment]
Мехов разбирайте  - будет сплав обедненного.

Пока не введут назад какой-либо способ получения другим столов - можете юзать заплатку 
https://cdn.discordapp.com/attachments/675752865905508365/675752986214924298/Recipes_Production.zip

заменить в
RimWorld\Mods\Rimatomics_SK\Defs\RecipeDefs

**Comment by Baldrvolsk** [comment]
мало того стены с повышенной защитой от радиации того же Rimatomics требуют для строительства сплав обедненного урана

**Comment by insidio118** [comment]
Стены мне лично не пригодились особо. Реактор сам не фонит если не разрушить. Фонят только израсходованные топливные стержни, которые можно безопасно хранить в бассейне, или сразу же отправить на переработку в плутоний. Вот из переработчика фонят ядерные отходы. Но фонят как-то слабо. Я хранил их в ящике в комнате с реактором за свинцовыми стенами из урана, и радиацию по 0.25 получали пешки которые в 3 клетках проходили изредка.
