### ISSUE TITLE
Chitlin Head dress won't complete!

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#205]
I have -6 work left and the pawn stands near it and won't complete it.  Noticed after a whole day of the pawn standing near that head dress and doing nothing.

I have 18 chitlin in stock.

![screenshot 36](https://cloud.githubusercontent.com/assets/16742086/18153565/69c8502c-6fcc-11e6-9a03-5a494f65d091.png)
![screenshot 35](https://cloud.githubusercontent.com/assets/16742086/18153572/6b52faa0-6fcc-11e6-9bc4-2ce75030c35f.png)
![screenshot 37](https://cloud.githubusercontent.com/assets/16742086/18153605/96a9c058-6fcc-11e6-9014-aff61f2216db.png)

**Comment by jnkyacc** [comment]
Dublicate #150

**Comment by skyarkhangel** [comment]
Already know error :)

**Comment by skyarkhangel** [comment]
Apparel craft reworked with fix this bug. So this problem solved
