### ISSUE TITLE
Стационарное оружие перестало стрелять.

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2051]
Раньше ставил операторов за орудия(пулеметы, автопушки), проверял, что снят запрет на обстрел, и дальше они сами держали оборону. Но сейчас они не выбирают цели. Стоят ждут, пока им не укажешь вручную цель для каждого. Никаких камней или преград нет.
Случилось это или после какого то обновления, или само по себе что то сломалось.

**Comment by Zim777** [comment]
Судя по всему, у вас дев-ветка?
Тогда это проблема нового СЕ, так как там есть проблема с радиусом реагирования на угрозы. Ребята сделали последнюю версию СЕ1,9 для римки 1,0 и забили на баги, кинушись делать СЕ под 1,1

**Comment by Proha5** [comment]
Да, dev. под 1.0.
А нельзя самим поправить?

**Comment by Zim777** [comment]
Очень много всего надо править. Пойдете в команду ХСК править?

**Comment by Proha5** [comment]
Zim777, ну вы скажите что поправить. Я в блокноте исправлю, выложу.

**Comment by Zim777** [comment]
Так вы сами найдите, что надо исправить и справиться, выложите

**Comment by Proha5** [comment]
Понял. Ладно, погуглю, попробую разобраться. Или просто переделаю оборону на турели из риматома.

**Comment by Casper969** [comment]
Такая же проблема. А можно как то откатиться на старую версию, чтобы все работало?

**Comment by Zim777** [comment]
> Такая же проблема. А можно как то откатиться на старую версию, чтобы все работало?

Такая проблема есть на всех старых версиях - дальность стрельбы турели равен дальности оружия в руках пешки. стоящей за турелью (можно давать бинокль в руки - самое дальнобойное "оружие") - или в ручную нацеливать
на самой новой версии скоро это исправлено будет(если уже не сипарвили)

**Comment by Casper969** [comment]
Да вот проблема в том, что у меня Mac OS и обновление для меня это танец с бубнами - я не понимаю где найти новую/старую версию, а инструкция на сайте даже ссылок на архив не дает.

По багу - минометы стреляют норм, а вот ракетные установки даже при наведении в ручную не стреляют, точнее как - снаряд вылетает, но никуда не попадает, т.е. тупо исчезает и все. При этом снаряд расходуется.
