### ISSUE TITLE
Диета больных животных

### ISSUE THREAD

**Issue by Proha5** [skyarkhangel/Hardcore-SK#2065]
Заболело 4 слона. Пока те без сознанки валяются, вырабатывают иммунитет, поселенцы кормят их хорошей человеческой пищей, хотя рядом с ними комбикорм. Как указать им диету?
За 3 дня все запасы ушли в ноль, хотя был переизбыток от ферм.

**Comment by Zim777** [comment]
Только сторонними модами - Тунан не предусмотрел диет для животных
