### ISSUE TITLE
"В четырёх стенах."

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2074]
Обновил игру и теперь думаю, зачем я это сделал? Играть стало весьма некомфортно. База в горе, но пешки много бегают на чистом воздухе, хоть и под крышами и с освещением. И если раньше только пара-тройка пешек иногда ловила дебафф "в четырёх стенах" и их приходилось отлавливать и заставлять тупо стоять на улице, пока ситуация не ухудшилась. Теперь приходится ловить практически ВСЕХ пешек, **весь** день, **каждый** день, нередко по паре раз за день одну и ту же пешку. Причём просто свежий воздух их, похоже, не устраивает. Надо чтобы крыш над головой не было. Играла стала кликером: без конца лови пешек и заставляй торчать столбом на огороде, пока им не станет лучше.

**Comment by AndreiAvinov** [comment]
дебаф контролируется модом open windows, можешь изменить насколько пешкам нужно гулять + для бафа можно сделать окно выходящее на естественный свет

**Comment by SetAriman** [comment]
Спасибо. Но раньше всё работало хорошо и логично на базовых настройках.

Какое окно - стеклянную крышу? Так их придётся ставить везде, где нет толстых крыш. Одно окно ничего не даст.

**Comment by Proha5** [comment]
Интересно, а как эти окна размещать, если база в горах?
Я вобще забил, принял как данность штраф к настроению в -9.

**Comment by SetAriman** [comment]
Кстати. Как-то эти окошки не так работают. У меня раньше исследователь постоянно получал этот дебафф. Поставил окно. Пешка сидит в рабочей зоне окна. Солнечный свет - есть, форточка открыта. Дебафф получает точно так же, как и раньше.

**Comment by Pardonius** [comment]
Решается достаточно просто - в горах есть дырки с тонкой крышей, либо сделать таковую. Все уличные развлечения ставятся так, чтобы пешка используя их, находилась на свежем воздухе.
Ну и защиту по периметру, десанты стрелять.

**Comment by SetAriman** [comment]
Вопрос не в извращениях, чтобы сходящие с ума пешки ждали конца игры, чтобы наделать дырок в горах. Вопрос в том, что мод ужесточает получение дебаффа, а для компенсации этого ставит форточки. Которые ... не работают в этом плане. (Да и визуально окно не вписывается в стену. И работает чересчур локально и требуя слишком много места.) Проще отключить корявый мод, чем извращаться с дырками. Развлечения на воздухе и прочее и без мода используются с той же целью.
