### ISSUE TITLE
Ошибка при старте игры после обновления до 735e910

### ISSUE THREAD

**Issue by surabujin** [skyarkhangel/Hardcore-SK#2081]
https://gist.github.com/65ae807524c191718c8a5ca0c75946b0

Попробовал снести все (игру через стим и папку из домашней папки пользователя "AppData/LocalLow/Ludeon Studios"), потом поставил по новой - игру через steam (залочено на версию 1.0) а мод через laucher - ошибка воспроизвелась.

**Comment by surabujin** [comment]
Уже вышло 2 обновления, после того, как при старте игры стала появляться ошибка. Причины которые я могу предположить в ее игнорировании - она проявляется только у меня, ее сложно исправить, она настолько ничножна что никого кроме меня не затрагивает.

**Comment by AndreiAvinov** [comment]
Игра вылетает при запуске? Если не вылетает и в самой игре показывается этот лог, то сделай скрин красных ошибок и скинь сюда

**Comment by Pardonius** [comment]
Отруби мод Real Ruins.

**Comment by surabujin** [comment]
> Игра вылетает при запуске? Если не вылетает и в самой игре показывается этот лог, то сделай скрин красных ошибок и скинь сюда

Лог ошибки приведен в первом сообщении. Вот еще раз - https://gist.github.com/65ae807524c191718c8a5ca0c75946b0

> Отруби мод Real Ruins.

Не хотелось бы, мне он нравится. Сама ошибка, проблем в игре не создает, на сколько я могу судить. Правда гранаты делать я еще не пробовал, довольствуюсь теми что добровольно приносят набегающие.

**Comment by kozachok3000** [comment]
В первом сообщении не лог ошибки, а лог игры. 2600 строк логов никто анализировать не собирается.

**Comment by surabujin** [comment]
> В первом сообщении не лог ошибки, а лог игры. 2600 строк логов никто анализировать не собирается.

Интересный у вас подход... этот "лог" сделан средствами самой игры именно т.е. используется механизм специально сделанный для уведомления о ошибках. Плюс в пояснении говорится что ошибка возникает сразу после загрузки... следовательно в этом логе нет никаких сторонних действий со стороны пользователя.

Как минимум вы могли бы отлистать его до конца и посмотреть что там. После чего вы, зная внутренности продукта могли бы в других частях лога найти то что может показать больше деталей о проблеме.

Если вы как разработчики не способны читать логи своего же продукта и использовать механизмы своего же продукта, то что-либо сообщать вам смысла нет. Даже сказать что проблема проявляется только у меня, вы почему-то не смогли... я могу лишь предполагать это по вашим "ответам".

**Comment by Zim777** [comment]
Да и так видно, что лог у тебя не полный явно - последние строчки - попытка загрузок карт с сервера руинами. Плюс в логе не написано - где красные ошибки, где желтые и конкретно их закинуть. Если игра не запустилась - значит у тебя в папке рима появилась папочка с названием даты вылета игры - там 2 файла лога.
Тебе пока что ответили только такие же юзеры как ты, тебе предложили варианты, тебе предложили правильно оформить. Ты решил, что ты умнее. ОК.

**Comment by surabujin** [comment]
Вот эта ошибка вылазит при старте
```
[RuntimeGC] Mod settings loaded.

Skipping RIMMSLoadUp.EagerPatchCleanup --- found LoadOnDemand assembly

SeedsPlease :: LoadingOnDemand CombatExtended

SeedsPlease :: LoadingOnDemand NaturesPrettySweet

XML error: Could not register node named "GrenadeRecipeBase" in mod Core_SK because this name is already used in this mod.

BodyDef QuadrupedAnimalWithHoovesAndAntlers has BodyPartRecord of Head whose children have more coverage than 1.
```

Сама игра не вылетает. "Правильным" оформлением, как мне казалось является использовать встроенный механизм сообщения об ошибках.

**Comment by AndreiAvinov** [comment]
Ошибка ничего не ломает, в деве уже исправлена
По поводу логов: далеко не всегда есть необходимость смотреть в достаточно сложночитаемый и подробный лог игры. Как правило хватает вот таких скринов/описаний красных ошибок

**Comment by Zim777** [comment]
Эта "ошибка" уже давно исправлена, причем в обеих ветках - dev и stable.
При этом она никак не влияет на работоспособность игры.
