### ISSUE TITLE
Стрельба по союзникам

### ISSUE THREAD

**Issue by DeaDRaTT** [skyarkhangel/Hardcore-SK#2085]
При стрельбе по животным, пешки могут задевать стоящих вплотную союзников.
![unknown](https://user-images.githubusercontent.com/63916371/79641071-e4ff3300-819d-11ea-8baa-c4110c934b1c.png)
![unknown (1)](https://user-images.githubusercontent.com/63916371/79641080-ef213180-819d-11ea-982a-51d85c03f7b3.png)
![unknown (2)](https://user-images.githubusercontent.com/63916371/79641118-20016680-819e-11ea-84f4-81b03801b2cf.png)

**Comment by surabujin** [comment]
Так, вроде бы, всегда было в CombatExtended.

**Comment by Zim777** [comment]
Так было всегда. Стрельба велась и по животным и по своим, если они были на линии огня.
Ставьте мод AvoidFriendlyFire.
