### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by ktrzos** [skyarkhangel/Hardcore-SK#2095]
Hello,
Are there any plans of new release for the newest version of Rimworld?

**Comment by sidfu** [comment]
yes it will be updated to 1.1
u have to remember the pack is bigger than the original game itself so takes time.

**Comment by ktrzos** [comment]
> u have to remember the pack is bigger than the original game itself so takes time.

Yeah, of course :). Do you have any time estimate for this?

**Comment by zakhad** [comment]
No longer relevant as 1.1 version of the pack out and being developed.
