### ISSUE TITLE
Sulphates/Sulfur=same item, different sources?

### ISSUE THREAD

**Issue by Masquerine** [skyarkhangel/Hardcore-SK#21]
Are the sulphates/sulfates produced from the oil refinery supposed to be the same item as sulfur produced from the ammo crafting table? One being produced from crude oil, the other from iron ore. Or should they be two, separate and distinct items with different uses? I'm not sure what the intent was with them, which makes defining a bit difficult.

**Comment by scyde** [comment]
Both products are sulfur. The general name of sulphates was there probably to explain some further recipes.

**Comment by Masquerine** [comment]
Thanks. I'll adjust the descriptions accordingly.
