### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by ochkoebanoe** [skyarkhangel/Hardcore-SK#210]
Боты садоводы и повары не работают.

Уборщик и переносчик получают по 2-8% радиации от урана. Заблевали мне пол карты. Кто не заблевал - взорвался. Пробовал изменить **ToxicSensitivity**, но ничего не дало.

Варианты решения: добавить кнопку ботам не подходить к урану, или дать резист.

**Comment by jnkyacc** [comment]
На них на сколько я помню зоны доступа распространялись. Когда тыкаешь на него, слева снизу 4 прямоугольника разноцветных. 

Садовод с right tool'сaми конфликтует еще с А13
Повар с CR, сломался на А14

**Comment by skyarkhangel** [comment]
Добавлен резист.

**Comment by jnkyacc** [comment]
@skyarkhangel а как насчет починить? :)
