### ISSUE TITLE
Щит и оружие ближнего боя

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#2108]
Враги приходят с щитами и оружием, которое с ним не работает.
К примеру, пришли туземцы с щитом и копьем, стоят вплотную, не могут атаковать и спамят  ошибку по кругу:
"started 10 jobs in 10 ticks. List: (Wait_MaintainPosture (Job_252929)) , (AttackMelee (Job_252931) A=Thing_Spelopede160524)"
Через правку сохранения отобрал щиты, заработало.
Пробовал несколько вариаций с разными щитами и разным оружием ближнего боя, что-то работает, а что-то надевать надевает, но атаковать уже не может.

**Comment by AndreiAvinov** [comment]
При генерации противники генерируются сразу с щитом, надо править пресеты противников чтобы не было двуручников с щитами

**Comment by nmn-dD** [comment]
Поселенцы частенько норовят взять лук + щит, арбалет + щит и стоять тупить, что доставляет неудобства. Конечно им можно создать "пресет" формы одежды в котором будет что одно. По началу это очень сильно напрягало и были трудности - приходилось перед боем\охотой  принудительно снимать щиты и т.п.  
Если можно исправить - это было бы великолепно

**Comment by Zim777** [comment]
nmn-dD
Все просто - в пресете запрещаешь щиты. Всего лишь пара кликов в самом начале колонии

**Comment by nmn-dD** [comment]
> nmn-dD
> Все просто - в пресете запрещаешь щиты. Всего лишь пара кликов в самом начале колонии

Ага, так и сейчас и поступаю, но первое время, очень напрягало. А с мелишниками как быть? У оружия где то написано, двуручное оно или нет? Потому что часть пешек отказывается нападать со щитом и оружием ближнего боя и просто рядом стоят, видимо как у топикстартера

**Comment by AndreiAvinov** [comment]
> > nmn-dD
> > Все просто - в пресете запрещаешь щиты. Всего лишь пара кликов в самом начале колонии
> 
> Ага, так и сейчас и поступаю, но первое время, очень напрягало. А с мелишниками как быть? У оружия где то написано, двуручное оно или нет? Потому что часть пешек отказывается нападать со щитом и оружием ближнего боя и просто рядом стоят, видимо как у топикстартера
> 

У большинства оружия в описании прописано двуручное оно или нет

**Comment by tornado02** [comment]
How can I disable enemies from coming with both shield and 2H weapons?
Thanks!

**Comment by zakhad** [comment]
@tornado02 not sure why you're writing this here and not on your own issue.

but  

IF<<<< it's the one i had issue with it's in RimWorld\Mods\Core_SK\Royalty\Defs\PawnKindDefs\PawnKinds_Kingdom.xml

`	
	<PawnKindDef Name="KingdomBrigand" ParentName="KingdomBase">
		<defName>KingdomBrigand</defName>
		<label>Kingdom Brigand</label>
		<combatPower>115</combatPower>
		<race>Alien_Nova</race>
		<canBeSapper>true</canBeSapper>
		<apparelAllowHeadgearChance>0.7</apparelAllowHeadgearChance>
		<gearHealthRange>
			<min>0.4</min>
			<max>1.6</max>
		</gearHealthRange>
		<apparelMoney>
			<min>960</min>
			<max>1370</max>
		</apparelMoney>
		<apparelTags>
			<li>MedievalKnightly</li>
			<li>MedievalShield</li>
		</apparelTags>
		<weaponMoney>
			<min>200</min>
			<max>300</max>
		</weaponMoney>
		<weaponTags>
			<li>MedievalMelee2H</li>
		</weaponTags>
		<inventoryOptions>
			<skipChance>0.8</skipChance>
			<subOptionsChooseOne>
				<li>
					<thingDef>SmokeleafLeaves</thingDef>
					<countRange>
						<min>3</min>
						<max>12</max>
					</countRange>
				</li>
				<li>
					<thingDef>vodka</thingDef>
					<countRange>
						<min>1</min>
						<max>3</max>
					</countRange>
				</li>
			</subOptionsChooseOne>
		</inventoryOptions>
	</PawnKindDef>`

get rid of either 			<li>MedievalShield</li> or  	<li>MedievalMelee2H</li>

The same would apply to anytime you see a pawn, check it's race and try to find out it's unique tag like KingdomBrigand, use a program like astrogrep to search within the mods folder for KingdomBrigand and it would point towards Mods\Core_SK\Royalty\Defs\PawnKindDefs\PawnKinds_Kingdom.xml once in there you'd find the appriopriate tag and delete it. Sky mentioned something to me a while back - something along the lines of CE not checking when spawning a pawn if it has both tags and invalidating that pawn - but yeah normally it would do a check and not spawn or so I'm to believe. Atm it's not working so you'll have to delete one of the entries you prefer them not to use i,e shields or 2 handers.

**Comment by tornado02** [comment]
Thank you for answering. Appreciate it a lot.
