### ISSUE TITLE
No Kibble or alternative farm food available at neolithic.

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#211]
There is no kibble or alternative animal feed available at neolithic levels.  This is a great imbalance as the animals will consume your food instead rendering the ability to stock up on food difficult.

Animal Husbandry I and II do not provide this recipe as it should.

Suggestion: Animal Husbandry I provides the ability to cook kibble on Small Butcher table and higher.

![screenshot 42](https://cloud.githubusercontent.com/assets/16742086/18214317/584901b2-711a-11e6-858b-6d303851f8a3.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/16742086/18214318/584e8d80-711a-11e6-9f7e-9129360e0b05.png)

**Comment by jnkyacc** [comment]
Fixed.
