### ISSUE TITLE
Нерф глины и торфа. 

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2114]
Наконец до них добрались и ... перекосили в обратную сторону. Раньше глины и торфа было полно и на халяву. В результате обычные электростанции были имбой - максимум электроэнергии за размер занимаемого места и простоту добычи топлива. Теперь же добычу торфа и глины практически уничтожили. Халявной добычи нет. А та, что есть, работает в мизерных объёмах, полностью уничтожая почву. С одной стороны некая логика есть, с другой - новый вариант такой же дурацкий, как и старый. :(

**Comment by Zim777** [comment]
Если перекопать на караю карту или в соседней клетке в лагере 20-30 клеток почвы в скалистую грязь - можно получить от 2к глины, 3к земли, 4-5к песка и щебня, а также около 500 торфа и некоторое кол-во удобрений. Это не имба?

Кстати, в подземных залежах есть торф, внезапно =)

**Comment by SetAriman** [comment]
В тераморфинге указано 5-20 единичек торфа с клетки. В различных вариантах. И даже если ты получишь целых 500 торфа - электростанциям в развитой колонии этого ненадолго хватит. Если не потратится на улучшение почвы под грядки. Не имба. Надежды только на покупку. 
P.S. Сдаётся мне, ты малость завысил цифры. На порядок.

**Comment by Zim777** [comment]
В развитых колониях давно уже слезли с торфа и сидят на атомке и других видах
Нет смысла вообще сидеть на торфе - есть куча дерева и древесного угля и химтоплива(из норбалов, из дерева, из бамбука, из бобов, из нефти) и других вариантов.
В умеренном лесу, пастбищах и тд - проблем с деревом вообще нету, оно вырастает быстрее, чем рубится.

**Comment by SetAriman** [comment]
1. Глубокая вода? Тратить овердохрена времени, чтобы добыть жалких 50 торфа? Ты шутишь? Это неплохо только тогда, когда ты строишь ров для обороны, не больше. А просто заводнять карту ради 20 торфа на клетку можно, но настолько тупо...
2. Залежи - да, бывают. Иногда. Если **очень повезёт**, то они будут в районе базы и их можно будет спокойно добывать. Не опасаясь, что твою технологичную добывалку поломает очередной рейд. И не надо будет тратить кучу времени ради добывания по капельке микробуром. В общем тоже идея, годная в теории. Лично у меня торфа в ближней половине карты нет, уголь далеко-далеко в горе маленький кусочек.
3. Химтопливо - да, неплохо. Но тратить месторождение я опасаюсь - не силён в математике. А лес, бобы - а что это? Я сейчас играю на лавовых полях. В начале игры вообще по всей карте выросшие деревья искал и пальмы рубил, чтобы освободить место под деревья. (А растить самому за пределами базы опасаюсь, боюсь что спалят, ироды. Да и учитывая продуктивность таких микролесов, итоговый результат будет так себе.) Для грядок места крайне мало. А растить в горе - топливо с бобов будет в основном уходить на питание лампы для растений. И это не только на моей карте. Ядерную зиму на всю игру ни кто не отменял.
4. Атомку заводить не рискую. Слишком геморная. Даже если её починили и атомные реакторы больше не надо разбирать, чтобы не взрывались.
5. Возобновляемые источники - не айс. На лавовых полях ветрогенераторы не катят. Солнечные - очень плохо, места нет. Если только под конец игры, когда можно будет снимать толстую крышу. Плазменные - ставлю. Но они чересчур дороги, занимают кучу места и выдают всего около 3к.
6. А вот торфянки работают изумительно. Они маленькие, дешёвые, вырабатывают больше всего энергии на единицу площади (кроме атомки, возможно) и просты в эксплуатации. Кроме того, доступны почти с самого начала.

**Comment by Pardonius** [comment]
1. Торф, если уж на то пошло, добываться должен вообще исключительно в болотах.
2. Для старта базы хватает 1-2 электростанций - хоть на дровах, хоть на начальном угле. Дальше есть масса вариантов:
а) Торговля
б) Коп угля в соседних клетках.
в) Если уж хочется именно торфа - скалистая грязь из почвы, нормальный строитель выкапывает сотни единиц торфа за день. Делается на своей или соседних клетках, по желанию.
г) Бесконечный поток химтоплива в виде норбалов позволяет легко разогнаться до 15-20 кв.
д) Бумалопы/бумкрысы, если есть чем кормить.
д) Если нужно больше 10-15 кв. энергии - явно технологии позволяют строить плазму, которая бесконечна.

**Comment by SetAriman** [comment]
1. Именно. Добываться. Добычу из игры убрали. ;) 
2. Новая добыча тераморфингом хороша лишь в теории. 
3. Торговля и прочее это понятно. Обсуждение было про то, что катастрофически порезали получение торфа. Т.е. теперь очень выгодные электростанции придётся обеспечивать в первую очередь именно торговлей. Уголь в целом в той же ситуации.
4. Что за химтопливо из норбалов? Я так подозреваю, это сойлент-электростанция? Ибо обычный переработчик - химстанция - трупы не потребляет. Я как раз собираюсь исследовать сойлент, но ... это тоже вариативно. Я сейчас играю на предпоследнем уровне сложности и Рэнди, в своей доброте, вот уже лет 8 старается присылать поменьше рейдеров. Даже ящеры не заходят. Хотя сойлент тоже вариант. Подсобный.
5. Бумалоп пока не заводил, так что даже не знаю, что именно в ХСК они дают. Но зная, как доятся животные - это же несерьёзно.
6. Плазма, как я говорил, очень дорога и малый выхлоп на единицу площади. Хотя приходится строить.
P.S. Я знаю, что есть варианты замены угольно-торфяным электростанциям. Но по описанным ранее причинам они куда менее выгодны и удобны. Просто торф резко занерфили и я не уверен, насколько это хорошо для геймплея. Возможно это только мне мешает. )

**Comment by Pardonius** [comment]
2. Новая добыча, при всех тех вещах, что мне в ней не нравится, на порядок баланснее, чем бесконечный коп топлива.
3. Ключевое - "очень выгодные электростанции". Если вам нужна лёгкая игра - просто добавьте пару тысяч торфа через консоль.
4. Перегонный аппарат потребляет любое мясо, да и много чего ещё.
5. Бумалопы дают взрывной экстракт, который идёт как топливо. Не очень выгодно, но зато бесконечно.
6. Это делает игру сложнее всем, но! это, на мой взгляд, разумное усложнение. Энергия через бесконечный торф слишком имбалансна и вычёркивала целый пласт контента. Те же гео/магмо/плазмо/водо/ветряные/солнечные станции, в общем всё, кроме атомки и антиматерии.

P.S. По тем же причинам хотелось бы нерфа шампиньонов и грибных похлебок. Их выращивание делает бессмысленным производство любой другой еды, и требует при этом минимальных вложений и по энергии, и по трудозатратам.

**Comment by Leslov** [comment]
Нерф бесконечного сбора торфа из ниоткуда - очень годный на мой взгляд. Люди и на переработку добычи ресурсов тоже жаловались (Раньше можно было одной добывалкой из одной и той же позиции бесконечно генерировать любое ископаемое), нужно лишь привыкнуть.

**Comment by SetAriman** [comment]
Ок, спасибо. Трудно отвыкать от приятных вещей. )

**Comment by surabujin** [comment]
Плюсую новую систему "добычи" торфа - стало значительно интереснее. Предыдущий варинат "бесконечного сбора торфа" всегда вызывал у меня недоумение.

**Comment by Pepelnica1488** [comment]
> 1. Новая добыча, при всех тех вещах, что мне в ней не нравится, на порядок баланснее, чем бесконечный коп топлива.
> 2. Ключевое - "очень выгодные электростанции". Если вам нужна лёгкая игра - просто добавьте пару тысяч торфа через консоль.
> 3. Перегонный аппарат потребляет любое мясо, да и много чего ещё.
> 4. Бумалопы дают взрывной экстракт, который идёт как топливо. Не очень выгодно, но зато бесконечно.
> 5. Это делает игру сложнее всем, но! это, на мой взгляд, разумное усложнение. Энергия через бесконечный торф слишком имбалансна и вычёркивала целый пласт контента. Те же гео/магмо/плазмо/водо/ветряные/солнечные станции, в общем всё, кроме атомки и антиматерии.
> 
> P.S. По тем же причинам хотелось бы нерфа шампиньонов и грибных похлебок. Их выращивание делает бессмысленным производство любой другой еды, и требует при этом минимальных вложений и по энергии, и по трудозатратам.

откуда же вы лезете мрази
