### ISSUE TITLE
Крафт оружия.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2115]
После недавних обновлений почему-то перестало крафтиться оружие на улучшенном оружейном станке. Заказана винтовка Штайр, пешка собирает компоненты, подходит, пару секунд стоит (не раскладывая компоненты), и уносит компоненты обратно на склад. Дробовик тоже не стали собирать.

**Comment by ArpoMo6** [comment]
Если рецепт был на станке до обновления, то это норм. Попробуй удалить рецепт и назначить его заново.

**Comment by SetAriman** [comment]
Спасибо. (К счастью, экспериментируя, сам догадался, одновременно с твоим ответом.)
P.S. Не в тему, может заодно подскажешь, чем опасен новомодный "чёрный дым" - от электростанций? А то уже боюсь, но ещё не знаю чего.

**Comment by ArpoMo6** [comment]
Режет точность. При больших концентрациях травит пешек и убивает их.
