### ISSUE TITLE
Researching Animal Husbandry II Provides recipe for Brewery NOT Animals

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#212]
Researching Animal Husbandry II does not provide abilities, or recipes for Farming.  Instead you get brewery recipes as you can see in the picture below.  

Suggestion:  Provide benefits for raising animals.

![screenshot 40](https://cloud.githubusercontent.com/assets/16742086/18214374/bef3c7ee-711a-11e6-8a8e-8ac71f172fd9.png)

**Comment by jnkyacc** [comment]
I'm afraid its by design... It suppose to unlock brewery for silage, so tequila, vodka and other alco stuff just bonus. :)

**Comment by zakhad** [comment]
Why not name it fermentation I ?

**Comment by Vigilence** [comment]
I like that idea, feels more intuitive.
