### ISSUE TITLE
More weapons for the weapon god

### ISSUE THREAD

**Issue by AndreiAvinov** [skyarkhangel/Hardcore-SK#2127]
Once you get into it, you can't stop, I guess. 
The plan is to add new special weapons:
- [x] Vibroknife
- [x] Flaming {something}
- [ ] Chainsword

Send me ideas and I'll think how to implement them.
I'll also try to use JecsTools' module for refillable melee weapons

**Comment by AndreiAvinov** [comment]
- Dart gun with different supportive darts (like movement speed boost, manipulation, etc.). Support your melee bois from afar.
- Essence gun that can use imbued ammo made from fenix or kirin hearts 
- Magical lanterns - one-time-use items that allow to breath fire or frost (like fenix and kirin do). Made with hearts, low tech.

**Comment by Avaddon-13** [comment]
- Poisoned Daggers. With low damage but great armor-piercing and strike rate. More for raids than for colony :) .

- Darts with sleep poison, to capture enemies. In fact, any effect (pain, nausea, sleep, hypothermia, overheating, etc.) that will allow you to capture a pawn.

- Similar weapon for high-tech. Pain projectors, tasers, tetanizers, etc.

**Comment by Leslov** [comment]
Darts with sleep poison already exists, works similar to bow/crossbow with poison arrows/bolts.

**Comment by CabbageGovernor** [comment]
Non-lethal bullets (such as rubber, stunning, etc.) for shotguns. It will also bring back the relevance of shotguns at the midgame and endgame (for calm down pawns in a rage and capture new ones).

**Comment by AndreiAvinov** [comment]
> Non-lethal bullets (such as rubber, stunning, etc.) for shotguns. It will also bring back the relevance of shotguns at the midgame and endgame (for calm down pawns in a rage and capture new ones).

We actually have these - beanbag shells

**Comment by Elldar112** [comment]
Not strictly a weapon but a turret to use beanbag shells for riot control
