### ISSUE TITLE
Soil Fertilization I does not allow the building of drainage pipes as it should

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#213]
Researching Soil Fertilization I does not give the ability to create drainage pipes as it states in the description.  

You gain the ability to create fertilized soil and a compost bin but not the drainage pipes.

Suggestion:  Allow the ability to create drainage pipes for swamps etc.

![screenshot 45](https://cloud.githubusercontent.com/assets/16742086/18214509/58132bd6-711b-11e6-9636-8aa01b7ddf42.png)
![screenshot 44](https://cloud.githubusercontent.com/assets/16742086/18214508/5812ed56-711b-11e6-9e8b-1f5c197ef0e3.png)
![screenshot 43](https://cloud.githubusercontent.com/assets/16742086/18214510/5818b1be-711b-11e6-980e-1bd590427362.png)

**Comment by jnkyacc** [comment]
There is no such item as Draining pump at all, so just typo. You can build moisture pump for de-watering swaps.
