### ISSUE TITLE
игра постоянно крашится в начале и нижнее меню недоступно

### ISSUE THREAD

**Issue by sfordinc** [skyarkhangel/Hardcore-SK#2130]
Игра постоянно падает в начале и нижнее меню недоступно. Проблема как с новой игрой, так и после загрузки старых сейвов.
Ссылка на последний краш-репорт - https://yadi.sk/d/my-fy1DZZHTfVw

**Comment by Zim777** [comment]
0 MB paging file [0 MB free].
Включайте назад файл подкачки

**Comment by sfordinc** [comment]
Файл подкачки был включен.
Где взять 2559 версию? Уж где только и не искал?
С 1.1 версией не работает.

**Comment by SomethingCrunchy** [comment]
> Файл подкачки был включен.
> Где взять 2559 версию? Уж где только и не искал?
> С 1.1 версией не работает.

Там же где и все остальные версии, в Steam

**Comment by Zim777** [comment]
Библиотека Steam - свойства RimWorld - бета-версии, выставить 1,0

**Comment by sfordinc** [comment]
Всем спасибо. Помогло обновление версии.
