### ISSUE TITLE
newest git

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#217]
so far newest git works fine bbut for 1 thing i found
 the tribal furnace and the clay oven( probbally got name wrong) both can be used when turned off. now they still use fuel to make the item but the new burn timer stops.

**Comment by skyarkhangel** [comment]
ok. Turn off would be removed. Fuel consumption decreased.

**Comment by sidfu** [comment]
sounds good as when they off u cant refuel them anyway.

also another thing since we have the early starge heating now for tribals theres another problem. there no early stage vent. there not enough heat bleedthru on doors for it to be effective but for large single rooms.
 have 3 rooms they not inside a mountain they just on outside. its 0F outside  so center room is 60 F the 2 side rooms are 45F. so have to add a camprie to theose 2 rooms to bring them to 50F-52F.

**Comment by sidfu** [comment]
hmm the fluffy error stoped after i redid my stockpiles and saved/reloaded game afterwards.

also was traders suppose to set off traps?
