### ISSUE TITLE
Swap SkilledBuilder for QualityBuilder (Linux CTD)

### ISSUE THREAD

**Issue by jaynus** [skyarkhangel/Hardcore-SK#219]
SkilledBuilder currently causes CTD for linux users. The successor of this mod, QualityBuilder, is released and backwards compatible for A14e. 

Link:
https://ludeon.com/forums/index.php?topic=25188.msg257433#msg257433

**Comment by ochkoebanoe** [comment]
He released the fix of CTD for Linux users?

**Comment by jaynus** [comment]
QualityBuilder fixes the CTD issues for linux users, yes. I can confirm in Ubuntu 16.04 it is running fine replacing SkillBuilder with QualityBuilder.

**Comment by ochkoebanoe** [comment]
Okay then, it is very good. Need to create pull or wait for the skyarkhangel.

**Comment by jaynus** [comment]
Confirmed fixed in master branch and the swap works.
