### ISSUE TITLE
Опечатка в Races_Animal_Arid.xml

### ISSUE THREAD

**Issue by JustACatRu** [skyarkhangel/Hardcore-SK#2197]
https://github.com/skyarkhangel/Hardcore-SK/blob/c5f70f3d524fe938129914c53eb8920643ebd827/Mods/Core_SK/Languages/Russian/DefInjected/PawnKindDef/Races_Animal_Arid.xml#L25

Вместо:
`<Rimram.labelFemale>овцы</Rimram.labelFemale>`
должно быть:
`<Rimram.labelFemale>овца</Rimram.labelFemale>`

**Comment by AndriiBr** [comment]
@skyarkhangel 
The problem described above is no longer relevant.

Here are the changes that completely removed these lines from the specified file: [commit](https://github.com/skyarkhangel/Hardcore-SK/commit/5167365ccc953c626b7963f3fde35fa9317d5dc2)

The issue can now be closed.
