### ISSUE TITLE
Grass and trees don't grow back - intentional?

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#221]
I have had a few fires that have cleared out large regions of grass and trees.  I thought after sometime the trees, bushes and grass lost in the fire would slowly grow back but they didn't.  This has left very large barren patches on the maps leaving many herbivores fleeing to other areas of the maps and consuming all the grass, further escalating the problem.

Even when everything is fine and you begin to strip the land of trees, bushes and grass for harvesting, they also don't grow back.

Is this an intentional behavior?  I feel that after some time the land should start to heal and stuff should grow back helping balance the map after a fiery disaster.

I thought I could swear a few weeks ago that everything was growing back, but I am not sure.

![forestfire](https://cloud.githubusercontent.com/assets/16742086/18228575/d86c1cfe-7222-11e6-9e39-d76e501f8b4c.jpg)
![onf_fire5 2700](https://cloud.githubusercontent.com/assets/16742086/18228576/d86f500e-7222-11e6-957d-e4d277d4f4c7.jpg)
![screenshot 48](https://cloud.githubusercontent.com/assets/16742086/18229079/10a6a0b6-7238-11e6-879f-19c1c96d464d.png)
![screenshot 50](https://cloud.githubusercontent.com/assets/16742086/18229078/10a4758e-7238-11e6-95e9-d7ba6b37eaa4.png)
![screenshot 49](https://cloud.githubusercontent.com/assets/16742086/18229077/10a38ca0-7238-11e6-882f-6a1bb807ab25.png)

**Comment by jnkyacc** [comment]
Spores\seeds from life plants have limited range and unable penetrate walls, so new life(type) will not appear from nowhere. If some type wiped completely, I suppose it will stop generating new seeds, so no new plants(this type).

**Comment by skyarkhangel** [comment]
jnkyacc, right. Its works like in vanilla.

**Comment by skyarkhangel** [comment]
We dealt with the issue.
