### ISSUE TITLE
Radiation affects robots (seem to have no resistance) and radiation effect lasts a very long time

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#222]
Hauler bots were frequently exploding when hauling uranium ore and enriched uranium to and from from a stockpile with a lot of uranium stacks. 
Not sure if this is intended behavior as the 'robot' trait provides 95% toxic resistance, though that is for fallout.

The radiation effect goes away very slowly, as a guess 1-3% a day by observation. I had a colonist handle uranium too much, they got to 90% radiation and have been unconscious in a bed for a week or so and it will probably take another for them to regain consciousness. Radiation should be a dangerous thing to deal with but it feels over the top if it takes weeks to recover if there's no way to speed up recovery.

edit: secondary note relating to radiation. I had the nuclear fallout even occur and animals are still coming to the map and dying. At least with the toxic fallout in vanilla animals stopped coming so there wouldn't be free corpses. Also is nuclear fallout supposed to cause everything outside to decay?
edit2: need more time to see, possibly making assumptions too soon since animals did stay and die to toxic fallout too but more don't come.

**Comment by ochkoebanoe** [comment]
>Not sure if this is intended behavior as the 'robot' trait provides 95% toxic resistance, though that is for fallout.

This trait does not give effect for uranium. I tried to set up it for 0%, -99%, 100% - no any change.

**Comment by jnkyacc** [comment]
Use chemical protection suit. It reduce amount of radiation you got.

**Comment by Jalordon** [comment]
I'm aware the chem protection suit does its job perfectly, no radiation at all getting through (though it gets torn up by radiation causing apparel damage so have to make a bunch of suits and a custom uniform for uranium haulers).

I resorted to using areas like I would for vanilla toxic fallout and it's working better, though still is annoying for the fall out event if someone is caught outside for an extended time that they have to sit out a very long time, probably better than dead though.

Main issue still is just the hauler bots going boom from rads. Is this intended for them to suffer rads (they puke too which I find funny)?

**Comment by skyarkhangel** [comment]
Fixed in next my update. Gets immune to radiation.
