### ISSUE TITLE
Toxic rains issues

### ISSUE THREAD

**Issue by Glucocorticoid** [skyarkhangel/Hardcore-SK#2225]
tl,dr Toxic rains are too often and has no notifications.

Чистая установка мода. Новая игра. Высадка в умеренном климате, горы. В настройках мира количество осадков среднее. Практически через день идут дожди. 

Внезапно на карте животные падают в шоке.  Почему-то у них экстремальное отравление токсинам. У поселенцев тоже внезапно отравление токсинами, хотя они ели только сухие пайки из аварийной посадки.

Оказывается дожди идут токсичные. Безо всяких уведомлени. Каждый раз при дожде проверяй снизу справа, нормальные это дождь или токсичный.

В итоге все животные на карте мертвы, т.к. к токсическому отравлению прикладывается еще и накапливающийся голод. Никого не удалось спасти.

Пожары вызывают осадки, которые внезапно снова токсические.

В моем частном случае:
- сутки идет токсически дождь, все животные погибают, 
- бум-крысы взрываются, вызывают пожар, снова начинается дождь и он токсический
- после дождя сухая гроза, вызывает пожар, дождь опять токсический
- через два дня хорошей погоды токсический туман с дождем, все вернувшиеся животные погибают
- далее обычные дожди через раз чередуются с токсичными, все животные погибают.

Проблема 1: токсичные дожди для хороших условий высадки (не радиоактивные или токсичные пустоши) идут слишком часто, животные на карте их не переносят и погибают. Погибшие животные не пригодны в пищу - вся карта завалена скелетами оленей и козлов. Не успеваю приручить новые стада - они тоже погибают. Каждую неделю вайп фауны на карте. Для колонистов проблемы нет - переждут под крышей, если успеют ее построить. Но успеть приручить диких животных не реально, они быстрее погибнут от токсичных дождей. 

Проблема 2: токсичный дождь это плохой эвент, но его наступление не сопровождается каким-либо уведомлением. Постоянно проверяешь внизу справа, что за дождь пошел, вдруг токсичный? Может стоит поменять favorability для этих дождей с Neutral на Bad?

**Comment by skyarkhangel** [comment]
В последнем обновлении переделано через новый эвент. Случайно дождь выпадать не будет, только в пустошах.
