### ISSUE TITLE
Wild Banana Trees - No fruit given when fully grown, harvest just gives logs.  

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#223]
So, I was very happy to finally have fully grown banana trees.  When my grower was ready to harvest instead of giving bananas and still allowing the tree to live, they were cut down and turned to wood logs.  No bananas dropped.

The banana tree should grow fruit and when ready should be harvest-able while still allowing the tree to live.

![screenshot 51](https://cloud.githubusercontent.com/assets/16742086/18229180/5a2cbb72-723c-11e6-9f44-96c627014d5d.png)

**Comment by jnkyacc** [comment]
Wild Banana Trees have no bananas. You need (Cultivated) Banana Tree.

**Comment by Vigilence** [comment]
Why call banana tree then?  It's confusing as you would assume it bears fruit due to the naming of the tree. 

If the name of the tree were palm tree then there would be less confusion.

**Comment by jnkyacc** [comment]
Not very eatable, huh? 
https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Inside_a_wild-type_banana.jpg/220px-Inside_a_wild-type_banana.jpg
But I agree about name :)

**Comment by Vigilence** [comment]
Even those product fruit :palm_tree:  :P

**Comment by ochkoebanoe** [comment]
It should be in the description.

**Comment by jnkyacc** [comment]
As far as I know there are no descriptions for wild trees

**Comment by skyarkhangel** [comment]
When we finish with retextures for plants, then we add "seeds" to wild plants.

**Comment by jnkyacc** [comment]
oh nooo :( no more seeds
может лучше скрытым ивентом засаживать?

**Comment by sidfu** [comment]
tbh i lliked the seeds please orginal  way u got seeds by that formula thats still in the descrpiption.
