### ISSUE TITLE
Черты характера

### ISSUE THREAD

**Issue by StarGoro** [skyarkhangel/Hardcore-SK#2232]
Привет. Создал аккаунт на ГитХаб, специально, чтобы написать об этом неприятном баге.
Играю за сценарий "Андроиды".
На предсоздании выбрал поселенцам 3 черты характера, среди которых был "Сангвиник". В процессе игры черта изменилась на "Оптимист", тем самым убрав конфликтующий с этой чертой "Сангвиника", но и "Оптимист" тоже не прибавился. Теперь у них только 2 черты характера. Причём, когда во второй раз я получил "Оптимиста" -- оптимист так и не прибавился к чертам характера.

**Comment by skyarkhangel** [comment]
Какие именно 3 черты были, кроме сангвиника?

**Comment by StarGoro** [comment]
> 
> 
> Какие именно 3 черты были, кроме сангвиника?

Быстрая Обучаемость, Усердие и Сангвиник. На всех трёх пешках. Баг произошёл со всеми тремя.
