### ISSUE TITLE
Не работает теплица.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2235]
Начал игру в тайге. Через пару лет построил теплицу со стеклянным потолком. Конец мартомая, всё хорошо, наступают заморозки. На улице -10*, в теплице +30*. Но теплица не работает. При +30* вся почва покрывается льдом.

Заморозки закончились. На улице +16* и всё оттаяло. В теплице +40* и сплошной лёд. Похоже придётся переигрывать. Ибо жить всю игру мизером колонистов и охотой на немногочисленных животных слабое удовольствие.

**Comment by ArpoMo6** [comment]
версия римки 1.0?

**Comment by SetAriman** [comment]
Да.

**Comment by SomethingCrunchy** [comment]
в 1.1 исправлено

**Comment by SetAriman** [comment]
Так версия под 1.1 же вроде нерабочая? На днях смотрел стримы по ХСК под 1.1 и там было полно багов.

**Comment by SomethingCrunchy** [comment]
слегка рабочая

**Comment by SetAriman** [comment]
Гениально. В старую толком не поиграть, потому что там добавили баги и неизвестно будут ли вообще править. Новую не поиграть, ибо хз когда приведут её в божеский вид. 
P.S. Ещё и кривую механику заражения ввели. Играть полностью больной колонией такое себе.
