### ISSUE TITLE
Розжиг генератора на химтопливе.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2258]
Случайно обнаружил, что для качественной работы этого генератора при запитке химтопливом, его надо предварительно "запускать" с помощью другого топлива. Желательно прометия. Чтобы генератор разогрелся, и при замене прометия на химтопливо продолжил работать при старой температуре и с гораздо большим выходом электроэнергии. Думается это баг, а не фича.
P.S. Имеет смысл писать о багах мастер-версии для 1.0?

**Comment by ArpoMo6** [comment]
думаю, что не имеет
