### ISSUE TITLE
Can't craft Muffalo Leather Dining Chair even though I have the materials.

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#226]
I can't craft a muffalo Dining Chair even though I have all the materials.  I have tried other types of leather for the chair and they all craft fine except muffalo.

![screenshot 56](https://cloud.githubusercontent.com/assets/16742086/18234720/ba54374c-72db-11e6-943b-8690479cc762.png)
![screenshot 55](https://cloud.githubusercontent.com/assets/16742086/18234721/ba5516f8-72db-11e6-846d-4c24a38dae58.png)
![screenshot 54](https://cloud.githubusercontent.com/assets/16742086/18234723/ba575350-72db-11e6-90a4-beaf3e48c37d.png)
![screenshot 53](https://cloud.githubusercontent.com/assets/16742086/18234722/ba55fb0e-72db-11e6-859f-32250679c6b4.png)

**Comment by jnkyacc** [comment]
Red numbers near muffalo leather in your picture tells me that you don't have enough leather at stockpile.
1) You don't have leather.
2) Leather is forbidden.
3) Cannot reach leather (forbidden doors, restricted zone, dumping zone, ect.)

**Comment by Vigilence** [comment]
1) I have enough leather, check out the pictures.
2) It's not forbidden, check the last picture.
3) Check last picture.
4) The leather is in the same room as the chair being built.
5) I can craft other things that need muffalo leather but not this.

**Comment by jnkyacc** [comment]
Ok :)
