### ISSUE TITLE
Coal burner not making room hotter

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#227]
I have 2 coal burners turned on in 1 building and the temperature inside is 32F while the temperature outside is 59F.  I placed 1 in the barn and it's 122F, so I am not sure what is going on.

![screenshot 58](https://cloud.githubusercontent.com/assets/16742086/18235468/352a76ea-72e9-11e6-9dde-f382400a5a9c.png)
![screenshot 57](https://cloud.githubusercontent.com/assets/16742086/18235469/352ae454-72e9-11e6-9d39-db1048e55ea1.png)
![screenshot 59](https://cloud.githubusercontent.com/assets/16742086/18235497/8e11fc1a-72e9-11e6-8cd5-c04a5d8683e1.png)

**Comment by Vigilence** [comment]
Now 66F outside and still 32F inside.

**Comment by WaytobeGlad** [comment]
The outcoming temperature is scaled by the size of the room the burner installed in.
Try to build more doors. And do not forget about ventilation.

**Comment by Vigilence** [comment]
Why would that make the room cooler instead of at least the ambient temperature outside if I am using 2 heaters?

**Comment by WaytobeGlad** [comment]
That can happen when your house is placed below the mountain - indoor temperature will be lower in summer or warm spring.
Besides, the heart of an ice cat placed in the same room can decrease the temp drastically.

**Comment by Vigilence** [comment]
Below mountain - do you mean if my base is inside a mountain?  I am not in a mountain but in a building outside on open land, which is why I found it weird.  I guess free AC is a good thing.

**Comment by jnkyacc** [comment]
Only can suggest this

> Besides, the heart of an ice cat placed in the same room can decrease the temp drastically.

or some vanilla bug with vents.

**Comment by skyarkhangel** [comment]
Obsolete, since new refuel system.
