### ISSUE TITLE
1.1 Неприятный баг, нужна помощь

### ISSUE THREAD

**Issue by shikulja** [skyarkhangel/Hardcore-SK#2281]
после перехода с 1.0 на 1.1
1. перестал работать правый клик мышью на торговца из проходящего мимо каравана и консоли связи
из-за этого невозможно торговать, возможно это связано из-за ошибок перевода.

так же в некоторых подсказках пропал список доступных предметов для крафта:
![Аннотация 2020-07-16 122415](https://user-images.githubusercontent.com/3386359/87654294-5a5baf00-c75f-11ea-9d08-b3b8572c5c58.png)
![Аннотация 2020-07-16 122402](https://user-images.githubusercontent.com/3386359/87654297-5b8cdc00-c75f-11ea-892a-3f5202ca9b72.png)

**Comment by ArpoMo6** [comment]
"после перехода с 1.0 на 1.1"
т.е. просто обновили 1.0 на 1.1 и загрузили свой сейв с 1.0, верно?

**Comment by shikulja** [comment]
@ArpoMo6 
да все так, диалоги отсутствуют

остальное как я и писал было так же после перехода с беты на 1.0. то есть игнор станков

**Comment by ArpoMo6** [comment]
Рекомендую вернуться на 1.0, довести колонию до логического (или не очень) конца и начать новую на 1.1.

**Comment by shikulja** [comment]
> Рекомендую вернуться на 1.0, довести колонию до логического (или не очень) конца и начать новую на 1.1.
проще сказать чем сделать, с учетом того как я часто играю, это будет еще неменьше года.. естественно hsk будет и дальше обновлятся.. так что это не решение

**Comment by ArpoMo6** [comment]
Сейвы из 1.0 несовместимы с версией 1.1, ХСК здесь не причем. Мне казалось это вполне очевидным...
![image](https://user-images.githubusercontent.com/62516232/87660714-f47c2100-c778-11ea-972f-048612745ce3.png)

**Comment by shikulja** [comment]
> Сейвы из 1.0 несовместимы с версией 1.1, ХСК здесь не причем. Мне казалось это вполне очевидным...
> ![image](https://user-images.githubusercontent.com/62516232/87660714-f47c2100-c778-11ea-972f-048612745ce3.png)
> P.S. то, что сейв вообще загрузился, уже можно считать чудом!

вообще-то совместимы, про это было написано

Technical details
If you’re playing without mods: You’ll be able to update and continue playing on the new version without interruption.

If you're using mods that haven't added support for 1.1: You can continue playing version 1.0 as long as you like by using the version-1.0 beta branch. To access it, right-click RimWorld in your Steam library list, click Properties, then select the ‘betas’ tab. Select ‘version-1.0’ from the drop-down list. You'll want to change this back to 'default' eventually.

**Comment by ArpoMo6** [comment]
Некорректно выразился. Предложение "ХСК здесь не причем" было лишним.
Корректнее будет так: основные моды сборки ХСК в 1.1. не имеют обратной совместимости с ХСК 1.0.

P.S. а ещё у вас внизу та же рекомендация доиграть на версии 1.0.

**Comment by shikulja** [comment]
> Некорректно выразился. Предложение "ХСК здесь не причем" было лишним.
> Корректнее будет так: основные моды сборки ХСК в 1.1. не имеют обратной совместимости с ХСК 1.0.
> 
> P.S. а ещё у вас внизу та же рекомендация доиграть на версии 1.0.

ладно посмотрю, может создам заново.
