### ISSUE TITLE
Food Update issues

### ISSUE THREAD

**Issue by d1ssolvedz** [skyarkhangel/Hardcore-SK#2289]
Посмотрел на апдейт еды и есть поправочки/предложения. 

В целом мне нравится новая система. Пока что есть пару замечаний
1) Яичница готовится далеко не из всех возможных вариаций яиц в игре. 
2) Нет применения жучиному желе. У меня его более 9 тысяч из-за квестов на ульи - а применения в блюдах помимо превращения в сахар нет. Стоит добавить его куда-то в рецепт вкусного блюда как альтернативный второй ингредиент, к примеру.

**Comment by insidio118** [comment]
А да. И перевода вообще нет. Все реворкнутые блюда на инглише. Не то чтобы это было проблемой - но сам факт. Первод Russian SK стоит.

**Comment by AndreiAvinov** [comment]
Яичница готовится из всех яиц, которые отмечены яичным тегом. Желе вернётся во второй части апдейта, сделаю из него цельный кусок желе как блюда и, возможно, в каких то рецептах само по себе будет использоваться. С переводом разберусь, видимо не туда засунул его.

**Comment by insidio118** [comment]
Не из всех оплодотворённых яиц можно сделать яичницу. Там как минимум на каждое яйцо должно быть оплодотворённое. Разницу видно глазами когда просматриваешь фильтр ингредиентов

**Comment by AndreiAvinov** [comment]
очень ограниченное количество животных откладывают не оплодотворённые яйца, большинство останавливается на 50% если нет партнёра)

**Comment by insidio118** [comment]
Понял. Я перепутал. Наоборот не из всех неоплодотворенных можно сделать. К примеру с тех же яиц кобры нельзя.

**Comment by insidio118** [comment]
![image](https://user-images.githubusercontent.com/35869635/88253693-77dacc80-ccbb-11ea-872d-9cffc1664eca.png)

**Comment by insidio118** [comment]
Я о том, можно ли будет делать яичницу из яйца которое было оплодотворённым но потом испортилось? (но не сгнило)

**Comment by AndreiAvinov** [comment]
тут уже я не знаю, других категорий у яиц нет

**Comment by insidio118** [comment]
А вручную прописать можно?

**Comment by AndreiAvinov** [comment]
Вечером посмотрю ещё
