### ISSUE TITLE
Materials - armor heat values

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#2293]
Видимо забыли поменять. 
<img width="612" alt="Screenshot_78" src="https://user-images.githubusercontent.com/21973141/88430426-1c1a5b80-ce01-11ea-8ace-7c5514a8dfcf.png">

**Comment by skyarkhangel** [comment]
их удалили из хск ранее, но забыли что они есть в ванильке, поэтому это статы из ванильки. Удаляются патчем в новых апдейтах.
