### ISSUE TITLE
Шкафы и переодевание [HSK 1.1]

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#2298]
Вроде уже видела этот баг в списке, но найти сейчас не смогла.
В общем переодевание через шкаф не работает совсем. Колонисты вещи в шкаф складывают и на этом всё. Кнопка переодеться или команда пойти переодеться статтерит их на полсекунды, после чего они идут заниматься своими делами. Вещи из шкафа после этого достать уже невозможно.

**Comment by Aldentr** [comment]
Та же проблема, а если поставить задачу на переодевание в очередь несколько раз, ещё и интерфейс пропадает xD

**Comment by Westus** [comment]
Столкнулся с такой же проблемой. Получилось достать одежду и оружие переставив сейф на новое место.

**Comment by skyarkhangel** [comment]
Bug found. Should be fixed in new update.
