### ISSUE TITLE
Расчёт эффективности имплантов. (1.1)

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2303]
Столкнулся с интересной ситуацией. Напали рейдеры. Лежит раненый. Левый глаз - стеклянный, -50% зрения. Вместо правого глаза - повязка на глаз, -50% зрения. -50% и -50% в сумме дают ... +15% зрения, ведь на улице светло!  о_О
P.S. У него ещё и протезы ступни и кисти. Тяжело быть рейдером.

**Comment by AndreiAvinov** [comment]
В ванили ограниченные возможности настройки hediff'ов, с этим банком к тунану
