### ISSUE TITLE
Масса турелей.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2305]
Нашёл во вражеском лагере у дикаря КПВ и возрадовался: это ж просто праздник какой-то! И чуть позже ... расстроился. Пришлось выкинуть, не унесу. Он весил 90+ кг. (88кг по дефолту). Заглянул на Вики, а там масса 52.3 кг. Куда ниже. Как по мне, стоило бы пересмотреть вес турелей. Возможно даже чуть ниже "оригинала", чтобы обнаружив неожиданный приз при налёте на лагерь, пешки всё же могли его утащить.

**Comment by AndreiAvinov** [comment]
В караваны предполагается ходить с животными, а масса турелей была повышена в последних апдейтах как раз чтобы пешки их в карманах с собой не носили

**Comment by SetAriman** [comment]
Пешки могут взять стадо бронированных бионосорогов вместо турелей. ;) 
P.S. Ок, понял. Не думал о таком.

**Comment by SetAriman** [comment]
Кстати о птичках. Игрок же может взять в караван вьючных животных. Смысл был увеличивать вес?

**Comment by SomethingCrunchy** [comment]
чтоб в карманах не таскали

**Comment by SetAriman** [comment]
Эмм ... молчу.
