### ISSUE TITLE
Кривой эвент.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2311]
Столкнулся с новомодным явлением: пси-дождь. Дождь, который по его описанию, длится от нескольких месяцев до нескольких лет и при этом понемногу старит всех, кто не под крышей. (И такой волшебный, что абсолютно не мешает песчаным бурям. Которые пару суток радостно ломают всё на карте.) Можно ли его пофиксить в сборке? Ладно неделя, ну две. Но дождь, льющий без остановки **годы**, это жуткий перебор, как по мне. Да ещё активно вынуждающий всех прятаться под крышами.

**Comment by Aldentr** [comment]
Он не настолько страшный, я в одном из прохождений недавно прожил с ним чуть больше 1,5 лет, разница в возрасте пешек составила от силы 2-3 суток, если правильно помню.

**Comment by SetAriman** [comment]
Да ладно. У меня иногда выбегали и за пару месяцев несколько дней натикало. Но дело даже не в этом. Непрекращающийся месяцами/годами дождь портит всю игровую атмосферу. Не говоря уж о двойном идиотизме ситуации.

**Comment by ArpoMo6** [comment]
Поправили уже. Теперь длится не более 4-ех дней и появляется только при определенных условиях.
Эффект старения при этом усилен в 10.
https://github.com/skyarkhangel/Hardcore-SK/commit/5f33b0890e28a8f47cdd49cc8bee3b3e4413ac56
