### ISSUE TITLE
Огнестрел и пластик.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2314]
После переработки нефтехимии, она стала довольно затратным производством, которое налаживается далеко не сразу. А огнестрел первого тира спокойно изучается раньше и вполне мог бы производиться, если бы не пластик в компонентах сборки. То есть для защиты базы нужен скачок с луков сразу к эпохе пластика. Кроме нескольких рецептов. Можно ли убрать пластик из рецептов первого тира?

**Comment by SomethingCrunchy** [comment]
После того как  1.1 выйдет на stable версию древо исследований будет переработано, без пластика доступно 16 видов огнестрельного оружия, вполне достаточно

**Comment by SetAriman** [comment]
Это какие виды - некоторые пистолеты и дробовики? У которых дальность стрельбы куда ниже, чем у лучников? Все три карабина - пластик. Обе снайперки - пластик. Вопрос не в числе, а в типе. Да и по логике. Пистолеты, винчестеры, карабины и винтовки, включая снайперское оружие, существовало и процветало задолго до эры пластиковых технологий. А тут: хочешь занюханный карабин под пистолетный патрон ,чтобы отбиваться от толпы механоидов? "Plastic, assholes!"

**Comment by ArpoMo6** [comment]
Есть некоторые пистолеты-пулеметы без пластика, внимательнее.

**Comment by SomethingCrunchy** [comment]
Винтовка Lee-Enfield 
Винтовка Мосина 
Винтовка раткинов 
Винтовка СКС
 ПП М3 GreaseGun
 ПП Uzi
 ППШ-41
 ПП Scorpion EVO 3
 ПП ТМР с глушителем
 Пистолет Colt M1911
 Пистолет Vector CP1
 Пистолет ТТ-34
 Дробовик М37А2
 Дробовик Remington 870
 Дедушкино ружье
 Дробовик раткинов

**Comment by SetAriman** [comment]
Откуда столько оружия? Верстаки раткинов я не строил (нафиг лишние верстаки, если у меня нет раткинов?) А без них, в первом тире нет СКС и Мосина. Если только с необязательным модом для **некоторых** любителей. А остальное то, про что я и писал: оружие с дальностью стрельбы ниже, чем у лука. Как я и писал, вопрос в типе. ПП по факту это те же пистолеты, только с повышенной скорострельностью. И почему-то отвечающие упорно игнорируют, что до изобретения пластика существовала МАССА разнообразного оружия. А тут первый огнестрел - ещё даже автоматы не изобрели! - и 1 (одна) винтовка, 0 карабинов, и короткострелы на выбор. Остальное с пластиком. Который даже в нашей реальности внедрили в оружейную промышленность чуть ли не через век, как уже были и всевозможные винтовки, и карабины, и даже снайперки. 
P.S. Не удивлюсь, если тут даже Калаш пластиковый. Пока не могу проверить.
