### ISSUE TITLE
Prepare carefully

### ISSUE THREAD

**Issue by StarGoro** [skyarkhangel/Hardcore-SK#2316]
Привет, Скай. Я не знаю, как мне правильно сформулировать мысль, чтобы донести её до тебя. Постараюсь. В общем, уже давно знаком со сборкой и периодически захожу покайфовать от атмосферы. Но, каждый раз я спотыкаюсь об мод на предподготовку Prepare carefully, который работает очень некорректно, и я постоянно сталкиваюсь с новыми косяками этого мода. Начнём с того, что при выборе "Ограничение очков" - очки он ограничивает всегда по разному. Иногда он может дать тебе 10 тысяч очков, а иногда 4 тысячи. При последующем выборе прессета ты с вероятностью 80% выйдешь за пределы доступных очков, хотя когда ты в прошлый раз его создавал - ты не выходил за пределы.  UPD: Дальше: у меня бывает отказывают клавиши этого мода. Интерфейс перегружен. Когда я редактировал через этот мод андроидов и давал им определенные черты характера - он просто сломал их. В течении игры я получал ещё черты характера, которые убирали старые, но при этом не появлялись.(Я уже писал об этом) Невозможность менять расы напрямую через этот мод. Помогает только выбор сценария. Этим модом ты с легкостью можешь отключить все родственные связи, и, как следствие, убрать проблемы с неприятным дебафом.

Не пора бы уже перейти на тот же RandomPlus ? Который очень прост, который абсолютно не ломает баланс и не даёт тебе никаких уступков. Не дает желание накрутить лишних стат пешке, и, который, в отличии от Prepare carefully, не делает старт игры всегда одинаковым. С RandomPlus твои пешки будут обладать особенностями, как при случайном прокликивании, при этом не даст вылезти за стандартный случайный разброс характеристик. На всех стримах, которые я смотрю, во всех видео, на которые я натыкаюсь, я вижу один и тот же стартовый прессет характеристик. Разве это то, к чему шёл HSK? Ведь ты же убрал старый colonist bar и заменил его более куда удобным и логичным аналогом (точно не знаю, как было, но пусть это не сбивает тебя с главной сути). Я надеюсь на твоё понимание. Да, мне ничего не мешает самому менять Prepare carefully на RandomPlus, но это я. Что насчёт людей, которые впервые вообще знакомятся с Rimworld на HSK?

Цитирую себя из чата в Дискорд:
_"Да нет, просто RP мне показался не ломающим баланс и не делая каждую игру, похожей на другую. Я не хардкорный игрок и далеко не олд , но за HSK слежу давно. Просто как раньше было? Мы все по часу прокликивали нужные статы пешке в поисках нужных. Каждая игра была со своими подвохами и особенностями. Нельзя было выкрутить ИДЕАЛЬНУЮ пешку как с PC. Но RP заменяет 1000 кликов на 1 клик, при этом тебе всё равно нужно будет с чем-то считаться. Ещё раз, как мне показалось, такая система куда более логична для HSK. Но я могу ошибаться и ни в коем случае не хочу навязывать своё мнение. Просто делюсь и хочу услышать ваше"_

**Comment by ArpoMo6** [comment]
На одного довольного пользователя придется около двух сгоревших стримеров. Так что не стоит :peka:

**Comment by skyarkhangel** [comment]
Спасибо, посмотрим. Арпомо, на выбор можно добавить, как миникартой.
