### ISSUE TITLE
Не работают луки (ошибки со стрелами)

### ISSUE THREAD

**Issue by AantCoder** [skyarkhangel/Hardcore-SK#2331]
Пропадают стрелы, если положить их на склад. Нельзя выкинуть стрелы из инвентаря. Невозможно охотиться с луком (ни сами пешки не охотятся, ни пкм-принудительно, нет пункта в контекстом меню). Невозможно стрелять из лука в боевом режиме (пункт меню стрелять есть, но пешка меняет на другой инструмент или пустую руку и просто стоит).
Полагаю суть проблемы одна. Эксперименты проводились с коротким луком, воспроизводится всегда. Версия 1.1 Development от 01.08.2020

**Comment by ArpoMo6** [comment]
версия основной игры какая?

**Comment by AantCoder** [comment]
1.1.2698 rev737

**Comment by Zim777** [comment]
![image](https://user-images.githubusercontent.com/46481732/89130927-dc92f400-d511-11ea-98b8-36bacfd7db5d.png)
Внезапно

**Comment by AantCoder** [comment]
Да, действительно, на предпоследней версии 1.1.2647 rev731 всё работает хорошо! Спасибо!
