### ISSUE TITLE
Проблемы с перезарядкой турелей.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2333]
В какой-то момент пешки перестали перезаряжать турели. Даже если им отдать команду на перезарядку. Выяснилось, что это произошло, потому что я патроны сложил в хранилище Tall shelf. Если выложить патроны на обычный склад, проблем нет.

**Comment by SetAriman** [comment]
Возможно влияет не тип склада, а дальность. (Пока нет удобной возможности тестить). В частности с дальнего обычного склада на базе турели точно так же не перезаряжаются. Надо тащить патроны близко к турелям.

**Comment by skyarkhangel** [comment]
Проверьте с новым обновлением. Возможно была проблема с одним из обновлений LWM Storages.

**Comment by SetAriman** [comment]
После последнего боя проблем не было. (Ещё бы и сейвы при ранениях не крашились.)
