### ISSUE TITLE
[Request] RightTools 

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#234]
Надо бы проверку там сделать павн или не павн, а то судя по всему роботы работать не будут. Оно пытается сделать проверку на тул, а т.к роботы нифига не павн класса - начитает тупить и спамить ошибкой.
Ну и дописать бы там все остальные работы, операции, кухарство и т.д.

___
По роботам есть идея делать болванчиков из поверженых еще не сдохших механоидов. Подобрали->вскрыли мозг->заменили аи персону->починили из останков других мехов->ну и заменили манипуляторы на... пускай грабли и фермер готов :) + систему апгрейдов.

**Comment by skyarkhangel** [comment]
хорошо

**Comment by skyarkhangel** [comment]
Проверьте работу с последним апдейтом.
