### ISSUE TITLE
Ошибка в исследованиях Фруктовый сад 1 и 3

### ISSUE THREAD

**Issue by CabbageGovernor** [skyarkhangel/Hardcore-SK#2346]
Разблокируется рецепт получения семян апельсина, а позволяет сажать яблоню. В другом исследовании наоборот.
![Untitled](https://user-images.githubusercontent.com/64545611/89727059-99191800-da32-11ea-81f0-8ec7a9c2356f.jpg)

**Comment by SetAriman** [comment]
Перевод во многих местах "хромает". Как я понимаю, доберутся до него не скоро - это не первоочередная важность. Ориентируйся по иконкам и списку того, что изучается.
