### ISSUE TITLE
Оружие Buster sword, ошибки при атаке.

### ISSUE THREAD

**Issue by Aldentr** [skyarkhangel/Hardcore-SK#2348]
Пешка, экипированная Buster sword при каждой атаке выдает ошибку в лог:

something wrong num1 == 0.0
Verse.Log:Error(String, Boolean)
SimpleSidearms.utilities.StatCalculator:GetAdjustedMeleeDamageUnarmedAmount(Pawn)
SimpleSidearms.utilities.StatCalculator:GetUnarmdeMeleeDPS(Pawn)
SimpleSidearms.utilities.StatCalculator:MeleeDPS(Pawn, ThingWithComps, Single, Pawn)
SimpleSidearms.utilities.GettersFilters:findBestMeleeWeapon(Pawn, Boolean, Pawn)
SimpleSidearms.utilities.WeaponAssingment:tryMeleeWeaponSwap(Pawn, Boolean, Boolean, Boolean, Pawn)
SimpleSidearms.utilities.WeaponAssingment:tryCQCWeaponSwapToMelee(Pawn, Pawn)
SimpleSidearms.utilities.WeaponAssingment:doCQC(Pawn, Pawn)
SimpleSidearms.intercepts.Verb_MeleeAttack_TryCastShot_PostFix:TryCastShot(Verb_MeleeAttack)
CombatExtended.Verb_MeleeAttackCE:DMD<DMD<TryCastShot_Patch3>?-1945051520::TryCastShot_Patch3>(Verb_MeleeAttackCE)
Verse.Verb:DMD<DMD<TryCastNextBurstShot_Patch0>?-834526080::TryCastNextBurstShot_Patch0>(Verb)
Verse.Verb:DMD<DMD<WarmupComplete_Patch1>?-434944768::WarmupComplete_Patch1>(Verb)
Verse.Verb:DMD<DMD<TryStartCastOn_Patch1>?357158912::TryStartCastOn_Patch1>(Verb, LocalTargetInfo, LocalTargetInfo, Boolean, Boolean)
Verse.Verb:DMD<DMD<TryStartCastOn_Patch0>?47620224::TryStartCastOn_Patch0>(Verb, LocalTargetInfo, Boolean, Boolean)
RimWorld.Pawn_MeleeVerbs:TryMeleeAttack(Thing, Verb, Boolean)
Verse.AI.JobDriver_AttackMelee:<MakeNewToils>b__3_1()
Verse.AI.<>c__DisplayClass4_0:<FollowAndMeleeAttack>b__0()
Verse.AI.JobDriver:DMD<DMD<DriverTick_Patch1>?-192337920::DriverTick_Patch1>(JobDriver)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:DMD<DMD<Tick_Patch1>?2006599936::Tick_Patch1>(Pawn)
Verse.TickList:DMD<DMD<Tick_Patch2>?-135787904::Tick_Patch2>(TickList)
Verse.TickManager:DMD<DMD<DoSingleTick_Patch1>?-1690480640::DoSingleTick_Patch1>(TickManager)
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Судя по тексту, связано с Simple sidearmes. Полный лог: https://gist.github.com/bd0284187e73587308d6ed06bb6ed587

Кроме HSK стоят другие моды, но, если правильно понимаю, они не должны быть причиной, тем более, что с большинством других оружий все нормально. Поправьте, если ошибаюсь, тогда больше не буду постить ошибки при наличии дополнительных модов.

**Comment by Spaniard829** [comment]
> Поправьте, если ошибаюсь, тогда больше не буду постить ошибки

У меня баг тоже проявляется.
По хорошему, всегда нужен сторонний тест. Можешь писать в оф. дискорд сборки. https://discord.gg/FMPRSKr
