### ISSUE TITLE
Конфликт модов Minerals (HSK) и List Everything (Steam). Для информации!

### ISSUE THREAD

**Issue by Aldentr** [skyarkhangel/Hardcore-SK#2351]
Основная мысль в последнем предложении тикета!

Попробовал поиграть вместе с модом List Everything (https://steamcommunity.com/sharedfiles/filedetails/?id=1706669545&searchtext=ListEverything). При попытке ввести в поле ввода фильтра по имени названия любого кристалла из мода Minerals (например, coldstone crystal) начинает спамить ошибки:

Exception filling window for List_Everything.MainTabWindow_List: System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Minerals.StaticMineral.getTexturePath () [0x00022] in <220fb78856104502b505030b4f6fa788>:0
at Minerals.StaticMineral.get_Graphic () [0x00001] in <220fb78856104502b505030b4f6fa788>:0
at List_Everything.MainTabWindow_List.DrawThing (UnityEngine.Rect rect, Verse.Thing thing) [0x00150] in :0
at List_Everything.MainTabWindow_List.DrawThingRow (Verse.Thing thing, UnityEngine.Rect& rect) [0x00018] in :0
at List_Everything.MainTabWindow_List.DoList (UnityEngine.Rect listRect) [0x00219] in :0
at List_Everything.MainTabWindow_List.DoWindowContents (UnityEngine.Rect fillRect) [0x00058] in :0
at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x00165] in <0ee2c524c4be441e9b7f8bfcb20aca6f>:0
Verse.Log:Error(String, Boolean)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Error(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:DMD<DMD<Update_Patch1>?-2136821888::Update_Patch1>(Root)
Verse.Root_Play:Update()

Full log link: https://gist.github.com/7ec02a28f21cb68fed2bc688d36d6da5

Создал тикет на гитхабе мода (https://github.com/alextd/RimWorld-ListEverything/issues/11). Автор отказался разбираться с ошибкой (цитирую: "Honestly, I see "HardcoreSK" and I'm not going to look at that."). Но предположил, что у Minerals есть какая-то проблема с путями к текстурам (цитирую: "But TL;DR, looks like Minerals has a problem with its texture path (which has never happened for anything else in the game) at least").

Понимаю, что времени и желания разбираться с конфликтами сторонних модов , скорее всего, у вас нет, но решил отписаться на случай, если проблема с Minerals на самом деле присутствует и в будущем может где-нибудь вылезти.

**Comment by skyarkhangel** [comment]
проверь на новой игре. Недавно было обновление мода на минералы и уже отмечали плохую совместимость со старыми сейвами.

**Comment by Aldentr** [comment]
К сожалению, старт новой игры не помог.


Начал новую колонию, проверил через Object Seeker отсутствие кристаллов на карте, добавил Sulfur crystals через dev mode (клетки с кристаллами находились в зоне видимости), при открытии окна мода List Everething сразу начался спам ошибок (скрин "Rimworld test 1.png").

Полный лог: https://gist.github.com/fd00cd4eea465f88fab2c6600241145b

Также попробовал с тем набором модов, что активны при первом запуске после обновления HSK (+ List Everything). Начал новую колонию, проверил через Object Seeker отсутствие кристаллов на карте (ничего не добавлял), открыл окно мода List Everething, при прокрутке стартового списка предметов, на определенном моменте начался спам ошибок (скрин "Rimworld test 2.png").

Полный лог: https://gist.github.com/725c886ab33619304220023139ece769

Судя по всему ошибки возникают, когда какие-то объекты из Minerals мода (точно кристаллы, и, судя по скрину "Rimworld test 3.png", новые руды) находится либо в зоне видимости, либо в видимой части списка предметов.

![Rimworld test 1](https://user-images.githubusercontent.com/48800040/90103212-d7704900-dd4a-11ea-850e-786fbeeb46ff.png)
![Rimworld test 2](https://user-images.githubusercontent.com/48800040/90103217-d93a0c80-dd4a-11ea-9d0b-c10ada54b16f.png)
![Rimworld test 3](https://user-images.githubusercontent.com/48800040/90103549-5bc2cc00-dd4b-11ea-94cd-4315f45cf657.png)
