### ISSUE TITLE
Скрытый пояс-щит.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2352]
Мои милишники ходили с разгрузками. Сделал пояс-щит, думая: ну. всё, сейчас переоденутся. Нифига. Носят и то и другое одновременно. Из-за чего, случись необходимость, пояс-щит не снимешь. Он не показывается среди вещей.

**Comment by Aldentr** [comment]
Крестик сверху слева в окошке надетых вещей щелкни - все отобразиться в виде списка, там щит будет.
![Rimworld 2](https://user-images.githubusercontent.com/48800040/90055817-9fcfb580-dce6-11ea-9113-e12263f100d3.png)
