### ISSUE TITLE
Бесполезные обломки.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2353]
Новые глиняные обломки не задействованы в рецептах. Ни как обломки камня, ни как мягкая глина.

**Comment by GuardianDll** [comment]
Ну, можно выбрать "Делать любые каменные блоки", и оставить из возможных материалов только глиняный обломок. Тогда у тебя обломки будут переделыватся в кирпичи

**Comment by l29ah** [comment]
Из кирпичей этих чёт даже каменную табуретку не собрать.
