### ISSUE TITLE
Полевые медикаменты

### ISSUE THREAD

**Issue by Glucocorticoid** [skyarkhangel/Hardcore-SK#2361]
С медициной какая-то беда.

В игре присутствуют бинты и полевые медикаменты.

Но из вариантов лечения поселенцев пропали дополнительные опции по видам лечения. Остались только ванильные варианты: лекарственными травами, индустриальными медикаментами (красная аптечка) и продвинутыми медикаментами.

Куда-то пропало лечение бинтами и полевыми медикаментами.

**Comment by SetAriman** [comment]
Есть такое. Но пока не исправят, это можешь "обойти". Скажем если есть зелёные аптечки, можешь назначить лечение красными. А чтобы красные не тратились (если есть на складе), запретить их стаки к использованию. И пешки будут лечить максимально лучшими аптечками из имеющихся, которые хуже красных.

**Comment by l29ah** [comment]
К сожалению, запретить стеки в сундуках невозможно: клик на галочку ничего не меняет.

**Comment by SetAriman** [comment]
Если пользуешься зелёными и бережёшь красные - храни красные на полу. Один-два стека на складе погоды не делают. Зато не будешь их тратить за зря. 
P.S. "Есть проблема - реши её!" )

**Comment by Glucocorticoid** [comment]
Fixed 01d640c
