### ISSUE TITLE
world generation problem

### ISSUE THREAD

**Issue by Twielru** [skyarkhangel/Hardcore-SK#2369]
https://prnt.sc/u1r2oz
just made a fresh installation of hardcore sk 1.1. trying to generate a new world and each time this happens

**Comment by sidfu** [comment]
unless u have royality disable asari

**Comment by Twielru** [comment]
got the royalty. disabled asari and world got generated. thank you

**Comment by skyarkhangel** [comment]
last update, on 1.2 added Asari race mod compatibility without royalty dlc.
