### ISSUE TITLE
Kibble no longer uses hay.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#237]
Kibble no longer uses hay.  Instead you are to rely on hard to grow vegetables that more then likely you can't grow due to not having any access to seeds.

Is this intentional or an oversight?

**Comment by jnkyacc** [comment]
You receive hay absolutely for free, even no seeds requires. It would be unfair turning only meat to twice larger stack of food.

**Comment by Vigilence** [comment]
I thought that was the whole point of making kibble, for the food advantage.   Since it's part of the vanilla version as well.  

Maybe they will change it down the road.

**Comment by jnkyacc** [comment]
You still have silage to make. Vanilla quite casual. Btw its vanilla recipe not SK.
In ice sheet biome you don't have much place for growing hay, so here comes kibble time.
