### ISSUE TITLE
Caffeine addiction creates need "Alcohol"

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#2377]
![screenshot-alco](https://user-images.githubusercontent.com/31852/90792956-cc518600-e313-11ea-8d57-18331582b4ae.png)

**Comment by l29ah** [comment]
Also when the addicted drinks coffee, it doesn't replenish the need bar, making the pawn consume all the coffee it can find.

**Comment by Voker57** [comment]
fix: https://github.com/Voker57/Hardcore-SK/commit/98b84a73b5dae06cad9ce852d1f824b776a81875

**Comment by l29ah** [comment]
This commit only fixes the description, not the insatiability.

**Comment by Voker57** [comment]
fix fix: https://github.com/Voker57/Hardcore-SK/commit/370dbd59afd8813dd137978ef4ea890b470e6421

**Comment by Voker57** [comment]
got fixed in linked MR
