### ISSUE TITLE
Burn pit doesn't react to the "Toggle automatic refuel" setting

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#2378]
Pawns reload it with fecal sludge regardless, so the only way to avoid losing such a valuable resource is to dismantle the pit (and rebuild it back when your shit overflows again).

**Comment by Aldentr** [comment]
Добавлю, что в HSK 1.1 у меня на отключение этой опции не реагировали факела, костер и surgery lamp (не знаю как она переведена) и печь из раздела температуры тоже.

**Comment by skyarkhangel** [comment]
исправлено.

**Comment by Voker57** [comment]
все эти предметы еще перезаряжаются автоматически вне зависимости от настройки, с последним development.

**Comment by l29ah** [comment]
Still broken.

**Comment by l29ah** [comment]
If i just forbid all kinds of fuel in the settings, the game allows all fuel on its own after the game is unpaused.

**Comment by Voker57** [comment]
Still broken.
