### ISSUE TITLE
Малярия убивает

### ISSUE THREAD

**Issue by Glucocorticoid** [skyarkhangel/Hardcore-SK#2385]
На карте есть четверка малярийных мух-мутантов, живет на углу карты. Держит в страхе всю округу. Опаснее тигров и снежных леопардов.

За короткое время уничтожает все теплокровное. На скрине  7 трупов оленей, два снежных леопарда и черепаха. Все трупы свежие, погибли от малярии (смертельная).

Кроме поселенцев эту заразу не может убить ничего. Животные мухам-мутантам не дают сдачи. Малярия у животных развивается очень быстро и становится смертельной.

Хищники не так опасны. Может стоит дать животным возможность отбиваться от этих тварей? Опустошительнее только набег рапторов.

![image](https://user-images.githubusercontent.com/34233184/90956166-9daaeb00-e48c-11ea-81d4-9682f4efbd33.png)

**Comment by Voker57** [comment]
Мух и прочих тараканов надо просто удалить. Движок не приспособлен для правильной обработки таких мелких существ. Они наносят непропорционально сильные удары, а правильной борьбе с ними никто не обучен.
