### ISSUE TITLE
Исчезновение инвентаря при сжигании пешек на костре

### ISSUE THREAD

**Issue by Glucocorticoid** [skyarkhangel/Hardcore-SK#2399]
На поселение напали 3 врага с гранатами на палках в рюкзаке и по 33 ед. нефрита в рюкзаке у каждой пешки. Были обезврежены выстрелами издалека и сложены на склад для дальнейшей утилизации в пепел. Инвентарь каждой проверен на наличи поживы и нефрит был у каждой.

Создан костер и задание сжигать трупы. После сжигания вокруг костра остается только экипированная одежда, а содержимое инвентаря пропадает. Если не раздевать трупы вручную - все сгорает. Никаких ошибок в логе не остается. Никакого нифрита тоже не осталось. лежать рядом с костром. На склад не утащили - там пусто.

Также заметил, что при падении транспортных капсул с погибшими внутри, с некоторых пешек неудается снять комбинизоны - операция выполняется, но снятой одежды рядом не появляется. Шансы будто 50/50 на успех. Целостности одежды до сняия была например 143/250, т.е. изношена, но не в 0.

**Comment by ArpoMo6** [comment]
Проверьте настройки модификации Non Uno Pinata

**Comment by Glucocorticoid** [comment]
Настройки противоречат действительности:
![image](https://user-images.githubusercontent.com/34233184/91083022-422a5a00-e652-11ea-9a9c-1abac79ed74e.png)

По настройкам должно снимать снаряжение и инвентарь при кремировании, в действительности происходит ровно наоборот - снимает одежду, но не снимает инвентарь и снаряжение
