### ISSUE TITLE
Crafter moves an unfinished item on a crafting station back and forth in a cycle

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#2416]
Save file: http://0x0.st/iE1G.xz

**Comment by Szara-ManOfHonor** [comment]
Is there a lot of stuff on the ground and maybe also the workbench?
I've only seen this happen when they didn't have a valid place to drop the unfinished item (and unfortunately 'valid' here seems to be strictly defined by the game).
Opening up some space in front of and/or besides the bench, even just a few tiles, has always fixed this before for me.

**Comment by l29ah** [comment]
Yes indeed, there's stuff around the bench, but plenty of open space too: ![](https://tinystash.undef.im/il/3U4gfCD39izEy1zyuv31g2qo5fcFmKpY1Q3Rt98H8XHchdandAk6DbCQodD8BM7SNLEyfjeSVfZghU1B94yrcXS)
Removing all the stored items from around the pawn crafting spot (smokeleaf and glass) has no effect.
I had a similar setup in vanilla, and it didn't have any problems with moving/storing the unfinished stuff.

**Comment by zakhad** [comment]
It's a bug myself and sid have known about for the longest time, I can't exactly remember the reason why it does it - i think it's something to do with unfinished tools/weapons not having the right tag, might need to compare it to unfinished ammo/apparel as they don't seem to have this problem, and is simply moved off of the table.

**Comment by Glucocorticoid** [comment]
@l29ah Does the crafter have any tools for work? I had same problem for a while. I think its because pawn have a couple of same crafting tools and pawn do switching it while crafting.  After 1.2 version this problem has gone. I`m assign crafting tools through equipment set. In current session all crafters never do any wired things with crafting benches. I think it SimpleSideArms mod bug.

**Comment by l29ah** [comment]
No, the crafter doesn't have any tools.

**Comment by omyasniko** [comment]
Im meet this thing in this scenario. Crafter already working to create tool #1 (Axe i believe) im change priority from axe to tool #2 (hammer i believe) when he still working. Then he start to juggle with both unfinished items.Im change priority back and he finished both jobs. Meet this only once.

**Comment by sidfu** [comment]
this is more of a combo issue of how some mods interact. this causedx by 3 things
1. the item can only be moved 1 u down or to sided so effecitvly leaving only 2 spots
2. its by a diffent crafter
3. lthe hual to iventory

 all these things create a ara for it to happen. what i recommend is to 
1. not have ever perton in colony a crsfter
2. set a skill level on the bill so fewer dan do it
3. give each crafter their own p[rimary usedbench(not every bench thou)

there is a mod to remove owndership of the temp item but far as ive heard it caused random bugs for items like item tho null ref constaly, broken stories or item just disspear randomly when finish

**Comment by Glucocorticoid** [comment]
@l29ah With attached save file I have error every time:

```
Tuuino started 10 jobs in 10 ticks. List: (Wait_MaintainPosture (Job_1989198)) , (HaulToCell (Job_1989201) A=Thing_UnfinishedWeapon910747 B=(156, 0, 109)) , (Wait_MaintainPosture (Job_1989202)) , (HaulToCell (Job_1989205) A=Thing_UnfinishedWeapon910747 B=(156, 0, 108)) , (Wait_MaintainPosture (Job_1989207)) , (HaulToCell (Job_1989211) A=Thing_UnfinishedWeapon910747 B=(156, 0, 109)) , (Wait_MaintainPosture (Job_1989212)) , (HaulToCell (Job_1989215) A=Thing_UnfinishedWeapon910747 B=(156, 0, 108)) , (Wait_MaintainPosture (Job_1989216)) , (HaulToCell (Job_1989219) A=Thing_UnfinishedWeapon910747 B=(156, 0, 109))  curDriver=JobDriver_HaulToCell (toilIndex=4) curJob=(HaulToCell (Job_1989219) A=Thing_UnfinishedWeapon910747 B=(156, 0, 109))
Verse.Log:Error(String, Boolean)
Verse.AI.JobUtility:TryStartErrorRecoverJob(Pawn, String, Exception, JobDriver)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Verse.Pawn.Tick_Patch1(Pawn)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()
```

For current work "Make Pickax" chosen another crafter: Tranca. Current crafter - Tuuino. Unfinished pickax linked to Tranca too.
![image](https://user-images.githubusercontent.com/34233184/91642780-c86de400-ea36-11ea-9e0d-63e6948cf252.png)

I think that is a problem. Tuuino can`t done this job because it for Tranca

**Comment by Glucocorticoid** [comment]
Tranca has no problem to complete this work, just tested it. Tuuino will never complete this task because he not allowed to work  with unfinished item from another crafters.
