### ISSUE TITLE
Make possible to choose fuel type.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#242]
Is it possible to make it for player to decide which type of fuel to use in furnace and other fuel consuming things (like torches) and in which order? For example, I make kindling from wood, cause in this case I preserve some wood logs as you get twice more kindling as fuel after chopping, but my haulers keep trying to use closest available fuel resource (like bamboo or wood logs) instead kindling for fueling those things, and it becomes quite annoying after time, making them manually go after kindling, especially if you have plenty of torches around your colony.

**Comment by Vigilence** [comment]
Yeah, I like that idea alot.  I hate it when they use valuable fuel for refueling when they have logs laying around.

**Comment by skyarkhangel** [comment]
May be... if we rework vanilla's "ugly" refuel system.

**Comment by skyarkhangel** [comment]
Reworked
