### ISSUE TITLE
Refuel / Fuel / Energy Problems

### ISSUE THREAD

**Issue by JuroDragon** [skyarkhangel/Hardcore-SK#2420]
At start I was thinking it because of scenario. So I played a bit, noticed that buildings that need fuel or energy just create items without them. Furnace can smelt everything without fuel like normal crafting table. Can't put fuel into simple grill/furnace/steam generator. Hamster wheel generating energy normally. At 0% refuel it don't show that green carnister but it doesn't help at any 0-100%. My pawns with full priority in hauling also can't do anything about it. Turning off firewood, logs or other types disabling doesn't fix anything. I have in storage - charcoal, firewood, logs. I just play with royalty and without Asari mod. I tried reinstalling game/modpack, other scenarios, regions. I use newest hardcore sk from launcher and 1.1.2618 (64bit) game. Droid batteries also not usable. Clicking on android paw to recharge option not working - he just eat normal food to recover. Only thing that my pawns refuell are light torchs :D Any ideas which mod is bugged here? For me is like whole energy system is turned off or smth. Or I should use different version of game? 
https://imgur.com/J4p8hWq

**Comment by Spaniard829** [comment]
For 1.1 (stable, master), highly recommended version 1.1.2647. You can also try 1.1.2654, but the first option is preferable.

**Comment by JuroDragon** [comment]
Tried 1.1.2654 not worked with new save.

**Comment by zakhad** [comment]
A couple of people have reported problems using 1.1.2618 you have to use 1.1.2647 or 1.1.2654. The fueling system is unique to SK (It was from a mod in like A16/B17 but it's integrated into the dll which can't be turned off easily so to speak.)

These problems haven't been reported with 1.1.2647 or  1.1.2654 so it's something to do with 1.1.2618 and using the latest version of the 1.1 modpack which wasn't intended to be played on a older 1.1 rimworld build, harmony hugslib, various references get changed and need updating and I simply assume that 1.1.2618 is asking for references that either don't exist or have been changed during the course of the update either it's the packs end or the base game, which results in this weird fueling behaviour. 

1.1.2647 and 1.1.254 both have been confirmed to work with the pack - I'm running 1.1.2654 myself.

Check to see if you're able to play vanilia first with a clean install, then install the modpack.

**Comment by JuroDragon** [comment]
Ya it worked when i hard removed every files/configs and reinstalled it for 1.1.2654. Thank you :3 Even Asari mod worked with map generation lol.
