### ISSUE TITLE
Traps and wild animals

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#243]
It seems those two not interacting with each other properly. Cause in v12, it was possible to put traps in the wilderness where animals wanders, and they being accidentally stepping on them, and it was like a good hunting idea, though, now, it seems that even enraged animals avoiding them on purpose. Like when man-hunting pack attacks happen, those animals simply forcing through traps, without them being triggering even once, making traps only useable for defense against human attacks.

**Comment by Vigilence** [comment]
I used to think that as well when I first started.  I would be great if it can be used for hunting as well.

**Comment by jnkyacc** [comment]
Trigger has 80% chance and work only toward hostile. More over I find out by experimenting that body size affecting on this chance as well. So little animals have less chance to trigger than human or orc.

**Comment by sidfu** [comment]
its not just hostile. ive had trader guards and their animals trigger traps. it forced me to get rid of all traps or have traders arrgoing me.
