### ISSUE TITLE
meditation is absent from schedule

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#2432]
Royalty introduced meditation schedule item, but it's missing from Hardcore-SK.

**Comment by l29ah** [comment]
Yea, it makes one effectively unable to make psycasters while being an enemy of the kingdom.

**Comment by sidfu** [comment]
is a bug with classroom mod. use steam version  it or use the setting labed classroom  and they shoiuld do it.

**Comment by sidfu** [comment]
is now fixed in newest version
