### ISSUE TITLE
Проблемы с нефтянкой

### ISSUE THREAD

**Issue by Rikkimari** [skyarkhangel/Hardcore-SK#2437]
В последней версии игры, в списке построек отсутствует платформа для разгрузки переработчиков нефти

**Comment by SomethingCrunchy** [comment]
во вкладке "хранилища" искал?

**Comment by Rikkimari** [comment]
сейчас гляну, но раньше оно точно было во вкладке нефтянки

**Comment by Rikkimari** [comment]
и правда в хранилищах, спасибо за помощь!

**Comment by l29ah** [comment]
По логике соответствующая кнопка должна быть в меню самих переработчиков, как с кроватями и крафтинг-стейшонами, но нет, её нужно искать непонятно где.

**Comment by ArhinZi** [comment]
Вроде можно закрыть, насколько помню в новых проблема решена
