### ISSUE TITLE
D development версии не работают задания на Костре

### ISSUE THREAD

**Issue by Impleks** [skyarkhangel/Hardcore-SK#2438]
В версии 1.2.27.23 Не работают задания на Костре
На костре выставлены задания сжигать трупы и готовить мясо, если выбрать поселенца и кликнуть правой кнопкой мыши на костер, появляется только "Заправить костер" других заданий нет.  

Поселенцам выставлены соответствующие задания, объекты для сожжения и готовки в пределах досягаемости.

**Comment by omyasniko** [comment]
Дай угадаю костер На улице/не под крышей и идёт дождь?

**Comment by SergeyDeCollantes** [comment]
Надо добавить оповещение какое-то на этот случай...

**Comment by SomethingCrunchy** [comment]
это оповещение - необходимость заправки и температура костра

**Comment by SergeyDeCollantes** [comment]
Если идёт дождь/пылевая буря и костёр на улице,то ничего не будет написано.Как если бы задания не было

**Comment by omyasniko** [comment]
Костер на улице в дождь если я помню корректно выглядит потухшим. Чем не оповещение

**Comment by Impleks** [comment]
Как ни странно, простой навес в 1 клетку помог, спасибо!
