### ISSUE TITLE
development Отображение функции Перенести все

### ISSUE THREAD

**Issue by Impleks** [skyarkhangel/Hardcore-SK#2439]
RimWorld 1.2.2723 rev661

Нет кнопки Перенести все, верней она есть, но отображается совсем не так как нужно
При клике на стак, появляется:
Перенести <предмет> 
перенести <предмет> именно с маленькой буквы

Вот так это выглядит на скрине
https://skr.sh/s44BIIP5Vfo

С большой буквы работает как Перенести все, с маленькой только выбранный предмет

**Comment by Glucocorticoid** [comment]
Так и задумано. При нажатии на "Перенести предмет" пешка схватит эту вещь и все ближайшие к ней, пока не заполнит себе инвентарь. "перенести предмет" перенесет только выбраный предмет.

**Comment by Impleks** [comment]
Раньше же было написано, перенести все, как теперь угадывать? Новичку например, мне кажется это надо как то в скобках поправить, как раньше было.

**Comment by Impleks** [comment]
Ну в принципе вопрос решен, спасибо.
