### ISSUE TITLE
Furnace power trigger.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#244]
I certainly remember it was just there about two days ago, and now, it is gone, probably happened in one of the latest patches, by accident probably.

**Comment by sidfu** [comment]
it was removed as u could use the them while they where off. now there no off switch but on other hand they went from 12hours of fuel to 2 days now.

**Comment by skyarkhangel** [comment]
This building have open fire and cant be flickable. Greatly reduced fuel consumption.
