### ISSUE TITLE
Development Не переключаются инструменты

### ISSUE THREAD

**Issue by Impleks** [skyarkhangel/Hardcore-SK#2445]
версия 1.2.2.5753

Не пойму как работают инструменты, визуально ничего не переключается, но если смотреть информацию то показывается что бонус от инструмента есть

Пример со строительством, у Пешки есть молоток, но строит она почему то с автоматом в руках
https://skr.sh/s/130920/cWB3kuEi?refresh=10

А если смотреть информацию о строительстве, то указан бонус за молоток
https://skr.sh/s48PxfShACA

С шахтерством такие же дела, копает с автоматом. 
https://skr.sh/s48gleMcsaW

В то же время, повар переключается на секач! 
https://skr.sh/s48jsc2pZZ9

Если нужна какая то дополнительная инфа, скажите пожалуйста, предоставлю. 

С модами не упарывался, вроде ничего такого не ставил. при загрузке красное в логе было только по alpha animals

**Comment by ArpoMo6** [comment]
@Impleks откатиться до версии 1.2.2723. Версия 2753 вышла только вчера.
![image](https://user-images.githubusercontent.com/62516232/93015537-bb72f800-f5d3-11ea-8b1b-51c03f0aa32e.png)

**Comment by Impleks** [comment]
Понял, спасибо, сейчас откачусь. По результату сообщу.

**Comment by Impleks** [comment]
Не, все так же не переключается 
https://skr.sh/s48nQtD3JlJ

Откатился на 1.2.2723
https://skr.sh/s48Khl4vReo

**Comment by Impleks** [comment]
Переключаются только повара на секачи при разделке и готовке. 

Копают и строят все так же с автоматами в руках....

**Comment by Impleks** [comment]
Я все починил.... 
Я все же пееборщил с модами.
Simple sidearms зачем то поставил, https://steamcommunity.com/sharedfiles/filedetails/?id=927155256
Встроенного simple sidearms lite вполне достаточно.
