### ISSUE TITLE
Development Пустая черта в биографии

### ISSUE THREAD

**Issue by Impleks** [skyarkhangel/Hardcore-SK#2448]
Вот что нашел
*Отсутствуют бонусы у черты в Биографии у Дитя колонии*
https://skr.sh/s491QEiYsau

Так и должно быть? 

Просто остальные трейты или как их назвать начинающиеся с Дитя имеют бонусы к статам.

**Comment by telekin22** [comment]
Трейт автоматически выдаётся тому, кто родился в колонии, мод children school and learning.  Ребёнок только появился на свет, у него ещё нет никаких заслуг или грехов, за которые бы можно было отсыпать статов, только врождённые рандомные навыки. В англоязычной версии описание тоже короткое: "[PAWN_nameDef] was born and grew up on a rimworld-colony."

**Comment by Impleks** [comment]
ну я понял, спасибо. значит так и должно быть.
