### ISSUE TITLE
Eating after sleep.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#245]
I was curious if it is possible to force colonists to eat after they waking up, cause, sometimes, when they are not so hungry, they instantly trying to go for their jobs, but, it that job is quite distant (like mining distant ore node), they aim for that at first, but stop at half-way, and turn around to eat something, which makes them lose quite much time at some cases. A half-solution to that, is to give them some food in invetory, of course, though, the problem is they get quite big mood penalties for eating without table and such.

**Comment by jnkyacc** [comment]
You can force them to eat manually. Keeping food in inventory have a temporary issue with CombatRealism.

**Comment by skyarkhangel** [comment]
Closed.
