### ISSUE TITLE
Баг с простым кардиопротезом

### ISSUE THREAD

**Issue by Selengiks** [skyarkhangel/Hardcore-SK#2450]
Поставил простой кардиопротез, и хотя эффективность его 50%, ниначто это не влияет
![RimWorldWin64_ZdCo6Sw3WI](https://user-images.githubusercontent.com/38987970/93482635-96022900-f908-11ea-9261-2eaa572e0058.jpg)

**Comment by ArhinZi** [comment]
Насколько я понимаю протез должен быть не на теле, а вместо сердца

**Comment by ArhinZi** [comment]
> Поставил простой кардиопротез, и хотя эффективность его 50%, ниначто это не влияет
> ![RimWorldWin64_ZdCo6Sw3WI](https://user-images.githubusercontent.com/38987970/93482635-96022900-f908-11ea-9261-2eaa572e0058.jpg)

Попробуй запустить режим разраба и попробовать поставить другой протез, бионический например. Судя по дефам они работают одинаково.
