### ISSUE TITLE
Зачем вернули странную системы сбора грязи и торфа?

### ISSUE THREAD

**Issue by surabujin** [skyarkhangel/Hardcore-SK#2467]
В поздней сборке для 1.0 убрали "бесконтрольную" сборку грязи и торфа с любой заболоченной клетли любое количество раз. Заменив ее на вполне адекватную систему терраформирования в которой при "выкапывании" мы получаем всякие ресурсы (ту же грязь), а при закапывании мы их тратим.

В текущей devel ветке на 1.2 системы сбора грязи/торфа вернули к той что была изначально в 1.0. Можно ли получить нормальную/адекватную системы терраформирования (ту что ввели в поздней 1.0)?

**Comment by SomethingCrunchy** [comment]
взять с гитхаба версию со старым новым террафоримрованием

**Comment by Zim777** [comment]
В действительности вопрос, зачем вернули старую систему терраформинга?
новая система фактически была идеальна
