### ISSUE TITLE
Tame hay

### ISSUE THREAD

**Issue by Quelling** [skyarkhangel/Hardcore-SK#248]
Баг с сеном. Чтобы приручить кого-то необходимо иметь сено в **инвентаре.** Т.е если на складе есть сено, то пешка ничего не делает. Если конкретно самому заставить взять сено, то пешка идёт приручать.

**Comment by jnkyacc** [comment]
Пробуй нацепить рюкзак.

**Comment by ochkoebanoe** [comment]
Нет. https://i.gyazo.com/6432cc55b4f8f189f5c861bb35d4032a.png

**Comment by jnkyacc** [comment]
Хм... в ванилле тоже не хотят...

**Comment by ochkoebanoe** [comment]
Ну да, не баг а "фича". Но лучше бы исправить.

**Comment by jnkyacc** [comment]
Честно говоря не представляю как это сделать. Ванильный воркгивер онально огорожен. А они будут коримить тем что в инвентаре в любом случае, если это жрет скотина.

**Comment by ochkoebanoe** [comment]
Хм, ну тогда остается написать новый класс hay_sk, который будет иметь нужные значения.

**Comment by jnkyacc** [comment]
А стоит оно того? :) Это как с грибами синими которые сырыми жрутся боротся.

**Comment by ochkoebanoe** [comment]
Скорее всего нет. Но оставлять так тоже не дело. С грибами то ладно, грибы сырыми есть можно. Не все правда, но будет считать, что конкретно синие можно.

**Comment by Inei** [comment]
По поводу грибов - у них там просто приоритет стоит на съедобность слишком высокий, можно поправить изменив данный параметр в файлах мода.

**Comment by harchschoolboy** [comment]
Вообще вся проблема от того что у сена отдельный тип, чтоб его поселенцы не жрали.
Если сменить тип на обычный, то сено работает аж бегом. На форуме предлагали не париться, и просто разрешить всем жрать сено, нутришн там крохотный совсем, плюс приоритет понизить. Это сразу вылечит проблему.

Они блин трупы жрут, а вы из-за сена переживаете.

**Comment by Vigilence** [comment]
I noticed this too, animals are eating the hay, but I can't tame anything nor can I train them with it.

**Comment by Inei** [comment]
Just put the hay in the inventory of your animal handler manually, and you'll be able to tame with it as well.

**Comment by harchschoolboy** [comment]
Inei, it's not solution, it's workaround.
Hay should work as well as any other food.

**Comment by Inei** [comment]
Yep, it's workaround, but, until they'll make a patch for this in mod files, it's only way to make it work.

**Comment by harchschoolboy** [comment]
I wrote a solution before, sorry if you probably don't understand russian.

So, the solution is to make hay same type as other vegetables. It's mean that hay will work, but also it will mean that pawns will be able to eat hay :3
It's nutrition is too small, so they will eat hay only if they don't have any other food.
Also, if they're able to eat dead bodies, why they can't eat hay?

**Comment by jnkyacc** [comment]
> Hay should work as well as any other food.

Нет не должен. Сверху ссылка возьми почитай.

**Comment by harchschoolboy** [comment]
я ж не о том что оно якобы везде работает, а у нас нет, я о том что оно нигде не работает, а должно

**Comment by jnkyacc** [comment]
Не должно оно работать. Сено не "вкусняшка", а поэтому для приручения не используется. У нас "фитча" благодаря CR - доступ к инвентарю, в который мы можем сено запихать и он пойдет приручать сеном. В ваниле доступа к инвентарю нет, а поэтому сено там врятли когда окажется.

**Comment by skyarkhangel** [comment]
Ответ дан в предыдущем сообщении.
