### ISSUE TITLE
Cut Tree order doesn't work sometimes

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#249]
Error Message: Must designate wood-yielding, sufficiently-grown plants.

Issue: Unknown. Manual selection works (clicking on the tree and selecting chop tree). Couldn't reproduce the bug when I planted a tree and grew it to maturity via development mode. Same issue for every kind of tree. In fact the Cut Tree order only works for very few developed tree. 

Might be a tool tip issue. Trees get harvestable after I use the Grow to Maturity tool/ Finish plant growth tool.

Edit: Forgot to say that the Tooltip says "Ready to harvest", which implies fully grown I assume. Also uses the model for a fully grown tree.
The Grow1 day tool also makes them harvestable, but fast forwarding one or more day(s) doesn't. Might be a bit more complicated problem.

**Comment by sidfu** [comment]
its a bug. the tool not reconizing those trees right. 
u can get around it by if u useing the colony manager and have it cut the full grown trees. t finds them fine.
