### ISSUE TITLE
Отсутствует описание "Мобильный сонар минералов" v2020.10.16

### ISSUE THREAD

**Issue by Westus** [skyarkhangel/Hardcore-SK#2504]
![2020-10-19_19-15-10](https://user-images.githubusercontent.com/4818769/96485514-46838580-1245-11eb-99f0-d9b4f63cc605.png)

**Comment by Spaniard829** [comment]
Appears when crafting/spawning an item.
After installation and "removal", it returns to normal.
Also, it has different strength values. Steel, 340 mounted, 100 minified.

---
Проявляется при крафте/спавне предмета.
После установки и "убирания", приходит в норму.
Также, имеет разные значения прочности. Сталь, 340 установленный, 100 убранный.

![image](https://user-images.githubusercontent.com/67763632/100284193-da045080-2f7f-11eb-9f2a-a0db07509ded.png)
