### ISSUE TITLE
Встречайте то чего вы так долго ждали

### ISSUE THREAD

**Issue by Pepelnica1488** [skyarkhangel/Hardcore-SK#2509]
https://github.com/cseelhoff/RimThreaded

Свеженький мод на многоядерность,вроде как работает с небольшим статтером раз в несколько секунд,осталось только заставить разрабов хск запилить это в СЮДА что бы золотой век наконец то настал

**Comment by AndreiAvinov** [comment]
Не работает с кучей модов, может когда нибудь...

**Comment by Zim777** [comment]
Ураа, у нас появился доброволец, желающий пилить этот мод под хск,
Поздравим же нашего добровольца, **Pepelnica1488**

**Comment by SomethingCrunchy** [comment]
держим за человека кулачки и надеемся на скорейшую адаптацию

**Comment by Pepelnica1488** [comment]
Подсосы конечно смешные но нет,сразу видно гниль разраба который нихуя не хочет делать и зажрался в донатах хотя судя по отсутствующим ошибкам там поправить 2 строчки что бы всё работало как надо

**Comment by godkron** [comment]
> Подсосы конечно смешные но нет,сразу видно гниль разраба который нихуя не хочет делать и зажрался в донатах хотя судя по отсутствующим ошибкам там поправить 2 строчки что бы всё работало как надо

Согласен рим тред 2.0 уже вполне неплохо работает со всеми хск примочками, но нужна доработка, некоторые вещи просто напросто кривые

**Comment by ArpoMo6** [comment]
> > Подсосы конечно смешные но нет,сразу видно гниль разраба который нихуя не хочет делать и зажрался в донатах хотя судя по отсутствующим ошибкам там поправить 2 строчки что бы всё работало как надо
> 
> Согласен рим тред 2.0 уже вполне неплохо работает со всеми хск примочками, но нужна доработка, некоторые вещи просто напросто кривые

Судя по списку несовместимых модов рим тредеда, несовместимых модов предостаточно. https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility#Incompatible
А именно:
- RocketMan - Performance Boost Mod;
- Vanilla Events Expanded (событие "Засуха" из указанного мода);
- Combat Extended (судя по описанию, до сих пор встречаются самые разнообразные баги и ошибки, но совместимость, вероятно, в будущем будет обеспечена разрабами Rim Threaded);
- предположительно, с модом на экспериментальную оптимизацию и частью функций Core_SK (т.к. ни одного из этих модов в мастерской нет, а какого-либо серьезного тестирования не проводилось).
Без совместимости с рокет мэном и экспериментальной оптимизацией смысла в Rim Threaded мало, т.к. оба мода нацелены на увеличение производительности, просто используют для этого разные методы, но первые два при этом обеспечивают прирост на любом железе.

**Comment by godkron** [comment]
> > > Подсосы конечно смешные но нет,сразу видно гниль разраба который нихуя не хочет делать и зажрался в донатах хотя судя по отсутствующим ошибкам там поправить 2 строчки что бы всё работало как надо
> > 
> > 
> > Согласен рим тред 2.0 уже вполне неплохо работает со всеми хск примочками, но нужна доработка, некоторые вещи просто напросто кривые
> 
> Судя по списку несовместимых модов рим тредеда, несовместимых модов предостаточно. https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility#Incompatible
> А именно:
> 
> * RocketMan - Performance Boost Mod;
> * Vanilla Events Expanded (событие "Засуха" из указанного мода);
> * Combat Extended (судя по описанию, до сих пор встречаются самые разнообразные баги и ошибки, но совместимость, вероятно, в будущем будет обеспечена разрабами Rim Threaded);
> * предположительно, с модом на экспериментальную оптимизацию и частью функций Core_SK (т.к. ни одного из этих модов в мастерской нет, а какого-либо серьезного тестирования не проводилось).
> 
> Без совместимости с рокет мэном и экспериментальной оптимизацией смысла в Rim Threaded мало, т.к. оба мода нацелены на увеличение производительности, просто используют для этого разные методы, но первые два при этом обеспечивают прирост на любом железе.

мне удалось наиграть на римтреде конечно 400 дней в хск и это было куда быстрее чем без него или с рокетмэном, я имею ввиду в реальном времени. Рим трэд это будущее и нет никакого смысла городить огород и тащить труп в виде рокет мэна, у него прирост производительности ну максимум 10%, когда у треда около 800. И на счёт багов, их вообщем то нет, за исключением работы 2 пешек на одинаковых станках или надевание одежды двумя пешками сразу или странное поведение медиков, но это настолько мелочь, что просто смешно. Проблема со стабильностью и отключением интерфейса куда болезненней, но и она проявляется уже ближе к лейту, а если сидеть на 1-2 воркерах так вообще не будет, но за это ты платишь тиками в секунду увы

**Comment by ArpoMo6** [comment]
Запустил мод на многопоток (рокет мэн и оптимизация выключены) - с самого же старта словил описанный баг на пропадание интерфейса.
![image](https://user-images.githubusercontent.com/62516232/125122927-7f36f800-e10f-11eb-941f-1bf01418afc3.png)
В логе постоянно спамят те или иные красные ошибки от животных. У некоторых предметов (в основном, СЕшное вооружение) сломано описание.
Мод с ХСК, к сожалению, на текущий момент слабо играбелен, на мой взгляд.

**Comment by godkron** [comment]
> Запустил мод на многопоток (рокет мэн и оптимизация выключены) - с самого же старта словил описанный баг на пропадание интерфейса.
> ![image](https://user-images.githubusercontent.com/62516232/125122927-7f36f800-e10f-11eb-941f-1bf01418afc3.png)
> В логе постоянно спамят те или иные красные ошибки от животных. У некоторых предметов (в основном, СЕшное вооружение) сломано описание.
> Мод с ХСК, к сожалению, на текущий момент слабо играбелен, на мой взгляд.

версия хск и треда?

**Comment by ArpoMo6** [comment]
> > Запустил мод на многопоток (рокет мэн и оптимизация выключены) - с самого же старта словил описанный баг на пропадание интерфейса.
> > ![image](https://user-images.githubusercontent.com/62516232/125122927-7f36f800-e10f-11eb-941f-1bf01418afc3.png)
> > В логе постоянно спамят те или иные красные ошибки от животных. У некоторых предметов (в основном, СЕшное вооружение) сломано описание.
> > Мод с ХСК, к сожалению, на текущий момент слабо играбелен, на мой взгляд.
> 
> версия хск и треда?

Последняя дев, версия треда из стима.

**Comment by godkron** [comment]
<ModsConfigData>
  <version>1.2.3009 rev734</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>pirateby.harmony.optimizer</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>skyarkhangel.rimthemeslite</li>
    <li>skyarkhangel.coretranslation</li>
    <li>skyarkhangel.royaltytranslation</li>
    <li>unlimitedhugs.hugslib</li>
    <li>erdelf.humanoidalienraces</li>
    <li>ceteam.combatextended</li>
    <li>skyarkhangel.hsk</li>
    <li>killface.facialstuff</li>
    <li>diannetea.facialstuffdefaults</li>
    <li>killface.alienfaces</li>
    <li>brrainz.cameraplus</li>
    <li>skyarkhangel.skynet</li>
    <li>skyarkhangel.skynetfaces</li>
    <li>chjees.androids</li>
    <li>skyarkhangel.androidfaces</li>
    <li>void.charactereditor</li>
    <li>dubwise.rimefeller</li>
    <li>neceros.deepscannersettings</li>
    <li>fluffy.worktab</li>
    <li>ghxx.techadvancing</li>
    <li>cattleya.florareskin</li>
    <li>weilbyte.snapout</li>
    <li>skyarkhangel.simplesidearms</li>
    <li>syrchalis.setupcamp</li>
    <li>notfood.seedsplease</li>
    <li>savestoragesettings.kv.rw</li>
    <li>maxzicode.zitools</li>
    <li>ratys.rtsolarflareshield</li>
    <li>ratys.rtfuse</li>
    <li>historic.industrialrollers</li>
    <li>storage.search.rsa</li>
    <li>fluffy.relationstab</li>
    <li>automatic.recipeicons</li>
    <li>haplo.miscellaneous.robots</li>
    <li>mehni.pickupandhaul</li>
    <li>oblitus.mylittleplanet</li>
    <li>multilangcolorfultraits.pirateby</li>
    <li>tgc.moreinfobox</li>
    <li>haplo.miscellaneous.training</li>
    <li>captainmuscles.categorizedbills</li>
    <li>dubwise.dubsmintmenus</li>
    <li>dubwise.rimatomics</li>
    <li>dhultgren.keepbedownership</li>
    <li>falconne.bwm</li>
    <li>arandomkiwi.huntforme</li>
    <li>orion.hospitality</li>
    <li>antaioz.modmedicinepatch</li>
    <li>likeafox.haulexplicitly</li>
    <li>wiseclock.ac.daysmatter</li>
    <li>jkluch.haultostack</li>
    <li>albion.goexplore</li>
    <li>skyarkhangel.fencesandfloors</li>
    <li>wit.expandedroofing</li>
    <li>dubwise.dubsperformanceanalyzerbutchered</li>
    <li>dubwise.dubsbadhygiene</li>
    <li>hsk.holybasin</li>
    <li>tikubonn.dontblockdoor</li>
    <li>mlie.dismisstrader</li>
    <li>mckay.colonyleadership.11</li>
    <li>dylan.csl</li>
    <li>crashm.colorcodedmoodbar.11</li>
    <li>hatti.cleaningarea</li>
    <li>jaxe.bubbles</li>
    <li>fluffy.areaunlocker</li>
    <li>com.github.alandariva.moreplanning</li>
    <li>com.bymarcin.architecticons</li>
    <li>fluffy.animaltab</li>
    <li>oblitus.animalslogic</li>
    <li>unlimitedhugs.allowtool</li>
    <li>skyarkhangel.survivaltoolslite</li>
    <li>skyarkhangel.degradation</li>
    <li>arpomo6.hmc.ussrwp</li>
    <li>solaris.ratkinracemod</li>
    <li>solaris.ratkinracemod.fs.hsk</li>
    <li>skyarkhangel.asarirace</li>
    <li>kikohi.cybernetic</li>
    <li>khamenman.armorracks</li>
    <li>avilmask.nonunopinata</li>
    <li>skyarkhangel.realisticdarkness</li>
    <li>pirateby.anothertweaks</li>
    <li>odeum.wmbp</li>
    <li>moretraitslots.kv.rw</li>
    <li>mehni.numbers</li>
    <li>saucypigeon.pawnbadge</li>
    <li>revolus.animalsarefun</li>
    <li>jaxe.foodrestrictions</li>
    <li>skyarkhangel.arachnophobia</li>
    <li>automatic.autolinks</li>
    <li>mlie.drugpolicyfix</li>
    <li>doug.nojobauthors</li>
    <li>mrcool92.agoc</li>
    <li>fluffy.medicaltab</li>
    <li>fluffy.backuppower</li>
    <li>avius.locks</li>
    <li>skyarkhangel.arcanetechnology</li>
    <li>name.krypt.rimworld.moddiff</li>
    <li>zacharyfoster.minerals</li>
    <li>zacharyfoster.mineralsfrozen</li>
    <li>automatic.incidenttweaker</li>
    <li>chippedchap.blueprinttotalstooltip</li>
    <li>pirateby.ce.extendedloadout</li>
    <li>pirateby.workrebalancer</li>
    <li>erdelf.moddercredit</li>
    <li>user19990313.runtimegc</li>
    <li>neronix17.wikirim</li>
    <li>glucocorticoid.energytab</li>
    <li>notfood.infused</li>
    <li>glucocorticoid.timebombs</li>
    <li>unlimitedhugs.defensivepositions</li>
    <li>glucocorticoid.hskmoreinfo</li>
    <li>uuugggg.sharetheload</li>
    <li>mlie.roadsoftherim</li>
    <li>avilmask.commonsense</li>
    <li>arandomkiwi.rimsaves</li>
    <li>jaxe.rimhud</li>
    <li>uuugggg.replacestuff</li>
    <li>fluffy.modmanager</li>
    <li>vitech.medievaloverhaul</li>
    <li>skharrs.replacer</li>
    <li>skyarkhangel.realisticterraform</li>
    <li>arpomo6.hldcrm</li>
    <li>skyarkhangel.caa</li>
    <li>skyarkhangel.mineralscanner</li>
    <li>telefonmast.graphicssettings</li>
    <li>orion.gastronomy</li>
    <li>factioncontrol.kv.rw</li>
    <li>edb.preparecarefully</li>
    <li>caesarv6.damageindicators</li>
    <li>mlie.colonistbarkf</li>
    <li>brrainz.achtung</li>
    <li>hatti.qualitybuilder</li>
    <li>hatti.qualitysurgeon</li>
    <li>qwerty19106.researchtreesk</li>
    <li>wit.betterminimap</li>
    <li>maxzicode.zitoolsbetterminimapaddon</li>
    <li>jaxxa.ed.enhancedoptions</li>
    <li>majorhoff.rimthreaded</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
  </knownExpansions>
</ModsConfigData>
вот мой список модов, есть подозрение что много проблем с дабсом, его миникарту я например не использую

**Comment by godkron** [comment]
> > > Запустил мод на многопоток (рокет мэн и оптимизация выключены) - с самого же старта словил описанный баг на пропадание интерфейса.
> > > ![image](https://user-images.githubusercontent.com/62516232/125122927-7f36f800-e10f-11eb-941f-1bf01418afc3.png)
> > > В логе постоянно спамят те или иные красные ошибки от животных. У некоторых предметов (в основном, СЕшное вооружение) сломано описание.
> > > Мод с ХСК, к сожалению, на текущий момент слабо играбелен, на мой взгляд.
> > 
> > 
> > версия хск и треда?
> 
> Последняя дев ХСК, версия треда из стима.

и ещё, они там у себя не указывают, но в любых конфликтах следует уменьшить количество ядер до нуля поиграть какое то время на сэйве и потом подключить ядра и уменьшить задержку до 1 и там уже повышать и танцевать с бубном а так да конечно печально, много чего делать приходится, но на самом деле разраб римворлда лучше бы не длц пилил а вводил бы многопоток, игра 2014го года жрёт 1 поток, просто смешно, хотя если парадоксам можно и люди хавают то почему ему нет?...

**Comment by ArpoMo6** [comment]
> ...разраб римворлда лучше бы не длц пилил а вводил бы многопоток...

Вот прям так возьмет и просто добавит всеми желанный многопоток... ну да, это ведь так просто...
Давно бы добавили, будь это так просто.

P.S. У себя в результате я не получил ну прямо ощутимого прироста от многопотока (где-то 15-20% относительно рокет мэна + оптимизации, хотя визуально игра действительно плавнее стала). Проц i7 2600k (4 ядра 8 потоков). Возможно, на 8-ми и более ядерниках прирост будет заметнее, но не в моем случае.

Думаю, вопрос с рим тредом на текущий момент неактуален. Возможно, в будущем что-то с этим и смогут сделать в ХСК, но сейчас скорее нет, чем да.

**Comment by Pepelnica1488** [comment]
пошёл в жопу

сб, 5 февр. 2022 г. в 05:18, skyarkhangel ***@***.***>:
