### ISSUE TITLE
Bug- Sometimes you can't build a door.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#252]

**Comment by Vigilence** [comment]
I've noticed this for a while.  Sometimes when you can't build a door.  It doesn't matter if there are two walls to the left and right of the door, you just can't build it.  

Notice in the pictures below. In the slate wall I made, there is an opening for a door to be made, but even though I have the wood I can't build it there.  In another picture, If I try in a different location I can.  

![screenshot 67](https://cloud.githubusercontent.com/assets/16742086/18327684/a6d14468-7519-11e6-9fc5-af59ede3ddb5.png)
![screenshot 66](https://cloud.githubusercontent.com/assets/16742086/18327685/a6d43420-7519-11e6-9e9b-84df3348a21e.png)
![screenshot 65](https://cloud.githubusercontent.com/assets/16742086/18327686/a6d447bc-7519-11e6-9903-8c772f1b03bb.png)
![screenshot 64](https://cloud.githubusercontent.com/assets/16742086/18327687/a6d69634-7519-11e6-84af-6683449df23b.png)

**Comment by Inei** [comment]
In current version you can't build a door right next to another door, there should be a space between them.

**Comment by Vigilence** [comment]
I see, sometimes I can and sometimes I can't which is why it's confusing.

**Comment by Inei** [comment]
I am not sure if different type of doors blocking each other, though, that can be an issue.

**Comment by Vigilence** [comment]
The issue remains regardless of the materials that were used for each door.
