### ISSUE TITLE
Mine extractor can be placed incorrectly

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#253]
The mine and advanced mine extractor can be placed in an invalid location. Doing so will cause it to immediately destroy itself. It'll work fine as long as you place it correctly though, but the correct position isn't very obvious for the advanced mine extractor.

**Comment by SmokeyUnicycle** [comment]
Geothermal also has this problem, and normal mine extractors too, but for some reason those survive sometimes even when half on the mining zone.

**Comment by jnkyacc** [comment]
Known issue. Placeworker from CCL little buggy

**Comment by skyarkhangel** [comment]
Ok. So, in next CCL version would work fine. 
For now, need to install exact in the center.
