### ISSUE TITLE
New updates causes pawns to just stand still and do nothing.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#255]
I installed new update and some of the pawns will just stand still and do nothing.  Drafting and undrafting them does nothing.

They will only move when they are ready to eat.

**Comment by Inei** [comment]
Not only that. Forbidding for equipment pieces and names for most equipment pieces display is bugged as well, though, the problem is seems to be only with the latest patch with "Fix clutter hologram" name. I've reverted back to "Merge pull #240" and it seems to be working fine.

**Comment by zakhad** [comment]
I'm not having this issue and i'm working with commit from Fix clutter holograms, Fresh install. Wasn't this an issue with psychology and right tools for the right job? I reported that issue similar to what you're describing a few days ago, but without details I've no idea if its the same.

**Comment by Inei** [comment]
Hmm, I had psychology enabled, but disabled it with that new patch, though, it is bugged the same way with or without psychology. Well, in that case, only starting new game will probably fix that.

**Comment by Owlchemist** [comment]
I had this problem too, at least when I applied the update to my existing colony. I was able to fix it by having everyone strip - clothing and equipment - and re-equip everything. Something to do with changes to infusion I think. I know some of the weapons broke too (you can tell if they're broken because they won't have their quality anymore, like awful, good, shoddy, etc).

**Comment by jnkyacc** [comment]
mb new outfitter issue

**Comment by Vigilence** [comment]
I tried that stripping to one pawn last night and he just still stood there like he was waiting on me. :(

**Comment by Owlchemist** [comment]
For future reference, enable dev tools in the options and view the debug log. That'll give you a hint at what's wrong.

I forgot to mention, all the wooden logs in my game were bugged and causing problems too. I had to delete them with the dev tools. Newly created logs there on out were fine.

**Comment by Vigilence** [comment]
Nice, I will try that next time.  Thanks for the tip.  :)
