### ISSUE TITLE
Question - What's people's prefered method of github upload i,e sourcetree or github desktop etc

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#2559]
As per the title just getting an idea of what people use or recommend.

**Comment by AndreiAvinov** [comment]
Sourcetree. Github desktop looks and feels too simplified

**Comment by Glucocorticoid** [comment]
I am use VSCode git-functions to push fixes and translate xml, console git utility to update local and remote repositories, github website for pull-requests. 

Console git with documentation is more powerfull than Github app. I tried github app and delete it.

**Comment by Spaniard829** [comment]
VS Code + GitLens
