### ISSUE TITLE
unable to install prostetics

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#256]
still unable to install them.

one of my colonist lost their food in battle. i made he wooden foot at the tribal prostetics bench but cant install it on them. not sure it might be tech related.

**Comment by Inei** [comment]
Yep, you need to research "Medicine I" first to be able to install anything, despite being able to make those things in tribal prosthetic bench. You can manually edit the requirements in "...\RimWorld14\Mods\Core_SK\Defs\RecipeDefs_Prostheses\Recipes_ProsthesesInstall_Basic.xml", in case you'll want to install that foot before researching that tech - simply remove  "<researchPrerequisite>SK_MedicineI</researchPrerequisite>" string from wooden foot installation recipes in there.

**Comment by sidfu** [comment]
ok didnt know that. to bad there not a way to have the wooden stuff not require research.

thanks for anwser glad its not another bug.
