### ISSUE TITLE
Drug Lab missing from production tab.  

### ISSUE THREAD

**Issue by DennisCorp** [skyarkhangel/Hardcore-SK#2586]
Rimworld version: 1.2.2753 
SK Development Release: 2020.11.29 09:08:56
HSK Launcher v1.6
Save File attached.
[Waum_NoDrugsLab.zip](https://github.com/skyarkhangel/Hardcore-SK/files/5612315/Waum_NoDrugsLab.zip)

Researched "Drugs Research II" which should unlock the Drug Lab.
The machine does not show up on the Production tab for building.

Via dev mode, I was able to add a Minified version of the table, and install that, which worked fine.  There is just no way to build the work table from the ingame menu.

**Comment by Spaniard829** [comment]
Please check again.
The table is displayed in the "production" category, subcategory "cooking stuff".
1.2.2723, your save file.
1.2.2753 is still not recommended.

![image](https://user-images.githubusercontent.com/67763632/100546029-1aa9e580-3270-11eb-8391-5933b952c984.png)

**Comment by DennisCorp** [comment]
Thanks champ.  I must have clicked through that menu a thousand times and still didn't see it.

Confirming, not a bug and closing the ticket.
