### ISSUE TITLE
Quality is showing for some furniture

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#259]
I noticed that some of the new pieces of furniture are showing their quality, much like how weapons and armor do. I'm assuming this is a bug since no other furniture does this, plus it just adds unnecessary clutter to the interface.

So far I've noticed it for pots and torch lamp and wall torch... I'm guessing it affects the rest of that medieval theme of items.

I poked around the XML, but wasn't sure how to fix this myself...

**Comment by skyarkhangel** [comment]
Yep, soon remove quality for container type buildings
