### ISSUE TITLE
Allow tool missing description

### ISSUE THREAD

**Issue by Masquerine** [skyarkhangel/Hardcore-SK#26]
Allow tool in the orders menu is missing a description, possibly the related file for it as I can't find where it would be located. Picture shows.
![allowtool](https://cloud.githubusercontent.com/assets/16396520/12437268/6d6e34c8-beea-11e5-821e-c48143b04fbd.png)

**Comment by skyarkhangel** [comment]
Soon fix

**Comment by Masquerine** [comment]
After solving the edb issue, I did some digging on this and figured it out. Silly really, but at least I know how it is fixable. : )
