### ISSUE TITLE
Проблема с дикарями.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2601]
Пришла дикарка. Пошёл приручать. Впала в ярость. Ранил и отнёс в тюрьму. После чего оказалось, что такую пленницу нельзя завербовать. Только игнорировать / выпустить / казнить.

**Comment by SomethingCrunchy** [comment]
Выпустить и приручить

**Comment by SetAriman** [comment]
Можно. Но это не отменяет того, что недоступны положеные игровые функции.
