### ISSUE TITLE
Новая болезнь?

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2605]
На второй игровой год слегка раненая пешка, лёжа в больнице, впала в "ступор". И вот уже несколько дней с ним ничего нельзя сделать, кроме как убить. Что не мешает ему стать пессимистом. И что теперь, до конца игры так и будет лежать на этой кровати? И, получается, даже со старта игры можно проиграть, потому что пешка возьмёт да и полностью отключится. Например в старте за одного.

**Comment by SetAriman** [comment]
Я написал здесь не для поиска решений, а для отчёта о возможном баге или недоработке.

**Comment by CabbageGovernor** [comment]
Та же проблема, 2 пешки впадали в ступор который длился минимум 10 дней, во время которого они становились пессимистами.

**Comment by bananasss00** [comment]
В master ветке устаревшая версия Experimental Optimizations. Проблема со ступором изза этого мода, в новой версии из development ветки это исправлено

**Comment by SetAriman** [comment]
Я про ветку разработки и писал.
