### ISSUE TITLE
naval turrent and other stuff

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#262]
welll first the naval turrent cant figure out what ammo it needs. they description talks about 35mm yet says it needs no ammo but when go ingame it says it needs armor perinceing explosive? i swear i spawned every type of ammo and couldnt figure it out.

also where does worktab go in load order?

right now if u click on the mod options and click fluffy relations it throws constant error.

**Comment by jnkyacc** [comment]
1) Bullet_30x173mm.
2) If you mean Fluffy tabs - try below RW_Manager

**Comment by skyarkhangel** [comment]
Yep, it need to update all descriptions for turrets with ammo info.
