### ISSUE TITLE
Сломаны залежи.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2628]
После какого-то из последних патчей прочность всех наземных залежей руды и камня стала 0.04-0.07%.

**Comment by AndreiAvinov** [comment]
Нужно обновиться до последней версии и загрузить сейв на котором всё было нормально - был баг в RockeMan который оперативно исправили

**Comment by SetAriman** [comment]
Спасибо. Блин, придётся начинать заново. ((
