### ISSUE TITLE
Kiln/Furnace 

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#263]
No designate power to stop them eating fuel constantly?

**Comment by sidfu** [comment]
toggle was removed and instead fuel coonsumption was reduced.

**Comment by zakhad** [comment]
Was this for immersion sake? because from a game play design its a a terrible idea, Because now I have to micromanage zones / doors to prevent them from eating all my fuel based resources. I always have someone hauling and they're one of the first priorities for a hauler to attempt compete.

**Comment by skyarkhangel** [comment]
Obselete, due to new refuel system.
