### ISSUE TITLE
сегфолтится при генерации мира из-за нового мода "gastronomy"

### ISSUE THREAD

**Issue by cut-up** [skyarkhangel/Hardcore-SK#2631]

**Comment by AndreiAvinov** [comment]
А можно как то поподробнее? Если стоит линукс, то нужен фикс для harmony. https://steamcommunity.com/sharedfiles/filedetails/?id=2149016328

**Comment by cut-up** [comment]
> А можно как то поподробнее? Если стоит линукс, то нужен фикс для harmony. https://steamcommunity.com/sharedfiles/filedetails/?id=2149016328

which: no glxinfo in (/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)
Set current directory to /mnt/sdc3/GOG Games/RimWorld/game
Found path: /mnt/sdc3/GOG Games/RimWorld/game/RimWorldLinux

**Comment by AndreiAvinov** [comment]
значит всё таки линукс - установи фикс и должно помочь

**Comment by cut-up** [comment]
здорово, хорошая идея... всякий раз буду так делать.
