### ISSUE TITLE
Баги или кривая установка?

### ISSUE THREAD

**Issue by kozachok3000** [skyarkhangel/Hardcore-SK#2636]
Сегодня обновил ветку dev и пешки перестали автоматически искать цель для стрельбы, а союзники-империя, призванные через привилегию, вместо помощи пытаются утащить что-то с базы. У меня одного так, или в обновления подвезли багов?

**Comment by bananasss00** [comment]
давно обновлялся? в последней версии дев ветки исправили баг с автострельбой
