### ISSUE TITLE
game crashing when world generated/game loaded with gastronomy

### ISSUE THREAD

**Issue by Flaczyna** [skyarkhangel/Hardcore-SK#2639]
Hello. I have following issue. my game is shutting down instantly when gastronomy mod is turned on. I am playing on ubuntu, tried Harmony Fix For Penguins. I am attaching the log
[Player.log](https://github.com/skyarkhangel/Hardcore-SK/files/5664162/Player.log)

**Comment by SanchozzDeponianin** [comment]
just a little test:
Ubuntu + Vanilla + Hugslib + Gastronomy installed from Steam Workshop = crash
Ubuntu + Vanilla + Harmony Fix For Penguins + Hugslib + Gastronomy = crash too
so it's not an HSK problem

**Comment by skyarkhangel** [comment]
check with last update. Commit: https://github.com/skyarkhangel/Hardcore-SK/pull/2644/commits/ca4f247f2dd69d39bdc92f90a15404b2e24e7f75

**Comment by Flaczyna** [comment]
Fixed. That was fast
