### ISSUE TITLE
Reverse Cooler tooltip wrong

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#264]
If you hover over the heating mode you get the tooltip "Click to start X." where X is the current setting. E.G. It says "Click to start Heating" when the cooler is already set at heating.

Tooltip should be "Click to start Y." where Y is the next setting.  E.G. Click to switch to auto mode when the cooler is currently set at heating mode.

**Comment by jnkyacc** [comment]
thx.
@skyarkhangel думаю правильней будет в исходниках поменять чем в Keyed

**Comment by skyarkhangel** [comment]
В исходниках нечего менять. Поправил в keyed.

**Comment by jnkyacc** [comment]
```
				command_Action4.icon = Building_ReverseCycleCooler.UI_TEMPERATURE_AUTO;
				command_Action4.defaultLabel = Translator.Translate("AutoLabel");
				command_Action4.defaultDesc = Translator.Translate("AutoDesc");
				command_Action4.activateSound = SoundDef.Named("Click");
				yield return command_Action4;
				command_Action4 = null;
и тд
```
Просто странным будет когда в кееде AutoLabel = Сooling, а кулинг это хитинг...

**Comment by skyarkhangel** [comment]
fixed
