### ISSUE TITLE
Странная первая миссия.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2648]
Начало игры. Получил первую миссию - зачистить бандитский лагерь с одним персонажем. С голой попой (персы почему-то не хотят носить стартовые комбинезоны, хотя они подходят по установкам) пошёл зачищать. Смеркалось... В лагере оказался бандит ... с крутейшими протезами, шмотом и штайром. Подкрался огородами, открыл шквальный огонь из-за угла - бандит меланхолично развернулся и ушёл в дом. Уклоняясь от 100% попаданий. Через какое-то время вышел из дома с любимым стулом в руках и свалил в закат. Точно так же уклоняясь от всех попаданий. Я остался в шоке. Баг? Фича?

**Comment by ArhinZi** [comment]
Не баг, а ФИЧА. Подумал Ну вас нафиг и решил пощадить голозадых аборигенов, проще уйти, чем разгребать потом гору трупов
