### ISSUE TITLE
Beauty of filled barrels and other containers

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#265]
Current beauty of barrels depends on it's contents. To be more precise: Barrels don't have beauty and the value of the tile is just the beauty of the items dumped into it. 

I don't think this makes much sense considering you don't see what's in the barrel unless you open it. Shouldn't it be a flat 0 Beauty?

**Comment by Vigilence** [comment]
A flat value, depending on the material used to produce the container would be cool.
