### ISSUE TITLE
Пустой метеорит.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2654]
Упал метеорит и появилось стандартное сообщение, что там можно собрать "серный кристалл." Однако место падения было пусто. Вероятно из-за низкой прочности материала.

**Comment by Pepelnica1488** [comment]
как и миграции которые НЕ ПРИХОДЯТ,как и андроиды которых суёшь в улучшалку А ОНИ ДОХНУТ ОТ ГОЛОДА БЛЯТЬ
