### ISSUE TITLE
Bug with containers while butchering.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#271]
I've not been noticing it first, but when colonist butcher something, it carries all amount of it's meat, even if it's over his capacity level - for example, capacity level in dark environment for unmodified human is 75, and one stack of meat is also 75, but butchering muffallo produces about 140-160 meat, so it'll carry all 160 meat at once. The problem here is that when he drops all of those meat into container , it transforms into only one stack of meat of 75, while all other meat simply disappears. I firstly been somewhat puzzled by the fact, that despite constantly hunting pack of muffalos, still was not getting enough food, only to realize in the end, that half of the meat been simply disappearing all that time. If you order to drop meat on floor though, or carry it to common storage - meat won't disappear.

**Comment by jnkyacc** [comment]
Use "Drop on floor" instead of "Take to best stockpile" until it will be resolved.
