### ISSUE TITLE
Wild grass prevents efficient tree farms

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#2715]
In vanilla, it was possible to establish a faraway tree farm, and it was really efficient: the pawns needed to walk there once in a few weeks, to sow a tree and to harvest it. In Hardcore-SK, wild grasses grow between trees, and pawns waste a lot of time on the trips to cut it, even when i never intended the plot to work as a grass farm and don't need those hilarious amounts of dirt cheap hay produced. The pawns or the plots can be micro-managed to avoid cutting grass, but can i just order them once, instead of managing a hundred of one-tile-sized farm plots?

**Comment by sidfu** [comment]
not a bug its just grass growing. put some flooring to prevent grass growing and your back to what you want. even terraform it into gravel does same thing
