### ISSUE TITLE
Снятые с врагов силовые щиты пропадают

### ISSUE THREAD

**Issue by ArhinZi** [skyarkhangel/Hardcore-SK#2719]
На врагах были одеты щиты. Я их подстрелил, назначил раздеть. Снялась одежда, но щиты пропали. Кто знает как возможно решить проблему?

**Comment by ArpoMo6** [comment]
Силовые щиты норбалов пропадают, обычные - нет. Насколько мне известно, так и было задумано.

**Comment by ArhinZi** [comment]
> Силовые щиты норбалов пропадают, обычные - нет. Насколько мне известно, так и было задумано.
Да, возможно то были норбалы
А в чем смысл? У них другие щиты или как?
