### ISSUE TITLE
(Agriculture) Research descriptions

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#272]
This seems to be all over the place.

Fruit Research II description includes Tomatoes, they only get unlocked with level 3.
Fruits Research III description does not include that it also enables Tomato Vine.
Orchards Cultivation II description does not include that it is a requirement for Grapes.
Flowers Cultivation I description does not include that it also enables Venus and Rosebay Flowers, 
Flowers Cultivation II description wrongly includes Rosebay Flowers (I) and Rose Flowers (III), but misses White Rose Flowers.
Flowers Cultivation III description misses Rose Flowers.
Medical Agriculture I is wrong. Only thing it enables is Healroot Plant which is not mentioned in the description.
Medical Agriculture III says it enables Xerigium (?!), what it really enables is hypericum, rose and mint in basins (should be the description of Medical Agriculture I).

Also it's very tedious to find out what exactly you need for what plant. I think every plant should have a "Required Research" field just like you have it for building (in the Help file).

**Comment by jnkyacc** [comment]
I believe, it will be updated after A15.

**Comment by skyarkhangel** [comment]
Soon fixed, thank you :)
