### ISSUE TITLE
Странный топор.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2738]
Топор вместо бонуса к рубке деревьев даёт бонус к посадке растений.

**Comment by AndreiAvinov** [comment]
В римке нет отдельного стата для рубки деревьев

**Comment by SetAriman** [comment]
Почитай описание ручного топора. И удивись.

**Comment by GuardianDll** [comment]
Кири не прав, в риме нет стата для рубки деревьев, но такой стат есть в survival tools.
Ты тоже не прав, хоть бы скрин скинул с багом :pekaallok:
![image](https://user-images.githubusercontent.com/67688115/105713174-179f3e80-5f1b-11eb-9a66-11b5b0d9a946.png)
