### ISSUE TITLE
skyai broke caravans and raids; cannot send my own caravan outside the colony 

### ISSUE THREAD

**Issue by alexanderguzhva** [skyarkhangel/Hardcore-SK#2740]
1. other factions caravan arrive to the map, travel to the entrance of the base and do nothing, finally starving to death. You can 'dismiss' a trader, but nothing happens. It is possible to trade with a trader.
2. raids get stuck near the entrance of the base. They do nothing and leave.
3. it is not possible to send my own caravan outside the base: you pick a destination, pick some items to grab, then the designated pawn collects the items and wanders around, never trying to leave the map.
4. this is 100% the effect of skyai. 

this problem is related to the 'development' branch, patch 0748a19f1c96479ca9672a2906477bf74535e896

i've attached a file.

[savegame.zip](https://github.com/skyarkhangel/Hardcore-SK/files/5864077/savegame.zip)

Thanks.

**Comment by AndreiAvinov** [comment]
Have you tried saving and reloading (it fixes pathfinding most of the time) or testing on new save?

**Comment by alexanderguzhva** [comment]
I did, multiple times.
2269693dd3d6d402522c77c916817ab90b391a93 still has the same issues. Also, passing friendly groups get stuck on the border of the map.

**Comment by zadumych** [comment]
Аналогичная проблема с караванами. Обновление не помогло.

**Comment by murmax** [comment]
У меня караваны работают, рейды тоже приходят. Ко мне не приходят чужие мирные караваны, но это из-за RimWar, так что винить в этом SkyAi я не могу.

**Comment by zakhad** [comment]
I've had this happen not related to a specific thing within the SkiAI as in it happened before SkyAI was a thing. 

Sometimes i have a map with bad pathfinding and i don't notice it until several hours of playing in that guests from hospitality can't pathfind there way out, same with traders sometimes raiders it's pretty rare with the latter though.

I will close this issue if it happens again on current builds then make a new issue.
