### ISSUE TITLE
pawns won't use melee weapons in melee if ranged is available

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#2742]
Save: 
[kwon.zip](https://github.com/skyarkhangel/Hardcore-SK/files/5872605/kwon.zip)

Glass has the electric baton manually equipped, but when cooldown ticks down, he will switch to rifle and bash the enemy with it instead.

**Comment by masakitenchi** [comment]
Should be fixed in https://github.com/CombatExtended-Continued/CombatExtended/pull/2451
