### ISSUE TITLE
backup power controller state is wrong on load

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#2745]
If backup power controller is in "off" mode when game is saved, when game is loaded it will not properly turn generators on again. Manual power switching is needed.

**Comment by AndreiAvinov** [comment]
The problem is between rimfeller and backup power mods. This bug appears only on rimfeller generators, right?

**Comment by Voker57** [comment]
> The problem is between rimfeller and backup power mods. This bug appears only on rimfeller generators, right?

didn't check others, probably.
