### ISSUE TITLE
Странное обрушение крыши.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2755]
![20210129214009_1](https://user-images.githubusercontent.com/47845929/106314572-f8861100-627a-11eb-9074-86d2cdb8a1cc.jpg)

И рушится постоянно, не давая построить карьер.

**Comment by AndreiAvinov** [comment]
Нет опоры рядом, ванильная механика же. 6 клеток держит, а седьмая падает

**Comment by Zim777** [comment]
Стены и камни по краям - теперь не опора?

**Comment by AndreiAvinov** [comment]
Они соединены крышей?

**Comment by SetAriman** [comment]
А вот это уже интересный вопрос. Слева и снизу - нет. Надо будет проверить. Я как-то не подумал, что крыша должна быть сплошной.
