### ISSUE TITLE
[Request] SK.Building_WorkTable_HeatPushAdvanced

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#276]
@skyarkhangel  Все что с этим классом не потребляет топливо.

___
~~Kiln и TableFurnace без кнопок, в свою очередь FueledSmithy с кнопкой, которая работает вполне нормально. Вкл - есть огонек и потребление, выкл - нет огонька и потребления. Честно говоря не вижу причины не добавить их к первым двум. Если причины есть, то убрать у смайти, но добавить всем кнопку форбид.~~

**Comment by Inei** [comment]
Там проблема в том, насколько я поняла, что когда выключаете, и нет огонька и потребления, всё равно можно работать.

**Comment by jnkyacc** [comment]
@Inei Понятно, пасиб.
