### ISSUE TITLE
Странные домашние животные.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2762]
К поселению периодически прибиваются животные, которые по идее не должны это делать. В этой партии сначала ко мне "прибился" терраморф. А сейчас - жук пожиратель. Их ещё и дрессировать можно. Это жежуки. о_О Ещё и интеллект - "средний". У жука?

**Comment by AndreiAvinov** [comment]
Терраморфы вполне валидные питомцы. С них ещё предполагалось состригать хитин, но что то пошло не так.
