### ISSUE TITLE
Возможно баг с отображением верстака.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2768]
![20210201130856_1](https://user-images.githubusercontent.com/47845929/106444525-ef6d8d80-648e-11eb-8e07-4669cb21e2e8.jpg)

**Comment by AndreiAvinov** [comment]
Это не баг, это у задней части верстака высокая панель такая

**Comment by SetAriman** [comment]
Покрутил - да. Но это не панель. как п
