### ISSUE TITLE
Ванильная графика

### ISSUE THREAD

**Issue by Ok23** [skyarkhangel/Hardcore-SK#2776]
Есть ли способ вернуть ванильную графику с текстурами ? У меня слабый комп и текстурки сильно бьют по производительности, да и стиль ванильный мне больше нравится

**Comment by ArpoMo6** [comment]
Большая часть текстур в паке весит раза в полтора-два меньше, чем в ваниле. Проблема производительности не в них.

**Comment by Ok23** [comment]
А разве игра не будет жаловаться на отсутствие файлов ? Или она просто стандартные подрузит ?

**Comment by ArpoMo6** [comment]
Если путь к текстуре полностью совпадает в ваниле и Core_SK, то текстура заменится на ванильную. В противном случае будет большой розовый квадрат

**Comment by Ok23** [comment]
Спасибо. Что еще может влиять на ФПС ?
