### ISSUE TITLE
Stockpiles and containers tuning.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#278]
Is there some way to make stockpiles, especially containers, storage nothing by default? Cause almost instantly, after being constructed it becomes filled with all kind of trash I don't need in there, and it's not easy to constantly oversee each storage building all the time. 
I remember there was a wonderful mod for that in v12, which made list of stockpiles empty by default.

**Comment by jnkyacc** [comment]
Agree. 
I suppose stockpile settings can be altered by mod only, and it will be confusing for new players "Why I cannot storage item_name? / Why my stockpiles not working?".

**Comment by trevize23** [comment]
Jep could be confusing, but I agree it would also be a nice addition. I guess only acceptable way would be a setting in Mod options if that is even doable. Probably easier to just run that mod manually if it exists.

**Comment by Inei** [comment]
In latest patch there was made a hotfix, that changed list of items for new containers to nothing, thankies alot for this.

**Comment by skyarkhangel** [comment]
ok. Closed.
