### ISSUE TITLE
Fluffy Relations Bug.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#280]
I am sure I've seen that bug somewhere around here, though, couldn't find, probably cause it was on forums, anyways - here's screenshot with error log.

When you push "Relations" button from panel - nothing happens, and that error message appears in the log.

http://i.imgur.com/K7VGlpb.jpg

**Comment by skyarkhangel** [comment]
All works fine. Mb, it was a temporary error.
