### ISSUE TITLE
Смерч почти не наносит ущерба

### ISSUE THREAD

**Issue by murmax** [skyarkhangel/Hardcore-SK#2803]
Слишком низкий урон смерча приводит к тому, что он даже деревья не разрушает, не говоря уже о постройках.

**Comment by SetAriman** [comment]
Как по мне, урон оптимален. Если его повысить, то первая же песчаная буря тупо разнесёт в хлам всю базу. И так железобетонные амбразуры и турели получают неплохой урон.
