### ISSUE TITLE
Добавить шаблоны ресурсов которые имеют надписи

### ISSUE THREAD

**Issue by shikulja** [skyarkhangel/Hardcore-SK#2810]
Для перевода ресурсов с надписями нужны шаблоны .psd
Чтобы наиболее идентично перевести надпись, с правильным параметрами шрифта\цвета\положения, а также без затирания фона

В основном это:
\Mods\Core_SK\Textures\Things
\Mods\SeedsPlease\Textures\Things\Item\Seeds

**Comment by GuardianDll** [comment]
Во первых, у нас нет исходников
Во вторых, у нас нет кода для реализации замены текстурок в зависимости от языка пользователя (и сделать его никто не сможет)
В третьих - это не нужно - текстуры обычно никто не разглядывают, разобрать, где кукуруза, а где ягоды, можно просто прикинув "на глаз", плюс вес текстурок увеличит время скачивания модпака - выхлоп невероятно маленький для того, чтобы этим кто-то занимался.
максимум можно сделать отдельный мод с заменой текстур, но сомневаюсь, что людям будет важно есть картошку, а не potato

**Comment by shikulja** [comment]
Ясно, будем пользоваться тем что есть.
