### ISSUE TITLE
Fueled workbenches - Fuel system broken

### ISSUE THREAD

**Issue by Monocer** [skyarkhangel/Hardcore-SK#2827]
Hello,

I have an issue where fueled workbenches (eg. Kiln, campfire) are not working. They show icon that says they dont have fuel. I cannot prioritize refueling them, and pawns wont auto refuel them, even though fuel filter is set correctly and several possible fuels are available in storage. Thus I cannot add bills and use them.

**Comment by AndreiAvinov** [comment]
Have you noticed new range setting? It works the same as in bills, you need to set a search radius for a fueled building

**Comment by Monocer** [comment]
I believe it was set to "infinite", but I will check...

**Comment by Monocer** [comment]
![image](https://user-images.githubusercontent.com/37194920/109397944-d9da6f00-7939-11eb-98fa-99cfba4c089e.png)

I cant seem to find the setting... see screenshot...

**Comment by AndreiAvinov** [comment]
uhhhhhh. what version do you have?

**Comment by AndreiAvinov** [comment]
And do you. by chance, have Prison Labor mod turned on? (it breaks fueling system)

**Comment by Monocer** [comment]
Yes I have Prison Labor, thanks! Is there a patch?

**Comment by AndreiAvinov** [comment]
no, it doesn't work, use other mods, for example Simple Slavery

**Comment by Monocer** [comment]
All right, thanks!
