### ISSUE TITLE
Unfertilized eggs can't be used for making kibble.

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#284]
I have plenty of eggs and potato's, but the eggs are not being used for making kibble.  They are not forbidden and they are right next to the butcher table.  

Eggs are selected as one of the ingredients in the kibble.  I have tried just allowing eggs and potato's, and eggs and vegetables but nothing is being made.

Aside from being used in kibble (not working atm) what other uses are eggs for?  I don't see any recipes for them.

![screenshot 73](https://cloud.githubusercontent.com/assets/16742086/18421604/2f6757aa-785c-11e6-9eb3-31b26d0fa622.png)
![screenshot 72](https://cloud.githubusercontent.com/assets/16742086/18421606/2f6d6db6-785c-11e6-945d-d4fbaad9392f.png)
![screenshot 71](https://cloud.githubusercontent.com/assets/16742086/18421605/2f69ba04-785c-11e6-8870-0e894767b3f6.png)
![screenshot 74](https://cloud.githubusercontent.com/assets/16742086/18421621/6f00cd24-785c-11e6-922a-5c5fe648a4b3.png)

**Comment by trevize23** [comment]
There needs to be more options on how to handle unfertilized eggs. Once you get chickens you'll have a ton of eggs and eating raw food is not optimal. 

The egg description also makes it kinda confusing: "Unfertilized chicken egg. It can be eaten raw, but it's much, much better cooked." It can not be cooked ingame. I suggest adding a recipe for cooked eggs.

The only viable option I found was making compost with the eggs.

**Comment by Vigilence** [comment]
Agreed.  With potato's and eggs that can be a meal right there.  Hopefully, they add egg recipes as well as fish recipes.
