### ISSUE TITLE
New refuel system

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#285]
Во! С этого и надо было начинать :) 
А теперь о погоде... 
1)
```
Exception in SetupToils (pawn=Vince, job=RefuelBurner A=Thing_WoodLog7966 B=Thing_Campfire8020): System.NullReferenceException: Object reference not set to an instance of an object
  at SK.JobDriver_RefuelBurner.FindFuelToGather () [0x00000] in <filename unknown>:0 
  at SK.JobDriver_RefuelBurner+<MakeNewToils>d__3.MoveNext () [0x00000] in <filename unknown>:0 
  at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0 
```
грузит намертво + вылет.
2) Неплохо бы иметь принудительную ~~загрузку~~ заправку через правую кнопку.
3) Максимум на 90 ед можно заправить. Больше не хотят...
upd/
Уголь осознано убрали со столов для готовки? Как на леднике готовить?

**Comment by Inei** [comment]
Проблема всё ещё остаётся. Игра вроде не зависает после одного из последних апдейтов, но топливо всё ещё загружаться не хочет ни в какую. Когда говоришь им хворост загружать, они просто стоят, и появляется красная надпись в логе, а если дрова - они их берут в руки, и тут же кидают на землю. Играть дальше невозможно, поскольку еду добывать без костра возможности нет.

**Comment by Inei** [comment]
Скриншоты с ошибкой.

http://imgur.com/a/V6vMg

**Comment by skyarkhangel** [comment]
с последним апдейтом проверьте

**Comment by skyarkhangel** [comment]
можно не начинать новую игру.

**Comment by jnkyacc** [comment]
Очень странно ведут себя. Ходит-ходит-ходит-пойдет заправит и опять ходит, при этом у него штук 8 не заправленых стоят. Опять же нельзя принудиловкой отправить заправлять. Ошибок пока не вылезало.

**Comment by Inei** [comment]
Со старым сохранением не работает - выдаёт ту же ошибку. Начала новую игру, через девтулс проверила - вроде пока порядок, но до 300 не загружает, максимальный размер определяется размером пачки, которую может нести колонист.

**Comment by skyarkhangel** [comment]
jnkyacc это без последнего апдейта? Как раз одно из изменений в коде работы было связано с ограничением макс, кол-ва поселенцев занимать работу.

**Comment by jnkyacc** [comment]
Последний апдейт. Новая карта и мир.

**Comment by skyarkhangel** [comment]
Гм. ок... сейчас попробуем немного изменить.

**Comment by jnkyacc** [comment]
@skyarkhangel они палки не могут поделить. а когда дворф несет палки то ИД палок которые он несет не обнавляется(одинаковый ИД в руках\инвентаре и куче из которой их берут) и второй пытается ети же палки зарезервировать на себя. вот тут примерно что то похожее https://github.com/skyarkhangel/Hardcore-SK/issues/206

**Comment by skyarkhangel** [comment]
Выпустил еще один апдейт. Строил десяток электростанций, спавнил пару десятков колонистов. тонны ресурсов для заправки. Было без ошибок

**Comment by jnkyacc** [comment]
![screenshot46](https://cloud.githubusercontent.com/assets/20729235/18473141/baf62ba6-79bb-11e6-82cd-97c520ab6885.png)
![screenshot47](https://cloud.githubusercontent.com/assets/20729235/18473148/c2c7d51e-79bb-11e6-92b2-600a8f9a46d5.png)
Еще заметил что у заправленых столов один фиг висят "капельки что не заправлено".

**Comment by Inei** [comment]
Проблема с заправкой к сожалению осталась. Но, если разрешить заправку всем подряд - без проблем будет заправлять дровами, но вот при попытке заправить опилками - игра снова виснет.

**Comment by Inei** [comment]
Мне кажется там проблема именно с опилками в чём-то. Просто дровами заправляет вообще без проблем. Кроме того, когда я поставила галочку "manufactured" в разделе где kindling - колонист вообще попытался досками заправить, хотя их в с писке даже нет.

**Comment by Inei** [comment]
Помимо прочего не сохраняется загруженное топливо - которое просто пропадает и настройки толпива при загрузке игры.

**Comment by jnkyacc** [comment]
@Inei попробуй только электростанции через девмод. 
Тут скорей проблема с классом столов.

**Comment by Inei** [comment]
http://imgur.com/a/tGpY0 

Выдаёт всё те же три ошибки. Это новая игра, с последним апдейтом, если что.

**Comment by Inei** [comment]
Проверила с электростанциями через дев-тулс - та же самая проблема, причём если дать побочное задание, не связаное с переноской топлива для неё сначала, колонист потом сам потом без проблем загружает топливо. В общем я уже ничего не понимаю.

P. S. А у меня одной такая проблема что ли сейчас?

**Comment by Inei** [comment]
Вот скриншоты - но там ошибка одна и та же по сути везде. 
http://imgur.com/a/iGjAc

Может это из-за подключенной психологии?

**Comment by WaytobeGlad** [comment]
Аналогично.
[http://imgur.com/a/pJpeF](url)

**Comment by skyarkhangel** [comment]
http://image.prntscr.com/image/d377564a171849149d32977bace87a48.png
Починил процесс заправки. Поселенцы не могли заполнять несколько раз.

**Comment by skyarkhangel** [comment]
Fixed.

**Comment by Inei** [comment]
Боюсь не помогло, к сожалению.

На тесте через девтулс просто - всё вроде работает правильно, но вот как сама строю, на первый-второй день развития колонии - опять то же самое. Хотя теперь уже только две ошибки, вместо трёх.

http://imgur.com/a/eHmGV

**Comment by Inei** [comment]
Что интересно, если включить опилки и дрова одновременно, без проблем загружает то, что ближе находится.

**Comment by Inei** [comment]
А ещё сохранения перестали работать почему-то.

http://imgur.com/a/AeDiR

**Comment by jnkyacc** [comment]
> И найдена ошибка. Она происходит когда станция заполнена одним топливом, которого не хватает до требуемой шкалы и есть другой тип топлива подходящий для этой станции. Поселенец пытается дозаполнить станцию другим типом и возникает выше описанная ошибка. Ищу способ пофиксить :) Поэтому, до фикса, выставляйте один тип топлива для работы.

Хм, но я всегда выставлял только один тип...

**Comment by Inei** [comment]
Не знаю баг ли это, но при разборке костра с топливом внутри, пропадает топливо, и камни из которых костёр был собран не остаются тоже.

**Comment by Inei** [comment]
Кстати, костры топится соглашаются исключительно брёвнами, хворост туда не лезет ни в какую, один раз как то удалось после десяти минут шаманства с бубном запихнуть пачку хвороста в костёр, но повторить в дальнейшем не получилось, ну хоть с дровами вроде проблем особых нет, и то ладно.

**Comment by skyarkhangel** [comment]
обновлено вторым фиксом. проверяйте.

**Comment by Sabikk** [comment]
Сейчас проверим...

**Comment by jnkyacc** [comment]
@skyarkhangel Стало очень лучше :)
Но снова о погоде :Р
1) Refuel at 100%
Дворф напихивает максимум, а потом идет еще за "0шт" "дровиной", которая потом превращается в "1шт" и пихает её туда, результат ниже.
![screenshot57](https://cloud.githubusercontent.com/assets/20729235/18594856/4179cf9c-7c42-11e6-8cbd-74ce9e6bb93c.png)
2) Slider "Refuel at *%"
Незнаю какая была задумка, но это работает как ограничитель максимального количества. (чуть не точно т.к носят стаками которые могут утащить)

to be continue...

**Comment by Sabikk** [comment]
И не запоминает сколько топлива при перезапуске...

**Comment by jnkyacc** [comment]
@Sabikk refueling считается как hauling

**Comment by jnkyacc** [comment]
По поводу 
> 5) 10 jobs in 10 tick

https://github.com/skyarkhangel/Hardcore-SK/issues/317

**Comment by skyarkhangel** [comment]
Дауж, баг на баге. Делаю одно, ломается другое :/ Про сохранение значений топлива молчу.. пока не понимаю почему Рим не хочет считывать данные из сейва, хотя туда их пишет.

**Comment by skyarkhangel** [comment]
Версия 3 готова. Сейв-лоад пока не сделан. По умолчанию значение заправки выставлено в 20%

**Comment by Sabikk** [comment]
А может выставить приоритет заправки станций по умолчанию на первое место из всей переноски. Флафи табс конечно прикольно, но я думаю единицы разобрались как и что настроить, все остальные теперь играют без энергии походу. Бал бы старый мод приоритетов там это все гораздо быстрее решается....

Вообщем пока не играбельно это ...

**Comment by Inei** [comment]
А у меня вроде в первую очередь заправляют.

**Comment by Sabikk** [comment]
Ну может у меня как то иначе все играется... просто постоянно на карте есть что переносить... так вот они переносят все а потом только бегут к электростанции. Только вот заметил что если только построилась новая станция они сразу побежали заправили - а на второй раз уже только если все переделали...

**Comment by jnkyacc** [comment]
1) Refuel at 100% - fixed
5) 10 jobs in 10 tick - вроде бы тоже фиксед
6) Поиск "дров" - fixed



to be continue...

**Comment by skyarkhangel** [comment]
Сохранение данных при загрузке реализовано.

**Comment by jnkyacc** [comment]
Настройки не сохраняет.

**Comment by skyarkhangel** [comment]
А это уже попозже, главное что ресурсы смогли сделать.

**Comment by skyarkhangel** [comment]
Обновил. Теперь сохраняет все настройки.

**Comment by skyarkhangel** [comment]
попробуй вставить в фильтр ветку дефаулт ресурсов

**Comment by jnkyacc** [comment]
> попробуй вставить в фильтр ветку дефаулт ресурсов. Фильтр работает как в ванильке.

Нипалучааитца. В ваниле же дефолт фильтра для топлива и небыло вроде как. Сам фуелфильтр идет как фиксед ингридиенты, а дефолт ингридиенты туда вставить низя.

> При значении перезаполнить при 0% происходит разовое заполнение. Сделаю так чтобы при 0% было игнорирование задачи.
 
Может его переделать как оно задумывалось? Сейчас это просто ограничитель макс кол-ва. Я так понимаю он должен работать как хистерезиз, когда у тебя заполняется полностью, а рефуел происходит до полного на этом значении. С таким обьемом как сейчас мелкие станки заполняются на месяца 2+, что практически вечность для них.

Принудиловку еще через правую кнопку, что бы всех сделать счастливыми :)

**Comment by skyarkhangel** [comment]
О спасибо, классная вещь!

**Comment by skyarkhangel** [comment]
Закрываю. При новых проблемах создайте новый тикет.
