### ISSUE TITLE
Lord for Ancients tried to add x whom it already controls.

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#2852]
The message is spammed continously after ancient vault got opened by earthquake

save & log:
[save.zip](https://github.com/skyarkhangel/Hardcore-SK/files/6142810/save.zip)

**Comment by agentofzog2** [comment]
I have the same problem, happened after a raid by an unrelated faction. Using the pawn cleanup tool seems to have stopped it.
