### ISSUE TITLE
refugees always arrive naked and it's very difficult to get them dressed

### ISSUE THREAD

**Issue by Voker57** [skyarkhangel/Hardcore-SK#2856]
Outfits are disabled, and only way is to force wear an item and for some reason option for it is not always there

**Comment by zakhad** [comment]
They're not permanent colonists and the issues we had which brought around this was with people stripping royalty dlc temporary pawns with high level gear/guns i,e mercenaries with power armours and automatic rifles unbalancing the game so any royalty dlc pawns wise has there inventory locked for the most part.

So when you get these temp pawns from a quests i,e refugee's the can't tell if they're merc's or refuge's so they get inventory locked; the only thing you can do is force equip them, i'm not sure if this will ever be resolved tbh.

**Comment by Voker57** [comment]
Force equip also works only on some of them.

Easiest solution is to ensure they have some kind of pants at least I guess :-)

**Comment by zakhad** [comment]
I don't think you can change any equipment they already have is that what you're implying, as that's intended? i,e changing the loin cloth to idk striped pants because they spawned with it, it can't be changed unless unconscious.
