### ISSUE TITLE
Misc Incidents - Updated?

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#291]
Does anyone know if Misc incidents is updated and patched?  I don't want to send my pawns on a mission or treasure hunt and not have them come back.  Happened to me a few days ago and it's not a good experience.

**Comment by Inei** [comment]
I've sent them three times in last few patches, they returned only once so far, so, it's up to you.

**Comment by Vigilence** [comment]
I know there is a patch released by the author, I am just wondering if that will be included.

**Comment by zakhad** [comment]
I keep manually updating I check every few days on the about for the version number of the hardcore sk of misc and its still Version: 0.14.5 not Version: 0.14.6

**Comment by jnkyacc** [comment]
Do you have patch for A14? Forum version updated to A15...

**Comment by Vigilence** [comment]
There is two possible fixes, the update to a15 might fix the issue, but he also released a patch. 

https://ludeon.com/forums/index.php?topic=3612.msg262831;topicseen#msg262831

https://ludeon.com/forums/index.php?topic=3612.msg262787;topicseen#msg262787

Download patch [here](https://www.sendspace.com/file/1ohbyq).

**Comment by jnkyacc** [comment]
> Download patch here.

Its "Misc_Patch_-_EdBPrepareCarefully_0141". How PC affecting on "Misc Inidents", just wondering?
Updating to A15 not possible due CCL not yet updated to A15.

**Comment by Vigilence** [comment]
The update in the script is supposed to allow your pawns to return from adventures and other events that require them to leave the map.

**Comment by Vigilence** [comment]
Misc_incidents here is 14.5 - Latest one is [14.6](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=1000)

Miscellaneous_MapGenerator here is 14.5 - Latest one is [14.6](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=1009)

Miscellaneous_Robots here is 14.3 - Latest one is [14.5](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=966) 

Miscellaneous_Robots_Xtension here is 14.1 - Latest one is [14.5 ](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=967)

Miscellaneous_TrainingFacility here is 14.1 - Latest one is [14.5 ](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=968)

[Patch](http://www.nexusmods.com/rimworld/ajax/downloadfile?id=933) for Miscellaneous and EdB's PrepareCarefully

These are the latest updates prior to a15

**Comment by jnkyacc** [comment]
thx. will try tomorrow

**Comment by Vigilence** [comment]
Np, glad to help.

**Comment by zakhad** [comment]
This was such an easy update as to why it took so long :/ - thanks for updating it.

**Comment by Vigilence** [comment]
Maybe it went under the radar.  If I knew how to use Github I would have updated it myself.

**Comment by jnkyacc** [comment]
Aaand probably will crush the game. :) Most side mods made to comply with vanilla stuff and to be compatible with most other side mods. HK using allot of custom resources, races, weapons system, now fueling system, map generation things. So if you will install mod, most simple example for some cool steel walls and will try to play it together with HK, it will cost you iron ore to build instead of steel bars. It takes time to convert each mod like that to HK-friendly.

**Comment by Vigilence** [comment]
I wouldn't mind having a wiki showing how we can convert mods for HK.

**Comment by jnkyacc** [comment]
> having a wiki

The most impossible thing on this planet :laughing: 
It would be like that http://sethgodin.typepad.com/.a/6a00d83451b31569e2019aff29b7cd970c-popup

**Comment by Vigilence** [comment]
lol I'm sure it can be done eventually :)   I wouldn't mind contributing as well instead of just opening issues.

**Comment by skyarkhangel** [comment]
Closed
