### ISSUE TITLE
Пассивная охрана тераформеров.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2929]
Упал терафомер, высадилась охрана и ... вся паника на моей базе была зря. Всю охрану преспокойно перестрелял один мой снайпер. Ни кто даже не попробовал сагриться на получаемый урон. Если обломки кораблей механоиды действительно охраняют, атакуя нарушителей, то здесь тупо мишени.

**Comment by Westus** [comment]
Такая-же проблема. 4 охранника были полностью пассивны.

**Comment by zaripovk** [comment]
Еще и из карманов патроны выпали.
