### ISSUE TITLE
Баг у нового биочана.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2930]
После выхода из игры и загрузки ,чан стал выглядеть вот так.
![20210428163502_1](https://user-images.githubusercontent.com/47845929/116413121-01698d00-a840-11eb-99d0-e6cf5a64704c.jpg)

Помимо этого, пуста информация о том, что он что-то содержит. Хотя там должна быть одна единица биоматерии.

**Comment by qwerty19106** [comment]
Должно быть  пофикшено в:
https://github.com/skyarkhangel/Hardcore-SK/pull/2933
https://github.com/skyarkhangel/Hardcore-SK/pull/2932

Обновите HSK и проверьте еще раз. Возможно придется пересоздать биочан.

**Comment by SetAriman** [comment]
После пересоздания - работает. И радует сообщением: "В процессе (2/штукы)". :)
P.S. Напомнило. 
"Вмири зказок тожи люби булочкы. Гнум." ))
