### ISSUE TITLE
Перестала работать функция "поиск объектов".

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2931]
Иконка на экране на месте, но при нажатии ничего не происходит.

**Comment by Zim777** [comment]
достаточно перезагрузить сейв или игру и все начинает работать снова
Внимательно посмотрите в консоль - возможно там есть красные ошибки - киньте скриншот и лог

**Comment by SetAriman** [comment]
В том и вопрос, перезагрузки не помогают.

![20210428201616_1](https://user-images.githubusercontent.com/47845929/116445784-ec502680-a85e-11eb-8e05-d9a06af82f55.jpg)
![20210428201625_1](https://user-images.githubusercontent.com/47845929/116445793-ef4b1700-a85e-11eb-9381-4694102d1106.jpg)
![20210428201642_1](https://user-images.githubusercontent.com/47845929/116445800-f114da80-a85e-11eb-9ca7-fe79378a20b0.jpg)

**Comment by Zim777** [comment]
Ну это ошибки после последнего обновления ферменторов

**Comment by SetAriman** [comment]
Больше красных нет.

**Comment by qwerty19106** [comment]
Исправил в https://github.com/skyarkhangel/Hardcore-SK/pull/2934.
Можете обновиться и подтвердить, что все работает?

**Comment by SetAriman** [comment]
Обновился. Не работает. Сразу после загрузки, даже не нажимая на кнопку, теперь бесконечно спамит сообщение:
Exception drawing TableOrganvat8565951: System.NullReferenceException: Object reference not set to an instance of an object
  at UniversalFermenter.CompUniversalFermenter.PostDraw () [0x0014a] in <627cabc292674bd4abf2414c40dec241>:0 
  at Verse.ThingWithComps.Comps_PostDraw () [0x00018] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Building.Draw () [0x00015] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at SK.Building_WorkTableGraphicOn.Draw () [0x00000] in <f70bf5272bca4bf9bb39156353dfbc12>:0 
  at UniversalFermenter.Building_UF.Draw () [0x00001] in <627cabc292674bd4abf2414c40dec241>:0 
  at Verse.DynamicDrawManager.DrawDynamicThings () [0x000d8] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Verse.Log.Error_Patch1(String, Boolean)
Verse.DynamicDrawManager:DrawDynamicThings()
Verse.Map:Verse.Map.MapUpdate_Patch2(Map)
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

Версия сборки от 6 утра этого дня.

**Comment by SetAriman** [comment]
Заменил биочан - теперь всё работает.
