### ISSUE TITLE
Недоработка биочана.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2936]
Нельзя поставить пешку на полное заполнение. Если в том же крематории я могу дать команду дроиду сжигать трупы - он какое-то время будет это делать, чтобы пешки не портили себе мораль. (Но не полностью.) В биочане же при отдаче команды и при наличии свободного места, один труп загружают и задача сбрасывается.

**Comment by qwerty19106** [comment]
Только что проверил биочан во всех 3 режимах: Сделать Х штук, повторять до Х штук, делать бесконечно.
Закидываю 6 огров подряд, полет нормальный.
Можете записать видео, если ошибка воспроизводится на свежей сборке?

**Comment by SetAriman** [comment]
Это не скоро. ((

**Comment by qwerty19106** [comment]
Тогда просто условия, при которых воспроизводится ошибка.
Или может быть сейв на чистом HSK, без доп модов.

**Comment by SetAriman** [comment]
https://dropmefiles.com/vLJ7N

Только что проверил, со свежими апдейтами на чистом ХСК. В биочане 5 мест свободно. Ставлю задачу перерабатывать пешке. Пешка один или два трупа приносит и переключается на другие задачи. Загружаюсь, ставлю задачу боевому дроиду. Он приносит один труп и тоже переключается на другую работу. В то же время подобную задачу в крематории дроид делает довольно долго, до переключения.
