### ISSUE TITLE
Pawns don´t shoot

### ISSUE THREAD

**Issue by Divinidas** [skyarkhangel/Hardcore-SK#2937]
My pawns only shoot if there is just one opponent. 
https://www.reddit.com/r/RimWorld/comments/n0mds5/why_do_they_not_shoot_mod_rimworld_hsk_all_fully/
There is the Video.
can someone help me pls?

**Comment by Divinidas** [comment]
i start the HSK mod with the launcher!

**Comment by Zim777** [comment]
Remove personal shield from you pawns

**Comment by Divinidas** [comment]
they have no shields. Just one! and why can they shoot against one and not against more opponents?

**Comment by Zim777** [comment]
![image](https://user-images.githubusercontent.com/46481732/116548124-71d5e400-a8fc-11eb-93f5-7ade1d07450f.png)

**Comment by Divinidas** [comment]
hmmmm ok i try it

**Comment by Divinidas** [comment]
ok that is the solution! thx!
