### ISSUE TITLE
мб занерфить пироги?

### ISSUE THREAD

**Issue by alexanderguzhva** [skyarkhangel/Hardcore-SK#2948]
На сложных уровнях игры становится очень выгодно кормить колонистов только и исключительно пирогами, потому что 2 подряд съеденных пирога дают +15 к настроению, а само производство пирогов предельно тривиально и незатратно, в отличие от lavish и luxury meal-ов

мб занерфить пироги?

**Comment by Zim777** [comment]
Пироги не дают бафов к различным параметрам пешек. только к настроению.
Плюс фрукты надо выращивать, плюс зерновые, плюс полоть зерновые.

**Comment by alexanderguzhva** [comment]
Мне кажется, что настроение ВСЕХ пешек - многократно более критично и важно, чем любые бафы.

**Comment by SomethingCrunchy** [comment]
добавить в рецепт мёд

**Comment by Zim777** [comment]
А мне не кажется.. у меня проблем с настроением нету в колониях.

**Comment by AndreiAvinov** [comment]
Вообще так не планировалось, наверное забыл старые строчки из xml убрать. Я обмозгую ещё, но скорее всего просто уберу возможность стакать бафы от еды (за исключением буквально пары штук)

**Comment by SetAriman** [comment]
Кому что выгодно. Я кормлю булочками, дающими +10% скорости и бафф от хорошей пищи к настроению. Требуется всего лишь кукуруза для обоих видов муки (что, по идее, недоработка мода) и тростник для сахара. (Ну и пельмешки, да.)
