### ISSUE TITLE
Нарктаун

### ISSUE THREAD

**Issue by cross228tu** [skyarkhangel/Hardcore-SK#2957]
Нарктаун-описание идеи для римворлд хск от игрока муомяумио(санёк).

Оглавление:
•	Вступление
•	Новые события
•	Общие правки
•	Описание событий с точки зрения игрока
•	Механика событий
•	Награды и штрафы

Вступление: 
Данная идея появилась так как сообществу интересна тема наркотиков в римворлд. Игрокам интересно на начальном этапе отыгрывать изготовление и продажу наркотиков, будь то косяки, психолисты или другое. 
Суть данной идеи заключается в том, что появятся новые события и варианты выбора между плохим/хорошим/нейтральным. Часть событий будет за пределами поселения, что заставит игрока также выбирать-либо тащить караван в даль, либо нет, но остаться без награды.
Игрок может качать репутацию пиратов и аборигенов поставляя на «рынок» наркотики, либо качать репутацию с «цивилизацией», уничтожая наркотики и поставляя «хорошие» препараты.

Новые события:

Договор на поставку: Фракция предлагает игроку поставлять какой-либо препарат в каком-либо объеме в обмен на репутацию и серебро. 
Обнаружен лагерь- «Полицией » фракции обнаружен лагерь другой фракции. Есть информация, что в данном лагере производят и/или хранят наркотики, необходимо разобраться.

Вымогательство/принуждение к сотрудничеству: к поселению прибывает рейд хорошо вооруженных пешек и выдвигает требования: в срок 2-3 дня необходимо передать им серебро, золото, наркотик или препараты на определенную сумму. В случае невыполнения требований-вызов подкрепления и атака/осада.

Общие правки:
Для данного события на мой взгляд необходимо изменить репутацию. В текущем варианте она качается и падает слишком быстро. Текущие значения получения-потери репутации необходимо балансировать, как вариант- в 2 раза(за крупную сделку получаем не 6, а 12, если сдох кот в караване-теряем меньше). Также за долгое время мы будем терять репутацию столько же, но за больший промежуток времени. Переговоры приносят не 75 репутации в случае триумфа, а 50(нельзя заключить союз с фракцией всего за 1 переговоры, это нелогично). Игрок должен чувствовать, что за репутацию необходимо "поработать".
Лагеря в новых событиях должны размещаться далеко от поселения, минимум в 15 клетках. Иначе для игрока не будет представлять сложности «ходить по карте». 
Повысить вероятность нападения на караван в случае если сумма товаров в караване больше «потолка» в пересчете на одну пешку, но не более 2 нападений за каждые 20 клеток пройденного пути. Например, «потолок» 500. В караване 3 пешки и слон с товаром. Не считая брони-оружия на пешке на слоне товара на 2000. А также сами пешки несут товара еще на 1000. Итого 3 пешки потолок 1500, ценность товара 3000, следовательно на 20 клеток пути этого каравана на него нападут один раз силой 1500(3 вражеские пешки того же технологического уровня), либо 2 раза по 1000 и 500. Еда также входит в ценность каравана при подсчете. Как только караван прошел 20 клеток, формула считается заново и создаются новые нападения.

Для работы некоторых событий нужно будет создать фоновые нейтральные фракции, которые не будут нигде светится в мире(курьеры, послы)
Условно вещества следует разделить на «препараты» , «наркотики» и «морально-серые»
Препараты:
Активированный уголь , безопасный антидот, бустер фертильности, ибупрофен, йодид калия, антибиотики, лечебная настойка из грибов и трав метадон пеноксицилин, противозачаточные, тест на беременность
Наркотики: берсерк херб, го-сок, люциферий, психин порошок и чай, сигара и сигарета бодрин (безвредный аналог-чашка кофе)
Морально-серые: амброзия, весь алкоголь, ириска, карамель, косяк дымолиста(безопасен, несмотря на запрет в ряде стран мира), простой антидот, фруктовый напиток чайный напиток чашка кофе.

Фракции тоже условно следует разделить на «наркотические», «чистые», «серые» и «нейтральные».

Наркотические фракции покупают наркотики, воюют с чистыми. Нейтральные никак не участвуют в этом.
Наркотические: все пираты, нова, норбалы, а также уровня развития неолит, средневековье.
Чистые: империя, а также уровень развития космический, ультра.
Серые: фелины, раткины, а также уровня развития индустриал.
Нейтральные: азари, андроиды

Описание с точки зрения игрока:
После завершения события «переговоры» Наше отношение с фракцией стало выше 0. Поступает задание «поставка». Фракция заинтересована в торговле с нами и после принятия задания через некоторое время(день-два) прилетает челнок и из него выходит гость-торговец. У него при себе некоторое количество серебра и/или золота, которое он должен обменять на определенный «морально-серый». Однако долго он ждать не будет и улетит, а отношения ухудшатся. Аналогично, если игрок не продаст весь объем товара по заданию.

При завершении мы получаем репутацию, тк награду мы получили во время торговли. Отдали товар получили валюту.
Ну или этот же курьер может прийти и по земле как торговый караван вместе с парой вьючных зверей.
Если отношение с фракцией 50 и выше фракция попросит «наркотик», а за выполнение задания сверху еще положена награда.

После завершения первого задания поставки «морально-серого» с нами связываются блюстители закона и порядка империи. Вас вводят в курс дела, что империей и еще несколькими развитыми фракциями заключен договор, в результате чего запрещены потенциально опасные для здоровья препараты. Вам предлагают сдать имеющиеся «наркотики» в обмен на репутацию и серебро, но по заниженному курсу. Отдаем много, получаем мало. Для успешного выполнения задания необходимо «продать» хотя бы 1 единицу товара.
После этого спустя 1-2 сезона нам может упасть задание от империи или «чистой» фракции. Обнаружен лагерь на расстоянии 15+ клеток от поселения. Имеется информация, что в лагере имеются наркотики. Лагерь должен быть уничтожен. Однако что делать с наркотой, забрать с собой или бросить и по сути уничтожить. В награду за лагерь получаем денежную награду и репутацию.

Если у игрока на складе имеются наркотики, репутация с чистыми падает по 10 за каждые 15 дней.
Пираты не любят, если игрок в хороших отношениях с чистыми(выше 20), репутация с пиратами в таком случае будет падать.
Если отношение чистых к вам выше 50, станет доступно задание на поставку препаратов. Аналогично поставке наркотиков. 
При должном уровне отношений для торговли чистым можно продавать препарат и морально серое, наркотическим можно продавать всё, серым можно продавать все, но не за полную цену. Нейтральные покупают только морально-серое.

Если на складе игрока есть наркотики и он во врагах с «наркотическими» приходит рейд. Игроку ставится ультиматум, где он должен сделать выбор подвергнутся нападению или отдать бОльшую часть наркотиков в обмен на репутацию. Если игрок выбирает нападение, от края карты появляется еще 1-2 отряда аналогичной силы что и первоначальный.
Если на складе наркотики и он друг наркотических, приходит хорошо вооруженный  рейд и требует отдать все наркотики колонии бесплатно, иначе нападение. В этом случае к первичному отряду добавляется 1-2 также хорошо вооруженных отряда, но десантируются прям на поселение.
Поскольку игрок начинает игру с империей 0 репутации, то после завершения квеста на поставку морально серого необходимо отнять немного репутации с империей.
Таким образом, если игрок пытается "балансировать" на репутации, у него будут отбирать наркотики ультиматумами, а торговать он будет морально-серым. 

События на ультиматум необходимо повторять не чаще раза в год.
С повышением стоимости колонии повышается сила рейдов и вооружение. При этом пешки «чистых» должны быть экипированы посмертным растворителем, иначе обуз. Объемы товара повышаться не должны, тк игрок может и не ставить основной целью выращивать огромные плантации.

Механика:
Для того, чтобы все это работало именно в наркополитике, необходимо будет создать 2 скрытых фракции(или 2 новых значения), которые никогда не появятся на карте но будут учитываться для этих квестов. А именно наркотические и чистые.
Как вариант, некоторые нарколагеря могут быть сгенерены внутри холмов. Снаружи это будет выглядеть как обычный холм и Чтобы уничтожить лагерь, необходимо копнуть. Причем тригером должно являться: 1. Вывод из строя охраны 2. Найти ВСЕ помещения с наркотой, будь то плантация на улице, либо склад.
Если на складах поселения нет наркотиков-данные квесты не появляются, а также если наркотики в малых объемах на складах.
Если на складах поселения нет препаратов-только задания на поставку препаратов и/или морально-серого(зависит от репутации), а также если препараты в малых объемах на складах.

Награды и штрафы
За первоначальную сдачу наркотиков чистым сразу получаем +20-30 репутации.
За ультиматумы получаем репутацию в зависимости от объемов отданного как, как за подарки.

**Comment by shikulja** [comment]
Не особо. Но за оказание гостям\заключенным мед помощи, в том числе и имплантов, никакой награды или репы.
Причем снижение репы если менять импланты заключенным даже наоборот её ухудшает, даже если имплант лучше.
Обидно, хоть я это и делаю только чтобы скилл медицины поднимать.

**Comment by cross228tu** [comment]
Про импланты у меня также есть идея, которую я опишу ближайшее время, а именно новые квесты на оказание фракциям медицинских услуг. также займусь разработкой если хватит ума и терпения.
