### ISSUE TITLE
Ненаучная фантастика?

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#2979]
Столкнулся со странным случаем. Упала капсула со здоровым пацаном. Через некоторое время пацан внезапно помер от внезапной трещины в позвоночнике. Чуть позже труп начал двигаться и воскрес - оказался агентом Скайнета. Вроде бы всё нормально, но... После "воскрешения" пацан слегка изменился.
![20210518140645_1](https://user-images.githubusercontent.com/47845929/118642316-dee5e680-b7e3-11eb-9f24-540c0b3996ec.jpg)
![20210518141355_1](https://user-images.githubusercontent.com/47845929/118642327-e2796d80-b7e3-11eb-8b46-7e8d25f99fee.jpg)

**Comment by EriIaz** [comment]
А может это просто не Скайнет?)

![Ataka-titanov-Eren_titan](https://user-images.githubusercontent.com/89162522/129964890-4e140afe-179b-45eb-8a55-8e299a912663.jpg)

**Comment by skyarkhangel** [comment]
Should be fixed already
