### ISSUE TITLE
Нужно обновить мод Gastronomy. В старой версии был баг для Линукса.

### ISSUE THREAD

**Issue by Andry2017** [skyarkhangel/Hardcore-SK#2991]
Мод Gastronomy содержал ошибку для Линукса. Игра вылетает при генерации планеты. В версия 02.01.21 для Rimworld (v1.2) указано что баг исправлен. Стоило бы обновить Hardcore SK Rimworld 1.2 project v10 (v.1.2.2723) так как это последняя стабильная версия и там мод с багом.

**Comment by Zim777** [comment]
ХСК давно уже перешел на 1,2,2753, а потом на 1,2,2900

**Comment by Andry2017** [comment]
Не все любят версии которые находятся в активной разработке. Так как порой бывают баги из-за которых приходится начинать игру заново.
