### ISSUE TITLE
I want to set start age 2100s -> 5500s

### ISSUE THREAD

**Issue by Redonsku** [skyarkhangel/Hardcore-SK#2994]
I want to make the first year to be 5500 years and enjoy it comfortably, but I failed no matter what I tried. I would like to know if there is a way to change the start year to 5,500 years or set it freely.

**Comment by AndreiAvinov** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2093902544

**Comment by Redonsku** [comment]
> https://steamcommunity.com/sharedfiles/filedetails/?id=2093902544

https://imgur.com/a/fDBrnmk
I tried it with this mod. However, setting the start year did not apply in the game. I don't know why.

**Comment by skyarkhangel** [comment]
We changed the starting date to make the game closer to realism. Bcs a lot of technology, weapons in HSK from the 19-21st centuries. In the regular game, there are far fewer references to Earth technology.

**Comment by Redonsku** [comment]
> We changed the starting date to make the game closer to realism. Bcs a lot of technology, weapons in HSK from the 19-21st centuries. In the regular game, there are far fewer references to Earth technology.

So, is there any way to change the start year or the existing save file year?

**Comment by Redonsku** [comment]
> 게임을 현실감에 가깝게 만들기 위해 시작 날짜를 변경했습니다. Bcs는 19-21 세기의 HSK에서 많은 기술, 무기를 사용했습니다. 일반 게임에서는 지구 기술에 대한 언급이 훨씬 적습니다.

I want to set the original start year at Rimworld and play the game, but I'm very sorry that it's set to 2100 so that I can't change it as I want. Is there no solution?

> We changed the starting date to make the game closer to realism. Bcs a lot of technology, weapons in HSK from the 19-21st centuries. In the regular game, there are far fewer references to Earth technology.

I want to set the original start year at Rimworld and play the game, but I'm very sorry that it's set to 2100 so that I can't change it as I want. Is there no solution?

**Comment by Redonsku** [comment]
> We changed the starting date to make the game closer to realism. Bcs a lot of technology, weapons in HSK from the 19-21st centuries. In the regular game, there are far fewer references to Earth technology.

I want to set the original start year at Rimworld and play the game, but I'm very sorry that it's set to 2100 so that I can't change it as I want. Is there no solution?

**Comment by AndreiAvinov** [comment]
> > We changed the starting date to make the game closer to realism. Bcs a lot of technology, weapons in HSK from the 19-21st centuries. In the regular game, there are far fewer references to Earth technology.
> 
> I want to set the original start year at Rimworld and play the game, but I'm very sorry that it's set to 2100 so that I can't change it as I want. Is there no solution?

Seems like there is no easy way to change that without digging somewhat deep into dlls

**Comment by hadaev8** [comment]
Same here, the old start date is preferable option.
