### ISSUE TITLE
Mobile Mineral Scanner/Deposits

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#30]
With mineral and oil deposits getting textures and being visible from the map start like geothermal geysers, does this mean that the mobile mineral scanner is now only useful for scanning mountains (like it originally was)?
If this is the intention then I'll adjust definitions accordingly. People didn't really seem to like being forced to scan to find hidden deposits.

However, there could be a "best of both worlds" with this. Have some deposits visible from the start and some hidden, findable by the scanner. That way people can have a place to get some extra ores to start, but will be required to invest in scanners to find extra ones later. Retains usefulness of the mobile mineral scanner while also making the game friendly to the user's understanding.

**Comment by skyarkhangel** [comment]
Okay... how i suggest to make this? Make rare minerals hidden?

**Comment by Masquerine** [comment]
I think the easiest way is to basically make a copy of each of the entries: mineral deposit, rare mineral deposit, oil deposit. One has the "is hidden until scanned" thing, the other appears naturally and is always seen. Also lets you adjust the spawning rate for both types that way.
Will do the events tomorrow. Been in the basement the last few days organizing and such. Got a billiard table. Lotsa fun.
