### ISSUE TITLE
Немного о балансе

### ISSUE THREAD

**Issue by goodDL** [skyarkhangel/Hardcore-SK#3012]
Во первых - при игре с хардкорным режимом инструментов и такой же настройкой тех уровней и их ограничений за племя, я не могу использовать мотыгу для посадки растений, а без неё на хардкоре нельзя, пишет нужна технология пивоварения, но даже после её изучения не могу взять, то же самое с метлой (постоянно приходится руками менять в файле принадлежность к неолиту этих вещей).
Во-вторых - терминаторы и батарейки за 10р из условного "ашана". Первая часть - захваченные гибриды не могут подзаряжаться от сети, а у меня не раз они появлялись ещё до изучения батарей дроидов и поясов-генераторов + к этому они пересели со своих реакторов на какие-то дешёвые щелочные батарейки, раз так быстро разряжаются (опять же ручками в файле исправляется). Вторая часть - дикие пролаги с пленными т800, захватил как-то 11 т800, в итоге еле как их всех отключил в таком лагодроме (1 кадр секунд 10 длился), при этом половина пешек просто зависала на месте со  статусом "стоит"
И в третьих - андроиды и гигиена. Первая часть - запрет выбора расы и имплантов для андроидов - зачем это? это эндгейм контент, к которому стремишься всю игру, а по факту они почти бесполезны выходят (опять же правится ручками в файле). Я понимаю, что им там бафнули немного статы статусом здоровья и отключили потребность в энергии, но это просто ничто на фоне отсутствующих имплантов и протезов. Вторая часть - жажда, сама гигиена не позволяет настроить именно только жажду, там только туалет и душ, так вот, андроид отправленный на "допечатывание" на сутки и 18 часов 100% умирает от жажды, хотя голод он не испытывает, ванометрик тоже не отключает потребность в воде, тут уже никак не смог с этим разобраться или как-то исправить

**Comment by Milten98** [comment]
Можешь в личку написать подробнее о настройке возможности выбора расы а "разрешении" установки имплантов андроидам. Буду очень благодарен.
