### ISSUE TITLE
Турели слишком сильны

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#3017]
Они могут стрелять вплотную.
Они имеют бесконечные патроны.
Они не горят.
С обычных винтовок урон смешной. 4 единицы, при хп 175 у самой простой турели. Турель механоидов имеет 1000 хп. Что делает ее ультимативным эндгейм боссом.

При этом та же самодельная турель имеет винтовочный калибр = хороший урон.
В остатке самая дешевая турель куда опасней хорошо одетого спейсера, а милишники умирают в попытке добежать до нее. Щит не спасает.
Стреляют они тоже довольно точно.

На квестахх турели нельзя захватить после разгрома лагеря, приходится ждать ночи и разряда батареек, что довольно тупо и скучно.

**Comment by goodDL** [comment]
Милкор тебе в помощь (или его младшая однозарядная версия) - 2 попадания с фугаса и нет турели с 1к хп, ЭМИ просто выключают их, да и дым завесы никто не отменял)
А на счёт бесконечный патронов - согласен, они вне СЕ работают, да и разлёт хп у инферно с бластерной просто громадный (100 и 1000).
В целом турели только на начальном этапе игры себя и показывали

**Comment by hadaev8** [comment]
Эми не работают на турели. Как минимум механоидов.
Эндгейм штуки не предлагать, потому что турели появляются с самого начала игры.
У инферно турелей такой огромный разлет, у снайперских и бластерных не очень.
Минитурель просто оружие судного дня.
Две мои турели отбили рейд средневековых челов.
При атаке на квестовые лагеря они же источник гемора.
Судя по всему, до захвата они читерят патроны.

**Comment by goodDL** [comment]
Милкор (тир2) и его младший брат (тир1) вообще далеко не эндгейм, особенно если у тебя уже пояса щиты есть. Эми работает на турели мехов, против обычных гранатомёты и снайпы, ну либо просто в фул латы заковывать пешку и сносить в рукопашку. У меня хоть и с магией хск, но и раньше проблем не было таких

**Comment by hadaev8** [comment]
Щиты я залутал.
Эми я тестил вчера - не работает.
Снайпа будет убивать мини турель до ночи, а там и батарейки разрядятся. Лучший геймплей в моей жизни, ага.
Гранатометы это ближе к миду/лейту.
С рейдов не лутаются особо.

Минитурель слишком сильна в обе стороны, как в плане создания ненужного гемора в простых по задумке квестах, так и в плане отбития рейдов.
Две турели без проблем вынесут пару десятокв индустриальных чуваков.
Они имеют больше хп, не горят и не станятся, стреляют точнее, стреляют винтовочным патроном.

Ты можешь конечно дальше объяснять, что я рак и не умею рашить в нужные техи, но с точки зрения геймдизайна это полный провал.
Башенки в нормальных играх не бывают сильней реальных юнитов.
Тут замочить пару десятков спейсеров куда проще, чем пяток самодельных мини турелей.

**Comment by goodDL** [comment]
Так я сам никогда не рашу технологии - так как настройки всё равно не позволят пользоваться вещами не из своей "эпохи", Полный сет латных доспехов имеет 10+мм брони, у меня просто платье было с зачарованием на 5мм и этого уже хватило, чтобы с парой синяков развалить турель милишником, без щита, так как не изучены.

В целом про баланс НПС турелей - согласен, бесконечные патроны, причём уже 5.56, а не .45 как раньше, стрелять может и вплотную, сам можешь пользоваться ими хоть на какой эпохе, главное чтобы была энергия для них. К слову, исследуются эти мини-турели после всяких страшных 14,5мм, 20мм и 30мм - это тоже весьма странно, после них разве что РК ещё есть. Очень далеко закинуты в технологиях
