### ISSUE TITLE
Various fruits give wrong mood bonus

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#302]
Strawberries and Oranges both give a "Ate awful meal" mood effect to pawns instead of a benefit.

**Comment by SmokeyUnicycle** [comment]
Too add to this, some foods like for example: 

Potatoes 

Canned Meat

Do not give an "Ate awful meal bonus" which if you've ever tried to eat a raw potato is very unrealistic :P

**Comment by ochkoebanoe** [comment]
Are you sure that you use stable branch or latest? Because i have changed this type of meals week ago.  https://i.gyazo.com/7a2a3a8430a9dcf8b10a2b991f053ff9.png https://i.gyazo.com/7b9a806036d98ade5159ca83d947bba8.png

**Comment by SmokeyUnicycle** [comment]
I have not updated in the past week, it is possible it was fixed. Is there a change log? I am having a lot of fun with my colony and don't want to ruin it by updating. (Or could I update without breaking the save?)

**Comment by ochkoebanoe** [comment]
Yes you can. https://github.com/skyarkhangel/Hardcore-SK/commit/df5899c8d72a7e9dfe90f4e9d1bf5326a96d3437 It must not crush the saves.
Just change here  Mods/Core_SK/Defs/ThingDefs_Resources/Items_Resource_Crops_Fruits.xml 
<preferability>MealAwful</preferability> to <preferability>MealSimple</preferability>

**Comment by skyarkhangel** [comment]
fixed
