### ISSUE TITLE
Ogre and abomination corpses cannot be composted in a compost bin

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#303]
They take multiple season to degrade

**Comment by skyarkhangel** [comment]
bcs not humanlike type.

**Comment by trevize23** [comment]
That would be inconsistent then as you can also compost fish corpses.

**Comment by SmokeyUnicycle** [comment]
They are in the animal tab under settings for what to allow in the compost box. 

They should either be removed from the menu on the compost box so pawns will stop putting them in the compost and clogging it, or they should be compostable I think.

**Comment by skyarkhangel** [comment]
Fixed
