### ISSUE TITLE
Не работает настройка качества и целостности предметов в назначениях оружия/предметов

### ISSUE THREAD

**Issue by Impleks** [skyarkhangel/Hardcore-SK#3032]
Не работает настройка качества и целостности предметов в назначениях оружия/предметов

https://skr.sh/s8fspDaA26u

Если настроить качество предметов, все будет работать в рамках текущей "сессии", но стоит только сохранить и загрузить, все параметры обнуляются опять на значения по умолчанию. 

Версия игры 1.2.2723 (caa8587)

**Comment by Zim777** [comment]
> Версия игры 1.2.2723
У нас давно уже 2900

**Comment by Glucocorticoid** [comment]
Не зависимо от версии игры ошибка присутствует (в том числе на 1.2.2900). Настройки набора снаряжения в сохранение записываются, но из сохранения не достаются или достаются некорректно.

**Comment by Zim777** [comment]
> Не зависимо от версии игры ошибка присутствует (в том числе на 1.2.2900). Настройки набора снаряжения в сохранение записываются, но из сохранения не достаются или достаются некорректно.

И решения до сих пор нету?

**Comment by Glucocorticoid** [comment]
На текущий момент выясняются причины такого поведения. Автором мода функциональность сохранения и загрузки настроек предусмотрена. Возможно с переездом на новую версию Combat Extended не хватает доп.проверок.

**Comment by Impleks** [comment]
> > Версия игры 1.2.2723
> 
> У нас давно уже 1,2,2900

Так я в курсе, проблема то очень давно, просто только сейчас решил о ней написать, так как данного функционала очень не хватает =)

**Comment by IacketI** [comment]
с последним обновлением стабильной версии появилась данная проблема

**Comment by SomethingCrunchy** [comment]
https://github.com/skyarkhangel/Hardcore-SK/blob/b5d76019033969d0e4f4220c7687d0000c7c0c3a/Mods/CE.ExtendedLoadout/Assemblies/Z.CombatExtended.ExtendedLoadout.dll скачать и заменить

**Comment by Impleks** [comment]
Спасибо! Помогло!
