### ISSUE TITLE
Embrasures have wrong description and don't work correctly

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#304]
Two problems: 
1. The tooltip description is the same as that for Parapet (A waist high wall bla bla bla)
2. They are not impassable like the full description says, pawns and animals will crawl through them. If this is intended, the description should be changed,

**Comment by Inei** [comment]
Embrasures are much harder to pass, than parapets, though, if I am no mistaken in the barbed wire description it's also said it is impassable, while it just slows enemies down.

**Comment by SmokeyUnicycle** [comment]
That is true, I had forgotten about barbed wire not working as expected. 

It's fine the way they work as is IMO, making them actually impassible might be OP, but the problem is that the description says otherwise misinforming the player. 

The game is hard enough with this mod for newer players, without lying to them about what things do!

**Comment by jnkyacc** [comment]
Vanilla limitations. If you can pass it - you can shot though it. But I'm not 100% sure.

**Comment by SmokeyUnicycle** [comment]
Deep water can be shot through but not passed!

But you guys might want to change "impassible" to "can be slowly crawled through" since balance wise I Think it's pretty good right now.
