### ISSUE TITLE
Most large caliber weapons have the wrong ammunition Tooltip text in trading menu

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#305]
They often say "A large caliber old school anti tank cartridge" regardless of the weapon, visible in the trader window.

**Comment by jnkyacc** [comment]
Sreenshot?

**Comment by SmokeyUnicycle** [comment]
http://image.prntscr.com/image/5fe588dd9fe840fe8763a568eb619180.png

This is the one it's accurate for, but it'll say the same thing for a bunch of ammunitions

**Comment by SmokeyUnicycle** [comment]
http://image.prntscr.com/image/5fe588dd9fe840fe8763a568eb619180.png

**Comment by SmokeyUnicycle** [comment]
Here found one by refreshing trade ships for several minutes

http://image.prntscr.com/image/37e2db8dd0aa496095d4bc38c13d7e51.png

**Comment by jnkyacc** [comment]
Ook, thx :)

**Comment by SmokeyUnicycle** [comment]
here they are irl lol

http://3.bp.blogspot.com/-etMaZWmaseE/UyhHCHlrnzI/AAAAAAAAAZw/6S7-BS6VA-0/s1600/35x228+at+hand.jpg
