### ISSUE TITLE
Various weapons have wrong caliber in their descriptions:

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#306]
-M42A4 Sniper Rifle: Says it takes 10mm HEAP but actually uses 7.62x51mm NATO 

-M256 Smart Gun: Says it takes 28x10mm Caseless but actually uses .50 BMG

-Desert Eagle .45 ACP means that the gun uses .45 ACP but it actually uses .50AE (Action Express)

-FN SCAR-H does not say what it uses, but it it uses a Soviet/Russian 7.62x39mm round in game when IRL it uses the longer NATO 7.62x51mm which is also in game. This is confusing to people with knowledge of real life weapons as they would build/buy the wrong type of ammo for the weapon.

**Comment by jnkyacc** [comment]
Ok. Thx. There is really mess with English description, as almost no feedback.

**Comment by SmokeyUnicycle** [comment]
The M82 Barrett is in game 14.5x114mm but IRL it's in .50 BMG. 

Is it helpful for me to continue to post every time I find an inconsistency? I'm new to this kind of thing.

**Comment by SmokeyUnicycle** [comment]
The Gsh 30mm turret says it uses 35x228mm shells in one of its descriptions but it uses 30x173 in game (which is not what it used in real life, but it's close enough since the real round isn't in game and isn't worth adding)

Also for some reason the GAU-8 Avenger is 35mm in game but IRL it's 30x173mm, I do not understand this, because the GAU-8 Avenger uses a bullet it did not use, and the GSH uses the Avenger's round instead!

Bug fixing wise, just the GSH 30 description (cannot remember if tool tip or information menu) is needed, but from a making sense with real life maybe make the two guns use the same round and just change the stats of them so one fires in shorter bursts?  I'm not sure there need to be two almost identical cannon ammunition types for gameplay reasons.

**Comment by jnkyacc** [comment]
> Is it helpful for me to continue to post every time I find an inconsistency? I'm new to this kind of thing. 
Yep. Just try edit your previous post if its 1-2 items only.

**Comment by skyarkhangel** [comment]
Fixed
