### ISSUE TITLE
install button is disabled

### ISSUE THREAD

**Issue by amdradeon** [skyarkhangel/Hardcore-SK#3060]
launcher install -> check updates ->(update) -> "you have the latest version" -> mods install -> play

but now

launcher install -> check updates -> (update) ->"you have the latest version" ->  (I checked mods...  there aren't anything in the mods folder!) -> "you have the latest version" -> "you have the latest version" -> "you have the latest version" -> .............

what's wrong?

**Comment by amdradeon** [comment]
I solved this problem

**Comment by SetAriman** [comment]
У меня эта проблема сегодня впервые вылезла.
