### ISSUE TITLE
Ship Traders offering large amounts of extremely valuable armor for very low prices

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#307]
Exotic Goods traders will regularly have 6 suits of Feral Plate Armor and Feral Spiked Plate Armor made out of expensive metal alloys for extremely low prices, these can either be worn as very effective armor or deconstructed for huge amounts of expensive alloys. 

You can get 38 Beta Poly for 120 silver ore and a few seconds at a tailoring bench. 

This is unique to these armor sets, normally a shoddy knife made out of expensive materials is also expensive, but these armors are an exception!

**Comment by SmokeyUnicycle** [comment]
TL;DR: Feral Plate and Feral Spiked Plate armors prices are way too low  and/or do not reflect material properly, and the frequency of their appearance in merchant ships might be too high.

**Comment by skyarkhangel** [comment]
ok... bcs some apparel have <MarketValue></MarketValue> in stat bases. Need to remove this line.
Soon check all apparel for this.

**Comment by SmokeyUnicycle** [comment]
Wait, so is value calculated by the actual stats of the item as well? 

I thought it was just a (marketvalue) x (material) x (quality) x (item health %)

**Comment by skyarkhangel** [comment]
Fixed
