### ISSUE TITLE
Can't place Doors on Wall's Blueprint.

### ISSUE THREAD

**Issue by ShanKanis** [skyarkhangel/Hardcore-SK#308]
Like the title, can't place doors on Wall's Blueprint. With completed wall it works fine.

https://s11.postimg.org/dqeqloohf/Doors_bug.jpg

**Comment by WaytobeGlad** [comment]
Its a feature right now.
By the way, you may install the door while the wall is just filled with resources, but not yet built.

**Comment by sidfu** [comment]
dont forget to mention if u destory 1 side of tthe wall of a door the door starts taking damage till it is destoryed
