### ISSUE TITLE
Is this pack supported for 1.3? 

### ISSUE THREAD

**Issue by belens** [skyarkhangel/Hardcore-SK#3086]
Just a quick question, is this modpack already supported for 1.3? I tried looking it up but i cant find anything on it. Thanks in advance, I LOVE the work you've done!

if there is anything that needs to happen to help, im happy to pitch in.

**Comment by GuardianDll** [comment]
Nope, its not, and willne be updated to 1.3 for month (at least to time when 1.3 got most of bugfixes)
And its better to ask in discord for better responding
https://discord.gg/2PmdgRyn37
