### ISSUE TITLE
Collecting resources

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#309]
Aborting the Collect Sand/Rubble/etc process instantly gives you the resource. 

Also this needs some balancing. I don't get why collecting sand would take that long. Isn't that one of the easier things to do and should therefor take little time.

**Comment by SmokeyUnicycle** [comment]
I think the time part is for balancing, since without sand on the map you need to crush rubble/rocks/chunks and blocks

**Comment by skyarkhangel** [comment]
Fixed in last updates?

**Comment by trevize23** [comment]
Fixed. Thanks.

Can you also change the collecting sound? Currently it's the same as for medical operations (not really fitting). I think the Cut plants/harvest sound would fit better.

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
Sound changed. Thanks.
