### ISSUE TITLE
AI Chip nerf

### ISSUE THREAD

**Issue by xwat** [skyarkhangel/Hardcore-SK#31]
Since 2.5-17 AI Chip has been nerfed greatly: instead of +35% bonuses to consciousness/manipulation/moving/talking it is only meager ~4-8%.

At the same time brain stimulator gives very competitive bonuses to consciousness/moving/manipulation (+7-8%), but is available much earlier.

Am I missing anything? If not I suggest to restore AI Chip to its former glory.

**Comment by skyarkhangel** [comment]
I think we can, but not so much. Bcs, earlier, for example, it was possible to increase the manipulation to 2000%+

**Comment by skyarkhangel** [comment]
In next update would greatly improved
