### ISSUE TITLE
Fences - What's the point?

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#312]
Current description says: A small fence is perfect for outdoor gardens. It is very fast to build, but weak.

Recently I've build up my garden and noticed that fences don't keep out predators like crashbugs. Is this intended? The fences only slow down movement (like barbed wire) making them imo useless as protection for your garden.  They cost more than walls (+1 component) and don't block out enemies. You can shoot over them, but their low hitpoints make them useless for defence. 

I think the idea of a fence is still nice as it gives additional immersion. They would be fine if made impassable like walls, but the additional component cost still makes them very expensive.  Maybe that would make more sense if the Work Speed factor was also increased (I assume this also works for growing).

**Comment by skyarkhangel** [comment]
the eternal problem since start work with hardcore sk. This rework would strong influence on game balance. Only if add impossible to shoot through them.

**Comment by Vigilence** [comment]
Fences should:

- Block animals and pawns from getting through

- Not act as cover when shooting

- Give a minor aiming penalty but allow shooting through it

**Comment by Ivanzyfer** [comment]
#325
