### ISSUE TITLE
Pawn fails to reload

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#313]
When you set "current mode: attack" the pawn will not reload it's weapon properly. Instead it will try to reload over and over again.

![reload bug](https://cloud.githubusercontent.com/assets/22052564/18554037/3393438e-7b63-11e6-97a8-c428c5ef5372.jpg)

**Comment by ScottS9999** [comment]
Possibly the same problem, or related - when a pawn runs out of ammo while hunting, it will stand there attempting to reload, over and over.

**Comment by jnkyacc** [comment]
Other modes works?

**Comment by trevize23** [comment]
Other modes work fine. Same mode with a melee weapon works fine.

To clarify: The pawn does this even though he has the correct ammo in it's inventory.

**Comment by jnkyacc** [comment]
Cannot reproduce(AKS74-U). What weapon?

**Comment by trevize23** [comment]
Had that issue with every weapon (not weapon or ammo related) and also in new colonies. Couldn't reproduce in newest version.
