### ISSUE TITLE
Приоритет склада с переносом не работает.

### ISSUE THREAD

**Issue by Vragerr** [skyarkhangel/Hardcore-SK#3159]
Не работает приоритетность складов при переносе с низкого на высокий, если вещь не на складе ее несут на высокий приоритет, но если вещь уже лежит на низком переносить не будут, тоже с трупами и могилкой (учитывая ее работу как склада) , если трупы уже лежат на складе кнопки хоронить нету.

**Comment by cross228tu** [comment]
Обнаружено, пешки все-таки несут со склада при условии, что в его настройках нет данных предметов. Такое ощущение, что приоритет не учитывается совсем.

**Comment by EriIaz** [comment]
Сторонние моды установлены? 

Предполагаю конфликт с Common Sense. Если он установлен, то нужно расположить его выше, чем Pick up and haul в порядке загрузки, тогда переноска заработает корректно.

**Comment by Vragerr** [comment]
Да ,common sense установлен. Переместил выше этих модов и починилось, спасибо.
