### ISSUE TITLE
1.3 церемония присвоения титула

### ISSUE THREAD

**Issue by cross228tu** [skyarkhangel/Hardcore-SK#3161]
Во время квеста по присвоению титула после завершения ритуала все грузятся обратно на челнок, однако один из солдат не хочет заходить в челнок, просто гуляет рядом. Спустя 2-3 дня солдат "спасается бегством" с карты, челнок все еще стоит ждет его. Спустя еще день-два челнок выгружает трупы остальной команды, а игроку начисляется штраф репутации как за убийство их всех.

**Comment by skyarkhangel** [comment]
Should be fixed already.
