### ISSUE TITLE
New Refueling System Fix?

### ISSUE THREAD

**Issue by johncabz** [skyarkhangel/Hardcore-SK#317]
Is there any temporary fix for the issues with the refueling system? Or am i the only one having an issue with it where whenever someone tries to refuel anything, it just spams errors, and then crashes if you attempt to draft/undraft anyone stuck in the error loop

I know there was already a post on this, but Unfortunately, I do not speak Russian, and google translate does not quite translate it correctly, and this issue is quite game breaking as you cannot cook food

**Comment by jnkyacc** [comment]
Not yet.

**Comment by Vigilence** [comment]
Yeah it's a bit unstable atm, causes system pauses due to the errors.

![screenshot 76](https://cloud.githubusercontent.com/assets/16742086/18603236/c5628330-7c3d-11e6-9280-7e6364628aec.png)

**Comment by jnkyacc** [comment]
@Vigilence need screenshot with this campfire and Igro.

**Comment by Vigilence** [comment]
![screenshot 78](https://cloud.githubusercontent.com/assets/16742086/18603359/c0b39b16-7c3e-11e6-9ff6-7c00b9d123bd.png)
![screenshot 77](https://cloud.githubusercontent.com/assets/16742086/18603360/c0b4ab28-7c3e-11e6-9a40-f134011b7b29.png)

**Comment by jnkyacc** [comment]
Remove everything around campfire and report back please.

**Comment by Vigilence** [comment]
![screenshot 79](https://cloud.githubusercontent.com/assets/16742086/18603587/db54c18c-7c40-11e6-8bae-96ae5a142c18.png)


I do get the crashing while drafting and undrafting the cook, I just don't pick him anymore.

**Comment by jnkyacc** [comment]
>_< can't see camp fire. Possible to refuel now or not? 
Yes, I forgot to tell that drafting lagging pawn causes crash. Sorry.
Try to force him to do some stuff or wait till he black out.

**Comment by Vigilence** [comment]
I cleared the area and the errors stopped, the constant slowing down has stopped.  My guys are refueling now.

![screenshot 80](https://cloud.githubusercontent.com/assets/16742086/18603923/2c5e2d90-7c44-11e6-9343-250b374ddca4.png)

**Comment by Vigilence** [comment]
I wish this game did a better job at storing things.  Other games can store items inside of containers and the items dissapear from the enviornment, saving space.

**Comment by jnkyacc** [comment]
Great. So for now:
1) Any loaded fuel will diapers after loading.
2) Drafting\undrafting lagging pawn cause crash.
3) You should keep space around any workbench or generator wich need to be fueled - 1 tile free.
xxx............xxxxxx
xox...........xooox 
xxx............xxxxxx
x - free space \ o - workbench or generator

**Comment by Vigilence** [comment]
Unless the containers hide the items and save space I don't see the point.

**Comment by Inei** [comment]
> Unless the containers hide the items and save space I don't see the point.

But... Containers do hide items and save space. (3 items stack for usual containers, 5 for military boxes), plus pots reduce deterioration rate by 25 percent for food.

**Comment by trevize23** [comment]
Not true, containers don't hide items - their beauty still affects the room. Don't know how they work in detail, but it looks like they just make different items stackable. 

Whenever I load my fuel disappears, did that get fixed already?

**Comment by jnkyacc** [comment]
> Not true, containers don't hide items - their beauty still affects the room. Don't know how they work in detail, but it looks like they just make different items stackable. 

It makes them invisible, but they presence still affecting the room. Its not critical so will be fixed soon or later.

> Whenever I load my fuel disappears, did that get fixed already?

Yes. Possible some refueling priority issue, but nothing critical.

**Comment by trevize23** [comment]
Okay I updated to newest version and works fine now.

I suggest adding some manual refuel option (like we have with torches already). It can get really tricky when you are low on meals and your stove is out of fuel. No way to cook manually and you have to way for the sometimes retarded pawns.
