### ISSUE TITLE
Статусы пешек слишком темные 1.3

### ISSUE THREAD

**Issue by shikulja** [skyarkhangel/Hardcore-SK#3170]
![Снимок экрана 2021-08-29 185308](https://user-images.githubusercontent.com/3386359/131257019-68a71e60-ed3c-42da-84e2-e866545e7112.png)

Раньше было нормально в 1.2, сейчас в 1.3 вообще ничего не разглядеть

**Comment by ArpoMo6** [comment]
На 1.3 ещё не перенесли модификацию Color Coded Mood Bar. Можете пока использовать его или его аналоги (Mood Bar Color, Colonist Bar KF) из мастерской
