### ISSUE TITLE
Full military box graphic bug.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#318]
Там глюк с коробкой этой - когда она заполнена - спрайт меняется на красный крестик, возможно это только с этим видом коробки, так как другие не проверяла.

http://imgur.com/a/ltRbo

**Comment by jnkyacc** [comment]
```
Could not load UnityEngine.Texture2D at Things/Building/Furniture/Containers/Mrofabox_full in any active mod or in base resources.
```

**Comment by skyarkhangel** [comment]
Должно быть поправлено в последних апдейтах.

**Comment by skyarkhangel** [comment]
Fixed
