### ISSUE TITLE
Can't Rotate Kiln

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#319]
Unlike other production structures where you can rotate to your liking, the kiln can only be set in one direction.
![screenshot 81](https://cloud.githubusercontent.com/assets/16742086/18604681/54f9c062-7c4d-11e6-8297-58efc0bfdcf7.png)

**Comment by jnkyacc** [comment]
By design.

**Comment by Vigilence** [comment]
Why by design, it doesn't make sense.  Everything else is rotatable.

**Comment by jnkyacc** [comment]
Because there is not texture for kiln sides.

**Comment by Vigilence** [comment]
Yeah I saw, no clue why they didn't finish the other drawings.  Really bad decision.

**Comment by jnkyacc** [comment]
You can make it rotatable by your self if it so annoying for you.
Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Production.xml open with notepad
Find "Kiln" then change rotatable from false to true.
`<rotatable>True</rotatable>`
But it will looks ugly :)

**Comment by skyarkhangel** [comment]
Soon rework with new textures, with rotation support.

**Comment by skyarkhangel** [comment]
Added.
