### ISSUE TITLE
Cannot grow mushrooms in the 'Fungal Gravel' soil

### ISSUE THREAD

**Issue by vladimirlashko** [skyarkhangel/Hardcore-SK#3194]
В DLC Ideology есть идеология Tunneler - открывает тип почвы Fungal gravel (плодородность 70%) - по задумке для выращивания грибов. Но в HSK нет подходящих под эту почву грибов. Т.к. шампиньоны требуют мин. плодородности 90%, а остальные грибы только в ящиках растут.

**Comment by ArpoMo6** [comment]
есть, nutrifungus (питательный гриб)

**Comment by vladimirlashko** [comment]
Спасибо!
