### ISSUE TITLE
Edb Prepare Carefully - Missing Listed Skills

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#32]
When you use the Prepare Carefully option for Edb Prepare Carefully, the listed skills doesn't match the normal embark skills - Fishing and Managing are missing from the list. Picture attached shows.
![edb prepare carefully embark](https://cloud.githubusercontent.com/assets/16396520/12733869/40804016-c90b-11e5-84ff-3b869a9fa36c.jpg)

**Comment by skyarkhangel** [comment]
Yep, Edb not support this skills. In A13 we try to add them.

**Comment by skyarkhangel** [comment]
Realized in last update.
