### ISSUE TITLE
Fueled Stove not considered a meal source

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#321]
Fueled Stove is not recognized as a meal source and the game will still give you the "need meal source" popup.

**Comment by jnkyacc** [comment]
Seems ok to me. [Here](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L338)
Mb side effect from new refueling system. Pls check grill, oven and electric stove.

**Comment by trevize23** [comment]
Seems like it got fixed with that patch already. My version (5-6 days ago) didn't have that particular line of code for Fueled Stove (rest worked).
