### ISSUE TITLE
Безоружные дружественные пешки "воруют" оружие

### ISSUE THREAD

**Issue by Raymack** [skyarkhangel/Hardcore-SK#3210]
Безоружные гости беспардонно берут оружие со склада. Или рабы из каравана работорговцев хватают только что купленное у этого каравана оружие. Пробовал отключать в SkyAI настройку поиска оружия и патронов - не помогает.

**Comment by SetAriman** [comment]
У меня со склада не воруют, но пару дней назад караван подарил медикаменты, тут же их сами забрали и ушли.

**Comment by skyarkhangel** [comment]
> У меня со склада не воруют, но пару дней назад караван подарил медикаменты, тут же их сами забрали и ушли.

как подарил? Если пешки не продали медикаменты, а выронили, заберут обратно, даже если медикаменты на складе игрока.

**Comment by SetAriman** [comment]
Не выронил, а подарил. Караваны иногда дарят что-то, когда собираются уходить с локи. И об этом проходит сообщение, что они оставили вам подарок. С пол-года назад это работало. Правда это редко бывает. Ещё реже, чем подарок еды от другой фракции. В результате сообщение прошло - подарок кинули на землю - тут же подобрали и ушли.

**Comment by Raymack** [comment]
У меня после прошедших обновлений больше не тащат "не свое". Ни оружие ни медикаменты.

**Comment by skyarkhangel** [comment]
В следующем обновлении добавил патч-фикс для подарков.
