### ISSUE TITLE
Неадекватное поведение.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3227]
На карту пришли расхитители. Потом туда же пришёл рейд. Лучники расстреливали расхитителей практически в упор - без какой-либо реакции со стороны жуков. Хотя гнаулеры и антисы обычно весьма агрессивны. Мало того, рейду надоело расстреливать, они "сдались и ушли". Выглядит странно.

**Comment by skyarkhangel** [comment]
Рейд теперь может уйти если определенная его часть осталась без боеприпасов и возможности их взять. На недавних тестах обратил внимание что временами генерируется недостаточный боекомплект у определенных классов, например у лучников. 16-18 стрел, очень мало. На счет расхитителей, надо потестировать.
