### ISSUE TITLE
Luncher

### ISSUE THREAD

**Issue by Kapsel444** [skyarkhangel/Hardcore-SK#3228]
I have a problem with the lucher. I stopped playing rimworld after 1.3 came out and waited some time before comeing back and I did not play HSC but base with Royalty, Ideology and some mods from Steam but after some time I came back to check up but when I clicked the button for updetes I saw this
![2021-11-24_LI](https://user-images.githubusercontent.com/94997375/143314457-ca80aa15-521d-4bb7-b29a-6326163f1ded.jpg)
then everything got blurry but I finally was able to see a text saying that this version is not suitable and tried reinstalling but my computer thought that this file was a threat or sth but I reinstalled it and nothing changed. PLS !!!  Help.

**Comment by sidfu** [comment]
did you try the one from discord on announcments

**Comment by Kapsel444** [comment]
No I tried the one from the main site on github

**Comment by Kapsel444** [comment]
Still the same problem with gliching

**Comment by sidfu** [comment]
might be something on your computer blocking it

**Comment by Kapsel444** [comment]
It did say it was considered dangeorus but I marked it as safe

**Comment by Kapsel444** [comment]
Well I might just wait for the 1.3 update to come out and I will see if it works or not

**Comment by zakhad** [comment]
We've had a 1.3 update for the past 3 or so months. It's not been moved to master/stable branch of github if I were to presume that's what you meant. Just go to the development/experimental branch, there's a lot of information in the discord regarding installing faq that I did, it doesn't really cover the launcher but it's more or less self explanatory for the launcher, you download it run it, point to the correct location and select the github branch you want and then download.

**Comment by Kapsel444** [comment]
Thanks for the info. It seems that the only problem is graphics so it is usable now the rest works
