### ISSUE TITLE
Fueled smithy glitch

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#323]
У колонистов свадьба началась, и работа по созданию шлема была отложена, теперь её невозможно продолжить, потому что предмет создаваемый оказался "в центре" кузнечного горна, и к нему невозможно проложить путь. 

http://i.imgur.com/oxuj1Fp.jpg

**Comment by jnkyacc** [comment]
Ее бы 2х2 сделать, а то сейчас она большая и страшная...

**Comment by skyarkhangel** [comment]
Должно быть поправлено в Rufuel update v8

**Comment by skyarkhangel** [comment]
Fixed
