### ISSUE TITLE
Bandits with Lee-Enfield.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#324]
Баг состоит в том, что бандиты или гости, которые появляются с данной винтовкой, оказываются либо вообще без патронов дополнительных патронов для неё, либо с патронами для других видов винтовок.  Сначала думала просто не повезло, но это уже третий или четвёртый раз так.

**Comment by skyarkhangel** [comment]
ок

**Comment by skyarkhangel** [comment]
Поискал, не нашел проблемы. Странно, все должно быть нормально.

**Comment by skyarkhangel** [comment]
Closed.
