### ISSUE TITLE
Развитие проблем с паузой.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3242]
Сейчас обновил и запустил игру.
1. Союзный вылеченный поселенец благополучно встал с больничной койки и отправился к выходу с карты. Почти всё хорошо. Почти, потому что остался момент, что у него с собой есть пеммикан, но он его не ест и находится на грани голодного обморока.
2. "Фракционной" паузы то же нет. Всё хорошо.
3.  Пришёл рейд и ... теперь он периодически становится на паузу.
MapComponent_SkyAI: RaidData check part exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at SkyMind.MapComponent_SkyAI.MapComponentTick () [0x00c81] in <83e88fe6f05548779cdc55b5494db177>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
SkyMind.MapComponent_SkyAI:MapComponentTick ()
Verse.MapComponentUtility:MapComponentTick (Verse.Map)
Verse.Map:MapPostTick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch1 (Verse.Game)
Verse.Root_Play:Update ()

Помимо этого, у рейдов в последнее время какая-то странная механика появилась. Сейчас пришёл рейд. Сообщается: нападает сразу. Но рейд проходит пол-пути и начинает тусоваться на одном месте. Причём разные группы рейда могут вести себя независимо. Можно перебить две пришедших группы из одной и той же волны рейда, и уйти с позиций, а третья так и будет непонятно зачем торчать посреди маршрута.

**Comment by skyarkhangel** [comment]
В версии 1.7 я загнал коллекцию с сохранением выхода точки в рейд, но ведь не все фракции могут его создавать, а значит не могут сохранять. Верну позже как было раньше. Косяк.
Вполне возможно это как раз было из-за опечатки в цикле. Присваивался аргумент другого цикла.
