### ISSUE TITLE
[Suggestion] Fence & Embrasures

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#325]
1) Fence
Если добавить `<regionBarrier>true</regionBarrier>` то смогут пройти колотисты и прирученые звери, но не могут дикие звери. Но при постройке оно выдает ошибку что не может сделать регион, не особо критично, но не приятно. 
Либо сделать их непроходимыми, уменьшить хп и убрать филл что бы не давал укрытие.
А то в данный момент это чисто декорация.

2) Embrasures
Есть смысл их делать непроходимыми и простреливаемыми? Что бы не абузили можно прилепить к ним дорфикс.

**Comment by skyarkhangel** [comment]
Не люблю всплывающие ошибки. Много их?

ИИ будет тупить, если сделать амбразуры такими. В этом главная проблема. Если сделать замкнутый контур из таких амбразур, то ИИ будет считать их автоматически не простреливаемыми.

**Comment by jnkyacc** [comment]
> Если есть задания, то начинает повышать температуру до рабочей. Соответственно убрав все задания, строение постепенно перейдет в режим экономии. 

Каждый раз когда строишь фенсу.

**Comment by SmokeyUnicycle** [comment]
I keep opening this thread because the title is in english and I think I haven't read it yet

**Comment by skyarkhangel** [comment]
это не прописать в xml. Используются в некоторых методах на проверку доступности к цели.
