### ISSUE TITLE
У дронов мёрзнут лапки.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3254]
Обнаружил дрона-уборщика, который "Ожидает в комфортной температуре" с серьёзной гипотермией. Это бага или фича? о_О
P.S. И гипотермия у него не спадает. В результате чего дрон становится бесполезен.

Кстати: при выделении дрона показывается кнопка DEBUG: Info.

**Comment by skyarkhangel** [comment]
Проверил. Гипотермии не получают. Возможно другая ошибка привела к сбою.

**Comment by SetAriman** [comment]
Сомневаюсь. Может позже были какие-то правки. Но на тот момент температура была около -100*С на улице. У дрона никаких других влияющих факторов не было. Он именно пережидал гипотермию в комфортной температуре. По сообщениям игры. И не мог сам лечиться и действовать после этого.
