### ISSUE TITLE
Проблема с топливом. 

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3256]
Новых модов вроде не было, а у старых такой настройки не нашёл. Но после одного из последних обновлений с каждой загрузкой игры сбрасываются настройки "топлива" для факелов, печей и прочего на дефолтные. Что весьма неудобно. Только показатель дистанции остаётся.

**Comment by AndreiAvinov** [comment]
Пофикшено #3257
