### ISSUE TITLE
SkyAI makes printed Android leave map

### ISSUE THREAD

**Issue by ottodeluxe** [skyarkhangel/Hardcore-SK#3261]
Just as the title says: I have printed an android. The android joins as colonist, as you would expect. But as soon as it spawns, it runs to the edge of the map and leaves. The android can be drafted and locked in a room, but as soon as it has an opportunity to do so, it will leave the map.

I have tried debug options to force a mental breakand re-recruit the andoid, but this behaviour continues. When I first printed it, the android had a star symbol above its head like the ones from the SkyAI mod from the mod options. Turning on the debug I found that the pawn indeed always tried to c alculate the best way to leave the map, but I do not know why.

There are other small error which can probably be ignored, the debug output relevant to this should be the last few lines: https://git.io/Jy84G

**Comment by ottodeluxe** [comment]
Disabling SkyAI, restarting the game, arresting and re-recruiting the android has fixed my problem. Not a great workaround, but at least the androids mod becomes useable

**Comment by sidfu** [comment]
your game is now broken. skyai cant just be deleted. it will get fixed the bug but your save is probably messed up now and even thou it load your gonna have allot of different issues cause of it.

 recommend you prepare to start a new game.

**Comment by skyarkhangel** [comment]
I am working around this bug. For some reason for some players droids are assigned exit duty after being built, its when all player pawns should have NULL duty.
