### ISSUE TITLE
Недоработка лечения.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3264]
Спас фракционного бойца. (Миссия спасения разбившегося челнока.) Положил в медкойку. А лечить не могу - нет опции. Максимум стабилизировать кровотечение на время, взяв медикаменты в инвентарь. Причём у самого бойца в меню нет выбора типа медикаментов для лечения. Хорошо додумался позже лечить его в боевом режиме. Тогда - да: вылечил и кровотечение и обработал заражение. После чего, по истечению кд у заражения, появилась опция лечения. Правда - травами. Выбора медикаментов ведь нет. Т.е. захваченного бандита лечить как угодно можно, а дружественного бойца - нет.

**Comment by skyarkhangel** [comment]
Вот как исправлять баги с таким багрепортом. Почему ты уверен что ошибка связана с тем что пешка дружественная? Скорее всего пешка относится к какой-то определенной фракции или типу, в которой возникает такая ошибка. Этих данных в багрепорте нет, сейва нет.

**Comment by SetAriman** [comment]
А кто ж знал, как именно багрепортить? Чукча не писатель, чукча игратель. На будущее постараюсь учесть.
