### ISSUE TITLE
Мод Better Pawn control не умеет работать со вторичными приоритетами

### ISSUE THREAD

**Issue by zaripovk** [skyarkhangel/Hardcore-SK#3288]
Мод  Better Pawn control не умеет работать со вторичными приоритетами.
При изменении вторичного приоритета в сторону уменьшения. после закрытия и открытия вкладки "Работа"  первичный приоритет изменяется на тот, который был выставлен на предыдущем действии, вне зависимости от того, развёрнуты вторичные тайминги или нет.

**Comment by skyarkhangel** [comment]
Чтож, печально. Очень надеюсь, что @bananasss00 вернется (автор ExtentedLoadout и совместимости с BPC) и поработает в этом направлении.

**Comment by TheLonerD** [comment]
Если кто-то натолкнётся на этот ишью: я заимплементил подприоритеты в bpc (доступно в 1.4 и 1.5), в процессе поддержка ExtentedLoadout (как руки дойдут).
