### ISSUE TITLE
Unfinished items crafted at the smithy can't be reached.

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#329]
Items crafted at smithy  can't be reached if only partially created as the unfinished object is in a inaccessible location in the middle  and have to be manually canceled or destroy the smithy.

**Comment by skyarkhangel** [comment]
They should be corrected in the latest updates.

**Comment by Ivanzyfer** [comment]
#323

**Comment by skyarkhangel** [comment]
Fixed
