### ISSUE TITLE
Fish meat is not shown in the statistics screen

### ISSUE THREAD

**Issue by xwat** [skyarkhangel/Hardcore-SK#33]
The picture below describes the issue.

![fishignored](https://cloud.githubusercontent.com/assets/5422293/12798182/532211a4-cac8-11e5-837d-aa8a0b4e4536.png)

P.S. The issue could be with this line in class `HistoryAutoRecorderWorker_RawFood`
```
if (keyValuePair.Key.IsNutritionSource && (keyValuePair.Key.ingestible.isMeat && keyValuePair.Key.ingestible.preferability == FoodPreferability.Raw))
          num += (float) keyValuePair.Value;
```

Is fish meat internally not a meat?:)

**Comment by skyarkhangel** [comment]
Thank you, soon fix.
