### ISSUE TITLE
The Nuclear Bombing event seems to have some issues

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#330]
Descrpition: 

"Oh shit, its Nuclear fallout. We are all die."

Is badly translated and breaks the theme of the normal event descriptions by being too informal and crass. 

-It does not provide an alert like all other events does, only an audio cue "Nuclear Launch Detected" 

-It implements radioactive falllout differently than the normal event (Toxic Fallout), with Radiation health effect instead of Toxic Buildup 

-The "We will die!" text and mood debuff are poorly done, and don't make any sense when the normal "Radioactive Fallout" event doesn't provide the same thing,  the -15 mood for two plus weeks is very punishing. Then again, since the plants don't seem actually be  harmed like they're supposed to maybe it's not. 

-It seems to have a massive unmentioned temperature effect, as mid summer is now around 0*C instead of 30 for me, and it keeps snowing. This is not mentioned anywhere in the badly done descriptions. 

Additionally, the explosion did no damage to anything but that may just be the explosion bug doing its thing. 

---

I would suggest changing the description, making it function closer to Toxic Fallout and/or making it clear that the event spawns a Nuclear Winter map condition. I would also suggest making it not take 100 days like it seems to, since that is far too long for endless winter for most players to survive. It needs some cleaning up and balancing. I would also like to know why someone launched a nuke at us! 

I think it's a very cool event, but it feels unpolished, confusing and a little unfair compared to the other events. All the mechanical elements are there, it just needs some tweaking.

**Comment by skyarkhangel** [comment]
So, you can improve event description, thoughts description etc :)

**Comment by SmokeyUnicycle** [comment]
Okay, so here are the problems, first there is the text and alerts which are easy enough to change.

I cannot find it in the game files though so I don't know exactly what it does or says, but here are two similar events and their text:


> A distant chemical fire has released a plume of poison over this entire region.\n\nAny person or creature not under a roof will be slowly sickened by the toxic dust settling out of the atmosphere.\n\nIt will last for anywhere between a few days to over a month.</

> A distant supervolcano has erupted and begun spewing millions of cubic kilometers of ash into the atmosphere.\n\nAsh in the atmosphere will obscure the sun. Temperatures will drop and plants will suffer for lack of sunlight. It could pass in a few weeks, or it might last many months.</


So I'll try and write one like these for the event:

>You colony has been struck by a low-yield nuclear weapon, in addition to the explosion, it has lofted a  plume of radioactive particles into the lower atmosphere, blocking sunlight and irradiating the area. Temperatures will be lowered and exposed people and animals will take radiation damage. 







But there is also the problem of what it does to the colony:

---------------------------

Right now the event does the following damage to your colony/map: 

-Big explosion seems to be aimed at your colony not just randomly on the map, this already does a lot of damage by itself killing or injuring pawns and buildings. 

-Spawns Radiation everywhere outside the map, enough to kill anyone who tries to work outside for more than one day in a row

-Makes it winter for multiple seasons (100 days?) so you will have blizzards in summer 

- "We Will die! -15" mood effect for 15 days (Description is "The radiation will kill us!")


All four  of these together at the same time is very very unfair.  :(


It will kill a colony unless they have a year of food in storage, because it means you cannot grow food outdoors anymore for almost two years. 

This means the event must be very very rare, but then it almost never happens so nobody gets to see it, and when they do see it, it kills them. 

This is bad I think, because it is a good event idea that could be very fun, right now it is not fun at all. 

It needs to be less harmful to be fair.

**Comment by skyarkhangel** [comment]
ok. changed descriptions. And some values.
