### ISSUE TITLE
Олово используется как топливо для костра...

### ISSUE THREAD

**Issue by OpacareAngelus** [skyarkhangel/Hardcore-SK#3300]
Собсна, баг по сабжу. Пешки тянут слитки олова в костёр. Горит и даёт 450 градусов температуры оО
В списке топлива его нет.
Лечится ручным запретом ВСЕГО топлива, а потом настройкой доступного из списка. Походу, мало того, что затесалось в топливо, так еще и не отображается в списке доступного топлива.

**Comment by AndreiAvinov** [comment]
А можно сейв? Или хоть что нибудь чтобы воспроизвести баг?
