### ISSUE TITLE
Craters are the wrong texture layer/should not be floor buildable area

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#331]
Building a type of floor on top of a crater texture is often possible, but no visual change is made since crater texture overides the crafted floor texture. 

Either the crafted floor should be visible on top, or no floor should be able to be built on the crater texture. 

http://image.prntscr.com/image/7922d2d25cd9437b825fb0912860ad6e.png

**Comment by jnkyacc** [comment]
Uh. Its possible to make floor over crater but it will be edgy and sharp. "No built zone" will be more appropriate.

**Comment by SmokeyUnicycle** [comment]
Edgy and sharp would be fine in my opinion, it would be annoying to have a meteor make part of your base not able to have floors there.

**Comment by jnkyacc** [comment]
Crater will disappear after some time

**Comment by SmokeyUnicycle** [comment]
Yes they will, but it's after a very long period of time, seems like at least one year.  If it were one season that would be less of a problem.
