### ISSUE TITLE
Robot Trader and Robot Issues (Resolved?)

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#332]
I am using a version from a few weeks ago these issues may be solved already. 

There are several problems with what is otherwise my favorite mod:

-The Robot Trader Ship will often have a trading menu that is the wrong size, so you cannot read what the one item (is there only supposed to be one item?) for sale is. 

-Robot Parts are very very valuable and can be sold for extreme amounts of money out of line with the amount you can make vs the time and materials they take compared to other high tech crafted items.

-The Gardening and Cooking robots do not work, they do not have textures and cannot be activated once built.

**Comment by jnkyacc** [comment]
> -The Robot Trader Ship will often have a trading menu that is the wrong size, so you cannot read what the one item (is there only supposed to be one item?) for sale is. 

Need screenshot.

> -Robot Parts are very very valuable and can be sold for extreme amounts of money out of line with the amount you can make vs the time and materials they take compared to other high tech crafted items.

Fixed.

> 
-The Gardening and Cooking robots do not work, they do not have textures and cannot be activated once built. 

They has some issue with work, but never with textures. Fixed.

**Comment by skyarkhangel** [comment]
its about "Crate". Useless item. As i know fixed and deleted.
