### ISSUE TITLE
Тактический бронежилет Rimarsenal_VestPlate нету в списке рецептов.

### ISSUE THREAD

**Issue by Unlite** [skyarkhangel/Hardcore-SK#3324]
На версии Stable отсуцтвует предмет в списке крафта "Швейной машинки"
![image](https://user-images.githubusercontent.com/7370384/163635748-4ce11b8e-4d76-4829-8604-6d621cb9918d.png)
В древе исследований есть рецепт на этот предмет
![image](https://user-images.githubusercontent.com/7370384/163635820-c06d747a-43d7-4791-bb7e-b87e5ed4cd8a.png)
Даже при помощи поиска "Помощь" я нахожу этот предмет, у него есть рецепт, но нету указанного верстака "Изготавливаеться в:"
![image](https://user-images.githubusercontent.com/7370384/163635979-c65eece4-5024-431b-b927-b8891af3ccd5.png)
Как пример вот как должно быть:
![image](https://user-images.githubusercontent.com/7370384/163636020-011e5ab6-e9ea-4e8c-a8a3-18dedce50770.png)
Пробовал открывать все технологии через режим разработчика но так и не смог нигде найти вератака для этого предмета.
Помимо Stable HSK, и пары модов которые идут по стандарту в комплекте сборки выключинными, никаких других модов не ставил.

**Comment by Unlite** [comment]
Изменил в исходниках тип предмета с `ArmorMedievalSimpleBase` на `ArmorIndustrialBase` и предмет появился в списке крафта
![image](https://user-images.githubusercontent.com/7370384/163650138-e3c95fec-a0c0-4747-ab96-850dfb4e7214.png)

**Comment by ArpoMo6** [comment]
Крафт некоторых предметов доступен только с модом HMC craftable all armors. Тактический бронежилет как раз один из таких предметов

**Comment by Unlite** [comment]
Если бы этого бронежилета не было в списке рецептов исследуемой технологии, то я и не задавал вопросов.
