### ISSUE TITLE
cannot execute incidents, game turns sour

### ISSUE THREAD

**Issue by rifkonz** [skyarkhangel/Hardcore-SK#335]
can anybody help?
downloaded rimworld a14, and harcore sk master, overwrite all. 
first there's "<mindifficulty>2<mindifficulty/> error, then i deleted the line on incidentDefs, incidents_variousBad.xml, start game, works well. 
after i played for awhile i noticed there are very very minimal incidents happened in this game although i choose cassandra on rough, even randy random on rough. but traders and visitors keep coming and after 2 months (in-game time) i only got 3 raids.

so i got curious, turned on development mode, and try to execute incident, then this happened.
![help](https://cloud.githubusercontent.com/assets/22302496/18643908/609c7938-7ed1-11e6-95fe-bd970f31190d.png)

is this a negligible error or something? or is this causing my game to have no incidents?

**Comment by jnkyacc** [comment]
I have no idea why you need to delete something. It should work just fine if installed correctly.
Incidents depends from many conditions like your wealth, map temperature, map condition and so on. Also there is delay between raid incidents.

**Comment by rifkonz** [comment]
if it installed correctly there should be no error logs, right?

**Comment by jnkyacc** [comment]
> if it installed correctly there should be no error logs, right?

nothing game breaking

**Comment by rifkonz** [comment]
i meant years, not seasons, sorry

well, okay then thanks for responding
