### ISSUE TITLE
Why is my interface transparent？

### ISSUE THREAD

**Issue by obama-k** [skyarkhangel/Hardcore-SK#3366]
My interface is transparent and everyone is blue
![1](https://user-images.githubusercontent.com/89937434/175822883-9ca5cb6e-76dc-46c9-8653-9b290ea025e9.png)
![2](https://user-images.githubusercontent.com/89937434/175822888-7a435b3f-f502-4cb4-b097-c999700ead1b.png)

**Comment by pacas** [comment]
Main menu - > Right bottom corner - > Rimthemes button - > Use another theme without transparency. Even from Steam Workshop. Try something from base variants or I can recommend theme Joywire from Steam.

**Comment by Zim777** [comment]
just switch to another theme in rimthemes - in main menu or in game 
![image](https://user-images.githubusercontent.com/46481732/175824070-6d04a31e-0dfc-4353-bdb7-a48dd85c0b68.png)

**Comment by obama-k** [comment]
> 主菜单 - > 右下角 - >边缘主题按钮 - > 使用另一个不透明的主题。甚至来自蒸汽工坊。尝试一些基本变体，或者我可以推荐Steam的主题Joywire。

thank

**Comment by obama-k** [comment]
> 只需在边缘主题中切换到另一个主题 - 在主菜单或游戏中 ![image](https://user-images.githubusercontent.com/46481732/175824070-6d04a31e-0dfc-4353-bdb7-a48dd85c0b68.png)

thank！
