### ISSUE TITLE
Can't make repair kit on the mending workbench

### ISSUE THREAD

**Issue by UnbelievableCat** [skyarkhangel/Hardcore-SK#337]
Bill is empty and throw exception 

![rim](https://cloud.githubusercontent.com/assets/22303350/18645463/fa43966e-7eb5-11e6-8bce-8969083dfc2f.png)

**Comment by jnkyacc** [comment]
Repair kits can be made on ElectricSmithy or FueledSmithy at this moment.

**Comment by skyarkhangel** [comment]
Ok. Soon fix.

**Comment by skyarkhangel** [comment]
Fixed in next update.
