### ISSUE TITLE
Bug with SOS2 when fishing

### ISSUE THREAD

**Issue by Buyue-z** [skyarkhangel/Hardcore-SK#3376]
There defiantely seems to be a compatibility issue with SOS2,leading to not catching any fish. It seems fish may be over written.

**Comment by sidfu** [comment]
its a known issue.. for now if you want to use sos2 and HSK then get the VE fishing then disable when you dont usue SOS2. VE fishing works fine as a replaement just adjust the settings a bit.

**Comment by AndreiAvinov** [comment]
The fix is in pull requests https://github.com/skyarkhangel/Hardcore-SK/pull/3362, the guys just wait for Sky to approve it since it has core modifications in it
