### ISSUE TITLE
Enemy throw grenades without limit

### ISSUE THREAD

**Issue by Buyue-z** [skyarkhangel/Hardcore-SK#3378]
When the enemy throws a grenade, he will first aim with a gun and then throw the grenade, but the number of grenades in the backpack has not decreased, including burning grenades and high explosive grenades.

Uploading 2022-07-15 11-16-05_Trim.mp4…

**Comment by Buyue-z** [comment]
there is no bug if enemy only carry grenades.

**Comment by Spaniard829** [comment]
Any additional mods enabled or only those included in HSK?

**Comment by Buyue-z** [comment]
> Any additional mods enabled or only those included in HSK?
no other mod except rimhub

**Comment by Buyue-z** [comment]
> Any additional mods enabled or only those included in HSK?
no other mod except rimhub.

**Comment by Buyue-z** [comment]
> Any additional mods enabled or only those included in HSK?

no other mod except Rimhub.
