### ISSUE TITLE
Mineral Sonar.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#338]
Я возможно что-то сильно путаю, конечно, но я с годмодом каждую вкладку просмотрела, но так и не нашла в списках чертёж для него, хотя по идее он в MISC должен быть.

**Comment by jnkyacc** [comment]
Убран.

**Comment by skyarkhangel** [comment]
Да убрали его, проблема с ним на а14, а руки до него не доходят. Тем более в а15 на половину становится бесполезным :(

**Comment by skyarkhangel** [comment]
Closed.
