### ISSUE TITLE
Enemy not take the initiative to attack

### ISSUE THREAD

**Issue by Buyue-z** [skyarkhangel/Hardcore-SK#3389]
In the course of the game, it often happens that the enemy troops wait in place for several days and die of malnutrition, and there is __"**Exception while ticking lord with job SkyMind.LordJob_StageAttack: 
System.NullReferenceException: Object reference not set to an instance of an object**__
" in the debug log...So I think it may be a bug.

**Comment by sidfu** [comment]
The ai is still a work in progress so issues  do come up. take and post a hug log that way they can look to see if any other mods might be interacting  with them.
you can try to fix yourself by dev down them. then unpause game for afew sec then  heal them. this usualy  resets the ai.

**Comment by Buyue-z** [comment]
> The ai is still a work in progress so issues do come up. take and post a hug log that way they can look to see if any other mods might be interacting with them. you can try to fix yourself by dev down them. then unpause game for afew sec then heal them. this usualy resets the ai.

Thanks for your advice. After I closed "Enable leader gathers troops near colony" in skyai mod, the attack became normal.
