### ISSUE TITLE
Fueling System. Again.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#339]
Я не знаю зачем так было делать, но у меня теперь на всём, что потребляет топливо при помощи топливной системы, кроме костров, внутренняя температура отрицательная, и колонисты отказываются каким либо образом взаимодействовать с ними, кроме заправки. То есть если правой кнопкой нажимать на стол, менюшка даже не появляется. Повышение температуры в комнате также не влияет ни коим образом на внутреннюю температуру агрегата.

http://imgur.com/a/7ABsd

**Comment by skyarkhangel** [comment]
Ок, проверю.

**Comment by skyarkhangel** [comment]
Готово. Кое-что упустил, спасибо поправил. Система заправки стала намного умнее. Теперь она проверяет на наличие заданий. Если есть задания, то начинает повышать температуру до рабочей. Соответственно убрав все задания, строение постепенно перейдет в режим экономии. Но до тех пор пока не наберется рабочая температура, работать со строением будет нельзя.

**Comment by jnkyacc** [comment]
> Если есть задания, то начинает повышать температуру до рабочей. Соответственно убрав все задания, строение постепенно перейдет в режим экономии. 

Сомнительное улучшение имхо. Теперь билл "делать пока не будет Х" - будет жечь дрова пермаментно. Плюс совершенно не понятно кто ее растапливает если дворфы к ней не подходят....

**Comment by skyarkhangel** [comment]
Мне говорили что до этого апдейта, расход ресурсов на рефуел верстаках был очень низкий, теперь будет немного выше.
Можно потом будет заморочится и сделать отдельную работу, раз так хотите "растопить" и "погасить".  Только это еще увечит время до начала работы.

**Comment by Inei** [comment]
А можно тогда к агрегатам таймер какой-нибудь прикрутить, чтобы они по ночам не работали и ресурсы не жгли?

**Comment by WaytobeGlad** [comment]
С т.з. формальной логики ничто не мешает подбрасывать в костер топливо из поленницы рядом (тем более что костер, судя по требуемым ресурсам, - уже вполне себе мини - печь) или же не делать этого точно так же, как с кузнечной печью. То есть если встать на путь унификации, то или печь должна потреблять топливо регулярно, или костер - по запросу. Принципиальной разницы между тем и другим лично я не нахожу.
А вот таймеры - это для ленивых ☺️  впрочем, для пущего реализма можно попробовать реализовать управление топливом в менеджере колонии.

**Comment by WaytobeGlad** [comment]
В идеале я бы увеличил цифры энергозатрат во время работы станков на все виды топлива, а траты топлива во время простоя снял.
Впрочем, система и на текущий момент вполне неплоха.

**Comment by skyarkhangel** [comment]
Добавим еще выключатели.

**Comment by skyarkhangel** [comment]
Obsolete, the problem with the old refuel system.
