### ISSUE TITLE
[1.3] Re-re-request for separating darkness event from core

### ISSUE THREAD

**Issue by SergeyPomelov** [skyarkhangel/Hardcore-SK#3394]
It's returned and happens often now. It's not just my luck; the Vile Darkness Apocalypse deemed as a quite ordinary event in configs. I won't repeat the arguments, see one of the previous issues. It's almost as annoying as deadly version of SARS but happens more often and ought to be removed despite somebody likes it so much and really shoves it into a player's face. And in beta still no way to switch it off without dev mode or configs. 
https://github.com/skyarkhangel/Hardcore-SK/issues/627

**Comment by sidfu** [comment]
darkeness event can be disabled your next game. its not a mandatory mod.  till then you can either use  incident tweaker and disable it or open the mod and set the chance to 0.
as for the disease its all rng and biome. some biomes have more disease chance than others means a greater chance of any disease.
the more deadly diseases like sars is actually  rare but can seem overtly common if your on a biome that has  higher chance.
temprate can be considered in the middle of disease chances and it goes down on colder biomes. hotter biomes tend to have greater chance of diseases.

**Comment by SergeyPomelov** [comment]
Should incidents tweaker be available in 1.3? I didn't found it in mode settings and thought it isn't added to dev. branch yet.

**Comment by SergeyPomelov** [comment]
Also - the darkness just ignores end current condition from dev menu.

**Comment by SergeyPomelov** [comment]
Still ignores. Just unnoying, forgot to fix configs after update again, ended restarting the colony (had no saves where it isn't planned).

**Comment by SergeyPomelov** [comment]
Don't think this is fixed, won't check every devignored issue every time because of brainless repeating bot's staleness mark.

**Comment by AndreiAvinov** [comment]
Dev mode fixes and support is something in the end of the imaginary priority list. Darkness is a separate mod now so the main issue is solved now.

**Comment by masakitenchi** [comment]
Close as completed.
