### ISSUE TITLE
[1.3] Animals and quarantine

### ISSUE THREAD

**Issue by kozachok3000** [skyarkhangel/Hardcore-SK#3397]
With new animal mechanics and epidemics with diseases like plague and flu, there is no way to quarantine animals. I cannot assign a special animal to a special barn. Animals ignore zones in one barn, and colonists also ignore zones when they distribute animals between two barns. There must be a way to quarantine or disable epidemics for animals without crutches and inventing the wheel.

**Comment by TheLoneTec** [comment]
until something simular is added, you can use the following for now. https://steamcommunity.com/sharedfiles/filedetails/?id=2558978295&searchtext=pen+filter. Has things not just for sick but managing animals, such as animals who need to be unloaded from a caravan, to malnourished, and others.
