### ISSUE TITLE
Prisoner events breaking

### ISSUE THREAD

**Issue by Masquerine** [skyarkhangel/Hardcore-SK#34]
Reposting a forum comment here so it won't get buried. Link shows error messages. 
User "Lude" wrote:

I also have a bug to report

http://pastebin.com/tGmnLUvm

It's basically prisoners trying to kill each other/go berserk, it throws a few thousand exceptions until it hangs and memory leaks (about 0.3 megabyte per second, oh wait that's probably just the log)
force recruiting/killing the culprit just makes the next best prisoner try to find an excuse to go berserk and hang the game (at first I thought it was an incident, since very few incidents/races cause a short hang before starting)

if a prisoner has a shield and goes berserk, tries to attack anything, it crashes on my end

**Comment by skyarkhangel** [comment]
Ok. Bug with shields fixed some days ago :)
