### ISSUE TITLE
Antis, Gnawler and Insect meat.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#340]
Поскольку пища приготовленная из данных типов мяса даёт серьёзные дебафы к настроению, было бы неплохо убрать их из рецептов по умолчанию - как человеческое и прочее мясо, поскольку на данный момент приходится вручную их отключать при создании каждого рецепта.

**Comment by WaytobeGlad** [comment]
Согласен, это актуальный запрос.

**Comment by Inei** [comment]
Вы немножко не то сделали, там теперь у москитов, например, мяса вообще нет, также как и у крашбагов, а у тех насекомых, у которых есть, то есть и у скорпионов, и фералисков и у терраморфов - оно просто называется "Insect meat". А его вы как раз не добавили.

**Comment by Jalordon** [comment]
An addition to this issue, each type of insect meat in a cooked food item will contribute to the 'ate cooked insect meat' negative mood. Try getting a stack of meals with multiple insect meats and have a colonist eat one. They will get x3 penalty for insect meat.

**Comment by skyarkhangel** [comment]
Fixed.
