### ISSUE TITLE
Kiln not usable

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#341]
Pawns don't bother to fuel kiln.  Also, can't manually refuel anything.

**Comment by skyarkhangel** [comment]
update to latest. Already fix this issue. Can't to manually add bill for refuel until full rework refuel bill. I can't say when it will be. Such a lot of work needed.

**Comment by Vigilence** [comment]
Didn't check update, will do now.  Thanks.
