### ISSUE TITLE
The problem was noticed with the Genetic rim expander mod.The right mouse button does not work, the game is paused.What's wrong?

### ISSUE THREAD

**Issue by Kek1234567890** [skyarkhangel/Hardcore-SK#3414]
The problem was noticed with the Genetic rim expander mod.The right mouse button does not work, the game is paused.What's wrong?
Could not find type named GeneticRim.DefExtension_Hybrid from node <li Class="GeneticRim.DefExtension_Hybrid"><dominantGenome>GR_UrsineGenetic</dominantGenome><secondaryGenome>GR_RodentGenetic</secondaryGenome></li>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.DirectXmlToObject:ClassTypeOf<Verse.DefModExtension> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ObjectFromXml<Verse.DefModExtension> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ListFromXml<Verse.DefModExtension> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ListFromXmlReflection<Verse.DefModExtension> (System.Xml.XmlNode)
Verse.DirectXmlToObject:ObjectFromXml<System.Collections.Generic.List`1<Verse.DefModExtension>> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXmlReflection<System.Collections.Generic.List`1<Verse.DefModExtension>> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXml<Verse.PawnKindDef> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXmlReflection<Verse.PawnKindDef> (System.Xml.XmlNode,bool)
(wrapper dynamic-method) Verse.DirectXmlLoader:Verse.DirectXmlLoader.DefFromNode_Patch2 (System.Xml.XmlNode,Verse.LoadableXmlAsset)
(wrapper dynamic-method) Verse.LoadedModManager:Verse.LoadedModManager.ParseAndProcessXML_Patch1 (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by Zim777** [comment]
Do you have the patch for HSK (if it exist of course) for this mod?
If not you ask the author of this mod

**Comment by Kek1234567890** [comment]
Thanks
