### ISSUE TITLE
1.4 Баг с разборкой вещей

### ISSUE THREAD

**Issue by SadOrange972** [skyarkhangel/Hardcore-SK#3444]
Не разбираются вещи на текстиль, в обычном верстаке кожевника. Вещи можно разобрать на ткатском станке, но они разбираются в воздух, ничего не падает с уничтоженной вещи.

**Comment by TheLoneTec** [comment]
Пока не обновится ветка 1.4, можно использовать форк. Там эта проблема исправлена.
