### ISSUE TITLE
cannot execute incidents, my pawns are stunned

### ISSUE THREAD

**Issue by nighelt** [skyarkhangel/Hardcore-SK#345]
I hope you can help me, but it appeared a really annoying bug.
Long story short, my pawns are stunned as soon as this incident tries to spawn, I tried to send forth the time but remain stunned until his death.

Storyteller: Sadistic Sereniz

Thank you in advance for the help

![screenshot_3](https://cloud.githubusercontent.com/assets/22324671/18676577/5cc9cfce-7f56-11e6-8073-9c79f2a878bf.png)

**Comment by skyarkhangel** [comment]
version?

**Comment by Inei** [comment]
I had that event in one of the latest versions, not so long ago. Though, I am playing Hildegarde Epic, and stun have passed in an hour or so.

**Comment by nighelt** [comment]
I'm playing on the penultimate version of github

**Comment by nighelt** [comment]
Even wait an hour bug recurs periodically (tested on another save with the same problem), now springs to mind the question of what comes this bug?
And there is a way around the bug and retrieve the save?

**Comment by skyarkhangel** [comment]
I suppose, fixed today.

**Comment by nighelt** [comment]
Unfortunately, the bug persists even with the new version of modpack (github version).
Storyteller always the same ...
Now I wonder whether it is not really a problem relegated to the storyteller Sadistic Sereniz ; and
there is perhaps a way to disable that specific event?

![screenshot_5](https://cloud.githubusercontent.com/assets/22324671/18883913/7b8f6560-84e5-11e6-8867-3d6db0df33c0.png)

**Comment by skyarkhangel** [comment]
Fixed
