### ISSUE TITLE
Падение производительности игры 1.4

### ISSUE THREAD

**Issue by SadOrange972** [skyarkhangel/Hardcore-SK#3456]
При выборе пешки происходит падение фпс, до 20-25 и ТПС в район 34-40. Если пешек не трогать, то фпс находится в районе 170, а ТПС, видимо, залочен на 60 так-как выше и ниже не скачет совершенно. Можно ли с этим что-то сделать?

**Comment by TheLoneTec** [comment]
Падение tps может быть вызвано явным переносом предметов, так как теперь можно выбирать удерживаемые предметы. Возможно слишком часто запускается проверка, проверю. Тем не менее, tps не должен быть заблокирован, я получаю 900, используя скорость 4. tps заблокирован в зависимости от скорости игры.

**Comment by SadOrange972** [comment]
Могу ли я, скинуть вам, скриншоты проблемы?

**Comment by TheLoneTec** [comment]
конечно, было бы неплохо иметь больше информации, например, ваш журнал Huglib, так как в нем будет ваш список модов, а также любые ошибки.

**Comment by SadOrange972** [comment]
[Player.log](https://github.com/skyarkhangel/Hardcore-SK/files/10268225/Player.log)

**Comment by TheLoneTec** [comment]
ваша ссылка Hugslib была бы лучше. откройте журнал ошибок и нажмите зеленую кнопку, чтобы создать журнал Hugslib. и киньте сюда ссылку.

**Comment by TheLoneTec** [comment]
на самом деле глядя на ваш player.log, похоже, что вы настроили его неправильно. Я рекомендую удалить всю папку Mods, загрузить последнюю альфа-версию и переустановить ее с ModsConfig.xml, который также предоставляется.

**Comment by SadOrange972** [comment]
Понял спасибо

**Comment by TheLoneTec** [comment]
Это также должно быть улучшено в последней альфе. Простое личное оружие вызывало графическую нагрузку на игру, которая его создала. Это было исправлено.
