### ISSUE TITLE
Пистолет стреляет стрелами. 

### ISSUE THREAD

**Issue by Majk-V** [skyarkhangel/Hardcore-SK#3459]
Версия: 1.3.3389 (64-bit), от 2022.12.18 11:35:12. Установка стандартная, без дополнительных модов и изменений в предустановленных.

Во время охоты у пешки "износился окончательно и рассыпался в прах" рекурсивный лук. Автоматически оружие сменилось на пистолет Sphinx AT 2000, однако при выстрелах по-прежнему тратились стрелы от лука. После первого удачного попадания по цели (Кабан) пистолет переключился на патроны.

**Comment by TheLonerD** [comment]
Урон был как от стрел или чисто визуал поменялся? Звук "выстрела" какой был?

**Comment by Majk-V** [comment]
Урона не было, пешка не попадала по цели. В руках был отрисован пистолет (анимация пистолета), звук был как от стрел. После первого попадания по цели звук поменялся на выстрелы.
