### ISSUE TITLE
Метеоритные дожди и т.д.

### ISSUE THREAD

**Issue by Zloooo** [skyarkhangel/Hardcore-SK#3460]
(1.4) Все что падает с неба, больше не оставляет на земле метеоры или металлолом в виде останков.

Падающие останки кораблей, капсул работают все так же правильно.

**Comment by Zloooo** [comment]
+ фугасные гранаты, багуются пешками при поднятии, они берут их и кладут по несколько раз сразу и оставляют лежать и так до бесконечности. (ставлю приказ на перенос в точку, к переработки у кузницы, с этим справляются)

**Comment by Zloooo** [comment]
newRatkinPlus рюкзаки, мешки используют параметр - "Грузоподъёмность", этот параметр не работает, должен быть параметр "переносимый вес"

**Comment by Zloooo** [comment]
При съедании пиццы, нет никакого положительного бафа на настроение, типо "съел шикарное блюдо", хотя рецепт последнего уровня сложности.

**Comment by Zloooo** [comment]
AssortedTweaks

Если в этом моде включить "Мясные ингредиенты", то игра ломается и пешки перестают кушать, пока не заставишь принудительно.

**Comment by Zloooo** [comment]
Рецепт приготовления "мясного супа х4" на поите шеф-повара, вместо 4 делает 12

**Comment by RogeVenham** [comment]
> Рецепт приготовления "мясного супа х4" на плите шеф-повара, вместо 4 делает 12

Тут всё правильно, т.к. простой (не x4) производит 3 шт., 3*4=12

**Comment by RogeVenham** [comment]
> При съедании пиццы, нет никакого положительного бафа на настроение, типо "съел шикарное блюдо", хотя рецепт последнего уровня сложности.

Пицца даёт баф на уменьшение боли, увеличение метаболизма и сознания
Я думаю на счёт шикарного блюда перебор... Будет конечно хорошо, но на сколько балансно?)

**Comment by TheLoneTec** [comment]
> 

это должно быть исправлено в последней версии.

**Comment by TheLoneTec** [comment]
> AssortedTweaks
> 
> Если в этом моде включить "Мясные ингредиенты", то игра ломается и пешки перестают кушать, пока не заставишь принудительно.

это должно быть исправлено в последней версии.

**Comment by TheLoneTec** [comment]
> При съедании пиццы, нет никакого положительного бафа на настроение, типо "съел шикарное блюдо", хотя рецепт последнего уровня сложности.

У пиццы есть свой Хедифф. Что дает еще одно преимущество.

<defName>ХадПицца</defName>
<label>съел пиццу</label>
<description>Я съел вкусную пиццу с таким количеством ингредиентов, что чувствую, как мои кости становятся крепче.</description>

**Comment by TheLoneTec** [comment]
> Рецепт приготовления "мясного супа х4" на плите шеф-повара, вместо 4 делает 12

Это правильно, это в 4 раза больше обычного количества рецепта. По одному рецепту получается 3 супа.

**Comment by TheLoneTec** [comment]
> newRatkinPlus рюкзаки, мешки используют параметр - "Грузоподъёмность", этот параметр не работает, должен быть параметр "переносимый вес".
> 
> У обычного человеческого рюкзака, такого параметра вообще нету, было бы справедливо добавить 20 "переносимый вес", что аналогично обычному рюкзаку раткинов.

исправлено в этом запросе на вытягивание - https://github.com/skyarkhangel/Hardcore-SK/pull/3482

**Comment by TheLoneTec** [comment]
> (1.4) Все что падает с неба, больше не оставляет на земле метеоры или металлолом в виде останков.
> 
> Падающие останки кораблей, капсул работают все так же правильно.

я не уверен, что вы имеете в виду, у меня это работает, есть разные типы метеоров, те, которые просто наносят урон, круглые, которые вы можете добывать для ресурсов, а затем те, которые оставляют пригодные для добычи залежи.

**Comment by Zloooo** [comment]
> > (1.4) Все что падает с неба, больше не оставляет на земле метеоры или металлолом в виде останков.
> > Падающие останки кораблей, капсул работают все так же правильно.
> 
> я не уверен, что вы имеете в виду, у меня это работает, есть разные типы метеоров, те, которые просто наносят урон, круглые, которые вы можете добывать для ресурсов, а затем те, которые оставляют пригодные для добычи залежи.

Это не работало на версии pre-alpha, сейчас же работает корректно, причем это поправилось обновлением вашего интегрированного мода, какого именно не знаю)

По поводу бафа пиццы настроения +6. Все блюда которые готовятся из четырех ингредиентов, его дают, помимо бафов в листе здоровья. например кебаб, чизбургер. все же не справедливо к пицце)

**Comment by TheLoneTec** [comment]
Я вижу, я добавлю это тогда

**Comment by TheLoneTec** [comment]
нашел проблему, в ней отсутствовал <tasteThought>AteLavishMeal</tasteThought>
