### ISSUE TITLE
Pet Follow (mod)

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#347]
From what I've read in the Pet Follow thread the mod hasn't been working for quite some time with hardcore sk. Is there a workaround? 

Currently my pet just does what it wants and doesn't help even during attacks. If I remember correctly then even in Rimworld vanilla the pets would help during attacks/draft mode.

**Comment by Vigilence** [comment]
Yeah, pet follow doesn't work atm.  A month or so ago they were at least draftable.  Currently pets you start out with don't have any of the pet follow options, and pets you get later on only have the options available when you select them.

**Comment by Inei** [comment]
For me it works somewhat odd. When I disallow it to follow me (big red cross on follow icon) - it actually follows, while stays at home when there is no cross. Same with hunting and taming.

**Comment by skyarkhangel** [comment]
Fixed.
