### ISSUE TITLE
Newest build replaces water with sand!

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#348]
How can I go fishing now? :(

![screenshot 84](https://cloud.githubusercontent.com/assets/16742086/18681692/2e2990e2-7f37-11e6-9753-1d92790bcf32.png)

![screenshot 85](https://cloud.githubusercontent.com/assets/16742086/18682360/f31b1c7a-7f39-11e6-9471-29b9569cabe7.png)

**Comment by skyarkhangel** [comment]
О_О ok

**Comment by skyarkhangel** [comment]
how to reproduce?

**Comment by Vigilence** [comment]
I can upload save file.


https://www.bigfile.to/file/XjzJ56jkXumj/Autosave-4.zip

**Comment by xwat** [comment]
+1. Only for me it replaced not water, but all swampy land into sand.

**Comment by skyarkhangel** [comment]
Fixed
