### ISSUE TITLE
1.4 Alpha Branch; 12 Gauge Buck Ammo Recipe Is Free

### ISSUE THREAD

**Issue by Szara-ManOfHonor** [skyarkhangel/Hardcore-SK#3480]
The recipe to craft 12 gauge buck shells `<defName>MakeAmmo_12Gauge_Buck</defName>` is material free, and requires no ingredients at all. Not sure how. The recipe structure in the xml looks fine, I compared it to a recipe that works (the bird shell one), and the differences were as expected. I verified the problem with only the mods in the provided modconfig.xml. My modset is up to date with the Alpha branch as of now, up to and including PR #3477 

https://i.gyazo.com/8429b6356ad0cdc18ebc95775ef56fef.png

**Comment by TheLoneTec** [comment]
I cannot recreate this issue, make sure you dont have a mod effecting the recipe.

**Comment by Szara-ManOfHonor** [comment]
> I cannot recreate this issue, make sure you dont have a mod effecting the recipe.

Like I said, I am using the provided modconfig.xml, and thus only have the modpack mods loaded.
Since it wasn't reproducible I did a clean install of Rimworld and the modpack, which fixed it. I suspect some old config files must have somehow been responsible.
