### ISSUE TITLE
Испарительный охладитель (идея)

### ISSUE THREAD

**Issue by RogeVenham** [skyarkhangel/Hardcore-SK#3487]
Сделать аддон к Dubs Bad Hygiene, который позволил бы перезаправлять испарительные охладители водой, а не древесиной.

Готовь задонатить 10$ за это дело :)

**Comment by TheLoneTec** [comment]
это уже опция в настройках мода Dybs Bad Hygiene

**Comment by TheLoneTec** [comment]
также варианты поддержки rimatomics и rimefellar.

**Comment by RogeVenham** [comment]
> это уже опция в настройках мода Dybs Bad Hygiene

Спасибо большое, не увидел, атом и феллер настроил, а это не углядел :)
