### ISSUE TITLE
Colonist will not sow certain crops

### ISSUE THREAD

**Issue by Vandenberg** [skyarkhangel/Hardcore-SK#349]
All requirements are met (seeds, skill, research) but my colonist won't plant certain seeds (eggplant, pumpkin, gooseberry, lettuce). However will sow cereals such as wheat and oats.

**Comment by Vulpes-Inculta** [comment]
Soil fertility requirement?

**Comment by Vandenberg** [comment]
You are right! I thought soil couldn't be more fertile than 100%. Turns out I need tilted soil. Good catch!

**Comment by Vulpes-Inculta** [comment]
Had the same "problem" myself when I first started Hardcore mod :)
