### ISSUE TITLE
Bug: Recent change to handheld tools

### ISSUE THREAD

**Issue by Goikoa** [skyarkhangel/Hardcore-SK#35]
Hammer, pickaxe, and handaxe.

They dropped but I received this debug.

Picture:
http://i.imgur.com/lGkxrJ6.png

**Comment by Goikoa** [comment]
More information:

After making a colony the tools still drop.
The characters can still hold the tools.
The characters can still use the tools. 

For some reason they'd bug and stand still after completing a task.
An example: Command builder equipped with a hammer to build a bed spot. Builder builds the structure for the bed and then he stands in one spot. Command Builder to finish the bed. He completes the bed. Then he stands still again. Drop the hammer. Builder goes back to normal, not bugged. Very odd behavior. 

Please fix.

**Comment by skyarkhangel** [comment]
Ok

**Comment by Goikoa** [comment]
Also, if your pawn cuts a tree without being equipped with a handaxe wood logs will not drop. I am unsure if this is intentional or a bug.

I like how you can make tools from different materials now.

**Comment by Masquerine** [comment]
This seems to have been fixed with the changes I made. Not getting any errors with hammer/handaxe/pickaxe equipped of various material types.
