### ISSUE TITLE
Fish recipes: where?

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#351]
There are no fish recipes at neolithic.

![screenshot 93](https://cloud.githubusercontent.com/assets/16742086/18691448/b1f66ea2-7f61-11e6-8d6b-725029d3892c.png)
![screenshot 92](https://cloud.githubusercontent.com/assets/16742086/18691449/b1fa82a8-7f61-11e6-91ad-65f39825c2c3.png)

**Comment by Inei** [comment]
You need to research "Fishing I" in order to be able to gut fishes into cook-able pieces.

**Comment by Vigilence** [comment]
Thanks Inei.

I researched Fishing I.  What I am asking about is the food recipes for fish and the like.  Roasted meat and jerky seems a bit lame.

**Comment by Inei** [comment]
Well, it's jerky fish, and roasted fish, and fish with potatoes if you like. Just use some imagination. ^^

**Comment by Vigilence** [comment]
Yeah :)

**Comment by Vigilence** [comment]
I checked roasted meat and jerky, I can't use any of the fish in them.

**Comment by skyarkhangel** [comment]
ok
