### ISSUE TITLE
Egg recipes: Where?

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#352]
There are no egg recipes.  For one of the most abundant animal food products, this needs a fix.

They also can't be used to make kibble due to a bug.

They should have individual recipes as well as recipes where they are ingredients.  They should also be included in fried assort's and other similar recipes.

![screenshot 96](https://cloud.githubusercontent.com/assets/16742086/18691507/0c147618-7f62-11e6-9269-7b5b78f3d1cc.png)
![screenshot 95](https://cloud.githubusercontent.com/assets/16742086/18691506/0c14341e-7f62-11e6-9bb9-96b3f294f42a.png)
![screenshot 94](https://cloud.githubusercontent.com/assets/16742086/18691508/0c1537b0-7f62-11e6-89e2-0baa00375f1e.png)

**Comment by skyarkhangel** [comment]
Eggs - its a Animal Raw Product and has parent category "raw meat". For default Fertilized eggs added to exception. Unfertilized eggs used like a meat.

**Comment by Vigilence** [comment]
It's not usable in recipes that require eggs such as kibble.
