### ISSUE TITLE
Is the klin/furnace meant to consume fuel even when not in use?

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#353]
I have toggled them off, but It's just burning through the entire reserve it has stored up inside of it.

I am using github version  (Merge pull request #350 from ochkoebanoe/master) commit 949d6e98a5b948af00282d60a462a6c4564832fd

**Comment by jnkyacc** [comment]
When you have active bill - table will consume fuel to maintain working temperature.

**Comment by zakhad** [comment]
Oh interesting... So craft until you have X will always make said machine active even though you don't have the crafting matts?

**Comment by jnkyacc** [comment]
Exactly. We discussed this matter already - some code limitations. 
You can try Crafting Hysteresis (need activate manually in mods) it will little help with bills like "do until X".

**Comment by skyarkhangel** [comment]
i'll check flickable comp.

**Comment by skyarkhangel** [comment]
Fixed today.
