### ISSUE TITLE
Production site lose Room property

### ISSUE THREAD

**Issue by olizit** [skyarkhangel/Hardcore-SK#354]
Some Production site like Hand Sawmill, Furnace and Kiln lose Room location property. Building_WorkTable::GetRoom() method return null.
Below a screenshot with a room.
Left column show some KO production site and right column show some OK production site.
![image](https://cloud.githubusercontent.com/assets/13608719/18720118/9ef91d62-802a-11e6-8753-d237eaa5ebe5.png)

**Comment by skyarkhangel** [comment]
ok. Thank you, need to check :)

**Comment by olizit** [comment]
Cool ! I dug a little bit but I don't find which mods add Hand Saw Mill production site.
