### ISSUE TITLE
Klin/Furnace Resetting colour upon reload.

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#355]
http://imgur.com/nIqK4zV

I have claybrick Klin/Furnace which are a orange/brown/tan colouration but they reset to default skin? e.g. white marble or limestone coloured furnace when reloaded.

**Comment by skyarkhangel** [comment]
In latest update, changed shader type for this buildings.

**Comment by skyarkhangel** [comment]
Fixed
