### ISSUE TITLE
Hurricane should increase grass and tree seed range dramatically

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#356]
During a hurricane, the default range for grass and tree seeds should be increased dramatically.  Normally once an area has been destroyed by fire there is no way for anything to grow back unless you assign a pawn to start farming there.  

This can be fixed by increasing grass and seed range during hurricane weather.

**Comment by skyarkhangel** [comment]
this will require to detour plant seed generator. I think this isnt a significant feature to Rimworld.
