### ISSUE TITLE
Colonists won't refuel things.

### ISSUE THREAD

**Issue by Rufert** [skyarkhangel/Hardcore-SK#357]
I've had this problem with the Steel grill, fuel cooking stove, and the first available fueled heater.
They just won't fuel it, trying to force it by right clicking on the station doesn't bring up the manual refuel option, even with a colonist that has every job. There is plenty of kindling and it is allowed. 
I've had it work sometimes, but suddenly they decide they won't do it from then on, rebuilding the station does nothing. 
Unless I'm missing something it'll be unplayable until this is fixed.

Edit: Like Virginace said down below, having a dedicated hauling pawn fixes it. However disallowing kindling also sorted it it seems.

**Comment by Vigilence** [comment]
If you have the latest build you can no longer right-click and force a pawn to refuel.  Not sure why that was taken out since it was helpful. 

You will need a pawn that is dedicated to hauling and hauling only for it to refuel your items.

**Comment by WaytobeGlad** [comment]
That was excluded due to some tech trbls, that cannot be fixed asap. Suppose, that's just a matter of time, however hauling is our salvation at the moment...

**Comment by skyarkhangel** [comment]
Fixed
