### ISSUE TITLE
Problem with operations

### ISSUE THREAD

**Issue by 4inur** [skyarkhangel/Hardcore-SK#358]
Hi, have a weird problem,  in 17 of my 20 colonist i can install only simple prohestetic arms and legs and harvest/amputate anything(well one of them let my replace his Lost kidney, but all that peoplee without nose or hand...) , with the other 3 no problem with any type of operation.

I have all de medicine and hospital research till bionics and only Hell Effect mod pack installed( with the ModsConfig.xml of the rar)

Thanks for your time and excelente modpack

**Comment by 4inur** [comment]
And sorry for my english :V

**Comment by jnkyacc** [comment]
Probably you using old version.

**Comment by 4inur** [comment]
Rimworld 14.1249, i think correct version for Hell Effect no?

**Comment by jnkyacc** [comment]
I mean Hardcore version. If you get it from mega or similar then its outdated, if you using github version then probably i will need your save game.

**Comment by 4inur** [comment]
Oh, ok thanks, think i have github versión but gonna try redownload, if problems still how i can send my save??
Another time thankyou

**Comment by Vanguard01** [comment]
Similar problem as 4inur, using hcsk 0.14.1249
rev 874 with Rimworld 14.1249. I have a colonist who has lost a hand and the opposite arm and im unable to replace the hand with a hook or the lost arm with a metal arm. On another colonists i was able to replace a lost leg with a peg and another lost leg with a bionic leg at roughly medieval tech level. Even after enabling dev mode and researching all techs im still unable to do a simple replace hand with hook surgery or replace the arm. (save is before i researched all techs) 

[Archangel.zip](https://github.com/skyarkhangel/Hardcore-SK/files/487883/Archangel.zip)

**Comment by jnkyacc** [comment]
If you will install github version on outdated it will not load your save.

> send my save??

use github.
C:\Users\USERNAME\AppData\LocalLow\Ludeon Studios\RimWorld\Saves

**Comment by 4inur** [comment]
Ok, sorry for my noobness :V i'm now in phone, Tomorrow try to create a new colony with github version, if problem persist send the save, or the two saves.thnx

**Comment by jnkyacc** [comment]
@Vanguard01 pawns names with problems and which ok

**Comment by Vanguard01** [comment]
After some testing all colonists are the same, organs appear to be unable to be replaced by operation, the option to do the operation is not in the list of operations (with full tech and spare organs to install). Legs are fine but operations for replacing hands and arms are missing as well, same for eyes though jaw and brain chip operations are available.

**Comment by jnkyacc** [comment]
![screenshot70](https://cloud.githubusercontent.com/assets/20729235/18761046/b33d0a98-8103-11e6-88d9-089734266f1a.png)

**Comment by Vanguard01** [comment]
Strange, still dont see any of the arm operation options, ill try a fresh rimworld/hcsk install and see if that resolves it.

**Comment by Vanguard01** [comment]
After a fresh install i was still getting the problem of missing surgeries, I looked on the EPOE forums and saw someone else had conflicts with the zombie mod causing the same thing, headed back here and saw your update. Removing zombie mod worked, all operations are back on a fresh game.

**Comment by jnkyacc** [comment]
@Vanguard01 thx. That what I thought. Will try fix zombie mod soon.
