### ISSUE TITLE
Textures compression >(

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#359]
Я все понимаю уменьшить место, меньше оперативки... НО
![screenshot66](https://cloud.githubusercontent.com/assets/20729235/18754581/7449f50e-80e9-11e6-88ba-9e55c2a87376.png)
![screenshot70](https://cloud.githubusercontent.com/assets/20729235/18754585/79171e22-80e9-11e6-9957-8105babfb53c.png)
![ы](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Textures/Terrain/Surfaces/Marshnew.jpg?raw=true)
Последняя вообще слов нет... пальцем мылили?
Если уж заменяете ванильные то делайте это пожайлуста КАЧЕСТВЕННО. Или отдельную ветку с ~~НД~~ нормальными текстурами.
![l308akbu0ke](https://cloud.githubusercontent.com/assets/20729235/18755146/4df00b30-80eb-11e6-89ac-54a35fe6eef0.jpg)

**Comment by ochkoebanoe** [comment]
Плюсую за ветку без сжатия.

 <img src="https://i.gyazo.com/4fba703d3496af026e788fa6f4a005d8.png"/>

**Comment by skyarkhangel** [comment]
Выложил в отдельную папку не сжатые текстуры, буду пополнять.
