### ISSUE TITLE
Glowstone lamps do not deplete

### ISSUE THREAD

**Issue by xwat** [skyarkhangel/Hardcore-SK#364]
The 'fuel' always stays at max lvl. 
I suggest to do one of the following:
1)Either remove 'fuel' and allow for free light without electricity
2)Fix the depletion

**Comment by xwat** [comment]
Actually, in CuproPanda's version, they don't intend to be depleteable. 
Current fuel system requires stuff to burn. Glowlamps in their def still rely on old one. Not sure how these glowstones would burn -- sounds pretty strange.
However, I am a bit hesitant to create a free source of light.
Maybe with increased cost and after some research Prereq?

Any thoughts, Sky & Comminity?:)

**Comment by Vigilence** [comment]
I can understand why it doesn't require fuel as the stone itself is self-illuminating.  It could have a text where it says the stones fade slowly, but I noticed it would be hard to refuel as there is usually very little on the map to find.

**Comment by jnkyacc** [comment]
Agree with 1) until glowstones by itself is non-depletable. Im using glowstones by itself, just dropping them all around. Same with coldstones.
As they quite rare so:
1) GlowstoneLamp = 5>4 glowstones  (as 1 tile MineableGlowstone gives you 2 pcs., so depends from luck you will receive enough materials for 3-6 GlowstoneLamps )
2) Trader balance require (just make sure that they will be rare and costly)
3) Quarry balance require (reduce chance)
00) Add forbidable button for glowstone\coldstone

**Comment by trevize23** [comment]
Last time I used coldstones (1-2 weeks ago) it was depletable, but that might've changed with the fuel update. The rate it depleted was way too high making it useless.

I feel like glow/coldstones should only be viable in early/ early mid game. Once you got your electrical infrastructure you should make the switch.
