### ISSUE TITLE
rimworld  workbench tool effectiveness factor hint

### ISSUE THREAD

**Issue by XeonPhobia** [skyarkhangel/Hardcore-SK#3648]
![Rimworld_hardcore_sk_material_tools](https://user-images.githubusercontent.com/28835890/230765025-4940e31b-e5a2-4274-8ebe-66aeec1f6cbc.jpg)

It would be awesome if I could see the materials affect on tool speed before manufacturing the tool.

**Comment by Zim777** [comment]
https://discord.com/channels/272340793174392832/411091475099549697/975348005047791676
