### ISSUE TITLE
Lack of consistency in material options for building workstations

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#366]
Some workstations like the Weapon Crafting Workbench can be built of Wood Planks, but some like the Ammunition Crafting Workbench cannot be. 

Wood Planks are sometimes treated like a Metal Alloy and sometimes not. 

There does not seem to be a clear pattern for what can be built out of what materials. 

Is there a system in place that I do not understand?

**Comment by skyarkhangel** [comment]
early access worktables could be built with wood or stone. Middle, Hi-end worktables require more advanced materials.
