### ISSUE TITLE
Не удается отнести вещи на стойку

### ISSUE THREAD

**Issue by emulatethis777** [skyarkhangel/Hardcore-SK#3671]
Не удается отнести вещи на обычную стойку для экипировки.
Пешка несёт вещь со склада подходит к стойке и тут же несёт вещь обратно на склад. Функционал снять\повесить при этом работает.
Как повторить:
разметить склад, положить любую одежду, создать стойку, разрешить всё сделать приоритет выше чем у склада.
Назначить одежде срочный перенос, приказать пешке перенести эту одежду.

**Comment by TheLoneTec** [comment]
Номер версии? какая ветка HSK?

**Comment by emulatethis777** [comment]
1.4.3.3682.
сейчас выкачал последний коммит из develop(0b3c068ecd90db63219a729e4839e05a165f0169) - то же самое.

**Comment by emulatethis777** [comment]
Спасибо, [4c3ba3f](https://github.com/skyarkhangel/Hardcore-SK/commit/4c3ba3f24a1fa38a63ee289c6b03120cf0bdb4ff) устраняет проблему.
