### ISSUE TITLE
I can't seem to tame animals

### ISSUE THREAD

**Issue by AlexandruRobertStoian** [skyarkhangel/Hardcore-SK#3680]
For some odd reason whenever I try and tame animals it goes to it tries to tame and after the last check to see it stops and resets the taming process plus the pawns don't seem to '' see '' the food to tame said animal in their inventory.

**Comment by PlywoodWolf** [comment]
Confirm, disabling "animals logic" mod fixes.

**Comment by AlexandruRobertStoian** [comment]
Thank you

**Comment by AlexandruRobertStoian** [comment]
I've disabled the '' animal logic '' mod, the issue still persists.

**Comment by AlexandruRobertStoian** [comment]
Looking forward for your conclusion.

**Comment by TheLoneTec** [comment]
post your Hugslib log in a bug report. Also with more details, like the animal, the tamer, the food they are using, your food policy for the animals etc.

**Comment by TheLoneTec** [comment]
look at the #faq-install-troubleshooting channel in the discord for instructions. A hugslib log is a log generated in game by opening the debug log in development mode and pressing the green button. It may fail to upload and give a link, if it doesn, uncheck "use recommended settings" and copy the log to your clipboard by pressing "to Clipboard". Paste it ina  .txt file. Save it and upload it into a bug report.
