### ISSUE TITLE
I'm having a problem with prisoners bugging out.

### ISSUE THREAD

**Issue by AlexandruRobertStoian** [skyarkhangel/Hardcore-SK#3684]
I seem to bug out prisoners when I load my savegame and can't recruit them anymore nor really interact in any meaningful way with them and when I use the console commands to kill and then ressurect them they disappear. Here is the log 
[Pawn BUG out.txt](https://github.com/skyarkhangel/Hardcore-SK/files/11488628/Pawn.BUG.out.txt) .

**Comment by TheLoneTec** [comment]
if this has happened only since you loaded your save game, load an earlier save and see if the issue persists.

**Comment by TheLoneTec** [comment]
also, fix your load order:

Thees must always be at the bottom. Make sure to follow the Load Order Guide on the discord.

  - trinity.RuntimeGCupdated
  - Dubwise.DubsPerformanceAnalyzer.steam
  - Mlie.WikiRim
  - Taranchuk.PerformanceOptimizer
  - Krkr.RocketMan

**Comment by TheLoneTec** [comment]
also vanilla fishing expanded i dont think is very compatible with hsk atm

**Comment by AlexandruRobertStoian** [comment]
Thank you for the help, it would seem that when I load other savegames it is the same.

**Comment by TheLoneTec** [comment]
Please make a bug report and post your hugslib log, not the Player.log or your config. There are instruction in #Error-Troublehsooting on how to do this

**Comment by AlexandruRobertStoian** [comment]
Thank you, will do.
