### ISSUE TITLE
Mech Weapons not spawning/functioning, some misc. suggestions

### ISSUE THREAD

**Issue by Arkaile** [skyarkhangel/Hardcore-SK#3688]
Legionary: Spawns without its needle gun and relevant ammunition

Centurion: Its point-defense turret doesn't fire on anything. Its shield is also comically weak for use in HSK, especially considering its high resource cost and bandwidth requirement.

War Queen: Its turret does not fire; the turret it uses is probably the same one as the diabolus, which functions just fine. However, due to the efficacy of its summoned urchins, this particular mech could likely be left as-is or changed to use the same point-defense turret as the centurion.

**Comment by TheLoneTec** [comment]
this needs more investigation, supposedly the turrets on them should work
