### ISSUE TITLE
everything stats mod

### ISSUE THREAD

**Issue by com30n** [skyarkhangel/Hardcore-SK#3696]
Hey guys!

It would be nice to have a modification made especially for HSK which would show all of the stats about materials 
such as: 
metals,
fabrics,
rock blocks,
etc.

for example, which the best for the work speed, which the best for the research speed, from which I should make beds for my hospitals, which the most expensive, etc

also would be nice to have the weapon stats mod https://steamcommunity.com/sharedfiles/filedetails/?id=974066449
with some changes for HSK (because it doesn't show ammo types and their differencies, dps for range weapon etc)
and would be nice to have some numbers about my clothes (which clothes better for scientific work, which for usual work, in which clothes my colonists will fo faster etc.)

If the mods will be found (or even created), that will make the playes quality of life a way more easier.

P.S. I just started to play HSK, and this is really nice project, I do really love it
but playing with the variants of the materail is really confusing me - instead playing I make tables where trying to decide what I should wear my colonists, from which I should make clothes, weapons for them, form which work tables better to build, etc and the game doesn't give me any advises or comparison between it :(

P.P.S. Thank you guys for the huge work which you already made! as a usual rimworld fan I do really appreciate it!

**Comment by TheLoneTec** [comment]
Some useful mods and tips:

- https://discord.com/channels/272340793174392832/411091475099549697/975350126082154546 (you can see any item/building made from different stats using this method)

- Textile Stats Database : https://steamcommunity.com/sharedfiles/filedetails/?id=2045777828

- Better Info Card : https://steamcommunity.com/sharedfiles/filedetails/?id=2890920739 (great for comparing stats)

**Comment by masakitenchi** [comment]
https://github.com/bananasss00/RW-RimDumper/
Or if you're interested in testing if this still works in 1.4

**Comment by com30n** [comment]
nice, thank you!

**Comment by com30n** [comment]
It doesn't work with 1.4, unfortunately :(
