### ISSUE TITLE
Fruits II research does not allow planting of tomatoes like description says

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#370]
I have tomato seeds but after researching the technology "Fruits II" I am unable to select them from the menu for the growing area.

**Comment by jnkyacc** [comment]
Check soil requirements

**Comment by SmokeyUnicycle** [comment]
The seeds don't show you the soil requirements. 

I tried making a 1x1 growing zone on a patch of 150% rich soil but it still didn't work, do they need 200% fertilization? 

Seems strange that they'd be in Fruits II if they need later game fertilization with Synthetic Ammonia

**Comment by Vigilence** [comment]
Yeah, I wish the seeds were a little more descriptive.

**Comment by SmokeyUnicycle** [comment]
Could tomatoes be moved to a later research? You're not going to be able to grow them until you can get synthetic ammonia, but well I guess you could hope for a trader... 

I feel like it's going to confuse some people. 

You might want to add the line "Some crops will not be available in Growing Zones without sufficient soil fertility" to every single Fruits and Vegetables and Cereals research technology so you don't have someone making this thread every week :P 


I dunno maybe I'm just dumb and it's just me :P

**Comment by SmokeyUnicycle** [comment]
Okay, I have gotten 200% fertilized soil, still not an option. 

image.prntscr.com/image/1b917b0218d04306b2abd4078290cd73.png

http://image.prntscr.com/image/0e35209d3a5d410ca85a17c592758a3e.png

http://image.prntscr.com/image/34abdb6c26e94074a56d41990bde7941.png

**Comment by Vulpes-Inculta** [comment]
Log walls themselves tell me you indeed have a wrong mod version :)

**Comment by trevize23** [comment]
It's not a matter of game version. Many Research descriptions are just wrong.

see: https://github.com/skyarkhangel/Hardcore-SK/issues/272

**Comment by Vulpes-Inculta** [comment]
Research description may be wrong but research info in the Help tab is always correct in my experience. So I use it extensively.

**Comment by skyarkhangel** [comment]
Fixed desctiptions
