### ISSUE TITLE
Баг с кинжалом, мод на инструменты.

### ISSUE THREAD

**Issue by Zloooo** [skyarkhangel/Hardcore-SK#3702]
После каких то обновлений, уже готовые кинжалы потеряли свойство инструмента, из-за чего поселенцы с ним в руках тупят и почти ничего не могут делать.
Исправил путем перехода на секачи для готовки. Новые кинжалы не делал, не знаю работают ли правильно.
Пост сделал что бы помогло, тому кто с этим столкнется.

**Comment by TheLoneTec** [comment]
You must dev destroy old tools whenever they are updated and use character editor to make new ones with the same stats
