### ISSUE TITLE
Производство сойлента.

### ISSUE THREAD

**Issue by Zloooo** [skyarkhangel/Hardcore-SK#3711]
Станок находится в разделе "приготовление пищи", для работы на нем, поселенец так же должен быть назначен на роль "повар", но при этом для производства необходимо 12 ремесла и 0 кулинарии.

Это создает неудобства для оптимальной работы колонии и назначении работ. Или сделать бы требование 12 кулинарии для работы или перенести тип работ к "ремеслу".

**Comment by TheLoneTec** [comment]
thanks for pointing this out, not sure which direction we should lean to. i am thinking crafting, as the thing that makes solent is a machine, i imagine it wouldnt need much cooking skill.
