### ISSUE TITLE
Расы фракций. Races of factions. 1.4

### ISSUE THREAD

**Issue by Zloooo** [skyarkhangel/Hardcore-SK#3714]
Нова, Дова и другие расы, были перенесены в генетику, имея базовую основу "человек".

У фракций же основа не "человек".

Это вызывает конфликты с разными модами на тело, глаза, лица.

**Comment by TheLoneTec** [comment]
большинство инопланетных расовых модов не делают того, что делаем мы. Прямо сейчас это просто ограничение, я ждал исправления от команды HAR, чтобы лучше работать с Biotech, но до тех пор это просто вопрос доступных исправлений для модов инопланетных рас.

**Comment by TheLoneTec** [comment]
Кроме того, не могли бы вы уточнить больше? какие проблемы?

**Comment by Zloooo** [comment]
> Кроме того, не могли бы вы уточнить больше? какие проблемы?

![111](https://github.com/skyarkhangel/Hardcore-SK/assets/121285991/9d779c50-c086-4207-a1da-420c8f36a579)
![222](https://github.com/skyarkhangel/Hardcore-SK/assets/121285991/ab61668b-5ce5-495a-bd3f-13b8a412f2fa)
![333](https://github.com/skyarkhangel/Hardcore-SK/assets/121285991/b708d97d-6fb8-4778-b77f-67c4ceb83eea)

**Comment by TheLoneTec** [comment]
это не проблема, они спавнятся с правильными ксенотипами, но если дать им другие ксенотипы, то конечно они будут такими

**Comment by TheLoneTec** [comment]
с введением биотехнологии гонки HAR стали не чем иным, как основой и модификацией bodyAddon. Если вы дадите расе другой ксенотип, конечно, они изменятся, чтобы соответствовать ксенотипу, в этом весь смысл. На данный момент вы можете просто рассматривать расу HAR как происхождение, потому что они в основном становятся гибридами, не все их изменения характеристик связаны только с генами, поэтому у них есть характеристики их нового ксенотипа и некоторые характеристики их исходной инопланетной расы.

**Comment by Zloooo** [comment]
> с введением биотехнологии гонки HAR стали не чем иным, как основой и модификацией bodyAddon. Если вы дадите расе другой ксенотип, конечно, они изменятся, чтобы соответствовать ксенотипу, в этом весь смысл. На данный момент вы можете просто рассматривать расу HAR как происхождение, потому что они в основном становятся гибридами, не все их изменения характеристик связаны только с генами, поэтому у них есть характеристики их нового ксенотипа и некоторые характеристики их исходной инопланетной расы.

на скринах продемонстрирован [NL] Facial Animation, который не видит не человеческую основу.
но вот к примеру есть такой мод как Xeva FB Pack, он как не странно видит все расы и работает с ними адекватно.

в принципе я стараюсь предоставить вам просто больше информации для ваших размышлений.

**Comment by TheLoneTec** [comment]
о, если вы говорите о том, что лицевая анимация не работает, то это не проблема HSK, вам нужно указать это на надстройку исправления HSK для лицевой анимации в надстройках Discord HSK
