### ISSUE TITLE
AI trying and failing to execute Sapper Strategy, causing slowdown (bug)

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#372]
http://image.prntscr.com/image/16837bd92f704c06a8707560b3067349.png

The game was getting very poor performance when attempting to increase speed, devlog reported this when I opened it. 

No other observations other than stuttering on x2 and x3 speeds. 

Reloading to an earlier save fixed it, but this issue might be worth looking into, I don't know. 

THis is on the 1249 version from July 29th

**Comment by Vulpes-Inculta** [comment]
Are you reporting a problem in 2 months old version of the mod? Or am I getting it wrong...

**Comment by SmokeyUnicycle** [comment]
I don't _think_ so, I followed the instructions from the forum post, "Go here to github to get the latest version of the mod"

Went to releases and downloaded A14E Hell Effect 4.0 assuming they've been updating it without releasing a new version. 

I just wrote what the version text in the top left corner of the screen said. 

:?

**Comment by Vulpes-Inculta** [comment]
Man, you are playing the very first raw version without all those 354 commits. You should go to: <>Code, then press "Clone or download" button and then download archive with the latest changes inside. There will be several folders inside but you only need the one with config file and several mods folders inside. After that it's all according to nstruction. I fear to imagine how long you have been doing it wrong, bruva ((

**Comment by ShanKanis** [comment]
There is no info in main posts about the mod, to get latest versions, so many people who don't know that it's constantly updated project, just get the one linked in those main posts. I did that at first too, I simply didn't know how it works.

**Comment by SmokeyUnicycle** [comment]
>Man you are playing the very first raw version of this last release without all those 354 commits. You should go to: <>Code, then press "Clone or download" button and then download the archive (Hardcore-SK-master) with the latest changes included. There will be several folders in the archive but you only need the one with config file and mods folders inside. After that it's all according to nstruction. I fear to imagine how long you have been doing it wrong ((


Yeeeeeaah that's a problem that needs to be fixed immediately, since that's basically the only way that makes sense to find the newest version if you're not familiar with github. 

Skyarkangel needs to update the Ludeon forums thread with this information because that means many people are using the old version of the mod.

>There is no info in main posts about the mod, to get latest versions

I mean there is, it's just not actually how to get the latest version, it just says it is and then points you to github.

**Comment by skyarkhangel** [comment]
Ok. I made 4.1 version, when players test latest update.

**Comment by jnkyacc** [comment]
@skyarkhangel 
mb just udpate old links to https://github.com/skyarkhangel/Hardcore-SK/archive/stable.zip and https://github.com/skyarkhangel/Hardcore-SK/archive/master.zip will be enough?
а вообще неплохо было бы что бы оно автоматом прописывало №комита в version.txt. Люди просто не знаю куда смотреть и какая у них версия.
п.с. в мастере до сих пор 874 ревижн.
