### ISSUE TITLE
Are sappers still in the game? Enemies do not attack walls. (Bug? Feature?)

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#373]
Other than lighting wooden walls on fire, the AI enemies will almost never attack solid walls. 

This makes certain defensive structures like kill boxes very powerful, is this intended behavior? 

I have played about 75 hours of two most recent versions and I think an enemy has attacked a wall once, and that was when it was a one thin wall that was damaged by a disaster. 

I understand that walls are much stronger/harder to damage in this version, but maybe some kind of demolition charge is needed/could be useful to make things more interesting? A very very high damage weapon with very small area of effect and very long detonation time.

**Comment by xwat** [comment]
Hmm, I am playing with the latest github version and for me sappers do try to avoid killboxes -- by mining a passage through mountain for instance.

**Comment by SmokeyUnicycle** [comment]
I have literally never had that happen!

**Comment by Vulpes-Inculta** [comment]
You are running thr wrong version, SmokeyUnicycle, check my answer you your other thread.

**Comment by Vigilence** [comment]
For me they just use grenades to blow them up.

**Comment by zakhad** [comment]
Point blank incendiary suicide squads for me is what I usually get.

**Comment by skyarkhangel** [comment]
Closed. Old version.
