### ISSUE TITLE
Solar Flair/Cosmic radiation critical bug

### ISSUE THREAD

**Issue by xwat** [skyarkhangel/Hardcore-SK#374]
Note: I am running the latest github version as of 24.09.
I got this event twice, both times every pawn tries to execute random actions (like eating, relaxing, hauling etc) and all have STUNNED status effect. They all stay still at their positions and their actions just keep changing randomly. The game is unplayable when this happens.
The dev log has red error whilsts trying to execute "cosmic radiation". <-- sry, this happened earlier today, didn't save the screen.

I managed out via save file editing, but I think that this event should be fixed. If fix is too expensive to perform, I suggest to turn it off until a solution is found -- as this ruins the game for less xml-savvy people.

**Comment by Vulpes-Inculta** [comment]
I'm pretty sure the event description mentions that stun effect is intended. How exactly does it ruin the game?

**Comment by xwat** [comment]
The event doesn't actually fire, that's how -- there is no notification that cosmic radiation is coming or anything like that. The information about the event is only visible in dev log. And  this stun is not going away.

**Comment by Vulpes-Inculta** [comment]
For me it is going away after a while with cosmic radiation event at least. And event does seem to fire normally.

**Comment by skyarkhangel** [comment]
Removed stun effect in next big update.
