### ISSUE TITLE
Ammo bench sprite missing

### ISSUE THREAD

**Issue by Yeeeho** [skyarkhangel/Hardcore-SK#3748]
https://gist.github.com/HugsLibRecordKeeper/d3c47f3e10ac0072b1ae4902d1d3a5ee
Log link

Could not load the Ammo bench sprite

**Comment by TheLoneTec** [comment]
Do a clean install of the latest, delete old files.

**Comment by Yeeeho** [comment]
> Do a clean install of the latest, delete old files.

Working on it

**Comment by Yeeeho** [comment]
> Do a clean install of the latest, delete old files.

Just wondering, could it be the problem if Combat extended mod was already installed before the installation of Hardcore SK?
I installed HSK via HSK launcher btw

**Comment by Yeeeho** [comment]
Never mind. That overlapped CE was the problem.
