### ISSUE TITLE
Stone Cutting Workbench needs blocks

### ISSUE THREAD

**Issue by Pierre-Demessence** [skyarkhangel/Hardcore-SK#375]
Hello,

In the latest version of the modpack (both in master and stable branch) you can't do anything at the beginning because almost every workbench needs blocks and the stone cutting workbench (which make b locks) also needs blocks.. So you needs blocks to make blocks.

I know that you can deconstruct pregenerated stuctures to get some blocks, but if you play on a tiny map and/or you are not lucky with the generation, you just can't do anything..

**Comment by ShanKanis** [comment]
I've checked and you're right, but you can go around it by researching stonecutting right away and making Hand Machining Table, which does same thing and more.

**Comment by nemesis688** [comment]
If you've looked around I'm sure you've seen the Totem poles scattered about. Those are the replacement for the default wood that you would normally start with. In the same vein, you should also see little stone statues called stone cairn. They are are pretty small so they are hard to see. Anyway, you are suppose to deconstruct them for stone. each ones gives about 52 blocks.

The crashlanded scenario is set to scatter them around so you should always have some

**Comment by Vulpes-Inculta** [comment]
Same witch classic scenario, for me they are always there.

**Comment by Pierre-Demessence** [comment]
With the stone cairns everything is good. As 10 cairns are scattered accros the map and each gives about 50 blocks, you have more than enough to start the game, even if making some mistakes.
Thanks ! ;)
