### ISSUE TITLE
New fuel system - planks not listed

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#377]
Planks are not listed as an option for fuel, but they get burned anyway.  I'm using the build as of this morning, 9/30/16, and my fueled stove just got loaded with planks.

**Comment by skyarkhangel** [comment]
all types of fuel allowed for defaut now. Do you want, that accidentally planks used as a fuel? i could add it..

**Comment by ScottS9999** [comment]
I think it should be allowed, but I should be able to turn it off like I can the other fuel types.

**Comment by Vigilence** [comment]
Should be added, but off by default so they won't use them by accident.

**Comment by jnkyacc** [comment]
@Vigilence  @ScottS9999 
Fuel system not allow to set default filter through xml same way as for containers or buildings. Only by modifying dll.

**Comment by skyarkhangel** [comment]
soon i test new features for thingfilter which i suppose solve problem and enable to set allowed,disallowed things by default.

**Comment by skyarkhangel** [comment]
Nope. For now, it couldn't be done.
