### ISSUE TITLE
"Could not resolve cross-reference: ..." after first install of HSK

### ISSUE THREAD

**Issue by Blackhoody12** [skyarkhangel/Hardcore-SK#3772]
Hello. I have played HSK few months ago. Now i had to reinstall windows so had to reinstall HSK as well. Problem is as description says. SO what Im doing. 

First installing base game and then launching it for the first time.

Next I launch HSK installer, click "Chceck for updates" and then "Install". 

Entering game, everything is fine. 

And now is problem. I go to mods menu, and want to add optional mods. Adding all that are marked as "HSK", clicking "Auto sort mods", then save. After saving console hits me with A LOT of "Could not resolve cross-reference: ..." errors. All I guess says about Combat Extended.

Here are few lines:
> Could not resolve cross-reference: No CombatExtended.AmmoDef named Ammo_30x173mm_HE found to give to CombatExtended.AmmoLink (null -> Bullet_30x173mm_HE) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

> Could not resolve cross-reference: No CombatExtended.AmmoCategoryDef named GrenadeHE found to give to CombatExtended.AmmoDef Ammo_90mmCannonShell_HE 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

> Could not resolve cross-reference: No CombatExtended.AmmoSetDef named AmmoSet_45ACP found to give to CombatExtended.LabelGun CombatExtended.LabelGun 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

> Could not resolve cross-reference: No CombatExtended.AmmoDef named Ammo_15x65mmDiffusingCharged_Buck found to give to CombatExtended.AmmoLink (null -> Bullet_15x65mmDiffusingCharged_Buck) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Does anyone had such problem and is there way to fix it? Also attach log file. Thanks in advance
[Player.log](https://github.com/skyarkhangel/Hardcore-SK/files/13460873/Player.log)

**Comment by TheLoneTec** [comment]
We need a Hugslib log. Read the Error - Troubleshooting section in the HSK discord.

**Comment by Blackhoody12** [comment]
https://gist.github.com/HugsLibRecordKeeper/66b848683a2d1349cdfc551c0c37f8e8

Here you go

**Comment by TheLoneTec** [comment]
Your getting errors for vanilla things. I would verify your game files and also make sure your not accidentally loading the workshop mods. Also make sure you did a full clean install. Not just doing it through steam, but uninstalling, and deleting all leftover files as well as configs.

**Comment by TheLoneTec** [comment]
for example its saying that <isHopper> double belong in <building> which makes no sense, because it does and thats a vanilla tag

**Comment by Blackhoody12** [comment]
> Your getting errors for vanilla things. I would verify your game files and also make sure your not accidentally loading the workshop mods. Also make sure you did a full clean install. Not just doing it through steam, but uninstalling, and deleting all leftover files as well as configs.

So Im doing manual clean after uninstalling via steam. I will try veryfying files, but every time I full reinstall game

**Comment by TheLoneTec** [comment]
uninstallating via steam does not full uninstall, you have to manually go to your files and delete the leftovers as well as the ones in the %appdata% folder.

**Comment by Blackhoody12** [comment]
> uninstalling via steam does not full uninstall, you have to manually go to your files and delete the leftovers as well as the ones in the %appdata% folder.

That what Ive said. After every uninstall Im deleting manually everything that is left in appdata and also in steam folder

**Comment by Blackhoody12** [comment]
So I thought that this errors shows up when I want to enable optional mods. But now I restarted game after fresh install and all those errors show up. I havo no idea what is happening. Never had such problem with HSK

**Comment by TheLoneTec** [comment]
Your on the wrong version RimWorld 1.4.3563 rev533, you need to be on the latest
