### ISSUE TITLE
Meteorite events

### ISSUE THREAD

**Issue by ElikSirius** [skyarkhangel/Hardcore-SK#3773]
Hi, I can't post on discord because of my phone number, so I'll post here. I switched from 1.2 and with a completely clean installation of Rimwold 1.4 3901 rev 238 (I deleted everything in appdata several times too) In the stable and development branch, I came across a bug in which meteorites from the EclipseMeteorImpact and BoulderMassHit event (from the dev menu) do not leave ore after falling meteorites and do not leave errors in the console. Perhaps other events related to meteorites also work incorrectly. For example, if you press “spawn thing > Meteor” a bunch of errors will appear in the console, even on the “release 11.0” version. By the way, this is the only version in which meteor events work normally, except for the "spawn thing > Meteor" errors, but maybe this is normal.
I also can’t download stable/dev from github directly, so I downloaded it from mirrors from pins in discord. But last time I was able to download "release 11.0" zip from Github.
so I see people have the same problem, but no one paid attention.
https://discord.com/channels/272340793174392832/272924909649395712/1172211147798233188
https://discord.com/channels/272340793174392832/272340793174392832/1175899783752335450
(Google translate)

**Comment by TheLoneTec** [comment]
this is normal, depending on the impact and fragments created, metorites can be destroyed on impact

**Comment by ElikSirius** [comment]
Really? I checked many times on x10 too, not a single big meteorite appeared, and I played for 1 year on sea ice until I noticed that there was not a single meteorite on my map, although they often fell from the sky.

**Comment by TheLoneTec** [comment]
also meteorites are not designed to be spawn in directly via dev menu, that error is normal

**Comment by TheLoneTec** [comment]
ok,. ive managed to recreate this, its being investigated

**Comment by ElikSirius** [comment]
Oh ok i made a screenshot:
![2023-11-25](https://github.com/skyarkhangel/Hardcore-SK/assets/31782583/52708bdc-75e6-4757-a253-b817c78f172a)

**Comment by TheLoneTec** [comment]
fixed in the latest dev
