### ISSUE TITLE
tin ore for fuel for coal burner

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#378]
like title says. not this git comment the one before this one they put tine ore for fuel twince in it. so far they havent did it to other building. what made it weird it said 75 tin ore gave it 3 days fuel.

**Comment by skyarkhangel** [comment]
more detail please.

**Comment by sidfu** [comment]
well not much to it my hauler was refilling things and when it came to the coal burner she grabed the tin ore instead of coal and put it in the burner.

it seems to happen when tin ore is closer than coal, but the weird thing is i had carchall checked yet she went right by the charcoal and grabed the tin ore.
