### ISSUE TITLE
with all the new textures

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#380]
with all the new textures game is hitting memory cap and crashing.

this is a recent issue thats poped up since all the new textures have been added.

**Comment by skyarkhangel** [comment]
what exactly textures?

**Comment by sidfu** [comment]
[output_log2.txt](https://github.com/skyarkhangel/Hardcore-SK/files/504153/output_log2.txt)
[output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/504154/output_log.txt)

here u go the output log for both. was half asleep when posted the crash.
at bottom the stackc trace points to some error in mini map.

well the output will also allow u to see the other errors like the 900 spams from the firepit inside a prisoners room be deconed.
