### ISSUE TITLE
Bug report of VMR

### ISSUE THREAD

**Issue by squirrelfishQAQ** [skyarkhangel/Hardcore-SK#3800]
_Variety Matters Redux_ (in development branch) is suspected to have a serious bug.
Whenever I load a saved game, the need bar _variety_ would be cleared just like
Before save and load:
<img width="182" alt="1" src="https://github.com/skyarkhangel/Hardcore-SK/assets/133613454/94801c33-ea1a-4ef4-abd9-0324a686d3d5">
After save and load: 
<img width="193" alt="2" src="https://github.com/skyarkhangel/Hardcore-SK/assets/133613454/c7d6e76d-d873-41e0-889b-72adb4b66adc">
Seems that the names of recently eaten meals were not properly written into/read from the **.rws** file.

**Comment by TheLoneTec** [comment]
try latest development, i just updated it to the latest workshop version.

For future reference for everyone using HSK. We dont have people keeping an eye on workshop updates. if something doesnt quite work right and the workshop version has an updated version. Try that first.

**Comment by TheLoneTec** [comment]
and then notify us.
