### ISSUE TITLE
Building requirement disappear

### ISSUE THREAD

**Issue by x3nit** [skyarkhangel/Hardcore-SK#382]
The require materials for buildings/objects dont show up anymore when i mouse over the objects. Is this intended ?

**Comment by ScottS9999** [comment]
Yes, you have to have some of the items to build the structure before the requirements show.  Pretty sure it is not intended.

**Comment by jnkyacc** [comment]
@x3nit 
Limitation of new sub category system. You should click on the object to show requirements. But with no materials you cannot click on it. Use "HELP" tab as temporary remedy.
