### ISSUE TITLE
SkyAI ворует молотки и не только

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#3822]
В общем, заключенные постоянно вооружаются, когда по логике этого не должно быть.
Веду караван куда то - тут же начинают собирать шмот вокруг на глазах у своих пленителей, пока те собирают караван.
Самое крутое, что было: продал кучу заключенных, один пошел и залутал молоток с поселенца без сознания в медпункте. МОЙ МОЛОТОК ИЗ НЕБЕСНОЙ СТАЛИ.

Когда они во время побега вооружаются я могу понять, но просто по дефолту - это бред.

**Comment by SergeyPomelov** [comment]
Ладно молотки, их из-за этого надо ещё микроконтролить чтобы хоть брёвна в поле зрения не неслись пиздить.

**Comment by hadaev8** [comment]
Заметил еще, что гости тоже могут лутануться.
Ситуация: продал раба, он понесся залутать пушку с гостя, гость очнулся, увидел, что пушки нет, зато рядом есть мой поселенец после операции, и залутал у того оружие.
