### ISSUE TITLE
Геошторм, которого не должно быть.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3860]
Столкнулся с тем, что на базе возник Геошторм. Хотя он отключен мной по сценарию. Начинается вскоре после загрузки этого сейва. (У меня дважды сработал при загрузке.)
[3.zip](https://github.com/skyarkhangel/Hardcore-SK/files/15142486/3.zip)

**Comment by GrandSior** [comment]
Это хотя бы не спавн смерча внутри базы

**Comment by SetAriman** [comment]
При Геошторме пара-тройка смерчей внутри базы это лишь часть проблемы...
