### ISSUE TITLE
Ии бьет объекты на своем пути вместо того, чтобы обойти

### ISSUE THREAD

**Issue by hadaev8** [skyarkhangel/Hardcore-SK#3868]
Ситуация: эвент вражеский десант, они вылезают из корабля и начинают его бить.
Думаю дело в том, что обойти лень, но точно не знаю.
![изображение](https://github.com/skyarkhangel/Hardcore-SK/assets/20247085/3c1b30d2-25bc-4c9e-be5d-13ba6456f13b)

**Comment by TheLoneTec** [comment]
what even is that ship?

**Comment by hadaev8** [comment]
"Enemy ship" from core sk, event enemy landing or something, not sure what is it in english.
So they spawn on bottom side and cant go around instead attacking ship, probably because of shallow water path cost?

**Comment by TheLoneTec** [comment]
to be honest, this is just a vanilla AI issue and yes that would be the reason, its the path cost.

**Comment by hadaev8** [comment]
Okay then
