### ISSUE TITLE
Kibble recipe and taming items

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#387]
I'm not sure what was intended, but the kibble recipe doesn't match what is actually used to make kibble.
Recipe = 1 meat, 1 vegetarian => ? kibble
Actual = 20 meat, 67 vegetarian => 50 kibble

Also, hay cannot be used for taming while vegetables and fruits can.  Is that intended?

**Comment by jnkyacc** [comment]
> Recipe = 1 meat, 1 vegetarian => ? kibble
1 nutrition from meat source and 1 nutrition from vegan source. Meat have mostly 0.05 nutrition, vegan have more nutrition diversity.

Hay is not a reward, so yes you cannot use it.

**Comment by ScottS9999** [comment]
Ok, it's 1 nutrition and not 1 item.  Got it.
