### ISSUE TITLE
melee weapon and fire

### ISSUE THREAD

**Issue by crusender** [skyarkhangel/Hardcore-SK#39]
i dont know if you can fix it, but when equip whit any melee weapon (pickaxe to longsword) if there a fire and they are in firefight the colon will freeze in standing mode and do nothing till fire is out.

**Comment by Masquerine** [comment]
I got an error when the colonist was equipped with a pickaxe while trying to fight a fire.
![fireerror](https://cloud.githubusercontent.com/assets/16396520/13379807/8ef9f04a-ddfe-11e5-8b70-8b735e45af73.png)

**Comment by skyarkhangel** [comment]
Ok. Problem found.

**Comment by skyarkhangel** [comment]
Fixed in next update.
