### ISSUE TITLE
SkynetTX takes radiation damage even if its radiation sensitivity is 0.(alpha branch)

### ISSUE THREAD

**Issue by 1465114862** [skyarkhangel/Hardcore-SK#3914]
1.5hsk, alpha branch
how to reproduce: Spawn Pawn\SkynetPrototypeTXOrigin
Spawn some NuclearWaste around TX.
Wait for a while.
![screenshot717](https://github.com/user-attachments/assets/29190d4d-e3d1-460f-82ec-4cb1a29b3222)
![screenshot718](https://github.com/user-attachments/assets/de2d2232-e80a-4427-9406-ef41b74b0448)

**Comment by TheLoneTec** [comment]
we override this in Core SK, all things can receive radiation damage, robotic pawns receive the hediff "radiation damage"

**Comment by TheLoneTec** [comment]
because even though they are machines, radiation still effects machinery over time. This could possible be adjusted in the future though

**Comment by TheLoneTec** [comment]
no problem, id rather people post than not, because other people can see this too and find out
