### ISSUE TITLE
If a pawn has a bionic part on one side, the other side of the body part will have the same health point as the bionic.(alpha branch)

### ISSUE THREAD

**Issue by 1465114862** [skyarkhangel/Hardcore-SK#3915]
1.5hsk, alpha branch
how to reproduce:
Give a bionic to a pawn.(Bionic leg etc.)
Let another pawn hit its leg.
![screenshot719](https://github.com/user-attachments/assets/e21c94bf-d0cf-47d9-9701-738bbbe1c1a9)
![screenshot720](https://github.com/user-attachments/assets/9432f25a-47b7-49ac-957b-d060726ab43d)

**Comment by TheLoneTec** [comment]
they are not the same, they were even hit by different things.

**Comment by 1465114862** [comment]
> they are not the same, they were even hit by different things.

I mean total health point of a body part. A normal leg without bionic should have 40 total health point. But now it has 150 total health point.

**Comment by TheLoneTec** [comment]
you know whats funny, this is a vanilla issue

**Comment by TheLoneTec** [comment]
![image](https://github.com/user-attachments/assets/5c5109b0-e324-4ef7-ad0d-732227b9e307)

Because both Legs def is called "Leg", 

      for (i = 0; i < recipe.appliedOnFixedBodyParts.Count; ++i)
      {
        BodyPartDef part = recipe.appliedOnFixedBodyParts[i];
        bpList = pawn.RaceProps.body.AllParts;
        for (j = 0; j < bpList.Count; ++j)
        {
          BodyPartRecord bodyPartRecord = bpList[j];
          if (bodyPartRecord.def == part && (validator == null || validator(bodyPartRecord)))
            yield return bodyPartRecord;
        }
        part = (BodyPartDef) null;
        bpList = (List<BodyPartRecord>) null;
      }
      
It technically adds it to both.

**Comment by TheLoneTec** [comment]
to clarify, this is the same in 1.4 too.

**Comment by TheLoneTec** [comment]
actually wait, i just tried this in 1.4, and adding a bionic leg still kept the hitpoints at 40. This is probably because the pawn also had an infection in the other leg. Its possible the hitpoints specifically are broken or match whatever the other limb has. It could also be just a text error and it doesnt represent it properly

**Comment by 1465114862** [comment]
> actually wait, i just tried this in 1.4, and adding a bionic leg still kept the hitpoints at 40. This is probably because the pawn also had an infection in the other leg. Its possible the hitpoints specifically are broken or match whatever the other limb has. It could also be just a text error and it doesnt represent it properly

I tested. In 1.5, the infection can't limit hitpoints to 40. And it's probably not an text error. Because the other leg can take damage more than 40.
![screenshot721](https://github.com/user-attachments/assets/98ac6187-3316-4f13-b5b2-115a6daa9c72)
![screenshot722](https://github.com/user-attachments/assets/e793ef28-595c-4934-8aaa-7c4bb09b86c5)

**Comment by TheLoneTec** [comment]
did you try having an infection on a leg first before adding the bionic leg?

**Comment by TheLoneTec** [comment]
because if that doesn't work, it may be something was disabled in 1.4 to stop this from happening, but is no longer disabled in 1.5, which allows the hitpoints to be changed and cause the bug

**Comment by 1465114862** [comment]
> did you try having an infection on a leg first before adding the bionic leg?

Yes I tried. The hitpoints is still 150. The order doesn't make a difference.
What's more, Adding muscle stimulator to another leg make the hitpoints of bionic leg drop to 80.
![screenshot723](https://github.com/user-attachments/assets/d94309da-931e-4741-8bca-7eeef62f1b68)

**Comment by TheLoneTec** [comment]
ok...something might have changed from 1.4 to 1.5. I would leave this open for now

**Comment by masakitenchi** [comment]
`Source/Harmony/HarmonyPatches.cs`, L1701:
For any bodypart that has an identical mirrored part.

# Reason
The code only checks if certain hediff is applied to that BodyPartDef, not that specific BodyPartRecord

EPOE should have a solution, but I couldn't figure out how it works
