### ISSUE TITLE
Wrong discharge value in the English description.

### ISSUE THREAD

**Issue by AndriiBr** [skyarkhangel/Hardcore-SK#3925]
I tried to create an MR with a fix, but this is prohibited by the repository settings.
So here's a description of the problem:

**Affected items:** [Makeshift fuse, Circuit Breaker]

**Item:** Makeshift fuse
**Problem:** Wrong description of discharge value.
**Place:**
https://github.com/skyarkhangel/Hardcore-SK/blob/0df28734a6f359137d66b4850958ffef9df369a2/Mods/RT_Fuse/Languages/English/DefInjected/ThingDefs/Building_RTMakeshiftFuse.xml#L5
**Correction:**
`<Building_RTMakeshiftFuse.description>A simple fuse. Handles up to 3000 Wd discharge, will require repairs if tripped.</Building_RTMakeshiftFuse.description> `

**Item:** Makeshift fuse
**Problem:** Wrong description of discharge value.
**Place:**
https://github.com/skyarkhangel/Hardcore-SK/blob/0df28734a6f359137d66b4850958ffef9df369a2/Mods/RT_Fuse/Languages/English/DefInjected/ResearchProjectDefs/ResearchProject_RTBasicFuses.xml#L5
**Correction:**
`<ResearchProject_RTBasicFuses.description>Allows building makeshift fuses; can be placed anywhere on a power network with batteries. Each one is enough to safely dissipate up to 3000 Wd (three standard batteries) discharge, but will require repairs if tripped.</ResearchProject_RTBasicFuses.description>`

**Item:** Circuit Breaker
**Problem:** Wrong description of discharge value.
**Place:** 
https://github.com/skyarkhangel/Hardcore-SK/blob/0df28734a6f359137d66b4850958ffef9df369a2/Mods/RT_Fuse/Languages/English/DefInjected/ThingDefs/Building_RTCircuitBreaker.xml#L5
**Correction:**
`<Building_RTCircuitBreaker.description>A set of automatic circuit breakers. Handles up to 6000 Wd discharge, will flick off if tripped.</Building_RTCircuitBreaker.description>`

**Item:** Circuit Breaker
**Problem:** Wrong description of discharge value.
**Place:** 
https://github.com/skyarkhangel/Hardcore-SK/blob/0df28734a6f359137d66b4850958ffef9df369a2/Mods/RT_Fuse/Languages/English/DefInjected/ResearchProjectDefs/ResearchProject_RTCircuitBreakers.xml#L5
**Correction:**
`<ResearchProject_RTCircuitBreakers.description>Allows building circuit breakers; can be placed anywhere on a power network with batteries. Each one is enough to safely dissipate up to 6000 Wd (six standard batteries) discharge, and will need to be manually reset if tripped.</ResearchProject_RTCircuitBreakers.description>`

**Comment by TheLonerD** [comment]
Нужно делать форк, закоммитить в него и уже "предложить" изменения в виде PR. В любом случае спасибо за корректировку.
