### ISSUE TITLE
ERR: [Site_label] [detected]

### ISSUE THREAD

**Issue by AndriiBr** [skyarkhangel/Hardcore-SK#3930]
From time to time, tasks without a description and reward appear. 
![0001](https://github.com/user-attachments/assets/1b2aa392-77c7-4de3-848e-1e3ec97ad20d)

They all belong to the same type - Camp Loot 
![0002](https://github.com/user-attachments/assets/0a1c35d7-ca68-44b0-963d-c7152ef996f6)

But not all tasks of this type are broken.
Here's an example of a working one:
![0003](https://github.com/user-attachments/assets/c5cab010-8eff-4eee-b1fe-e360269d88ee)

**Comment by TheLonerD** [comment]
Проверь имя пешек, название поселений и фракций. Скорее всего у кого-то в названии имеется квадратные скобки.

**Comment by TheLonerD** [comment]
Возможно ещё у некоторых предметов имеются в названии квадратные скобки.
Но по трём скриншотам и без логов невозможно сказать точно, да и мне лень угадывать.
