### ISSUE TITLE
Placing doors with furniture nearby

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#394]
If I have a situation like the following, where W = walls, B = barrel, . = empty:

. W .
. . B
. W. 

when I try to place a door between the two walls, I get the message;
"The door can be placed if there is a support structure on each side..."
and I cannot place the door.

Moving the barrel eliminates the problem and I can place the door.

**Comment by jnkyacc** [comment]
Door should have free passage(1 free tile for "exit" and "entrance").

.W.
.D.
.W.

**Comment by ScottS9999** [comment]
I can live with that.   But since the barrel doesn't actually block movement, it doesn't seem intuitive.

**Comment by skyarkhangel** [comment]
Remove this door restrictor.
