### ISSUE TITLE
Fixing the inability to wear gloves/boots with bionic prostheses 

### ISSUE THREAD

**Issue by xwat** [skyarkhangel/Hardcore-SK#395]
I possibly found a solution to #93 

NB: this solved problem for my colonists's limbs, but I have absolutely zero liability for the possible side effects:)

Brief analysis:
The issue with inability to wear boots/gloves is that when a prostheses is installed, the game REMOVES all parts that are beneath it. You can see hediffs in devmode with debug view, btw.

 For example, if you install bionic arm (to LeftShoulder), the game will add hediff bionicArm to LeftShoulder and REMOVE all sub-parts (all tibias or whatever theses bones are called,  a hand and all fingers!) That's why if you have 2 full (arms/leg) prostheses it is impossible to wear gloves/boots.

The fix I suggest is code-based, so only Sky can adopt it. It works like this:
1) Replace <workerClass> for every full limb replacement(bionic/advanced bionic/cybernetic arms/legs) from Recipe_InstallArtificialBodyPart to Recipe_InstallArtificialBodyPartBionic
2) Add the following Recipe override to Core_SK:
It basically restored all absent subparts of the limb when applied and only when the original surgery was successful.

```
namespace RimWorld
{
    public class Recipe_InstallArtificialBodyPartBionic : Recipe_InstallArtificialBodyPart
    {
        public override void ApplyOnPawn(Verse.Pawn pawn, Verse.BodyPartRecord part, Verse.Pawn billDoer,
                                         List<Verse.Thing> ingredients)
        {
            base.ApplyOnPawn(pawn, part, billDoer, ingredients);

            if (billDoer == null)
            {
                Log.Warning("Billdoer is null ");
                return;
            }

            // botched surgery
            if (!pawn.health.hediffSet.HasHediff(recipe.addsHediff))
            {
                Log.Warning("did not found hediff " + recipe.addsHediff );
                return;
            } 
            // only 'heal' deleted parts for bionic prostheses, not for peg legs!
            if (!recipe.addsHediff.addedPartProps.isBionic)
            {
                Log.Warning("addedPart is not bionic, will not restore");
                return;
            }

            foreach (var subpart in part.parts)
            {
                if (subpart == null)
                {
                    continue;
                }
                if (subpart.Equals(part))
                {
                    continue;
                }

                BodyPartDamageInfo bodyPartDamageInfo = new BodyPartDamageInfo(subpart, false);
                DamageInfo dinfo = new DamageInfo(DamageDefOf.RestoreBodyPart, 1, null, bodyPartDamageInfo);
                pawn.TakeDamage(dinfo);
            }
        }
    }
}
```

I'd be happy to hear your thoughs on possibility of adopting this fix OR fixing the problem in some other way.

**Comment by jnkyacc** [comment]
Does it not make to have something like (Flesh hand - Bionic arm - Flesh shoulder) ?

As I know Tynan said that it is intentional.

**Comment by xwat** [comment]
What do you mean? Actually, no body part is bionic ever. 'Bionic' is just a property of added headiff that some prostheses add. It doesn't actually replace the bodypart.
And if, say, shoulder adds bonus headiff to manipulation, this headiff is propagated to all its sub-parts (arm, hand, fingers) even without this change (even if they are absent!). You can check it out in the debug menu.

**Comment by xwat** [comment]
Ping.. As far as I know, this is a rather annoying issue; would be great to hear some feedback on the patch feasibility.

**Comment by skyarkhangel** [comment]
Ok. i can try soon

**Comment by skyarkhangel** [comment]
Tested. Its  not solve problem.

**Comment by skyarkhangel** [comment]
Try in test in next update
