### ISSUE TITLE
Return ZiTools objects seeker mod

### ISSUE THREAD

**Issue by emulatethis777** [skyarkhangel/Hardcore-SK#3955]
In my opinion(and may be almost all players) ctrl +f too complicated for use.
ZiTools does it's work better.
[Link to 1.5 mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3280114640)

**Comment by TheLoneTec** [comment]
so while i agree its simpler to use, it doesnt have as much functionality. Ctrl + f can search for things in inner containers and on pawns.

**Comment by TheLoneTec** [comment]
its also not really that much more complicated, there is only one search bar, it just allows you to save preset searches for future reference
