### ISSUE TITLE
[bug] Weapons shown as pink squares

### ISSUE THREAD

**Issue by wangqinNick** [skyarkhangel/Hardcore-SK#3970]
<img width="847" alt="截屏2024-11-15 20 22 48" src="https://github.com/user-attachments/assets/49971dfd-0faa-4c41-a376-a955b137c16e">
<img width="1467" alt="截屏2024-11-15 20 23 45" src="https://github.com/user-attachments/assets/a7f066a6-8223-48dd-bbd8-5534ff2fe83e">

System: Mac
Version: 1.4.3901
Master Branch

**Comment by TheLoneTec** [comment]
Need Hugslib log. As this is most likely a Addon/Install/load order issue as the 1.4 branch works fine.

**Comment by TheLoneTec** [comment]
https://discord.com/channels/272340793174392832/1154415624659939388

step to bug reporting. Its on the discord. But also, we have a launcher that does this automatically for you.

**Comment by TheLoneTec** [comment]
Without the Hugslib log, we cant help you, you need to post it here.
