### ISSUE TITLE
catapult crate cant be constructed 

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#399]
1. it takes 209 work to finish which is fine but it needs a state so u can stop and start when neeeded.
2. it wont finish building the crate it gets to around 60%ish then the progress bar disappears and it can never be finished.

logs had no errors

**Comment by skyarkhangel** [comment]
should work fine. Its recipe sctructure 100% like other recipes.

**Comment by sidfu** [comment]
ok with newest build its workign again but the progress bar for it still disappears at around 70%.
