### ISSUE TITLE
Balancing issues about ultra solid and solid alloy

### ISSUE THREAD

**Issue by crusender** [skyarkhangel/Hardcore-SK#40]
i see some receipt that dont use all kind of ultra solid and solid alloy. like magnetic material, need to make a new chain of material for build it, dont event take alpha solid.

**Comment by Masquerine** [comment]
Kind of confused on your wording here, but are you suggesting alpha/beta poly be in their own category?

**Comment by crusender** [comment]
no some receipt like for make magnetic material only use specific ultrasolid (3 of them), i cant use other kind ultrasolid to make them.

**Comment by Masquerine** [comment]
I see. Having had a look at the other ultrasolid descriptions/mixes, there should be a few more enabled on there as they related to magnetism. Will add onto it. Any other recipes with a similar issue?

**Comment by crusender** [comment]
Electronic Components, should use all high conductivity material not only use copper alloy.

**Comment by Masquerine** [comment]
Added High Conductivity Alloy category to Electrical Components. I looked over each of the metals for the Ultrasolids, and it looks like 6 of them should be magnetic-capable. I'm going to add a note about magnetism to the related metals.
