### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#401]
Just turned winter, I told all my pawns to go out hunting (1st year) and it just randomly crashed. 

Fresh install as of 3-4 hours ago using today's commit being 

commit 72aecad766dacd17c260d7aee3b3b551aa6cd877 @Ivanzyfer Ivanzyfer committed 11 hours ago

I've enabled; Crafting Hysteresis, Fluffy's Worktabs & Mountain Temp when compared to default, I've also attempted to install the new textures, as of a few commits ago, as you'll see in the ludeon forums where I mention it

http://pastebin.com/hDqJFHnM

http://pastebin.com/KgpGq5Ab

Update - It might have been a bad incident in the queue, as I've played past that point and around the time it crashed I get blight,(Could be coincidence but more info the better) so I'm assuming it was a incident crash, not sure what one though.

Edit happened again this time as soon as a raid turned up on my screen it crashed

http://pastebin.com/pF2CnKeg

http://pastebin.com/wahD4uJa

**Comment by skyarkhangel** [comment]
It looks like the memory usage reached its peak and then crash.

**Comment by zakhad** [comment]
With the changes to the sound files essentially lowering memory usage would make this obsolete now?

**Comment by skyarkhangel** [comment]
yep.
