### ISSUE TITLE
Using your fists are more effective than early game melee weapons against high armour targets

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#402]
10 minutes of beating on a scyther in melee who had both scythes / and sight/smell sensors destroyed (assumed the particular parts have low armour value) but we're unable to put a dent in any other part of his body (rarely my 19 damage axe was able to get the occasional damaging hit) but as soon as I unequipped my weapons off they went to town on the poor scyther, and it went down in seconds. :S

My pawns are all humans who do 5 damage a hit in melee unlike the norbal etc they're the lowest hitting pawns.

**Comment by ScottS9999** [comment]
v0.15a debuffed fists, so Tynan is at least aware of the problem.  I haven't played it, so I don't know if his solution works well or not.
