### ISSUE TITLE
Strange fps drop

### ISSUE THREAD

**Issue by nighelt** [skyarkhangel/Hardcore-SK#404]
Some strange bug that lowers fps.
I can not understand where it comes from.
There is a way to solve this problem?
Thanks in advance :) .

original fps: 60
Fps with the bug: 23

![screenshot_6](https://cloud.githubusercontent.com/assets/22324671/19274852/f1aac888-8fd1-11e6-8afc-d12a2647e2b6.png)

**Comment by skyarkhangel** [comment]
Bug in explosion tick. So its related to explosions. Need help to reproduce again

**Comment by nighelt** [comment]
How can I help you duplicate the bug?
I have to post things like save or log?

Thanks in advance :) . *

**Comment by skyarkhangel** [comment]
Need help how to reproduce to start this ticks with explosion bugs. You show already happened bug ticks..

**Comment by skyarkhangel** [comment]
I suppose fix this error in latest updates.
