### ISSUE TITLE
Terminator

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#405]
Playing on a 9/30/16 build, so these might be outdated already.  Please delete if that is the case.

1) I had a plunderers event.  The normal 4 insects show up and wander around.  And then a terminator (a T-X, I think) comes out of nowhere and rips a colonist's leg off.  Was the terminator related to the plunderers event?  Or did it show up unannounced?

2) The other 4 colonists lined up and went full auto on it with assault rifles.  To my surprise, I rapidly "killed" it.  I had done maybe 5-10% damage to it before it went down, with no significant damage to critical systems.  It looked like it was a pain knockdown.  Is it intended to go down that quickly?

3) After it got back up, it bashed a hole in the wall of my fort and started tearing up the furniture.  When one of my colonists came into sight, it grabbed a melee weapon off the floor, ran toward my colonist, ran back, put the melee weapon back down, and then ran to attack unarmed.  What's going on there?

4) In that build, incendiary devices didn't work right, so it ended up being a colony ending event.  I played with dev mode in a current build and determined that incendiary devices do actually kill it permanently.  Is that the intended way to actually kill them?

5) Balancing - I feel like the terminator should be much harder to knock down.  30 rounds from an assault rifle and an incendiary grenade, and what should be a really big threat is neutralized.  On the flip side, I feel like if they are harder to knock down, they should not show up until a base is rather advanced.  The event should not be a guaranteed colony ender.

I am starting a new fort on the current build this evening, so hopefully I will be able to provide further feedback.

**Comment by skyarkhangel** [comment]
1) Not related. Pure coincidence, the guest could be covert agent.
2) in last update removed pain offset, now like mechanoids.
3) In some earlier updates fixed AI mechanics with droping weapon.
4) Need check with latest update. Full reworked damage system.
5) Now there are 3 prototypes, each has its own bonuses. They became harder.

**Comment by ScottS9999** [comment]
Again I had a terminator appear out of nowhere, I assume from a covert agent guest.  It one-shotted my best crafter, and I didn't even know it was there until she was dead.  It has happened twice now, and I find it really annoying to lose colonists with zero warning, so I'm considering recommending some sort of notice that there is a terminator on the map.  But then, the entire point of a covert agent is that it is covert, so maybe the attack should be a surprise.

Thoughts?
