### ISSUE TITLE
Request - meat/corpse categories

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#406]
Currently corpses and meat are divided into humanoid and animal.  Is it possible to add an insect category as well?  Meals containing insect meat give a mood debuff, so it would be nice to separate that meat from the rest.

**Comment by skyarkhangel** [comment]
its possible.

**Comment by skyarkhangel** [comment]
nope. not possible for now. Corpses add to this category automaticaly using internal vanilla code.

**Comment by skyarkhangel** [comment]
it could be done by detouring method, but for now, i try not to increase their number to not so important things.
