### ISSUE TITLE
Advanced Mine Extractor Collapses 

### ISSUE THREAD

**Issue by nemesis688** [skyarkhangel/Hardcore-SK#408]
Upon being constructed the Advanced mine extractor immediately collapses  saying that a support was removed.

**Comment by skyarkhangel** [comment]
Need to install evenly in the center.

**Comment by nemesis688** [comment]
I have tried, There seems to be three green spots you can put it. All three, including perfectly center all result in an instant collapse.

**Comment by skyarkhangel** [comment]
Would be fixed in next version for A15. Bcs its related to CCL error. Closed.
