### ISSUE TITLE
the issue with refueling

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#411]
its known how they wont refuel but found some info that might help. right now after the first time its refueled they wont refuel anything but i found that if when they look for a job and they 2 blocks from something that needs to be refueled they refuel it.

doesnt that mean for haulers they basicaly not seeing the refuel job as its not broadcasting it far enough.

update. think i found what it is for refueling now. the refuel at seems to be wrong instead of refuel at its acting more like refuel up to this ammount. in my playing anything below 50% they keep ignoreing the refuel jobs 50% seems to do the trick and have them refuel them and even refuel them when they on where at 20% they wouldt refuel them when on.

**Comment by skyarkhangel** [comment]
Ref. system updated
