### ISSUE TITLE
Petfollow not working?

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#415]
The follow icons show up in the order menu, but not on the animal itself or in the animal tab.  The icons in the order menu don't appear to do anything.  Either it is broken or I'm missing something.

**Comment by dr3am3r5** [comment]
I can confirm that. Pet follow doesn't work even after training them.

**Comment by skyarkhangel** [comment]
Closed. Petfollow fixed in latest 4.2 for A14.
