### ISSUE TITLE
New skynet event

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#417]
I've explained in detail on the forums, but the skynet event needs to have a fixed spawning amount or a custom raid event, it shouldn't use the typical raid formula at least in this one instance.
 
After several failed attempts / reloads I found that

4 terminator's that outright destroyed me,
3 terminator's and I was able to win barely with cheese/kiting 
2 terminator's was realistically doable with the odd acceptable casualty.

Of course it's subject to many factor's my relevant details are on the forums. 

I understand that the mod is meant to be hardcore but when each terminator has vaguely 900 health per body-part that really isn't balanced against my weak-sauce 40 torso hp humans. (I could hit him 20-50 times and he'll not die and I get attacked once or twice and I fall over, there is very little skill in bad RNG)
![bugged texture](https://cloud.githubusercontent.com/assets/5264667/19506938/629365c8-95c7-11e6-9cf1-f1f51a9ca5bf.jpg)

**Comment by zakhad** [comment]
The image was an edit in, for some reason reloading the game makes them lose there textures.

**Comment by skyarkhangel** [comment]
Fixedin last update.

**Comment by skyarkhangel** [comment]
Compatible with savegame.
