### ISSUE TITLE
Placed Locker accessories cause problems with beds

### ISSUE THREAD

**Issue by Nenaka** [skyarkhangel/Hardcore-SK#418]
A Locker actively placed on the map causes "Exception in BreadthFirstTraverse" error. Beds end up having issues such as:

- Newly placed beds inherit problems and is shown upon loading save.

- Uninstalling/deconstructing a medical bed just sets it back to nonmedical, and is treated as a new job so the colonist just walks away to do something else or stands there for a moment.
- Installing a bed dupes a ghost onto the ground. Installing the ghost just moves the original.

Uninstalling/deconstructing/deleting the locker prevents these issues and fixes those new beds.

![lockerbug](https://cloud.githubusercontent.com/assets/18184133/19622937/adbe149e-98f1-11e6-88df-c74ae1e07c97.png)

**Comment by skyarkhangel** [comment]
ok. soon fixed.
