### ISSUE TITLE
Military box accessory has no texture when full

### ISSUE THREAD

**Issue by Nenaka** [skyarkhangel/Hardcore-SK#419]
Is it trying to find a "full" texture variation when there isn't supposed to be a difference? Otherwise works fine

![militaryboxfull](https://cloud.githubusercontent.com/assets/18184133/19622955/5718b0b2-98f2-11e6-8e5f-3e7e71677f8a.png)

**Comment by skyarkhangel** [comment]
ok. soon fixed.
