### ISSUE TITLE
Not killed during GiveInjuriesToKill +NullReferenceException

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#42]
When you first embark to a map, if a Centipede or Terminatrix is hidden in a room the debug log gets spammed with System.NullReferenceException. Attempting to damage or kill either entity provokes another error: They refuse to die given injuries to kill them. Additionally, Terminatrix is immune to the kill command and damage commands. She could not die at all. I was only able to destroy her using the bomb command around 100 times. She kept flashing a white sphere around her. Picture attached shows errors. Debug log continued to be spammed by the null error after death.
![mecherrors](https://cloud.githubusercontent.com/assets/16396520/13382449/be48eb6e-de42-11e5-9165-9dca8c40839e.jpg)

**Comment by skyarkhangel** [comment]
it is a consequence of that the faction Skynet use "mechanoid type" faction, but they are hostile to each other. I try to rework skynet faction.

**Comment by skyarkhangel** [comment]
it seems no problem anymore.
