### ISSUE TITLE
Cannot load sound on Linux

### ISSUE THREAD

**Issue by LimeCookies** [skyarkhangel/Hardcore-SK#424]
It seems that the commit upgrading sound to mp3 have broken something. When it run, none of the mp3 is loaded. The log looks like that:

Streaming of 'mp3' on this platform is not supported

(Filename:  Line: 390)

Streaming of 'mp3' on this platform is not supported

(Filename:  Line: 390)
...

If you don't mind me asking, why do you prefer to change to mp3? If I'm not wrong, unity used to have poor support for MP3, due to licensing issues. Though, I think the last patent with MP3 will expired by December.

**Comment by skyarkhangel** [comment]
with ogg format, Rimworld has problems. So, need to convert into wav :/

**Comment by LimeCookies** [comment]
I suppose all the sound loading is done by Rimworld, and none of the loader is written the .dll of the mod?

**Comment by skyarkhangel** [comment]
mp3 readable in your version of Linux? If not, you have problem with sound mixer. Check this.

**Comment by LimeCookies** [comment]
mp3 can be played by other programs on my Linux. I'm not sure why only rimworld didn't support mp3. 

Though, I have tried converting all the mp3 to wav, and it works smoothly for me now.
