### ISSUE TITLE
will put 2 types of items for refueling

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#425]
so far only seen it on campfire but they will put or more if ther not enough of the already burningitem. the issue is that they will keep putting it over and over. the 2nd item dont increase the burn time either. ejecting the item does give it back thou.

**Comment by skyarkhangel** [comment]
ok. About mechanics There to types of refuel. 1) when burner empty 2) when burner have items.
So i need to add check, if item in burner disalowed, then auto remove?

**Comment by sidfu** [comment]
well it needs some form of check. right now say u put it at 50% refeul and it curently is at 49% with logs. if they go gete charcoal they will keep putting characoal over an dover and over since the second fuel item dont count to the burn time.

before u updadted the fuel system they never grabbed a differnt material they would only grab the type that was already in it.

**Comment by skyarkhangel** [comment]
Fixed
