### ISSUE TITLE
Released prisoners suicide

### ISSUE THREAD

**Issue by LEEROU** [skyarkhangel/Hardcore-SK#428]
Released prisoners can commit suicide.

**Comment by LEEROU** [comment]
upd: Prisoners can instakill each other through all map, if released and got tantrum.

I suggest you removing prisoner events for a while, to fix massive bugs, like fuel and interface.

**Comment by skyarkhangel** [comment]
We haven't "massive bugs". Rework this event, now takes into account prisoner mood.
