### ISSUE TITLE
Trader has no money, retrade=crash

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#43]
This one happens when you do a trade with a trader (was using the passing ship one) and in the transaction you take all of the trader's money. Immediately after the trade, re-trade with the same trader without unpausing the game and you'll encounter this error.
![tradernomoney](https://cloud.githubusercontent.com/assets/16396520/13447696/7d206810-dfeb-11e5-96a0-5249b8874ba2.jpg)

**Comment by Masquerine** [comment]
This appears to be a vanilla issue as well. I let the mod author know on his forum thread. See what happens I suppose.

**Comment by skyarkhangel** [comment]
Yep. And sent bug to mod author.

**Comment by skyarkhangel** [comment]
Ok

**Comment by Masquerine** [comment]
Supes the mod author of this is currently working on fixing it. :)
