### ISSUE TITLE
Fueled Stove says it can accept peat, but can't.

### ISSUE THREAD

**Issue by Rufert** [skyarkhangel/Hardcore-SK#430]
It isn't in the fuel tab.

**Comment by skyarkhangel** [comment]
where you find that Fueled Stove could accept peat? its not true.

				<fuelFilter>
				  <thingDefs>
					<li>Charcoal</li>
					<li>Coal</li>
					<li>Kindling</li>
				  </thingDefs>
					<categories>
					  <li>Wooden</li>
					</categories>  
				</fuelFilter>

**Comment by Rufert** [comment]
http://i.imgur.com/VBTCCdW.jpg 

Here.

**Comment by skyarkhangel** [comment]
ok. wrong discription. soon del this info.

**Comment by skyarkhangel** [comment]
Fixed
