### ISSUE TITLE
PrepareCarefully: Pawns just spawn in Pods and then get killed in the Meteorshower on new map.

### ISSUE THREAD

**Issue by TobWalter** [skyarkhangel/Hardcore-SK#431]
So whenever I start a new colony, I want to select my own pawns (in the Crashlanded Scenario). But on Maploading they just start in their landingpods and obviously die during the meteor shower and the big shipwreck landing on top of them.

This can't be intended, since there would be no purpose of using EDBPrepareCarefully.

**Comment by skyarkhangel** [comment]
Known problem, it can't be fixed without Edb PC compatibility patch. We make standard "classic" scenario for playing with Edb PC. Also, soon would update with reworked vanilla's 2 events: podcrash, resoursedrop with Crashlanded variant.
