### ISSUE TITLE
Please make metal gauntlets better than leather for physical protection

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#432]
Not only do these metal gauntlets have a higher quality level they also have an armour buff due to ancient modifier also in perfect condition.

If you want to argue that metal gauntlets don't protect against blunt trauma than change it so it also requires leather as internal padding (You don't have access to cloth until you get power, this early on and doesn't make sense for the smithy to have recipes that require cloth at least as the mod currently stands)

What I'm suggesting is for the base value or the scaling value to be increased so it always starts around 20% give or take various materials not 5% its beyond pitiful; also the leather gloves should have less sharp resistance.

![buff](https://cloud.githubusercontent.com/assets/5264667/20033960/4ce5ea06-a3a6-11e6-8cd7-0ed161cd3f26.jpg)

Don't get me wrong I appreciate everything you do for the mod and its community, It's probably something that has been miss out due to the sheer amount of items/modifiers/material-types that have been added.

**Comment by skyarkhangel** [comment]
hehe, yes need some balance

**Comment by zakhad** [comment]
I think.... I fucked up, ancient being that they're only 25% of normal :/ 

![gauntlets](https://cloud.githubusercontent.com/assets/5264667/20085388/7189d406-a560-11e6-8348-6bc91cb7a0ff.jpg)
