### ISSUE TITLE
New escape pod event is badly bugged

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#435]
Drops a tremendous number of escape pods all over the map, obliterating all life.

I have a save if you want it.

![escape pod bug](https://cloud.githubusercontent.com/assets/22219720/20155530/4bc51fba-a69a-11e6-8fe6-a97230b45ead.png)

**Comment by ScottS9999** [comment]
Now that I think about it, I had one "normal" escape pod event prior to this that worked as intended.  So it's not happening every time.

**Comment by sidfu** [comment]
check the save its possible the event got stuck and is instead constaly fireing. if it is u can edit the save and remove the event with a text editor.

**Comment by skyarkhangel** [comment]
Fixed? in last update.

**Comment by skyarkhangel** [comment]
But its looks epic :D

**Comment by ScottS9999** [comment]
Yeah, it was pretty cool.  :)  Laggy as hell though.

**Comment by skyarkhangel** [comment]
still work :/

**Comment by skyarkhangel** [comment]
fixed
