### ISSUE TITLE
Alloy

### ISSUE THREAD

**Issue by Clownvenus** [skyarkhangel/Hardcore-SK#436]
Hi everybody !

I arrived at a level where I have to start produce a lot alloy for developing my colony. So what's is the best way to produce alloy?

Furnace for coal+Quarry for ore+electric smelting furnace?

**Comment by caesius90** [comment]
you mean steel alloy right? then
no quarry.

use mine extractor for coal and steel, and electric smelt table for making.
smelt tables made from titanium have most fast work speed factor. tin and aluminium also good choice.

**Comment by xwat** [comment]
Please do not discuss general game strategy on GitHub! Issues are used to report **bugs**, and not for all-around game chat. There are 70+ issues, so please don't dev's life harder than it needs to be!

**Comment by Clownvenus** [comment]
Sorry for that, i thinked this website it's for posting questions about the game :s
