### ISSUE TITLE
plasma generater does nothing.

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#439]
just try to use the generater in game. you will understand it.

if it works as intended and no problems at all, plz let me kn how can i use them.

ps : not plasma reacter. it works good. im talking about plsma generater (smaller ones)

**Comment by skyarkhangel** [comment]
Checked. You are right. Something wrong.  Soon fix.

**Comment by skyarkhangel** [comment]
fixed in next update.
