### ISSUE TITLE
new escape pod update bug (Yellow event)

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#449]
commit cf2b314a0cd3c5a92df6f8e09169a7cae3431460

Most of the time the escape pod works fine. But occasionally you'll get one that makes your game insufferably laggy  (1-10 fps on speed 1) reloading a autosave a few minutes before before the queued incident occurs and ill get a different escape pod event and it'll work fine.
 
Deleting all the items via destroy doesn't seem to remove the lag, same with destroying the terrain via console doesn't fix it maybe its a script?

![bug1](https://cloud.githubusercontent.com/assets/5264667/20248957/6e59ac94-a9e7-11e6-8cdd-a575de53624b.jpg)

Upon saving the game to make a backup encase you'd want the save and I get this error spam in the console so I assume giving you the save won't work.
![bug2](https://cloud.githubusercontent.com/assets/5264667/20249036/c79b71c4-a9e8-11e6-86e7-658f5e9c4095.jpg)

**Comment by skyarkhangel** [comment]
fixed in last update.
