### ISSUE TITLE
feature: Improve mending building 

### ISSUE THREAD

**Issue by evgeny-k** [skyarkhangel/Hardcore-SK#45]
nowadays it is pain to search required item in mending building so it should be improved.

inherit `SK_Mending.ITab_Mending_Building` from `StorageSearch.ITab_Storage_Enhanced` or just use `StorageSearch.ITab_Storage_Enhanced`.
as a result StorageSearch and load/save store features will be added and 'items' tab will work similar to one in `NanoScanner` building

**Comment by skyarkhangel** [comment]
"Mending" would be fully rework soon.
