### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by LEEROU** [skyarkhangel/Hardcore-SK#452]
![nice](https://cloud.githubusercontent.com/assets/13592373/20268674/94eb1f3e-aa99-11e6-845e-3cf1e5091503.png)
![shit](https://cloud.githubusercontent.com/assets/13592373/20268675/9504473e-aa99-11e6-96e0-9818398705f0.png)

**Comment by skyarkhangel** [comment]
Version? In latest version was additional fix

**Comment by skyarkhangel** [comment]
Fixed. All this errors.
