### ISSUE TITLE
Raptors

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#456]
Eggs: Being able to buy 30 silver each then being able to sell them for 2000 after a month is completely broken, as much as I enjoy it it really ruins the sense of progression. I just let them roam the map rarely do they have any problems with wildlife unless its a raider with guns and once they're juvenile they pretty much sell for the same value as an adult. 

Suggested prices of 250-500 per egg as its extremely hard to get tame one, and it'll probably murder you if you don't pay attention if it goes berserk. They make  god damn awesome fighting pets if  a little very hard to get obedience training 90% wild :P but its a worthwhile investment. 

Also can you reduce the base volume of the raptor sounds, its obnoxious as hell, (50% reduction) its way too loud compared to everything else, as well as the frequency of how often they're played down by 50%

**Comment by caesius90** [comment]
raptor eggs must not be able to be bought from merchant for balance i think.

but only found in ancient ruins or expedition.

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
changed in next update.
