### ISSUE TITLE
Butchering priority 

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#457]
A few days ago / commits like 3-4 it was set that you'd always cook before butchering now its been reversed. Was that intentional? 

For the time being I'm using my own workaround by using the "dwarf therapist" module of fluffies worktabs to override the default priorities so that cooking is always higher than butchering but I just wanted to know if it was intentional change or not.

**Comment by skyarkhangel** [comment]
not quite sure what exactly the problem.

**Comment by zakhad** [comment]
Butchering should always be lower, if you use the manager to hunt then they'll just run off to the edges of the map picking up every corpse, due to being unrestricted (Which is what you want) first before cooking, limiting the area of where you collect corpses to butcher from is counter productive.
