### ISSUE TITLE
Mechanoids AI bug 

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#459]
I'm using commit 65205bb08b6bbeccfd8b4061018bf2f6ebaa640b

Obvious gender joke aside, Why an earth are the mechanoids deciding to dig rather than fight me?

![mechs](https://cloud.githubusercontent.com/assets/5264667/20363601/c240479e-ac37-11e6-8656-c630bca24e2b.jpg)

https://www.dropbox.com/s/ttg3795ijla5icz/Zakhadia.zip?dl=0 - pre psychic ship damaged (Unreleased mechs) save file .zip format (Cant upload .zips for some reason even though it says it accept's them)

**Comment by skyarkhangel** [comment]
Mechanoid using 100% Rimworld AI.
So its vanilla bug.
