### ISSUE TITLE
feature: add categories for leather

### ISSUE THREAD

**Issue by evgeny-k** [skyarkhangel/Hardcore-SK#46]
e.g. 

- Insulation_Cold|Insulation_Heat|ArmorRating_Blunt|ImmunityGainSpeedFactor|etc
 - low (<100%)
 - standard (=100%)
 - high (>100%)

it will be usable for `TableLoom` and for stockpiles

it can be implemented via tags or via comparing correspondent values in run-time

**Comment by Masquerine** [comment]
I'm already working on addressing the entire leather category in more ways than simply this. Still mid-process of doing it. It'll affect categories, recipes, apparel, ect, making leathers much more useful than simply being identical in every way, shape and form (for the most part as it currently is, anyway).

**Comment by Masquerine** [comment]
One more day or so and I'll have this overhaul ready.

**Comment by Masquerine** [comment]
Kay, edit is in. That took far too long to define. lol.

**Comment by skyarkhangel** [comment]
Leather generate with race. At this moment we couldn't we can not directly add thingcategories for each of them. Please, use help to find and compare leather stats.
