### ISSUE TITLE
campfires can stop makeing heat

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#460]
there no error they just stop heating the room. they can still be cooked on and still show the temp from fuel but they dont heat the room.

thought it was like the audio bug(where sound stops) but seems once it happens its perm for the save.

ill provide the save,log and such after a big internt is screwyy today.

btw the quality builder error from decon of cairns and totems is still there.

update.

found the issue with campfire not making heat. it seems if u have a campfire outsde and put a roof over it but no walls around it bugs all ccampfires on the map and they make no heat till the outside campfire is deconed.

**Comment by skyarkhangel** [comment]
In next update, fixed
