### ISSUE TITLE
The commit crash the game during initialization

### ISSUE THREAD

**Issue by SergeyLutsky** [skyarkhangel/Hardcore-SK#463]
The commit https://github.com/skyarkhangel/Hardcore-SK/commit/8fdb4bbad93fdef9383b8a5c6cb8df4bd0bf954c
crash the game 
![untitled](https://cloud.githubusercontent.com/assets/3072186/20453472/4008a6dc-ae2f-11e6-9a01-064b000b8766.png)

**Comment by SergeyLutsky** [comment]
It seams, not last commit crash the game. When i replace ModsConfig.xml file in "...\AppData\LocalLow\Ludeon Studios\RimWorld\Config" folder ant then start the game, this errors are occurred. FYI: after closing the game   ModsConfig.xml file rollback to initial state(contains only "Core" mod)

**Comment by caesius90** [comment]
it also occurs to me.
i replied this problem in forum too. looks like it is not ours(users) problem.
https://ludeon.com/forums/index.php?topic=12996.4035

**Comment by SergeyLutsky** [comment]
ok. thx for the quick response.

**Comment by SergeyLutsky** [comment]
Small update, the all code after commit https://github.com/skyarkhangel/Hardcore-SK/commit/83c2f7c7d119fedf7fa3339bfbf1695eea5d65ee does not work

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
i'll make soon full update.

**Comment by skyarkhangel** [comment]
Sorry. Fixed, its my bad)

**Comment by MechanosG** [comment]
Heya.  I'm having this problem too with the latest 1407 revision on a clean a14 install.  Wiped mods folder, backed up core folder, downloaded HSK, copied over mods folder contents, moved ModsConfig.xml into config folder, etc.  Far as I know this is the correct installation procedure.  Results in what appears to be the same problem
![screenshot 2016-11-19 15 00 37](https://cloud.githubusercontent.com/assets/4360512/20466931/2b1e7cb2-af31-11e6-898a-b52f3fa97337.png)
.

**Comment by skyarkhangel** [comment]
MechanosG try this:
in AppData\LocalLow\Ludeon Studios\RimWorld\Config
where modconfig, delete KeyPrefs.xml, Knowledge.xml, Prefs.xml
