### ISSUE TITLE
mod recommendation

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#464]
work smarter : https://ludeon.com/forums/index.php?topic=27331.0
- The cooks gather ingredients as much as to near storage before start cooking.
- The constructors and haulers gather resources as much as to near storage before start building.
- If storage is farther than their working place than start working immediately.
- If worker is incapable of hauling than work as normal.

quite looking simple, light, and useful mod. so i recommand it

**Comment by sidfu** [comment]
tbh u dont realy need u can
 plan out your food storge thats why there so many types of barrels and storage bins.
when u plan your storage room think of whats most common an build storage for it closer.

**Comment by skyarkhangel** [comment]
For this time, all mods that require HugsLib will not be added. This mod require this library. I will deal with them in the future. When update SK to a15/16.
