### ISSUE TITLE
Q. was it changed? about plasma generator

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#466]
the generator gave out "massive heat" in old versions.
(as FAQ said, the genarator requires massive study and resources but it takes advantages from the massive heats )
now it give out quite small heats. ..

is this intended???

**Comment by sidfu** [comment]
as i havent got that far in a while not sure but if it is a bug then its probaly a byproduct of changeing the fuel system

**Comment by caesius90** [comment]
if its not a bug, then the generator now quite useless building...

**Comment by skyarkhangel** [comment]
it shoulf work like in old version.

**Comment by caesius90** [comment]
checked in latest version. it still give out small heats.
in old version, temp rise up to around 1200C? 1500C? in 1x1 small room beside the generator (definitly over 1000)
now, it goes up just under 200C = similar to other generator like coal generator
(other small difference is that, it give out heat when it is fully charged and when it is charging, it absorbs heat inversely. in old version, temp goes up when it is changing)

Sky, if it is not intended, would you look into this problem? thanks.

**Comment by caesius90** [comment]
@caesius90
d
