### ISSUE TITLE
Embrasures?

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#467]
I saw they got fixed in CR, then that CR was moved over to hardcore sk.  Was the embrasure fix moved?  In a commit from yesterday, they are still not blocking movement.

**Comment by skyarkhangel** [comment]
??
all embrasures not block movement, only makes very slower.  Can't to make possibility =  immposible, due to AI stupid bug, that make game much easier.  So, one more again. Adding to the game embrasures, through which you can not pass - its cheat to player.

**Comment by SmokeyUnicycle** [comment]
As Sky says, if you make them act like walls, the AI breaks and runs around helplessly in circles while you gun them down with impunity.

**Comment by Dunkhan** [comment]
So what is going on with this? The commit db4f1355e28f8d11bd1d95bdf5ed1cdec874bd3b just set them to impassable. Is the balance issue resolved? Will this be applied to fences as well?

**Comment by SmokeyUnicycle** [comment]
As far as I know making them actually impassible breaks the AI. Maybe something was changed but otherwise that probably needs to be rolled back.

**Comment by skyarkhangel** [comment]
Now embrasures blocking movement
