### ISSUE TITLE
Sometimes unable to generate a new world

### ISSUE THREAD

**Issue by MechanosG** [skyarkhangel/Hardcore-SK#469]
Fresh install.  Selected The Survivor scenario, Chillax Rough storyteller, used the seed "the answer is 42".  After clicking Generate, it waited about 10 seconds then spit this error.
![screenshot 2016-11-21 15 05 22](https://cloud.githubusercontent.com/assets/4360512/20504395/07c01dc2-affc-11e6-813e-e1fb83d69f5a.png)

I was able to successfully create a world via retrying though.

**Comment by skyarkhangel** [comment]
Yep. Known problem with futuristic protheses, when generating faction Orion or Syndicate. I just need to find which specific prosthesis cause this error.

**Comment by skyarkhangel** [comment]
Fixed
