### ISSUE TITLE
Escape pods not spawning pawn?

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#471]
Escape pods are supposed to drop a pod and spawn in injured colonist automatically, right?  I've had two fall now where the pad falls properly, but the pawn never appears.  In one of these instances, the pawn was an abomination.  I got the message where the abomination was announced, but it never spawned either.

**Comment by LimeCookies** [comment]
Check if you're on the newest version (And not the 'stable' version downloaded from forum). I had that problem a while ago too.

**Comment by skyarkhangel** [comment]
Yes, all should work fine.
