### ISSUE TITLE
Экзоскелет

### ISSUE THREAD

**Issue by semareset** [skyarkhangel/Hardcore-SK#475]
Привет Скай!
Багует экзоскелет при создании персонажа, именно обнуляет стоимость(в очках) всех имплантов установленных до экзоскелета. При установке в процессе игры такого не происходит(через **god mode**) Еще кажется из-за него появляется ошибка при сохранении колониста (и при дальнейшей загрузке его), пока не нашел зависимость.

**Comment by skyarkhangel** [comment]
Отлично! Спасибо за инфу.

**Comment by skyarkhangel** [comment]
Removed from spawn. But not fixed yet.
