### ISSUE TITLE
Newer versions of the mod don't work on Linux(Ubuntu)

### ISSUE THREAD

**Issue by LimeCookies** [skyarkhangel/Hardcore-SK#478]
Upon starting the modded game, the log pops up immediately showing red. The main menu screen is from normal game instead of the hardcore SK one. After looking through the log, I believe it's likely something caused by the core_sk mod. 

I've cut the important parts out from the game log:
...
Community Core Library :: Queueing Library Initialization
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Initialized the EdB Prepare Carefully mod
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./RimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./libRimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86_64/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./libRimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/RimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/./libRimWorldLinux_Data/Mono/x86/libmono.so
Fallback handler could not load library /home/user/RimworldSK/RimWorld1249Linux/RimWorld1249Linux_Data/Mono/x86_64/libRimWorldLinux_Data/Mono/x86/libmono.so
Could not execute post-long-event action. Exception: System.TypeInitializationException: An exception was thrown by the type initializer for AchtungModCR.Main ---> System.DllNotFoundException: RimWorldLinux_Data/Mono/x86/libmono.so
  at (wrapper managed-to-native) AchtungModCR.Platform:linux_86_mono_domain_get ()
  at AchtungModCR.Platform.mono_domain_get () [0x00000] in <filename unknown>:0 
  at AchtungModCR.Platform.GetJitMethodSize (IntPtr ptr) [0x00000] in <filename unknown>:0 
  at AchtungModCR.HookInjector.Inject (System.Type sourceType, System.Reflection.MethodInfo sourceMethod, System.Type targetType, System.Reflection.MethodInfo targetMethod) [0x00000] in <filename unknown>:0 
  at AchtungModCR.HookInjector.Inject (System.Type sourceType, System.Reflection.MethodInfo sourceMethod, System.Type targetType, System.String targetName) [0x00000] in <filename unknown>:0 
  at AchtungModCR.HookInjector.Inject (System.Type sourceType, System.String sourceName, System.Type targetType, System.String targetName) [0x00000] in <filename unknown>:0 
  at AchtungModCR.Main..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor (intptr)
  at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) [0x00000] in <filename unknown>:0 
  at Verse.StaticConstructorOnStartupUtility.CallAll () [0x00000] in <filename unknown>:0 
  at Verse.PlayDataLoader.<DoPlayLoad>m__573 () [0x00000] in <filename unknown>:0 
  at Verse.LongEventHandler.ExecuteToExecuteWhenFinished () [0x00000] in <filename unknown>:0 
 
(Filename: /home/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)

Community Core Library :: Library Core :: Validations :: Validated
	ModHelperDef :: Community Core Library :: Passed validation, requesting v0.14.3
	ModHelperDef :: Combat Realism :: Passed validation, requesting v0.14.0
	ModHelperDef :: Fluffy Research Tree :: Passed validation, requesting v0.14.0
	ModHelperDef :: Fluffy Breakdowns :: Passed validation, requesting v0.14.0
	ModHelperDef :: Clutter Furniture :: Passed validation, requesting v0.14.0
	ModHelperDef :: Hospitality :: Passed validation, requesting v0.14.0
	ModHelperDef :: LT-No Cleaning Please! :: Passed validation, requesting v0.14.0
	ModHelperDef :: RedistHeat :: Passed validation, requesting v0.14.0
	ModHelperDef :: Skynet SK :: Passed validation, requesting v0.14.0
	ModHelperDef :: PetFollow :: Passed validation, requesting v0.14.1
	ModHelperDef :: Area Unlocker :: Passed validation, requesting v0.14.0
	ModHelperDef :: Fluffy Relations :: Passed validation, requesting v0.14.0
	ModHelperDef :: GHXX Tech-Advancing :: Passed validation, requesting v0.14.0
	ModHelperDef :: Zoom to Mouse :: Passed validation, requesting v0.14.0

**Comment by Quelling** [comment]
I am have same errors: https://i.gyazo.com/12a2b82561edc927653b3c2c9ec18692.png

But it is happen only in debug mode. I'm not sure, but perhaps these errors do not matter?

**Comment by skyarkhangel** [comment]
Try to download from stable branch and check results.
