### ISSUE TITLE
bug: GauseWindTurbine can work under roof

### ISSUE THREAD

**Issue by evgeny-k** [skyarkhangel/Hardcore-SK#48]
![untitled](https://cloud.githubusercontent.com/assets/1670762/13582614/64710d60-e4be-11e5-9e50-06b6f918670f.png)

**Comment by skyarkhangel** [comment]
so it was conceived, like wind turbine. Change this?

**Comment by Masquerine** [comment]
Yes, will change this to be like the other wind turbine - can't be under roof. That way you can't lock one in a room where the wind would be unable to reach it, but still have it acting like it is being powered by wind. Thanks for the notice.

**Comment by evgeny-k** [comment]
creating of turbine requires no roof - this is ok.
after creating, turbine works w/o problem in room with roof - this is wrong. 
I think, border in 2 cell for blades of turbine should be without roof otherwise turbine should said "blocked by roof"

**Comment by skyarkhangel** [comment]
<placeWorkers>
      <li>PlaceWorker_NotUnderRoof</li>
    </placeWorkers>

Remove this from GauseWindTurbine.

**Comment by evgeny-k** [comment]
no, this fix doesn't work. 

these screens taken with "draw roofs" option:
![untitled](https://cloud.githubusercontent.com/assets/1670762/13711555/396155d4-e7d0-11e5-9fc0-c06c794a1634.png)
![untitled1](https://cloud.githubusercontent.com/assets/1670762/13711554/39608082-e7d0-11e5-8f13-fe4823c0a085.png)

as you see, GauseWindTurbine works w/o any problems, but original one - doesn't

**Comment by skyarkhangel** [comment]
ok. soon remove this block.
