### ISSUE TITLE
cant have mutiple campfires becauses

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#480]
in the current git of 9aae160f42427202e5581380c8001cafcd5bbde5 if u have mutiple campfires when 1 runs out of fuel all of them stop putting out heat even if they have fuel.

update weird stuff here when my campfire in my storage goes out the campfire in my barracks stops makiing light and heat but if my one in barracks runs out the one in the storage is fine. there no error ill put save here for u to check. also deconing the cairns and such still throwing errors

[Troit.zip](https://github.com/skyarkhangel/Hardcore-SK/files/628741/Troit.zip)

[ModsConfig.zip](https://github.com/skyarkhangel/Hardcore-SK/files/628742/ModsConfig.zip)

**Comment by skyarkhangel** [comment]
soon fix.
