### ISSUE TITLE
Strange thunderstorm with skynet mod disabled

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#485]
Skynet mod is off, but I'm still getting the strange thunderstorm event very frequently.  Nothing happens except the lightning though.

**Comment by ScottS9999** [comment]
Seems to happen every 1-3 days.  I didn't notice any correlation with weather or map condition.

**Comment by skyarkhangel** [comment]
I suppose u have map condition -electric thunderstorm mapcondition which slightly increased.  So its intended.
