### ISSUE TITLE
holosuite cant be reinstalled automatically

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#489]
well, it goes well first and you can set blueprint of the holosuite at a new location.
but, pawns do not reinstall it automatically and yes, cant be manually reinstalled either (cant right click to bluprint), but if player uninstall it first and install it again, it works.

if you cant understand what im saying, just try to reinstall a holosuite. you will get it soon.

using db1b9d099736367660644d7426239d799191941e git version

+ sky,  is there any way to get old git version pack 192c8f13f61104b9aec071a68a4a75fe23b5920a ??
thanks.

**Comment by skyarkhangel** [comment]
ok. why you need old this version? there are only changes with zeon

**Comment by caesius90** [comment]
i want to play my colony but in newest version i cant load it. i think the error came from removing ccl depandancy. the version i asked is the last version before removing ccl so that version is most latest version that can load my file so i asked. if finding/getting that version is too bothersome work, just let me know and i will stay my current cersion untill finish my save.

**Comment by skyarkhangel** [comment]
Nope i can't to get this version :/ I making backups, but its was fast fix without backup.

**Comment by caesius90** [comment]
@skyarkhangel 
well, what about version 826ae586490202eb4fc3349ecc60dcde6f8deba3 ?
another reason i want to play as latest version as i can is that i can find bugs that didnt fixed yet in newist pack.
