### ISSUE TITLE
bug: impossible to build MA5 ICWS

### ISSUE THREAD

**Issue by evgeny-k** [skyarkhangel/Hardcore-SK#49]
according to help, it can be build in Advanced weapon crafting workbench:
![untitled1](https://cloud.githubusercontent.com/assets/1670762/13588031/95636408-e4dd-11e5-874d-94b506c2c85d.png)

but actually, it is impossible:
![untitled](https://cloud.githubusercontent.com/assets/1670762/13588032/95637bf0-e4dd-11e5-878a-22e15052907d.png)

**Comment by Goikoa** [comment]
Fixed. Will push soon the fix soon.
