### ISSUE TITLE
A2B is still on the included mod list but not in actual game play.

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#490]
shouldnt it be excluded?

+ in A15  SK PACK , A2B continues to be included in this pack? (lets assume it will be updated)
or it will be replaced with industrial roller (newface mod)??

**Comment by skyarkhangel** [comment]
Yep.. i forgot about a2b

**Comment by caesius90** [comment]
@skyarkhangel 
ah...that is quite hard request for me... because i cant play rimworld without your awsome mod pack...
and industrial roller is A15 mod.
but i will try. as far as i know, industrial roller have some great features which A2B dont, but also some balance issues ex) puller.
