### ISSUE TITLE
Костёр греет соседнюю комнату (но не ту, где расположен)

### ISSUE THREAD

**Issue by Andrey-Sisoyev** [skyarkhangel/Hardcore-SK#492]
Версия игры 0.14.1249 (rev942), со стима
Версия Hardcore-SK: https://github.com/skyarkhangel/Hardcore-SK/commit/9aae160f42427202e5581380c8001cafcd5bbde5

(1) в горе выкопал большое помещение X
(2) в нём сделал комнату Y -> поставил там костёр А -> работает нормально
(3) выключил костёр А
(4) поставил костёр Б в большом помещении X -> вместо помещения X обогревается комнатка Y 
(5) неправильный костёр не излучает свет (визуально)
(6) сохранился (ссылка на файл ниже) -> перезапустил игру -> загрузил игру -> оба костра источают свет, хоть костёр А не горит; костёр Б всё ещё отопляет непрвильное (соседнее) помещение

В помещении X костёр Б.
В помещении Y костёр А.

Сохранка https://yadi.sk/d/U-gIaoxe32rFy6

**Comment by skyarkhangel** [comment]
Не актуально. Был уже такой багрепорт. В версии https://github.com/skyarkhangel/Hardcore-SK/commit/9aae160f42427202e5581380c8001cafcd5bbde5 должно все работать.
