### ISSUE TITLE
Reading Table Bug

### ISSUE THREAD

**Issue by Goikoa** [skyarkhangel/Hardcore-SK#50]
Yesterday I had put down a reading table, a journal table, and a (normal) bookshelf. I not sure which table is the problem .. yet.

Error reports I received:
http://imgur.com/a/7lLbd

It looks like some portion of the dll. is involved.

I have not looked more into it but when I do I will update this.

Another thing, probably XML issue, the pawns eat on top of the journal table.

**Comment by skyarkhangel** [comment]
Ok. Its a Clutter, which soon will updated.

**Comment by skyarkhangel** [comment]
Updated.
