### ISSUE TITLE
current a16 test issues

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#502]
no errors that where recorded in log but  3 things i found

1. no people will join. it basicialy is the old error about the type of pawn that before prevented some raids and trade caravans

2.sometimes people get stuck doing stuff. this may be stock game bug but good to know.
3. roasted and jerky dont have place in stockpile

**Comment by Owlchemist** [comment]
Regarding #3, I noticed this for a number of other things, like for example the packaged survival meals you start out with.

**Comment by Owlchemist** [comment]
Is the sexuality system from the Psychology mod working? I noticed the gay trait is still one you can select, but the mod options for psychology suggests the trait was removed by it.

**Comment by sidfu** [comment]
hmm i know there is a mod option in the menu for the gay thing did u check it?

**Comment by sidfu** [comment]
error that prevents pawn markers
Faction Jodir Ost of def NorbalTribe has no usable PawnGroupMakers for parms map=Map 0 (ID 0) (player home) (current), points=62, faction=Jodir Ost, traderKind=, generateFightersOnly=False, generateMeleeOnly=False, raidStrategy=, forceOneIncap=False
Verse.Log:Error(String)
RimWorld.<GeneratePawns>c__IteratorC4:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.IncidentWorker_NeutralGroup:SpawnPawns(IncidentParms)
RimWorld.IncidentWorker_VisitorGroup:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by Owlchemist** [comment]
Poked my head into Rimworld for a few minutes to check out today's update, and looks like it fixed the stockpiles at least.

One minor thing I noticed though - the z-depth is a bit off for trees. For example, I see granite chunks being rendered on top of taller trees when they should be behind it.

**Comment by zakhad** [comment]
Anyone else not getting option to name the colony/area?

**Comment by sidfu** [comment]
just tried the newest i could name my colony
