### ISSUE TITLE
Alpha 16 Test escape pods unable to unload bad map reference

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#509]
![image](https://cloud.githubusercontent.com/assets/5264667/21583653/5c46386c-d082-11e6-9ba6-cde8966af26d.png)

Attempted to loot but it had no defined map to unload its content's too due to how the new map system works

The version I am running is commit 1d9bd883f1310f1e2dcd668eb694c9a13fc75801

**Comment by skyarkhangel** [comment]
Seems fixed in last update.

**Comment by Rhyssia** [comment]
is fixed
