### ISSUE TITLE
Asari Scenario doesn't get batteries

### ISSUE THREAD

**Issue by LoliScout** [skyarkhangel/Hardcore-SK#510]
Despite starting with Power already researched, the Asari scenario can't construct batteries. There doesn't appear to be any new batteries down the tree so this is rather crippling.
![nobat](https://cloud.githubusercontent.com/assets/24879707/21595412/b47c3486-d0fb-11e6-9561-75220d875954.png)

![therebat](https://cloud.githubusercontent.com/assets/24879707/21595424/c84b8b10-d0fb-11e6-854d-09d7a7042ad9.png)

**Comment by Rhyssia** [comment]
Battery is moved to "Electronics Basics" Look at second screen shot, under box. Description for [Power] will need update.

**Comment by Rhyssia** [comment]
Note: Research related, fixed on local fork.

(trying other fixes before pushing to my branch)
