### ISSUE TITLE
Wandererjoin Incident still giving errors

### ISSUE THREAD

**Issue by Rhyssia** [skyarkhangel/Hardcore-SK#512]
![something](https://cloud.githubusercontent.com/assets/24862205/21596392/7ee2f8e8-d108-11e6-8e80-c06055ecf2dc.jpg)

**Comment by Rhyssia** [comment]
Also sometimes gives this error on wanderer join
![something](https://cloud.githubusercontent.com/assets/24862205/21596651/b393d064-d10b-11e6-9e16-18a3e2a64c91.jpg)

**Comment by skyarkhangel** [comment]
Fixed in next update.
