### ISSUE TITLE
Error with Neutral Vistors and Raid

### ISSUE THREAD

**Issue by Rhyssia** [skyarkhangel/Hardcore-SK#516]
Using Commit  6d75cd4

![something](https://cloud.githubusercontent.com/assets/24862205/21615780/fa823f50-d1ac-11e6-91e8-d67e8e27096a.jpg)
![something](https://cloud.githubusercontent.com/assets/24862205/21615806/11ac82ee-d1ad-11e6-8dbe-d50b4bd2c4a0.jpg)

**Comment by Rhyssia** [comment]
Still errors.

![error](https://cloud.githubusercontent.com/assets/24862205/21669678/dbb053b6-d2db-11e6-9274-77a5aae074e8.jpg)

**Comment by Rhyssia** [comment]
From forum:
http://i.imgur.com/KY2to5X.png

**Comment by Owlchemist** [comment]
Looks like this is still an issue. Just installed the latest build and got it on day 4.

Problem with hospitality, maybe? I noticed HCSK is not using the latest version of it.

![image1](https://cloud.githubusercontent.com/assets/5252347/21753756/581f4938-d5a8-11e6-9262-aa0254cac9c4.jpg)
