### ISSUE TITLE
Error when Colonist pick up "Living Fire"

### ISSUE THREAD

**Issue by Rhyssia** [skyarkhangel/Hardcore-SK#522]
When Living Frost, Living Fire, or Uranium in Colonist Inventory.
Living Frost or Living Fire this error:

![error](https://cloud.githubusercontent.com/assets/24862205/21652006/dbbc2ed8-d278-11e6-9ae9-689b2b5e3892.jpg)

**Comment by Rhyssia** [comment]
Uranium Ore this error:
![error](https://cloud.githubusercontent.com/assets/24862205/21653371/bcc2a7cc-d27e-11e6-9c09-b6e4409c49a9.jpg)

**Comment by notfood** [comment]
Inside Inventory when Colonists grabs something Map becomes null. You've to go to through the holder or just test for null before trying to irradiate cold/heat/radiation.

**Comment by skyarkhangel** [comment]
So its related to CR.
Interesting.. how to fix it.

**Comment by notfood** [comment]
It's not only CR. Applies to vanilla RimWorld too. If Colonists wears/hauls/grabs something, the item's Map becomes null.

**Comment by Rhyssia** [comment]
Living Frost + Uranium Fixed. Living Fire gives:
![error2](https://cloud.githubusercontent.com/assets/24862205/21667229/2747d8d8-d2c5-11e6-9968-bef742394621.jpg)

**Comment by notfood** [comment]
Sk, try using this:
```csharp
var curMap = parent.holdingContainer != null ? parent.holdingContainer.owner.GetMap() : parent.Map;
```
if you are in a component.

**Comment by skyarkhangel** [comment]
Yep, seems it help.
