### ISSUE TITLE
Unable to drop wearable gear

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#527]
If you pickup something you can wear (picking it up into inventory, not hauling or equipping it), you cannot drop it. Nothing happens when you try.

This is consistent and easy to reproduce.

Doesn't apply to weapons.

**Comment by Rhyssia** [comment]
What item of clothing? Trying to reproduce with mundane shirt. Colonist just throws it back on ground if there is no stockpile for it.

**Comment by Owlchemist** [comment]
Anything. An easy example would by the cryptosleep bodysuit you start out with. I just started up a new game to test it with. And just to double-clarify, it works fine if they're actually wearing it. It's only when it's in their *inventory*, not being worn, when it gets stuck.

**Comment by Rhyssia** [comment]
I am having trouble reproducing, could you upload save with bug?

**Comment by skyarkhangel** [comment]
Fixed in next update
