### ISSUE TITLE
Textile Issue (Not Critical)

### ISSUE THREAD

**Issue by Rhyssia** [skyarkhangel/Hardcore-SK#529]
Issue: Deadman's clothes reduce value by 90%
Breakdown clothing gives material
material value is greater.

![error](https://cloud.githubusercontent.com/assets/24862205/21701278/ba5dae74-d372-11e6-9d36-1f08bc8e9abb.jpg)

**Comment by Rhyssia** [comment]
Possible fix: Prevent breakdown of deadman's clothes, or reduce material from breakdown based on deadman.

**Comment by SmokeyUnicycle** [comment]
Is the Dead Man clothing mechanic desirable in Hardcore SK?
