### ISSUE TITLE
Unnecessary furniture text

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#532]
Low priority item, probably:

Some furniture show their quality level, acting as though they were equipment. Examples include backless stools and primitive chairs.

Also, pet beds like the hay bed show "unowned", but pets can never own their beds, so pointing that out is useless clutter text.

**Comment by LoliScout** [comment]
Pet beds can be owned by pets but only while a pet is trying to sleep there.

**Comment by Rhyssia** [comment]
Furniture quality level also has effect on beauty/comfort (I believe). (Shoddy chair gives less beauty/comfort than superior chair)

**Comment by LoliScout** [comment]
I think he means that they appear like names for pets do. It can be quite an eyesore if you have a bunch of chairs.

**Comment by Rhyssia** [comment]
Oh ok, I understand now. Screen clutter with quality tags.

**Comment by Owlchemist** [comment]
> Pet beds can be owned by pets but only while a pet is trying to sleep there.

I had a look at this just now. What do you mean? I don't see any assignment button. Every night they just take whatever bed they want at random.
![image1](https://cloud.githubusercontent.com/assets/5252347/21739725/2208438c-d458-11e6-831f-1371556d3919.jpg)
