### ISSUE TITLE
Colonists Eating Binge

### ISSUE THREAD

**Issue by LoliScout** [skyarkhangel/Hardcore-SK#534]
My colonists will eat every single piece of jerky as soon as it's made, regardless of hunger. No mental breaks or anything.
![image](https://cloud.githubusercontent.com/assets/24879707/21719724/3e16b5d8-d3ed-11e6-8a9a-ab30e5b131e6.png)

**Comment by LoliScout** [comment]
Jerky is considered a joy food, like chocolate. So they'll keep eating it till their joy is at some threshold I haven't worked out. It makes the start hard when you have no joy activities and only jerky as a stable food source.

**Comment by Rhyssia** [comment]
Looking into where I can. Does it happen with roast meat as well?

**Comment by Arachnidek** [comment]
Can confirm. Roasted meat acts exactly the same. Colonists eat every single piece of Jerky and Roasted Meat avaiable.

**Comment by Owlchemist** [comment]
This behavior is quite unpredictable. In my 3 year colony, I've only ever caught it one time...a colonist heading to the dining table to eat some jerky when they were already full. I drafted and undrafted them to make them stop, and it seemed to work. Never saw it happen again afterwards. Of course I can't spend all my time monitoring the dining hall, though, so I may have missed it.
