### ISSUE TITLE
Fishing uses Shooting skill

### ISSUE THREAD

**Issue by carpediembr** [skyarkhangel/Hardcore-SK#536]
Fishing is using the shooting skill instead of fishing skill.

**Comment by Rhyssia** [comment]
error is at Core_SK.Dll\FishIndustry.JobDriver_FishAtFishingPier

code is...
this.pawn.skills.Learn(SkillDefOf.Shooting, 0.15f * single2, false);

**Comment by sidfu** [comment]
not a bug in once sense as fishing skill has been removed but still shows they now use the hunting stat

**Comment by Rhyssia** [comment]
ok will work to remove fishing skill later.

**Comment by notfood** [comment]
Fishing WorkType has been removed. Fishing now uses Shooting skill.
