### ISSUE TITLE
'Locusts attack' event bugged

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#538]
I got this event, but nothing spawned. Here's the error it produced:

![image5](https://cloud.githubusercontent.com/assets/5252347/21739211/b33bfe8e-d449-11e6-95ed-779e658f7d62.jpg)

**Comment by skyarkhangel** [comment]
Attemp to fix in next update

**Comment by Owlchemist** [comment]
Still getting an error.

![image2](https://cloud.githubusercontent.com/assets/5252347/22138602/61527c40-de96-11e6-99a4-57f3e557ceeb.png)
