### ISSUE TITLE
uranium error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#541]
Tried to make non-Stockable thing for trader stock: Uranium
Verse.Log:Error(String)
RimWorld.StockGeneratorUtility:TryMakeForStockSingle(ThingDef, Int32)
RimWorld.<TryMakeForStock>c__Iterator15A:MoveNext()
RimWorld.<GenerateThings>c__Iterator15D:MoveNext()
RimWorld.<GenerateTraderThings>c__Iterator164:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.TradeShip:GenerateThings()
RimWorld.IncidentWorker_OrbitalTraderArrival:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by skyarkhangel** [comment]
Fixed in next update
