### ISSUE TITLE
2 new short hash errors

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#544]
Hash collision between Uranium and  GTStomach: both have short hash 23201
Verse.Log:Error(String)
Verse.<ThingsToSpawnAfterLoad>c__Iterator1CE:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
Verse.Map:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__736()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

Hash collision between WallLamp_Blueprint_Install and  LoadoutGen_AmmoTypeH: both have short hash 35982
Verse.Log:Error(String)
Verse.<ThingsToSpawnAfterLoad>c__Iterator1CE:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
Verse.Map:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__736()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by notfood** [comment]
Should be fixed in latest master by https://github.com/skyarkhangel/Hardcore-SK/pull/547/commits/c1dce44631abadb61015c4e32460a4483bead5dd
