### ISSUE TITLE
trader/raid for neutrals still

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#550]
still getting this error all time since most pawns are neutral to enmy ti means u get basiccaly 0 traders.

Faction Entthaenni of def Outlander has no usable PawnGroupMakers for parms map=Map 0 (ID 0) (player home) (current), points=40, faction=Entthaenni, traderKind=, generateFightersOnly=False, generateMeleeOnly=False, raidStrategy=, forceOneIncap=False
Verse.Log:Error(String)
RimWorld.<GeneratePawns>c__IteratorC4:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
RimWorld.IncidentWorker_NeutralGroup:SpawnPawns(IncidentParms)
Hospitality.IncidentWorker_VisitorGroup:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by Owlchemist** [comment]
I been looking into the PawnGroupMakers error today. I thought it had something to do with Hospitality but I started a new game without it and still got it. I was looking at the PawnGroupMakers section in the faction XMLs but I don't see anything obviously wrong about it. I imagine it has something to do with those null parameters, though.

![image1](https://cloud.githubusercontent.com/assets/5252347/21785516/b837b770-d674-11e6-8c62-501f16cc5195.jpg)

**Comment by sidfu** [comment]
probaly the hosptiatliy error part comes from how it checks if it is needed for them or not and when they fail to spawn it throws error as part of existing error.
