### ISSUE TITLE
Potentially OP Items:

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#555]
My observations after playing about 20 hours of this current build are that some items/mechanics may need balancing/tweaking to not be so effective, instead of making a bunch of threads I figured I'd put them all here. 

---

Corn: 

It's super easy to grow lots of it, it stays fresh a really long time (one year?) and it doesn't need to be cooked into meals. I don't use cooks or freezers any more, I just have a big warehouse full of 12000 corns on pallets XD It also doesn't need to be harvested or planted very often so even your gardeners have a lot of free time in between harvests and planting.  Khrushchev is very happy!

Other vegetables may be likes this as well, I am not sure, my guess is corn is probably the best choice but they may also be too strong. 

--

Primitive Floors: 

The floors made out of Hay cost very few resources, build very quickly and are very beautiful with 3 Beauty. Compared to other floors they are much much much better because they don't need a processed resource, and hay is one of the easiest resources to collect and are very quick to build. 

--

Components: 

Now that they are quick to make with the electric bench, they sell for very high amounts of silver, and are cheap and quick to make with steel. It is a very easy way to get huge amounts of money (or would be if the trade ships  worked) 

--

Will add more if I notice/remember them!

**Comment by Rhyssia** [comment]
We're working on bug fixing first. After things are stable we will be doing a balance pass. Please do not let this message discourage you from posting more issues of this nature, just know that it is not at the top of the priority list yet.

**Comment by Owlchemist** [comment]
Changing the stats on prim floors would be straightforward. What do you propose?
Maybe 2 beauty, double build time?

Also, corn is a vanilla crop. Are your observations pointing out a difference that HCSK is making to the crop (I'm asking because I don't play vanilla to really know for certain)? Rebalancing vanilla content would be debatable.

**Comment by sidfu** [comment]
leave build time for the primitive floors but make it 1 bueaty.

think of pimitive floors as a quick way to cover the ground so its not dirt.

**Comment by Owlchemist** [comment]
@Rhyssia I been doing independent contributions here and there but I'm not really "part of the loop", so to speak. I'm not really sure what the game plan is, but I could work on any balance stuff in the meantime and take a closer look at the numbers here. Outside of Rimworld modding, balance and testing has typically been my role in modding projects (most notably did the balance work on Colonial Charter mod in Banished).

**Comment by zakhad** [comment]
Prim floors are way too easy / no point on doing others until you're stylising your base. They should only have a beauty of 1 as Sidfu said. Perhaps baring the tiki floor which uses gold also bamboo which isn't something you easily have access to.

@Owlchemist  I have spent many an hour playing Banished / Colonial Charter, have you played Life is Feudal: Forest Village? it's like a spiritual successor albeit a lacking of modding support atm.

**Comment by SmokeyUnicycle** [comment]
I think having one of the three keeping at least 2 beauty and low resource requirements balanced by very very long build time ( like 50+ work) would be a good tradeoff, weaving grass into mats takes a lot longer than laying down bricks or stones.
