### ISSUE TITLE
cavebimoe error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#557]
XML error: Could not register node named "CavePlantGlowerBase" in mod Core_SK because this name is already used in this mod.
Verse.Log:Error(String)
Verse.XmlInheritance:TryRegister(XmlNode, ModContentPack)
Verse.XmlInheritance:TryRegisterAllFrom(LoadableXmlAsset, ModContentPack)
Verse.ModContentPack:LoadDefs()
Verse.ModContentPack:ReloadAllContent()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__735()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by skyarkhangel** [comment]
Remove mods folder and copy mods without replacing
