### ISSUE TITLE
cargo pod error is back

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#558]
luckly the items still spawn unlike before

Tried to double-add designation on Thing Thing_DropPodLanded394802
Verse.Log:Error(String)
Verse.DesignationManager:AddDesignation(Designation)
SK.CompLoot:DesignateForLooting()
SK.<>c__DisplayClass2_0:<CompFloatMenuOptions>b__0()
Verse.FloatMenuOption:Chosen(Boolean)
Verse.FloatMenuOption:DoGUI(Rect, Boolean)
Verse.FloatMenu:DoWindowContents(Rect)
Verse.FloatMenuMap:DoWindowContents(Rect)
HugsLib.GuiInject.<>c__DisplayClass1:<_WindowOnGUI>b__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Comment by skyarkhangel** [comment]
You seems need to full reinstall mod folder. All works fine. Closed.
