### ISSUE TITLE
Prisoner Room Outdoors Bug

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#560]
Perf warning: Ran ContainedBeds in huge room Room(roomID=446, first=(248, 0, 93), RegionsCount=69, lastChangeTick=21312460)
Verse.Log:Warning(String)
Verse.<>c__Iterator1E2:MoveNext()
Verse.Room:RoomChanged()
MapGenerator.RectTrigger_UnfogArea:ActivatedBy(Pawn, Map)
MapGenerator.RectTrigger_UnfogArea:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

It seems to have set the large outdoor area in my base to a prisoner room meaning I cannot haul my crops because they are in a prison room. 

How this happened is unclear, the outdoor area is very large and does not say "unfroofed" just "outdoors' 

http://image.prntscr.com/image/fa4b80847f9d42c68da4099fc19a2d90.png

This cornfield is a very nice prison apparently 

I wonder if building a bed outside and then making it not for prisoners will reverse this?

No it will not, the beds are not toggleable, they stay as prison beds even if you try and change that. 

Hmm.

**Comment by Owlchemist** [comment]
Is that the latest version? Because your icons look like they're from an older version of HCSK.

**Comment by SmokeyUnicycle** [comment]
I downloaded it a few days ago by clicking the clone/download button on the master branch of the main mod. It's entirely possible I messed something up.  I

hcsk 0.16.1393
rev 1214

It seems the most recent is 1264, so no it's not the most recent but it shouldn't be very out of date should it?

**Comment by SmokeyUnicycle** [comment]
I reloaded to a previous save, the same time as before the bug occured again, I still am not sure what is causing it. I can retrace my steps a third time, would this be worthwhile?
