### ISSUE TITLE
quarry corrupts my saves

### ISSUE THREAD

**Issue by k4iser88** [skyarkhangel/Hardcore-SK#565]
After the second hours long gamesave got corrupted i finally investigated further and discovered the cause seems to be the construction of the quarry.
This is when the problem seems to occur in the log:
http://pastebin.com/ukQDJVKj

To confirm the thing i started a new colony and dropped a random quarry in god mode, saved, rebooted (as long as I dont close the game it still manage to load), and the savegame was corrupted instantly.

Can someone try this? Anything i can do to fix this? ty :)

UPDATE: I hardfixed it by deleting the "quarry" lines in the savefile, without the quarry on the map the gamesave is working again, so it was clearly this building presence to corrupt the saves.

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
Tested. Works fine, may be you use old version?

**Comment by k4sier88** [comment]
I'm on A16. v. 0.16.1393 up to date on steam

Isn't this the last?

**Comment by e3r** [comment]
This happens to me too.
It's been like this for several commits - not sure when it started.
I tested today with the current commit 7e09fc663297b6ea9ce81e4eae53586140ab73b1 and it's still happening.
The current workaround is to dismantle the quarry before quitting the game :(

My exception is similar, but it references a subnode in the save-xml that seems to include the rest of the xml-file. (Which makes it a little too big for referencing)

**Comment by skyarkhangel** [comment]
ok. Ill test it more.

**Comment by e3r** [comment]
The recent change to the quarry seems to have fixed this. 
I'm no longer able to reproduce the exception 👍

**Comment by notfood** [comment]
Quarry was reworked. It shouldn't cause any more issues.

**Comment by Vandenberg** [comment]
Is it possible to get the fix to the quarry as a separate package that does not break games in progress?

**Comment by notfood** [comment]
You can edit the xml and remove all the quarry instances. It uses a MapComponent that was removed, that's why it breaks your save. Remove it and you will be able to load it.
