### ISSUE TITLE
Switching from grenade to gun deletes weapon

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#569]
I just saw CR was updated a little while ago, so this might have already been fixed. In case it wasn't though, when I switched from frag grenade to a gun, I got the following error and my gun disappeared.

![capture](https://cloud.githubusercontent.com/assets/5252347/21839428/9b2c45a6-d78c-11e6-8b9b-449825ade4a9.PNG)

**Comment by SmokeyUnicycle** [comment]
Can confirm this happening in the older version I'm on, additionally my T-1000 picked up a bunch of dead man's clothes into his inventory but cannot drop them.

**Comment by Rhyssia** [comment]
@Owlchemist Error still persists? If no confirmation, will test tomorrow after work.
