### ISSUE TITLE
Feature: improve seed description to tell what kind of soil the use

### ISSUE THREAD

**Issue by tivec** [skyarkhangel/Hardcore-SK#57]
At the moment, it is not intuitive which kind of soil is needed for a specific plant. Research screen is not helpful either. It would be a great improvement if the seed description were to include the type of soil it needs. For example:

Peach Seeds can be sown in soil to grow Peach Trees, which produces Peaches.

changed to:

Peach Seeds can be sown in **rich** soil to grow Peach Trees, which produces Peaches.

**Comment by skyarkhangel** [comment]
Seedplease soon update to new version

**Comment by skyarkhangel** [comment]
Closed.
