### ISSUE TITLE
Suggestion for smoother gameplay

### ISSUE THREAD

**Issue by Bsonnete** [skyarkhangel/Hardcore-SK#571]
Hello guys, great job with this mod that makes playing Rimworld much more rewarding and tactical.
Now to the issue: I don't know if this is the right place to put this but I love the way weight and bulk makes everything much more interesting but I find incredibly frustrating that every time I have to draft my pawns I have to equip manually the guns because I love to give them tools to work. I don't know if there's a way to make them to automatically equip them when drafted or just make that with double click you can equip anything.

Sorry if this is in the wrong place but I didn't find any other place to put it.

Great mod anyways :1st_place_medal:

**Comment by notfood** [comment]
Just put them in their inventory, they will use the **right tool for the right job** automatically, that mod is included in Core_SK.

**Comment by SmokeyUnicycle** [comment]
But they won't equip a gun when entering combat/being drafted, which is the problem.

**Comment by Bsonnete** [comment]
Yes, when i give them tools they use them ok, they change automatically when needed, but when i'm getting raided they keep wathever tool they where using before they where drafted, so i have to change manually one by one to the Gina: select pawn, open gear, right click on gun, equip.
This may sound easy enough but when you have 14 pawns and each one of them has tools, it gets annoying.
Just a suggestion, i have no experience modding so i have no idea how to do it, I would appreciate if someone with experience could tell me if is posibble or to just drop it off and dont bother anymore 😀

**Comment by Dunkhan** [comment]
As far as I can tell it should be possible to add a button to the pawn combat buttons, many of which I believe are from combat realism. What would be ideal IMO is two buttons similar to the reload or the draft/undraft buttons. One that enables the player to unequip all equiped weapons from selected pawns, and one that enables the player to equip the first weapon on each pawn's gear list. This would not solve all problems as it would still require micromanagement to ensure that the right weapon is at the top of the list when multiple are carried. This change would save a lot of clicks however and make the work speed penalties of weapons less severe.

A question for the core team: Would it be better to try to suggest this to the combat realism team, or is this the kind of thing that should be implemented here?

**Comment by Bsonnete** [comment]
Just an idea I've had, just make that double clicking in one item equips it, I have no idea of modding or how difficult it could be but I think it's simple enough just to not have this problem
