### ISSUE TITLE
applo error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#572]
MakeThing error: Apparello_Headset is madeFromStuff but stuff=null. Assigning default.
Verse.Log:Error(String)
Verse.ThingMaker:MakeThing(ThingDef, ThingDef)
SK.Events.IncidentWorker_ColonistStash:TryExecute(IncidentParms)
RimWorld.Storyteller:TryFire(FiringIncident)
RimWorld.Storyteller:StorytellerTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

item was a headset wtih bandana made out of cloth

**Comment by sidfu** [comment]
this error seems to be poping anytime the event for a colonist to give the colony a item. out of 2 times both times it triggered and both where on clothing peices

**Comment by skyarkhangel** [comment]
ok
