### ISSUE TITLE
Miscellaneous Weapon Problems

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#573]
**1. The"RPK-74" is not an RPK-74**

 (Wrong graphic) the one in game looks like a Galil or something. RPK should look like an AK-47/74 with a longer barrel and magazine. It is also using the wrong round, or is titled wrongly. The RPK shoots the short, fat 7.62 x 39mm round like the AK-47. The RPK-74 shoots the short, thin 5.45 x 39mm round like the AK-74 and AKS-74U. I would suggest just getting rid of the  short 7.62 round entirely and making the AK-47 into the AK-74. There's not enough of a difference between the rounds to matter IMO, simpler just have the 74 family of 5.45mm weapons. 

Edit: Digging through the textures I was correct, it currently has the Galil texture, but there is an RPK-74 texture in the weapon texture folder.  

**2. LMG-15?**

   I don't know what the L-15 LMG is, is this a real weapon? I cannot tell from the image or description what it is supposed to be.

       ( It looks kind of like a Lewis Gun without the barrel cooler, I could probably edit the little artwork in gimp to make it closer to the real thing, I would rename it to "Lewis Gun" and change its ammunition to .303 British so more guns use the same ammo as the Lee-Enfield rifle.)

**3. The "HK XM8 Military Rifle" should just be called "HK XM8"** 

**4. The M72 LAW rocket launcher is not reloadable in real life.** 

    It can only be fired one time.  It should work like Grenades do, where it is used up when fired. Probably needs some balancing in cost/materials if this is changed.

**5. The "VSS Thread Cutter" has some problems.** 

   It should probably not get a nickname (Just "VSS"), or the nickname should stay in Russian, as "VSS Vintorez"  

   It shoots a slow 9 x 39mm bullet which is not powerful, weaker and slower than the 5.56 NATO round. In game it is much longer ranged and does 50% more damage. That makes no sense realistically.  In real life it is used by spetsnaz and other elite troops because it is very quiet, but that does not matter in rimworld. 

    It also shoots a magical "shock round" that is a fantasy weapon and seems to be broken because it keeps killing everyone it hits for some reason instead of stunning them like it says.

    It is also the only gun to use this ammo type I think, though that's not a big deal. 

**6. The Sci-Fi Ballistic Assault RIfles have some problems.**

The MA5 ICWS, MA39X ICWS and the "Tar-21 Tavor" (which is actually the M41A1 Pulse Rifle) don't make sense. 

These are all future rifles  from Halo and Aliens. They should be like the Halo Sniper Rifle (SRS99 AM Sniper Rifle)  where they're the best bullet gun of their type before going to future weapons with lasers and plasma.  I can expand on stats later I guess, I just want to make sure there isn't a reason for the way they are. 

----------------

I'll add more when I run across them, I understand this is not a priority, but I can't really help bugfixing with my lack of coding skills so this gives me something to do. 

Edit: oh god why did it format the posts like this what the heck

Edit2: I think I can make half of these changes, things like altering descriptions and changing ammo types pretty easily now that I've taken a look at how they're done. Something like changing the LAW to be single use (which might not be okay with people) may remain beyond my capabilities at this time.

**Comment by SmokeyUnicycle** [comment]
I put together a rough draft and hit the "propose changes" button :D

**Comment by notfood** [comment]
This is more for Combat Realism. HardcoreSK only includes them.

**Comment by SmokeyUnicycle** [comment]
Does Combat Realism include mods like Rimfire and Halo and Aliens weapons? I was under the impression it did not.  If this is true, then this seems like flawed integration of multiple mods which is in our ballpark.

 Also, Skye is the one running Combat Realism now and it's a critical component of Hardcore SK.
