### ISSUE TITLE
Mod components do not always drop at start

### ISSUE THREAD

**Issue by Dunkhan** [skyarkhangel/Hardcore-SK#58]
I had to rewrite this issue, I thought at first it was due to the crashlanding mod but that appears not to be the case.

Version 22 March github

Sometimes the components that are added to drop at the start of the game by the mod (ingots, electronic components, mechanisms, spare parts) do not drop, rendering the mod unplayable.

Reproduction:
1. Install the mod
2. Create a new world and start a new colony
3. Quit to the main menu
4. Start a new colony

Workaround restarting the game before starting a new colony prevents the bug

**Comment by skyarkhangel** [comment]
Unfortunately, its one of the problem which could happen when starting new game after restart new game.

**Comment by Dunkhan** [comment]
Ok, if this is difficult to fix I certainly understand if you want to concentrate on other things. It is probably a good idea to leave this issue here though so people can see the workaround.

**Comment by skyarkhangel** [comment]
Obsolete. It should work fine now.
