### ISSUE TITLE
carago drop error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#587]
Failed to find RimWorld.BiomeDef named Cave. There are 10 defs of this type loaded.
Verse.Log:Error(String)
Verse.DefDatabase`1:GetNamed(String, Boolean)
RimWorld.BiomeDef:Named(String)
SK.Events.Ticker_SCcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
Fixed
