### ISSUE TITLE
Projectile/ammo inconsistencies

### ISSUE THREAD

**Issue by Blothorn** [skyarkhangel/Hardcore-SK#588]
There are a handful of obvious inconsistencies in the projectile and ammo stats: .50 Action Express HP does lower damage than its FMJ, 7.62x39mm HP has the same armor penetration as its FMJ, 7.62x51mm NATO FMJ has the same SLDBar cost as its AP/HP variants, and I think I have seen a few others. I would be happy to make a pull request for these fixes.

However, I think ammo balance in general is a bit odd, at least if it is supposed to reflect real-world comparisons. For example, 9x19mm Parabellum has nearly the same performance as 5.45x39mm (and their AP variants are identical aside from muzzle velocity and cost), despite the latter having about four times the energy. Similarly, the 9x39mm is superior to the 7.62x51mm (-0.01 penetration, +3 damage) despite again having only a quarter the energy. Both those comparisons seem to indicate that these were balanced to strongly favor projectile weight over muzzle velocity--but the 7.62x39mm is only barely punchier than the 5.56x45mm, despite having twice the bullet mass and greater energy. Would it be worth my trying to rebalance things more generally, or are these all pursuant to gameplay balance demands?

Note: most of these issues are with CR ammo; I am reporting it here because for some reason Hardcore-SK and vanilla CR have very different projectile stats.

**Comment by SmokeyUnicycle** [comment]
I've also been pretty confused with the stats of different types of round. 

The 9x39mm is particularly bizarre. 

I've been thinking about proposing a more realistic system but the biggest thing stopping me has been this:

If we go with realistic ballistic effects, given the availability of advanced materials in the mod we're going 
to trend towards intermediate caliber weapons becoming ineffective around the late mid game, and then nothing to replace them until futuristic weapons.  

There's a ton of 5.56  weapons and very few full sized rifle, 7.62x51/54 mm rounds. 

Against someone wearing near future protective gear, 5.56 rounds are not going to be effective. 

In real life however there's a simple solution of just going back to the Battle Rifle and full power rounds, which in game we don't really have, other than the SCAR-H and some sniper rifles. 

 It would be pretty easy to add in 7.62 models of the M16 and FAMAS as existed in real life, but that seems kind of strange to go backwards chronologically. 

Alternatively, we could just make the player reliant on these hypothetical depleted uranium AP rounds I guess.


-------------

Rambling aside, there's definitely room to fix the inconsistencies without messing up the overall system in place. 

I'd be happy to help try and balance weapons realistically with each other in a way that works in the game, but I think we need some sort of approval from Sky or someone else that things aren't this was for a dearly held reason.

**Comment by SmokeyUnicycle** [comment]
Looking through the files, it seems like the differences in ammo types aren't really very large. Hollow Point rounds for example are only losing like 5% of the penetration of FMJ rounds and only getting a similar amount of damage in return. There's really not much of a difference in the three main round types right now. 



IMO it should be something like this for Hollow Points:

Penetration of FMJ/2 and Damage of FMJ x1.33 or 1.5

And something like this for Armor Piercing

Penetration of FMJ x 1.33/1.5 and Damage of FMJ x .66 


The properties of damaging flesh vs penetrating armor are diametrically opposed. What will cause a big wound in a body will just flatten and bounce off of armor, and what will pierce armor, will just bore a small neat wound in a body. Right now they are 95% the same, which is unrealistic and a big loss of gameplay diversity since the choice doesn't really matter that much.

**Comment by Blothorn** [comment]
From the source material (Halo) the MA5 and (presumably) the MA39 should fire 7.62x51mm NATO, which would give a bit more variety in that cartridge. If we were to consider new guns:
- A 7.62x54mmR machine gun would make that cartridge a bit less isolated--the Mosin-Nagant is nifty for its price (and, if not taken at embark, for being craftable without plastic), but given the poor performance of the Dragunov I see insufficient reason to add another ammo type to my supply chain.
- The 5.7x28mm would give handguns/SMGs a bit more life. Not to mention that I think the quite decent armor penetration of the 9x19mm is one of the most egregious departures from reality; having a tier-3 pistol cartridge with better penetration would make nerfing the tier-1 cartridges more palatable. (Seriously, how does 9x19mm AP have the same penetration as 5.45x39mm AP?!)

I am not overly concerned by the chronological shift--the full-power rounds have not died out, and I imagine that if body armor with the capabilities of near-future armor became widespread, the primary effect would be a resurgence of full-power rounds. (Although I would also think likely the replacement of the intermediate cartridges with a more powerful cartridge following the same light-bullet, high-velocity paradigm--body armor would not change the primary reason for moving away from the battle rifle cartridges, that they are optimized for longer ranges than most weapons will be used at.) That said, if we follow the suggestion (which I much like) of increasing the difference between ammo types, 5.56mm AP should remain relevant much longer anyway.

Although thinking of AP, I find the DU requirement oddly harsh, given that by my understanding, most RL AP just has a hard-steel core. I would consider making AP require USLD (and perhaps add an APDS DU round for the 7.62mm+ guns as a further late-game boost to penetration). Even more ambitious would be to remove most ammo classes (excepting specialty rounds such as shock/HE/incendiary) and make ammo material-sensitive, with harder alloys having lower damage and higher AP. But I suspect this would require a binary fork from vanilla CR since it does not have the Hardcore-SK alloys, and I doubt it would be worth that headache.

**Comment by Rhyssia** [comment]
*Deep Breath* Concerns will be added to balance pass. I will try to keep track of all this, and will notify if fixed.

The Ammo "stuff" requirements sounds awesome and could probably be linked with the Sharpness stat on material. But this would probably require some C# functions. It might be possible to put in the next version after all the major bug fixes and balance updates are pushed through.
