### ISSUE TITLE
Bug: Tailor's Loom unfinished item not completeable, changes material type.

### ISSUE THREAD

**Issue by iancwyatt** [skyarkhangel/Hardcore-SK#59]
I was making a clawed boots at a Tailor's Loom and queued up Make Clawed Boots x2 w/ the Raptor Leather material. The first boot came out fine, but the second one was called "Unfinished Nitinol Clawed Leather Boot". It got to 0 work left, but wouldn't complete. I disessembled it and got raptor leather back. People on the forums are reporting the same issue with tailoring (random wrong materials, not finishable).

**Comment by iancwyatt** [comment]
Just got this same problem using a modern loom to make an item.

**Comment by Karel-Kroeze** [comment]
this is a known RW bug where stuffed items will take their stuff identifier randomly from the list of ingredients. If a non-stuff def is selected as the stuff, the craft bugs out.

I believe it's been reported and fixed for A13

**Comment by skyarkhangel** [comment]
Soon we start to rework apparel craft.

**Comment by skyarkhangel** [comment]
Reworked apparel craft. Should work fine now.
