### ISSUE TITLE
Is the furnace's graphic correct?

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#592]
Every time I play, it just looks a bit off, as though it weren't responsive to the ambient lighting. It practically glows in the dark.

Its graphic also doesn't really seem to react to its material types like some other production buildings do.

![image2](https://cloud.githubusercontent.com/assets/5252347/21957376/8189b434-da49-11e6-8121-d63f79815a99.jpg)

**Comment by skyarkhangel** [comment]
its bcs, <shaderType>CutoutComplex</shaderType> in graphicdata.

**Comment by Owlchemist** [comment]
I took care of it.
