### ISSUE TITLE
they put anything nearly for burning

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#597]
they useing anything close now for refueling. they where putting sand in my stove and such.

**Comment by notfood** [comment]
That's hilarious.

Clear the filter and set it again? Can you try it in a new save?

**Comment by sidfu** [comment]
seems it kinda settles out after a while so far. after around 10min they stoped it. maybe some data was saved in save and took a while before it changed into the changes.

and yeah funny they put ssand in a stove lol. i did clear it at first and console rebuilt it and was same. have to see as i play more if it stays right.

**Comment by notfood** [comment]
Possibly old save issue. Check with new save.

**Comment by notfood** [comment]
Closing this. Can't reproduce.
