### ISSUE TITLE
Subspace Burst Transponder Error + Cell Door not working right

### ISSUE THREAD

**Issue by aiu2003** [skyarkhangel/Hardcore-SK#598]
Cell door is acting like a normal door and is splitting the prisoner room from the outer room.

SBT throws:

Exception ticking Buildings_SubspaceBurstTransponder937532: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.IncidentWorker_OrbitalTraderArrival.TryExecute (RimWorld.IncidentParms parms) [0x00000] in <filename unknown>:0 
  at SK.Building_SubspaceBurstTransponder.SummonTradeShip () [0x00000] in <filename unknown>:0 
  at SK.Building_SubspaceBurstTransponder.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by Owlchemist** [comment]
For what it's worth, the cell door hasn't worked properly since I first noticed it in HCSK back in the a14 days.

It seems to me like the cell door *shouldn't* be usable by prisoners, considering the graphical style it uses (classic jail door look), but rather normal wooden doors would be usable by them.

**Comment by natasenasni** [comment]
I think the prisoners can open doors when they throw a tantrum, but they don't want to open them for needs like for food or such.

**Comment by sidfu** [comment]
i thought the prison door was  way to make personal areas for each prisoner. and the prision door allowed them to leave that area so say u couold have a common area and a outside area for them.

**Comment by skyarkhangel** [comment]
Subspace Burst Transponder soon fixed
