### ISSUE TITLE
Mobile Mineral Sonar missing

### ISSUE THREAD

**Issue by aiu2003** [skyarkhangel/Hardcore-SK#599]
I am using the latest mod version just uploaded 3 hours ago. The SBT works correctly now.

There are two entries in the Electronics Table for Mineral Solar Module and I don't see anywhere to build the Mobile Mineral Sonar that uses the module.

I am also getting the following error on startup:

Could not load UnityEngine.Texture2D at Things/Building/SatelliteDish in any active mod or in base resources.
Verse.Log:Error(String)
Verse.ContentFinder`1:Get(String, Boolean)
Verse.MaterialPool:MatFrom(String)
MobileMineralSonar.Building_MobileMineralSonar:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.PlayDataLoader:<DoPlayLoad>m__6F8()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

**Comment by skyarkhangel** [comment]
in next update fixed
