### ISSUE TITLE
Odin Hammer no stockpile spot

### ISSUE THREAD

**Issue by aiu2003** [skyarkhangel/Hardcore-SK#600]
Odin Hammer not showing up on the Stockpile list. Cannot haul. It looks like there's also a placement issue  since when I manually pick up and drop it, it lands on top of another item. Doesn't throw an error.

![odinhammer](https://cloud.githubusercontent.com/assets/24995725/22005679/e22af57c-dc2a-11e6-85be-d2a25a68b3e5.jpg)

 A small thing; the advance mine cannot be rotated? All the other mines can.

**Comment by Owlchemist** [comment]
Odin hammer confirmed, and submitted a fix.

As for the advanced mine I can't say if that was intentional or not.

**Comment by notfood** [comment]
Fixed.
