### ISSUE TITLE
Окна

### ISSUE THREAD

**Issue by Wolfius8** [skyarkhangel/Hardcore-SK#603]
Нашел тут один баг на а16, вообщем, на стене песчаника построил окна из обычного стекла, оно ресурсы потребовало , его достроили и как 100% постройки просто исчезло. Решил построить стены из стекла, она не пропускает свет.... Вопрос еще насчет растений: Раньше растения росли даже при простой лампе но с замедлением, а сейчас вообще не растут, это фикс игры или баг?

**Comment by skyarkhangel** [comment]
Thanks! Fixed.
