### ISSUE TITLE
Haygrass can't be grown

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#605]
Grass yields hay, but no seeds, but trying to grow haygrass fields I think requires seeds, so you can't actually grow it.

I presume the intention is like how we had it in A14 where only normal crops require seeds, but not simple native flora (personally I prefer this), but I think the crop field config needs to be updated to account for this.

**Comment by notfood** [comment]
Grass and Haygrass are two different plants. There is a haygrass seed.

Grass doesn't have seeds because you can't grow it. Plants that you can't grow don't have seeds.

**Comment by Owlchemist** [comment]
I see. That threw me off since I wasn't expecting different plants to yield the same thing - hay. Okay, thanks. Closing.
