### ISSUE TITLE
repeating error when pawn has no weapon for CR

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#606]
Exception in RimWorld.ThinkNode_ConditionalCanDoConstantThinkTreeJobNow TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at Combat_Realism.JobGiver_TakeAndEquip.TryGiveJob (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Combat_Realism.Detours_ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
RimWorld.ThinkNode_Conditional:TryIssueJobPackage(Pawn)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn)
Verse.AI.Pawn_JobTracker:DetermineNextConstantThinkTreeJob()
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

easy to find just start a game and the error appears till everyone has tool or weapon equiped

**Comment by skyarkhangel** [comment]
CR such often updates, test with latest version from master tree

**Comment by sidfu** [comment]
error seems to be gone now. had a random join and no error about themnot havveing anything equiped

**Comment by sidfu** [comment]
food seems to be causeing it now. seems like forbidden stuff is whats mainly triggering it on food.
