### ISSUE TITLE
Trading not working

### ISSUE THREAD

**Issue by Dunkhan** [skyarkhangel/Hardcore-SK#61]
Trading no longer gives the player items. The items given to the trader are subtracted but neither silver nor items are obtainable from the trader. The trade screen does not close, and clicking the accept button repeatedly subtracts the same items again from the player each time.

I am playing with a development version from 03.04.16 (9a3fe35305c45fb80045402d6f76a15b9a823dff) so i this is the result of some work in progress changes I completely understand. I am reporting this in case this was an unintended side effect of something that would otherwise not be noticed. 

In the attached log the relevant error message appears to be "Exception filling window for RimWorld.Dialog_Trade: System.Reflection.TargetParameterCountException: parameters do not match signature" which starts at line 1267 (triggered by loading save with a trader on the map)

Only tested with the tent traders, not with the orbital trader.

[output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/201391/output_log.txt)

**Comment by Nimander** [comment]
Same issue. Same version, but with disabled Skynet, enabled Crash_Landing_SK, MAI+, Darkness +SK patch and Do Not Disturb. Different error: [http://i.imgur.com/jKouHuH.png](url).

**Comment by Nimander** [comment]
I'm 90% sure it's caused by having a roof over trade stockpile.

**Comment by Dunkhan** [comment]
Confirmed with debug tools. If you have at least 1 trade building built outside, you can trade as normal including goods that are under a roof. This workaround makes the bug from a game breaker to a small nuisance. Thanks for the tip Nimander.

**Comment by jnk1136** [comment]
I don't have this issue with the 4.0 release, so it's definitely something that was changed since then.

**Comment by Dunkhan** [comment]
Sorry I forgot this was here. This is no longer an issue
