### ISSUE TITLE
Randy Random doesnt have Permadeath. I have found the problem.

### ISSUE THREAD

**Issue by Curlyjefferson** [skyarkhangel/Hardcore-SK#611]
As you might have known randy random doesn't have the "Permadeath" option. I dont know if this has been adressed yet , but the problem is the added difficulties have moved it off the screen. I have found that  Shortening his description brought the option back.  I hope this helps,

http://i.imgur.com/2BF6kbP.png

**Comment by skyarkhangel** [comment]
For now, playing with permadeath is not desirable. Bcs of bugs with beta HCSK for a16.
