### ISSUE TITLE
Explosion Error fps drop

### ISSUE THREAD

**Issue by firedoom13** [skyarkhangel/Hardcore-SK#614]
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.Explosion.Tick () [0x00000] in <filename unknown>:0 
  at Verse.ExplosionManager.MapComponentTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

I don't know if someone already report this, but here you go.
It happen when the Razer rain started

**Comment by zoranjoza** [comment]
I have same problem as thsi guy.

**Comment by skyarkhangel** [comment]
https://ludeon.com/forums/index.php?topic=12996.msg280195;topicseen#msg280195

**Comment by skyarkhangel** [comment]
hopefully fixed, relate to craters.
