### ISSUE TITLE
Ксенон-ионная турбина

### ISSUE THREAD

**Issue by Corwin4real** [skyarkhangel/Hardcore-SK#619]
Её никак не удаётся запустить, хоть ты ставь её в комнате где 10-20 паровых гейзеров и т.д....температура падает до ~100 и всё, выше уже никак не подымается. Раньше как я понял, можно было просто поджечь дерево или что то..и всё, проблема решена, но сейчас это не проканает =\=\

**Comment by skyarkhangel** [comment]
All works fine. Geysers not push temperature to extreme high values.
