### ISSUE TITLE
Misspelling in recipes definition

### ISSUE THREAD

**Issue by JLBShecky** [skyarkhangel/Hardcore-SK#62]
I went to use help to check the recipe for Manganese Alloy and discovered that it is misspelled as 'Maganese'. See lines 245-247 as it is misspelled in all instances. It is not really that big of a bug but for a beginner like myself it was a little confusing.

https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/RecipeDefs/Recipes_Bars_SK.xml#L245

**Comment by skyarkhangel** [comment]
Fixed. Thanks!
