### ISSUE TITLE
Being given free alpha poly apparel

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#624]
There's a random event in which one of your pawns shares with the colony one of their treasures. You've most likely seen it, it's not uncommon.

Problem is, if they give apparel, it seems the material type isn't defined, so it's just picking something alphabetically instead? ...which happens to be alpha poly, the second-best material in the game and quite OP for my year 1 colony to have.

![image1](https://cloud.githubusercontent.com/assets/5252347/22137201/6490e886-de8e-11e6-885c-2170bc2d154a.png)

**Comment by Rhyssia** [comment]
Related to https://github.com/skyarkhangel/Hardcore-SK/issues/572
