### ISSUE TITLE
Many errors with raid event

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#626]
The following error was happening every few ticks and started when there was a raid. The raid type was the one where they prepare for a little while before rushing the colony. It happened a little over 1000 times, only ending once the raiders started fleeing.

![image3](https://cloud.githubusercontent.com/assets/5252347/22142191/26e30232-deaa-11e6-8696-f19c72b3494a.png)

**Comment by sidfu** [comment]
thats the same error i was getting when i started a new colony. it went away when i gave everyong a weapon or tool.

**Comment by skyarkhangel** [comment]
since this issue, fixed 4 reasons where error starts
