### ISSUE TITLE
No events, eternal rainstorm.

### ISSUE THREAD

**Issue by Nimander** [skyarkhangel/Hardcore-SK#63]
Release 65d9d6d. In my current colony all events stopped happening and there is an eternal heavy rainstorm going on. Before the silence very little happened as well - only one raid in 7 months. At first I thought it is just RR making things randomly quiet, but I switched to Cassandra and it's pretty much same thing. Challenge difficulty.

I also get a constant spam in debug log about planting seeds. I don't know if this is related.
[http://i.imgur.com/Vx9wbcg.png](url)

**Comment by skyarkhangel** [comment]
in 12, was problem with some events which could affect on other. Try A13 please.
