### ISSUE TITLE
Simple grill - manufactured fuel accepts anything.

### ISSUE THREAD

**Issue by Traper** [skyarkhangel/Hardcore-SK#630]
If you allow kindling as fuel for simple grill colonist will use whatever is near, mechanisms, medicine etc.
http://imgur.com/B2KfnpB

**Comment by notfood** [comment]
Can you repeat it with a new save? It seems to be an old save issue. Clear the filter, have the item drop, save then reload.

**Comment by Traper** [comment]
Indeed it fixed itself after saving.
