### ISSUE TITLE
Research broken? 

### ISSUE THREAD

**Issue by Joshuawood1998** [skyarkhangel/Hardcore-SK#632]
I find i am unable to research the later techs in the tree such as matter conversion and renewables 4

Which after over 28 hours of game play in the world its a bummer. Not sure if its becasue it was a tribe or not. i couldn't find any documentation on it I Did have an advanced research bench with the multi-analyser 1 space away (there was the ghost line connecting the 2) along with the filing cabinet.

Sorry if i'm being a Twat. but i have play ALOT of this mod pack and i'm pretty sure i'm not missing anything 

Ps. Great work. I've played this one modpack about 30x longer than any other time in the game. And more than most AAA titles i've played

**Comment by Rhyssia** [comment]
Looking into it now.
