### ISSUE TITLE
Infinite Raspberry Bushes

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#635]
I was watching my tamed muffalo during the winter and I noticed that they were doing well as far as food went, I never had to feed them. But this was because they were eating raspberry bushes, which don't seem to get removed from the map when eaten. They were just gathered around 1 bush by the barn eating it over and over until they were full, everyday.

I was looking over the XML but I'm not quite sure how to fix that properly without breaking other systems...

**Comment by Rhyssia** [comment]
This is driving me insane, with core_sk\assemblies loaded, no issue. But once I start tossing folders back in it breaks.

**Comment by Rhyssia** [comment]
flag = (!base.IsCrop ? this.growthInt >= this.def.plant.harvestMinGrowth : true);  ??
Im not sure if it runs the evaluation or just returns as always true.

**Comment by notfood** [comment]
Seems to be a bad detour. It adds the Effecter but copies the original method wrong.

**Comment by Rhyssia** [comment]
So, it should be changed from :
`flag = (!base.IsCrop ? this.growthInt >= this.def.plant.harvestMinGrowth : true);`
to
`flag = (!base.IsCrop && this.growthInt >= this.def.plant.harvestMinGrowth);`

**Comment by notfood** [comment]
```csharp
    public static class PlantCrop
    {
        internal static bool Get_IngestibleNow (this RimWorld.Plant self)
        {
            if (self.def.plant.IsTree
                || (self.Growth >= self.def.plant.harvestMinGrowth
                    && !self.LeaflessNow
                    && (!self.Spawned
                        || self.Position.GetSnowDepth (self.Map) <= self.def.hideAtSnowDepth))) {

                self.def.ingestible.ingestEffectEat = EffecterDefLocal.EatVegetarian;

                return true;
            } else {
                return false;
            }
        }
    }```
