### ISSUE TITLE
Abominations don't work in the compost bin

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#636]
Normally any corpse you place in the compost bin decays rapidly, but not for the abomination for some reason.

**Comment by k4iser88** [comment]
What did you expect!? :)
![abo](https://cloud.githubusercontent.com/assets/24949302/22174478/ced06f12-dfdf-11e6-839e-86fc8502f001.png)

**Comment by skyarkhangel** [comment]
this is intentional.

**Comment by Bsonnete** [comment]
Burn it as fast as you can so deseases don't take over your village 😂😂
