### ISSUE TITLE
Research errors

### ISSUE THREAD

**Issue by freijie** [skyarkhangel/Hardcore-SK#639]
Several tech unlock errors i encountered during my first playthrough.

Its impossible to research low techs using hi-tech research table like in vanilla - is it intentional?

- Nanotechnology and Nano Replication are available for research but unlocked buildings are commented-out in xml - forgotten temporary fix?
- Storage II and Storage III needs to be swapped - 2nd gives items for 3rd and vice-versa.
- Fungi I gives access to all shrooms, mismatched with Fungi II and III's descriptions(they are supposed to unlock shimmershrooms(II) and gleamcap(III))
- Sheduled switch is unlocked before researching "timer switch" - is it intentional?
- Hygiene I and II descriptions are incorrect, (I) Should unlock crematorium according to it, but this building is unlocked at (II), (I) gives only runner carpets.
- Robotics has Circuit Breaker shown as an unlocked building. But it doesnt unlock it, in fact.

**Comment by Rhyssia** [comment]
Yup, this is on my to do list.
