### ISSUE TITLE
Error loading map

### ISSUE THREAD

**Issue by MrSamsa** [skyarkhangel/Hardcore-SK#640]
This save is a custom scenario with a few multipliers and events disabled. Also using prepare carefully. The save will nearly load up but fails at the end. Besides doing some map editing with dev mode the only thing I had done in this game was dress and equip the pawns. I thought it was being caused by the pawn weapon loadout but i wasnt able to reproduce the problem on a new map. 

The map that this save is failing to load on is messed up all the way back to the 1st autosave after its creation, so it appears to have been doomed all along? 
[badsave 5.0jewel 1-22-17.zip](https://github.com/skyarkhangel/Hardcore-SK/files/722119/badsave.5.0jewel.1-22-17.zip)

![rwhc log](https://cloud.githubusercontent.com/assets/25283162/22184312/2a6f0dd4-e09d-11e6-9e7d-d3e577f7d789.png)
![rwhc log 2](https://cloud.githubusercontent.com/assets/25283162/22184313/2dbf8978-e09d-11e6-9651-ea5c8b163154.png)
![rwhc log 3](https://cloud.githubusercontent.com/assets/25283162/22184314/2f3d1e8c-e09d-11e6-91ef-ce68469fe482.png)

**Comment by Rhyssia** [comment]
Think this might be related to incident keys that are found near top of save? (Have not looked)

**Comment by MrSamsa** [comment]
I cant imagine why they would be related but im no expert. I have other games with the same scenario started from without any issue so far. It wasnt a persistent problem with other saves i have but i posted this to serve anyone else that might find the info useful.

For this particular game I had the following incidents disabled; RazorRain, BoulderMassHit, MalariaRaid, FleaRaid, PermanentDarkness, Infestation, and Alphabeavers.

Also, I have the global learning modifier up at 1.5 to combat the skill bleed along with tailoring, smithing and sculpting speed at 1.5 normal.

**Comment by Rhyssia** [comment]
Alright, tomorrow after work I will look into issue.

**Comment by Rhyssia** [comment]
It is verb error, similar to stargate error.

**Comment by MrSamsa** [comment]
Idk what that means or how to prevent but glad its been identified.

**Comment by skyarkhangel** [comment]
difficult to understand without output.log. Screenshots with debug menu not saying much useful
