### ISSUE TITLE
A bunch of minor issues

### ISSUE THREAD

**Issue by freijie** [skyarkhangel/Hardcore-SK#641]
- Seeds please doesn't have seeds for caveflora fungi, somewhat inconsistent
- "Chest" storage description says it's capacity is up to 4 stacks, yet it contains up to 5 stacks of items.
- Wall torches use raw logs as a fuel, weird.
- Mining helmet's light spot sometimes causes a weird bug with pawns teleporting all over the screen(with an error pointing on the fact that it tries to apply lamp effect on incorrect coordinates), may be related to low free memory, happens most often when cpu is fully loaded.
- When there is no spare ammo ready for hunter, pawn just locks itself trying to shoot hunted animal, no ammo - nothing happens - pawn is stuck.
- Brick wall with builtin automatic lights got different brightness/hue in comparison to vanilla brick wall with the same material, looks weird.
- Probably vanilla bug, but visitors sometimes destroy colony walls(wood plank ones for me) when they want to get some fresh air and the door is whole dozen of tiles away.
- Is it intended that oil drill vanishes completely instead of staying here waiting to be disassembled after it's use? Even if its a feature, it feels like its a bug.
- No FSX on boomrats, if i recall correctly vanilla CR had both boomalopes and rats with FSX. Intended?
- Fenrir didn't start an attack on colony during eclipse event, was just walking around eatingneutral muffalos. Gotta tell ya that hunting down big doggie in forest is a pain in the ass with only 5 bows.
- I see completely OP centipede guns for cheap on some vendors. 110 accuracy long ranged minigun for like 1k-2k silver?

**Comment by sidfu** [comment]
caveflora cant be grown in zones so no need for its seeds.

torches and such not part of the custom refuel system so they still use stock

on stuck hunters just enlist unenlist will have them do next job in list. its been a known issue but there bigger fish to fry right now.

i remember reading about visitors doing that for vanilla so not 100% sure on that thou.

**Comment by freijie** [comment]
Still, why is there no need for seeds? Fungi are grown in non-maintained buildings which are not much different from zones, with very minor build cost to boot. I found that its much easier to just clear some rock and plant seedless fungi instead of waiting for seeds that i need. 

Vanilla cave flora got potato requirement for fungi cultivation, thus making it a long-term expensive investment, akin to hydroponics. With seeds/spores you'll at least have to dig some tunnels and wait for wild spawns first, forcing you to focus on other sources in the meanwhile.

Or is it a technical issue(eg cant use seeds please with fungoponics basin in general) and I misunderstood you?

**Comment by notfood** [comment]
mmm it's a plant, should work...

**Comment by notfood** [comment]
CaveFlora added to SeedsPlease: https://github.com/skyarkhangel/Hardcore-SK/commit/fe50ab401b2a2726dba159f703ee56e11edd021e

**Comment by notfood** [comment]
Right now FSX is unobtainable. Not even from Boomalopes.
