### ISSUE TITLE
Power Conduit Explosion Error

### ISSUE THREAD

**Issue by aiu2003** [skyarkhangel/Hardcore-SK#646]
Game was going good until a power conduit exploded. Afterwards, this error constantly ticks about 30 times a second causing massive lag during time compression. Reloaded to an autosave prior to explosion and was able to use time compression just fine.

System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.Explosion.Tick () [0x00000] in <filename unknown>:0 
  at Verse.ExplosionManager.MapComponentTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by Rhyssia** [comment]
that is assembly error, brought up in Discord for looking at.

**Comment by notfood** [comment]
Could it be a bad detour? I've seen this error in other types of explosions. It's always explosions triggering this infinite null bug.

**Comment by skyarkhangel** [comment]
what detour? No one of this methods not detoured

**Comment by notfood** [comment]
I looked around and found no detours in explosion code path. Not sure what is causing it.
