### ISSUE TITLE
Odd behavior & misc

### ISSUE THREAD

**Issue by MrSamsa** [skyarkhangel/Hardcore-SK#647]
Some weird things I notice that dont seem to have much or any reference.

- Colonists will stop research and ignore research tables until the research tree queue is changed/shuffled.

- Meals or objects colonists are supposed to put in their inventory to eat away from the colony are repeatedly picked up and dropped on the floor. The task description is "taking jerky" or something instead of "hauling jerky".

From what I can gather from issue #137 it seems the last problem lies somewhere within Combat Realism? I understand Russian better when I hear it than when I read it but, I think jnkyacc was pointing out that meals need to be allowed into the loadout somehow? With no workaround given I began playing with files and was able to stop the crazy behavior myself thankfully and the colonists even started packing meals in their inventory correctly to my surprise :P

I cannot find any solution to the colonists abruptly stopping their research and ignoring research tables anywhere here or from poking around in the game files. Was not a problem prior to removing the original research button.

If this info is apparent already I apologize.

**Comment by freijie** [comment]
Is it the same research table issue as https://github.com/skyarkhangel/Hardcore-SK/issues/639 ? Some technologies can only be researched on low-tech tables, hi-tech wont do.
Second issue happens when pawn has no available food added in their loadout (where you add weapons, search required food in 'select all' list)

I must say it really needs an additional "food" list in loadout interface, its very confusing for new players.

**Comment by MrSamsa** [comment]
The research problem doesnt seem related to issue #639. The research will abruptly stop no matter what is being researched by any tables. The issue started as early as the very first research categories such as vegetables or fruit cultivation with the low tech table. I constructed normal research tables and the problem has continued up to the last technology I have researched without high tech tables.

**Comment by MrSamsa** [comment]
Ive just noticed a error in the log that didnt seem to appear before, perhaps its related.

Couldn't relax research project coordinates apart after 200 passes.
Verse.Log:Error(String)
Verse.ResearchProjectDef:GenerateNonOverlappingCoordinates()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__735()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by freijie** [comment]
That error is from the techtree visuals, i recon. Not related to actual research job.

**Comment by Rhyssia** [comment]
Indeed, is dummy error.
Vanilla Rimworld Tech Tree trying to fit all techs into research tab
Fluffy_Research then overrides Vanilla Rimworld Tech Tree
