### ISSUE TITLE
Turkey Jerky?

### ISSUE THREAD

**Issue by MitsuKitsune** [skyarkhangel/Hardcore-SK#649]
It seems we are not be able to make jerky out of turkey meat?
In the Jerky cookingmenu bird meat is possible but turkey meat are not labeld as bird meat,
its seperatet into turkey meat.

**Comment by Rhyssia** [comment]
Looking into

**Comment by MitsuKitsune** [comment]
Hm its look like already fixed? I only had now the time to play the new uploaded version and there i can use turkey meat. :D
