### ISSUE TITLE
Ammo

### ISSUE THREAD

**Issue by lordmatiz** [skyarkhangel/Hardcore-SK#65]
Colonists aren't picking up ammo (dev branch).

**Comment by Vuursteen** [comment]
Are you load any of Edb mods?

**Comment by lordmatiz** [comment]
Yup. Prepare Carefully and Mod Order. Are they causing the problem?

**Comment by Vuursteen** [comment]
Yes, try disable this mods and leave only Edb Colonist Bar

**Comment by Vuursteen** [comment]
No new comments, so close this issue like solved
