### ISSUE TITLE
Fertilizer pump does not work after being moved?

### ISSUE THREAD

**Issue by Blothorn** [skyarkhangel/Hardcore-SK#653]
As it says on the tin--I built a fertilizer pump and it worked; I then moved it to a new location and nothing happened. Perhaps something is not getting reset when it is moved?

**Comment by notfood** [comment]
Save, then reload.

It's a problem with minified things.

**Comment by Blothorn** [comment]
That is still not working. (Tried moving, saving, then reloading; uninstalling, saving, reloading, installing.) No errors showing up.

**Comment by Rhyssia** [comment]
From Blothorn : Discord : 
" Oh, I looked into the source behind the issue I was having with moving fertilizer pumps--it seems that minifying an object does not automatically reset its instance variables (looking at the save game, the uninstalled pump is still tracking them). I think that the fertilizer pump needs to override DeSpawn() to reset ticksSinceExpand and timesExpanded when it gets uninstalled. "
