### ISSUE TITLE
new short has stack

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#654]
Hash collision between WallLamp_Blueprint_Install and  LoadoutGen_AmmoTypeI: both have short hash 35983
Verse.Log:Error(String)
Verse.<ThingsToSpawnAfterLoad>c__Iterator1CE:MoveNext()
System.Collections.Generic.List`1:AddEnumerable(IEnumerable`1)
System.Collections.Generic.List`1:.ctor(IEnumerable`1)
System.Linq.Enumerable:ToList(IEnumerable`1)
Verse.Map:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoader:LoadGameFromSaveFile(String)
Verse.Root_Play:<Start>m__736()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by notfood** [comment]
Should just rename the def, nothing else can be done until Tynan fixes it.
