### ISSUE TITLE
Terminator party event

### ISSUE THREAD

**Issue by Quelling** [skyarkhangel/Hardcore-SK#658]
https://i.gyazo.com/d43889749a235d781967076888748304.png - log
http://rgho.st/6ksSkstR2 - save

**Comment by skyarkhangel** [comment]
where log file?

**Comment by Quelling** [comment]
Sorry https://gist.github.com/Quelling/c72ebad2a8a02510d68b1cbb810b5ba9

**Comment by skyarkhangel** [comment]
I suppose its problem with RumoursAndDeception mod :/

**Comment by Quelling** [comment]
I am turn off Rumours And Deception mod but this error still pops up. Should I start new game or the problem was not here?

**Comment by skyarkhangel** [comment]
Fixed
