### ISSUE TITLE
Mushroom Recipes problem

### ISSUE THREAD

**Issue by Dudok22** [skyarkhangel/Hardcore-SK#661]
My pawns of sufficient skill level are unable to make mushroom stew, roasts etc. looks like glowbulb and shimershroom are not taken as basic food that is needed as is written in the recipe description.

**Comment by Blothorn** [comment]
Yes--looking at the defs they are impossible to make, as nothing in their ingredient filters satisfies the BasicPlantFoodRaw ingredient requirement.

I think the two ways to go here are making mushrooms BasicPlantFoodRaw (which would also allow them to be used in fine/elaborate meals, if you want to spend a few more mushrooms per meal to get the "Ate fine meal" thought), or relax the ingredient category for the mushroom-specific meals.
