### ISSUE TITLE
I'm getting this bug?

### ISSUE THREAD

**Issue by zoranjoza** [skyarkhangel/Hardcore-SK#663]
I'm getting this bug. My colonist has made jerky and he dont know where to put it, he is stuck, walking i meter up 1 meter down near stockpile..

```
Getting random element from empty collection.
Verse.GenCollection:RandomElement(IEnumerable`1)
RumoursAndDeception.InteractionWorker_RevealSecret:RandomSelectionWeight(Pawn, Pawn)
Hospitality.Detouring.<>c__DisplayClass4:<TryInteractRandomly>b__0(InteractionDef)
Verse.GenCollection:TryRandomElementByWeight(IEnumerable`1, Func`2, InteractionDef&)
Hospitality.Detouring.Pawn_InteractionsTracker:TryInteractRandomly(Pawn_InteractionsTracker)
RimWorld.Pawn_InteractionsTracker:InteractionsTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

```

```
Could not reserve Thing_MealJerky814551 for Miñoca doing job HaulToCell A=Thing_MealJerky814551 B=(144, 0, 165)(curToil=1) for maxPawns 1.Existing reserver: Breixo doing job Ingest A=Thing_MealJerky814551(curToil=4)
Verse.Log:Error(String)
Verse.AI.ReservationManager:LogCouldNotReserveError(Pawn, LocalTargetInfo, Int32)
Verse.AI.ReservationManager:Reserve(Pawn, LocalTargetInfo, Int32)
Verse.AI.ReservationUtility:Reserve(Pawn, LocalTargetInfo, Int32)
Verse.AI.<Reserve>c__AnonStorey465:<>m__6CE()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```

**Comment by Rhyssia** [comment]
Related to Rumors/deception mod maybe. Have pawn pick up jerky in inventory.

Does picking up jerky fix?

**Comment by zoranjoza** [comment]
No, they pick up , and move with it.UP and down 1m.
If i force them to draft and return them again to normal , they again stuck. 
I delete stockpile then they drop it on the ground where they stand and just leave.

**Comment by zoranjoza** [comment]
tyes

**Comment by zoranjoza** [comment]
I "created" error again this popup, maybe isnt related but popup in that moment,

`System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.GatheringsUtility.ShouldGuestKeepAttendingGathering (Verse.Pawn p) [0x00000] in <filename unknown>:0 
  at RimWorld.PartyUtility.ShouldPawnKeepPartying (Verse.Pawn p) [0x00000] in <filename unknown>:0 
  at RimWorld.PartyUtility.AcceptableMapConditionsToStartParty (Verse.Map map) [0x00000] in <filename unknown>:0 
  at RimWorld.VoluntarilyJoinableLordsStarter.Tick_TryStartParty () [0x00000] in <filename unknown>:0 
  at RimWorld.VoluntarilyJoinableLordsStarter.VoluntarilyJoinableLordsStarterTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`

**Comment by zoranjoza** [comment]
Again more lines about that error. This is related to that, i think. |Going exactly this order.
`Could not reserve Thing_MealSimple1241490 for WIndBuilderer doing job HaulToCell A=Thing_MealSimple1241490 B=(198, 0, 157)(curToil=1) for maxPawns 1.Existing reserver: Zoki doing job HaulToCell A=Thing_MealSimple1241490 B=(174, 0, 178)(curToil=2)
Verse.Log:Error(String)
Verse.AI.ReservationManager:LogCouldNotReserveError(Pawn, LocalTargetInfo, Int32)
Verse.AI.ReservationManager:Reserve(Pawn, LocalTargetInfo, Int32)
Verse.AI.ReservationUtility:Reserve(Pawn, LocalTargetInfo, Int32)
Verse.AI.<Reserve>c__AnonStorey465:<>m__6CE()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.Pawn_JobTracker:StartJob(Job, JobCondition, ThinkNode, Boolean, Boolean, ThinkTreeDef)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean)
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`
`WIndBuilderer started 10 jobs in 10 ticks. lastJobGiver=Combat_Realism.JobGiver_UpdateLoadout, curJob.def=HaulToCell, curDriver=Verse.AI.JobDriver_HaulToCell
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`
WIndBuilderer started 10 jobs in 10 ticks. lastJobGiver=, curJob.def=Wait, curDriver=Verse.AI.JobDriver_Wait
Verse.Log:Error(String)
Verse.AI.Pawn_JobTracker:StartErrorRecoverJob(String)
Verse.AI.Pawn_JobTracker:FinalizeTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by skyarkhangel** [comment]
I "created" error again this popup, maybe isnt related but popup in that moment,

System.NullReferenceException: Object reference not set to an instance of an object at RimWorld.GatheringsUtility.ShouldGuestKeepAttendingGathering (Verse.Pawn p) [0x00000] in <filename unknown>:0 at RimWorld.PartyUtility.ShouldPawnKeepPartying (Verse.Pawn p) [0x00000] in <filename unknown>:0 at RimWorld.PartyUtility.AcceptableMapConditionsToStartParty (Verse.Map map) [0x00000] in <filename unknown>:0 at RimWorld.VoluntarilyJoinableLordsStarter.Tick_TryStartParty () [0x00000] in <filename unknown>:0 at RimWorld.VoluntarilyJoinableLordsStarter.VoluntarilyJoinableLordsStarterTick () [0x00000] in <filename unknown>:0 at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 Verse.Log:Error(String) Verse.Map:MapPostTick() Verse.TickManager:DoSingleTick() Verse.TickManager:TickManagerUpdate() Verse.Game:Update() Verse.Root_Play:Update()

this bug related with terminator. Fixed
