### ISSUE TITLE
string errors i get

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#664]
No string files for Words/Nouns/ColonyNames.
Verse.Log:Error(String)
Verse.Translator:TryGetTranslatedStringsForFile(String, List`1&)
Verse.Grammar.Rule_File:LoadStringsFromFile(String)
Verse.Grammar.Rule_File:Init()
Verse.Grammar.RulePack:get_Rules()
Verse.RulePackDef:get_Rules()
RimWorld.NameGenerator:GenerateName(RulePackDef, Predicate`1, Boolean)
RimWorld.NameGenerator:GenerateName(RulePackDef, IEnumerable`1, Boolean)
RimWorld.Planet.FactionBaseNameGenerator:GenerateFactionBaseName(FactionBase)
RimWorld.FactionGenerator:NewGeneratedFaction(FactionDef)
RimWorld.FactionGenerator:GenerateFactionsIntoWorld(String)
RimWorld.Planet.WorldGenerator:GenerateWorld(Single, String, OverallRainfall, OverallTemperature)
RimWorld.Page_CreateWorldParams:<CanDoNext>m__527()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

total of around 8 striing errors related to names and directions

**Comment by sidfu** [comment]
new one related to CR armor color

Failed to find any texture while constructing Multi(initPath=Things/Apparel/SK/Vault_Security_Helmet, color=RGBA(0.659, 0.616, 0.490, 1.000), colorTwo=RGBA(1.000, 1.000, 1.000, 1.000))
Verse.Log:Error(String)
Verse.Graphic_Multi:Init(GraphicRequest)
Verse.GraphicDatabase:GetInner(GraphicRequest)
Verse.GraphicDatabase:Get(String, Shader, Vector2, Color)
RimWorld.ApparelGraphicRecordGetter:TryGetGraphicApparel(Apparel, BodyType, ApparelGraphicRecord&)
Verse.PawnGraphicSet:ResolveApparelGraphics()
RimWorld.Pawn_ApparelTracker:<ApparelChanged>m__2AD()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Update()
Verse.Root_Entry:Update()

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
all fixed in next update
