### ISSUE TITLE
locust attack errors

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#666]
Temperature check failed.
Verse.Log:Error(String)
SK.Events.Ticker_LCcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

Exception ticking LCcounter329170: System.NullReferenceException: Object reference not set to an instance of an object
  at SK.Events.Ticker_LCcounter.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by skyarkhangel** [comment]
ok. Fixed in next update
