### ISSUE TITLE
Does coffee seem weak and useless?

### ISSUE THREAD

**Issue by MrSamsa** [skyarkhangel/Hardcore-SK#672]
If this is intentional or known already forgive me but, coffee doesn't seem to be worth a damn now. When a colonist drinks coffee the effect only lasts about 1 in-game hour. Looking at the items_meals_drinks.xml coffee only gives a .05 severity and hediffs_caffeine makes it reduce by -1.0 per day which seems off.

Perhaps a starting severity of .5 instead of .05 would be more practical? It doesnt seem anything else needs to be changed except the blackout minSeverity from .45 to something like .90 to avoid instant passing out (lol) from 1 cup?

I wonder if instead of passing out its possible to make colonists act like cats during "crazytime" xP

**Comment by Joshuawood1998** [comment]
It does also give 20% rest which means the colonist just saves 1/5 of its sleep cycle from being needed. Which is more than enough time for the time invested in making the coffee. Seems more than worth to me

**Comment by MrSamsa** [comment]
I notice the rest is effected but, considering the time to grow the coffee and the mats you need just to brew coffee, it is not really worth the time now imo. If fatigue alleviation is now the primary purpose of coffee or tea instead of boosted performance that seems odd since coffee doesn't reduce fatigue but instead amps up the body to expend more energy. Because the boosts from caffeine are so short, it wasn't worth the effort in my colony to grow and brew coffee having beds that take only 5 hours to fully rest.

Prior to this update into a16 coffee was perfect for the time between early research & development, up to being able to produce bionics, since coffee would make colonists perform on par with their bionic betters
his update into a16 coffee was perfect for the time between early research & development, up to being able to produce bionics, since coffee would make colonists perform on par with their bionic betters.

I thought this was an oversight or something but perhaps its just me. :P
