### ISSUE TITLE
Terminator on caravan

### ISSUE THREAD

**Issue by Vandenberg** [skyarkhangel/Hardcore-SK#674]
When I send the T-1000 on a caravan, I get the message that the caravan could no be formed because a colonist was lost.

**Comment by skyarkhangel** [comment]
Old version? I'am fixed this

**Comment by Vandenberg** [comment]
Sorry running an older version. I assume I can't get the fix without breaking the game?

**Comment by skyarkhangel** [comment]
At own risk, but there were changes that 100% req. new game like update with nova race.
