### ISSUE TITLE
Feenix bug causing the game unable to load.

### ISSUE THREAD

**Issue by Michausz** [skyarkhangel/Hardcore-SK#675]
Game didn't load from save file after a Feenix appeared on the map.
Deleting Feenix item from the save file fixed it.

From output.log file:

> 
> Exception in SetupToils (pawn=Feenix340125, job=DrawEnergyFromFire A=Thing_Fire344673): System.NullReferenceException: Object reference not set to an instance of an object
>   at Verse.AI.ToilFailConditions.FailOnDespawnedOrNull[Toil] (Verse.AI.Toil f, TargetIndex ind) [0x00000] in <filename unknown>:0 
>   at SK.JobDriver_DrawEnergyFromFire+<MakeNewToils>d__0.MoveNext () [0x00000] in <filename unknown>:0 
>   at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0 
>  
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> Exception from asynchronous event: System.NullReferenceException: Object reference not set to an instance of an object
>   at Verse.AI.Pawn_JobTracker.CleanupCurrentJob (JobCondition condition, Boolean releaseReservations, Boolean cancelBusyStancesSoft) [0x00000] in <filename unknown>:0 
>   at Verse.AI.Pawn_JobTracker.EndCurrentJob (JobCondition condition, Boolean startNewJob) [0x00000] in <filename unknown>:0 
>   at Verse.AI.JobDriver.EndJobWith (JobCondition condition) [0x00000] in <filename unknown>:0 
>   at Verse.AI.JobDriver.SetupToils () [0x00000] in <filename unknown>:0 
>   at Verse.AI.JobDriver.ExposeData () [0x00000] in <filename unknown>:0 
>   at Verse.PostLoadInitter.DoAllPostLoadInits () [0x00000] in <filename unknown>:0 
>   at Verse.Game.LoadGame () [0x00000] in <filename unknown>:0 
>   at Verse.SavedGameLoader.LoadGameFromSaveFile (System.String fileName) [0x00000] in <filename unknown>:0 
>   at Verse.Root_Play.<Start>m__736 () [0x00000] in <filename unknown>:0 
>   at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00000] in <filename unknown>:0

**Comment by skyarkhangel** [comment]
ok. Delete it fo a first time before fix

**Comment by skyarkhangel** [comment]
updated
