### ISSUE TITLE
[SUGGESTION] Insectoid apiary

### ISSUE THREAD

**Issue by LEEROU** [skyarkhangel/Hardcore-SK#677]
Idea: Add a high-tier research that allows to create artificial insectoid hives. Similar to low-tier beehive, but instead of farming honey allows to farm insect jelly (in lower rate than natural hive). Also, add a chance for natural hive to drop bee-queen analog, and use it later in artificial one.

In need of discussion.

**Comment by Rhyssia** [comment]
Not really an issue, try suggestion in discord.
