### ISSUE TITLE
Raids are always from Insectoid Hive

### ISSUE THREAD

**Issue by Vandenberg** [skyarkhangel/Hardcore-SK#68]
In my current experimental game, I'm noticing raids are always from insectoid hives. When I spawn a raid with developer tools, insectoid hive. When I edit my savegame faction relation settings to make all 5 insectoid factions from hostile true to false, different factions show up for raid (always raiders/sparta).

**Comment by skyarkhangel** [comment]
Its seems we found raid chance balance for Insectoid faction
