### ISSUE TITLE
Berries can't be sown

### ISSUE THREAD

**Issue by Dunkhan** [skyarkhangel/Hardcore-SK#684]
It is not possible to sow any of the berry bushes on a farm plot.

Reproduction:
Research the a fruit growing tech (SK_FruitsI, SK_FruitsII, SK_FruitsIII)
Create farm plot
Go to plant type selection screen
Observe that the affected plants do not appear on the list

The issue appears to affect all plants on the SK_Fruits line except for tomato, which is growable, and the fruit drink recipe, which means the defs are being loaded. The affected plant defs are PlantAgave, Plantcloudberry, Plantgooseberry, Plantblueberry, PlantStrawberry, PlantGrape.

I was unable to spot any obvious problems in the defs so I have no idea what is causing this.

**Comment by sidfu** [comment]
think i know whats wrong ill get it fixed and pushed now

**Comment by sidfu** [comment]
a quick fix posted on forums use that. will be pushed to git in next few hours

**Comment by Dunkhan** [comment]
Confirmed no longer reproducible after commit 43a4fc4e45a0fdd31af78c1c757593228912e9d4
