### ISSUE TITLE
Cooler breaks the wall it was built on

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#687]
I built a tin cooler onto a marble wall in my walk-in-freezer. After it was finished, the wall it was built on vanished, leaving the cooler floating there.

I'm not using the redistheat module, though, I heard that might have something to do with it.

**Comment by Dunkhan** [comment]
just to clarify, the room still counts as inside and heat does not escape, it is also not passable. The bug appears to be only graphical.

**Comment by Rhyssia** [comment]
issue with <li>SK.PlaceWorker_OnWall</li> ?
redistheat uses <li>RedistHeat.PlaceWorker_WallChecker</li>

could change graphic from...
<texPath>Things/Building/Misc/TempControl/CoolerB</texPath>
to...
<texPath>Things/Building/Misc/TempControl/Cooler</texPath> which is vanilla cooler graphic

**Comment by skyarkhangel** [comment]
Soon fix this issue

**Comment by skyarkhangel** [comment]
Fixed
