### ISSUE TITLE
Not able to plant strawberries in fertile soil despite having research and seeds.

### ISSUE THREAD

**Issue by Rufert** [skyarkhangel/Hardcore-SK#690]
Option doesn't show up on the field.

**Comment by sidfu** [comment]
just checked and they working. check your load order. also if u useing any other plant mod it can and might cause that issue. also are u useing the version from today or older version

**Comment by sidfu** [comment]
ok u need FruitsIII research to plant strawberrys the discription for agriculter is wrong and will be fixed

**Comment by Rufert** [comment]
I had fruits 3 and  was allowed to extract the seeds at the plant table but they refused to plant in the ground. 

I am not using any other mods or have changed the mod order from the modconfig file that comes with hardcore sk.

**Comment by Rufert** [comment]
Made a video.

Maybe I'm just being dumb https://www.youtube.com/watch?v=NJgPHiS9No4

My cursor didn't show up in it. Hopefully not too confusing.

**Comment by sidfu** [comment]
try rienstall. if u notice the research isnt showing the plant picture. something somewhere is wrong. try this one make sure to change it into a .cfg and put it in. RimWorld\Mods\Core_SK\Defs\ThingDefs_Plants
[Plants_Tree_SK.txt](https://github.com/skyarkhangel/Hardcore-SK/files/743393/Plants_Tree_SK.txt)

**Comment by Rufert** [comment]
Reinstall with bugfix?  Since if I reinstall it'll be the exact same again.

**Comment by sidfu** [comment]
on the research if u look u not got the icon for the plant next to it so something is breakinng it there.
do u have dev console on to see if their a error?

**Comment by Rufert** [comment]
https://www.twitch.tv/sirrufert

Streaming it right now, if you have time pop in and tell me where to look :)

**Comment by Rufert** [comment]
Do you mean this? Only error I'm getting 
Couldn't relax research project coordinates apart after 200 passes.
Verse.Log:Error(String)
Verse.ResearchProjectDef:GenerateNonOverlappingCoordinates()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.Root:<Start>m__735()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__733()

**Comment by sidfu** [comment]
issue resloved can be closed
