### ISSUE TITLE
Bug: Infinite spawning of german shepherds

### ISSUE THREAD

**Issue by tessling** [skyarkhangel/Hardcore-SK#70]
Infinite spawning of german shepards without any notification of an event or anything. I just noticed them because my game started stuttering. Happens occasionally in my actual savegame didn't try a new one yet. 
looks like this:
http://i.imgur.com/InDlYwI.jpg

**Comment by tessling** [comment]
Update: after messing around in some other savegames in which this bug did not occur it finally did now again, this time around with nightlings

https://i.imgur.com/kXbmUc8.png

**Comment by skyarkhangel** [comment]
Temp. switch off plunderers event. Thanks.
