### ISSUE TITLE
Permanently Hunkered down while firing at something from point blank range 

### ISSUE THREAD

**Issue by fluffe9911** [skyarkhangel/Hardcore-SK#71]
So I tried firing a this boar that was right infront one of my dudes and now he is stuck and what seems a never ending hunker down

**Comment by fluffe9911** [comment]
Ok after like a day or 2 in game time he finally unhunkered down still weird though

**Comment by skyarkhangel** [comment]
hmm  ok...

**Comment by skyarkhangel** [comment]
Since A14, suppression removed.
