### ISSUE TITLE
Refugees from space pods are maybe always bugged?

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#726]
And by "bugged" I mean the abomination event. I'm not sure if I'm just having some real rotten luck here, but ever since I started playing the A16 version of HCSK a month ago, I've never once had an escape pod refugee that didn't turn into a monster. Is that just my luck, or is there an event calculation error? I'm not sure where to look to investigate myself...

**Comment by SoccaTheScrub** [comment]
I had several refugees that weren't Abominations. I always rescued them instead of capturing them, I'd say 80% joined my colony after being healed. Maybe there's something fishy with the 'capture' option ?

**Comment by Blothorn** [comment]
I have had one join, one abomination. Both were rescued, not captured.

**Comment by Owlchemist** [comment]
Guess it's just me then!
