### ISSUE TITLE
Dark in/under wood plank door. Huge problem with darkness event.

### ISSUE THREAD

**Issue by MitsuKitsune** [skyarkhangel/Hardcore-SK#728]
As it looks like the wood plank door is under permanent "dark" even if a lightsource is direct beside it. Even the "hold open" option dont fix this, the door is held open thats fine but the tile is still dark and for that an spawn point for the darkness creatures from the darkness event.

That way a multi-room building is a death trap. :D And i think that should be fixed.(if possible)

**Comment by Owlchemist** [comment]
Not an easy fix, maybe. Doors have the blockLight set to true. Except for the fence gate, so you theoretically could use gate fences instead. Or glass doors.

I think the assembly code that grants voids special spawning abilities would need to just not spawn them on top of doors.

**Comment by Dunkhan** [comment]
Doors arent the only thing, they sometime spawn in walkable workshops like the coal power plant (I do not have specific examples for the current version so this may no longer be true). I agree with the fix proposed by owlchemist but it needs to be extended to all buildings, so they only spawn on empty floor.

In the meantime there is a workaround for doors, especially necessary if you are playing the permanent darkness scenario: In the Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Doors.xml file change all instances of <blockLight>true</blockLight> to <blockLight>false</blockLight>
