### ISSUE TITLE
Several Cheese Issues -FIXED

### ISSUE THREAD

**Issue by Lukavy** [skyarkhangel/Hardcore-SK#739]
1) Cheese has 2 expiration timers and one of them is way too short, so raw milk lasts a lot longer, which doesn't make sense, especially since historically making cheese basically was a way to preserve milk without a fridge.

2) Cheese is treated as a meal and this causes 2 issues:
a) Like other meals it stacks in 10s, meaning that if we process (10 milk produces 4 cheese) a stack of milk (75) we get 3 stacks of cheese (10+10+8). I reality you need a bucket of milk to make a cup of cheese; cheese is much easier to store for long time than milk.
b) Cheese fills 25% of nutrition and since it is treated as a meal pawns eat only 1 at a time (unlike 10-20 of milk at a time) so they have to eat 4 times more often if they eat only cheese. This wastes a lot of time not only for process of eating 4 individual pieces of cheese, but also 4 travels across map into the fridge and back.

I think, both a) and b) can be easily solved if cheese made a "cooking supply" instead of "meal" so pawns eat 3-4 of it at a time and it stacks in 75s. Plus, in reality cheese IS a cooking supply, rather than an actual course.

**Comment by Owlchemist** [comment]
1.) is certainly a bug. It's been around for awhile now and was noted in another issue thread on here. I'm not immediately sure how to fix it, will take some investigation...

2.) Will look into that, thanks. In the meantime, you can turn cheese into a full course meal by making burgers or grill cheese with it. (btw it fills 20% nutrition).

**Comment by Owlchemist** [comment]
Alright, this should be fixed now in the next update.

**Comment by Lukavy** [comment]
Hey, thanks a lot!
