### ISSUE TITLE
Several Terraforming Issues

### ISSUE THREAD

**Issue by Lukavy** [skyarkhangel/Hardcore-SK#741]
1) When you "dig up water" you get "dig up water" tile that looks like mud.
2) Terraformed shallow water and mud are not suitable for building fishing buildings nor for collecting clay/peat. Because it looks the same as original water/mud - it gets pretty confusing sometimes. Maybe it should be made clear that natural mud/water does not equal artificial mud/water? But then what kind of "terraforming" would that really be?
3) I don't think algae can grow in created water. Offtopic: Also algae can grow in original water multiple plants on the same tile (once got 5 algae in the same tile) and if you order to harvest the tile with multiple algae in it - pawns harvest only one plant and order gets canceled.
4) It is possible to "dig up water" and create "shallow water" on natural rough stone floor, however it is impossible to make rich or "tiled" soil there. Does it really make sense? 
5) Artificial "rough stone floor" does not support cave flora mushrooms. Maybe it should be made clear that "natural rough stone floor" does not equal "artificial rough stone floor"?
6) I built a bridge on mud to speed up the movement of my pawns through the area, however pawns prefer walking through the mud next to the bridge.
9) It is possible to create "mud" and then "water" and then remove them; it is impossible to remove natural mud/water without pump and a ton of time. That is pretty inconsistent. It would be cool if you could reverse the pump to create actual mud/water - now THAT would be real terraforming.
8) Offtopic: brightbells in pots die if the soil under the pot is different from the natural rough stone floor. I understand them dieing when the pot is too far from the natural wall, but I do not understand why do you need a pot if it seems that you grow it in the ground. Maybe it's worth making say "growing spot" for them instead of growing them in a flower pot?

**Comment by Blothorn** [comment]
2. This makes sense to me (although I agree it should be better documented)--artificial ponds need to be stocked with fish if you want to fish there, and clay/peat require time to accumulate. (The fact that peat can be repeatedly harvested from the same place is its own balance/realism bug, but that is a different matter--in the meantime, I think that if you want a peat source you can harvest it from constructed rich soil.) The best use I can think of for terraforming to wetland is to make moats for defense--marsh/shallow water are slow to walk across and do not grow trees, making them excellent killing zones.
7. Probably some consolidation of terraforming techniques is in order...
