### ISSUE TITLE
Explosion related problem inducing a lot of lag

### ISSUE THREAD

**Issue by plasmidon** [skyarkhangel/Hardcore-SK#742]
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.Explosion.Tick () [0x00000] in <filename unknown>:0 
  at Verse.ExplosionManager.MapComponentTick () [0x00000] in <filename unknown>:0 
  at Verse.Map.MapPostTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.Map:MapPostTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

I've been getting this message repeadetly multiple times a second in the dev log,and ever since it appeared(I am pretty sure it was during a razor storm), my game lags horribly when I pick the 3 Speed option,which is pretty dissapointing..
![image](https://cloud.githubusercontent.com/assets/25616971/22701542/8f6345cc-ed66-11e6-8d2b-9779080b2e8a.png)

EDIT:I tried updating to the latest version from series 1400 to 1500,but it has not fixed the issue

**Comment by skyarkhangel** [comment]
Known problem. Use this:
https://ludeon.com/forums/index.php?topic=12996.msg280195;topicseen#msg280195

**Comment by plasmidon** [comment]
that fixed the problem,thanks a lot :)

I really appreciate your efforts into making this a great mod pack!
