### ISSUE TITLE
Components x0 after clothing recycling

### ISSUE THREAD

**Issue by Quelling** [skyarkhangel/Hardcore-SK#745]
Feb 6 version.

Give a command https://i.gyazo.com/5adfe2a4a12e401157943b53f6dcc360.png
Pawn take x0 component and bring it to storage.
https://i.gyazo.com/f1d0d08c9122cd5ae952cba1b9ca2833.png
https://i.gyazo.com/c1bce9d50cd158a49d852d34fa82bf9d.png

But, sometimes it gives error.
https://i.gyazo.com/8646b09d3d67bce1e3f892cee205213e.png

Log https://gist.github.com/Quelling/4148aec21ce438c683b35897784ca490

**Comment by Rhyssia** [comment]
Is known, Believed fixed.

**Comment by skyarkhangel** [comment]
should fixed in next update
