### ISSUE TITLE
Bug with food container - A16 - tribal early game

### ISSUE THREAD

**Issue by Kirinya** [skyarkhangel/Hardcore-SK#753]
Starting scenario was tribal, build from about 3 days ago, fresh setup of Vanilla & Hardcore mod.
Vanilla version 0.16.1393

Found working as intended: _Neither healroot tincture nor mushroom tincture can be used to treat patients, they are also not registered as medicine ("Low medicine - you have no medicine in storage"). 
All the tinctures were crafted by my tribe, so it shouldn't be a technology issue. Medical care is set to "best quality" for all pawns._

Also, food container "pot" was filled by cooking pawn with 7 stacks of pemmican instead of the 4 it should be able to hold max. It was placed at a one field distance diagonally from the cooking pawn, in case that's relevant.

**Comment by Owlchemist** [comment]
Tinctures are actually antibiotics instead of regular medicine. Still pretty helpful, boosts blood filtration. I think they need to be administered via operation menu (or eaten manually).

**Comment by sidfu** [comment]
correct. ad medicne treatment has less effect than blood filtrration the medicne from them was removed so that they can be admin while a pateint is in bed do same way as a operation. they can also be drunk manulay by right click.

**Comment by Kirinya** [comment]
Thanks for the info, good to now - I leave the issue open for the pot issue.
