### ISSUE TITLE
Отствует описание для легендарных предметов.

### ISSUE THREAD

**Issue by allanonHHS** [skyarkhangel/Hardcore-SK#76]
![image](https://cloud.githubusercontent.com/assets/12098411/15993400/b569892e-30ed-11e6-878a-5352405a7c4b.png)

По крайней мере для двуспальных кроватей. Скрафтил пару легендарных - описания нет.

**Comment by skyarkhangel** [comment]
Ок, спасибо. проверю.

**Comment by skyarkhangel** [comment]
Было поправлено в предыдущих обновлениях.
