### ISSUE TITLE
Grammarr: Kirin event pop up grammatical error (IcicatPasses)

### ISSUE THREAD

**Issue by Adenia37** [skyarkhangel/Hardcore-SK#763]
Event pop up states "An Kirin is wandering through the area. Solitary and peaceful, these legendary creatures are also known as frost incarnate. Said to be living ice, an Kirin heart is highly prized on the black market. While docile, an enraged Kirin is a sight to behold. They can be tamed and even trained, but only by the bravest - the best insulated - of men."

The word 'An' before 'Kirin' in each instance should be 'A' 

"A Kirin is wandering through the area. Solitary and peaceful, these legendary creatures are also known as frost incarnate. Said to be living ice, a Kirin heart is highly prized on the black market. While docile, an enraged Kirin is a sight to behold. They can be tamed and even trained, but only by the bravest - the best insulated - of men."

**Comment by Owlchemist** [comment]
Fixed.
