### ISSUE TITLE
Fuel filters don't work right, colonists will burn many items

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#767]
This was reported in ticket #630 but prematurely closed. I have tracked down the cause of this problem that some people have been reporting on. If you click on one of the categories (instead of the specific item), the game is secretly enabling everything everything within that category, not just the items you're allowed to see. Likewise, if you click "allow all", it's doing the same thing, but for all categories at once.

In the meantime, players should avoid clicking categories and only the specific fuels they want.

**Comment by skyarkhangel** [comment]
Fixed in next update
