### ISSUE TITLE
Бесконечные попытки заправить топливом "выключенные" станции и, как следствие, зависание персонажей..

### ISSUE THREAD

**Issue by WareXD** [skyarkhangel/Hardcore-SK#77]
Проблема:
Сканер работ спамит поселенцев бесконечной выдачей работы на заправку топливом выключенную электростанцию. Каким-то образом движок игры считает Выключена, - значит недоступна, но продолжает выдавать наряды. Как следствие, после срабатывания защиты в ограничение 10 работ, заставляет персонажа зависать в состоянии `Wait`. 

Подробнее:
Объекты, наследующие классы `CompProperties_Refuelable`, `CompProperties_Flickable`, сталкиваются с некоторым багом в коде Рима. Признаться, сам до конца не разобрался, но ниже попытаюсь немного объяснить.

Выше указанные классы, грубо говоря, добавляют объектам 4 состояния:

1. Есть топливо, Включено;
2. Есть топливо, Выключено;
3. Нет топлива, Включено;
4. Нет топлива, Выключено.

Первые три работают исправно, но 4ое работает не как должно.
Пока на данный момент, такие объекты в моде это Электростанции, т.е. наследующие класс `CompProperties_Power`. 

~~При сканировании доступных работ, движок игры, исполняя проверочную функцию `CanRefuel` класса `WorkGiver_Refuel`, судя по всему, не проводит проверку на состояние объекта `<switchOn>false</switchOn>` установленный классом `CompProperties_Flickable`. К тому же, последний дополнительно использует внутреннюю систему сигналов (таких как `FlickedOn`, `FlickedOff`, `wantSwitchOn`) для своей реализации, что дополнительно расшатывает крышу)~~

Функция класса `WorkGiver_Refuel`:
```C#
 	private bool CanRefuel(Pawn pawn, Thing t, bool mustBeAutoRefuelable)
		{
			CompRefuelable compRefuelable = t.TryGetComp<CompRefuelable>();
			if (compRefuelable == null || compRefuelable.IsFull)
			{
				return false;
			}
			if (mustBeAutoRefuelable && !compRefuelable.ShouldAutoRefuelNow)
			{
				return false;
			}
			if (t.IsForbidden(pawn) || !pawn.CanReserveAndReach(t, PathEndMode.Touch, pawn.NormalMaxDanger(), 1))
			{
				return false;
			}
			if (this.FindBestFuel(pawn, t) == null)
			{
				ThingFilter fuelFilter = t.TryGetComp<CompRefuelable>().Props.fuelFilter;
				JobFailReason.Is("NoFuelToRefuel".Translate(new object[]
				{
					fuelFilter.Summary
				}));
				return false;
			}
			return true;
		}
```

> ILSpy is the open-source .NET assembly browser and decompiler

~~Как обойти:
@skyarkhangel, я понимаю для чего выбрали `CompProperties_Flickable`, жаль, но не работает. 
Кстати, как мне кажется _Хоппер_ был придуман как костыль, для того чтобы обойти это.
В общем, решений несколько:
Или писать DLLку-патч, инкапсулировать функуию `CanRefuel` (но, честно, хз как это отразится на остальном) и она ли корень проблемы и одна ли вообще;
или, пока Тайнан снизойдет,  использовать костыль. Вместо `CompProperties_Flickable` использовать **`CompProperties_Forbiddable`**. Но есть подводные камни -> В `CompProperties_Refuelable` нельзя использовать `<consumeFuelOnlyWhenUsed>true</consumeFuelOnlyWhenUsed>`, точнее не работает (ресурсы вообще не потребляются). Иными словами, не использовать ресурсы при выключенной электростанции не получится, да и графически вместо выключателя - крестик, но хотя бы остальное работает и более удобно, чем искать и маркировать ресурсы. Кстати и более менее объяснимо, например, забавно пытаться выключать дрова или уголь, а вот для остановки подачи следующей партии топлива в самый раз. К тому же, для ограничения подачи электричества уже есть рубильник-выключатель. Единственный минус, это графическое отображение состояния - крестик вместо выключателя.~~

~~Пока все "забагованные" объекты сосредоточены в файле
`Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Power_SK.xml`~~

С уважением.

**Comment by WareXD** [comment]
Так, интересный момент. 
**всё вышесказанное надо пересмотреть**.
В файле `Mods\Core\Defs\ThingDefs_Buildings\Buildings_Power.xml` (с чистого Рима) объявленный объект `<defName>FueledGenerator</defName>` также наследует `CompProperties_Refuelable`, `CompProperties_Flickable` и работает исправно!
В то время как в файле `Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Power_SK.xml` некоторые объекты вызывают ошибки.
Пока не могу понять в чем диссонанс...

**Comment by WareXD** [comment]
@skyarkhangel Всё. Нашел в чем баг. В чрезмерной гибкости XML. Хе-хе.
Наследование объектом класса `CompProperties_Flickable` должно быть **раньше**, чем `CompProperties_Refuelable`!
А это, в принципе, затрагивает много объектов.
Вероятно дело в конструкторах классов. В `CompProperties_Refuelable` какие-то объявления или инициализация пересекаются с переменными `CompProperties_Flickable`. До конца ковыряться нет желания, простите. 
Главное, теперь всё работает, включая возможность не потреблять ресурсы при выключенном состоянии, но **момент интересный** и призывает мододелов подумать, прежде чем лепить что-то в XML, особенно с классами.

Спасибо за внимание и Ваш труд, надеюсь скоро поправите и спокойно поиграем))
С уважением.

**Comment by skyarkhangel** [comment]
Привет. Мы уже в курсе этого бага, убрали CompProperties_Flickable у строений использующих CompProperties_Refuelable. В последних версиях их нет. В моих планах дописать CompProperties_Refuelable и WorkGiver_Refuel, который будет осуществлять проверку на Flickable Как видите там ничего нет. Спасибо за фишку про наследование классов, действительно стоит задуматься.

**Comment by WareXD** [comment]
@skyarkhangel Кстати, да, привет)
Если в курсе, тогда молодцы. Но тогда почему этот **master** содержит такие ошибки, разве это не тест последней версии, не 3.0 или я ошибаюсь?


Просто, к примеру, в этом мастере файл: 
`Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Power_SK.xml` 
содержит как раз такие ошибки. Вот часть кода Угольной электростанции:
```xml
<comps>
	<li Class="CompProperties_Power">
		<compClass>CompPowerTrader</compClass>
		<basePowerConsumption>-2300</basePowerConsumption>
		<transmitsPower>true</transmitsPower>
	</li>
	<li Class="CompProperties_Refuelable">
		<fuelConsumptionRate>28.0</fuelConsumptionRate>
		<fuelCapacity>200.0</fuelCapacity>
		<fuelFilter>
			<thingDefs>
				<li>Coal</li>
				<li>Charcoal</li>
				<li>Peat</li>
			</thingDefs>
		</fuelFilter>
	</li>
	<li Class="CompProperties_Glower">
		<glowRadius>6</glowRadius>
		<glowColor>(217,112,33,0)</glowColor>
	</li>
	<li Class="CompProperties_Breakdownable"/>
	<li Class="CompProperties_Flickable" /> 
</comps>
```
Чтобы все работало и `WorkGiver_Refuel` не спамил, всего-то нужно поменять местами строчку:
```xml
<comps>
	<li Class="CompProperties_Power">
		<compClass>CompPowerTrader</compClass>
		<basePowerConsumption>-2300</basePowerConsumption>
		<transmitsPower>true</transmitsPower>
	</li>
	<li Class="CompProperties_Flickable" /> <!-- эта строка должна быть здесь -->
	<li Class="CompProperties_Refuelable">
		<fuelConsumptionRate>28.0</fuelConsumptionRate>
		<fuelCapacity>200.0</fuelCapacity>
		<fuelFilter>
			<thingDefs>
				<li>Coal</li>
				<li>Charcoal</li>
				<li>Peat</li>
			</thingDefs>
		</fuelFilter>
	</li>
	<li Class="CompProperties_Glower">
		<glowRadius>6</glowRadius>
		<glowColor>(217,112,33,0)</glowColor>
	</li>
	<li Class="CompProperties_Breakdownable"/>
</comps>
```

**Comment by skyarkhangel** [comment]
Хм, ок. Значит или забыли где-то убрать или случайно откатили. Поправим, проверим

**Comment by WareXD** [comment]
Да, проверьте, пожалуйста, т.к. есть ещё несколько электростанций с такой проблемой.
Спасибо за быстрый фидбэк.

**Comment by skyarkhangel** [comment]
Проверено. Сделано.
