### ISSUE TITLE
Почему не WTF-4?)

### ISSUE THREAD

**Issue by WareXD** [skyarkhangel/Hardcore-SK#78]
`Mods/Core_SK/Languages/Russian-SK/DefInjected/RecipeDefs/Recipes_Bulk_Meals.xml` 
использует UTF-4. [ISO/IEC 10646:2014](http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=63182) не слышали об этом, даже на [1 апреля](http://tools.ietf.org/html/rfc4042)

**Comment by Ivanzyfer** [comment]
Спасибо :) Исправим
