### ISSUE TITLE
"Hyglene" research typo

### ISSUE THREAD

**Issue by Morlark** [skyarkhangel/Hardcore-SK#780]
All instances of the word "hygiene" in the research tree are typoed as "hyglene" instead.

**Comment by Rhyssia** [comment]
lol yeaaah...

**Comment by Owlchemist** [comment]
Fixed.

**Comment by Dunkhan** [comment]
I have seen a bunch of typos, is it useful to make a collection issue for them?
e.g. Convectional Power -> Conventional Power
