### ISSUE TITLE
Проблема с SK.Building_PL

### ISSUE THREAD

**Issue by WareXD** [skyarkhangel/Hardcore-SK#79]
Наружные лампы `<defName>OutdoorGroundLamp</defName>` и `<defName>Lighting_PathLamp</defName>`, объявленные в `Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Furniture_SK.xml`, не работают.
Накопление и расход энергии в норме, но, предполагаю, что наследуемый `<CompGlower>` не получает сигналы `PowerTurnedOff` или `PowerTurnedOn`, тем самым визуально не изменяют своего состояния и "горят" постоянно, как днем, так и без энергии.

**Comment by skyarkhangel** [comment]
Да, похоже забыли обновить с А12 версии.

**Comment by skyarkhangel** [comment]
Fixed in A14 update.

**Comment by jnkyacc** [comment]
@skyarkhangel Not fixed.
