### ISSUE TITLE
Flower pots and flowers

### ISSUE THREAD

**Issue by Dechukni** [skyarkhangel/Hardcore-SK#791]
Flowers planted in flower pots have their texture hidden under flower pot texture, due to their altitudeLayer being LowPlant while pots have default Building that is higher. That itself is easy fix, upon fixing, the next problem is that arguably all flowers except red roses almost never spawn in the center of square, that makes them look like they are growing out of flower pots' walls.

**Comment by Owlchemist** [comment]
Fixed the altitude, thanks.

As for the non-centering, that is a more convoluted problem. It would require a new set of flowers and sowing "recipes" and research unlocks to go with them, with the only difference being a more centered, orderly placement instead of the wild look they go with now.

**Comment by Dechukni** [comment]
Decorative sowing recipe applies only to them, so it is just a point of creating one more parent abstract class that covers only decorative, changing old one to cover only wild, then coping existing set and setting them to inherit from new class. Also, make the wild subclass unsowable so there is no need for new techs. 
As a suggestion maybe decrease actual variety in flowers that can grow in wild, because it is unreasonable that all cultivated flowers can survive in wild climate

**Comment by skyarkhangel** [comment]
Agree, we can just increase fertility req. for decorative plants.

**Comment by Dechukni** [comment]
Btw current fix makes flowers to be Item altitudeLayer that breaks their textures in wild, making them overlap boulders/trees, it is better to move them back to LowPlant, and then move flower pots to Zone layer
