### ISSUE TITLE
Merchants freezing to death

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#795]
Most factions are allowed to arrive as low as -45C, but, they are not often geared to survive such cold temperatures and die.

I'm not certain the best way to fix this, because simply changing their allowed temperature range may result in too few traders in very cold biome, which are especially in need of traders to survive.

**Comment by Dunkhan** [comment]
Any way to control their clothes? If they all had wool jackets they would probably be ok

**Comment by skyarkhangel** [comment]
up traders closes resist to cold in next update. Thanks!
