### ISSUE TITLE
Green Wyverne is OP

### ISSUE THREAD

**Issue by LEEROU** [skyarkhangel/Hardcore-SK#803]
As you know - fire in RimWorld is a big problem. Besides of enormous amount of lags it produces - it can destroy almost all vegetation in playable map.
Wyverne starts fire when it is hungry, but their nutrition decreasment is as fast as decreasment of other species. It means that wyverne willl start a fire almost at the beginning of play.
Also, even when wyverne is surrounded by fire - its nutrition increases too slowly, meaning that it will start fire over and over again, even if colonists have managed to extinguish it.
Please, rework wyverne's hunger rate, to prevent it from starting a fire too frequently.

Thanks.

**Comment by skyarkhangel** [comment]
reworked in next update.
