### ISSUE TITLE
Characters just standing

### ISSUE THREAD

**Issue by lordmatiz** [skyarkhangel/Hardcore-SK#81]
Hello.
I've got problem in which my characters are standing still, idling or simply doing nothing.
[SAVE](http://s000.tinyupload.com/?file_id=24282392546955444122) where after 2-3 minutes everyone is standing.

**Comment by skyarkhangel** [comment]
Try to check powerplants. There are bug, when colonists can't to refuel while powerplant switched off.

**Comment by thadius856** [comment]
@lordmatiz I've experienced what skyarkhangel is describing.

In my case, it was `Fueled Power Plant`. Even when flicked off, it still consumes (wood) fuel. Once it drops low enough to trigger a refuel job, the pawn that gets assigned to it just starts standing around.

If you turn on `Developer Mode`, your see your console being spammed with the colonist trying to take 10 jobs in 1 second and failing.

**Comment by Mordochor** [comment]
I have the same issue, but it's not related to powerplant. I've assigned creation of chitin caps at the tailoring workbench and my crafter got the materials and started working on it. After a while she stopped and is unable to work. I can assign another work, but when i prioretize tailoring, she gets there, even takes the unfinished product if it's hauled to stockpile and stands in front of the bench. UI says she's standing.

**Comment by skyarkhangel** [comment]
Obsolete. Should work fine with new refuel system.
