### ISSUE TITLE
UI Elements misplaced when using  1.5x magnification

### ISSUE THREAD

**Issue by Kurios** [skyarkhangel/Hardcore-SK#815]
when using non 1x UI scale (for larger resolution monitors), 

![image](https://cloud.githubusercontent.com/assets/255022/23443720/8f901338-fde5-11e6-8c56-3d80263e1707.png)

becomes 
![image](https://cloud.githubusercontent.com/assets/255022/23443736/a553b74c-fde5-11e6-802a-380d1f3b89fb.png)

**Comment by skyarkhangel** [comment]
bug from A16, seems fixed in next a17
