### ISSUE TITLE
Faction Ulir Gaf of def NorbalTribe has no usable PawnGroupMakers

### ISSUE THREAD

**Issue by augustofinamore** [skyarkhangel/Hardcore-SK#82]
Every game I get this error message several times:

Faction Ulir Gaf of def NorbalTribe has no usable PawnGroupMakers for parms (target=Tortoise134497 points=52 )

Faction Ulir Gaf of def NorbalTribe has no usable PawnGroupMakers for parms (target=Squirrel134644 points=124 )

I think this is causing the faction is always getting anger because of missing members. 

Tried I clean install with only this mod pack, still the same issue.

**Comment by skyarkhangel** [comment]
Very strange.. ok.

**Comment by skyarkhangel** [comment]
Closed. Vanilla storyteller feature.
