### ISSUE TITLE
Raider stuck in 10 jons in 10 ticks

### ISSUE THREAD

**Issue by Canute00** [skyarkhangel/Hardcore-SK#828]
Release from march 4.
Human sapper raiders stuck at their appearence. They wander a bit around but don't attack.
Heavy lag spikes.
After a while they raider decide to leave.
That happen now 2 of 2 times with humanoid sappers.
https://gist.github.com/82f1a0c05e025cd63b71cfd1c95aa314

**Comment by Dunkhan** [comment]
I had this twice in a row with visitor in the same spot in my base. There used to be a guest bed there but I moved it. Eventually they starve to death.

**Comment by skyarkhangel** [comment]
this relate to CR, so we fixing this.
