### ISSUE TITLE
Colonists being released from their duty when there are no active enemies.

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#830]
The problem is when darkness comes, and you wish them to stay within light source, they always trying to run to go their business instead as they see no active enemies, while darkness kills them if you don't stop them by drafting them again, but with like 6 or 7 colonists doing so at once, makes it quite annoying to do it over and over again, pausing the game, till the darkness passes.

**Comment by Dunkhan** [comment]
I always just restrict them to a very small area around the light. Then they stay put
