### ISSUE TITLE
Embrasures too good, or skynet too dumb?

### ISSUE THREAD

**Issue by Inei** [skyarkhangel/Hardcore-SK#836]
I just got that terminator event after which there was terminator attack, the problem is that all of them instead of trying to shoot my colonists, were effortlessly trying to get inside my stronghold by melee attacking the doors and walls, while colonists been shooting them through embrasures, though, even five of them attacking the door at once were not been able to do much damage, and my constructor had little trouble keeping fixing the doors, and those walls I damaged badly with my own shots, while all the terminators got shot one by one. I understand that if they kept shooting me I'd probably lost few my colonist, considering I had to spend almost all ammo my colonists had to put them down this way, but the way they are now - having all the weapons, but stupidly trying to keep attacking the doors and walls in melee, it is just no fun at all to fight them.

**Comment by skyarkhangel** [comment]
ok
