### ISSUE TITLE
Hospitality needs to be updated

### ISSUE THREAD

**Issue by LetheNyx** [skyarkhangel/Hardcore-SK#84]
There's a section of code left in the hospitality DLL that makes it where no matter what, the chief is angered because of people going "missing" this was patched with the newest 1.13c update of Hospitality but the current version isn't in the modpack.

I'd very much enjoy being able to make friends with tribals and such instead of having them constantly pissed off at me for people going missing even though I've watched them walk off the map happy and healthy...

**Comment by skyarkhangel** [comment]
Soon were updated

**Comment by skyarkhangel** [comment]
Updated
