### ISSUE TITLE
Рыбалка

### ISSUE THREAD

**Issue by TheMoonLite** [skyarkhangel/Hardcore-SK#842]
Уже который раз (неделю) сталкиваюсь с проблемой.
Поставил пирс для рыбалки.
Рядышком (как позволяет система ставлю второй)
Проходит несколько игровых месяцев.

И когда охотник добывает очередную рыбу, она почему то ставится под запретом.
Причём не важно оставляет он её на пирсе или же есть склад для рыбы.
И всё, сколько бы он дальше рыбы не ловит, она вся под запретом. Приходится постоянно снимать с неё запрет. Что очень гемморно. Просьба пофиксить.

http://image.prntscr.com/image/4ab4d570d44644a6a2a3d732fa999aaf.jpeg

**Comment by FaHT1k** [comment]
Пирс должен находится в "домашней зоне", тогда запрет ставиться не будет.
