### ISSUE TITLE
Wrong race

### ISSUE THREAD

**Issue by Canute00** [skyarkhangel/Hardcore-SK#844]
Not sure if you can fix this.
But the mother of one of my pawn droped with an escape pod.
Pawn Asari
Mother human

**Comment by Inei** [comment]
Well, according to Asari biology, if I remember Mass Effect lore correctly,  asari can have children with any other race and gender. So, if another mother of your asari pawn is asari too - all is correct, and she just having two mothers.

**Comment by Canute00** [comment]
Maybe at this case you got a lore exception.
But what do you would say if the pawn was Orassan ?
Inter-race relationships are very rare.

**Comment by Inei** [comment]
If the pawn was orassan it would be totally another case somehow. :)
