### ISSUE TITLE
"There was a problem saving [...] ColonistBar_KF.xml"

### ISSUE THREAD

**Issue by ktrzos** [skyarkhangel/Hardcore-SK#845]
Error on screenshot:
![err](https://cloud.githubusercontent.com/assets/14212721/24042165/16bec13c-0b11-11e7-9c5d-ffa8830035b2.png)

This error is appearing couple of times with random moments.

**Comment by sidfu** [comment]
usualy something like that happens when the file or folder is protected. make sure any existing .cfg for it isnt write protected.

**Comment by ktrzos** [comment]
(Windows 10 here)
I've run Rimworld as an Admin.

**Comment by sidfu** [comment]
dont matter if u run it in admin if the file is read only it wont write to it. same with folder if its read only folder even windows itself will fail to write a file in that folder.

**Comment by ktrzos** [comment]
I see. Could this files saving be blocked while having opened `Config` directory in Windows Explorer? Does this directory recreating while playing game?

**Comment by sidfu** [comment]
the config files are saved to the app data area where the modconfig.cfg is. its possible that the ones included in pack are readonly by accdent or the folder for configs is read only.

**Comment by ktrzos** [comment]
Ok, I'll make some "tests" and, for now, close this issue, because no major bugs are happening right now with the game. Thanks for the help!
