### ISSUE TITLE
Не работает торговля и странный интерфейс.

### ISSUE THREAD

**Issue by EttyKitty** [skyarkhangel/Hardcore-SK#85]
Проблема в том, что у меня по каким-то причинам перестала работать торговля с приходящими торговцами ~~из определенной фракции (не уверен, но пока из других фракций просто не приходили)~~, поселенец подходит, ничего не происходит и он идет заниматься другими делами. Фото лога приложу. ~~С этой фракцией были нормальные отношения, потом началась война, потом война прекратилась, но отношения сейчас -52. Не знаю связанно ли это.~~
Вторая проблема в том, что у меня начал некорректно отображаться интерфейс иконок колонистов. Играю на старом мониторе 1280x1024, знаю, что это не самое популярное разрешение, однако я никогда не имел проблем с этими иконками ранее. Сейчас иконки начали центрироваться по правой стороне, вместо стандартной середины из-за этого пришлось переносить мини-карту ниже и боюсь, что с приходом второй колонки - придется переносить еще ниже, а с приходом третьей - вовсе отключать. По 8 колонистов в одной колонке. Возможно как-то отцентрировать эти иконки по центру, как это было раньше? Понимаю, что менять под меня все не рационально, поэтому эта проблема скорее моя личная, чем пака, но все же мне интересно можно ли ее решить.
Заранее спасибо.
![1](https://cloud.githubusercontent.com/assets/20323032/16628744/a8217d7c-43bb-11e6-99a4-7f4be6bd7986.png)

**Comment by EttyKitty** [comment]
Еще постоянная проблема с отношениями. Ко мне приходят люди из других фракций и в то время, когда они крутятся вокруг моих зданий - мне уже приходит минус отношений от их вождя, ибо они по его мнению пропали на моей территории.

**Comment by skyarkhangel** [comment]
Скорее всего это баги в офф. версии. В А14 будут изменения и фиксы ошибок связанные с торговлей. На счет минуса отношений с другими фракциями, в посл. апдейтах было обновление, которое должно исправить эту ошибку.

**Comment by EttyKitty** [comment]
Спасибо за ответ. Я узнал все, что хотел. Если на счет иконок что-то можно будет придумать - отпишите, если будет не трудно на вашем же форуме мне в личные сообщения, а эту тему я закрою, чтобы не мешалась под рукой.
Ник на форуме: December.
