### ISSUE TITLE
Mine Extractor Issues

### ISSUE THREAD

**Issue by Fizzler** [skyarkhangel/Hardcore-SK#853]
I've noticed that sometimes the mine extractors just stop working, the part that descends into the shaft just stays at the top and never moves or produces ores. These are ones I've just built and they eat power and make me waste resources by demolishing/rebuilding. I've checked the debug log but couldn't find anything relevant.

Also, as a side note, for some reason the animation for the mine is slower at 4x speed. I'm not sure if that makes production slower as well or not.

**Comment by skyarkhangel** [comment]
ok

**Comment by reaper0022** [comment]
same here

**Comment by skyarkhangel** [comment]
fixed in next update
