### ISSUE TITLE
Bug: Mosquitoes/Flies always keep sucking blood

### ISSUE THREAD

**Issue by pongvin** [skyarkhangel/Hardcore-SK#854]
It seems that the mentioned insects are always hungry for blood and are permanently trying to suck blood, despite their full hunger bar.  See attachment screengrab.

Thank you for your work in any case, great mod!

[Video_2017-04-06_210547.zip](https://github.com/skyarkhangel/Hardcore-SK/files/903701/Video_2017-04-06_210547.zip)

**Comment by sidfu** [comment]
not a issue far as i know. the on purpose made to keep attacking to try to give malaria. just kill them they take 2 hits to die

**Comment by pongvin** [comment]
Understood, but still seems weird, real mosquitoes don't do that. A better solution would be to increase their chance to give the disease and reduce their appetite.
