### ISSUE TITLE
Issues and Suggestions

### ISSUE THREAD

**Issue by Fizzler** [skyarkhangel/Hardcore-SK#855]
First off, I'd like to say that I love the mod and the work you and your team/friends do. I admire the effort you all have put into this. I know English isn't probably your first language, so if you don't understand something, let me know and ill try to explain it better. I will be creating more of these if I find more issues or come up with more suggestions as I play the mod pack.

**Issues:**
1. When researching with the queue system, the researcher sometimes skips prerequisite research. For example, Construction II researched BEFORE Construction I, I had to manually hit the research button in order to get support columns because it put construction I at last in the queue. I haven't tested how much you can skip, you may even be able to skip having to need a high tech bench, this needs to be tested.

2. Pawns no longer wake up when they get too hot during heat waves and move to another room to cool off. Had to manually watch all 9 pawns while they slept, waking them up so they'd go chill out instead of dying.

3. Mobile mineral sonar needs to be uninstalled before colonists can reinstall it somewhere else. You can just reinstall, select the new location, then uninstall and the pawn will uninstall and move it, but it just adds an extra step that shouldn't be there. (low priority)

4. Algae is still stacking upwards of 5+ plants on one tile. Right now the highest is about 70+ on one tile. This isn't a huge issue as you can use mass select to select every algae and harvest. (low priority)

5. Random messages saying something like "We have found/struck rare ore deposits" even though these "deposits" are in undiscovered tiles in mountains.

6. Infestations can appear in any area that's in a mountain/hill. I've had an infestation appear at the other end of the map because i broke in a building, they just kept growing and destroying rocks. I've also had an infestation appear inside an undiscovered mountain, the only way to get to them was to dig for a year to get to them. (I haven't had this happen to me on the current build, but have on the older ones.)

7. If you load the game multiple times eventually it will crash. I don't know the exact number, somewhere between 10-15? It always crashes, sometimes creatures/pawns will just be black squares, if they're squares it's a guaranteed crash on the next load. Could it be a memory leak or flaw in the base games code?

8. I saw you updated the code to fix the slow mine extractor animation speeds at higher game-speed, did you also fix the mine extractors to keep them from stalling at the top of the animation and not giving you any resources?

9. I'll get a message saying a wanderer has joined, but no one actually joins.

**Suggestions:**

1. The innocent prisoner debuff needs to be removed or tweaked. There's nothing innocent about someone who just tried to kill us and take our things, my colonists have no reason to be sad. Is it possible to only have this debuff trigger if you capture a guest/wanderer?

2. Guests will give you 100% as long as you have one guest bed. Even if 5 show up and 4 end up sleeping in your freezer and get hypothermia, I've never had a single complaint. (low priority)

3. Add minify back in? Not sure if the developer abandoned it or it was causing too many bugs? It'd be nice to be able to re-install already built machines without losing resources.

4. Stop skills from decaying. There's really no point in having this, maybe keep it for the highest difficulties?

5. Adding the neat stockpile stacks mod so stockpiles don't have 100 stacks of the item when it could just have 1 stack. (low priority)

6. Add text to storage items (skip/pallet etc.) letting the player know how much they hold. Also, it's still more efficient if the item can stack 300+ (ex. coal/iron ore) to build wooden barrels and fill those up rather than building skips. (low priority)
6a. Show what item is in the barrels so when the player double-clicks it will show them how many they have in that area. Right now the barrel's lid closes and it's difficult to tell exactly how much of the resource you have. Maybe just overlay it on top of the barrel's picture? (low priority)
6b. This could be solved if we could get a customizable menu of some kind that would show us how many resources we have. For example, I could set it up to show food, silver, wood, iron, and coal amounts but nothing else. (low priority)

7. Exhausted mines shouldn't just vanish into thin air when their time is up. Perhaps simply make it breakdown, allowing a pawn to carry some supplies over to get it back up and running.

**Comment by freijie** [comment]
Issues
1. may be an issue with fluffy's tech tree mod
6,7 is a core game issues

Suggestions:
1. Its possible, but it was made to increase benefits of having psycho trait. Its the same as harvesting organs from prisoners - (s)he may have tried to kill you but normal people would never be comfortable with this.

2. Hospitality mod issue, post suggestion in it's forum thread.

3. Well there is a hardcore word in mod's name, so... Its possible to add make most items minifi-able without any issues though.

4. There is a mod called Mad Skills that does exactly that, in 3 different flavors. There is some point in this - to force you to make specialized pawns instead of a band of jack-of-all trades with full 20's in every skill after a few years.

5. A vanilla issue. Fluffy made a mod that allows your colonists to merge stacks when they are free. Currently HCSK mod has Pallets that do exactly that - merge several stacks of one type, so use storage furniture when possible to avoid clutter.
6a. Will require full re-work of barrels. 
6b. Some proper GUI for storage would be nice, indeed.
