### ISSUE TITLE
Loss of apparel after cybernetic surgery.

### ISSUE THREAD

**Issue by scubaelement** [skyarkhangel/Hardcore-SK#856]
Hey after you install cybernetic bionic legs or arms on a pawn, any gloves or boots will vanish permanently. They don't drop like they should. Also why can't you attach a cybernetic hand to a cybernetic arm. It's like if you keep one regular arm or leg you can add a foot or hand and keep your boots/gloves. Then if your sole remaining hand or foot gets blown off the apparel is lost permanently. Makes a fully augmented pawn weaker than one with a natural arm and leg just for techno gauntlets and boots, which then has its own weird weakness.

**Comment by skyarkhangel** [comment]
Seems, vanilla bug?

**Comment by scubaelement** [comment]
I'm running Hardcore SK from late December 2016, with a couple extra mods like mad skills added at the bottom. I was wondering, when I try to force equip boots/gloves on a pawn with 2 cybernetic bionic arms/legs it says body part missing. Is it tied to core_sk or one of the other mods in the pack?

**Comment by freijie** [comment]
A vanilla bug, in normal game you usually don`t notice that since there is no gloves/boots.
However it should have been fixed in late february patch for SK. At least it properly fixed limbs for me during surgery tests.

**Comment by scubaelement** [comment]
Thanks for the info.
