### ISSUE TITLE
sunlamp lighting is off by 1 block

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#864]
the sunlamp from stock and the mod pack are both the same stats but due to the sk one being 2 blocks itts throwing off the light radisous indicator by 1 block

https://ludeon.com/forums/index.php?topic=12996.msg324606#msg324606

**Comment by skyarkhangel** [comment]
iam thinking about to remove this heat sunlamp.

**Comment by zachary-foster** [comment]
Yes, I dont use the heater sun lamp since I think of light and temperature as two different goals. Perhaps remove heated sun lamp and make the normal sun lamp give off a little heat, since that is realistic.
