### ISSUE TITLE
Forming caravan with animals causes GUI to disappear I can only Alt F4 etc 

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#866]
Whenever I try to form a caravan with **animals** my entire GUI disappears and the game carries on at 1 speed, and I'm unable to interact with anything the only thing I can do is force the game to close via Alt F4 or some other forced manner.

I've tried it with 2 different type of animals and both yielded the no GUI bug, I've even tried different colonists it always happens whenever I add animals to the caravan. 

Starting a new game and spawning in a few animals or via prepare carefully it still makes my GUI disappear when forming a caravan with animals. It's new world etc, so I'm reasonably certain its not unique to my game but I could be wrong.

Whenever I form the caravan without animals it works entirely fine.

I'm using commit e59467439029dd68ab759f7cf10b64374a078eca a few hours old fresh install.

I just wanted to pawn off the cats I was recently "gifted" I guess cat soup is back on the menu.

![ui works](https://cloud.githubusercontent.com/assets/5264667/25059381/caf075ec-217d-11e7-9659-facdd941e22b.jpg)
![ui disappears](https://cloud.githubusercontent.com/assets/5264667/25059382/cfe38030-217d-11e7-9977-6c3c309b0986.jpg)

**Comment by skyarkhangel** [comment]
Ok. I'll check

**Comment by skyarkhangel** [comment]
What animals in caravan?

**Comment by zakhad** [comment]
European shorthairs I had like  8 or so of them and I also tried with a single ptarmigan hen. both yielded the no GUI.
