### ISSUE TITLE
steam darkness event error

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#878]
reported on steam. causes game to lag so needs prompt looking at. seems game is trying to spawn gear on them

Cannot generate apparel for faction-less pawn Void554305
Verse.Log:Error(String)
RimWorld.PawnApparelGenerator:GenerateStartingApparelFor(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:GenerateGearFor(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:GeneratePawn(PawnGenerationRequest)
Verse.PawnGenerator:GeneratePawn(PawnKindDef, Faction)
SK.Events.Ticker_BVcounter:GenVoid(Pawn, IntVec3, Map)
SK.Events.Ticker_BVcounter:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by skyarkhangel** [comment]
Strange, its not a humanlike.

**Comment by sidfu** [comment]
yeah i looked around in the xml didnt see anything that stood out.
