### ISSUE TITLE
Mine Extractors Don't Display Power Consumption

### ISSUE THREAD

**Issue by thadius856** [skyarkhangel/Hardcore-SK#88]
As the title says, `Mine Extractor`s don't display their 2500W power consumption.

`Advanced Mine Extractor`s do properly show their 4000W power consumption.

XML: `Mods\Core_SK\Defs\ThingDefs\Buildings\Buildings_Production.xml` as defName `Extractor`.

I compared the defs for these two items and can't find any difference to account for this.  It appears to inherit thingClass `SK_RareMiner.Building_Extractor`, but for the life of me I can't find where this is being inherited from. The only matching text I can find anywhere in the whole `Mods` folder is in `Mods\Core_SK\Assemblies\Core_SK.dll`, though I lack the skill to actually read it.

Does anybody know the reason for this bug?

**Comment by skyarkhangel** [comment]
Fixed?

**Comment by skyarkhangel** [comment]
Fixed.
