### ISSUE TITLE
why terminator have bowel movement...?

### ISSUE THREAD

**Issue by caesius90** [skyarkhangel/Hardcore-SK#880]
they are machines activated by small nuclear core. how can and why they have poo poo?

**Comment by skyarkhangel** [comment]
bcs, dubs hygiene mod add to all humanlike his comp...

**Comment by caesius90** [comment]
im asking that thing should be fixed...if cant be, sad...

**Comment by skyarkhangel** [comment]
as a variant, to ask dub add check before inject comps

**Comment by skyarkhangel** [comment]
fixed on a17
