### ISSUE TITLE
No bird skin when butchering

### ISSUE THREAD

**Issue by Kirinya** [skyarkhangel/Hardcore-SK#886]
With master build from April 22, butchering birds does not yield any leather.

This seems to be due to tag "Leatheramount" with value 0 in Races_Animal_Ptarmigan.xml, where all the other birds get their leather definition from.

Setting this to a positive value fixed the problem for me.

**Comment by sidfu** [comment]
far as i know leather from birds was removed. it was left at 0 insstead of a compte remove probaly just incase we needed it in future.

**Comment by Kirinya** [comment]
Thank you, good to know.
