### ISSUE TITLE
CommunityCoreLibrary.CompPowerLowIdleDraw

### ISSUE THREAD

**Issue by pongvin** [skyarkhangel/Hardcore-SK#89]
On loading the game, workbenches draw the maximum amount of power regardless if being used. When a bench is turned off and on again, it will draw only 10% of the power needed always, even when being used.

**Comment by skyarkhangel** [comment]
Ok. I translate this bug to CCL. Bcs, its CCL feature.

**Comment by Jalordon** [comment]
This is still an issue with the new release. Did the CCL team manage anything to fix this issue?

**Comment by skyarkhangel** [comment]
Closed. In CCL  known problem, I am guessing would be fixed in A15.
