### ISSUE TITLE
Animals stealing food

### ISSUE THREAD

**Issue by lordmatiz** [skyarkhangel/Hardcore-SK#895]
I can understand, that my ~4 lol cook  makes so delicious roasted meat that nobody can resist... but when animals (mostly herbivore) travels 1/4 map only to eat some of it when everywhere around they've got grass or anything else... ye it's weird. 
And yes I know I can hide it in building but still.

**Comment by sidfu** [comment]
not a bug its base game behavor. protect your food.

**Comment by skyarkhangel** [comment]
yep, need to add a suggestion for a18.

**Comment by zakhad** [comment]
I find it quite annoying when after trading for food and it  all drops to the ground and the animals you purchased the food off of gets immediately eaten by them.

You want some carrots?! fine that'll be 50 silver, trader unloads carrots on the floor, then the pack animal immediately eats the carrots you just purchased :/
