### ISSUE TITLE
Deadfall Trap Listed Twice

### ISSUE THREAD

**Issue by thadius856** [skyarkhangel/Hardcore-SK#90]
There are two `ThingDefs` for `Deadfall Trap`. They appear to be identical entries.

Bug?

`\Mods\Core\Defs\ThingsDef_Buildings\Buildings_Security.xml:322`
`\Mods\Core\Defs\ThingsDef_Buildings\Buildings_Defenses_SK.xml:375`

**Comment by skyarkhangel** [comment]
Nope. one of them in Core. In defenses_SK it overwrite vanilla.
