### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by jnkyacc** [skyarkhangel/Hardcore-SK#91]
~~1) почему то откатило эти [исправления](https://github.com/skyarkhangel/Hardcore-SK/commit/46299be217047d2a9ad6ff5bd21779d197eecd73)-> тут надо будет скобочку [поправить](https://github.com/skyarkhangel/Hardcore-SK/commit/46299be217047d2a9ad6ff5bd21779d197eecd73#diff-80a48a44363e994a9863ac0e1c14a1acR2987)~~
~~2) [Tailor's Loom](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L1601) по моему это должно называться Tailor's Workbench, а [Tailor's Workbench](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L1810) - Tailor's Loom~~
3) [ElectricCrematorium<](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L3673) - нету кнопки вкл\выкл
4) ради всего святого добавьте в описание [Mending Workbench](https://github.com/skyarkhangel/Hardcore-SK/blob/master/Mods/Core_SK/Defs/ThingDefs_Buildings/Buildings_Production.xml#L1960)  что нужны рем наборы, а то оно ну совершенно не стыкуется с описанием.
5) большинством новых пушек нельзя стрелять в землю.
6) Geothermal heater разрушается через пару секунд, пишет - что то не выдержало. Ошибок нет. 
?) не знаю по адресу или нет, но не отображается дальность стрельбы больше 56 (на станках радиус поиска тоже)
__
хотелось бы сжигать в крематории не стаком в 20(одного материала) а пускай 3(дрова)+7(ниток)+10(кожи)

**Comment by skyarkhangel** [comment]
3) Добавлено.
4) Добавлено.
5) Сделано, теперь можно.
6) Проверьте еще раз, возможно обрушение крыши.
7) Механика игры. Больше 56 радиус н отображается.

**Comment by jnkyacc** [comment]
6) с А13 идет эта проблема. мне кажется что проблема в рестрикшене топ и правых тайлах которые прописаны в коде, либо в том что оно как бы поглощает гейзер.

![screenshot37](https://cloud.githubusercontent.com/assets/20729235/18013989/240e3c04-6bc1-11e6-920e-ab8ad905e71b.png)
если ставишь на заленые тайлы(нижние\левые\можно один нижнийлевый) гейзер смещается к центру хитера, хитер рушится - гейзер появляетя в центре хитера. повторяем н раз и можем двигать не движимое. дорого выходит правда :Р
![screenshot43](https://cloud.githubusercontent.com/assets/20729235/18013998/2ac5cc06-6bc1-11e6-8d50-56554941bf53.png)

**Comment by jnkyacc** [comment]
все починил :)
