### ISSUE TITLE
Medium Heather broken

### ISSUE THREAD

**Issue by Bsonnete** [skyarkhangel/Hardcore-SK#915]
rev 1931
It just dosen't work

> Exception ticking RH_MediumHeater3496965: System.NullReferenceException: Object reference not set to an instance of an object
  at RedistHeat.Building_MediumHeater.Tick () [0x00000] in <filename unknown>:0 
  at Verse.TickList.Tick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()

**Comment by sidfu** [comment]
thats a error from the orginal mod. as we not useing the most updated version of the redistheat due to a nanc error corrpting saves and breakign heating system for now u have to use the small heater to heat rooms till the mod authoer fixes the nanc error

**Comment by Bsonnete** [comment]
Ok, thanks
