### ISSUE TITLE
Кузнечный верстак

### ISSUE THREAD

**Issue by Enfield1** [skyarkhangel/Hardcore-SK#92]
"Кузнечный верстак"(fueled smithy) открывается не после исследования "Плавка" (Smithing), а после исследования "Продвинутая обработка"(Machining).

Файл:
Mods\Core_SK\Defs\ThingDefs_Buildings\Buildings_Production.xml
Блок:
```
<DefName>FueledSmithy</DefName>
```
Текущее значение: 
```
<researchPrerequisites><li>Machining</li></researchPrerequisites>
```
Нужно: 
```
<researchPrerequisites><li>Smithing</li></researchPrerequisites>
```

------------------------------
Также "Верстак боеприпасов"(ammobench) открывается слишком рано, после исследования ОбработкаI (Crafting I).
```
<DefName>AmmoBench</DefName>
....
<researchPrerequisites><li>CraftingI</li></researchPrerequisites>
```
Возможно он должен открываться вместе с оружейным станком, тогда нужно заменить на "SecurityI"

**Comment by skyarkhangel** [comment]
Дерево исследований переделано.
