### ISSUE TITLE
butcher table & chemical laboratory forgetting bills; cybernetic limbs can't wear gloves/boots

### ISSUE THREAD

**Issue by pongvin** [skyarkhangel/Hardcore-SK#93]
Hello!

It seems that the butcher table and the chemical laboratory forgets added bills after a while. I did not experience this on any other workbench.

Cybernetic bionic parts (arm and leg) cannot wear gloves or boots. Have not tested for any other prosthetics.

Thank you for your work!

**Comment by skyarkhangel** [comment]
First- already fixed, as i know.
About the inability to wear glovers/boots with prostheses is something new in last off. updates.

**Comment by xwat** [comment]
+1 for gloves/boots. Applies only when full limb is replaced (arm or leg). Gloves and boots are still weareable if you only replace hands or feet.

**Comment by skyarkhangel** [comment]
Closed.
