### ISSUE TITLE
Issues from the forum thread I baby-sitted all day for you guys ;-p

### ISSUE THREAD

**Issue by kaptain-kavern** [skyarkhangel/Hardcore-SK#94]
[From here](https://ludeon.com/forums/index.php?topic=12996.msg251051#msg251051) : 

> I'm not able to uninstall/miniaturize work stations. Is it intended to be this way or are there plans to make it so that work stations can be miniaturized?
> 
> edit: unrelated note, all tree types can be planted even without the required tree cultivation technology (example, can plant cecropia trees without Tree cultivation 1)
> 
> Smelting 'tin alloy' is also producing copper alloy instead of tin alloy, easy xml fix.

[From here](https://ludeon.com/forums/index.php?topic=12996.msg250517#msg250517) : 

> One question: I've been having my pawns eat berries, but they seem to be getting the debuff for eating something bad. The berries description still says they are good to eat raw, but it doesn't seem to be working out that way. Is this intentional, or a problem?

[From here](https://ludeon.com/forums/index.php?topic=12996.msg250556#msg250556) : 

> - Dried fruits are 1 to 1 about 7x more valuable, 21x more nutritious, and 10x more joyful than non-dried fruits.  10 low value fruits (around 21 silver) + 25 work = 10 dried fruits (140 silver)  is afaik the 2nd most efficient and least difficult way to make a huge chunk of silver, or just feed a large colony with almost no work or land required.  Maybe change dried fruits into 2 resources, 1 as an ingredient and one as a meal made from 5-10 units of dried fruits.  Atm it's a really powerful 1 ingredient self contained meal.
> 
> 
>   - I was wondering why I didn't seem to have any food struggles anymore and found this to be the cause. Yeah, dried fruits are so good right now that they seem either bugged or overpowered. It increases the nutrition from 0.02 to 0.42 per unit. 15 fruit = 15 meals. If it were 15 fruit = 1 meal, then 0.3 nutrition (0.02 x 15) upgrades to 0.42, which seems like it was the intention.
> 
> 
> - Bumpin' this potential bug/oversight, still present. Easy fixed by changing line 965 to 1 in ...\RimWorld\Mods\Core_SK\Defs\RecipeDefs\Recipes_Meals_SK.xml
> 
> edit: in fact the dried fruit is even worse now than it was before. Before it was 15 raw fruit (0.02 x 15 = 0.3 nutition) would give 15 meals ( 0.42 x 15 = 6.3, a 15x gain). Now it's 10 (0.02 x 10 = .2) yielding 10 meals (0.42 x 10 = 4.2 / .2 = 21x gain). Yikes!

**Comment by skyarkhangel** [comment]
I don't know add minified type for workstation's or not... Now, all furniture, accessorities could be able to uninstall/miniaturize.
Tin alloy recipe fixed already.
Ok, need to fix trees research.
Ohh, ok. Some berries could be bad updated. In A14 added new foodtypes (Raw bad, Raw Good).
Ok, iam check dried fruits recipe.

**Comment by kaptain-kavern** [comment]
BTW is that helping you, me doing that ?

I also try to reply to everyone in the forum thread

**Comment by Jalordon** [comment]
I was able to get work stations miniaturized by adding <minifiedDef>MinifiedFurniture</minifiedDef>
to the xml definitions. I don't know if there's a better way to do so.

**Comment by kaptain-kavern** [comment]
You're right. I only know that way too. But i know the new minifications mods use an other way.

But there are way to add the tag into parent def in order to not having to label each and every item. (I wasn't sure but seems @skyarkhangel in fact said I did it)

**Comment by Jalordon** [comment]
Some objects felt like they shouldn't be miniaturized so I had to add to add to each definition to avoid oddities that would have happened by adding it to the parent definition.

On another note, #89 is still an issue. Did the CCL team address this yet?

**Comment by jnk1136** [comment]
>Ohh, ok. Some berries could be bad updated. In A14 added new foodtypes (Raw bad, Raw Good).
Possibly related to this, I've seen pawns eating raw rice and getting the "Ate something nice" buff.

**Comment by jnkyacc** [comment]
> On another note, #89 is still an issue. Did the CCL team address this yet?

https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/issues/107
