### ISSUE TITLE
Mushrooms doesn't seems to grow past 5%

### ISSUE THREAD

**Issue by kaptain-kavern** [skyarkhangel/Hardcore-SK#95]
All the mushrooms I see on the map are stuck to 5% "_growhInt_"

![Stucked shroom](https://i.imgur.com/DeXvreB.jpg)

**Comment by skyarkhangel** [comment]
ok

**Comment by kaptain-kavern** [comment]
I just saw that Brightbells aren't concerned. They grow to 100% as intended

**Comment by skyarkhangel** [comment]
fixed or?

**Comment by kaptain-kavern** [comment]
All mushrooms are stuck at 5% growth like in the screenshot. But i just realized that only Brightbells behave normally (in case it can help).

I just saw you accepted my PR. Want me to try to address some of the issues here ?

**Comment by kaptain-kavern** [comment]
Excuse me. I just saw in commit that is now addressed. I will close the issue. Pardon me
