### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by lex1975** [skyarkhangel/Hardcore-SK#950]
[2017-05-14_075242.zip](https://github.com/skyarkhangel/Hardcore-SK/files/999386/2017-05-14_075242.zip)

**Comment by sidfu** [comment]
that is a out of memory crash. that is a base game issue not the mod packs fault.

**Comment by skyarkhangel** [comment]
Try to less travel. Or sometimes reload game.

**Comment by lex1975** [comment]
I think, Rimworld need to upgrade to 64-bit version
