### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by mora145** [skyarkhangel/Hardcore-SK#952]
Is it possible to add more brightness to these items?

![screenshot_19](https://cloud.githubusercontent.com/assets/25883820/26036601/723d6890-38ae-11e7-93fd-1c4a8d1c13c9.jpg)

![screenshot_20](https://cloud.githubusercontent.com/assets/25883820/26036602/72408db8-38ae-11e7-9c20-9136c6fff0ec.jpg)

@skyarkhangel

**Comment by LEEROU** [comment]
As I know, the color is highly depended on material, meaning that to make theese brighter they'll need to change material color. (No, you can't just make base brighter, because this will cause too bright color when using brighter materials)

**Comment by mora145** [comment]
mmmm... ok. thx!
