### ISSUE TITLE
rus fix

### ISSUE THREAD

**Issue by DesertRain7** [skyarkhangel/Hardcore-SK#976]
Hospitality languages fix

**Comment by DesertRain7** [comment]
Hospitality\Languages\Russian-SK\Keyed

  <ForGuestUse>Для использования гостями</ForGuestUse>
  <GuestBedFormat>Гость {0}</GuestBedFormat>
  <CommandBedSetAsGuestLabel>Для гостей</CommandBedSetAsGuestLabel>
  <CommandBedSetAsGuestDesc>Эта кровать для гостей.</CommandBedSetAsGuestDesc>

 <VisitorsArrivedTitle>Гости из {0} прибыли</VisitorsArrivedTitle>
  <VisitorsArrivedDesc>Они боятся ступать на вашу территорию по следующим причинам:\n{1}\n\nЕсли вы их отошлете, то они останутся в этом районе и вернутся позже.</VisitorsArrivedDesc>
  <VisitorsArrivedAccept>Гарантировать безопасность</VisitorsArrivedAccept>
  <VisitorsArrivedRefuse>Отослать прочь</VisitorsArrivedRefuse>

<RecruitAngerMultiple>{0} расстроил {1} {2}x раз подряд.</RecruitAngerMultiple>

**Comment by FaHT1k** [comment]
Добавлено. Можно закрыть.
