### ISSUE TITLE
Old Crash Landing | Старая версия Crash Landing

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#978]
Yes, new scenario, simillar to that mod is, for sure good. But it lacks the main attribute of Crash Landing mod - simulation of spaceship crash. In the scenario you always spawn with the same resources, and there are only couple of spaceship parts are falling from above, while mod offers more "Realistic" landing, including **random** loot drops from peculiar ship parts (Cargo would drop clothes and resources, kithen would drop food and cryosleep module would drop colonists). As a fan of this mod I really would like to see original Crash Landing in A17 build, as optional choice, when starting a new game.

---------------------------

Да, новый сценарий очень годный, но он не передает главной черны мода - симуляцию крушения корабля. В сценарии вы всегда спавнитесь с одним и тем же набором, и падает только несколько обломков корабля, в то время как мод создает более реалистичное крушение, включая падение **случайного** лута с соответствующих модулей (С грузового будет падать одежда и ресурсы, из продовольственного еда, а из камер криптосна - люди). Как большой фанат этого мода я бы очень хотел увидеть оригинальный Crash Landing в сборке A17, как один из вариантов старта.

**Comment by notfood** [comment]
Crashlanding mod works fine with HardcoreSK with no modifications needed. It's my favorite start as well.
