### ISSUE TITLE
Game crashes to desktop when generating planet for  "Planetary Recon"

### ISSUE THREAD

**Issue by CML1978** [skyarkhangel/Hardcore-SK#990]
Every time

 I try generating a planet for the "Planetary Recon" scenario, it crashes to desktop when generating. Everything else seems to work that I have tried, so it seems to be just that one. Multiple tries, no extra added mods that I'm aware of. 

Pastebin of log is: https://pastebin.com/jfLVLCGY

**Comment by mora145** [comment]
Ram memory?

**Comment by sidfu** [comment]
OOM crash try smaller world/map

0 MB physical memory [0 MB free].

**Comment by CML1978** [comment]
I have 16Gb of ram.... so I seriously doubt it.

**Comment by CML1978** [comment]
Confirmed issue. I never get to the part where I choose map size, just world generation. I tried loading a planetary recon, 30% world size, still crashes to desktop. I also noticed that on "Crashlanded", while i have three pawns during customization, only two show up on the actual game map. One just disappears.

Otherwise the game plays fine on all the other scenarios I have tried. Even on the largest map sizes, no issues. So it is definitely not a RAM issue.

**Comment by sidfu** [comment]
cml rimworld is a 32 bit program so 4gib is max no matter how much ram u have it will never go above 4gb ram use. in fact game crashes hen it hits that cap. your log shows the game had 0 ram to use so it crashed

**Comment by CML1978** [comment]
Fair enough. wasn't aware it was 32 bit. So what does the recon scenario use up that the other scenarios don't? I'm fine playing other scenarios, just wondering why one wouldn't work but the others do...

**Comment by skyarkhangel** [comment]
Fixed
